Charla en Frankfurt. Alemania. 27 de septiembre de 2003.

Es maravilloso volver aquí después de tanto tiempo. Siempre que venía nos reuníamos en un gran hall y así es cómo Sahaja Yoga ha ido creciendo. Para vosotros que sois de Alemania y Austria es muy importante que entendáis que hace tiempo estuvisteis en guerra, pero hoy estáis en la guerra conmigo. Tenemos que luchar contra el mal. Ya sabéis cómo está el mundo. Tenemos que luchar y conseguir librar a la gente de la ignorancia. Sois un gran apoyo, porque tenemos que transformar a los seres humanos, tienen que llegar a ser gente buena y muy rápidamente. Una vez reciban la Realización, el cambio comenzará.

En Inglaterra e Italia lo que están haciendo es dar la Realización por la calle, y con este método, miles de personas se han convertido ahora en almas realizadas. Es algo grande, porque una vez tenéis la Realización, os convertís en el Espíritu, y toda la bondad debería venir a vosotros. Si hay algo malo o algo de maldad en vosotros, desaparecerá. Sahaja Yoga se está extendiendo muy rápido en todas partes y debería ocurrir lo mismo en estos países.

No tenéis ninguna necesidad de luchar ni pelear, porque contáis con la ayuda del Divino, con toda su ayuda. Debéis comprender que tenemos toda su ayuda para transformar a los seres humanos en seres especiales, pues eso es lo que somos.

Estamos ahora aquí porque os quería comunicar que debemos tener un ashram para Sahaja Yoga, y no quisiera que vivieran en él personas que no sean sahaja yoguis. Porque hay personas muy sucias en este mundo, ni os imagináis hasta qué límite pueden llegar con las cosas que hacen. Os pueden dañar, porque no solo son negativas sino que, a veces, también son satánicas e intentarán echar a perder a vuestros niños, vuestras familias... pueden hacer cualquier cosa. Así que no tengáis nada que ver con ellos, manteneos alejados, porque vosotros ahora estáis limpios, y la gente limpia no se mezcla con la gente vulgar. Por lo menos tened este mínimo de sabiduría en vuestra cabeza y no mezcléis Sahaja Yoga con nada más.

Esto es muy importante y os lo vengo diciendo desde hace tiempo, manteneos alejados. Pero a veces la gente no lo hace y luego sufren mucho. Tenemos todo tipo de diablos a nuestro alrededor, todo tipo de fuerzas satánicas actuando con cultos o no sé muy bien con qué; pero no han hecho ningún bien a la gente, ningún bien en absoluto. Ya veis lo que hay hoy día. Todo tipo de disputas, peleas...asesinatos, todo esto está ocurriendo y debéis saber que estamos en uno de los peores Kali yugas. Tenemos que luchar contra este Kali yuga a través de la colectividad. Debemos ser colectivos.

Observad a los niños. Ved lo colectivos que son. Tenéis que amar a toda la gente, a todos los sahaja yoguis que tenéis alrededor. No busquéis sus defectos. No os peleéis con ellos. Porque el trabajo que yo estoy haciendo es muy importante. Estoy intentando transformar a la gente para convertirlos en gente buena, agradable. No se trata de sacar nada de ellos, sino de proporcionarles algo con lo que se puedan transformar en gente buena. Debemos tener gente extremadamente buena y amable. Personas que no odien ni tengan avaricia. Hay gente realmente avariciosa que, en países en los que han podido hacer dinero, han engañado a todo el mundo y se han hecho ricos.

Y por ello sus hijos sufrirán. Mi atención es para todos vosotros, porque podéis ayudarme en esta gran guerra contra el mal. Estas personas son malas por naturaleza e intentarán destruiros, tenéis que entender esto. No dejéis que os manipulen. Y madurad, haceos personas sólidas, porque no habéis venido a esta tierra para acumular cosas, coleccionarlas o algo así, sino para convertiros en sahaja yoguis de gran calibre.

Otra cuestión es que si no sentís gozo en vuestro interior, si no tenéis gozo, daréis problemas a los demás. Así que lo mejor para vosotros es que meditéis, y no criticar o utilizar el cerebro sino meditar. Con la meditación sabréis cómo gozar de Sahaja Yoga y de todo lo demás. Esto es necesario, y la actividad mental debería desaparecer. No intentéis organizar a los demás ni darles conferencias. Haced introspección con vosotros mismos, intentad ver qué hay de malo en vosotros y qué es lo que estáis haciendo mal. No se trata solo de que uno sea pacífico o esté en paz, ni de ser bueno simplemente. Hay que conseguir que los demás lo sean también, que la gente sea buena, que este mundo sea hermoso a través de vuestra ayuda y vuestra atención.

El problema es que la gente se suma muy fácilmente a hacer cosas malas, incluso después de venir a Sahaja Yoga. No apoyéis a nadie así. Al contrario, explicad a esa persona que Sahaja Yoga es una actividad colectiva. No podemos tener nuestro "propio"...de nada. Tenemos que ser activos y estar juntos todo el tiempo. La unión es muy importante y después ved el gozo de esa unión. Si podéis sentir ese gozo que viene de la colectividad, habréis conseguido el propósito de esta vida, porque entonces reuniréis a más gente y les daréis este gozo de ser el Espíritu.

Tan pronto como se convierten en el Espíritu, comienzan a cambiar. Pero si sois colectivos y estáis juntos, hacéis todo lo que hay que hacer, entonces crecéis muchísimo. A aquellos que hablan de separación o separatismo, que tienen estas ideas absurdas, por favor, no les escuchéis. Es mejor que les digáis que tenemos que estar juntos, que no podemos separarnos. Y cualquier cosa de este tipo será destruida. Porque ya veis cómo está el mundo, cómo están las cosas y cómo está funcionando.

Por tanto, para entender la belleza de los tiempos modernos, de que hayáis nacido en estos tiempos, hay que ver que es un tiempo en el que os podéis transformar y podéis llegar a ser el Espíritu. Esto se ha intentado anteriormente, pero nada funcionó. Ahora, con la ayuda de vuestra Kundalini, lo estamos haciendo funcionar. Ahora vosotros sabéis cómo dar la Realización, sabéis todo lo que hay que hacer, cómo comprobar las vibraciones.

Una vez que veis todo esto, os dais cuenta de que estáis haciendo un gran bien a la humanidad. Yo dependo de todos vosotros. Sois gente muy buena y sensata que habéis llegado a Sahaja Yoga. Siempre que yo venía en el pasado habéis estado aquí. Me alegra mucho ver que aquí han venido muchos países. Tan pronto como supisteis que venía, todos habéis expresado vuestro amor por mí viniendo hasta aquí a pesar de que me quedaré tan poco tiempo, es increíble. Que Dios os bendiga.

Y sed responsables, tened claro que sois los responsables de transformar el mundo entero en un mundo de buenas personas, de personas espirituales. Esta es vuestra responsabilidad y ya sabéis lo qué tenéis que hacer en consecuencia. Tenéis que ser muy responsables, no importa el país del que seáis, sois responsables. Intentad ver qué estáis haciendo por Sahaja Yoga.

Veo muchas caras nuevas y me alegra mucho. Antes he estado con la gente de Austria y Alemania, pero veo que hay gente de otros países. Ha sido un gesto muy dulce el que hayáis venido hasta aquí. Lo que es importante es la entrega, lo cual es un problema con la gente. No se pueden entregar a Sahaja Yoga. Pero esa es vuestra vida, es el hermoso río de la bondad. Deberíais intentar entregaros. Si no podéis hacerlo, algo va mal en vosotros. Por favor intentad entregaros y os sorprenderá ver que solo a través de la entrega es cómo se consigue el gozo, la felicidad y la paz.

Esto es muy importante y es lo que he venido a deciros, que por favor, intentéis entregaros. La entrega es...no sé, uno no se puede forzar a sí mismo, pero entrad en conciencia sin pensamientos, meditad y entrad en conciencia sin pensamientos y estoy segura de que -con todo mi amor y mis bendiciones- seguro que conseguiréis la entrega; y no solo eso, sino que obtendréis grandes poderes para transformar a los demás. Todos tenéis este potencial y podéis desarrollarlo. Ved a cuántas personas habéis ayudado a cambiar en la vida.

Muchas gracias.