...Najváženejší sahadža jogíni, sudca Vaidya a jeho milujúca manželka! Pán Bakshi, (...prerušená nahrávka...) Dhumal, pán Gavin Brown, ktorý je archeológom, Dr. Pramila Sharma, ktorá je profesorka hindštiny a majsterka literatúry Kabira a ďalej pani Jane Brown, ktorá je geologičkou z univerzity v Cambridge, a náš podpredseda pán Zachre, tiež láskavá speváčka pani Shobha Gotu, ktorá bola veľmi milá a prišla spievať a v marati povedala: “Matka, nie som schopná urobiť nič iné, len vám zaspievam dva bhadžany.”

Všetci sahadža jogíni, ktorí sem prišli, všetci ľudia, ktorí sa tu k nám pridali na oslavu mojich pozemských narodenín... Som veľmi vďačná, veľmi vďačná a naplnená veľkou radosťou a šťastím. Moje vibrácie prúdia cez moje oči ako slzy, keď vidím, že aj v tejto Kali juge existujú ľudia, ktorí sú vďační Matke, ktorá dáva len niečo také abstraktné, známe ako vibrácie.

V skutočnosti vám nedávam... nemôžem dávať ani brať, budete prekvapení. Len to zo mňa vyžaruje. Je to moja “swabhava” [vrodená povaha]. Musí to tak byť, nemôžem si pomôcť. Je to “bytosť”, ktorá je bytím. Nemôžete z nej urobiť niečo iné.

Koná sama od seba, stále pracuje. Je to mimo mňa, aby som ovládala to, ako vás mám všetkých milovať. Neviem, ako sa ľudia učia nenávidieť. Nemám dosť času ani na to, aby som ľudí milovala. 24 hodín je na to veľmi málo!

Neviem, ako si ľudia sadnú a manipulujú a premýšľajú s chladným pokojom, ako nenávidieť. Nenávisť má len silu deštrukcie - vašej a druhých.

Dnes by som vás požiadala, aby ste stále mysleli na lásku. Láska je všetko poznanie. Poznanie je všetka láska. Nie je nič nad tým. Ak máte poznanie, tak musí prejsť skúškou lásky. Ak niekoho poznáte, tak to vo vás nič nezanecháva, lebo ho poznáte zvonku. Ale ak niekoho milujete, tak toho človeka poznáte skrz-naskrz. Poznáte ho tak dobre, viete o ňom všetko, aký je. Toto poznanie nazývame “para” - poznanie. Takéto poznanie musíme hľadať. Všetky knihy len naznačujú týmto smerom.

Sú míľnikmi, ktoré nám hovoria: “Choď ďalej, choď ďalej.” Neriešia to, ako vstúpiť do Kráľovstva Božieho.

Žiadam vás, aby ste všetci vystúpili na túto úroveň chápania Božského vo vás. Božej lásky, ktorá je vo vás, ktorá sa snaží cez vás pretekať a tešiť sa zmyslom vyžarovania a dávania. Dávanie je najväčšia radosť a potešenie. V dostávaní nie je radosť. A keď dostanete, začnete dávať.

Počuli ste, ako Dhumal hovoril, akú prácu robil v Rahuri. V Rahuri, keď som išla na univerzitu v Rahuri, ľudia z okolitých dedín vedeli, že naše auto tadiaľ pôjde. Sú to obyčajní dedinčania. Nikdy nič o joge nečítali, nerozumejú ničomu, len vibráciám, tým pocitom, ktoré dostanete. Je to subjektívne poznanie. Nemá žiadne slová. Je to subjektívna skúsenosť, ktorú cítite na svojich prstoch, vo vašej bytosti - požehnanie Boha.

A ako som išla, pocítila som v aute trhnutie, lebo pri ceste jednoducho bolo tak veľa ľudí a niektorí stáli pri ceste a zastavovali auto a začali kričať: moje “Džej!” Bola som ohromená! Povedala som: “Ako ste vedeli, že som bola v tom aute?” Povedali: “Matadži, dala si nám vibrácie. Vedeli sme, že toto je to auto, ktoré nám prináša vibrácie. Takže teraz musíš prísť sem dole.” Len som tam zišla a všetkých som objala a naši sahadža jogíni čakali na druhej strane. Povedala som: “Nevadí.” Toto je sahadža - takíto milujúci ľudia! Vtedy som myslela, ak raz s Rámom - ako ste cítili tie veci s ľuďmi, s veľmi jednoduchými ľuďmi, s veľmi jednoduchým srdcom so “Šradhou”, ako mali tieto pocity prijímania vašej lásky a jej cítenie.

Každý na tomto svete potrebuje lásku, nemôžete existovať bez lásky. Celá vaša bytosť je na láske založená. A želám vám všetkým v tejto krajine, aby ste pochopili, že pokiaľ nie je vo vašom srdci láska, nesnažte sa robiť niečo navonok, lebo ak to budete robiť, tak hneď zistíte, že ste mimo. Každý človek rozumie, čo je láska.

Vo vás sa odhráva množstvo vecí. Dnes vo vás nastávajú vesmírne zmeny. Viem, že sa to deje. Samotná Šrí Čakra zostúpila na túto zem a Satja juga už začala. To je dôvod, prečo cítite tieto vibrácie na svojich prstoch a nikto z tých guruov a rišiov a týchto ľudí tieto veci nespomínali. Lebo toto je možné, len keď Šrí Čakra zostúpi. Je tu. Cítili ste to a rozumiete tomu. Všetci to musíte prijať s otvoreným srdcom. Nič od vás nechcem. Čo mi môžete dať? Nič nechcem, chcem len, aby moje deti boli šťastné. Modlím sa za ich šťastie. Žijem pre nich a stále, či spím, alebo som zobudená, alebo v inom stave, ak zavolajú “sabhranta”, tak som s vami. V každom okamihu ste v mojich myšlienkach.

Všetkým vám želám veľmi, veľmi šťastný nový rok lebo dnes je Navroz a Navroz je deň, keď Zaratuštra začal svoju prácu na tomto svete. Bol veľkým sahadža jogínom. Bol inkarnáciou samotného Dattatreyu.

... vám povedal o Mohamedovi Sahibovi. Musím vám povedať, že on bol mojím otcom a bol inkarnáciou samotného Dattatreyu. Nebol obyčajným človekom. Napriek tomu ho ľudia trápili. Mučili ho v každom okamihu jeho života.

A Hazrat Ali je veľmi, veľmi veľká inkarnácia, kedy sa Brahmadeva inkarnoval len jediný raz a inkarnoval sa ako Hazrat Ali. Takže títo ľudia sú tak ohromní! Nemôžete ich kritizovať.

Sú tak ohromní -  každé slovo, ktoré povedali, je mantra. Všetko, čo vám povedali o “namaaz”, nie je nič iné, ako Kundalini “džagruti” [prebudenie].

Mohammed Sahib urobil v Sahadža joge najväčšiu prácu a urobil najväčší pokrok, čo sa týka prebudenia Kundalini. Ako ho môžete kritizovať?

Nedokážem zniesť čo i len slovo proti nemu. Viem, ako veľmi ho trápili.

A dnes sa v tejto krajine narodili tí istí ľudia, ktorí hovoria proti nemu. Ak nesiahate ani po jeho chodidlá, prečo by ste mali urobiť tak veľký krok?

Pochopte to, čo ste v živote urobili? Čo ste dosiahli, že kritizujete tieto veľké osobnosti?

Khwaja Nizamuddin Saheb bol veľký Auliya [svätec] – bezpochyby. A hrozný kráľ ako Khilji sa ho snažil trápiť a on sám bol zavraždený! A jeho meno sa stratilo v prachu. Dnes, Khwaja Nizamuddin Saheb... choďte a vyskúšajte vibrácie! Choďte a vyskúšajte tiež Chisti... Chisti’s Maqbara [hrob] v Ajmer Sharif - uvidíte to isté. V Patne, choďte a vyskúšajte Patna Saheba, kde máte nášho Mahavira Saheba - aj tam sú vibrácie. Hovorím vám, že títo všetci hovorili o tej istej pravde. Dnes ich však môžete rozoznať. Budete vedieť, kto sú.

Prosím, skúste byť pokornými. Najskôr získajte túto večnú pravdu v sebe. Nech je vaša bytosť subjektívnym nástrojom na pochopenie, kto je Boh. Nedajte sa zviesť tým, že si niečo prečítate tu a tam. Nedajte sa zviesť úzkoprsými ideami a egoistickými hlúposťami, ktoré sú všade, ktoré si robia zo všetkých srandu.

Ó, človek! Prosím, prebuď sa pri tejto veľkej príležitosti pochopenia. Táto dynamická sila sa z vás snaží vybublať. Musíme tento svet zmeniť a transformovať ho na nádherné stvorenie, lebo Stvoriteľ nedovolí, aby bolo Jeho stvorenie zničené. Ak neprijmete pravdu, tak budete zničení. Takže vás opäť prosím ako Matka, prijmite Božskú pravdu, Božskú lásku a buďte s ňou zajedno.

Želám vám všetkým, všetkým sahadža jogínom a všetkým ľuďom, ktorí hľadajú Boha, najväčší z najväčšieho, najvyšší z najvyššieho úspechu vo vedomí Boha a jeho lásky. Toto je to, čo je. Inak všetko ostatné je zbytočné. Tí, ktorí hľadali iné satwik alebo tamasik veci v živote, skončili na smetisku. Išli do pekla a sú úplne zničení.

Vy to nechcete. Ste jednoduchí, obyčajní ľudia, a preto ste najlepšími ľuďmi, lebo netrpíte na žiadne extrémy. Máte veľmi jednoduché srdce. Vediete veľmi zbožný život a posvätený manželský život. Toto miesto je pre ľudí, ktorí sú na strednej ceste pána Buddhu. Sahadža joga je spojenie všetkých životných právd a to vám môžem dokázať pomocou Kundalini, že to,  čo hovorím, je pravda - je to tak. Pokiaľ nepoviete meno Hazrat Ali, vaša Swadhistána čakra sa nemôže vyliečiť a toto vedia všetci sahadža jogíni. A pri sahadžajogínskej pudži musíme používať meno Mohameda Sahiba znova a znova a tiež aj meno Hazrat Ali.

A tiež musíme používať meno Pána Ježiša, ktorý je “Ašraya” [útočiskom] pre celý svet, ako opísal Šrí Krišna v Bhagavat Gíte - On bol Mahavišnu. Môžete si to prečítať a budete prekvapení, že tak, ako je opísaný Mahavišnu, je presne to isté, ako bol Ježiš Kristus. Žiadam vás, aby ste neboli tak obmedzení. Doteraz ste nepoznali pravdu. Snažte sa ju pochopiť - buďte subjektívni, cíťte ju, pochopte ju. Všetky knihy hovoria to isté, čo hovorím aj ja. S tým, že to môžem urobiť. Ja to nerobím. Len sa to stane. Prišla som na túto zem práve kvôli tomuto zapáleniu. Toto je posledný bod zapálenia. Toto sa musí stať a stane sa. Pozrime sa, koľkí ľudia v tejto nádhernej Joga Bhumi to prijmú.

Nech vám Boh žehná! Opäť a znova vám žehnám! Teraz, 25., idem do Londýna a dúfam, že všetci, ktorí ste dostali Realizáciu v tieto posledné dva dni, opäť prídete na náš program do Bharathiya Vidya Bhavan v utorok o 6.30. Máme tiež pekné centrum na ulici Altamount. Tu si môžete zobrať adresu, na ulici Altamount je veľmi pekný byt na prízemí, pred kaderníctvom - Kamal kozmetický salón, niečo také. Je to byt slečny Moradži, ktorá nám láskavo poskytla tento byt.

Dúfam, že všetci budete mať hlboký záujem o Sahadža jogu, naučíte sa všetky metódy a ovládnete Kundalini. Medzi nami je veľa ľudí, ktorí to vedia a môžete s nimi hovoriť, dokonca aj na programoch môžete počúvať moje prednášky a tak porozumiete. Ale to nie je porozumenie cez počúvanie, ale je to porozumenie cez vaše srdce a len cez vaše cítenie vibrácií môžete posúdiť Kundalini.

Včera som vás veľmi žiadala a opäť vás žiadam, že na pochopenie Sahadža jogy nepotrebujete príliš veľa rozumu. Potrebujete srdce, “Šraddha-van”, srdce [s vierou]. A ak ho máte, tak to bude fungovať. Nadišiel čas, aby mnohé kvety dozreli v plody. Je tu ten čas.

Opäť vám ďakujem, že mi preukazujete veľkú lásku. Je to ako... keď cítim oceán mojej lásky, keď prúdi k brehom všetkých vašich sŕdc, tak breh ho odrazí späť ako reakciu. Je to parabolický pohyb. Keď moja láska cez vás prechádza a vráti sa mi späť ako láska, teším sa z nej. Je to tak nádherná skúsenosť. Myslím, že je to možno iná skúsenosť, ktorú nemožno vyraziť alebo vložiť do týchto smrteľných slov.

Ďakujem vám znova a znova. Ďakujem všetkým zástupcom a všetkým vám znova a znova.

Nech vám Boh žehná so všetkou svojou prosperitou, so všetkou svojou dobrotou, vľúdnosťou a večnosťou! Paramačajtanja by mala zostúpiť do vášho vedomia.

(potlesk)