Voda života - Water of Life  - Poetická cesta k oceánu, režie Björn Kurt, 27 minut (2007)
Úvodní text na začátku filmu - recitace Victor Vertunni
Kedysi dávno, v dávno zabudnutej krajine, žili ľudia šťastne a v úplnom súlade s prírodou. Vlastnili božský klenot, ktorý ich spájal s ich vnútorným svetlom – Vodu Života! Prešli storočia plné mieru, ale ľudia postupne začali zabúdať na ich klenot a skoro sa stali lakomí a leniví. Bohovia sa na to pozerali s hnevom, pretože tento poklad ponúkli ľudstvu. Tak sa rozhodli, že ho človeku vezmú a ukryjú ho na bezpečnom mieste. Ale kde? Najhlbší oceán, najvyššia hora, dokonca ani mesiac sa im nezdal dosť bezpečný na to, aby ho ľudská chamtivosť nedosiahla. Nakoniec sa Bohovia rozhodli, že ho uložia na mieste, kde by ho zvedaví ľudia mohli hľadať najmenej - v človeku samotnom. Vyzeralo to, že sa tento klenot stratil naveky a celé ľudstvo upadlo do temnoty, ktorá trvala mnoho tisíc rokov. Matka Vesmíru sa pozerala, ako Jej tvorenie trpí počas dlhej temnoty a vedela, že musí začať skoro konať, aby zachránila Jej vlastnú prácu. Ako milujúca matka vedela, že konečne nadišiel čas, aby ľudstvu ponúkla kľúč k tomuto klenotu. A tak sníva večný sen o osvietenej ľudskej bytosti, ktorej v žilách koluje (tečie) Voda Života a ktorá sa nakoniec vracia k svojej skutočnej božskej prirodzenosti.
Z interview s Björnem

Jak vznikla myšlenka natočit podobenství duše a kapky vody formou snímku Water of life? 

Celý príbeh má vlastne dve stránky. Na jednej strane som musel odložiť až dva filmové projekty – hrané filmy pre moju diplomovku na Filmovej Akadémii v Mníchove, kde som študoval réžiu. Ked‘že som musel ukončiť moje štúdium, profesor na mňa naliehal, aby som si našiel námet. Práve v tom období som dostal prácu ako kameraman na tri týždne na Novom Zélande a nápad o filmovaní môjho filmu práve tam bol „nadosah“. Hm, ale čo? Profesorovi som naznačil nejaké nejasné myšlienky o prírodnom dokumente, ktorý poukazuje naanalógiu s našim vnútorným ľudským bytím. Odsúhlasil to nie kvôli tomu, že by to bola výborná myšlienka, ale skôr preto, aby som už konečne dokončil svoju diplomovku. Poprosil som Šrí Mátadží, aby mi dala znamenie a počas našej vianočnej návštevy Slovenska, odkiaľ pochádza moja manželka, sme sa zastavili u jednej rodiny.

Takže teda na tej strane druhej som dostal počas Novoročnej pudže, ktorú sme u nich slávili, vskutku krásne „božské vnuknutie“. Počas meditácie som obdržal číru víziu toho, že vnútorná cesta Kundalíni z muladháry, resp. z posvetnej kosti do sahasráry sa rovná plavbe kvapky vody z ľadového vrcholu hory nadol, cez rôznorodé krajiny až do šíreho oceána, kde sa všetky vody Sveta zjednocujú. Sú tu jasné kvality, ktoré sa zhodujú s našími energetickými centrami. Toto bola tá myšlienka, ktorá všetko začala, potom už všetko zapadalo samo do seba. Počas tohto projektu som mal pocit, že ma úplne riadili sily, ktoré mi veľmi pomáhali dosiahnúť veľmi dôležitú prácu. Samotná práca bola vrcholne príjemná. Ked‘že to bola moja diplomová práca a mal som na jej uskutočnenie len malý rozpočet a pritom som to chcel filmovať na vysoko kvalitný film stredného formátu, mohol som si nárokovať len veľmi malý tím. V základe len mňa samotného a jedného asistenta. Nebol tu žiaden sponzor, žiaden zákazník, nikto, kto by mohol kontrolovať. Mohol som si robiť vyslovene to, čo som „chcel“. Takže táto tvorivá sloboda bola pre nás veľkým „katapultom“ a dala nám krídla pre túto fantastickú prácu. Takáto skúsenosť sa môže prihodiť filmárovi asi len raz za život.

DVD přináší nádherné záběry na přírodu a jasně ukazuje myšlenku autora na podobenství s čakrami, jejich vlastnostmi a matkou Přírodou. Pozorný divák rychle tato podobenství analyzuje např. krásy zelené krajiny – nábhí nebo úzké průrvy ve skalách – ádžňa čakra či rotace vody ve víru – svádhišthána – tvoření. Odkud přišly tyto nápady ?

Keď už má raz človek jasnú štruktúru, potom začne všetko naberať podobu. Tak ako sme povedali, že vrcholom hory je muladhára, tak sa pozrime, aké máme kvality, farby, elementy čakier a potom začneš hľadať podobnosti. Pre muladháru sme chceli nájsť niečo pevné, zemské, nehybné. V swadistáne sme chceli ukázať vírivú silu, aktívny princíp tvorivej sily. Je to ako pripájanie jedného článku k druhému… navodíš myšlienku a veci prichádzajú sami od seba. Zvláštne je to, že tieto – ako ich vtipne volám „downloady“ – príjmy z nebies, sa dejú počas meditácie. Je to skutočné požehnanie a poukazuje to na to, že inšpirácia nie je výtvor vlastného mozgu, ale v skutočnosti pochádza z vyššieho zdroja. Niekedy sme mali len kl‘účové slová. Napr. pre nábí sme vôbec nevedeli, kde máme hl‘adať, až sme doslovne zakopli o rieku s prekrásnymi kapradinami. Toto bol jediný „zamračený“ deň počas nášho filmovania (ináč sme mali plné tri týždne slnečné počasie, čo je na Novom Zélande neuveritelné šťastie). Šťastie sme mali preto, lebo s oblakmi bola zelená farba krásne sýta a svieža. Keby sme mali slnečno, bolo by vidieť iba svetlé okraje listov a čierne tiene kvôli vel‘kému kontrastu, s ktorým sa film nevie vysporiadať. Filmovanie na film bolo vel‘mi dobré rozhodnutie, pretože sme mali ovel‘a širšie možnosti zachytenia detailov a informácií v tieňoch a svetlých častiach, ktoré by sa úplne stratili, keby sme točili na video.

Z interview s Martinou Kurt

Na filmu jsi spolupracovala v horách jako asistent kamery, jak je zřejmé z titulků na konci filmu. Jak jsi k této práci přistupovala a čím tě obohatila? Měli jste s Björnem vždy stejný názor na určitý záběr nebo jsi to vnímala jinak? 

Už od mojej rannej mladosti ma zaujímala fotografia a aj som sa jej dosť aktívne venovala. Toto ma pred niekol‘kými rokmi priviedlo aj k vel‘kej túžbe uplatniť sa nejako v oblasti filmu. Nevedela som presne ako, ale nakoniec to vyriešila Šrí Matadži tým, že mi našla manžela filmára J. A tak som si to mohla hned‘ naostro vyskúšať. Robiť asistenta kamery naozaj nie je až taká hračka, ako som si to predstavovala, hlavne keď sme v tíme dohromady len dvaja. Človek robí nosiča ťažkých kamier a statívov aj na dosť nebezpečných miestach ako sú ľadovce, musí držať nohy zanieteného kameramana, ktorý vidí len svoj záber a vôbec nevníma, že stojí na okraji 200 metrovej priepasti, niekedy sa musí šplhať hore rozmočeným šmykl‘avým zrázom, kedže mu príliv odrezal cestu od auta (počas filmovania sahadžajogínskeho kinospotu vo Francúzsku), ap. Myslím, že niekedy je lepšie nevidieť husárske kúsky, ktoré stvára môj šikovný manžel počas rôznych filmových projektov. Trošku mi to schladilo nadšenie pre profesionálne filmovanie a som si uvedomila, že fotografia je pre mňa o niečo vhodnejšia. Kedže sme filmovali na skutočný negatívny film, mohli sme si zábery pozrieť len cez hl‘adáčik priamo na mieste. Björn je vel‘mi skúsený a v mojich očiach vel‘mi talentovaný filmár, má spolu s manželom tak prežiť aktívny “honeymoon“. Takže jedno s druhým prinieslo dobrodružstvo s romantikou;)

