1 januára 2006
 (Austria)
EGO: OK. Prejdime si to ešte raz.

Kúpiť chlieb, vyvenčiť psa, ísť do čistiarne, kúpiť chlieb, vyvenčiť psa, zbaviť sa myšlienok, kúpiť koláč, ...koláč? A to prišlo odkiaľ? Čokoládový...? Mňam! Nie, nemôžem. Nesmiem! Čokoláda mi napadá pečeň. Keď mám napadnutú pečeň, ľahko sa nahnevám. Keď sa nahnevám, kopnem psa. Prečo by som kopal psa?

Mám problémy so psom? Hm... Značím si: "spraviť introspekciu ohľadom problémov so psom". Ozaj, pes... ...musím kúpiť psie krmivo. Ktovie, ako také krmivo chutí? Vyzerá celkom dobre. Aj psovi chutí... Ako som sa sem dostal? Aha, "značím si"... ...nezabudnúť zbaviť sa myšlienok. A čo som to chcel? Koláč. Áno.

Nie! Z koláča priberiem. ...jeden kúsok? Prečo nie... Nie! Stanem sa závislým a budem len priberať a priberať. A potom zomriem. Kto zaplatí pohreb? Pekár? Ale...veď sa takmer nepoznáme. Preboha, už meškám.

SUPER-EGO: Necítim sa moc dobre... Vonku je taká zima... Išiel by som ešte do postele... Vyzerá tak útulne... Taká teplá a príjemná... Ale...potom zmeškám vlak... ...a prídem neskoro do práce, ako vždy. Ani ma nepozdravia. Určite ma nemajú radi. Budem musieť predstierať, že som chorý. A potom sa budem cítiť vinný. Samozrejme, veď som vinný! Cítim sa previnilo, len keď na to pomyslím. Kiežby som hneď teraz zaspal... Spať... A spať... Celý deň... EGO: Prečo meditujem? Mal by som ísť kúpiť to krmivo, vyvenčiť psa, ísť do čistiarne a.... SUPER-EGO: Je taká zima. Prečo je život taký ťažký?

EGO: Moment. Toto nepôjde. Nemám dosť času. SUPER-EGO: Kiežby som tak mohol žiť na Havaji... Na slnku, pri mori. EGO: Prejdime na plán B. Vyvenčím psa cestou do pekárne. SUPER-EGO: Ale...potom by som sa cítil zle. Cítil by som sa zle, pretože sa cítim dobre. EGO: Predávajú v pekárni aj psie krmivo? Prečo by preboha predávali psie krmivo? Je to pekáreň, pečú tam chlieb!

SUPER-EGO: Možno si nezaslúžim žiť na Havaji. EGO: To znamená, že môj pes bude hladovať. SUPER-EGO: Iba Havajčania si zaslúžia žiť na Havaji. EGO: Potom bude kňučať. SUPER-EGO: Som podvodník. EGO: Potom bude zavýjať. SUPER-EGO: Čo to tu robím? EGO: A potom sa pekár nahnevá a... ...a nepredá mi čokoládový koláč. SUPER-EGO: Nie je nám mizerne? EGO: Ale to je vlastne dobre, nie?

SUPER-EGO: ...zima... EGO: Áno, to je dobre! SUPER-EGO: ...depka... EGO: Naozaj musím začať premýšľať nad meditáciou. EGO: Čo sa to s ňou deje?! Aký má stále problém? "Dúfam, že si sa rozhodol správne." Samozrejme, že som sa rozhodol správne! Ten chlap bol idiot. Zaplať pánboh. JOGÍN: Idiot! EGO: Musel si ho vyhodiť.

Nemal si na výber. JOGÍN: Rozhodne. EGO: Tak načo tie posmešky?! "Je ho škoda." Je ho škoda?! Bol to neschopný blbec. Nevedel si spočítať dve a dve. Vôbec ho nie je škoda. Úplný... JOGÍN: ...idiot! EGO: Ona ťa stále len kritizuje.

Vieš to, nie? JOGÍN: Naozaj? EGO: PREMÝŠĽAJ o tom. SUPER-EGO: Áno...ale... ...možno naozaj mala pravdu? Možno si ho nemal vyhodiť. Chudák... Predstav si to... Príde domov a bude to musieť povedať žene a deťom. (MANŽELKA) Ahoj zlatko. Ako bolo v práci? (MANŽEL) Dnes ma vyhodili. (MANŽELKA) Vyhodili?!

Ale... čo bude s naším domom? Vysťahujú nás. Budeme žiť na ulici. (DETI) Ocko? Čo znamená "vyhodili"? (MANŽEL) Znamená to, že ocko nemá prácu. Žiadna práca, žiadne peniaze. (DETI) Ale ocko, sľúbil si mi bicykel! (MANŽEL) Je mi to ľúto, zlatko. Budeme radi, ak budeme mať tento mesiac čo jesť.

SUPER-EGO: Bože môj... ...cítim sa strašne... Mal som... JOGÍN: ...dať mu ešte šancu. EGO: Nezmysel. Už trikrát si ho napomínal. SUPER-EGO: Ale čo tie úbohé deti? EGO: To nie je tvoj problém. S tým by som vôbec nestrácal čas. SUPER-EGO: "Môj nový bicykel, ocko! Sľúbil si mi ho!" EGO: To dieťa už bicykel má. Jeden už dostalo.

SUPER-EGO: "Ocko! Sľúbil si mi ho!" JOGÍN: NETI! NETI! JOGÍN: Toto nie! Toto nie. EGO: Ehm. Ehm! Pst! Uh uh!

Uh uh uh uh! Uh uh uh! Uh! Uh! Uh uh! Uhhh! Uhhh! Už sa roztápam! Roztápam sa. Rozpúšťam sa!

Pst! Pst! Psssssssssssst! Tak... ako dlho si bol bez myšlienok? JOGÍN: Tri minúty. EGO: Tri minúty? JOGÍN: Minimálne. EGO: Možno aj viac...? JOGÍN: Áno. Päť minút.

Najmenej. EGO: Dosť dobré, čo?! JOGÍN: Áno. Áno. Dosť dobré. EGO: Úplne bez myšlienok? JOGÍN: Jasné. EGO: Ho, ho, ho! Aký jogín! JOGÍN: Ďakujem.

JOGÍN: Myslíš, že som dobrý jogín? EGO: Veľmi dobrý! JOGÍN: Dosť dobrý, aby som bol členom podvýboru? EGO: Podvýboru? PODVÝBORU?! JOGÍN: Členom rady...? EGO: Mysli vo veľkom! JOGÍN: Svetovej rady! EGO: Líder svetovej rady! JOGÍN: Myslíš?

EGO: Rozhodne! Si nepostrádateľný. Kolektív by bol bez teba stratený! Svet by bol bez teba stratený! JOGÍN: Áno, máš pravdu. Som nepostrádateľný! EGO: A vieš čo je na tebe úžasné? JOGÍN: Povedz mi. EGO: Si taký... ...skromný... JOGÍN: Naozaj? EGO: Jeden z najskromnejších jogínov, akého poznám.

JOGÍN: No, keď hovoríš... Wow! Skromný...! EGO: Obdivujem ťa. JOGÍN: Nie, neobdivuješ. EGO: Ale áno! JOGÍN: Nie! EGO: Ale áno! JOGÍN: Nie, neobdivuješ. EGO: Ale áno! JOGÍN: Neobdivuješ!

Poznám tvoju hru! Viem o čo ti ide! Ja nerobím nič... Ja nerobím vôbec nič... EGO: To ti teda ďakujem! JOGÍN: Čo je? EGO: Ja nerobím vôbec nič?! Máš trochu krátku pamäť, nie? JOGÍN: Ako to myslíš? EGO: A kto minulý týždeň uzavrel tú dohodu v práci, čo? Lesná víla? JOGÍN: To nie... EGO: Sedem trpaslíkov?

JOGÍN: Nie... EGO: Ono sa to samo?! JOGÍN: Nie, ja... EGO: Áno! JA! Presne tak. Ja! JA! Ja. Ja, ja, ja, ja, ja, ja, ja, ja, JA! A išlo to to veľmi dobre. Famózne!

JOGÍN: Naozaj? EGO: Myslíš, že niekto iný by bol schopný uzavrieť tú dohodu? Mysliš, že ONA by ju uzavrela? Tá pani "je ho škoda"? Nikdy! Nemožné! Ty si ten muž. JOGÍN: Išlo mi to dobre, že? EGO: Išlo NÁM to dobre. Len tak ďalej, bráško!

ÁNO! EGO: Cigaru? JOGÍN: Neurazí... EGO: Takže... ...kto to teda všetko robí? JOGÍN: Ty! EGO: Bingo! Poďme spolu! Jeden, dva, tri, štyri. Ahoj! ♫ Peter Gabriel - Big Time (pozn. : zvuk chýba) Už idem, som na ceste, zvládnem to.

Ukážem im to. Je to väčšie ako život sám. Budem sa pozerať, ako to rastie. Pochádzam z malého mesta. Myslia tam v malom. Používajú malé slová. Ale ja nie. Ja mám na viac. Vymyslel som to. Budem naťahovať ústa, aby tie veľké slová mohli vyjsť von.

Stúpam vyššie. Idem von. Do mesta. Do veľkého, veľkého mesta. Budem robiť veľký hluk, s veľkými chlapcami. Toľko sa toho naučím. A budem sa modliť k veľkému Bohu. Keď si kľaknem vo veľkom kostole. Užijem si to. Už idem.

Zvládnem to. Bude to zábava, to áno! Užijem si to. ♫ EGO: Hej! Kde je tvoja pozornosť?! Ja sa vrátim! SUPER-EGO: Spomínaš... JOGÍN: Paríž... SUPER-EGO: Paris, ah, oui... Merci, mon chéri... Bol si taký... JOGÍN: Slobodný, bez akýchkoľvek starostí... SUPER-EGO: Slobodný, citlivý... JOGÍN: Mladý... SUPER-EGO: Bol si vtedy skutočným básnikom... Pre lásku by si zomrel... JOGÍN: Bez mihnutia oka! SUPER-EGO: To je také romantické! Kam sa podeli tie časy? JOGÍN: Tie pesničky!

Darara, ratatatata... SUPER-EGO: Je to už tak dávno! JOGÍN: Pätnásť rokov! SUPER-EGO: Spomínaš...? JOGÍN: Ten mesiac... Tá rieka... To šampanské! SUPER-EGO: Jedol si, pil si... JOGÍN: Tancovali sme! SUPER-EGO: Spomínaš na to bistro v tej ulici vľavo? JOGÍN: La cage imaginaire! [Imaginárna klietka] SUPER-EGO: La cage imaginaire! A spomínaš na ten film? JOGÍN: Ako by som mohol zabudnúť?

Jeanne Moreau! SUPER-EGO: Ako chodila v nočnej košeli... V noci... Od Julesa k Jimovi... JOGÍN: Tak smutné...tak skutočné...tak krásne... SUPER-EGO: Bol to tvoj obľúbený film! JOGÍN: Bol to JEJ obľúbený film. SUPER-EGO: Candy... JOGÍN: Candy... SUPER-EGO: Volala sa Candy! JOGÍN: Volala sa Candy... ♫ Candy (cukrík) Volám môjho miláčika 'cukrík' pretože na cukrík som sladký, a cukrík je sladký na mňa. Ona mi rozumie. Môj chápajúci cukrík. A cukrík je stále poruke, keď potrebujem súcit. Prial by som si, aby boli aspoň štyri, aby som ju mohol milovať ešte viac. Vzala mi celé srdce.

Som maškrtný, na môj sladký cukrík. Bude to skrátka úžasné, ten deň, keď si vezmem svoj cukrík, a bude už len moja, celá moja. ♫ EGO: Samozrejme, teraz už si oveľa starší. Žiadne mladé kura. Veru, poriadne si zostarol. JOGÍN: Myslíš? EGO: Ó, áno. JOGÍN: Myslíš, že by som mohol vyzerať tak na 25? EGO: Aj na 22, bez problémov! SUPER-EGO: Možno len trochu farby na vlasy... JOGÍN: Si si istý?

EGO: Samozrejme! Vyzeráš úžasne! JOGÍN: Čo by podľa teba povedala ona, keby ma teraz videla? EGO: Bola by ohromená. Určite. Viedol si si dobre! JOGÍN: Áno. Máš pravdu. EGO: Ja mám vždy mám pravdu, môj milý. EGO: Hej!

Čo to robíš? SUPER-EGO: Medi... tujem... EGO: Takto sa to nerobí! Takto sa to robí. Sleduj. Sleduješ? Takto sa to robí. Vidíš akú mám pozornosť? Je to ľahké. Len prestaň myslieť. Nič to nie je.

To zvládnem. Nie je to žiadna veda! Bol som bez myšlienok? Bol som? Podľa mňa áno! Čo myslíš? Ha? SUPER-EGO: Nechaj ma na pokoji! SUPER-EGO: Hej! EGO: Čo je?

SUPER-EGO: To je moja doména! EGO: To teda nie je. SUPER-EGO: Plač, stonanie, kňučanie, to je moja parketa! Ďakujem veľmi pekne! EGO: Kto povedal? SUPER-EGO: Ja hovorím. EGO: 'JA' hovorím? Prepáčte slečna, ale je tu len jedno 'JA'... ...a to som ja! Ja, ja a ešte raz ja! SUPER-EGO: JA!

EGO: Ja! SUPER-EGO: JA! Ja, ja, ja, ja ja! SUPER-EGO: Ty si vždy takýto! EGO: A už to tu máme znova. "Ty si vždy taký, ty si vždy onaký." Nie som nikdy nijaký! SUPER-EGO: Musí to byť vždy o tebe? Ty, Ty, iba Ty. Nemyslíš na nikoho iného ako na seba!

EGO: Samozrejme, že nemyslím! To nie je moja práca. Som tu, aby som sa postaral o pána Číslo Jeden. SUPER-EGO: Ale čo ja? Čo moje pocity? Už si niekedy, aspoň na jedinú sekundu... ...premýšľal o tom, čo by som mohol cítiť ja? EGO: Nie. SUPER-EGO: Neuveriteľné. Ešte to aj priznáš. EGO: OK, máš to mať.

Áno, priznávam. Som sebecký! Spokojný?! SUPER-EGO: A tebe je to jedno! Je ti to úplne jedno! Ani sa za to nehanbíš! EGO: Sebecké ego, zlé ego, zlé, zlé, zlé! SUPER-EGO: Veľmi vtipné! Tak prečo nejdeš von aj so svojimi ego-kamarátmi a neporozprávate si, akí ste všetci skvelí? EGO: No, určite by to bola väčšia zábava... ...ako byť tu, s tebou!

Cítiť sa mizerne! SUPER-EGO: Možno by si to mal niekedy skúsiť. Zistiť, aký je to pocit. EGO: A kto je potom toto? "Ó, cítim sa tak zle..." "Je to všetko moja vina..." "Som hrozný človek. Nezaslúžim si byť šťastný..." "Asi by som mal rovno skočiť do Dunaja..." SUPER-EGO: Och, ty vždy tak preháňaš! EGO: A ty VŽDY hovoríš, že VŽDY preháňam. SUPER-EGO: Nemáš žiadne city. Si studený ako psí čumák! EGO: Prosím, aspoň raz.

Môžeš aspoň raz prestať vyťahovať minulosť? SUPER-EGO: Stále sa ma snažíš ovládať! EGO: Koho zaujíma, čo som povedal 22. decembra 1957?! SUPER-EGO: Ty ma nemáš rád. Vôbec ma neľúbiš. EGO: Už sa cez to prenes! Začni žiť! SUPER-EGO: To ty ma privádzaš k alkoholu, vieš to? EGO: A ty mňa... ...privádzaš ku kokaínu! Dobrá práca, sestrička!

SUPER-EGO: ♫ Cukrík, volám svojho miláčika cukrík... EGO: ♫ Ja som ale veľký kráľ, hu-ha hu-ha, bolo že nám dobre, bolo že nám dobre, hu-ha hu-ha EGO & SUPER-EGO: ♫ Chanson d'amour... EGO & SUPER-EGO: OK, takýto je plán. Vstať o šiestej. Vyjsť z domu. Bez raňajok. Prísť tam. Získať tú dohodu. Odísť odtiaľ. Zobrať telefón. Skontrolovať plán. Blížiš sa k cieľu?

To je dobre. A ideme ďalej, nemôžeš si dovoliť strácať čas! Ratatataaa... SUPER-EGO: "Ocko, sľúbil si mi bicykel..." EGO: Hej! Už na to všetko zabudni. Ak nemôžeš vystáť teplo, choď preč z kuchyne. SUPER-EGO: Nenávidím sám seba. EGO: Milujem sám seba! SUPER-EGO: Som najhorší. EGO: Som najlepší! SUPER-EGO: Najhorší!

EGO: Najlepší! JOGÍN: ŠAM! SUPER-EGO: Už roky som nikomu nedal realizáciu. JOGÍN: HAM! EGO: Dal som realizáciu už miliónom! Som super-jogín! JOGÍN: ŠAM! SUPER-EGO: Všetko je to moja chyba! EGO: Všetko? Aj globálne otepľovanie?

Terorizmus? Africký dlh? SUPER-EGO: Všetko je to moja chyba... JOGÍN: HAM! EGO: Ona povedala že neviem odpúšťať?! Je to hlupaňa. Stavím sa, že dokážem odpustiť rýchlejšie ako ona. Stavíme sa? Poďme na to! Všetci ideme odpúšťať! Tri, dva, jeden... SUPER-EGO: Mne NIKDY nič nevychádza!

EGO: Ty idiot! SUPER-EGO: Som zbytočný. JOGÍN: Som duch! JOGÍN: Som čistý duch. JOGÍN: Som čistá duchovná bytosť. JOGÍN: Som čistý duch. JOGÍN: Som čistý duch. EGO: Ako dlho sme boli... SUPER-EGO: ...bez myšlienok? EGO: Aspoň... SUPER-EGO: Päť... EGO: Minút... SUPER-EGO: To je... EGO: ...príliš veľa. SUPER-EGO: Príliš málo!

Je to úplne... EGO: ...úžasné! SUPER-EGO: Nemá zmysel... EGO: ...vzdávať sa! Pokračuj... SUPER-EGO: ...v nariekaní! EGO: ...v snažení sa! Buď pozitívny! SUPER-EGO: Realistický! EGO: Optimistický! Pohár spolovice... SUPER-EGO: Prázdny! EGO: Plný! Preteká!

SUPER-EGO: Stále prázdny... JOGÍN: Odovzdávam sa... Odovzdávam sa. Odovzdávam sa. Odovzdávam sa. Odovzdávam sa. DUCH: Dobre deti, hra sa skončila! Zaujmite svoje miesta! Veľký úsmev. Sýýýr! Sýýýýýr!