Programa público: "Del Muladhara al Vacío". Derby, Reino Unido. 10 de julio de 1982.

Doy las gracias a todos los sahaja yoguis de Derbyshire y de Birmingham por darme la oportunidad de hablar a todos los buscadores de este lugar. El que haya buscadores en los tiempos modernos es algo único. Nunca tuvimos buscadores antes, o por lo menos, no tantos. Solía haber gente que buscaba dinero, como hay muchos buscándolo hoy día; otros que iban de país en país, en busca de poder. Y muy pocos eran los que buscaban la dicha, el verdadero gozo de Dios.

La razón es que la consciencia colectiva de los seres humanos quizá les hacía pensar que no eran capaces o quizá necesitaban algo de búsqueda. Pero hoy se da una hermosa combinación, porque hay buscadores muy genuinos que han nacido ahora en esta tierra y son masas. No son uno o dos desperdigados, viviendo en la cima de una montaña o en una cueva e intentando meditar, sino que son muchos los que están "buscando", que se sienten insatisfechos consigo mismos, con lo que tienen, y sienten que debe haber algo más allá. Aquellos que sienten que aún no han encontrado el sentido de su vida, y que aún tienen que encontrar el propósito de ésta, aquellos que sienten que aún tienen que encontrar algo superior a aquello con lo que ahora están, todas estas personas son buscadores no de hoy día, sino de miles de años.

En tiempos de Cristo no había ninguno, diría yo, porque incluso las personas que Él mismo escogió como discípulos fueron, de alguna manera, forzados a ello. Él mismo tuvo que ir a buscarlos y hablarles de su Verdad. Por eso debemos decir que estos son tiempos muy importantes en la historia de la Creación, porque hay muchos buscadores.

Sin embargo, el problema con los buscadores de hoy es que no saben qué están buscando. No tienen ni idea de qué buscar ni cómo buscar ni qué esperar. Entran en un área muy desconocida para ellos, y esta área tan desconocida que están buscando está ahora representada por un montón de personas. Uno dice: "Yo soy quien da las bendiciones", otro dice: "Yo soy quien puede hacerlo".

Naturalmente, así se crea la confusión. Los tiempos modernos son tiempos de confusión, gran confusión. Y cuando esta gran confusión se establece, encontramos a su vez una gran solución, una solución permanente para resolver todos los problemas por fin. Nunca ha habido tal confusión en la mente de los seres humanos como la que hay hoy día, en cuanto a lo que está bien y lo que está mal. Nunca tanto como ahora. Si se decía que algo no estaba bien, lo hacían, aún sabiendo que estaba mal. Si eran buena gente, decían "esto está bien, pues haremos lo que está bien". Sin embargo, en general, aún sabiendo que algo no era correcto, muchos lo hacían.

Pero hoy día nadie sabe lo que está bien y lo que está mal. Aparte de esta cuestión del bien y el mal, hay algo más allá y es que tenéis que conoceros a vosotros mismos. Porque esta consciencia está en nuestro interior. Pero no nos conocemos a nosotros mismos ni conocemos el Absoluto, vivimos en un mundo relativo. De esto todo el mundo parece ser consciente, quizá es algo que está en el subconsciente o en el inconsciente. Pero hay un sentimiento generalizado en todos nosotros de que no sabemos. Es un sentimiento muy honesto y muy sublime, de que debemos saber algo más.

Cuando utilizamos la palabra "saber" hay que ver a qué nos referimos. Si digo, "no conozco Derbyshire, nunca he estado allí". ¿Qué significa? Que no conozco Derbyshire. Pero, ¿qué es lo que no conozco? Puedo leer libros, puedo averiguar toda la historia de Derbyshire. Puedo saber quiénes son los mejores artesanos de porcelana aquí. Puedo descubrir todo sobre su historia. Puedo leerlo todo. Entonces, ¿por qué debería decir que no conozco Derbyshire? Porque aún no he estado allí. No he estado en Derby, no conozco la zona. No he estado en ese lugar. No lo he visitado, no tengo la experiencia de este lugar, por eso no conozco Derby.

Y esta es exactamente la situación, pues no sabemos aún sobre el Divino. Hemos leído y oído de ello. Mucha gente ha escrito sobre el Divino. Tan pronto como hay una inquietud surgen libros y más libros. Se escriben miles y miles de libros. ¿Cuántos son certeros y cuántos no? Es imposible saberlo porque, de hecho, no lo sabemos. Supongamos que alguien dice que Jacob Bedford nació en Derbyshire. Bien, ¿cómo voy a saber si es cierto? No lo sabré hasta que me lo confirme alguien que pertenezca realmente a ese lugar y lo sepa.

De la misma manera, el conocimiento que tenemos sobre el Divino es muy confuso. Pero esto no es conocimiento, nunca es conocimiento. La idea de conocimiento nos viene como respuesta a alguna inquietud o pregunta de tipo racional. Algo que podemos comprender a través de la inteligencia. Pero esta área de la que hablamos, está más allá de la inteligencia, más allá de la lógica. Más allá de todo lo que es limitado, se encuentra el área o espacio de lo ilimitado. Y todos estos espacios ilimitados solo pueden conocerse a través de la experiencia de vuestra consciencia.

Debéis entender que esto es muy delicado: conocer algo a través de la experiencia de vuestra consciencia. No se trata de una experiencia como ver, de repente, una luz y luego decir que eso es una experiencia. Siempre podéis ver una luz, ¿qué hay de grandioso en ello? Mucha gente piensa que ha tenido una gran experiencia por ver alguna luz brillar enfrente de ellos, o algo así. Puede que sean luces o brillos que provengan de algún área así, pero que no son de ninguna utilidad para vosotros. Sin embargo, puede que os hagan sentir que habéis tenido una experiencia especial.

Por tanto, uno debe saber que "ver" no es experimentar. Por ejemplo, un perro ve este micrófono. Pero ¿qué sabe de él? Solo lo ve. La consciencia humana tiene cosas grandiosas en sí misma, comparada con la consciencia de los animales. Por ejemplo, los animales no tienen la consciencia de la belleza ni de la claridad. Los seres humanos la tienen en su interior, la pueden sentir. Pueden sentirla en su sistema nervioso central. Por tanto, todo aquello de lo que sois conscientes debéis sentirlo en vuestro sistema nervioso central. No es algo imaginario, tampoco una discusión de tipo intelectual "sí, sí, ya sé..." No es eso. El conocimiento debe veniros a través de vuestras sensaciones. Igual que yo ahora puedo sentir si esto está frío o caliente. Pero las piedras no sienten nada.

De la misma manera, la sensación os tiene que venir de vuestro sistema nervioso central. Eso significa que vuestra consciencia debe prepararse para ello, debe tener una nueva dimensión. Vuestra consciencia debe obtener una nueva dimensión. Otro tipo de experiencias no tienen ningún sentido en la evolución. En el proceso evolutivo, es la consciencia la que mejora. Recibe cada vez mejores dimensiones. Y estas dimensiones alcanzan su máximo exponente cuando llegáis a ser seres humanos. Es entonces cuando vuestra consciencia está lista para recibir la consciencia del Ser universal, del Ser colectivo, de manera que vosotros mismos os convertís en el Ser colectivo.

Me gustaría hablaros del sistema sutil en nuestro interior y por una cuestión práctica, no deberíais dar por hecho todo lo que os digo pero tampoco deberíais negarlo. Es como entrar en una nueva universidad, escuchamos al profesor e intentamos seguirle. Supongamos que él os propone una hipótesis y vosotros empezáis a juzgarla y ponerla a prueba. Si resulta ser cierta, entonces lo llamáis ley. De la misma manera, deberíamos afrontar este nuevo entendimiento, primero observándolo, no negándolo. Y si resulta ser cierto, entonces tenemos que creerlo. No debería haber una fe ciega en Sahaja Yoga. La fe ciega no ayuda en absoluto. Tampoco debería haber una negación. Si escucháis simplemente con una actitud abierta todo lo que os diga como una hipótesis, no necesitáis aceptarlo como verdad ahora mismo. Pero para mí ha llegado el momento de demostrar lo que es verdad, y la verdad es demostrable.

Ha llegado el momento de demostrar la existencia de Dios. Demostrarlo, y no simplemente daros una conferencia larga sobre el tema o llevaros a juicio o algo así. ¿Cómo voy a demostrarlo? A través de vuestra consciencia. Va a ser una experiencia absoluta de vuestra consciencia, y es que vais a sentir a Dios Todopoderoso.

Ha llegado el momento de demostrar lo que se dice en las escrituras. Ha llegado el momento de demostrar vuestra propia conexión con Dios, vuestra propia relación con Él, con el Ser Primordial, tanto si le llamáis Dios o de otra manera, a Él no le importa. Le llaméis como le llaméis, Dios existe, y ese Dios no es como vosotros le concebís, ni de la manera en la que entendéis o conocéis a Dios. Es Dios tal y como es. Hasta que no le sintáis, no vais a creer en Él. Incluso aunque creáis en Él bajo ciertas circunstancias, es una creencia ciega. Lo cual no tiene ningún sentido para ninguna persona inteligente, y llegará el día en que una persona así denunciará ese tipo de fe ciega.

Dentro de nosotros, como os decía antes, hay todo un sistema sutil que ha venido estableciéndose a lo largo de nuestro ascenso en la consciencia en diferentes niveles. Es como la Historia escrita en nuestro interior. ¿Cómo hemos llegado a seres humanos? Es un proceso dividido en varios niveles. El primero es el nivel del carbono. De la materia muerta pasamos a la vida. Se sitúa al inicio del diagrama, está por debajo de ese gran Poder que reside en nosotros, que habita en el hueso triangular y al que llamamos Kundalini. Este Poder es también descrito en la Biblia como el Árbol de la Vida. "Apareceré ante vosotros como lenguas de fuego". La Biblia, mirándola microscópicamente y con todo el simbolismo que encierra, no se puede explicar a menos que obtengáis una nueva consciencia o digamos, la consciencia vibratoria.

Este poder es el poder del deseo. El poder del deseo último, el único deseo, el deseo real que existe en nuestro interior. Los demás deseos resultan inútiles. Observad los países desarrollados. Han alcanzado riqueza, son ricos, pero no son felices. Los que son más ricos, como Suecia y Suiza, compiten entre ellos. ¿En qué país se suicidan más jóvenes? He oído recientemente que en Suiza son más ricos, pero el número de suicidios entre los jóvenes también es mayor que en Suecia. Aquí es donde debemos entender que la riqueza no era nuestro deseo más genuino y real, porque si lo hubiera sido, al conseguirlo, habríamos llegado a ser personas felices y llenas de dicha. Pero no lo somos.

El principio básico de la economía es que, quizá en algún caso particular, un deseo es saciado, pero en general, nunca son saciables. Lo cual significa que la materia no puede satisfacer vuestros deseos. Por tanto, ¿cuál es el deseo, la búsqueda que uno tiene? Ese deseo está escondido en ese poder y es la búsqueda para llegar a ser Uno con Dios. El Yoga: la Unión con Dios. Lo que llamamos el Bautismo. En el Corán se le llama Pir que significa "nacido por segunda vez". Se ha descrito en distintas lenguas, pero se describe el mismo hecho y está en todas las escrituras. Si intentáis ver lo que significa, os sorprenderéis de que en todas se dice lo mismo.

Puede que alguien diga: "Madre quizá hay otros métodos para todo esto". No los hay. Porque esto se ha venido produciendo durante miles y miles de años, desde que os encontrabais a nivel del carbono, y todo ha sido dispuesto en vuestro interior por la Naturaleza. Es como si alguien dice que una semilla puede germinar de otra manera. No, no hay otra manera. La semilla contiene la prímula, y esta ha de despertar; esa es la única manera. De la misma manera, esto tiene que funcionar en todos vosotros. Este poder debe agitarse en vuestro interior, debe despertar. Si es despertado, se eleva. Ahora bien, ¿qué es este poder? Es el poder de llegar a ser Uno con el Espíritu. Este poder sabe que tiene que llegar a ser Uno con el Divino.

Sabemos que tenemos muchos otros deseos. Uno puede preguntarse: ¿Cómo se relaciona esto con lo demás? Es como si, volviendo al ejemplo de antes, decimos "ven a Derbyshire y conoce a toda esta gente". Venimos recorriendo todo el camino y al final, no nos encontramos con todos vosotros (que sois de Derby). En ese caso, todo mi camino no ha servido de nada, porque al final, no me he encontrado con vosotros. No tiene ningún sentido. De la misma manera, todos los demás deseos son solo para que se cumpla este deseo último de ser Uno con el Divino.

Se pueden decir muchas cosas de la Kundalini. Habré hablado de Ella cientos de veces. Y para saber más de Ella tenéis que venir a Sahaja Yoga. De momento os he explicado lo que es y dónde se sitúa.

El segundo centro, que en el diagrama aparece como tercero, es el poder, es el centro de nuestra búsqueda. Este centro se llama Nabhi y es el que nos aporta nuestra búsqueda. Cuando estamos en el nivel animal, buscamos la comida a través de nuestro estómago. Y os sorprenderá saber que, cuando llegamos a seres humanos, buscamos el dinero también a través del estómago. Puede que nos desviemos un poco aquí y allá, pero incluso también a nuestro Dios lo buscamos a través del estómago. Rodeando el estómago hay un área que debemos cruzar. Esta área es, de hecho, el área de los Maestros. Todos los Maestros Primordiales nacieron en esta área, como Moisés, Sócrates... Hay principalmente 10 Maestros Primordiales que vinieron a esta tierra. Vinieron para darnos una idea de lo que teníamos que hacer en nuestra búsqueda. Básicamente vinieron para enseñarnos cómo equilibrarnos a nosotros mismos con el fin de que pudiéramos ascender.

Todos estos grandes profetas o seres primordiales, que eran maestros, vinieron para informarnos de que, si nos desviamos demasiado hacia el lado izquierdo o hacia el lado derecho, perderemos nuestro "sustento", nuestra condición de ser humano. Como ser humano debéis tener un sustento y este es el centro que despliega gradualmente este sustento, desde el nivel animal más básico, pasando por animales superiores hasta el nivel humano, en el que nos damos cuenta de que este sustento existe dentro de nosotros. Así es cómo vinieron nuestras leyes; los Diez Mandamientos de la Biblia son las diez diferentes cualidades que nos sustentan desde el interior. Son los diez Gurus que vinieron a esta tierra para salvar a los seres humanos de caer fuera del camino del centro, yéndose más hacia el lado izquierdo o al derecho.

El lado izquierdo, como veis aquí, es el lado emocional en nuestro interior. También es el poder del deseo. El lado emocional es el que nos da el subconsciente y en un nivel superior, el subconsciente colectivo. En el lado derecho se encuentra el poder de la acción. Es el deseo puesto en acción, y este poder de acción es el que nos da nuestro sentido de futuro y sustenta nuestras actividades físicas y mentales. Como resultado de todo ello, se desarrolla una entidad en nuestro cerebro llamada ego. Todo el mundo lo tiene. No hay por qué asustarse de él. Cuando se hace algo, uno siente que lo ha hecho él, pero es un mito. Sin embargo, continuamos con el mito porque aún no hemos visto la realidad.

Con el poder del lado izquierdo recibimos la agresión de los demás, en él se encuentra nuestro pasado, y como consecuencia de nuestra actividad emocional, se genera otra entidad, indicada como un globo en el dibujo, llamada superego.

Estas dos entidades se encuentran una frente a otra en la cabeza. Cuando crecemos, la zona de la fontanela, que en la infancia es muy blanda y pulsa constantemente, se calcifica y queda cubierta por completo. Así es cómo desarrolláis vuestra "yoidad" (sentido del yo), así os convertís en el señor "tal o "cual". Desarrolláis vuestra propia libertad. Es la libertad que habéis conseguido de ser el señor X, Y o Z.

Después de conseguir esto, comenzáis a utilizar el segundo centro, el de vuestra creatividad, centro de vuestra acción. Los animales no tienen ningún ego. Si viven con humanos puede que lo desarrollen; si no, no lo tienen en absoluto. Si vosotros hacéis algo que está mal, os sentís mal, os sentís culpables. Los animales nunca se sienten culpables, porque está en su naturaleza el matar a otro animal, está en su naturaleza el comer. Nunca se sienten culpables. Es solo la naturaleza humana la que dice: "¡Oh!, no debería haber dicho eso, no debería haber hecho aquello..." Esto es solo una característica humana, el sentirnos culpables, así como el agredir a otros.

Cuando este segundo centro entra en acción, comenzáis a pensar. Pensáis en el futuro, planificáis. Para pensar necesitáis energía y la obtenéis de las células de la grasa que se encuentra en el estómago. Son transformadas para uso del cerebro. En el proceso de esta transformación, este pobre centro debe trabajar duro. Cada vez que pensáis este centro entra en acción y debe trabajar muy, pero que muy duro. Es su único trabajo, cuidar del suministro de las células grasas.

(Madre pide que apaguen algunas luces)

Este centro al que llamamos Swadishtana, es el que os da vuestro futuro, os da la energía para pensar en vuestro futuro, en vuestros planes. Os da la energía para hacer posible el trabajo físico, el ejercicio físico y, su principal misión es transformar la grasa para uso del cerebro. Si un centro, que tiene que ocuparse de muchas otras cosas, empieza a dedicarse solo a una de ellas, el resto queda desatendido. Como resultado de ello, desarrolláis problemas, porque tiene que atender al hígado, al páncreas, a los riñones, al bazo y, cuando se canaliza su acción en una única dirección o para un único trabajo, queda programado para ello y no puede ocuparse del resto. Así es cómo desarrolláis un hígado en mal estado, diabetes, problemas de riñones, problemas con la tensión y también una enfermedad muy seria, llamada cáncer de sangre.

Sahaja Yoga puede curar todos estos problemas. Solo es algo físico. Los problemas físicos también se pueden curar, porque si este centro se consigue normalizar en cuanto a sus funciones, entonces podéis curar fácilmente todas las enfermedades que provienen de esa hiperactividad, de ese exceso de pensamiento, exceso de imaginación. Es algo muy peligroso estar siempre pensando en el futuro. Por ejemplo, ahora estamos aquí, agradablemente sentados y charlando. Pero si en lugar de eso, estáis pensando "adónde voy a ir mañana, qué voy a hacer cuando llegue a casa, que voy a hacer mañana, qué voy a cocinar, qué voy a comer o cómo haré para coger el tren...", toda esta actitud futurista solo os lleva a desarrollar una personalidad rara.

Os hacéis tan futuristas que olvidáis el pasado. Conocí un señor que llegó incluso a olvidar cómo se llamaba; olvidó el nombre de su padre, de su madre, y para desmayo de su esposa, el nombre de ella también. Ella se echó a llorar diciendo, "¿qué voy a hacer ahora? Lo ha olvidado todo. Vive en el futuro. Solo conoce el futuro". Se le tuvo que hacer retroceder al centro y poco a poco empezó a recordar. Me dijo que el presidente de uno de los consejos de un gran distrito en India..., y continuó "él era..., ay, no, ¡yo soy!" dijo. "Muy, bien", le dije. "Así mucho mejor, ahora estás en ese estado en el que dices "yo soy". Así es, esto es lo que ocurre y lo que le acabará pasando a nuestra sociedad aquí, porque es muy futurista.

Para reducir este problema podéis intentar lo que queráis. Podéis intentarlo, por ejemplo, mostrando fotos del pasado o cosas así, pero eso no va a hacer que regrese este caballo desbocado. Va corriendo muy deprisa. Lo único que lo puede solucionar es el despertar de la Kundalini. Cuando la Kundalini se despierta, ilumina el chakra o centro y el centro mismo reasume su propia forma, su propio comportamiento y su estado normal.

Aparte de eso, tiene un poder dinámico o una manifestación específica, pues este centro cuida de nuestra atención. Al iluminarse el chakra o centro, también la atención se ilumina. Y la atención iluminada se hace dinámica. Por ejemplo, estando aquí sentados, solo con poner la atención en alguien, sin hacer nada, solo poniendo la atención en esa persona, podéis saber a través de vuestros dedos qué problemas tiene. Y puede que se encuentre a mil kilómetros de distancia. Cuando Nixon tenía problemas, dije: "Decidme cómo está Nixon, cómo está él" y me contestaron: "Madre, está fatal". Cristo lo dijo: "Vuestras manos hablarán" y el momento ha llegado. Estas manos, que parecen tan simples, tienen tal integración, están integradas de tal manera, y a su vez, la conexión de los nervios es tan microscópica, que no podemos saber cuánto pueden llegar a decirnos, hasta donde pueden llegar.

Cuando el despertar tiene lugar, comenzáis a sentir las vibraciones a vuestro alrededor, es el Poder Omnipresente que hasta ahora no habíais sentido. Lo sentís a través de vuestros dedos, unos dedos a los que normalmente no les prestamos atención, los utilizamos mal, a veces, hasta los utilizamos para cosas equivocadas. Estos dedos también se iluminan y comenzáis a sentirlos. Y esto es lo que antes os decía, que tenéis que obtener la consciencia, una consciencia iluminada, es la consciencia la que debe manifestarse y así es cómo empezáis a sentir en vuestros dedos "en este hay un problema, en este otro...", así veis dónde está la obstrucción.

Todos los dedos se relacionan con los chakras o centros, siete en la mano izquierda (cinco en los dedos, uno en la base y otro en el centro) y siete en la derecha. La mano izquierda responde a vuestro lado emocional y la derecha a vuestro lado físico, mental o racional. A través de las manos podéis saber cómo está una persona, viendo si lo que os llega de ella es calor, sensación de quemazón, o si los dedos se entumecen o se hacen más pesados. Se establece así una comunicación con el Poder Omnipresente que os informa, os da mensajes. Y los mensajes son tan correctos, que si por ejemplo, cogéis diez niños que sean realizados... Porque actualmente nacen muchos niños que son realizados. No entendemos mucho a los niños, pero en estos tiempos han nacido niños muy especiales porque es el momento, es el tiempo del Juicio Final, tiempo de resurrección. Son tiempos que han sido descritos en todas las escrituras. Por eso ahora nacen personas muy especiales. Pues bien, si a estos diez niños les tapáis los ojos y les preguntáis: "¿Qué problema tiene esta persona que está sentada frente a vosotros?" Todos ellos levantarán el mismo dedo, todos el mismo. Aunque tengan los ojos tapados. O si los ponéis de espaldas a la persona en cuestión, levantarán igualmente el mismo dedo. Los niños en esto son muy sensibles.

Cuando por ejemplo, se meten varios dedos en la boca, a veces lo interpretamos mal. Probablemente debido a Freud, un personaje mediocre que no sabía nada de Dios ni de la vida, y que para él todo es por algo relacionado con el sexo. Él mismo estaba obsesionado con el sexo y quería que todo el mundo lo estuviese igual, no era un ser humano normal. Diga lo que diga este individuo, no tiene nada que ver con el sexo. Lo que ocurre es que los niños sienten realmente este calor en sus dedos, lo sienten y por eso se meten los dedos en la boca. Lo he visto hacer a muchos niños pequeños. Aquí tenemos uno que es de Londres, y otro que es de por aquí, y si les preguntáis por alguien, os dirán inmediatamente dónde tiene una obstrucción, qué chakra está obstruido.

A los niños no les podéis engañar, todos os dirán lo mismo: "esta es la obstrucción". Por tanto vuestra consciencia se ilumina y vuestras manos, que tienen en los dedos las terminaciones del sistema nervioso simpático, os informan. Podemos decir que, en nuestro sistema nervioso central podemos sentir a los demás y a nosotros mismos.

Supongamos que estáis aquí sentados frente a mí y os pregunto: "¿Qué problema tienes tú?" Me diríais: "No sé qué problema tengo, no sé". Pero puede que yo sí que os lo pueda decir. Y después vais al médico y os confirma: "¡Sí, así es!, ¿cómo lo has sabido?" No es necesario que vayáis al médico a haceros todo tipo de pruebas patológicas en las que casi os sacan los dientes, los ojos...y cuando acabáis solo os dicen que sois la persona más sana del mundo. No tenéis que pasar por eso tan horrible, tan frustrante, ni gastar dinero. Simplemente observad vuestras manos y sabréis lo que os pasa.

Los que ya son sahaja yoguis os dirán cómo curar los problemas que tengáis. Ha llegado el momento, son tiempos fantásticos. Con Sahaja Yoga hemos curado a mucha gente con cáncer, con cáncer de sangre. Recientemente, una sahaja yoguini de Nueva York, ha curado a alguien de cáncer de sangre. Era un joven al que le habían dado quince días de vida. Después de venir desde India, pasar por mil penalidades, y gastar un montón de dinero, esto es lo único que pudieron hacer, diagnosticar quince días de vida. Esta gente me llamó y les remití a esta sahaja yoguini de Nueva York. Este joven se llama Raúl, tenía dieciséis años, se le diagnosticó un cáncer de sangre, y no solo se curó sino que vino a Londres a verme y ahora está de vuelta en su casa.

Suena muy increíble que una persona que no es médico, que no tiene nada que ver con la medicina, pueda curar a otros. Mucho más allá de la Medicina está este poder sutil, este Poder del Divino del que todo procede.

Si conseguís convertiros en una persona que posee ese poder o que aprende a manejarlo, podréis curar a quien queráis. No soy yo quien cura a la gente sino mis discípulos. No sé a cuántas personas habrá curado Warren, un sahaja yogui que es médico, y que ha utilizado solo Sahaja Yoga para ello, siendo que este Yoga no es una ciencia médica. Ni él mismo podría contar a cuántos pacientes ha curado.

Todo el sistema va a cambiar. Ahora vosotros os vais a convertir en maestros de vosotros mismos, de vuestros poderes. Todos estos poderes van a emanar de vosotros. Cuando decimos que hay gurus que pueden curar, que pueden detener el crecimiento de una enfermedad y cosas así, pensamos que no es real, que no es posible. "¿Cómo lo vamos a creer? Es una falacia". Pero cuando vosotros mismos veáis todo esto manifestándose, os sorprenderéis.

En cierta ocasión viajaba en barco y le di la Realización al capitán. Ocurrió que alguien de la tripulación entró en la cámara congeladora, quedó atrapado y cogió neumonía. Yo viajaba en ese momento porque mi marido era el presidente de esa compañía, y no me pidieron que bajara a atender a este hombre porque parecía que era pedirme demasiado. Así que, le dije al capitán: "Vale, si no me dejas bajar a mí, baja tú. No llaméis a ningún médico ni mandéis mensaje de emergencia. Simplemente ponle la mano en el pecho cinco minutos, eso es todo." Se curó totalmente de la neumonía. El capitán no podía creerlo, decía: "¿cómo puede ser?" "Así funciona esto, ahora te has convertido en una persona así, asúmelo, acéptalo".

Debéis aceptar este poder que se os da. Como se dice en sánscrito "Virage", "Asumidlo". Es como si os doy un trono y no asumís el poder de ese trono, no creéis en él. Os comportaréis como un mendigo al que se le coloca en un trono y en cuanto vea aparecer gente seguirá extendiendo la mano diciendo "Dame cinco rupias, dame cinco rupias". Hasta que no asumáis estos poderes no os sentiréis seguros, pero los tenéis. Y este es uno de los problemas más difíciles de la mente occidental, en especial, porque no pueden creer que tengan estos poderes. Se les dice, pero insisten, ¿cómo puede ser? ¡Lo es!

Si por ejemplo, lleváis este micrófono a una pequeña aldea y les decís que transmitirá vuestra voz a todo alrededor, o si lleváis un televisor y les decís que podéis ver en él películas, teatro, música...no os van a creer. Dirán: "¡En esta caja..., si parece una simple caja de madera...!" Pero cuando la enchufáis, muestra su poder. De la misma manera, los seres humanos dais por hecho que sucedan muchos pequeños y mundanos sucesos. No sabemos lo especiales que somos, la grandeza que hay en nosotros, cómo nos ha creado Dios, con tanta dificultad, con tanto cuidado, con tanto amor. Todo para un propósito muy especial, y es que quiere otorgaros todos sus poderes. Quiere que entréis en el Reino de Dios y disfrutéis de sus bendiciones y de su amor.

Todo esto es algo que no podemos creer. Estamos tan frustrados, tan descontentos con nosotros mismos, con la sociedad, con todo... Pero no importa, es algo que tiene que ocurrir, solo tenéis que ser conectados a la fuente y funciona, funciona. Ha funcionado con miles y debería funcionar con vosotros. Y todas las ideas o conceptos absurdos que la gente tiene de que se puede pagar por esto..., ¿cómo se puede pagar por algo que es un proceso vivo? ¿Acaso habéis pagado alguna vez por algo así? ¿Habéis pagado alguna vez por obtener un fruto de una flor? ¿Podéis pagarle a la flor diciéndole: "toma una libra, dame un fruto"? ¿Acaso funcionaría? Es tan absurdo como eso. No podéis pagar por un Dios vivo, por la experiencia viva ni por el proceso evolutivo, porque es algo espontáneo, está en nuestro interior, funciona sin más. Pero entendemos todo a través del dinero y por eso somos incapaces de ver o aceptar que esto es gratis. Sin embargo, tenemos muchas cosas gratis pero no entendemos la importancia que estas cosas tienen. Pensamos que si algo es gratuito no puede ser bueno. De hecho, todas las grandes cosas tienen que ser gratuitas, sino, no existiríamos. No viviríais. Si no pudierais respirar, coger el aire sin pagar, no viviríais. A veces ocurre en un avión, por ejemplo, que por lo que sea no se puede respirar y entonces uno valora y ve la importancia de esas cosas gratuitas que, sencillamente, damos por hechas.

Por tanto, debemos entender que el concepto que tenemos de Dios, de alcanzarle, de entrar en contacto con nosotros mismos, es erróneo. Pensamos, por ejemplo, que por hacer una postura invertida, sobre la cabeza, podemos alcanzar a Dios. Si llegáramos a Dios en una postura así, entonces habríamos evolucionado a seres en una postura parecida. También pensamos que podemos llegar a Él haciendo carreras o tomando alimentos específicos, o haciendo cosas determinadas. Esto es un error.

Puede que preguntéis: "Entonces ¿por qué en todas las religiones, las encarnaciones decían no harás esto, no harás aquello...?" Lo dijeron porque estos mandatos o leyes son lo que se requiere para nuestro sustento, para nuestro equilibrio como seres humanos. Perdemos nuestro equilibrio si no cumplimos estas leyes. Necesitamos equilibrio y por eso se nos dijo que no hiciéramos ciertas cosas.

Los seres humanos tienen la capacidad de ir siempre a los extremos. He conocido gente a la que le dices: "Para mejorar este chakra puedes hacer esta postura o asana"; entonces la hacen cien o mil veces al día. Pero yo solo les dije de hacerla de vez en cuando. Una vez a la semana..., pero ellos la hacen cien veces. Nos vamos a los extremos. Y para evitar esto nos dijeron que no hiciéramos algunas cosas. Sin embargo, nuestro ego reacciona y dice: "¿Por qué no?" "¡Pues muy bien, adelante, hazlo!" A los jóvenes les decís: "No fumes", y dirán: "¿Por qué no? Todos mis amigos fuman". Vale, pues fuma, coge cáncer, acaba con un agujero en la garganta para respirar, luego lo perderás también, y la nariz. Acabarás moviéndote como una máquina, mirando a todo el mundo, sin poder hablar, y sin poder vivir como una persona normal. Entonces uno se da cuenta y dice: "¡Dios mío, ojalá no hubiera fumado!"

Pero en Sahaja Yoga nunca decimos: "No fumes," porque la mayoría se irían. Nunca decimos: "No bebas, no hagas..." Solo decimos: "¡Vale, haz eso, vale...!" Pero tan pronto como recibís la Realización, lo acabáis dejando vosotros mismos, porque cuando habéis encontrado lo más sutil, lo más elevado, ya no os preocupáis por estas pequeñas cosas. Todos vuestros malos hábitos desaparecen de forma automática. Yo no tengo que forzaros para ello. Tenéis este poder en vuestro interior que os eleva. Os eleváis como un loto que asciende por su propia fuerza por encima del lodo, y vuestra fragancia llena todo el fango. Os sorprendéis de vosotros mismos. Primero estáis identificados con ese lodo, y pensáis "esto es lo real", pero no. Cuando este loto asciende, extiende sus pétalos y su fragancia es la que le da esa personalidad. Se extiende por todas partes, y eso es lo que os va a ocurrir a todos vosotros. Todos vosotros vais a ser un loto así; un loto que parece escondido e invisible en vuestro interior se va a abrir, y la fragancia de vuestra divinidad se extenderá por todas partes.

Hoy no puedo hablar de todos los chakras porque me alargaría mucho. Como veis, he hablado de tres de ellos, el Muladhara, el Swadishthana y el Nabhi. Mañana hablaré del resto, pero hoy tengo que hablar del Espíritu. Hemos estado diciendo durante miles de años que "tenemos que llegar a ser el Espíritu". Como sabéis, en inglés la palabra "espíritu" se usa para varias cosas, es un término ambiguo. Al alcohol se le llama "spirit", también una alma muerta es un "espíritu". Y para referirnos al Ser Puro, lo que llamamos en sánscrito "Atma", también decimos Espíritu. Aquí solo voy a hablar de ese Espíritu, ese Ser Puro que reside en vuestro interior. Es un Ser desapegado, es el testigo en vuestro interior. Os ve y observa constantemente. Reside en el Corazón en forma de gozo y alegría. Está en el Corazón. Este Espíritu no está en nuestra mente consciente, no está en nuestro sistema nervioso central, no está bajo nuestro control.

Para dar una analogía de todo esto, podemos decir que el lado izquierdo es como el freno y el lado derecho, como el acelerador de un coche. En el coche vamos sentados delante aprendiendo a conducir, pero el Maestro va atrás, viendo todo lo que hacemos. A veces os vais al lado izquierdo, es decir, presionáis el freno; otras aceleráis, cometéis errores, y así aprendéis a conducir. Ese aprendizaje es lo que os da sabiduría, algo que viene del hecho de equilibraros a vosotros mismos. Equilibrarse es lo más importante de todo. Incluso gente con grandes desequilibrios, en Sahaja Yoga se equilibra. Este equilibrio entre el lado izquierdo y el derecho, entre el freno y el acelerador, es lo que os da una posición en la que podéis decir que habéis conseguido la maestría de la conducción. Pero aun así, el Maestro sigue sentado detrás.

Entonces pasáis a convertiros en el Maestro. El Maestro es el Espíritu en vosotros. Os convertís en el Espíritu y comenzáis a observaros a vosotros mismos como conductores. Todo se convierte en una obra de teatro. Os separáis de vosotros mismos, veis cómo todo ocurre frente a vosotros, como una representación en el exterior, y vosotros no formáis parte de ella. Así entráis en el área de vuestro eje central y la periferia pierde el impacto sobre vosotros. Os convertís en una persona silenciosa, dichosa, en paz... Alguien que ve el movimiento de la periferia pero que no está en él. Así es cómo os convertís en el maestro, en el profeta.

Hoy Sahaja Yoga hará profetas a los hombres de Dios que, a su vez, tendrán el poder de hacer a los demás profetas también. Eso es lo que dice William Blake, el gran poeta de este país. Y esto es precisamente lo que hace Sahaja Yoga; él lo predijo hace cien años. Y si venís a Sahaja Yoga os sorprenderéis al ver lo que sois. William Blake habló del Jerusalén de mañana y ese mañana es hoy. No sé si la gente de Inglaterra es consciente, pero este país es el Corazón del Universo, es la parte más importante del Universo y ha de convertirse en Jerusalén. Para ello los ingleses tenéis que salir de la inercia para ver vuestro valor y llegar a ese punto. Tiene que funcionar. De hecho, ya está funcionando en Londres. Por supuesto que no podemos tener mucha gente, porque el plástico se puede producir en máquinas en gran cantidad, pero cuando se trata de algo vivo, lleva tiempo. Ahora bien, cuando madure, estoy segura de que este país se convertirá en el profetizado Jerusalén, el lugar de culto al que la gente tiene que venir a rezar.

Es sorprendente las cosas que están ocurriendo con Sahaja Yoga; las margaritas que no tenían olor en este país tienen ahora gran fragancia. Lo mismo con muchas otras flores de Inglaterra, conocidas precisamente por no tener fragancia, ahora la tienen. Podéis comprobarlo vosotros mismos. Todas estas cosas ocurren a través de la naturaleza, están pasando. Pero, ¿qué pasa con los seres humanos?, ¿dónde están?, ¿qué están haciendo?, ¿dónde se han perdido? Esto es algo muy triste.

Vine a Londres por casualidad, diría yo, o quizá estaba preestablecido. Mi marido fue elegido para este trabajo y tuvo que venir. Esta agencia de las Naciones Unidas solo está ubicada aquí, en Inglaterra, en ningún otro lugar. Excepto la de Inglaterra, no hay en ningún otro lugar otra agencia de las Naciones Unidas para la que mi marido fue elegido, y por eso estoy aquí. De lo contrario, no creo que hubiera venido aquí como Guru, porque no tengo ningún otro interés excepto éste. Y no hubiera venido aquí de otra manera, porque, si no hubiera sido invitada, no habría venido a este país. Pero vine aquí como persona invitada.

Todo funciona. Solo tenéis que resolverlo por vosotros mismos y tenéis que fomentar no solo el dinamismo, la vitalidad; sino que lo más importante es que en este momento estáis situados al borde de la destrucción o de la construcción. Y los ingleses ocupan un lugar muy especial. Tienen que alzarse porque son las células del corazón.

Daré una charla de nuevo mañana. Espero que vengáis y os sintáis cómodos. Perdonad por la voz con la que he hablado. Muchas gracias. Si tenéis alguna pregunta, me gustaría contestarla.

Un yogui explica la pregunta de un buscador: "Dijiste que podías curar después de la Realización. Su problema es que su madre está sorda. ¿Puedes curar este problema de oído?"

Shri Mataji: Bueno, esta pregunta se debe a que piensas que soy una persona que tiene que curar a todo el mundo. Estás tristemente equivocado. Tu curación es un subproducto del despertar de tu Kundalini. Siento que lo hayas entendido así, que estoy aquí para curar a la gente. ¿Igual debería establecerme en un hospital? Lo principal es que tu Kundalini despierte para que te cures. ¿De acuerdo? Si tu madre estuviese aquí, podríamos solucionarlo. Lo más importante que tienes que entender es que Dios tiene un gran sentido común, como nosotros, y a Él solo le interesan las luces como nosotros que harán su trabajo. Gente muy enferma, extremadamente enferma, se puede curar al instante; te sorprenderías si te contara.

Nuestro presidente, el Presidente de India, fue a los Estados Unidos para que lo curasen y no lo consiguieron, así que tuvo que volver a India. Yo fui a verlo como "Señora de...", pero el Alto Comisario le dijo que yo era la "Señora de..." y que había oído mi nombre en India.

Su mujer dijo: "¿Por qué no cura a mi marido?"

Estaba en las últimas y lo estaban preparando para sus ritos hindúes. Puse mi mano en su espalda diez minutos, no os lo vais a creer. Él no había podido dormir -durante días- por el dolor y dijo: "¡Ya no me duele, quiero dormir!"

Se levantó y estaba perfectamente bien. Bajó las escaleras, aunque la gente estaba allí con camillas preparadas, bajó por sí mismo. No podían creérselo. Pero esto ha ocurrido porque él va a servir para el trabajo de Dios.

En nuestra casa, si tenemos bombillas que nunca van a dar luz no nos preocupamos por ellas. Las tiramos a la basura. De la misma forma, el Divino no cura a toda la gente. Cura a miles de personas pero a algunos que están muy enfermos les dice: "Tú pasa por el segundo ciclo, ¿de acuerdo? Vuelve purificado, descansado, y entonces todo funcionará".

Así que, no necesariamente se curarán todos, no necesariamente. Pero muchos se han curado y ha funcionado. Sin embargo, nuestro trabajo principal no es el de curar a las personas. ¡No! Es dar la Realización a la gente y como subproducto, como tú dices, por supuesto, si ella recibe su Realización su sordera se curará. Mucha gente se ha curado de su sordera. No solo de sordera sino que a personas calvas les ha crecido el pelo. Él no tenía nada de pelo en la cabeza cuando acudió a mí. No sabría cómo decirlo,..., que después de la Realización y antes de la Realización es tan increíble lo que ocurre, que deberíais sacaros una foto antes de la Realización y verlo vosotros mismos; y luego miraros después de la Realización. Algunas personas que tenían fotos de antes de la Realización las tiraron. Es diferente, pero lo más importante no es curar sino la Realización; eso es lo más importante.

La edad no es un problema. Ayer en Birmingham le dimos la Realización a un señor que creo que es muy mayor. Así que la edad no importa, la salud no importa, nada de eso. Todos pueden recibirla y deberían tratar de recibirla. ¿De acuerdo? Así que, si le puedes dar la Realización podremos solucionarlo. Pero no prometo nada, ¿de acuerdo? Que Dios te bendiga.

Por supuesto, la Realización la prometo, esto lo prometo. Si tenéis paciencia con vosotros mismos como yo la tengo con vosotros. ¡Debéis tener paciencia! ¿Alguna otra pregunta, por favor?

Un yogui explica la pregunta de un buscador: Tiene un problema en su pecho desde hace cuatro o cinco años. ¿Hay alguna forma de ayudarle?

Shri Mataji: Claro que sí, que podemos ayudarle. Un problema en el pecho, ¿como qué? ¿Un problema respiratorio? ¿Es indio? Asma. ¿Eres indio? ¡Oh, los indios! Se bañan muchísimo. Creen que aún están en India. Cada día se bañan por la mañana y salen a la calle, ¿no es cierto? Eso no debería hacerse. Esto es Inglaterra. Deberíamos bañarnos por la noche. Deberíamos vivir como los ingleses. A los indios les encanta bañarse, ¿sabéis? Se bañan cada día aunque estén a cero o a menos doce grados. Deben bañarse. Es una costumbre que tienen y sin la cual no se encuentran bien, por eso desarrollan [asma] pero, en cualquier caso, curaremos tu asma. ¿De acuerdo? No es tan difícil. Pero uno no debería bañarse demasiado en Inglaterra. Yo os sugeriría que si queréis tomar un baño lo hagáis por la noche como los ingleses, porque el clima es muy traicionero. Porque cuando toméis un baño y salgáis a la calle es seguro que tendréis estos problemas en el pecho. No solo eso, sino también artritis y otras cosas que son consecuencia de esto. Algo así es un descuido en este país; con este clima deberíais tener cuidado.

No quiero decir que debáis posponer el baño para siempre. Lo digo porque también debo mostraros el otro extremo. Pero nos encanta bañarnos, sin duda. La higiene personal es extrema en los indios, extrema. Pero la limpieza general o podéis decir la limpieza colectiva, es mayor aquí. Cortar el césped y cuidar la limpieza de las carreteras estaría mucho mejor. Quiero decir que tenemos que combinar estas cosas. Esto es importante. Tiene solución, ¿de acuerdo? El asma no es un problema tan grande. ¿Qué más?

Un yogui explica la pregunta de un buscador: ¿Cómo funciona esto?

Shri Mataji: Tenemos un centro dentro de nosotros -que es el centro de Shri Rama- en el lado derecho. Lo llamamos Corazón derecho. Y si podemos curar ese centro en ti, estarás bien. ¿De acuerdo? Lo solucionaremos. Te diremos cómo se hace.

Un yogui explica la pregunta de una buscadora: ¿Hace cuántos miles de años que existe el yoga?

Shri Mataji: ¿A qué yoga te refieres? El yoga espontáneo ha estado ahí siempre. Lo que es espontáneo está vivo. Y el proceso viviente siempre ha estado ahí. Así que, no podemos decir cuándo empezó. Lo que podemos decir es cuándo se separó. Cuando Dios y sus poderes se separaron y Dios empezó a verlo todo como un testigo, Dios Todopoderoso y sus poderes empezaron a trabajar. Creó todos los Universos, creó nuestro Universo del cual creó a los seres humanos. Y ahora tienen que volver a ser Uno. La Creación debe conocer a su Creador.

Uno, dos, tres, cuatro, siempre ha habido pocas personas que obtuvieran esta conexión pero hoy son los tiempos de la evolución en masa. Así que, para el crecimiento de la vida no puedes especificar el tiempo. No puedes decir cuándo empezó, hace cuántos años. Pero ahora es el tiempo del florecimiento, cuando muchos han de obtener las bendiciones del yoga. ¿De acuerdo? ¡Gracias!

¿Qué más?

Un yogui explica la pregunta de un buscador: Has hablado de la Kundalini. Es muy difícil despertarla para una persona corriente.

Shri Mataji: ¡Oh! ¿Quién te dijo eso? ¡No es así! Las personas anormales hablan de la Kundalini como si fuese algo anormal porque no saben cómo hacerlo. Es algo facilísimo de hacer si eres una persona con la Realización. Hasta un niño puede hacerlo. Aquella gente que dice que es muy difícil no sabe nada de la Kundalini. No son maestros. ¿Qué es difícil para un maestro? Incluso una persona corriente puede convertirse en maestro, entonces, ¿qué puede ser difícil? Esas personas no son maestros. Son completamente ingenuos, hacedores de dinero, gente inútil. Escriben libros sin saber nada acerca de la Kundalini.

Son personas que te llevan por el camino equivocado. Es lo más fácil de hacer: se moverá bajo vuestra mano, la veréis subir y pulsar en la cabeza. No es difícil en absoluto. Os dije que es lo más vital que ha de ocurrir y todo lo que es vital tiene que ser gratuito y fácil, sahaja.

En India tuvimos a Nanaka, que dijo: "Sahaja samadhi lago. Sahaja samadhi lago". Nadie dijo que fuera difícil.

Kabir nunca dijo eso. Dijo: "Pacho pachiso pakar bulau ek hi dor bandhahu". Juntaré a veinticinco personas y las uniré con el mismo hilo.

Aquellos que tenían autoridad siempre hablaban así. Nadie dijo que fuera difícil. Son solo estas personas que no conocen el trabajo, que no tienen autoridad para hablar así. No les creáis. Es lo más fácil de hacer. Lo veréis por vosotros mismos. Suponiendo que es facilísimo, ¿por qué deberíamos negarlo? Supongamos que tengo un diamante para vosotros gratis, ¿no vendréis a verlo? ¿No lo tomaréis? O vamos a pensar: "Es muy difícil, ¿cómo hacemos?", cuando os digo que es fácil. No tenéis que pagar por ello. ¿De acuerdo?

[Alguien del público dice algo inaudible]

Shri Mataji: ¿Qué es?

[Alguien del público dice algo inaudible]

Shri Mataji: ¡No, eso es correcto! ¡Siéntese, siéntese! ¡Muy bien, muy bien! ¡Siéntese, por favor! Se lo voy a contar. Ese es el método que probó la gente. No funciona de esa forma. Imaginemos que le pasa algo a su coche, ¿de acuerdo? ¿Puede limpiarlo si está sentado dentro del coche? ¿Puede arreglarlo? Tiene que salir de él. Así que, primero tiene que subir la Kundalini. La gente lo ha confundido todo. Incluso en hatha yoga, donde hay ashtangas, lo primero es Ishwar Pranidhana. Lo primero es establecer a Dios, estar en conexión con Dios.

Incluso en el cristianismo primero tenéis que ser bautizados. Por supuesto, es algo artificial, olvidadlo, pero tenéis que ser bautizados. Incluso como hindú se tiene que ser "iniciado" de una forma que se llama Yagnopavita, lo cual se hace a los ocho años. Eso es lo que es la Realización. O Mahoma y toda esa gente, la gente utiliza Sumta (libertad de pensamiento y consciencia), que es lo mismo. Así que, lo primero es que recibáis vuestra Realización. Eso no quiere decir que os convirtáis en maestro. Pero después de que la Kundalini despierte y crezca, llegáis a ser un maestro. Este era el proceso real, pero la gente lo tergiversó. ¿Cómo podéis limpiaros a vosotros mismos si no lo hacéis desde fuera?

Por ejemplo, si mi sari se ensucia, tengo que quitármelo y lavarlo, ¿no es cierto? Por eso es difícil. ¡Eso es! Es la confusión que han creado. No creáis todas esas historias. Si intentáis suprimir vuestro ego, se sentará en vuestra cabeza. Nunca saldrá corriendo. Si intentáis suprimir vuestro superego, tampoco os ayudará nunca. Pero aquí sucede automáticamente y cómo sucede os lo contaré mañana. Al despertar a las deidades dentro de vosotros, todo eso se absorbe. La Kundalini despierta y lo hace. Por último, si queréis que lo confiese, hay algo especial en mí porque puedo hacerlo. Algo debe haber. Si no me crucificáis diré lo que hasta aquí he dicho, no más. Es mejor que lo descubráis, si no lo primero que haréis será crucificarme. Y no quiero que eso suceda más. ¿De acuerdo? Que Dios os bendiga.

¿Sí, hijo mío?

[Alguien del público dice algo inaudible]

Shri Mataji: No hace falta ninguna cirugía para eso. En Sahaja Yoga tenemos técnicas, técnicas divinas con las cuales abrimos nuestro Corazón. La confusión está por otro lado y esta confusión nos mete en problemas. La confusión está en cómo tiene que ser nuestra relación con nosotros mismos, con los demás y con la sociedad. Hay una gran confusión que empezó hace mucho tiempo, cuando se escribieron los smritis. Podríamos decir que cuando se practicaba la religión era justo al revés. Empezamos a hacerlo todo y así es como perdimos nuestra capacidad. La actitud hacia nosotros mismos debería ser la de perfeccionarnos a nosotros mismos. Y esto es algo completamente tiránico. Cuando intenté perfeccionar Sahaja Yoga fui tiránica conmigo misma. La cantidad de trabajo que puedo sacar de este cuerpo y la cantidad de esfuerzo que puedo sacar de este cuerpo, extender toda mi paciencia en su completa longitud, todo eso tuve que trabajarlo. Me refiero a que, normalmente, la gente se siente presionada: "¡Madre, esto es demasiado, no podemos soportarlo!" Lo habéis visto vosotros mismos. Pero tenéis que ser realmente tiránicos para perfeccionaros a vosotros mismos. Esta es la forma en que tenemos que trabajar con nosotros mismos, y con los demás deberíamos tener una relación ideal.

Como cuando, por ejemplo, tenéis un hermano, es vuestro hermano, debería ser un hermano ideal. Si es vuestro padre debería ser ideal. ¡Pero es una confusión tan grande! Cuanto más iluminados os volvéis, por así decirlo, más elevados os volvéis y la confusión es: ¿Quién es vuestra hermana, quién es vuestra madre, quién es vuestro padre? Entonces la relación entre los sahaja yoguis también se confunde. Sois sahaja yoguis, sois todos profetas, debéis respetaros los unos a los otros. Sois todos profetas, habláis la misma lengua. Tenéis que amaros los unos a los otros. No es algo racional, tiene que ocurriros porque la relación tiene que ser establecida, la relación ideal.

Muchas personas se enfadan conmigo: "Madre, tienes demasiada paciencia con los sahaja yoguis." ¡Pero ellos son mis hijos! Tengo que perfeccionarme a mí misma y mi relación con ellos debería ser ideal. Tengo que llevar mi perdón hacia ellos al extremo, para que asciendan. Así que, la relación con los demás debería ser ideal. ¿Sois un padre ideal? ¿Sois una madre ideal? ¿Sois una hermana o un hermano ideal? ¿Sois ciudadanos ideales para con los demás? Pero la sociedad tiene que ser pragmática, la sociedad tiene que funcionar de forma pragmática y el funcionamiento pragmático se da a través del cambio.

Imaginad que hoy dijera que en India no necesitamos ser vegetarianos. En Inglaterra, sí. Todo es pragmático. La sociedad tiene que ser pragmática. Aquí somos pragmáticos para con nosotros mismos, no para con la sociedad sino con nosotros mismos. Todo funciona. "¿Qué hay de malo?" Una mujer que tiene hijos se marcha con otro hombre. "¿Qué hay de malo?" O bien, una mujer que tiene hijos venderá su país por el bien de sus hijos. "¿Qué hay de malo?"

Esta confusión dentro de nosotros crea este problema y así es cómo no sabemos cómo abrirnos a nosotros mismos. Si pudiésemos librarnos de nuestras confusiones, todo podría ir bien. Puede hacerse a través de Sahaja Yoga. Todas estas confusiones fueron creadas por gente mediocre, diría yo. No hay nada malo en las encarnaciones, en los profetas. No ocurre nada malo con su profundidad. Lo que está mal en nosotros es nuestra actitud. Y si podemos usar discriminadamente nuestra actitud hacia nosotros mismos, hacia los demás y hacia la sociedad, todo va a funcionar. Va a ser muy hermoso.

Debido a esta confusión, nuestro Corazón está cerrado. Nos dan miedo los demás. ¿De qué hay que asustarse? La relación es ideal. ¿Qué podemos hacer? Por lo que a ellos respecta, vuestra relación y vuestro corazón son ideales. Lo que hagan no importa. Lo que yo hago por ellos es lo que tiene que ser ideal. Tengo que seguir amándolos, admirándolos, animándolos, apoyándolos y dándoles lo que tengo, se trata de mi relación con ellos. Por ejemplo, una fuente de agua que está bajo la Madre Tierra, ¿pensará en qué clase de árbol está encima, en qué cosas hace? Simplemente le da su fuente, su agua. De la misma manera, porque vosotros sois la fuente la relación tiene que ser ideal. Estas confusiones se han formado y nosotros las hemos aceptado racionalmente. Y esto nos ha llevado a una especie de trampa, y es que nuestros corazones están cerrados. ¿De acuerdo?

Un yogui explica la pregunta de un buscador: ¿Puedes explicarnos la diferencia entre Sahaja Yoga y Kriya Yoga?

Shri Mataji: ¡Oh! En cierto modo es lo mismo o en cierto modo es lo yuxtapuesto. Es como la Realización real o el bautismo real a través del despertar de la Kundalini y el bautismo que dan los curas. Este bautismo y aquel bautismo están en yuxtaposición. De la misma forma, cuando la Kundalini asciende Kriya Yoga tiene lugar en nosotros. Algo entra en kriya, en acción. La acción tiene lugar cuando la Kundalini asciende, es una fuerza tremenda que asciende y es un acontecimiento único para el cual el cuerpo entero está preparado. Y cuando asciende una ola de acción tiene lugar en el cuerpo. Como el movimiento peristáltico que tenemos a la hora de hacer la digestión, así es. Cuando la Kundalini asciende hay una especie de contracción muscular que mantiene la Kundalini arriba y luego se dilata, se abre, y después se contrae. Todo esto tiene lugar automáticamente en nuestro interior. Cuando ponemos el coche en marcha, toda la maquinaria se pone en funcionamiento. De la misma forma, el kriya tiene lugar automáticamente en nuestro interior. El kriya tiene lugar en nosotros en Sahaja Yoga. Todo es subsidiario a Sahaja Yoga, es decir, al Yoga mismo. Pero todas estas cosas tienen lugar en nuestro interior.

Pero, contrariamente, podemos hacer otra cosa: sin poner el coche en marcha, podemos empezar a mover una rueda. Esto es lo que llaman Kriya Yoga. Es lo yuxtapuesto al verdadero Kriya Yoga que es espontáneo, construido dentro de nosotros. No tenéis que hacer nada ya estáis hechos para eso. He visto a gente que se corta la lengua y les cuelga. Gente muy mayor lo importó de alguien que vino de América, un tipo horrible. Se cortan las lenguas y sus lenguas cuelgan. Son personas inútiles. Un doctor se hizo eso, un médico. Imaginaos a un buscador arruinado de esta manera. Pregunté: "¿Por qué? ¿Por qué hacéis eso?" Él dijo: "Se supone que hemos de hacer khechari".

Khechari es cuando os cortáis la lengua, la volvéis hacia atrás e intentáis tocar la parte de atrás con la punta. ¿Podéis imaginároslo? Lo llaman dawedi raveni pranayams, son cosas inútiles. Estas cosas han arruinado el camino de la Kundalini. He visto a la Kundalini lastimada, herida, moviendo su cabeza de un lado para otro. Este es el ego del hombre que piensa: "Puedo hacerlo y lo llevaré hasta cualquier extremo". ¡Olvidadlo! Es tan simple. Es como una luz encendida; una vela encendida puede encender otra vela. Funciona así de fácil. No os hagáis todo este tipo de cosas a vosotros mismos. Si sois un buscador verdadero, ¡olvidadlo! ¡No os arruinéis! No habéis hecho nada para arruinaros a vosotros mismos. Hacen eso porque son fervientes buscadores. Miman su ego: "¡Puedes hacerlo!", así que lo hacen.

En Sahaja Yoga, no tenéis que hacer nada hasta que sois realizados. Como a la gente que no sabe nadar, se les dice: "¡No te muevas, intentaremos llevarte a la orilla!" Así que, se les lleva a la orilla, se les enseña a nadar, a salvar a la gente, y luego salvan a la gente. No tenéis que hacer nada hasta que recibís vuestra Realización y su maestría. Hasta que lleguéis a ser el maestro no tenéis que hacer nada. Primero tenéis que llegar a ser maestros. Lleva muy poco tiempo convertirse en maestro. Es demasiado bueno para creerlo pero es cierto. Todo lo que es perfecto se ve así, ¿no es verdad?

[Alguien del público dice algo inaudible]

Shri Mataji: Sí, ahora hablaremos de los zapatos. Alguna gente incluso discute conmigo: "¿Por qué los zapatos? Así que, es mejor que dé una explicación, si no se levantarán y dirán: "¿Por qué los zapatos?" Estamos muy identificados con los zapatos.

Hoy en día, especialmente en estos tiempos modernos, las suelas de los zapatos no las hacen de piel sino con algo más y los zapatos os aíslan de la Madre Tierra. Y para recibir la ayuda de la Madre Tierra debemos quitarnos los zapatos, pero hasta eso molesta a la gente, ¿os lo imagináis? Sin embargo, si les pedís que se corten las lenguas no les importará.

Quieren que todo sea completamente sahaja. Cuando es sahaja tiene que ser extremadamente sahaja, por eso nos sacamos los zapatos. ¿No es interesante nuestra forma de ser? Es un juego tan hermoso. Quitémonos los zapatos y estemos de buen humor. No hay nada serio en eso.

Sacaos los zapatos, solo eso. Ahora poned vuestras manos hacia mí, por favor, así. Las dos manos. Y cerrad los ojos. ¡Por favor, no mantengáis los ojos abiertos! Esto es importante. Es el mismo Kriya Yoga del que estabais hablando, cuando la Kundalini asciende, toca por primera vez este centro de aquí. Este centro está situado en el quiasma óptico. La pupila se dilata, así que, si vuestros ojos no están cerrados, no ascenderá. Con la hipnosis es justo al revés. Así que, por favor, mantened vuestros ojos cerrados. Y sed amables con vosotros mismos. No os juzguéis a vosotros mismos pensando que sois culpables. Este es el primer mantra que enseñamos a la gente, sobre todo en Occidente donde todo el mundo parece ser culpable de algo, no sé de qué, de algo desconocido. Es algo que se bloquea en este dedo. Por favor, antes de empezar nada, decid en vuestro Corazón: "¡Madre, yo no soy culpable!"

No hay nada por lo que sentirse culpable. Al fin y al cabo, ¿qué culpa podéis tener? ¿Qué mal podéis cometer que no pueda ser envuelto en el Amor de Dios? ¡No os sintáis culpables por nada! Quizá en mi charla haya dicho que no está bien hacer ciertas cosas, pero no importa. A mí no me importa. Sea lo que sea, sé cómo hacer este trabajo. Así que, no os sintáis culpables en absoluto. Simplemente decid: "¡Madre, yo no soy culpable!" Esto es muy importante porque si no este horrible Vishuddhi se bloquea. Con esta culpa desarrolláis espondilitis en el lado izquierdo y todo tipo de problemas. Así que, es mejor que digáis: "¡Madre, yo no soy culpable!" Así de simple: "¡Madre, yo no soy culpable!"

Ahora, cerrad los ojos.

Por favor, no os sintáis culpables, por favor. Decidlo una y otra vez: "¡Madre, yo no soy culpable!"

¡Por favor, no abráis los ojos, no los abráis, por favor!

Por favor, poned vuestra mano derecha, no abráis los ojos y poned vuestra mano derecha en vuestro Corazón. Preguntad en vuestro Corazón: "Madre, ¿soy yo el Espíritu?" Haced la pregunta. Es una pregunta muy simple pero es la que va a estableceros. Hacedla de una forma humilde: "Madre, ¿soy yo el Espíritu?" Por favor, decidlo doce veces.

La respuesta misma os la dará una brisa fresca saliendo de vuestra mano.

[Shri Mataji sopla tres veces en el micrófono]

Ahora poned la mano por encima de vuestra cabeza donde se encuentra el área de la fontanela, donde teníais un hueso muy blando llamado talu. Mirad si hay una brisa fresca saliendo de ahí. Podéis pedírmelo, porque yo no puedo forzaros, así que, tenéis que pedirlo. Tenéis que pedir vuestra Realización, diciendo: "¡Madre, por favor, dame mi Realización!" Yo no puedo forzaros. Vuestra libertad debe ser respetada. Si queréis ir al Infierno podéis ir. O si queréis ir al Cielo también se puede hacer. Así que, por favor, pedidme la Realización. En realidad, yo no la doy, pero así es cómo funciona.