Shri Ganesha Puja. Geneva (Switzerland), 22 Augut 1982.

Czy jest ktoś, kto może tłumaczyć? Dorosła osoba. Możesz tutaj usiąść.

Ale czy on przyszedł? Wiesz, on powinien przyjść na puję. Wszyscy powinni wejść. Rozpocznę, gdy wszyscy tutaj będą. Przejdźcie do przodu. Tu jest miejsce. Ci, którzy mogą siedzieć na podłodze, mogą usiąść z przodu. Wejdźcie. Jak miło! Podoba wam się? Kolor pasuje? Gdzie jest...? W porządku, więc podejdź. Ty będziesz tłumaczyć na francuski a ona na włoski. ...przyszła? Tam jesteś. Kto jeszcze? Dzieci mogą usiąść z przodu – niech dzieci usiądą z przodu. Czwórka dzieci mogłaby przyjść później, kiedy zaczniecie puję. Czy wszyscy już przyszli? Ach! Motocykliści! Świetnie! ...Właśnie, o to chodzi! W porządku.

Najpierw chciałabym wam opowiedzieć o znaczeniu pujy. Są dwa aspekty. Pierwszy to ten, że macie swoje własne bóstwa wewnątrz siebie. I te bóstwa mają być w was obudzone. Bóstwa to różne aspekty jednego Boga. Więc z jednej strony macie bóstwa, czyli aspekty Boga, które są przez cały czas obudzone. A z drugiej strony macie swoje własne bóstwa, które czasami są obudzone, czasami na wpół-obudzone, czasami śpią a czasami są chore.

Więc musicie zastosować dwie metody: jedną żeby zadowolić te bóstwa Boga i poprosić je, aby pobłogosławiły wasze bóstwa lub poprosić, aby obudziły wasze bóstwa. Więc odprawianie pujy oznacza, że kiedy ofiarowujecie cokolwiek co macie do ofiarowania, cokolwiek co ofiarowujecie – jak powiedzmy kwiaty, jeśli chcecie ofiarować Bogu kwiat, nie musicie nic mówić, musicie tylko ofiarować, o tak: “To jest dla Ciebie”. Każdy może zrozumieć ofiarowywanie, to znaczy, że do tego nawet nie musicie mieć języka. Nawet jeśli niewidomy chce wam coś ofiarować, on po prostu może wam to dać, o tak. I ten gest jest wystarczający, żeby każdego przekonać, że on może to ofiarować. Nie musicie nic mówić. Więc teraz, kiedy ofiarowujecie Bogu kwiat, nawet bez mówienia mantry, on jest ofiarowany – w porządku, jest dany. Problem w tym, czy zostanie zaakceptowany czy też nie. Ale teraz, kiedy jesteście zrealizowanymi duszami i coś ofiarowujecie, to zostaje zaakceptowane przez Boga, nawet jeśli nic nie powiecie.

Ale co z jakąś nagrodą, którą za to dostajecie? Po realizacji, jeśli ofiarowujecie cokolwiek Bogu, On to zaakceptuje, ponieważ to pochodzi od zrealizowanej duszy, więc On akceptuje. A więc, w jaki sposób jesteśmy błogosławieni przez Niego, ofiarowując Bogu kwiat? Kiedy nic nie mówicie, tylko ofiarowujecie kwiat, wtedy możecie automatycznie zostać wynagrodzeni wieloma kwiatami w życiu. Lub możecie być – jeśli ofiarowujecie coś materialnego, – możecie być materialnie pobłogosławieni. Albo w subtelniejszy sposób, jeśli coś powiecie, tak jak powiecie ofiarowując coś komuś mówiąc pokornie: “Będę szczęśliwy jeśli to przyjmiesz”, to może przyniesie nawet subtelniejsze rezultaty, które mogą być bardziej rozległe, może znacznie głębsze.

Więc robicie coś symbolicznego, coś co jest samą esencją, zasadą czegoś. Jak kwiaty są – one reprezentują zasadę Matki Ziemi. Więc medytowano nad symbolizmem tych wszystkich rzeczy, jakie możemy ofiarować Bogu i odkryto go. Więc oni używali pięciu rzeczy zwanych panchamruta, tak jak mamy tutaj. Ponieważ, jeśli utraficie w zasadę, to w rzeczywistości utraficie w całość, ponieważ dobro duchowe jest dobrem całkowitym. To nie jest tylko częściowo wasze materialne dobro, albo wasze fizyczne dobro, albo wasze emocjonalne dobro, albo wasze umysłowe dobro; ono jest całkowite, zupełnie zrównoważone w całość.
Kiedy ofiarowujecie te pozostałe rzeczy, jak na przykład, wy nazywacie je akshadas, my tak je nazywamy – a jak wy je nazywacie? Kurkuma. Ryż z kurkumą, widzicie, ta żółta rzecz. Kiedy to ofiarowujecie, wiecie, że żółty kolor jest od Czakry Swadishthan. A ryż jest bardzo drogi wszystkim bogom.

Więc w tym jest trik, ponieważ jest to ludzki trik. Bogowie to lubią, więc oni dodają kurkumę do tego i to oznacza, że “ofiarujemy Tobie ryż zabarwiony na żółto” – to znaczy, “powinieneś nam dać błogosławieństwa naszej kreatywności”. Kiedy to zjecie, popłynie więcej kreatywności i będziemy błogosławieni przez to bóstwo – to jest trik. Widzicie, cała koncepcja pujy, jest trikiem świętych ludzi, w jaki sposób przechytrzyć Boga, aby dał więcej błogosławieństw! Ale cokolwiek jest lubiane przez Boga, musi być pomyślne i święte. Więc ostatecznie to się wypracowuje dla świętości świętych i ich prostych serc.

Puja nie może być celebrowana przez osobę, która nie jest Zrealizowaną Duszą. Osoba, która wygłasza kazanie też musi być Zrealizowaną Duszą, ten, który robi namaz musi być Zrealizowaną Duszą i ten, który się modli musi być Zrealizowaną Duszą. Więc wszystkie używane naczynia muszą być czczone, w sposób odpowiedni dla świętych rzeczy dla rzeczy szanowanych. Nie możecie używać, powiedzmy, tych samych rzeczy do łazienki a potem do pujy, to absurd.

Trzy rzeczy są bardzo ważne, to jest ghatah, co oznacza naczynie, naczynie, które zawiera Kundalini, naczynie, które zawiera nasze wewnętrzne pierwotne pragnienie dotarcia do Boga, nasze pragnienie musi być najpierw czczone. To jest ghatah, stworzone tutaj. A na górze zwane jest jako shripala. Shripala oznacza, że to również zawiera w sobie wodę, widzicie, tak jak ten kokos zawiera, on jest, on reprezentuje, kokos reprezentuje to samo. W subtelnej postaci to jest woda ze wszystkich rzek świata, rzek. I kokos jest wodą wszystkich oceanów. Woda z oceanu lub morza wznosi się przez pień palmy kokosowej i staje się słodką wodą w kokosie. To jest coś symbolicznego. Więc to naczynie nazywa się ghatah-puja, to jest ghatah-puja.

Dzisiaj nie chcę wchodzić w szczegóły, ponieważ mamy mówić o Ganeshy. Tak samo – więc to jest woda, w porządku. Potem musimy czcić mantrę i shankar, obie reprezentują dźwięk. Muszla. W rzeczywistości shankar, reprezentuje eter. Potem mamy deepa, co to oznacza? To jest światło, reprezentuje element światła, nazywany tejas. Zazwyczaj także dają Bogini wachlarz, który reprezentuje element powietrza.

W ten sposób, przez ich użycie, od razu zadowolimy wszystkie pięć elementów. Więc one, ich esencje lub przyczynowe esencje tych pięciu elementów powinny być zadowalane w tym czasie, powinny wspierać puję.

Istnieją też wszelkiego rodzaju inne rzeczy, takie jak rodzinne bóstwa: może w waszej rodzinie czczono jakieś bóstwa. One także nie powinny przeszkadzać podczas pujy; to samo dotyczy duchów przodków. Wszystkie te rzeczy trzeba wyciszyć, trzeba im powiedzieć, że to jest puja i że teraz nie wolno nam przeszkadzać. To znaczy, że nawet myśli nie powinny się pojawiać, ich myśli lub zakłócenia z ich strony. Więc wszystko trzeba przekształcić w spokój.

Powiedziałam wam w skrócie o tym jednym aspekcie, ponieważ to jest bardzo rozległy temat. Jeśli miałabym o tym mówić, musiałabym wygłosić trzy wykłady po trzy godziny każdy i jeszcze mogłabym nie skończyć.

Teraz doszliśmy do drugiego aspektu, o który was pytałam – w jaki, w jaki sposób możecie odnieść z tego korzyść? Więc poza tą techniką, aby osiągnąć najlepszy efekt błogosławieństw lub najlepszy przepływ Łaski wewnątrz nas, mówimy mantry. Dźwięk mantr, dźwięk, dźwięk odbija się echem w istocie Boga. A one ponownie odbijają się echem w naszych czakrach i wtedy czakry zaczynają bardziej się otwierać. Więc otrzymujemy przepływ Łaski Boga. Ale tylko zrealizowana dusza powinna mówić mantrę. Bowiem jak bez połączenia ona ma dotrzeć do Boga? To błędne koło.

Ktoś może powiedzieć: “Matko, nie można otrzymać Realizacji, dopóki nie otrzyma się Łaski Boga. I czakry nie zostaną otwarte przez osobę, która nie jest Zrealizowaną Duszą. A bez otwierania czakr nie można otrzymać Realizacji”. W ten oto sposób przejawia się gra Matki i wszystkich świętych takich jak wy. Powiedziałabym, że Sahaja yogini muszą przerwać to błędne koło. Musicie sami podnieść Kundalini. I kiedy podnosicie Kundalini, Kundalini trochę otwiera czakry, ponieważ daliście czakrom swoje wibracje. Kiedy Ona wie, że to Sahaja yogin stoi za poszukiwaczem, Ona się unosi. Ona wie, że jesteście Jej braćmi i siostrami, że należycie do tej samej rodziny co Ona. Widzicie, Ona zna grunt na jakim ma wzrastać, więc ona może to poczuć i wtedy Ona wznosi się w swej godności. Oto jak Ona przerywa to błędne koło.

Dlatego właśnie na początku nie mówimy im o mantrach, ponieważ w mantrach musicie zaakceptować Mnie jako Bóstwo. W czasie Mojego adwentu rozpoznanie Mnie jest obowiązkowe; ponieważ jest to bardzo niepewny, jak my to nazywamy, Czas Zmartwychwstania albo czas waszego Sądu Ostatecznego. Najpierw musi być dana Realizacja bez jakiegokolwiek rozpoznania. Ale nie tym, którzy zaprzeczają lub ubliżają Mi. W żadnym wypadku oni nie mogą otrzymać Realizacji, czegokolwiek byście nie próbowali. Nawet jeśli po Realizacji ludzie zaczną mieć myśli przeciwko Mnie, wibracje się zatrzymają z powodu Sahasrary. A serce musi być w zupełnej zgodzie ze Mną, w przeciwnym wypadku Sahasrara będzie zamknięta.

Widzicie, ludzie którzy są prości i mają w pełni otwarte serca, tacy ludzie rozumieją Mnie bardzo dobrze i po prostu umieszczają Mnie w swoich sercach. Po Realizacji, po przejściu przez zrozumienie Sahaja Yogi poprzez ich aktywność umysłową, również intelektualiści Mnie zrozumieją i rozpoznają Mnie, choć w trochę okrężny sposób. Po pujy, kiedy otrzymują błogosławieństwa w postaci osiągnięcia stanu błogości, wtedy też uświadamiają sobie wartość pujy – później.

W Indiach, gdzie zwyczaj celebrowania pujy należy do tradycji i bardzo go pielęgnowano, oni rozumieją to, bez żadnych procesów myślowych. Ale kiedy spotkają jakiegoś intelektualistę, który stał się Sahaja yoginem, widzicie, oni nie potrafią ich zrozumieć. Nie chcą o tym słyszeć, o tej całej kotłowaninie w mózgu. A ci, którzy próbują – widzicie, ci trochę pod wpływem zachodu, oni próbują, widzicie; rozwijają kompleks niższości i schodzą na lewą stronę.

Ale nie ma potrzeby, żeby rozumieć to mentalnie, mam na myśli, żeby cały czas analizować poprzez wasz proces myślowy a następnie wszystko zrozumieć, po czym stać się Sahaja yoginami o otwartym sercu – to raczej bardzo okrężna droga. Ale cóż zrobić? Poszli tą drogą, więc muszą tą drogą iść. Ponieważ nawet jeśli zostaną Sahaja yoginami, zaczną wątpić i myśleć o tym, martwić się tym. Tak więc fałszywi ludzie po prostu ich hipnotyzują i czerpią z tego korzyści.

Więc nie należy czuć się źle. Jeśli macie, jeśli czujecie, że macie analizować to proszę bardzo, róbcie to, ponieważ Ja nie mogę zatrzymać waszej prędkości, nie zamierzam was hipnotyzować. W Sahaja Yodze ma być szanowana wolność. Ale nie pozwalamy przychodzić na puję ludziom, którzy nie osiągnęli pewnej dozy mentalnego zrozumienia Sahaja Yogi – ludziom z Zachodu, nie z Indii, tutaj istnieje ograniczenie. Ponieważ przypuśćmy, że w Indiach nie wyjaśnię im, oni i tak nie chcą wiedzieć. Oni wiedzą, że otrzymają wibracje. Oni już wiedzą o wibracjach, więc nie muszę im mówić: “Otrzymacie więcej wibracji”. Gdy dostają więcej wibracji, oni wiedzą, że jestem Adi Shakti, to wszystko, nie muszę tego wyjaśniać. Tak jak wy możecie rozpoznać najlepsze wino, tak oni mogą rozpoznać prawdziwą osobą. Znają smak tego.

Kiedyś na pujy około sześciu tysięcy ludzi dotknęło Moich Stóp. Powiedziałam więc: “Od teraz na pujy, proszę, nie musicie – ludzie nie muszą dotykać Moich Stóp”. Ja to powiedziałam. Ale oni pomyśleli, że Dhumal to zasugerował i rzucili się na niego. Powiedzieli: “Sam chcesz wziąć dla siebie wszystkie błogosławieństwa ze Stóp Matki i nie chcesz, abyśmy je wzięli”, i oni mieli do niego pretensje.

Kolejna rzecz, widzicie, przedtem na Zachodzie Ja nigdy nie robiłam panchamrutu Moimi Stopami, tylko Rękami, ponieważ tutaj ludzie pomyśleliby, że stopy to coś brudnego i nie powinniśmy mieć tego ze stóp, widzicie. A w rzeczywistości Stopy są bardzo potężne i one nigdy nie mogą być brudne. Tak jak wibracje rzeki Ganges. Jeśli weźmiecie wodę z Gangesu zobaczycie, że ona nigdy nie może zostać zabrudzona. Wręcz przeciwnie, jeśli cokolwiek jest w niej, ponieważ ona nigdy nie jest utrzymywana w czystości, jakikolwiek brud się do niej dostanie, osiada na dnie i w ogóle nie brudzi. To bardzo czysta woda, cały czas daje wibracje.

Więc trzeba zrozumieć, że cokolwiek jest czyste, co jest odpowiedzialne za czystość, co jest źródłem czystości, może oczyścić każdą nieczystość. Więc jak to może być nieczyste? Ale jeśli używając mózgu tak myślicie – to takie ograniczone. Nie możecie rozważać czegoś co jest po prostu uosobieniem czystości.

Myślę, że teraz doszliśmy do momentu, w którym powinnam opowiedzieć o Absolucie. Jest nim Shri Ganesha. Dzisiaj jest Jego Puja. To wyjątkowo wspaniała sprawa, że robimy tę Puję w Genewie, w Szwajcarii. Genewa jest prawym Sercem, tak sądzę. W pewien sposób, to jest przeciwko prawemu Sercu. Życie wszystkich ludzi jest tragedią, niczym Ramy i Ayodhyi. I dlatego to jest bardzo ważne, aby Shri Ganesha był czczony tutaj.

Shri Ganesha jak wiecie jest uosobieniem niewinności. Kolorem Ganeshy jest czerwień lub lekko pomarańczowy. Dlatego, że pierwszym kolorem, jaki widzi dziecko będąc płodem jest pomarańczowo–czerwony kolor ścianki macicy matki. To jest krew. Na pewno uczyliście się w Sahaja Yodze, że każda akcja wyzwala reakcję, która działa. Kolorem pierwszego, możemy powiedzieć, pierwotnego Ganeshy jest kolor gliny, ponieważ został On stworzony z Matki Ziemi. Kiedy Gauri, Matka Ganeshy, stworzyła Go, by strzegł Jej niewinności, w czasie, gdy brała kąpiel, nadała Mu czerwony kolor, aby każdy mógł zobaczyć, że siedzi tam ktoś, aby Jej strzec. Więc, kiedy jako płód widzicie czerwony kolor wokół siebie, wtedy wchłaniacie ten kolor i wasz Ganesha w ten sam piękny sposób otrzymuje czerwony kolor. Po prostu pojawia się reakcja, przez którą staje się czerwony i działa, to znaczny czerwony kolor Ganeshy, ten, który ma czerwony kolor Ganeshy odstrasza innych. Oni wiedzą, że tam siedzi Ganesha, czysta, nieskażona osobowość z całą zapalczywością Ganeshy tam jest.

Kiedy Ganesha jest w dzieciństwie, widzicie, kiedy dziecko się urodzi, dzieci są nastawione wyjątkowo obronnie lub gwałtownie, możemy powiedzieć, do każdego kto naruszy ich niewinność. Kiedy one są bardzo małe, nawet nie są tego świadome. Ale powoli, kiedy robią się starsze, stają się bardzo świadome i nie lubią, kiedy zdejmuje się im ubrania w obecności innych, one stały się bardzo nieśmiałe z powodu ich niewinności. Mam na myśli, nieśmiałe, nieśmiałość nie w kontekście ich nagości: bardzo nieśmiałe z powodu swojej nagości, tak aby ich niewinność nie została atakowana. Kiedy ich niewinność nie jest atakowana i kiedy są czyste, to gdy zobaczą nagą kobietę, zamkną oczy. Nie będą chciały patrzeć na nagą kobietę albo nagiego mężczyznę. Więc jest to wrodzone zrozumienie, intuicyjne zrozumienie, że to jest ważne, że muszą chronić swoją niewinność.

Więc czym jest niewinność w nas? Co ona dla nas robi? Tak jak wam już mówiłam, ona daje nam mądrość. Z powodu naszego ego robimy różnego rodzaju głupstwa; tak jak wam opisywałam prezydenta i wielu innych w podobnym wieku i na tak wysokim stanowisku, tak się dzieje, ponieważ całkowicie brakuje Ganeshy. Pojechaliśmy do Brighton, a tam mają plażę, w pewnym sensie – plażę, gdzie mogą przebywać nudyści. I Moja służąca, ona jest niewinna, widzicie, poszliśmy tam, a ona nie mogła zrozumieć, widzicie. Zapytała Mnie: “Ale dlaczego oni to robią?”

Ale jak się zorientujecie, to na Zachodzie trudno jest znaleźć naprawdę mądrą osobę. Możecie powiedzieć, że ludzie są aż za bardzo wykształceni i bardzo dobrze wyposażeni w zrozumienie materialnej strony życia i temu podobnych. Ale jeśli chodzi o mądrość, wiecie, chodzi Mi o to, można być zaszokowanym ich postępowaniem. Po prostu nie mogę zrozumieć, jakiego rodzaju mądrość za tym stoi? Ponieważ cała ich mądrość stała się tylko seksem. Ciągle myślą o seksie i ciągle chcą zrozumieć cały ten absurd związany z seksem. Jeśli zaczniecie myśleć o seksie, w naturalny sposób wasza niewinność zostanie natychmiast zniszczona, ponieważ nie możecie używać inteligencji do seksu.

Nie mogę zrozumieć tej mądrości, z jaką potraficie racjonalizować seks. To przecież taka spontaniczna rzecz. I czy poprzez myślenie o tym, będziecie się tym cieszyć? Jak możecie? To tak jakby powiedzieć, że możemy przekształcić kwiat w owoc poprzez myślenie. A jeszcze poważniejsze jest to, że przypuśćmy, powiecie: “Ja potrafię to zrobić” – oczywiście wy nigdy tak nie pomyślicie, mam nadzieję, że możecie przekształcić kwiat w owoc, mam nadzieję. Ale niektórzy ludzie mogą pomyśleć: “Potrafię przesunąć”, powiedzmy na przykład “tę rzecz, stąd tutaj, za pomocą mojego umysłu, potrafię to przesunąć”. Albo materializować rzeczy. Więc potraficie to zrobić, wierzycie w to, że potraficie to zrobić, ponieważ jacyś ludzie tego dokonali. Ale jako Sahaja yogini wiecie, że to robią buce, duchy zmarłych, one to robią dla was, ponieważ są to wścibskie istoty, które starają się wam pomóc.

To samo dzieje się, jeśli chodzi o seks. Kiedy chcecie uprawiać seks przez intelektualne dążenia, sprawiacie tylko, że buce to dla was robią. Ponieważ, kiedy za bardzo przeprowadzacie projekcję swojego umysłu, wtedy on wchodzi w rejony, gdzie ściągacie na siebie buce. A one są czasami bardzo przebiegłe, czasami zdeprawowane, czasami agresywne, zbieracie rozmaite rzeczy i w rezultacie seks staje się niedorzecznością. Tak wielu zdeprawowanych ludzi ma satysfakcję, gdy tylko was zatakuje i wtedy macie albo bardzo ożywiony seks, że nawet gdybyście zgwałcili sto kobiet to i tak nie będziecie zaspokojeni, albo zostajecie najgorszego typu impotentami. A więc, mam na myśli, że zawsze pozostajecie niezaspokojeni. Wszyscy tacy ludzie po śmierci stają się takimi samymi bucami, czekając na kogoś opętanego seksem i wskakują na niego.

Niewinni ludzie mogą także przez wiele lat nie być aktywni seksualnie, nawet po ślubie, ponieważ są tacy niewinni. Tak samo może być w przypadku ludzi, którzy są jak dzieci. A tutaj to jest wiedza, której uczą od dzieciństwa – wyobraźcie sobie. Ale po co? Czy zwierzęta muszą się uczyć czegokolwiek o seksie od dzieciństwa? One też produkują dzieci.

Co powiedziałeś?

Więc ascetyzm nie jest tym, czego uczę. Najpierw niewinność ochrania i jest czerwona powiedzmy do wieku, co najwyżej pięćdziesięciu lat. Potem stopniowo, jeśli osoba dojrzewa prawidłowo, ludzie, którzy nie są głupi, ale ci, którzy dojrzewają prawidłowo, po pięćdziesiątce, ona zaczyna stawać się pomarańczowa. Staje się pomarańczowa. To znaczy, że kiedy bierzecie ślub ten proces stawania się czerwonym, odchodzi i staje się, zaczyna stawać się pomarańczowa. To oznacza, że etap ochrony jest zakończony. Oznacza to, że przed ślubem dziewictwo musi być strzeżone.

Dopóki nie spotkacie osoby, z którą weźmiecie ślub, ta czerwień jest ochroną dziewictwa. A gdy weźmiecie ślub, etap ochrony nie jest potrzebny. Ale tak musi być względem tylko jednej osoby, czyli żony albo męża. Po czym następuje właściwa dojrzałość i w wieku około pięćdziesięciu lat ona staje się pomarańczowa – to oznacza odwiązanie. Już w ogóle nie czujecie, że macie ochotę na życie seksualne. Nie ma również potrzeby. I wtedy rozwijacie to, co nazywacie prawidłową, dojrzałą niewinnością, która może być porównana do prawidłowo wypalonego glinianego naczynia.

Więc wiek starczy jest doprawdy złotym wiekiem, kiedy osoba posiadła tę mądrość jaśniejącą poprzez ogólne zachowanie tej osoby. Ale po co – ponownie, po co mieć tę dojrzałość, po co mieć tę niewinność? I znowu, ponieważ jesteście racjonalnymi ludźmi, więc można zadać to pytanie, po co? Niewinność jest drogą, w której naprawdę dajesz innym radość, tworząc z tego zabawę. Zabawa jest tworzona tylko poprzez niewinność. I niewinność jest jedyną drogą, przez którą także możecie naprawdę emitować radość. Wyobraźcie sobie świat bez zabawy, co by się stało? Ale ludzie są bardzo zdezorientowani, co jest zabawą a co przyjemnością. Przyjemność jest miła na początku i okropna na końcu. Ale zabawa jest skarbem. Wszystko, co jest nasycone radością zapamiętacie na całe życie, możecie opowiedzieć innym, to takie uosobienie tworzenia zabawy.

Yogin: We francuskim nie ma słowa “zabawa”!

Wyobrażacie sobie, ten francuski język jest dyplomatyczny – nie ma słowa na “zabawa”!

Dam wam prosty przykład jak te dzieci tworzą zabawę z niczego. Widzicie, one zamieniają wszystko w zabawę. Nawet, gdy mówią lub opowiadają także tworzą z tego wielką zabawę. Pewnego dnia Moja najmłodsza wnuczka, Anupama – ma zaledwie sześć lat – bawiła się w domu i poszła gdzieś na górę i usłyszeliśmy duży łomot, widzicie. A Moja córka, która jest bardzo przejętą matką, wiecznie się martwi o dobro swoich dzieci. Zabawa, eh? Ona nie mogła nawet chodzić, widzicie, jej nogi stały się bardzo ciężkie ze zmartwienia, ale poszła dowiedzieć się, co spadło. Więc krzyknęła wołając dziecko i ono zbiegło na dół, wszystko z nią było w porządku.

Więc krzyczała na nią: “Co się stało? Gdzie poszłaś? Dlaczego weszłaś na górę?” Po prostu zaczęła na nią krzyczeć.

Więc dziecko na nią patrzyło, trochę zaskoczone i czekało aż skończy krzyczeć. I powiedziało bardzo cicho: “Nie przyjechałam tu aż z Riadhu, żeby umrzeć!”

Więc jest tyle rzeczy, które trzeba zapisać, to wszystko jest zabawą, one ze wszystkiego mają naturalną zabawę. Widzicie, mamy tu tyle dzieci, możecie napisać o nich tyle rzeczy, jakie piękne psoty wyczyniają, jak iskrzą im się w oczach figle, bo chcą zamienić wszystko w zabawę.

Zabawa daje radość, daje wam radość. To w żadnym wypadku nie jest jakiegoś rodzaju przymilanie, albo robienie komuś krzywdy ani nie ma w tym nic sadystycznego, ale to jest po prostu rozkwitanie.

Yogin: Matko, jak sądzisz, czy moglibyśmy przestać tłumaczyć, bo to zabiera zbyt dużo czasu na ... Angielskie słowa, wyjaśnimy im pod koniec. Matko, dla tych kilku, którzy nie rozumieją, wyjaśnimy im pod koniec. Czy to dla Ciebie w porządku?

Właśnie zbliżam się do końca, Gregoire, ponieważ kończę o dwunastej trzydzieści, więc zróbmy tak dzisiaj. Ale następnym razem myślę, że będzie lepiej, żebyście przetłumaczyli to później. Możemy przetłumaczyć jeszcze trochę, bo zbliżamy się do końca. I dlatego to trwało tak długo, inaczej zajęłoby to jedną trzecią tego czasu. Po prostu przetłumaczmy tę część.

Zabawa jest niczym innym jak tylko rozkwitaniem. Ona nikogo nie drażni, nie robi nikomu krzywdy, nikomu nie przysparza kłopotu, tylko rozkwita i całość zamienia w aromat. To taki trik Boskości. To ma w sobie również coś wyższego niż to, że gdy jesteście niewinni, naprawdę możecie poczuć radość. Więc niewinna osoba może poczuć radość z czegoś, czego ktoś bardzo poważny i bardzo racjonalny może nigdy nie poczuć. Niewinna osoba może się śmiać głośno z czegoś, co dla innych ludzi może nie być zabawne. Więc tworzenie zabawy nie jest czymś dziwnym, jest to bardzo prostolinijne, proste, spontaniczne rozkwitanie.

Tu w Genewie ludzie traktują wszystko bardzo poważnie. Jeszcze bardziej w Szwajcarii. Do takiego stopnia, że w rezultacie popełniają samobójstwa. Ponieważ jesteście zorientowani na pieniądze i dodatkowo jesteście pewnego rodzaju, przyjmujecie rolę wybawiciela całego świata. To znaczy, że jesteście bardzo egoistyczni, ponieważ chcecie pomóc całemu światu. Kim jesteście, aby pomagać? A po trzecie, macie tu bezsensowną armię, która wcale nie jest potrzebna.

Yoginka: Matko, przepraszam, pisali wczoraj w gazetach, że rozbił się kolejny wojskowy samolot w Szwajcarii, są dwie ofiary śmiertelne.

Yogin: W obecności Twojej fotografii!

To chyba przesada, żeby Mnie obwiniać!

Yogin: On mówi, że to było podczas pokazu, w którym chcieli zademonstrować całą potęgę armii.

To jest zabawą – to jest zabawą, widzicie? Więc wszyscy z tego powodu są szczęśliwi, widzicie, tak właśnie dostrzega się zabawę.

Aby jeszcze bardziej pomóc w zabawie, mamy Hanumanę. On pomaga zabawnej stronie Shri Ganeshy. Tak jak, tak jak Ganesha stosuje zabawne sztuczki na lewostronnych osobach, On stosuje Swoje sztuczki na prawostronnych osobach. Tak jak wtedy, gdy kobieta za dużo płakała, jej mąż nie żyje: “Cóż teraz począć? Koniec ze mną”, i tak dalej, widzicie – i nagle widzi, jak jej mąż wchodzi do pokoju! Ale On robi to tylko dla ludzi, którzy są niewinni. A przebiegłych, On karze. Będzie wtedy obsypywał ich wszelkiego rodzaju nieszczęściami, jedno będzie gorsze od drugiego i powie: “Teraz płacz więcej i więcej. Chcesz płakać? W porządku, masz tutaj, płacz jeszcze bardziej”.

A Hanumana po Swojej stronie – na przykład, kiedy Lakshmana był chory i On musiał przynieść pewne lekarstwo z wielkiej góry, On przyniósł całą górę! I powiedział: “Nie miałem czasu, żeby tego szukać, więc ty znajdź” i przyniósł całą górę. On też ma taki sam styl i może być bardzo destrukcyjny w przypadku ludzi egoistycznych, takich jak Ravana – cała Lanka została spalona.

Gdy Ganesha jest pomalowany na czerwono, to On jest na pomarańczowo. Tak jak Ganesha musi osiąść na stałe w jednym miejscu, i używa Świętego Michała do biegania w górę i w dół po lewej stronie, to Hanumana może biegać w górę i w dół, On nie musi osiadać w miejscu. Ale chociaż On jest Bóstwem, które spoczywa – On ma osiąść – i kiedy już spocznie, emituje wibracje, które wszędzie docierają. On jest źródłem niewinności. On jest źródłem wibracji. W pewnym sensie, On jest wszystkim. Kiedy On się wznosi, tutaj wewnątrz was jako Mahaganesha a w Bogu On schodzi w dół jako Ganesha – stąd, z tyłu [głowy].

Więc, kiedy za dużo myślicie o seksie, wasze oczy się niszczą, ponieważ używacie Mahaganeshy. Wasz Mahaganesha jest zepsuty a wasze oczy zaczynają wędrować. Oczy tracą niewinność, czystość i zaczynają wchłaniać wszelkie brudy. Oczy, które są czyste i niewinne dają niewinność innym. Nie tylko to, ale są oczami, przez które wygląda Duch. Nie ma czasu, aby wam teraz opowiedzieć o wielu kombinacjach, ale to bardzo źle, kiedy ludzie mają takie nieczyste oczy, jak oczy buców. I wszyscy dookoła, którzy są jak buce, będą patrzeć na tę osobę, ponieważ rozgrywa się teraz szatańska gra negatywności. I właśnie to robimy, kiedy nie umieszczamy Ganeshy we właściwych miejscach. Jeśli mamy sprawić, żeby Ganesha był odzwierciedlony w naszym stanie Mahaganeshy, powinniśmy starać się utrzymywać nasze oczy bardzo czyste, tak, aby miejsce Mahaganeshy było czyste.

W czasie Pujy do Shri Ganeshy musicie też przynieść miękką trawę, durvah. On lubi durvah, to się nazywa durvah – ponieważ miękka trawa jest łagodząca dla oczu. Nie tylko to, ale ona daje wam zieloną część czakry Swadishthan. Ponieważ On istniał zanim zaczęliśmy myśleć, zanim zaczęliśmy proces myślowy. To sugeruje, że ta część Swadishthanu w czasie, kiedy nie myślicie, ta zielona część; niższa część Swadishthanu jest zielona.

Więc zielony jest tym: na etapie, kiedy nie staliśmy się jeszcze istotami ludzkimi, na tym etapie on reprezentuje zieleń Swadishthanu, kiedy stworzono cały Wszechświat, wszystko. Aż do tego momentu jest on zielony. Potem, kiedy zaczyna tworzyć ego, staje się żółtym kolorem, gdzie używa słońca, strona akcji – nie “używa” słońca ale staje się aktywna, reprezentuje stronę słońca.

Więc faktycznie zieleń reprezentuje część Ganeshy, w pewien sposób część Ganeshy, ponieważ do tego momentu nie myślicie. Widzicie, jesteście na poziomie, który jest blisko Matki Ziemi. Więc Matka Ziemia daje, widzicie. Etap słońca jeszcze się nie zaczął, kiedy jest tam zieleń, ponieważ Matka Ziemia daje tę zieleń. Oczywiście to słońce sprawia, że to jest zielone, to inna sprawa, ale jeszcze nie zaczęliście tego robić. Kiedy zaczynacie sami coś robić na ludzkim poziomie, całość staje się żółta. Więc Swadishthan ma dwie strony, fizyczną i mentalną. Fizyczna jest zieloną stroną a mentalna jest stroną żółtą.

Więc dzisiaj jesteśmy tutaj, aby czcić Shri Ganeshę. Teraz chciałabym, abyście zerwali trochę trawy z trawnika, trochę miękkiej trawy, ponieważ jest to ważna część tego.

Teraz powinniście skierować oczy na zieleń, aby polepszyć waszego Ganeshę. A kiedy jest bardzo ciepło, możecie rano chodzić boso po trawie, gdy na trawie jest rosa. Ci, którzy są wyjątkowo nadaktywni powinni stosować wegetariańską dietę, to im pomoże, stać się bardziej zbalansowanymi. Nie fanatycznie, ale więcej jarzyn i jedzenie bardzo małych zwierząt, tak też jest w porządku.

CD2

Ale dzisiaj nie mówiłam o Jego vahanie, ponieważ mówiłam o tym w innych wykładach. Jego vahana – Jego pojazd – nie mówiłam o tym, ponieważ mówiłam o tym w Moich innych wykładach o Nim.

Najlepiej by było, gdybyście to znaleźli, tak jak tego typu, bardzo cienki, ten rodzaj, on jest dobry. Ten jest w porządku, możecie wziąć więcej, tylko... Używa się tego do pokrapiania Stóp wodą.

Ci, którzy jeszcze nie myli Moich Stóp powinni dzisiaj umyć Moje stopy. O, to jest dobre, o to chodzi! On ma dokładnie to, co miałam na myśli, dokładnie to. To jest bardzo dobre, tak. Och, ale wciąż niektóre z nich są twarde, nie szkodzi. To jest ten rodzaj z okrągłymi krawędziami. Czy możecie je wyjąć, część z nich? Te okrągłe krawędzie, te okrągłe krawędzie. To są te okrągłe, nie płaskie, ale okrągłe. Nie z ostrymi krawędziami, ale te z zaokrąglonymi. Niech on to zrobi. Okrągłe są, tak? Okrągłe? Tak, o te chodzi, o te chodzi. To wystarczy. One też nie są okrągłe. Te okrągłe. W porządku? One wszystkie są płaskie. Jest jeden okrągły. Nie, ten również jest płaski. Myślę, że nie macie takich w tym kraju. Myślę, że powinniśmy zdobyć kilka... Niech będzie. Po prostu przywiążcie je sznurkiem, to wszystko. Tak będzie dobrze, to wystarczy, po prostu zwiążcie to z tym, z kijkiem. Po prostu przewiążcie je sznurkiem dookoła i używajcie do pokrapiania wodą. One się nazywają durvan gulah, to znaczy kiełki, kiełki z tego.

Yogin: Matko,... Na Wielkanoc chowamy jajka dla dzieci w takiej trawie.

Po prostu zobaczcie. O, tak trzeba! Dobrze. Dziękuję. Zwiążcie to, ten też. Dobrze. Czy możecie to związać sznurkiem? Tak jest dobrze, dobrze. Macie tego więcej? Lepiej mieć te większe, w porządku? Ponieważ nie mamy dużego wyboru.

Teraz ci, którzy będą myć Stopy. Te osoby, które jeszcze nie myły Moich Stóp powinny podejść. Niech ona podejdzie, niech podejdzie. Tak bardzo się cieszę, że mogłaś przyjść! Tak miło cię widzieć! Dobrze. Podejdźcie tutaj. Jedna osoba powinna myć, a ktoś inny powinien zacząć tak robić. Możecie go zapytać. Tak, podejdź. Dobrze, dobrze, dobrze. To będzie po pujy, w porządku? Więc cała czwórka małych dzieci, gdzie oni są? Gdzie jest Anand? One powinny myć jako pierwsze. Niech zobaczę. A co z tymi czterema rzeczami, które wam dałam dla dzieci? Gdzie się podziała ta czwórka dzieci? Nie, jedna.... W porządku będziemy mieli tę czwórkę. Podejdźcie. W porządku, podejdźcie. Wy – najpierw niech podejdą dzieci i umyją Moje Stopy, najpierw podejdźcie. Wszystkie dzieci, podejdźcie, podejdźcie! Zaczekajcie. Myjcie Moje Stopy. Dobrze. Nalejcie wody, tak myślę... Gdzie ona jest? Marie-Amelia, Marie-Amelia? I również to żółte przynieście stamtąd, to żółte... Mocno pocierajcie, pocierajcie mocno.

Niech was wszystkich Bóg błogosławi. Dobrze. Wyson jest od niej młodszy, prawda? Barbara jest młodsza, dobrze. Więc teraz. Witaj... to jest dla ciebie... dobrze? Barbara, to powinno być dane jako dakshina, rozumiesz?

Dobrze, dałam każdemu z nich według wzrostu. Dobrze ... Skończone, skończone! Teraz po prostu to zabierzcie. To powinno być podarowane ludziom na głowę – niektórym liderom. Poproście dzieci, one to zrobią Jak to nałożyć na głowę zapytajcie Lawrenca... Powinniście podłożyć coś pod Moje Stopy – ręcznik, ktoś powinien to zrobić. Myślę, że powinien tu być ktoś, kto wie jak to zrobić. Ktoś, kto wytrze Moje Stopy. Czy możesz, ty bez aparatu fotograficznego? Przyjdź tutaj. Ręczniki do wytarcia Moich Stóp powinny być tam. Tutaj, tylko położyć tutaj. Powiedzcie im, żeby tego nie upuścili. Tylko tam położyć.

One nie mogą być, to musi być Chaturthi, według osób z Indii. Widzicie, Chaturthi. To musi być ... Również to może być. Kiedy był...? Szesnaście dni temu. Więc to jest po... To jest dwa dni po nowiu księżyca. Ale to jest, to musi być Chatur Dashi, to musi być czwartego dnia czasu indyjskiego, ponieważ Chaturthi jest dniem gdzie on został ustanowiony. Bo widzicie, w Indiach to jest trochę inaczej. Pewnie się to teraz zaczęło. Około dwunastej! Więc potrzebujecie tłumaczy. To jest Chaturthi, napewno. Widzicie, jak to się wypracowuje.

Niech przyjdą ci, którzy nie myli jeszcze Moich Stóp. Najpierw trzeba wziąć to... Tego użyjcie na wodę...

Ci, którzy jeszcze nie myli proszę podejdźcie ...dajcie im zimną wodę do umycia Moich Stóp. Musicie umyć Moje Stopy. Musicie pocierać. Musicie pocierać Moje Stopy, mocno, mocno. Masuj. Masuj. Ty masuj Moją prawą, i ...dolną część, dolną część. Masuj, tak, pocieraj. Mocno pocieraj. Mocno, mocno, mocno. Pocieraj tutaj. Mocno, mocno, bardzo mocno. Tutaj...

Zatrzymajcie tę wodę do picia, nie aby... ale trzymajcie to w czymś, w butelce lub czymś.

Tak jest dobrze. Jesteście w porządku. W porządku? Tak dobrze. Teraz, zdajecie sobie sprawę, że pocierając Moje Stopy dostaliście więcej wibracji, więc rozumiecie to racjonalnie. Niech Bóg was błogosławi. Bardziej teraz czujecie? Niech Bóg błogosławi. Teraz inni mogą podejść. Nie po to, aby trzymać, ale aby więcej pocierać. Nie aby trzymać za długo, ale aby pocierać.

Byłeś u Hare Rama, nieprawdaż?

Yogin: Nie, on nie był.

Ale on mówi mantry...

Yogin: Tak, on był w Rzymie i przedtem też był, on jest z Sycylii.

Dlaczego ma zablokowane prawe Vishuddhi? Prawe Vishuddhi?

Yogin: Ach, tak, Matko, on przedtem palił papierosy, ale teraz już nie pali...

Teraz lepiej?... Dobrze.

Teraz on musi przeczytać Ganesha Atharva Sheersha.

Twoje palce powinny być masowane, twoje palce powinny być masowane w ten sposób. To twoje palce to robią, nie Ja. Musisz masować swoje palce, żeby stały się bardziej wrażliwe, dobrze? Chodź tutaj, chodź... Posłuchaj tego, co on mówi, dobrze? ...

On czyta. Posłuchaj go. To oznacza obudzenie w nas Chrystusa, obudzenie w nas Shri Ganeshy.

Radujcie się!