Onschuld - Moederlijke liefde – Vâtsalya - Les Diablerets, Zwitserland - 8 augustus 1989

En TVD 2015-1009 NlTVD 2020-1127

Vandaag zijn jullie hier gekomen om eer te bewijzen aan mij als Shri Ganesha. We hebben Shri Ganesha’s lof gezongen, vóór elke puja. En we hebben zo’n geweldig respect voor Shri Ganesha, omdat we tot de ontdekking gekomen zijn dat zolang Shri Ganesha - die het symbool van onze onschuld is - niet in ons ontwaakt is, we het Koninkrijk van God niet kunnen binnengaan. En om daar zelfs maar aanwezig te zijn om de vreugde te beleven van de zegeningen van Shri Ganesha, moet onze onschuld volledig tot bloei gekomen zijn. Zo loven we hem en hij is heel gemakkelijk te loven.  En wat we ook verkeerd gedaan mogen hebben - voordat we bij Sahaja Yoga kwamen - dat zal hij geheel vergeven,  want hij is het eeuwige kind.

Je merkt bij kinderen, dat als je ze soms een tik geeft, als je boos op hen wordt, dat ze dat vergeten. Ze onthouden alleen de liefde en niet wat zij door jullie handen te verduren kregen. Totdat ze volwassen worden, hebben ze geen herinnering aan nare dingen die hen zijn  aangedaan. Vanaf het allereerste begin dat een kind geboren is bij een moeder, beseft het niet wat het meemaakt, maar geleidelijk aan begint het geheugen te werken en zal het in zichzelf de dingen weer naar boven halen. Maar in het begin herinnert het zich alleen maar wat voor leuke dingen hem zijn overkomen. We denken dus altijd graag terug aan onze kindertijd, aan wat we fijn vonden in onze kindertijd. Maar als we groter beginnen te worden, gaan we ons ook alle nare dingen herinneren en alle miserie en ellende die we moesten doorstaan. Alle pijnlijke ervaringen die we doorgemaakt hebben, die proberen we op te smukken. In de kindertijd onthouden kinderen alleen de mensen die van hen hielden en niet de mensen die hen pijn deden. Ze willen het zich misschien niet herinneren. Daar lijkt het op. Maar als ze groot worden, dan proberen ze alleen aan die mensen te denken die hen kwaad gedaan hebben, of hen lastig gevallen hebben en zo maken ze zichzelf werkelijk diep ongelukkig.

Maar het Ganesha principe is uiterst subtiel, het subtielste van het subtielste.  En het komt in alles voor; in materie is dat in de vorm van vibraties. Er is geen materie die zonder vibraties is. Er zijn zelfs in atomen vibraties gezien en ook in de moleculen van alle stoffen die er bestaan. Zo is Shri Ganesha evenzeer  de eerste die in de materie werd gevestigd. Zodoende kunnen we zien dat hij in de zon voorkomt, dat hij in de maan voorkomt, dat hij in het hele universum voorkomt, in de hele schepping en vervolgens ook in mensen. Alleen de mensen zijn in staat om hun onschuld op een of andere manier te maskeren. Daartegenover zijn dieren onschuldig. Mensen hebben de vrijheid; als ze willen, kunnen ze hun onschuld verborgen houden, ze kunnen de deuren naar Shri Ganesha dichtdoen en beweren dat hij niet bestaat. Ze kunnen dat verhullen. En daarom zien we bij mensen dat ze zoveel afschuwelijke dingen doen, en het bestaan van Shri Ganesha uit de weg gaan.

Maar hij komt in actie. Hij grijpt op zodanige manier in dat hij natuurlijke terughoudendheid ten opzichte van ons wangedrag laat zien. Zoals wanneer je dingen doet die Shri Ganesha niet fijn vindt, dan gaat hij binnen bepaalde grenzen mee, dan vergeeft hij je tot op zekere hoogte, maar dan zal hij zich openbaren als ziektes, als fysieke kwalen en bij vrouwen wordt dat een mentale aandoening. Het kan ook leiden tot problemen in de natuur. Natuurrampen zijn dan ook alleen maar de vloek van Shri Ganesha. Als mensen verkeerde dingen beginnen te doen, zich op een verkeerde manier gaan gedragen, collectief, dan komen er natuurrampen om hen een lesje te leren.

Zo is hij in zijn essentie toch in alles aanwezig, ook in zijn vermogen om zijn wil in te zetten voor ontketening van de ondergang van de hele wereld. We hebben een beeld van Shri Ganesha als een minuscuul iets. Wij menen dat als hij zich op een klein muisje kan verplaatsen, hij dan ook wel heel klein moet zijn. Hij is zo klein als hij groot is. Hij overtreft alle godheden in zijn wijsheid. Hij is de bezorger van wijsheid. Hij bezorgt ons wijsheid. Hij laat ons leren. Hij is onze guru in dat opzicht, Mahaguru, omdat hij ons leert hoe we ons moeten gedragen. Als je probeert om hem voorbij te streven door je te misdragen, dan zal zelfs Moeder dat niet dulden, want zij weet dat degenen die Shri Ganesha overtroeven ook de mensen zijn die Moeder nooit zullen respecteren. Hij is dus het toppunt van respect voor Moeder. Het toppunt. Hij kent geen andere godheden. Hij heeft geen weet van Sadhashiva. Hij heeft geen weet van iemand anders, heeft alleen maar respect voor de Moeder. Hij is dus degene die de kracht van devotie is en van volledige overgave aan Moeder en daarom is hij de machtigste godheid onder alle godheden en niemand kan hem overtreffen in zijn kracht.

We moeten begrijpen dat als kinderen groot worden, Shri Ganesha ook in hen gaat groeien, maar omdat zij menselijke wezens zijn, kunnen ze hoe dan ook Shri Ganesha trachten in te tomen.  Het is dus de taak van de ouders, die Sahaja yogi’s zijn, om erop te letten dat ze op een bepaalde manier  - op een onthechte manier - zorgen dat Shri Ganesha in hen gevestigd is.  Het eerste teken van Shri Ganesha in een kind is wijsheid. Als het kind niet wijs is, als het lastig is, als het zich niet weet te gedragen, dan toont dat aan dat Shri Ganesha door hem wordt aangevallen.  En vandaag de dag in de moderne tijd, zoals het er nu voorstaat, worden kinderen heel erg aangevallen. Wordt de onschuld aangevallen. En het is heel moeilijk voor mensen om een lijn te trekken tot waar-en-niet-verder je met kinderen mag gaan.

De lezing van vandaag zou meer moeten gaan over hoe ver je gaat met Shri Ganesha, wat kinderen betreft, want dat is een heel belangrijk punt omdat hij de bezorger van wijsheid is. De ouders moeten dus begrijpen dat: “Als hij de bezorger van wijsheid is, dan zou er wijsheid moeten zijn, wijsheid in mij. En als ik wijsheid heb, dan ben ik evenwichtig, en verlies ik niet mijn zelfbeheersing bij kinderen, maar probeer ik hen op zo’n manier terecht te wijzen dat ze gecorrigeerd worden. ”Als je in tegendeel heel streng probeert te zijn met je kinderen, dan zouden ze als reactie  de verkeerde kant op kunnen gaan. Of als je ze teveel aan banden probeert te leggen, dan kunnen ze zich ook op zo’n manier gedragen. Dus om te beginnen zou je – praat met je eigen kinderen over hoe Shri Ganesha dat zelf doet, over dat respect hebben voor je Moeder. ‘Je Moeder ‘ wil zeggen je Heilige Moeder én je eigen moeder. Dat is heel belangrijk. Als de vader het kind geen respect voor de moeder bijbrengt, dan kan het kind nooit goed terechtkomen. Want het gezag komt zonder twijfel van de vader, maar moeder moet gerespecteerd worden. En daarvoor is het weer heel belangrijk dat de moeder de vader moet respecteren. Als je dus in het bijzijn van de kinderen met elkaar ruzie gaat maken, je gaat misdragen en gaat praten op een manier zoals het niet hoort, dan zal dat ook een slechte invloed hebben op de Ganesha Tattwa (principe) van het kind. Die opvoeding is iets heel belangrijks in Sahaja Yoga, want door Gods’ genade hebben jullie allemaal gerealiseerde kinderen gekregen. Dus moet je weten hoe ver je mag gaan met je kinderen. Om ze wijzer te maken.  Om deugdzaam te zijn, om rechtschapen te zijn – in de eerste plaats moet je hun wijsheid proberen te beschermen. Als ze iets wijs zeggen, dan moet je dat naar waarde schatten. Maar zij mogen ook niets zeggen wat ongepast is, wat onbeleefd is. Zich misdragen kan dus ook niet getolereerd worden, in die zin dat de innerlijke wijsheid die er maar voorhanden is, naar buiten tot uiting gebracht dient te worden als licht.

Nu gaan we verder kijken in hoeverre Shri Ganesha iets doet. Zoals ik al zei, is hij in het subtielste van het subtielste aanwezig , maar je moet hem wakker maken. Bijvoorbeeld, jullie hebben het water gezien dat gevibreerd is – wat betekent dat? Gevibreerd wil zeggen dat de Ganesha Tattwa in dat water verlicht is. Als dat water dus in je maag komt, of in je ogen, of waar je het ook maar wilt toepassen, dan werkt het,  dan werkt het zodanig dat het de Shri Ganesha Tattwa zal stimuleren in alles waarvoor je het maar wilt gebruiken. Jullie hebben wel gezien dat we agrarische wonderen beleefden, om mee te beginnen. Een agrarisch wonder is iets waar mensen zich over verbazen, maar het is heel simpel. Als je het Ganesha Principe eenmaal gaat stimuleren in het zaad, dan wordt het tien keer, soms wel honderd keer zo groot. Zelfs Moeder Aarde, waarvan we menen dat het iets doods is, kan worden gevibreerd. Stel dat jullie Sahaja yogi’s met blote voeten over de grond lopen, dan wordt Moeder Aarde gevibreerd.  Zó’n Moeder Aarde zal op de bomen inwerken, op het gras, op de bloemen, op alles. Het is zo, vertelden Sahaja yogi’s me, dat alle bloemen die in hun ashrams groeien buitengewoon groot zijn en heel lekker ruiken. Zo hadden madeliefjes in Londen of in Engeland nooit een geur, nooit. Toen was het formaat van madeliefjes zo klein; en dat is nu zo groot geworden, en je ziet ze overal, zo heerlijk geurend. En het is een wonder; de eerste keer toen ik iemand vertelde dat madeliefjes lekker ruiken, konden ze dat niet geloven.  En toen merkten ze de geur op; ze waren verrast.

Op zo’n manier zal de Ganesha Tattwa begrijpen, denken, organiseren en zijn uitwerking hebben, als hij ontwaakt is.  En zo niet, als hij nog aan het sluimeren is, dan gebeurt dat niet. Als hij dus actief wordt, dan werkt het. Net als het zaadje wanneer het ontkiemt.  Aan het topje van het zaadje zit een klein celletje met daarin de Ganesha Tattwa, die ontwaakt is. Daardoor weet het hoe het naar omlaag moet gaan, hoe het om een steen heen moet gaan en hoe het zich vast kan zetten. En hoe het de waterbron kan bereiken. Maar het heeft alleen gevoel voor hoe ver het moet gaan om te blijven voortbestaan en zich te voeden, op heel materieel vlak om de boom in staat te stellen om te groeien.

Maar die Ganesha Tattwa begint heel heel subtiel te worden, en het subtielste op het punt van de Agnya chakra. Tegen de tijd dat de Agnya chakra bereikt wordt, begrijpt het dat het nu een spirituele dimensie heeft.  Dezelfde Ganesha Tattwa die in een klein topje van een wortel actief was, is nu aan het werk voor de spirituele zaak. Daarom sluiten mensen hun ogen als ze mediteren – want ze willen niets anders zien dan alleen maar Shri Ganesha, die bezig is met het meditatieve proces van hun Kundalini.

Dit meditatieproces treedt op als we onze ogen sluiten, maar als..  je ziet als iemand aan het slapen is en als hij droomt, dan zul je zien wat er gebeurt... de ogen zullen de hele tijd bewegen, de ogen zullen in beweging zijn. Die Ganesha Tattwa wordt nu door je aandacht in gang gezet. Als je een aandacht hebt die de hele tijd van hier naar daar, naar daar, naar daar gaat, dan wordt die aandacht aangetast, speciaal voor het geval dat we naar mannen beginnen te kijken, naar vrouwen, de hele tijd door.  Dan zal – wordt ook onze Ganesha Tattwa heel erg beschadigd. Zulke mensen hebben het moeilijk om verder te groeien in hun spirituele ontwikkeling omdat de Agnya zelf uitdooft.

En die Ganesha Tattwa kan ook afnemen als je heel materialistisch bent, altijd maar bezorgd om je spullen, zoals wanneer je iets in huis hebt wat je zorgen baart, en dat je op al die dingen moet letten en de hele tijd probeert om ze mooier maken en je alsmaar ongerust bent over materiële zaken. Dan kan de Ganesha Tattwa ook verloren raken, omdat je de hele tijd over die spullen bezorgd bent. Zoals wanneer we naar de winkel gaan om van alles te bekijken. “Wat is daar? Wat is daar? Wat moet ik kopen? Wat zal ik kopen?” Precies zo, als je je daar teveel aan wijdt, zal het ook zo gaan.

Maar veronderstel dat je iets koopt vanwege de schoonheid, omdat het mooi is. Je wilt iets kopen om je huis te verfraaien. Dat wil zeggen dat je iets tracht te doen om anderen te plezieren. Je doet het om anderen blij te maken. Dan werkt het andersom, dan laat het je spirituele ontwikkeling groeien, maar alleen als het gedaan wordt om een soort van vreugde bij anderen teweeg te brengen, het delen van schoonheid van wat je ook maar gekocht of meegenomen hebt.

Maar stel je dat je iets koopt om anderen jaloers te maken – dat leerde ik ook onlangs,  dat een dergelijke neiging bestaat bij mensen om iets te kopen om anderen jaloers te maken,  niet om iemand blij te maken.  Als er mensen zijn die dingen kopen enkel om anderen jaloers te maken,  dan kan hun Ganesha Tattwa ook te gronde gaan. Wat zou je moeten kopen?  Van alles, je zou een prachtig huis moeten maken. Als iemand naar je huis komt,  zou men moeten zeggen: “Oh , wat hebben we iets moois gezien.” Niet omdat je aan het ding gehecht bent, maar aan het feit hoe mensen zich voelen, hoe ze zich fijn en ontspannen voelen en ze hun Shri Ganesha binnenin zich voelen, zoals bij schoonheid gebeurt.  Als dat gevoel opkomt, dan kunnen we zeggen dat er Ganesha Tattwa aanwezig is. En dat is een heel moederlijk gevoel; zo is dat.

Zoals een moeder altijd lekkere dingen aan haar kinderen wil geven, heerlijke dingen, aan haar kinderen. Op dezelfde manier als je die vatsalya hebt - zoals het genoemd wordt - werkt dat gevoel van de moeder voor het kind. Dat subtiele gevoel dat je krijgt:  “Als mensen mijn huis komen bekijken. Kijk maar eens hoe fijn ze dat vinden,  hoe ze daar van genieten en hoe ze dat waarderen.” Op die manier voldoe je ook in grote mate aan het Ganesha Principe omdat je aandacht aan kunstenaars hebt geschonken.

Alhoewel kunstenaars al hun mooie werken hebben gecreëerd door middel van hun Swadishthan, als echter de Swadishthan niet door Shri Ganesha geleid wordt, dan kan het niet mooi worden.  Tegenwoordig zie je wel dat kunstenaars zich laten meeslepen door allerlei bespottelijke dingen en heel immorele dingen. En die dingen zijn van geen blijvende waarde.  Vandaag zullen mensen het kopen en morgen zullen ze het wegdoen.

Alleen de dingen die het subtiele Ganesha Principe actief in zich meekregen,  die maken dat je gerust bent, dat je je vredig voelt, dat je je gelukkig voelt, zijn de dingen die op prijs gesteld worden. Shri Ganesha vestigde zo het hogere Zelf binnenin jullie. Dus het lagere zelf, dat plezier heeft in alle lagere dingen in het leven, zal worden beknot, zal worden ingeperkt, en zal soms zelfs volledig vernietigd worden door Shri Ganesha.

Ik zal je het voorbeeld van de Mona Lisa geven. Als je Mona Lisa ziet – ik bedoel, ik weet niet, ze kan geen filmster zijn, ze kan de schoonheidswedstrijd niet winnen, denk ik.  Ze... haar gezicht is zo sereen, heel moederlijk, heel zuiver zijn haar ogen. En hoe komt het nou dat ze eeuwenlang zo’n waardering krijgt? De reden is dat het Ganesha Principe in haar aanwezig is. Ze is een moeder, en het verhaal daarover is dat deze dame haar kind verloren had en dat ze nooit meer zou lachen en nooit meer zou huilen. En er werd een klein kind naar haar toe gebracht en toen ze het kind zag, toen kwam die glimlach op haar gezicht, uit liefde voor dat kind en dat is door de grote kunstenaar uitgebeeld. En daarom hebben mensen er zo’n waardering voor.

Je ziet in het Westen - ofschoon mensen niet veel interesse tonen in de moeder-kind relatie - dat waar je ook gaat het thema van moeder en kind het voornaamste is. Ze laten je foto’s zien: “Dit is moeder en kind, dit is Christus, Moeder en Kind. Toen Christus neergehaald werd, was de Moeder erbij. ” Het moeder-en-kind principe (aspect) moet in hen in werking zijn, anders wordt die afbeelding niet als zoiets groots beschouwd. Of eigenlijk moet je Christus, die het Ganesha Principe zelf is, laten zien. Ik heb geen enkele afbeelding als zodanig gezien uit die tijd waarin dit aspect niet aanwezig was. Zelfs Picasso heeft er gebruik van gemaakt. Zelfs mensen die best modern waren, moesten dit element wel gebruiken om populair te worden. Maar sommige mensen hebben gebruik gemaakt van populaire aspecten - niet vanuit het Ganesha Principe - maar juist van anti-Ganesha elementen. Al die dingen zijn van het toneel verdwenen, en ik zie nu langzamerhand alles dieper afglijden, dieper en dieper en dieper.

Ondanks het feit dat mensen hun ethiek zijn kwijtgeraakt, zouden ze toch wel graag een Rembrandt willen hebben, willen ze een Leonardo da Vinci hebben, zouden ze iets van die kunstenaars willen hebben die Moeder en Kind geschilderd hebben.  Dat is verbazingwekkend. Toen ik deze keer naar Oostenrijk ging, vroeg ik: “Wat voor beelden hebben jullie?” “We hebben een prachtige Moeder en Kind.”

Zo geeft dit element het meeste vreugde, is dit het element wat mensen het meeste vreugde bezorgt: naar kinderen kijken, met hen spelen, van hun gezelschap genieten. Waarom? Omdat daarin dat liefelijke van het kind aanwezig is. Het is echt, ik bedoel, het maakt je aan het lachen van blijdschap als je naar een kind kijkt. Meteen wordt het gezicht anders. Ik vertelde jullie al dat ik zelfs een krokodil gezien heb die haar eieren aan het openbreken was. Ze lieten dat in een film zien en je zou de ogen van die krokodil hebben moeten zien op dat moment, hoe voorzichtig ze dat breken deed. Zo mooi waren haar ogen, vol van – zulk een liefde straalde er uit haar ogen. Je kunt niet geloven dat dit dezelfde ogen van dezelfde krokodil waren, en hoe kalmpjes aan ze al die eieren met haar bek aan het breken was en de kleine, kleine krokodilletjes die eruit kropen. En toen bracht ze hen naar de kust en waste hen de hele tijd in haar mond, zo voorzichtig, alsof het een badkamer was, zo gebruikte ze haar bek, weet je.

Je zou het moeten zien hoe ook dieren met hun kinderen omgaan. Maar als je min of meer ‘modern’ wordt, zogenaamd, dan wordt je optreden heel merkwaardig. Er zijn mensen die kinderen doden, er zijn mensen die kinderen misbruiken. Ik bedoel, dat is erger dan rakshasa’s.  Zelfs rakshasa’s hebben dat niet gedaan, pinkshasa’s hebben dat niet gedaan. De Gana’s zijn verbijsterd: “Wat voor soort nieuwe schepsels is er opgestaan, waar vandaan, dat ze geen liefde hebben voor hun kinderen, dat ze hun kinderen kunnen doden,  hun handen kunnen breken. Dit zijn hun eigen kinderen. Als ze dit doen met hun eigen kinderen, wat zullen ze dan doen met andere kinderen?

De liefde voor je kind moet dus absoluut aanzienlijk zijn, maar je mag als Sahaja yogi’s, ten eerste, niet alleen maar gehécht zijn aan je kind. En ten tweede moet je weten hoe je een hele speelruimte behoudt in je liefde. Die speelruimte is lankmoedigheid. “Is dit goed voor mijn kind? Ben ik mijn kind aan het verwennen? Ben ik mijn kind teveel aan het aansporen? Speel ik mijn kind in de kaart? Of ben ik het kind goed aan het leiden?”  Want in de kindertijd moeten de vader en de moeder het kind leiden. Ze moeten kinderen begeleiden en kinderen moeten gehoorzaam zijn en naar hun ouders luisteren.

Maar tegenwoordig zijn kinderen niet gehoorzaam. Dat zijn ze niet, omdat er – ze zien dat de ouders onderling niet naar elkaar luisteren. Ook zien ze een maatschappij waarin kinderen hun ouders het leven onophoudelijk zuur maken, dus worden zij ook zo. Maar dat maakt niet uit, jullie zijn Sahaja yogi’s, dus moeten jullie je kinderen een opvoeding tot gehoorzaamheid geven, tot wijsheid, tot sensibiliteit; met dezelfde liefde als die de krokodil voor haar kleine krokodilletjes heeft.

Als we nu bij de subtielere kant van de Ganesha Tattwa komen, dan komt dat in onze ogen tot uiting. Als ik naar sommige dingen kijk, dan zie ik die als iets wat vreugde brengt, wat gewoon blij maakt. En als ik iets wil kopen, dan denk ik: “Goed, ik kan dat voor een bepaald iemand kopen. Hij zal dat mooi vinden, want ik weet waar hij van houdt, dus zal ik dat ding voor die persoon kopen.” Of als ik iets voor mijn familie koop, dan denk ik dat ook.

Zoals ik nu een huis gebouwd heb waar ik alle dingen in ga zetten, de geschenken die jullie gegeven hebben, alles, zoals een museum, en ik ga alle dorpelingen vragen om te komen kijken, want zij hebben zulke dingen nog nooit gezien. Ze kunnen niet naar Zwitserland reizen en Engeland achter zich laten. Dus moeten we – ik denk erover om het huis zo te maken dat deze dorpelingen die nog nooit mooie dingen gezien hebben, zouden kunnen komen kijken. In India is er eigenlijk geen sprake van dat eenvoudige mensen jaloers zijn. Alleen de nieuwe materialistische mensen hebben die hebbelijkheid van jaloezie ontwikkeld. Maar daarentegen zullen ze altijd zeggen: “Wat een mooi ding! Wat prachtig is dat !” Zo zijn ze.

Zo waren jullie liedjes over Sahaja Yoga aan het zingen in Poona. Eigenlijk hebben jullie dat echt heel goed opgepikt, moet ik zeggen, maar er zaten daar meesters van die muziek naar jullie optreden te kijken. Dat waren meesters in drama en toneelspel, heel bekende artiesten in India. En zij zeiden toen: Ah,waar  jullie naar toegingen om naar hun voorstelling kijken, ook in Poona, als je je dat nog herinnert. Zij boden mij dus aan: “Moeder, we willen uw verjaardag komen vieren.” Ik zei: “Dat is moeilijk, want jullie zullen zo ver weg zijn.” “Nee, nee, we zullen komen!” De hele nacht hebben ze gereisd en praktisch de hele dag. Ze kwamen aan om ongeveer 5 uur, stel je voor. Ze beëindigden hun toneelstuk om ongeveer 3 of 4 uur en toen reisden ze de hele dag en arriveerden om ongeveer 5 uur, ergens vanuit Belgam of zoiets, en het programma begon om 6.30u. Ze waren dus allemaal piekfijn gekleed en daar kwamen ze, en hoe ze toen begonnen te vergelijken! Ze zeiden:  “We schaamden ons. We meenden altijd dat wij Maharathi (inwoners van Maharashtria) zo goed in muziek zijn, heel goed in tala’s (muziekritme) en zo. Maar we geneerden ons hoe goed die vreemdelingen onze muziek zongen. Wij kunnen niet zingen zoals zij. Hun muziek kunnen wij niet zingen, terwijl zijn onze muziek wel zongen en we geneerden ons en waren beschaamd. Hoe konden zij zo goed zingen? ” En de waardering was zo groot dat ik zelf in verlegenheid gebracht werd door de manier waarop ze dat vertelden. “Hoe is dat gegaan met die mensen? Wat is – hun guru – wat heeft die gedaan? Wat hebben ze met deze mensen gedaan, dat ze zo goed kunnen zingen?”  Dus de waardering en de heleboel was laaiend enthousiast. We hebben er een bandopname van, denk ik. Een audio opname; ik weet niet of jullie video hebben of niet, maar als jullie dat hebben, dan alsjeblieft krijgen jullie het.

Het is heel boeiend hoe ze mijn kinderen waardeerden, de manier waarop ze zongen. En ik voelde met hen mee in hun uitlatingen en zo, want ze zijn zulke meesters en zo ontwikkeld in hun – de manier waarop ze hun waardering uitspraken, alsof ze kinderen aan het beoordelen waren die iets fantastisch aan het zingen waren.  Kijk – de verstandhouding daarbij was zo van een – een heel lieflijke verstandhouding van vatsalya, wat het gevoel van moederlijkheid is, dat: “Kijk nou toch, die kinderen zingen zo mooi.” Het is bij veel mensen gebeurd die ik gezien heb, dat als er een aantal artiesten kwam, weet je wel, dat als die jullie mensen zagen zingen met toenemende waardering, dat ze dan hetzelfde gevoel hadden: “Hoe konden die kinderen – hoe konden die mensen zo mooi zingen? Hoe konden ze dat zo goed geleerd hebben?” Ik bedoel, al die heerlijke gevoelens en al die waardering creëerden zo’n fijne atmosfeer, omdat we zulke goede artiesten in ons midden hadden die jullie zo waardeerden, in plaats van te zeggen: “Oh, wat een... die zijn niet goed in muziek, waardeloos.” Ze hebben het zo geapprecieerd dat die mensen die nooit Indiase muziek hebben gekend zo goed zingen.

En zo was er in die waardering ook die vaderlijkheid, die moederlijkheid, was er die vatsalya  en de situatie was zo geweldig. Net als, zeg maar, wanneer een persoon als Ravi Shankar met Yehudi Menuhin moet spelen, dan is Yehudi Menuhin een kind ten opzichte van hem. Maar ik heb gezien hoe hij voor hem zorgt en hoe hij hem beschermt, “samhala” zoals we in mijn Hindi taal zeggen. De hele tijd let hij op hem en leidt hij hem. En ook zagen we in het muzikale gedeelte, stel dat er een tabla-wallah zit, een zeer bejaarde muzikant, een meester, dan zal hij zeggen: “Let alstublieft op me, Samhalu, let op me”, altijd met een heel groot besef van een kind: “Let op me.”

Al die dingen zijn heel belangrijk in het leven om ook goede relaties tussen onszelf te creëren. Met degenen die jonger zijn dan wij, die niet zo welgesteld zijn, of die niet zo getalenteerd zijn, of die niet zoveel kennis van Sahaja Yoga hebben, of met degenen die niet zulke anciens zijn in Sahaja Yoga.

We moeten voor de anderen zorgen op een heel vaderlijke manier of, we kunnen ook zeggen, op een moederlijke manier, omdat ze niet de nodige bagage hebben. Goed dan. Wij hebben een Ganesha Tattwa, stimuleer hun Ganesha Tattwa dus. Ze zouden zich afhankelijk van ons moeten voelen om het meesterschap te bereiken of om de hogere staat te bereiken. Omdat het Guru Principe absoluut met het Ganesha Principe verbonden is.

Als een guru niet het Ganesha Principe heeft, dan wordt hij een vreselijke, vreselijke, vreselijke kerel en niemand wil bij hem blijven en ze lopen allemaal bij hem weg. Ofschoon hij straf zou kunnen opleggen, hij zou ook kwaad kunnen worden op de discipelen, maar wat hij eigenlijk denkt is: “Hij is mijn volgeling, ik ben hem aan het ontwikkelen, aan het opbouwen.”

Maar in het moderne denken gaat het: “Laat hen individuen zijn, laat hen onafhankelijk zijn.” En zo zorgen de vader en moeder niet voor hun kinderen zoals ze zouden moeten. “Kijk hier, dit is mijn zoon, ik heb een talent, ik moet hem dat leren, hij moet op gelijke hoogte komen, hij dient een voortzetting van mijzelf te zijn.”  Dus dat idee dat iedereen een eigen individualiteit heeft: jij bent een individu, met achttien jaar ga je het huis uit, dan doe je wat je wilt, dan sta je op je eigen benen. Nee, het leven is een continu uitgangspunt. Het is niet alleen maar dat je op eigen benen staat, maar het gaat erom dat men de hele tijd met het geheel verbonden moet zijn.

Zonder volledig verbonden te zijn, kunnen we de collectiviteit van de onschuld niet begrijpen. De collectiviteit van onschuld zie ik wel eens. Ik ben heel blij als iemands kind soms bij iemand (anders) op schoot zit, daar heel zoet blijft zitten, daar naar toe komt alsof het zijn eigen vader is, daar gewoon op schoot komt zitten zonder zich te realiseren: “Dit is niet mijn vader”. Die bewustheid is er nog niet. Dat verbreekt dus het gevoel van ‘mij en bezit’, dat van: “Dat is van mij, dat is van mij”. En wat leidt tot het gevoel dat we nu een middel geworden zijn, een middel kunnen we zeggen, een instrument, een medium waarmee we de Ganesha Tattwa volledig tot uitdrukking brengen, en dat zijn vibraties. Dus die vibraties zelf, waar je om vraagt, die vibraties zelf zijn niets anders dan het Principe van Shri Ganesha. Hij is de Omkara. En als dat er is, wat is dat dan? Dat gevoel waarover ik jullie vertelde, de vatsalaya, het  gevoel van liefde tussen een kind en een moeder. Dat gevoel, dat is wat de vibraties zijn tussen het kind en de moeder. De ruimte tussen die twee is vibraties en dat is wat iemand moet voelen – dat het nog een kind is en dat daar de moeder is; en moeder brengt het kind mee, geeft het kind alle kracht, voedt het op, houdt van het kind, begrijpt de beperkingen van het kind, zorgt ervoor, dat allemaal. Alle bekoorlijkheid, alle wijsheid van het kind moet je waarderen. Dat zijn vibraties. En als je de subtiele kant ervan ziet, het is niet mijn kind. Dat hoeft niet– het is niet enkel beperkt want het is voor altijd, het is overal, dus kun je het niet inperken.

Bij alles wat jullie doen, heb ik gezien hoe mensen in het Westen met dingen omgaan - wij Indiërs moeten ook van hen leren. Zo moeten we van hen overnemen hoe je ook met mooie dingen omgaat, hoe je voor mooie dingen zorgt, hoe je slaagt in mooie relaties. Kijk, je moet niet hard zijn, je moet niet onvriendelijk zijn en je moet geen dingen zeggen die anderen kwetsen zodat de relaties stuk gaan. Alle relaties die er zijn tussen mensen en God, bestaan  door middel van het Ganesha Principe. Dus als de relatie tussen jou en God op gang komt, dan zijn daar vibraties en dan zou diezelfde relatie zich moeten uitbreiden tot in alles wat je doet. Je zou moeten zien welke dingen goed zijn, welke er vibraties geven.

Nu -vandaag- wil ik jullie graag iets heel belangrijks vertellen over die allesdoordringende kracht waar we over gehoord hebben: dat is niets anders dan vibraties. De Paramchaitanya is niets anders dan vibraties, waarbij elke identiteit wegvalt – waar de moeder verdwijnt, vader verdwijnt; we kunnen zeggen dat er niets anders overblijft dan enkel die vibraties, dat enkel die subtiele vatsalya echt bestaat. Dat is alles. En dat is het enige waaruit alles voortkomt en het enige wat in zichzelf standhoudt. Zoals we kunnen zeggen dat de stralen van de zon opkomen om te proberen chlorofyl te gaan maken. Het is dus niet zo dat we de zon daarmee kunnen vergelijken. Of we kunnen zeggen dat uit de oceaan wolken voortkomen, die Moeder Aarde proberen te voeden. Dat is ook... dat kun je niet vergelijken. Alles zit binnenin.  Deze Paramchaitanya heeft alles in zich. Dus kunnen we zeggen dat alles niets anders is dan kennis, niets dan waarheid, niets dan licht.

Maar als de plooien (van de Paramchaitanya) zich ontvouwen, dan komen we terecht in die plooien van de Chaitanya en dan worden we onwetend (wat betreft de werking van de Chaitanya), maar er bestaat niet zoiets als onwetendheid. Dat bestaat niet, is er niet. Net zoals er duisternis is omdát er geen licht is. Als het licht wordt, dan is het niet donker, dat bestaat niet. Zo is er ook geen onwetendheid. Maar wat er gebeurt, is dat de plooien van die oceaan (van Paramchaitanya), dat mensen daarin verdwijnen en verloren raken. Laten we dus een ding heel duidelijk begrijpen: dat we ons in de Paramchaitanya bevinden. We worden door de Paramchaitanya gemaakt en er voortdurend door omringd. Het enige wat gebeurt, is dat we soms in die plooien verdwalen. En waarom?  Waarom we verloren lopen in de plooien, is wegens ons eigen – ons eigen niet bewust zijn. Dat bewustzijn moet er komen: dat we deel uitmaken van die Paramchaitanya. De hele zaak wordt chitvilasa genoemd, dat is de vilas, de speelse vreugde van Gods aandacht.

Nu zul je zeggen: “Hoe gebeurt dat dan?” We zien bijvoorbeeld de zon – en gewoon om een vergelijking dichterbij te geven - we zien de zon en dan zien we het water. We zien het water in het meer, ja? Er is water – omwille van de zon kunnen we het water zien. Veronderstel dat we dan een fata morgana zien. We zien een fata morgana en denken dan dat het water is, we gaan achter dat water aan. Maar de hele boel is een spel van de zon, ofwel is het een fata morgana, ofwel is het water, ofwel is het de zon.

Op dezelfde manier treedt die Paramchaitanya op en dan raken we de weg kwijt in onze gewaarwording dat we de Paramchaitanya zijn. Daarom begint dat spel, het spel begint net als de puja van gisteren, eergisteren: wat waren we aan het doen? We zaten daar en het begon te regenen. Om zo te testen, te testen of ik de regen kan beheersen. Het regende dus. Sommige mensen  bedekten zich met iets, met zo’n ding. Ik gaf een bandhan. Na een tijdje schoof de regen van de puja vandaan naar achteren. Het regende niet waar jullie zaten. En daarna kwam de zon en was het zo bewolkt. De zon verscheen, het werd zonnig, zo kun je de krachten van Chaitanya gewaarworden.

Als je nou een bandhan geeft, wat je dan doet is de Chaitanya in werking stellen: “Doe hier iets aan, treed daar op, grijp hier in.” Ofschoon je, stel je voor,  je in de oceaan bevindt, maar de oceaan werkt de hele tijd op jou in. Jij kunt niet op de oceaan inwerken, je kunt het water niet vragen om dit of dat te doen. Maar als gerealiseerde zielen heb je macht gekregen, je kunt het water nu vragen: “Goed, je lost dit op, je doet dit en je doet dat.” Maar daarvoor is het belangrijk om meester te zijn. En om meester te worden, zie je, zoals uit stof een menselijk wezen ontstaat, moeten jullie van menselijke wezens meester worden over de stof en de materie beheren. Zo komen we terug op hetzelfde. Zoals we landbouw kunnen beheren, geef het gewoon vibraties.  We kunnen water beheren, we kunnen de zon beheren, we kunnen de maan beheren – want dat houdt verband met elkaar. Nu zijn we ons ervan bewust dat er een verband tot stand gebracht is, en dus is dit hele spel uitermate kostelijk voor mij. Ik zie er op toe.

Maar jullie moeten nu allemaal beseffen dat je allemaal gerealiseerde zielen bent geworden en dat je beschikt over die krachten. Dus alle andere onzinnige dingen die je leert, alle onzinnige dingen waar je  aan toegeeft, die kun je maar beter opgeven. Die hebben geen zin. Wat wel zinvol is, zou je moeten doen omdat Shri Ganesha in jullie aanwezig is, die absoluut bezonnen is. Hij is niets anders dan zingeving. Hij is degene die zin geeft, dus is hij degene die de demonen doodt , zoals men zegt.  Hij is degene die alle beproevingen wegneemt. Hoe dan? Door ons bewustzijn te verbeteren. Beproevingen blijven toch niet voortduren, want je geeft ze een bandhan, dat werkt.

Nu vroeg ik aan iemand – Phil – ik vroeg hem om over wonderen te gaan schrijven, en hij zegt nu dat het een lijvig boek geworden is. Dat zal wel zijn, want wat er vóór de realisatie op een wonder leek is geen wonder meer. Wonderen hebben aan betekenis verloren, want nu zijn jullie krachtig geworden en kunnen jullie ze teweegbrengen. Het werkt in alles: in je talent, in je inzicht, in je opvoeding, in alles.  Zo waren er enkele jongens, die zeiden : “Moeder, ziet u, we konden maar geen oplossing vinden voor ons probleem, dus gaven we het een bandhan. Onmiddellijk kwam er schot in de hele zaak en konden we de boel afwikkelen”,  en waren ze weer waar ze moesten zijn. Velen is dat zo vergaan.

Dus in iedere handeling, in alles wat je maar doet, moet je beseffen dat het de Paramchaitanya is die handelt. Het enige is dat je bewust moet zijn van jezelf en bewust dáárvan (van de Paramchaitanya), dan komt het in actie en dan gaan jullie gewoon mee in dat bewustzijn en dat werkt, en dat hebben jullie gezien. Maar nog steeds weten zoveel mensen dat niet. Zoveel mensen nog altijd - hoewel ze het met hun verstand weten, weten ze het niet met hun hart. En zoveel mensen, ook al weten ze het in hun hart, handelen niet vanuit hun aandacht.

Zo hoeven jullie alleen maar deze drie dingen te verbeteren: het ene is je hoofd, het andere is je hart en het derde is je lever.  Als je deze drie organen kunt verbeteren, dan zal deze Paramchaitanya aan het werk gaan. Maar dan, al die belangstelling voor geld. Zoveel mensen: geld hier, geld daar. Dat is van geen betekenis.  De Paramchaitanya zal alles voor je tot stand brengen, wat je maar wilt. Dat zal dan wel geen geld voortbrengen, want het heeft geen muntslagerij, maar het zal mogelijkheden creëren – mogelijkheden en dat is iets wat heel goed verstaan moet worden, het is zo heerlijk om te weten dat je je nu bewust bent van de Paramchaitanya en dat je er meester over kunt zijn. Meester, niet in de betekenis van dat je domineert, maar dat je er aan kunt vragen zoals aan een goede geest. Je weet dat je kunt zeggen: “Oké, doe dit, doe dat”, met respect. Met respect werkt het, maar de manier waarop we soms geen respect betonen aan de Paramchaitanya is ook wel verbazingwekkend. De manier waarop we alsmaar handelen, de manier waarop we ons gedragen. Zoals in mijn tegenwoordigheid, mensen kunnen gaan zitten en hun ogen sluiten, of ze gaan de foto vereren in plaats van mij. Soms is het de manier waarop ze hun Kundalini behandelen, soms de manier waarop ze zich gedragen ten opzichte van mij en van anderen.

Al die dingen moeten worden begrepen nu we zijn binnengegaan in het Koninkrijk van God, dat wil zeggen de Paramchaitanya, en dat we heel belangrijke bewoners daarvan zijn. Als men dat kan begrijpen, dan denk ik dat Sahaja Yoga heel succesvol kan zijn. Alles zal zijn uitwerking krijgen. Op miraculeuze wijze zal alles uitwerken. En al degenen die zich niet bewust zijn van de kansen op wat ze kunnen bereiken, die worden in zekere zin verstoten binnen de gemeenschap, in onwetendheid, zogezegd in duisternis. Ze kunnen weer terug in het licht komen als ze bij zinnen zijn gekomen. Wees hen dus vergevingsgezind. Het kan jou ook overkomen, als je dat begrijpt.

Ik hoop dat jullie de lezing van vandaag in jezelf hebt kunnen verwerken. Het is heel belangrijk om in je op te nemen, dat je beseft dat je je in de Paramchaitanya bevindt en dat je daardoor heel aardig zult worden, heel vriendelijk zult worden en heel liefdevol, hartelijk en wijs. Dat is heel belangrijk.

Moge God jullie zegenen!