Shri Adi Shakti Puja. Cabella Ligure, Italia. 6 de junio de 2004.


La reunión de hoy es muy especial. También es un día muy especial lleno de bendiciones. El motivo es lo que se habla, canta y dice sobre el nacimiento del orden, el nacimiento del poder, el origen, el "Adi" [Lo Supremo] , lo Primordial y cómo este es responsable de la Creación de este gran Universo. Vosotros ya sabéis por qué ha comenzado y cómo funciona. No necesito hablar de esto.

Pero hoy tenemos que hablar de este poder que está escondido en vuestros corazones y con el que podéis hacer cualquier cosa que queráis, crear un mundo nuevo, una nueva familia, unos valores nuevos, incluso cosas que todavía son desconocidas. Es algo muy posible, es muy posible y se está haciendo.

Pero lo que es difícil es cómo hacer a la gente más adaptable, más en armonía unos con otros. Parece ser una cosa muy difícil. Se encuentran a gusto consigo mismos si se trata de sus propios amigos, su propio estilo, sus cosas. Pero hacerles totalmente Uno, uno con los demás, en la misma sintonía, en la misma línea es muy, muy difícil y no debe hacerse. Se supone que no debe ser, que no se tiene que ser de esa manera. Pero tiene que funcionar.

Ahora el problema es: tenemos hermosas personas, almas hermosas, pero no se hacen una con las demás personas. Entonces, cómo resolver este problema. Mucha gente me ha preguntado. "¿Madre, que hacemos con este problema? Yo simplemente sonrío. Porque si veis la idea original de por qué comenzamos esta radiografía, por qué empezamos este muevo tipo de... comprensión, este nuevo tipo de penetración, fue porque queríamos encontrar la unidad, lo nuevo en cada persona.

Y tendríais que estar agradecidos de que todos vosotros sois uno, uno en el interior, no hay segundo. Solo hay uno y este uno, cuando habla y cuando quiere administrar algo, ¡os llevaríais una sorpresa!, porque todo se hace de la misma forma, es la misma cosa y funciona de la misma manera, no hay cambio, no hay diferencia entre dos.

A pesar de esto, nuestras mentes andan errantes, deambulando en alguna clase de problema que no tiene trascendencia en Sahaja Yoga. Entonces, el problema más importante que tenemos es que no nos damos cuenta de que no tenemos ningún problema. Somos sin problemas.

Pensamos que hay problemas y que tenemos que tratar con problemas, pero no hay ninguno, ninguno de esos problemas existe. Yo no veo problemas en ninguna parte. A aquellos que piensan que tienen problemas les pido que los escriban y yo intentaré contestarles y decirles qué clase de problema es ese.

Pero antes de que pueda hacer nada, me gustaría decir que todavía los sahaja yoguis no han llegado a ese nivel de comprensión de la unidad, de lo único en sus corazones que es la unidad. Todo esto viene de dentro, no de fuera, así que todos los esfuerzos que se hacen fuera no sirven para nada.

Tenemos que ser "sin esfuerzo" y convertirnos en lo que somos. No hay necesidad de tener otra reunión ni de codificar nada, no hay necesidad, todo está ahí. Simplemente tenéis que ser eso, convertiros en eso. Esto es bastante difícil de entender para gente que tiene diferentes narices, diferentes caras, diferente de todo, convertirse en lo mismo. Pero lo sois, lo sois y es porque no sabéis que lo sois por lo que parecéis diferentes.

Así que tengo que deciros una cosa; que todos sois uno. Uno en el sentido de que sois todo, el impulso, cada sensación, cada comprensión es la misma. Lo único es que aparece en un tiempo equivocado, en tiempos diferentes y os da la falsa impresión de que es diferente, pero, en realidad, no lo es.

Solo hay una, una relación, y esta relación es con la Adi Shakti de la que formáis parte, y por mucho que se intente uno no puede separarse de la Adi Shakti. Habéis nacido de Ella, sois guiados por Ella y sois cuidados por Ella. Para mí todo es uno, mientras que vosotros pensáis que hay una línea diferente de enfoque y de acción, lo que es un error.

Todo lo que yo pueda decir debe ser probado, si no, ¿por qué deberíais aceptar esta tremenda afirmación? Yo soy una con vosotros y siempre permaneceré de la misma manera con todos vosotros. Para mí no hay diferencia, yo no veo nada como eso. Es por fuera, solo están vuestros vestidos y vuestro estilo, por dentro tal vez el temperamento que tenéis, depende de vuestro temperamento. Si este temperamento cambia un poco veréis la unidad entre todos vosotros y las diferencias se perderán en poco tiempo.

Hoy vi a un hombre muy peligroso, pensé que podía matarme si quería, podía hacer lo que hubiera querido, pero no, no sucedió. ¿Por qué? Porque nunca le comprendí. El no era así, solo quería expresarme sus respetos, no quería matarme, no quería hacer nada malo. Es sorprendente cómo os percibís unos a otros. Hasta que no tengáis una correcta comprensión unos de otros no alcanzaréis nada de lo que es sobrio, esencial, correcto, de lo que es la Verdad.

La Verdad comenzó hace mucho tiempo, mucho antes de que nadie pudiera pensar en tener aquí una verdad. Se lanzaron tantas cosas que no eran verdaderas que la Verdad se fue. Como la serpiente. La serpiente nació de la ignorancia. Otras serpientes empezaron a apoyar. Serpientes y más serpientes empezaron a crecer y llenaron el universo de deshonestidad y de ideas falsas. Creyeron en ellas y se pusieron a luchar matándose unas a otras, pero todas eran serpientes. Así, ¿cuánto debe uno creer en su sinsentido, cuánto debe uno seguir su sinsentido? ¿Cuánto debe cualquiera aceptar su sinsentido?

Es muy difícil. Pero se acepta mucho más que la Verdad. La Verdad no es tan aceptada como la falsedad. ¿Por qué? Porque hemos crecido en la falsedad. Nuestra comprensión es falsa y tenemos que cambiar esta comprensión a la Verdad, lo que no es muy difícil, porque somos Verdad. ¿Por qué debería ser difícil convertirnos en la Verdad que somos?

No debería, pero sucede. Esto significa que hay algo erróneo en alguna parte dentro de nosotros que debe encontrarse. Y la cosa que está equivocada en nosotros es que no podemos enfrentarnos a nosotros mismos. No podemos enfrentarnos a nosotros mismos. Nos enfrentamos a otros, no a nosotros mismos. Nunca nos vemos a nosotros mismos. No tenemos ni idea de cuál es nuestra situación. Y solo para esto es para lo que necesitáis una Madre que os muestre a vosotros mismos.

Y así es cómo la Madre vino a esta tierra, para deciros cuál es el problema en vosotros, dentro de vosotros. Esto tiene que ser aceptado, este principio debe ser practicado. Y os sorprenderéis de vosotros mismos, de cuánto conocimiento ya tenéis de vosotros mismos y de ese entorno. No hay nada especial, nada extraordinario, lo única cosa es que tenéis que ser aceptables a vosotros mismos.

Pienso que la gente se está convirtiendo en sahaja yoguis, pero no lo están haciendo. No son sahaja yoguis, pero están intentando serlo. Pero por el contrario deberían saber que son sahaja yoguis y que no tienen que convertirse en nada. Entonces no hay ningún problema. Pero una vez que aceptáis que hay... Sahaja Yoga -que es diferente- y sahaja yoguis que son diferentes y vosotros que sois diferentes, entonces, ¿cómo podéis convertiros en sahaja yoguis?

La cuestión es la ignorancia, la ignorancia que tenemos, que nos estamos comportando como extraños unos con otros. Completa ignorancia. Tenemos que saber que todos somos lo mismo. No hay necesidad de tener ninguna ignorancia de ninguna clase. Y cuando esto suceda los problemas del mundo entero se resolverán sin ninguna dificultad.

El Puja de hoy es muy especial, porque estáis haciendo un Puja a algo que nunca vino en ninguna transformación, que no cambió de ninguna manera, que fue siempre lo mismo, permaneció de la misma manera, nació con lo mismo y todavía está con lo mismo. En un Puja así, ¿qué puedo decir? ¿Por qué nadie tiene que decir algo? ¡Nada! Solo, se uno contigo mismo; es el punto al que llegamos. Que tenemos que ser uno con nosotros mismos y no perdernos en las palabras o en la atmósfera u otras cosas de los movimientos de nuestro cerebro. Porque es el momento en que nuestro cerebro comienza a moverse y cuando empieza a moverse pierde el control sobre sí mismo. Como una serpiente, si está en su sitio no hay peligro, pero tan pronto como empieza a moverse es peligrosa. De la misma manera, debemos saber que nuestra mente es muy difícil y que no debe ir en la dirección equivocada.

Por esto debemos hacer el Puja a la Madre Primordial, porque debemos intentar estar en sintonía con la Madre Primordial. Tenemos que permanecer "Primordiales" nosotros mismos. Tenemos que trabajar nuestro "Sí mismo Primordial" y no cambiarnos sin ton ni son. Esto es lo mejor y podemos conseguirlo. Estoy segura de que podemos, no hay problema. La única cosa es que estamos tan conscientes de ser indios, ingleses, europeos y todo eso, pero no lo somos. Somos únicamente nosotros mismos y esto es lo que tenemos que alcanzar, la unidad con nosotros mismos.

Que Dios os bendiga a todos.