Shri Mahalakshmi Puja. Kalwe, India. 30 de diciembre de 1992.

Aquellos que se han pasado la mañana preocupados (por los billetes) deberían entender que os estáis insultando a vosotros mismos. Sois santos, ¿por qué deberíais preocuparos sobre qué avión vais a coger y cuál no? No sé por qué os preocupáis, habéis venido aquí bajo mi protección y volveréis bajo mi protección. Me sentía tan enferma por vuestra preocupación esta mañana, que pensé que quizá no tendríamos ningún Puja. Debéis saber que formáis parte de mi cuerpo, os he puesto dentro de mi cuerpo y debéis comportaros.

Hoy es un día muy auspicioso en el que nos hemos reunido aquí para celebrar este Puja, que debería llamarse Mahalakshmi Puja porque tiene relación con la industria de este país y del mundo entero. Hasta que todas las acciones o empresas humanas no estén relacionadas con Dios, no podrán alcanzar su estado perfecto. Por eso tenemos problemas en Occidente, donde se supone que la gente es muy inteligente, muy sofisticada, con muy buenos equipos para todo, con muchos estudios, etc. Y sin embargo tienen recesión y otros problemas, porque no tienen equilibrio; no saben que existe el Poder de Dios y cuando se menosprecia este poder, esto es lo que os ocurre, que tenéis problemas. Para un trabajo grande de industria, se requiere mucha materia de la Madre Tierra; y cuando se utiliza para un propósito adecuado, con un fin constructivo para ayudar a otros, pero siempre con equilibrio, entonces la Madre Tierra puede pensar y producir más y más de lo que anteriormente había producido. Ella puede producir muchas cosas para gente que es sensata, que está en armonía con Dios y no para la gente que solo se ocupa de sacar dinero para sí misma, o de hacer su propio negocio, sino para aquellos que piensan en una totalidad, que piensan qué se puede lograr con todo esto y así es cómo puede triunfar una industria. Ya habéis visto que también hay una gran industria en Japón, pero no hay espiritualidad, no son gente feliz. Los niños están sufriendo, las familias también. El dinero no aporta todo el bienestar al ser humano. Por tanto debe haber un equilibrio. Gracias a Dios que en nuestro país no ha habido una industrialización tan rápida. Por eso nos hemos librado de muchos problemas que tienen los occidentales y de los que los hindúes no son conscientes. Piensan que allí vivís una vida muy cómoda. Pero la industria tiene que ir mano a mano con la artesanía. Y los que están a cargo de la industria tienen que apoyar a los artistas, porque si no, ¿cómo va a haber arte? El arte es algo que alivia; por ejemplo, las personas que trabajan en esta industria, al terminar escuchan música, el arte de la música, que les reconforta, les da paz, les relaja y les da equilibrio. Por eso la industria debería proteger el arte. Le he dicho a Rajesh que aquí deberían intentar crear algo de artesanía con el acero, intentar algo.

Pero la industria tampoco debe ser mal vista, como ahora en nuestro país, donde los industriales parecen los peores ladrones, y los políticos los santos. Aunque yo creo que es al revés. La industria debe ser tratada con respeto y los industriales deben ser gente iluminada, así pueden hacer mucho bien, no solo a su país, sino a la gente que está a su cargo.

Por tanto, en el Principio de Mahalakshmi, Mahalakshmi muestra varios mudras. Uno es levantando la mano derecha que significa que da protección a la gente que está al servicio de un hombre rico o de un hombre de industria. En India si decís un hombre rico, significa un hombre que abusa de los demás, a nadie le gusta. Porque los hombres ricos siempre han tenido fama de ser los peores; pero en mi experiencia esto no es así, porque hemos visto que un hombre pobre puede ser terrible. Hemos tenido muy malas experiencia en Ganapatipule con gente muy pobre y de muy malos modales. Por tanto debe haber un equilibrio adecuado en el entendimiento entre ricos y pobres, entre pobres y ricos. Después de un tiempo veréis que la pobreza y la riqueza del Espíritu pasarán a ser lo importante. Así serán las naciones sahaja, donde la riqueza del Espíritu, la espiritualidad, la unión con el Divino, se convertirá en la bendición mas grande de todo el mundo. Pero todavía estamos luchando por llegar a ese estado y aún caemos en tonterías y cosas materialistas. Todo esto lo debéis observar cuidadosamente. Si mantenéis este carro del nuevo progreso, progresando cada vez mas rápido, entonces crearemos un mundo de completa armonía, completa paz y amor. Pero para ello, sois vosotros los que debéis hacerlo, yo no puedo hacerlo. Si yo hubiera podido hacerlo sola no os lo pediría. Es como los caballos de un carro y el jinete. Los caballos han de ser conducidos, no es el jinete el que lleva el carro. De la misma manera debéis comprender vuestra responsabilidad, estamos haciendo el trabajo más grande. No estoy hablando simplemente de la industria, del obrero, del capital, sino que estoy hablando de la totalidad del bienestar. Sin duda que todo esto forma una parte de ello. Pero el equilibrio debe estar en la totalidad del bienestar. Una vez que pensáis en esta totalidad, entonces lo primero que debería venirnos a la mente es: ¿Somos capaces de conseguir esa totalidad? ¿Somos capaces de instaurar o crear este bienestar? ¿Tenemos ese bienestar en nuestro interior o no?

Pero todavía estamos preocupados de si llega o no el avión, o si lo cogemos. ¡Somos tan mundanos!, ¡tan pequeños! Con un bandhan podéis controlar cualquier avión, cualquier atmósfera, y todavía estáis aquí preocupados por cosas que están realmente bajo vuestro control. Por tanto, debéis pensar en esta totalidad. ¿Qué es esta totalidad de la que Madre habla? En esta totalidad hay que crear un mundo de personas diferentes y este mundo debe crearlo gente que no tenga miedo ni temores. Este miedo tiene que desaparecer. Detrás de todo este tonto nerviosismo que tenéis, hay miedo. Para ello la Diosa os da protección, bajo su protección estáis más allá de cualquier temor; pero si no queréis creer en vosotros mismos ni en su protección, entonces nadie puede ayudaros, porque todo es mítico para vosotros. En cualquier cosa que emprendáis no debéis tener ningún temor, porque Dios está con vosotros, es un hecho. ¡Probadlo! Pero cuando probáis lo hacéis desde vuestro ego y entonces caéis en el miedo. He visto que la gente egoísta es la gente más asustada y temerosa, y la razón es que ellos atemorizan a los demás y piensan que a ellos les pueden hacer lo mismo cualquier día.

Cuando los ingleses estaban aquí, en los comienzos, todo el mundo temía a los ingleses. Pero ahora en Inglaterra todas las familias tienen miedo de las demás familias. Abren la puerta con una cadena puesta, llenos de temor. Estoy sorprendida de que estos sean los ingleses que una vez nos gobernaron en India y a los que nosotros mostrábamos nuestro desagrado; ahora ellos nos tienen miedo a nosotros. Porque cuando una persona egoísta intenta dominar a los demás, esta misma persona está en el espejo y piensa que son los otros los que le quieren dominar, así es cómo este miedo empieza a penetrar en la mente y a raíz de ello generamos esta absurda inseguridad que proviene de este falso temor. El miedo es creado únicamente por nuestro ego. Una persona que no tiene ego no tiene miedo, porque si no ha hecho mal a nadie, ¿por qué habría de tener miedo? Y una persona así será totalmente cuidada por Dios, porque entonces Dios asume todas sus responsabilidades. Cuando rendís vuestro ego a Dios, Él asume todo, completamente todo. Pero con aquellos que tienen ego, Él dice: "Adelante, protégete a ti mismo con el ego y córtate el cuello". Así que, cuando hablo de la total benevolencia y bienestar hablo de vuestro total bienestar; y lo primero es pues, que el miedo debería salir completamente de vuestra mente si creéis en Dios Todopoderoso. Decimos: "¡Oh, es Dios Todopoderoso! ¡Todopoderoso!", pero lo decimos superficialmente, no desde el corazón. Si creéis que Dios es Todopoderoso y estáis conectados con Dios, entonces, ¿por qué habríais de tener miedo? Pero cuando decimos: "¡No debemos tener miedo!", viene el otro extremo y pensamos que podemos hacer lo que queramos, que podemos hacer lo que sea sin decírselo a nadie, etc. Pero a Dios sí que se lo tenéis que decir, tenéis que informarle de vuestros planes, hagáis lo que hagáis debéis tener su permiso, su consentimiento. Sin embargo pensáis que vosotros mismos sois Dios; pero no lo sois, por eso esta otra parte de la cuestión, el "no tener miedo" crea un tipo de actitud muy arbitraria que es muy peligrosa para Sahaja Yoga, para vosotros mismos y para todos los demás.

El segundo temor que tengo es que, cuando os digo algo, sé que el noventa y nueve por cien de vosotros entendéis que lo digo por vuestro bien, pero hay un uno por ciento de personas que reaccionará porque tiene mucho ego y porque no dan importancia a aquello que es bueno para ellos. No entienden que si les digo algo es precisamente para darles a ellos mismos plenitud, totalidad. Por el contrario adoptan una actitud muy errónea. Uno tiene que desarrollar una cierta indiferencia hacia estas personas que, innecesariamente, se van al extremo de su propia destrucción y que no quieren ver cuál es la esencia de todo lo que yo estoy diciendo. Solo yo puedo deciros qué está mal, ¿quién si no? He de deciros lo que habéis hecho mal y vosotros tenéis que rectificar, tenéis que cambiar. Este es pues otro tipo de reacción, y muestra que no están interesados en su crecimiento ni en el bien de sus hijos ni el de su país, ni el del mundo entero. Entonces preguntaos, ¿por qué estáis en Sahaja Yoga? Desde luego que para ascender, pero ascender, ¿para qué? Supongamos que me traen una bombilla, si no da luz, ¿para qué sirve? De la misma manera, ¿de qué sirve que vengáis a Sahaja Yoga si no podéis ser la luz del Divino? Así que, entre todos vosotros, de todos vosotros, no hay ni uno solo que sea una pequeña persona, lo que ocurre es que no os dais cuenta de lo que sois. Todavía tenéis esos condicionamientos que os hacen pensar que no sois buenos. Pero todos podéis florecer y atender a muchas personas. Si desarrolláis en vuestro interior esa totalidad del bienestar, esto se manifestará en el exterior, sin duda, es un hecho.

La atención es muy importante. La atención debería estar en vuestra autoperfección y en lo que es bueno para vuestra totalidad. Esto es algo que mucha gente no capta y se dedica así a ver defectos en los demás y no en sí mismos. Ahora bien, no entiendo por qué lo hacen. ¿Cuál es el resultado? ¿Qué obtenéis de ello? Si alguien está haciendo algo mal o es negativo; incluso si ponéis la atención en esa persona, ¿qué hacéis al respecto? ¿De qué sirve? Sin embargo, si vosotros tenéis algo mal y lo detectáis, podéis corregiros. Esta es la especialidad de los hindúes: que se dedican a ver los defectos de los demás, pero nunca se dicen, ¿qué hay de malo en nosotros? Constantemente la atención está ocupada en ver los defectos de los demás, entonces, ¿cómo podemos mejorar? Por el contrario, si os dedicáis a ver los defectos de otros, vosotros mismos adquirís más defectos aún. La tendencia a "copiar" está en la naturaleza humana. Alguien ve a otro haciendo algo malo y me dice: "Madre es un sahaja yogui y está haciendo esto y aquello"; pero, ¿quién ha dicho que es un sahaja yogui? El ser sahaja yogui no es ningún certificado, ni un carnet, ni una organización; es un estado que vosotros mismos habéis alcanzado. Cualquiera puede decir que es un sahaja yogui. Yo no puedo darlo. Incluso he visto a algunos, en Sahaja Yoga, que están algo locos, pero como dicen que son sahaja yoguis, pues constan como sahaja yoguis. Pero vosotros mismos tenéis que verificar si sois o no un sahaja yogui, antes de llamaros a vosotros mismos sahaja yoguis, comprobad si lo sois o no. Pero, a pesar de todo, para mí es una gran satisfacción ver que tantas personas han recibido la Realización; nunca imaginé que tantas personas la recibirían, sabía que sería algo en masa pero no esperaba tal resultado. Sin embargo ha ocurrido y ahora espero que alcancéis la posición mas alta, llamada "Athala", imperturbable. Esta es mi esperanza y estoy segura de que ocurrirá.

Os contaré ahora en inglés la historia de Namadeva y Gorakumar. Ya os he contado varias veces cuando Namadeva vio que Gorakumar necesitaba arcilla para su cerámica; se presentó ante Él y le dijo: "Vine aquí para ver a Dios en su forma de Nirakara, es decir, sin forma y me encuentro que Dios ha tomado forma". Este es el gran aprecio que un sahaja yogui debe tener por otro. Cada sahaja yogui es una gema. Incluso solo el pensamiento de la gema os debería traer gozo. En cualquier vida, en cualquier área o lugar o estilo, uno debería tener este sentimiento. Para nosotros todos somos sahaja yoguis y tenemos fe en todas las religiones. Adoramos igual a Rama que a Mahoma. Igual es Brahmadeva que Adi Guru Datattreya. Para nosotros no hay diferencia. No es que a todos les consideremos igual, pero sí les adoramos con el mismo respeto. Por tanto no hay diferenciaciones, tampoco con las nacionalidades. Y cualquier defecto que tenemos vemos que viene de nuestro país. Los mismos sahaja yoguis me dicen "esto es típicamente inglés", "esto es típicamente francés o italiano". Pero la cosa más importante que debemos entender es que en Sahaja Yoga hemos perdido todas estas limitaciones. Hemos alcanzado el estado en el que todos somos "Uno". Y la sola idea o el pensamiento de un sahaja yogui individual o un grupo de sahaja yoguis, os debería llenar de gozo, deberíais sentir el gozo como una ola que viene constantemente. Porque vosotros, los sahaja yoguis, estáis bajo la forma de gozo, de paz. Si habéis logrado este tipo de aprecio por los demás sahaja yoguis, entonces, y solo entonces, podéis decir que sois sahaja yoguis. Y esta es una de las pruebas que debéis pasar. A mí me amáis mucho, lo sé, pero hasta que no os améis entre vosotros, ¿cómo vais a ser felices?

Así que, hoy es un día especial porque el Principio de Mahalakshmi despierta dentro de vosotros y así salís del Principio de Lakshmi, que quizá os hace un poco egoístas e individualistas; ahora entráis en una nueva dimensión de búsqueda, una búsqueda de un sistema de valores de un nivel superior; algo que está más allá, sin limitaciones. Y este Principio de Mahalakshmi, no es otra cosa que vuestra búsqueda del Amor Universal. En su esencia es esto. Normalmente no amamos a ciertas personas porque son de tal país o son de otra organización, todo esto ya no existe para nosotros. Amamos a los demás simplemente porque somos parte del Todo y parte de ellos; somos Uno con ellos.

Así que, los que hoy estáis adorando a Mahalakshmi debéis ver cuántas personas están adorando a Mahalakshmi; y todos ellos son una parte de nosotros. ¡Es un sentimiento tan grande!

Si no, como ocurre especialmente en Maharashtra, un sahaja yogui va a hablar de Sahaja Yoga a un distrito y el líder de ese distrito empieza a pelearse con él diciéndole: "¿A qué has venido tú aquí? ¿Qué derecho tienes? Yo soy el líder de este lugar". Todo esto en lugar de respetarle, de darle la bienvenida como invitado, pidiéndole o preguntándole en que le podría ayudar; sin embargo se pelean bruscamente. Es sorprendente.

Cuando Namadeva fue al Punjab, Guru Nanak le respetó mucho y no solo eso, sino que le pidió que escribiera también en punjabi (idioma del lugar). He visto un gran libro escrito en punjabi por Namadeva, donde incluyó todos los grandes santos de Maharashtra, porque Él sabía que eran almas realizadas, almas superiores. Los sikhs lo leen pero no queda nada en sus cabezas. ¿Qué se puede hacer?

Así que, si en aquellos tiempos los santos podían quererse entre ellos, y podían expresarse de esa manera, ¿por qué no nosotros, los sahaja yoguis del mundo entero? Ahora tendremos el baile de Ras, donde los sahaja yoguis de fuera bailarán con los sahaja yoguis de India, bailarán todos juntos. Así que, no os sentéis en grupos, mezclaros con los demás, conocerles. Así es cómo vamos a conocer a todos los sahaja yoguis del mundo entero. Para mí es muy importante que os améis entre vosotros. Esto será lo que mayor alivio me dé, lo que mayor gozo me dará; será para mí el mayor logro y significará el sentido completo de mi vida. Si alguien está verdaderamente en un error o hay algo mal en esa persona, escribidme y decídmelo; yo lo sabré inmediatamente por las vibraciones. Nadie puede engañarme, os lo aseguro. Alguien dice a veces: "Tal persona le ha dicho esto a Madre", pero nada se le puede decir a Madre, soy demasiado "astuta" para todo esto, no os lo podéis ni imaginar. Nadie puede decirme nada, yo juego un poco aquí y allá, pero conozco a la perfección a cada uno de vosotros. Os doy una oportunidad durante un tiempo, pero no penséis que alguien puede engañarme diciéndome alguna cosa de otra persona. Yo escucho a todo el mundo, ¿por qué no probáis a hacerlo vosotros también?

Si amáis a otro sahaja yogui, el mismo proceso de este amor, el mismo hecho de amar da mucho gozo. Cuando me visteis por primera vez en el escenario, os sentisteis así porque este proceso de amor es lo que mayor gozo da. Así que, sed felices, si algunas personas pierden el avión no pasa nada, se pueden quedar aquí con otros sahaja yoguis; después de todo os encontráis aquí, en un "lugar del mundo"; no estáis perdidos. Incluso si "estáis" allí, ¿qué importa?, ¿por qué es tan importante tener la reserva de este avión, salir a esta hora, etc.? No hay necesidad de esta preocupación. Dondequiera que estéis, estáis con sahaja yoguis, entonces, ¿por qué preocuparse? La cuestión es que vosotros "SOIS". Mucha gente me pregunta, "Madre viajas tanto, ¿cómo es que no estás cansada?" Pero yo no pienso que viajo, solo pienso que "YO SOY", eso es todo, tanto si estoy en el avión, como aquí o allí, simplemente SOY. A veces me tengo que decir a mí misma que estoy viajando. Y de nuevo se me olvida. Así que, vosotros SOIS, tanto si estáis aquí, como en Inglaterra o en cualquier parte. ESTÁIS aquí, SOIS. ¿Por qué preocuparse?

Esto ocurre especialmente con los aviones, creo que los occidentales tienen un problema genético. Creo que el avión entra en sus Kundalinis y se desesperan de una manera increíble; esto de los aviones es algo que nunca he podido entender. Les he dado tantas lecciones acerca de esto, pero todavía continúan comportándose de la misma manera. Si les digo esto se sienten culpables, pero luego lo repetirán. La próxima vez, si vuestro avión es a las 8 a.m., id al aeropuerto a las 9 a.m. El avión os esperará hasta las 10. Os lo aseguro. Esto ya ha ocurrido, muchos pueden contar esto. Hay muchas experiencias que no hemos escrito; pero la gente sabe que muchos aviones se han retrasado solo por esperarnos a nosotros. Yo nunca he perdido un avión y si esto ha ocurrido ha sido con un propósito y algo grande había detrás de ello. Es importante saber que es una obra de teatro.

Solo deberíamos tener una preocupación y es: "¿POR QUÉ NO PUEDO AMAR A LOS DEMÁS COMO ME AMO A MÍ MISMO?"

Os aseguro que es solo este Amor Universal el que os puede dar confianza y ese estado superior. ¿Por qué aquellos santos sufrieron por vosotros? ¿Por qué Cristo o Mahoma sufrieron por vosotros? ¿Por qué hablaron del dharma? ¿Por qué Ganeshwara escribió Ganeshwari? ¿Por qué? ¿Qué obtuvieron de ello? SATISFACCIÓN. La satisfacción de haber expresado su Amor Universal. Todo lo que han hecho los grandes poetas, como William Blake, lo han hecho porque tenían este amor universal y querían expresarlo. ¿Por qué no hacéis esto vosotros?

Si queréis mantener la llama del Principio de Mahalakshmi encendida, entonces aseguraos de que amáis a todos los sahaja yoguis. Este es el mensaje de hoy y espero que lo entendáis.

Que Dios os bendiga.

Os pediría a los niños extranjeros y a todos los extranjeros que vengáis a tantos pujas como podáis, debéis saber eso. Pero los hindúes, apenas van a un puja aquí y allá. Tampoco los niños tienen más oportunidades. Así que dejemos que esta vez los niños hindúes vengan delante ¿de acuerdo? Y las mujeres hindúes también. Gracias.