21 marca 1993
Urodzinowa Pudźa
Nowe Delhi (Indie)

Bardzo trudno mi mówić, nawet dla Mnie widzieć tylu Sahadźa Joginów siedzących tu z tak promiennymi twarzami z całego świata, jakby Moja wizja dziś przybrała formę.

Widzę w was zbawicieli jutra którzy mają ocalić ten świat przed wszystkimi katastrofami Kali Jugi które nas otaczają. Nadchodzi ze wszystkich stron, podczas gdy wy naprawdę doświadczyliście drugich narodzin z tego stawu Kali Jugi i naprawdę staliście się pięknymi lotosami o różnych barwach, odcieniach, zapachu i urodzie. Zamiast tego, żebyście obchodzili moje urodziny, lepiej, żebym Ja obchodziła wasze urodziny. Jak mówiłam wam niedawno, że to wy jesteście tak wielkimi poszukiwaczami, poszukiwaczami prawdy i miłości, że to mogło się udać, w przeciwnym razie byłoby to niemożliwe. Nawet przemiana jednej osoby jest bardzo trudna, ale wy byliście tak wrażliwi i tak głęboko duchowi, że ta subtelna wiedza, nie wiem, jak przeniknęła do waszej istoty. To niewiarygodne. Nie mogę sama uwierzyć, jak wielcy ludzie rodzą się w tej Kali Judze. Nikt nie może uwierzyć, że jest ich tak wielu świętych mędrców zasiada przed Mną, tylu Wali; tylu Nali zasiada przede Mną. W historii duchowości to nigdy się nie zdarzyło. Nawet w niebiosach jest niewielu devatów i dew, nie tak wielu.

Jeden lepszy od drugiego tak piękne serce, tak genialne umysły i taka aktywna uwaga, naprawdę dziękuję wam wszystkim, że na te siedemdziesiąte urodziny mogłam zobaczyć tyle ludzi, jakich nigdy się nie spodziewałam. Wiecie, Sahadźa Joga rozpoczęła się od jednej osoby a potem przyszli także inni, z nich, niektórzy byli nastawieni na władzę, na pieniądze, różnego rodzaju ludzie stwarzali nam problemy. Jeden po drugim, pojawiało się tyle problemów a także było wielu, którzy byli poszukiwaczami bardzo niskiego poziomu. Ale widzę dzisiaj, że wszyscy oni pięknie się rozwinęli. Nie potrafię odróżnić jednego od drugiego, tak, jak to się stało. A zaangażowanie, jakie macie w Sahadźa Jodze jest największym błogosławieństwem dla tego świata. Nie mogłam tego dokonać sama. Wiecie o tym. Gdybym mogła, nie potrzebowałabym was. Jesteście kanałami i musicie to rozwijać coraz bardziej.

Naprawdę niezwykły jest sposób w jaki ludzie z Delhi wszystko zorganizowali. Przede wszystkim, wszyscy byli bardzo skupieni na siedemdziesiątych urodzinach. Nie wiem, co było przyczyną, ale cokolwiek to było, a potem ludzie z Delhi powiedzieli, "Tym razem zamierzamy świętować, Matko, Twoje urodziny w Delhi." Powiedziałam: "Wszyscy są zaangażowani, więc uważajcie, to nie będzie łatwe. To wielki kłopot. Tak wielu przyjdzie." Ale oni nie spodziewali się tyle, jestem pewna ... ludzie przychodzą. Setka przychodzi stamtąd, setka z tamtego miejsca. Powiedziałam: "Czy się martwicie?" Odpowiedzieli: "Nie, jesteśmy z tego bardzo szczęśliwi."

Widziałam ich entuzjazm, ich organizację, sposób, w jaki to zrobili. Najlepsza część tego wszystkiego, Delhi, które jest miejscem, gdzie mieszkają wszelkiego rodzaju politycy, mają ugrupowania i politykę, i to wszystko, ale w Sahadźa Jodze w Delhi nie ma polityki. Nie ma kłótni. Nie ma wzajemnego dokuczania. To naprawdę niezwykła rzecz że dzieje się to w miejscu takim jak Delhi, gdzie codziennie słyszycie że nawet w naszym parlamencie biją się nawzajem. Być może tylko w tym piekle, ta dobroć miała się narodzić i aby została objawiona przez Sahadźa joginów. Wiedza Sahadźa Jogi, jak wiecie, jest niezwykle, niezwykle subtelna i nie jest łatwa przeniknąć do tak zwanych ludzi, którzy nazywają siebie intelektualistami lub którzy są całkowicie podporządkowani swoim uwarunkowaniom. Tak więc, z jednej strony, mamy masy ludzi nieświadomych, a z drugiej strony, klasy, które żyją w ramach które sami wykreowali ze swoich umysłów. Obie te drogi, jak sądzę, są niezwykle przyziemne. Ale sposób, w jaki przyswoili ten subtelny nektar boskości, jest czymś niewiarygodnym.

Nikt nawet nie potrafi pojąć że tak wielu narodziło się po Moich narodzinach, na tej Ziemi, albo niektórzy być może nawet wcześniej, bardzo nieliczni. Zaraz po Moich narodzinach urodzili się tutaj w tym świecie, aby osiągnąć Sahadźa Jogę. Ale kiedy zobaczyłam świat, byłam w szoku, bardziej w szoku niż sam Kabira. Powiedziałam: "Jak mam o tym mówić komukolwiek?" Moi członkowie rodziny, nie wiedziałam, jak rozpocząć ten temat z nimi. To było niemożliwe, tak wielka była ciemnota ignorancji. Jak mogą uwierzyć, że naprawdę istnieje boskość, że czeka na nich pełnia? Wszyscy wierzyli w pewną religię, która nie miała nic wspólnego z rzeczywistością. I nawet było niemożliwe wyobrazić sobie sposób, w jaki mogłabym z nimi rozmawiać. Pamiętam pierwszy incydent kiedy udaliśmy się do Nargol, gdzie otworzyłam Sahasrarę.

Pierwszą osobą, która dostała Realizację, był Gudźarati i jubiler. Natychmiast wszyscy inni, było ich ledwo około trzydziestu pięciu, zaczęli mówić, że "Oczywiście, że jest bogaty, że jest jubilerem, więc Matka obdarzyła go oświeceniem." Myślę, że to był pierwszy i ostatni raz, kiedy naprawdę się zdenerwowałam. Zaczęłam na nich krzyczeć, "Jesteście do niczego, bezużyteczni ludzie, nigdy nie przyjmiecie Boskości," i naprawdę pomyślałam: "Przestańcie teraz." Trzeba wziąć kolejne życie, kolejny raz, kiedy ludzie zrozumieją, czym jest Sahadźa Joga. Ale potem, nagle, ludzie zaczęli odczuwać chłodny powiew w swoich dłoniach, natychmiast po moim krzyku. Wyobraźcie sobie. I mówili: "Matko, zobacz, to działa. Działa w nas. Działa na zewnątrz nas."

W ten sposób mieliśmy dwunastu ludzi i jedną panią, której już wcześniej dałam samorealizację, ona była czternastą. Tak więc, początkowo mieliśmy tylko tych czternastu Sahadźa Joginów, dla których to było zupełnie niespodziewane. Wszyscy byli zdumieni. Nie wiedzieli, czym to było. A potem, ku zdziwieniu, na jednym z naszych programów, przyszła pani, opętana przez pewnego bramina, i zaczęła mówić: "Dźagadamba, Dźagadamba." Nie mogli zrozumieć. Nigdy im nie powiedziałam, kim jestem, nigdy. Wcześniej też im nie mówiłam. Więc potem recytowała wiersz z Saundarya Lahari w sanskryckim języku a była tylko pokojówką. I w męskim głosie.

Wszyscy byli w szoku że buce miałyby mówić te wszystkie rzeczy. A potem odeszła. Po tym, ci ludzie zaczęli to zgłębiać. I chcieli mieć Moje Pudźe, po raz pierwszy, bezpośrednio w Moim domu. Wciąż ludzie nie byli pewni, czy robią to, co właściwe. Nawet braminów, których przywoływali, mówili, "Ta Saptasadi jest bardzo trudną Pudźą i coś nam się stanie." Ale po Pudźy mówili, "Nic się nie stało, czujemy się o wiele lepiej." Wszyscy poczuli chłodny powiew i cała atmosfera się zmieniła. Zaczęli rozumieć, że Sahadźa Joga to Juga Dharma, jest tym tej jugi, tej Kali Jugi, więc Sahadźa Dharma stała się dharmą tej jugi. Ta juga jest bardzo trudna, bez wątpienia.

Ale to właśnie w trudnościach stajemy się intensywnymi poszukiwaczami i to właśnie wam się przydarzyło, że odkryliście, że wszędzie ludzie podążają za tym, czemukolwiek podążają, nie osiągają żadnego rezultatu. Jak kokon, uderzają się głową tu i tam. Osiągnęli realizację tak szybko, i kiedy mi mówili, jak poszukiwali, co się z nimi działo, byłam zdumiona. Jak to poszukiwanie działało w nich i popychało ich ku Sahadźa Jodze. Również, w międzyczasie, muszę powiedzieć, tak wielu zagubiło się w sidłach fałszywych guru. Pomimo tego, dzisiaj mamy tylu Sahadźa joginów. Reprezentujecie tylko swój kraj, ale w waszych krajach jest ich znacznie więcej. Nawet w Indiach mamy ich znacznie więcej. Jesteście tu tylko, aby ich reprezentować. Tak więc, wielokrotność tej liczby, nie wiem, ile ich będzie.

Wielu pytało: "Ile jest Sahadźa joginów?" Powiedziałam, "Nie wiem." "Nie wiesz?" Powiedziałam: "Nie. Nigdy nie prowadziliśmy żadnych rejestrów." Więc oni nie mogą zrozumieć. Powiedziałam, "Nie mamy biura, nie prowadzimy rejestrów. Nie mam sekretarki. Nie umiem pisać na maszynie. Nawet swojego czeku nie potrafię wypisać."

Oni nie mogą zrozumieć osoby takiej jak ja, istniejącej w tych nowoczesnych czasach. Ale wszystko jakoś się udaje. Pomimo całej mojej współczesnej niewiedzy, wszystko zostaje absolutnie zrobione w najbardziej doskonały sposób jak pilot zdalnego sterowania. Teraz to wszystko, nigdy o tym nie mówiłam, muszę wam powiedzieć - nic. Nigdy nie dałam żadnej wskazówki, jak to powinno być. Nawet nie powiedziałam im, ilu się spodziewamy. Ale spójrzcie, jak spontanicznie wszystko się ułożyło ponieważ wy wszyscy macie zaangażowanie a to zaangażowanie daje wam wszystkie te zdolności organizacyjne. Widzieliście, jak wiele rzeczy zostało zorganizowanych ponieważ również Paramczajtanja nadeszła do Krita Jugi gdzie to działa. To się dzieje. A ta aktywność również was całkowicie wspiera.

Na przykład, policja nam powiedziała, że mieszkają tu muzułmanie i możecie być przez nich zagrożeni. Mogą wam zaszkodzić. Powiedziałam: "Którzy to muzułmanie?" Odpowiedzieli: "Ludzie Nizamuddin Aulia są tutaj." Powiedziałam: "Oni nigdy nam nie zaszkodzą." "Dlaczego? Bo był sufim i był wielką, oświeconą duszą a ludzie, którzy tam są, muszą być, przeważnie, przynajmniej wyznawcami sufizmu. Jak oni mogą nam zaszkodzić?" Więc powiedziałam: "Jutro, wcześnie rano, idźcie i załóżcie chador, jak to nazywają, wszyscy," i byli tak pod wrażeniem, że wieczorem zobaczyliście, że przyjechali aż tutaj, rano, i byli bardzo pełni szacunku. Potem wezwali Mnie, dali Mi kolejny chador, ten, tamten, i mówili, że jesteśmy Twoi, to i tamto, i wszelkiego rodzaju rzeczy.

A jego uczniem był Amir Khusrau, był kolejnym, bardzo, bardzo wielkim sufickim dżentelmenem i zawsze podziwiałam jego poezję oraz sposób, w jaki Nizamuddin prowadził swoje życie z godnością i boskością. Wszyscy ci muzułmanie, którzy tam byli, kładli ręce ku Mnie w ten sposób i mówili: "Czujemy chłodny powiew," Powiedziałam: "To jest Ruh." "Ach, to jest Ruh." Gdy tylko ci ludzie zaczną otrzymywać Ruh, wszyscy bardzo szybko staną się Sahadźa joginami i być może będziecie musieli mieć ... Na całym świecie jest tylu sufich i zamierzamy zebrać ich adresy i spotkać się z nimi; wtedy być może będziecie musieli zorganizować kolejny duży pendal, podwójny pendal, myślę, może potrójny. Jeśli ludzie z Delhi nie boją się tych rozmiarów, to myślę, że znów będziemy musieli to zorganizować wyłącznie w Delhi. Również współcześnie, Delhi znajduje się w stanie zamętu i powinniśmy być tu, aby je uspokoić, aby je uciszyć, aby przekazać mądrość tym ludziom którzy mają kierować sprawami. Zadziała. Z pewnością zadziała. Z tymi wszystkimi Sahadźa joginami emitującymi tak piękne wibracje. Zobaczcie, na waszych głowach ta tkanina cały czas porusza się w górę i w dół, choć na zewnątrz nie ma wiatru, liście są po prostu nieruchome, ale z waszych głów, widzicie, to wszystko się porusza.

Więc jestem pewna, że te wibracje uspokoją atmosferę i przyniosą pokój naszym politykom oraz ludziom którzy kierują sprawami. W tym momencie, gdy na całym świecie dzieje się tyle rzeczy niepewności, na przykład w Rosji, są niepewności, w Bośni są niepewności, w Anglii panuje recesja, w Ameryce panuje recesja, w Hiszpanii panuje recesja, wszyscy cierpią z powodu udręk pewnego rodzaju skrajnego zachowania, w które wpadli. Więc jestem pewna, że ta polaryzacja którą teraz widzą, skoryguje ich zachowanie wobec materializmu i jestem pewna, że zostanie osiągnięta równowaga. Z waszymi dobrymi życzeniami, z waszymi modlitwami, ten świat będzie tak piękny, tak czarujący, że w historii, ludzie będą opisywać że sam świat stał się lotosem pełnym zapachu boskości. Jesteście płatkami, jesteście koroną, jesteście kolorem, jesteście pięknem, jesteście pyłkiem tego pięknego lotosu który jest moją wizją tego świata. Mam nadzieję, że dziś wszyscy postanowicie pracować dla Sahadźa Jogi, rozpowszechniać Sahadźa Jogę i pracować również dla siebie. Jedynym niebezpieczeństwem jest że nie powinniście dopuścić, aby ego zasiadło na waszych głowach. To jest jedyny koń. Jeśli potraficie sami jeździć, a nie pozwolicie, by koń was jeździł, będziecie posuwać się naprzód bardzo szybko, pięknie. Dlatego jestem pewna, że Sahadźa Joga się rozpowszechni.

Na każde urodziny musimy złożyć przysięgę. Nie wiem, jaką przysięgę powinnam złożyć. Ludzie mówili mi, że nie powinnam pracować tak ciężko, ale ja pracuję bardzo ciężko, ale złożyłam przysięgę, że będę pracować podwójnie ciężko. W ten sam sposób wy również, wszyscy musicie dziś złożyć przysięgę, że damy z siebie wszystko w zaangażowaniu w pracy dla Sahadźa Jogi. Pomyślimy o tym. Są naukowcy, którzy powinni pisać książki, są lekarze, którzy powinni pisać książki, pisma, przemierzać, rozmawiać ze swoimi kolegami, organizować spotkania, seminaria ze swoimi kolegami. Są architekci i inni profesjonaliści, którzy mogliby wezwać swoich kolegów i obdarzyć ich Samorealizacją. Nawet osoby zajmujące się finansami powinny się oddać Sahadźa Jodze. To bardzo ważne, ponieważ problemy finansowe mogą być rozwiązane tylko przez Boską Siłę. Nikt inny tego nie rozwiąże.

Więc każdy na tym świecie, czy to prawo, czy jakakolwiek inna dziedzina, wszyscy powinniście zająć się Sahadźa Jogą oraz pracy twórczej. Ponadto, musicie rozpowszechnić Sahadźa Jogę w swoim otoczeniu, we wsiach, w miastach, gdziekolwiek to możliwe, gdziekolwiek możecie zorganizować, musicie rozpowszechniać Sahadźa Jogę wszędzie. Jeśli chodzi o leczenie, radziłabym, nie musicie nikogo dotykać. Proszę, używajcie tylko moje zdjęcie. W ten sposób pozyskacie więcej Sahadźa joginów i mniej chorych ludzi. Również ludzie zostaną wyleczeni i wszyscy oni staną się Sahadźa joginami. Mamy również rolnictwo w którym coś zrobiliśmy, ale w rolnictwie można zrobić znacznie więcej. Trzeba zwrócić się do rządu i powiedzieć im, co rolnictwo może osiągnąć. Możecie utworzyć komisję i udać się do nich i porozmawiać z nimi, że jak rolnictwu może pomóc Sahadźa Joga. Musimy pomóc naszym dzieciom.

Musimy o nie dbać, bo wiecie, jaka przyszłość ich otacza, jaką atmosferę mają wokół siebie, nawet w Indiach. Dlatego musimy zadbać, aby nasze dzieci odpowiednio dorastały w kulturze Sahadźa. To jest bardzo ważne ponieważ oni są jutrzejszymi Sahadźa joginami. Tak wielu z nich rodzi się zrealizowanych, więc musimy ich odpowiednio zdyscyplinować i musimy uczynić z nich aala, "aala darza" Sahadźa jogin, jak opisano w qawwali. Również nasze życie rodzinne jest bardzo ważne. To szokujące, że życie rodzinne obecnie staje się czymś głupim. Nikt nie rozumie jego znaczenia. W Sahadźa Jodze musimy to zrozumieć. Błahe kłótnie, spory, należy porzucić. Surowość należy porzucić, okrucieństwo należy porzucić na początek powinna być właściwa relacja między mężem a żoną, aby istniała więź towarzyska i aby dzieci również widziały tę więź i czerpały z niej radość.

W naszym ubiorze, w naszym życiu, musimy być godni i przyzwoici, szanując nasze ciało. To jest bardzo ważne. Powinniśmy nosić to, co nam odpowiada w jakimkolwiek kraju jesteśmy. To znaczy, wyobraźcie sobie, w letnim klimacie jeśli ktoś chce nosić garnitur trzyczęściowy, co mu się stanie? Cokolwiek nam odpowiada, cokolwiek pasuje do naszej kultury, należy starać się nosić przyzwoite stroje, tradycyjne stroje. Szczególnie dla kobiet jest bardzo ważne nosić stroje, które sprawią, że będą wyglądać bardziej godnie. Również, jeszcze jedna kwestia, którą chciałabym poruszyć, że panie, szczególnie, muszą zacząć czytać, przynajmniej gazety. Jeśli wasza uwaga skupia się na problemach które występują w tym świecie, to jest bardzo skuteczne ponieważ wiecie, że wasza uwaga jest aktywna, działa. Więc używajcie swojej uwagi. Czytacie gazety, oglądacie – wiem, że czasami to przeraża możecie dać bandhan, ale musicie zobaczyć, co się dzieje gdzie, to jest bardzo ważne.

Również mężczyźni nie powinni czytać tylko czegoś sensacyjnego, ale czytać to, co się dzieje i również zastanawiać się, jakie są rozwiązania. Jak wy, jako Sahadźa jogini, możecie temu pomóc, w sposób kolektywny lub indywidualny. Musimy rozwiązać wiele problemów tego współczesnego świata. Również trzeba czytać dobre książki, dobre filmy trzeba oglądać, i przemyśleć je. Utrzymujcie umysł czujny. Przeczytałam ostatnio wiele pięknych wierszy, pochodzących od pewnych ludzi, od których nigdy się nie spodziewałam, że napiszą wiersze, piękne, bardzo wysokiej klasy. Więc tę poezję również zbierzemy. Zbierzemy wszystkie cudowne fotografie ze wszystkich stron. Teraz starają się je usystematyzować. A teraz, w tym systemie, jeśli wszyscy możecie spontanicznie pomóc, będzie to wielkim osiągnięciem ponieważ jak dotąd nie byliśmy w stanie zebrać wszystkich tych danych i przechować je u siebie.

Najlepsze jest to, że wszyscy musicie medytować. Wszyscy musicie medytować. Tylko w medytacji jesteście w teraźniejszości i rozwijacie swoją duchowość. Mówiłam to wielokrotnie, ale ludzie po prostu tego nie robią. Około dziesięciu minut, jeśli moglibyście pomedytować przed snem, to jest dla was ogromną pomocą, bez wątpienia. Naprawdę rozwijamy się bardzo szybko. Natychmiast wiem, że ten człowiek medytuje, sposób, w jaki się zmienił. A potem, kiedy się do tego przyzwyczaicie, nigdy tego nie porzucicie. To bardzo prosta medytacja. Macie moczenie stóp lub coś podobnego a rano powinniście bić swoje ego, to wszystko.

Nie chodzi o to, że musicie robić sto tysięcy jappas czy coś takiego. Nic z tego rodzaju. To jest bardzo proste. Ale to musicie robić dla siebie, aby szanować swoją Samorealizację i rozwój duchowy. Mamy wiele zalet w porównaniu z innymi. Ale jedno muszę wam powiedzieć, z ludźmi, którzy nie mają skłonności do poszukiwania, proszę, nie rozmawiajcie z nimi o Sahadźa Jodze. Nie marnujcie swojej energii na takich ludzi, rozmawiając i spierając się, bo nie da się tego wiele przedyskutować. Po prostu o nich zapomnijcie i zostawcie ich w spokoju. Ja się nimi zajmę. Skupcie się tylko na prostych, dobrych ludziach, którzy poszukują prawdy.

Nie chcę, abyście się trudzili się z tymi ludźmi, którzy tylko wierzą w dyskusje, argumenty i shabda jaal (słowotok). Dziś kultura Sahadźa Jogi tak bardzo się manifestuje, że ludzie, gdy was zobaczą, natychmiast wiedzą że jest w was coś wyjątkowego i że posiadacie coś bardzo unikalnego cechy, których rzadko można znaleźć u zwykłych ludzi. Wszystko to, powinniście zrozumieć, przyszło do was spontanicznie z wnętrza, ale musicie je zachować i nigdy się ich nie wstydzić. Nigdy nie powinniście wstydzić się swoich cnót. A cokolwiek ludzie będą próbowali mówić wam: "Lepiej zróbcie to i lepiej zróbcie tamto," jeśli to jest złe, nigdy tego nie róbcie. Bo teraz jesteście bardzo potężni Wystarczy, że powiecie: "Nie chcę tego robić." i że to wy musicie prowadzić ludzi a ludzie nie muszą was prowadzić. Mody nie mają was prowadzić, ale musicie tworzyć mody. Musicie stworzyć dla nich ścieżkę. Nie chodzi o to, że macie kroczyć ścieżką, którą oni wydeptali.

Spróbujcie zrozumieć że wasza własna osobowość jest na takim poziomie, że możecie dostrzec tak wiele subtelnych rzeczy i jesteście tak potężni, że inni tego nie dostrzegają, wtedy musicie automatycznie przejąć ich przywództwo. Nie czerpcie od nich pomysłów i nie dajcie się przestraszyć gdy próbują wam coś powiedzieć przeciwko wam lub przeciwko Sahadźa Jodze. Bądźcie pewni. Bądźcie pewni siebie. W ten sposób wszystko się wypracuje. Jestem tylko kobietą i gospodynią domową, ale byłam tak pewna Sahadźa Jogi że to się udało. Nie musiałam, zastanawiać się, czy powinnam to robić, czy nie. Po prostu to zaczęłam. Chociaż w rodzinie nie cieszyło się to dużym szacunkiem, nie było zbytnio akceptowane, nie ma to znaczenia. Zaczęłam to wszystko sama, sama to zrealizowałam, ponieważ miałam pełne zaufanie do prawdy, że jeśli opieram się na prawdzie, to mi pomoże i pomoże wszystkim, którzy do Mnie przyjdą.

I tak się stało. Więc dla was to wcale nie powinno być trudne. Przede wszystkim wszyscy powinniście sprawdzić, czy nie macie uwarunkowań i że nie macie ego a potem powinniście to kontynuować i zdziwią was rezultaty. Dzisiejsza pudźa jest bardzo krótka. Dlatego dałam wam długi wykład. Jest tyle rzeczy, których nie mogę w tym krótkim czasie wam powiedzieć ale jeśli usiądziecie, możecie łatwo stworzyć jeden, dwa, trzy, cztery, pięć, sześć, siedem, osiem sami. Więc teraz skupcie się na tym w taki sposób, abyście byli organizatorami. Co więc powinniście zrobić? Co możecie zrobić? Co zamierzacie osiągnąć?

Proszę, spróbujcie, a to się uda. Wszyscy możecie to zrobić. Myślę, że najlepiej jest prowadzić dla siebie dziennik i zapisywać w nim: co zrobiliście, ile osób otrzymało od was Samorealizację, ile zostało wyleczonych, co o nich myślicie. Ale teraz, jeśli nie macie dziennika, Sahadźa jogini powiedzą, "Matko, nie mamy dziennika, więc zaczniemy jutro." Nie, zacznijcie dzisiaj. Jedyny problem z Sahadźa joginami polega na tym, że podchodzą do rzeczy zbyt swobodnie. Oczywiście, taki jest ich charakter. Ale nie w stosunku do Sahadźa Jogi. Inne rzeczy możecie traktować lekko Jeśli ktoś na was krzyczy, ktoś się na was złości, ktoś nawet was uderzy, potraktujcie to lekko. To nie ma znaczenia, nie robi to dla was różnicy, bo wy jesteście duchem.

Nic nie może zniszczyć ducha. Nainam Chidanti Shastrani. (Duszy nie mogą przeciąć żadne bronie - Bhagavad Gita: 2.23) Ale jeśli chodzi o Sahadźa Jogę, wasze nastawienie powinno być inne. Jeśli z jednej strony odpoczywacie, z drugiej strony musicie być dynamiczni i to właśnie na tej stronie musicie zaprezentować teorie Sahadźa Jogi, musicie rozmawiać z ludźmi, musicie zorganizować konferencję prasową lub cokolwiek innego, co chcecie zrobić. Na jakimkolwiek poziomie chcecie to realizować, proszę, sporządźcie do tego odpowiedni plan i po prostu to zróbcie. Wszystko się ułoży. Jestem pewna, że się ułoży. Ze wszystkimi tymi pomysłami, które mam, wy macie o wiele więcej i mam nadzieję, że do następnego roku, zobaczymy ich manifestację. Mam nadzieję, że wiele osób napisze książki tak jak napisał U.C. Rai.

Jestem pewna, że książki mogą być napisane przez każdego lekarza. Lekarz U.C. Rai pracował samodzielnie. Wszystko zrobił samodzielnie. Tak pięknie to opracował. Zatem każdy z was może opublikować książkę ze swoimi doświadczeniami, ze swoim zrozumieniem Sahadźa Jogi, co również pomoże Sahadźa joginom. Ale to powinna być uczciwa, bardzo uczciwa książka. Jestem pewna, że taka książka będzie bardzo doceniona w Sahadźa Jodze i chcielibyśmy również opublikować takie książki. Wszyscy, którzy mają takie pomysły powinni podjąć wysiłek, aby stworzyć nowe książki, nowe idee, nowe projekty. To jest bardzo ważne ponieważ w obecnych czasach ludzie chcą robić coś nowego, coś nowatorskiego.

W tych okolicznościach, jestem pewna, że wszyscy sobie poradzicie. Zatem cały czas musicie myśleć o Sahadźa Jodze i zapisywać wszelkie pomysły, które przychodzą wam do głowy a potem można je odpowiednio zestawić, tworząc piękną książkę o Sahadźa Jodze. Panie również mają wiele szans na robienie tak wielu rzeczy dla Sahadźa Jogi. To jest bardzo korzystny czas. Myślę, że Satja Juga zaczyna się od jutra. Bez wątpienia. A jaki będzie objaw że teraz satya zwycięży, vijaya. Cokolwiek ludzie próbują, ostatecznie satya będzie vijaya. Satyame vijayate. To się stanie, a wy jesteście za to odpowiedzialni.

Za to gratuluję wam raz po raz. I mam nadzieję, że będziecie mieli zaangażowanie, aby to zrobić. Niech Bóg was wszystkich błogosławi.