Shri Kundalini Puja. Cabella Ligure, Italia. 21 de junio de 1992.

Hoy nos hemos reunido aquí para adorar a la Adi Kundalini y a vuestra propia Kundalini, porque vuestra Kundalini es el reflejo de la Adi Kundalini. Sabemos mucho sobre la Kundalini, como al despertarse y ascender nos ha llevado al más alto estado de consciencia. No solo nos ha elevado en consciencia sino que además nos ha dado muchos poderes, y también nos ha permitido algo que nunca antes había acontecido en la historia de la espiritualidad: el poder despertar la Kundalini.

Antes, cuando conseguían la Realización se iban al lado derecho o al izquierdo, intentando conseguir más poderes, que nunca usaban para el beneficio de los demás. Buda escribió que cuando viniera la futura encarnación de Buda que es Matreya, las tres Madres juntas, este poder se usaría para el bien de la humanidad. De todo el mundo, no solo de los sahaja yoguis. Pero esto no puede ser posible hasta que aquellos que son Budas, que significa almas realizadas, conozcan la ciencia de la Kundalini.

Aquellas personas que tenían un pequeño conocimiento de la Kundalini, porque lo habían leído en las escrituras o en algún sitio, empezaron a darle mal uso, convirtiéndose en "tantrikas". Sin embargo, como muy bien sabéis, "Tantra" es el mecanismo de la Kundalini y "Yantra" es la misma Kundalini, es decir, la máquina.

Creo que ahora que ya sabemos mucho de la Kundalini, cómo pasa a través de los diversos chakras, cómo se eleva, etc. deberíamos averiguar cómo nutrirla y alimentarla.

En primer lugar hay una gran diferencia entre vosotros y aquellos que obtuvieron su Realización. La primera es que vosotros conseguisteis este poder de forma sahaja, espontanea, y fácilmente, mientras que ellos tuvieron que ir a los Himalayas, dormir a la intemperie, con tanto frío muchos murieron; otros vivían en cuevas, comían frutas, a veces nada. Incluso en la época de Buda, tenían solo una prenda para cubrir su cuerpo, pedían comida en los pueblos, cocinaban lo que podían y se lo comían frío o caliente, de cualquier manera. Buda les enseñó a renunciar a las comodidades pero aun así ninguno de ellos obtuvo la Realización, ni pudo hacer el trabajo de despertar la Kundalini.

Hay una gran diferencia en la forma en que vosotros obtuvisteis la Realización: vuestra Kundalini se ha despertado de una manera sahaja, del mismo modo manifestáis sus poderes. Por ejemplo, podéis dar la Realización, curar, sentir las vibraciones de otros; hay sahaja yoguis que pueden controlar la lluvia, el Sol, la Luna, todo.

Algunos tienen el gran poder de la oración. Rezando han salvado la vida de mucha gente. Estos poderes eran accesibles para alguno de ellos, incluso Rishis y grandes Munis de aquellos tiempos. Pero sus poderes no se basaban en el amor y la compasión. Su función era la de protegerse a sí mismos o destruir; desarrollaron poderes para maldecir a la gente. Mientras que vosotros tenéis que trabajar para el beneficio de los demás. No podéis maldecir a nadie (no tenéis ese poder), porque yo he anulado ese poder. Tampoco yo maldigo a nadie, aunque puedo; no obstante nunca maldigo porque nuestros cimientos son el amor, la compasión y la ternura.

La mayoría eran gentes con muy mal genio, extremadamente agresivas, hablaban de una manera muy dura sobre los que no eran almas realizadas, los que les molestaban, estaban enfadados con la sociedad. Otros vivían de espaldas a la sociedad, no la denunciaban ni la insultaban, solo estaban satisfechos de sí mismos, vivían escribiendo las bendiciones que tenían. Pero vosotros estáis en una nueva dimensión, y debéis usar vuestros poderes para el bien de todos. Vuestra Kundalini fue despertada de forma sahaja gracias al Amor y a la Compasión de vuestra Madre, por eso ahora, vuestra Kundalini solo puede nutrirse si desarrolláis en vuestro interior el sentido de Amor puro y la Compasión pura.

He usado la palabra pura que es también mi nombre; significa que, para empezar, tenéis que ser inocentes. Si no sois inocentes entonces tendréis ciertos problemas, quizá con la lujuria o quizá vuestro amor se dirija solo a ciertas personas. La Kundalini no es así, Ella asciende, va a todos lo chakras sin implicarse con ninguno, trata de curar cada chakra, de alimentar cada chakra, y su única preocupación es su ascenso.

De la misma manera un sahaja yogui no debe involucrarse en ninguna relación como tal; esto es posible, no tenéis que ser como los discípulos de Buda. El ejemplo que siempre pongo es el de la savia del árbol que va a todas las diversas partes, donde se evapora o regresa. Al igual, este canal, debe estar abierto en nosotros para que la Kundalini pueda subir fácilmente, sin ningún obstáculo.

Pero este canal puede cerrarse si os involucráis demasiado con algo. Hay quien está muy involucrado con los padres; al principio es normal, vienen a mí para que cure a su padre, su hermana, su marido, sus cosas, me escriben largas cartas para hablarme de sus relaciones. Yo pierdo el hilo. ¿Y este quién es? Sin escribir siquiera sus nombres, me mencionan todos sus parientes o relaciones. Estas son conexiones artificiales. Mañana os ocurrirá alguna calamidad y estas relaciones no os servirán de nada, por el contrario descubriréis que intentarán aprovecharse. Así que, no podéis depender de vuestras relaciones, no importa en que familia, país o religión habéis nacido, porque ahora sois Seres Universales.

Por lo tanto, ya no más vínculos con estas relaciones artificiales, vuestro vínculo está basado en otras relaciones espirituales. Esto no significa que tengáis que abandonar a vuestro esposo o esposa, a vuestros niños; nada de eso, sino que tenéis que desprenderos de todos los condicionamientos.

Tenemos diferentes tipos de condicionamientos, los hay buenos, aunque también debemos dejarlos en el sentido de que seremos maestros de ellos.

Por ejemplo, los indios tiene el buen condicionamiento de bañarse muy temprano por la mañana. Yo también lo solía hacer. Entonces fui a Inglaterra; es horrible para eso, Inglaterra es como un país maldito, simplemente no puedes bañarte temprano; o te bañas por la noche o no te bañas. Si tenéis este condicionamiento os sentiréis tristes. ¡Oh!, he perdido mi baño, no puedo dormir, no me siento bien, no estoy normal. Es un buen condicionamiento, sin embargo os convertís en esclavos.

Entonces, tanto si es bueno o malo, si es un condicionamiento, debéis intentar verlo claramente. Lo que no quiere decir que tengáis que hacer lo contrario: ¡Está bien nunca me bañaré!, esta no es la solución. La solución está en pensar: ...bien, si no puedo bañarme por la mañana lo haré por la noche, no importa si por una vez lo pierdo... El baño no me controlará, sino que yo controlaré el baño. Nada debería controlaros; entonces la Kundalini avanzará. Debéis ser completamente libres, puesto que si no tenéis completa libertad la Kundalini no se moverá.

Tenéis condicionamientos heredados de vuestra familia, de vuestra religión, de vuestro país. Debéis ver los que os vienen a través de vuestra familia en la mayor medida que os sea posible. Si habéis nacido en una familia cristiana estaréis apegados a Cristo, aunque no sepáis si Cristo existió o no, o si la Biblia es verdad o mentira; sin embargo, estaréis más apegados a la Biblia. Si sois hindú estaréis apegados al Gita y a los Devas. Esto crea desequilibrio porque debemos tener la misma actitud con todas las religiones, con todas las escrituras; esta es la señal de un Santo. Así que, los condicionamientos tienen que desaparecer.

Otro condicionamiento que hay que desechar es el del país donde nacisteis. Esto es muy importante. No hablaré de cuales son los diferentes condicionamientos de cada país, vosotros los conocéis bien. Después de vuestra Realización, cuando ascendéis más alto que la sociedad que os rodea, comprendéis los condicionamientos y los podéis describir. He llegado a conocer la estupidez de un país por la gente que pertenece a él.

Por ejemplo, un francés dirá: "Madre esta es la mentalidad francesa", o un hindú dirá que tal persona representa al típico hindú. Pero vosotros debéis comprender que no representáis a un país, sino que sois Seres Universales y que vivís como tales. Cuando os convertís en universales notáis que el color de la piel no marca diferencias en el mundo.

Y no odiáis a nadie porque sea negro o blanco. Los blancos y los negros se odian por igual, es mutuo, ambos piensan que los otros están equivocados.

Si pedís a un fanático su opinión sobre otra religión, os dirá que es mala, que la mejor es la suya. Y si preguntáis a otro fanático de otra religión os dirá que es mala, que la mejor es la suya. Y si preguntáis a otro fanático de otra religión os dirá que la suya es la mejor, y que las demás son peores. Lo que en opinión general significa que todas son las peores, hay un consenso en pensar que todas las religiones fanáticas son las peores, ninguno dirá que su religión está bien y alguna otra también.

Si preguntáis a un inglés él dirá: "Madre, este es un típico inglés, no puedes evitarlo". Se enfadan tanto. Yo he visto cómo un inglés se irritaba con otro que se comportaba mezquinamente conmigo; pero yo no, porque yo sé que está ciego. La compasión debe estar dentro de vosotros como Seres Universales a los que Dios les ha concedido la gracia de ascender a un estado más alto. No es necesario certificar que sois almas realizadas. ¡Vosotros sois almas realizadas!, sin duda, sois almas realizadas.

Soy Sakshat, así que, ahora tenéis el certificado absoluto de Dios de que sois almas realizadas. Naturalmente tenéis que cambiar todo. No sirve con identificaros o tipificaros con lo que sois. Ahora sois como el huevo que se ha transformado en pájaro. Los pájaros no se identifican con el huevo ni se quedan en un sitio, sino que vuelan. Ya no sois más el huevo, ahora sois el pájaro. De la misma manera, tenéis que aceptar vuestra posición como almas realizadas, con dignidad, comprendiendo cuál es el propósito de vuestra vida; ahora, todo ha cambiado completamente.

Una vez que en vuestro interior, y no en el exterior que es solo un proceso mental, entendéis cuál es la finalidad de vuestra vida, inmediatamente os volvéis responsables; porque sabéis que habéis recibido la Realización para extenderla por todo el mundo y emancipar al mundo entero. Cuando aceptáis esto automáticamente tomáis responsabilidades y la Kundalini asciende.

Sé de mucha gente que decía: "Madre, yo no puedo hablar en público, me asusta". Solo ponte de pie y ya está, empieza a dar conferencias. Ahora tengo que pararles (risas).

Hay otros que decían que no podían escribir poemas o cantar. Se de una chica que cantaba tan mal que la gente le tuvo que pedir que se callara porque siempre desentonaba. Ahora es ella una de las que dirigen el grupo.

De esta manera, todas las cosas maravillosas empiezan a manifestarse, debéis aceptarlo y abandonar lo que llamáis "miedos".

Tenéis todo tipo de miedos que provienen del lado izquierdo. Las personas que son del lado izquierdo tienen que saber que ahora son almas iluminadas y nadie puede tocarles y mucho menos destruirles. Aquel que intente destruiros será eliminado de una manera muy interesante, muy bromista. Os reiréis y gozaréis al ver cómo funcionan las cosas. Como se dice en sánscrito "(?)". La destrucción vendrá de su propia estupidez.

Poco a poco veréis cómo se transforma en estúpido y desde su estupidez se autodestruirá, no tenéis que preocuparos de esto, por eso vosotros no tenéis necesidad de ningún poder destructivo. Eso será hecho por el Poder divino Omnipresente.

Dejad ese trabajo al Divino, vosotros simplemente tenéis que perdonar a esa persona; tan pronto como perdonáis, la responsabilidad deja de ser vuestra y la Kundalini asciende.

No tenéis que guardarle rencor ni ir contra él, solo reíros porque están ciegos, porque son estúpidos, porque son tontos.

¿Qué hacemos cuando vemos a un idiota?, no podemos reírnos en su presencia, pero nos reímos a sus espaldas. Ellos se convierten en idiotas y nosotros vemos como lo hacen. Este es el humor de Sahaja Yoga, también tenéis que tener algo de humor, ¿no? Contemplamos a estos payasos comportándose cómo en un circo.

Por lo tanto, no tenemos que tener miedo de ningún ser humano u organización. Por supuesto, tenéis que saber que como almas realizadas habéis visto la Verdad, estáis en la Luz, y ellos se van a oponer, van a ir contra vosotros. Anteriormente lo hicieron con otros, y todos sufrieron mucho, pero ahora ya no hay más sufrimientos, sencillamente gozad del humor.

Comprended esto, que nada os destruirá, que nadie os dañará, ellos están aquí para proporcionarnos humor. Si adoptáis esta ligera actitud hacia ellos, todo el miedo y el lado izquierdo se desvanecerá. Los badhas, los bhuts, los tantrikas no os harán nada ya que sois tan poderosos, que solo con una mirada vuestra empezarán a bailar sobre sus cabezas.

Mientras sigáis teniendo miedo, la Kundalini no ascenderá. Porque Ella no se eleva para la gente que es cobarde. No apoya la cobardía. Si sois un cobarde, Ella permanece en su sitio sin manifestarse. Normalmente, la gente, cuando pasea por la calle tiene miedo de la oscuridad, de que alguien les pueda atacar, pero un sahaja yogui no, si es un verdadero sahaja yogui, porque él sabe que hay muchos ganas y ángeles a su alrededor.

Nadie puede dañaros, pero si alguien lo intentara, los ganas le dejarían en ridículo dándoos la oportunidad de reíros de él; observad y veréis.

Así que, este lado izquierdo o miedo debe dejarse de lado; y entonces toda vuestra astucia, vuestras complicaciones mentales, vuestros celos, desaparecerán. Así es cómo la Kundalini ascenderá sin problema alguno.

El otro problema para el despertar de la Kundalini es el ego. Es tremendo, debo admitir que es mayor en los seguidores de Cristo y Buda, me sorprenden, porque ellos son anti-Cristo y anti-Buda. Él, que murió en la cruz, dijo: "¡Padre, perdónales porque no saben lo que hacen!" Si vosotros le seguís, ¿cómo podéis tener ego?

El perdón es o debería ser, espontáneo, no debería haber motivo de enfado porque sois muy poderosos. ¿Cómo podría alguien dañaros? Pero si os obstruís el Agnya vosotros mismos, os dañáis, y si otros quieren haceros daño, nadie os puede ayudar.

Esta cólera o enfado que viene del hígado y se establece en el Agnya tiene que ser examinado. En Occidente este es un punto importante donde se detiene la Kundalini, porque su propia cultura ha creado dos problemas. El primero es el instinto de consumo (o adquisición) lo que llamáis avaricia. Cuanto más avaricia, más máquinas y más desarrollo industrial del plástico y esto tendrá una consecuencia contra la ecología. En España he observado que hay muchos coches; debe de haber tres o cuatro fábricas de coches porque en cada coche va una sola persona. Hay tantos que uno no puede ni moverse, incluso para llegar a tiempo al programa tienes que salir dos horas antes, cuando en otras condiciones en quince minutos llegarías.

En Francia igual, concretamente en París, si quieres ir a algún sitio tienes que salir a las cuatro de la madrugada o de lo contrario no llegas. También pasa en Milán y Roma, en Suiza es peor. No sé qué decir de Suiza, solo nombrarla es peligroso (se ríe) por todo ese dinero negro que manejan, han hecho todo tipo de cosas, de pecados, en nombre del consumo. Para ellos nada es pecado, quitan el dinero a unos y se lo quedan, lo extraen de países pobres, se lo quedan, no ven nada malo en ello, son impasibles. Deberíamos ver claramente todo este instinto consumista que tenemos y que hemos avivado, se ha convertido en una especie de cualidad en Occidente. En la antigüedad, en estos mismos países europeos se usaba para crear arte, y apoyar a los artistas.

Incluso en nuestro país, los artistas eran apoyados por los Reyes y el Imperio.

Actualmente no hay ningún gobierno dispuesto a apoyar a los artistas. Como sabéis, Mozart fue llamado por la Reina para que tocara para ella.

Los gobiernos no solo se ocupaban de recaudar los impuestos, también cuidaban de los artistas, músicos, pintores y gente creativa. Como en Francia, su Reina coleccionaba hermosas obras de arte y animaba a los artistas a hacer su trabajo, gastando dinero en esto, y fue asesinada por su gente. Al matarla acabaron con el arte de Francia. Ahora los franceses se han convertido en burgueses, se han transformado en lo mismo que condenaban.

Así que, este instinto consumista debería trasladarse al consumo del arte. Esto no debería ser plástico, de lo contrario mañana podríamos empezar a comprar cosas de plástico como arte. Deberíamos comprar cosas genuinas, hechas a mano. Lo mismo con la música, deberíamos adquirir música profunda, clásica, canciones del Divino y no toda esa música barata que nos vuelve locos o llenos de lujuria y codicia. Así que, este es uno de los problemas de vuestra cultura que os da un cierto tipo de ego. Lo que quiero decir es que esa gente que tiene un Rolls Royce, nadie puede hablar con ellos. Sus cerebros se hinchan en sus cabezas; incluso el conductor del Rolls Royce, no es el propietario, pero como lo conduce va con la cabeza alta; tienen una forma diferente de caminar, de hablar. Así, el instinto consumista, os da mucho ego.

Si vais a la casa de alguien, como a la de esos estúpidos indios que ahora viven en Inglaterra; fui a su casa, eran seguidores de Guru Nanak, donde el beber no está permitido. Pero cuando entras te enseñan el bar de su casa; "¡Dios mío!", dije, y retrocedí unos pasos, entonces dijo: "mira mi pub" y sacó una botella de soda. Cuando dije que nosotros no bebíamos, pensó que por no beber, éramos pecadores de la peor clase.

Así que, este instinto consumista termina siendo algo muy vulgar e inmoral. Su interés por alardear es tan grande, que uno a veces queda estupefacto. La manera en que esta gente trata de presumir, como los americanos...Vino una mujer americana y me preguntó, Sra. Srivastawa, ¿cuántos pubs ha visitado en Londres? "¡Ninguno!", contesté.

"Pero, ¿cómo es posible?, ( se ríe) es un poco inútil; ¿acaso no sabe que los pubs son las mejores casas de cada pueblo y ciudad en Inglaterra ? - dijo con orgullo.

"Las he visto por fuera", dije para complacerla, porque pensé que se refería al arte (arquitectura).

- "No, no mire, los mejores pubs son... y me dio una lista. ¡Imaginaos!

Entonces le pregunté cuál era el mejor. Me dijo que uno llamado "El pub del ermitaño". Yo le pregunté : ¿Y qué tiene de especial? Entonces me explicó que el hombre que vivía en esa casa murió, nadie supo de su muerte y permaneció allí durante meses. Cuando entraron el lugar tenía un horrible hedor y estaba cubierto de telarañas. Sacaron el cuerpo pero el hedor y las telarañas aún siguen allí intactas, tienes que tener cuidado de no romperlas (risas). Y este es el mejor pub por el cuál tienes que pagar mucho. "Yo lo he visto", dijo orgullosa.

Así que, en esto acaba este instinto consumista, en cosas podridas y putrefactas. Desembocan en esto a causa de las reacciones del ego, así disfrutáis de las cosas podridas. Como el queso de Francia. Nunca lo comáis, si no, os arderán los dedos, la garganta y el estómago. Está podrido y cuanto más podrido mejor, más les gusta.

El vino, igual, es el zumo de uva en descomposición; no podéis tomarlo, huele como el corcho podrido. Le pedí a alguien que lo oliera y dijo que olía bien, (risas), entonces le dije que olía como el corcho en descomposición. Me dijo que nunca había olido el corcho.

- "Si alguna vez hubieras olido el corcho podrido nunca en tu vida beberías vino"; todo son cosas podridas.

¿Sabéis cómo se descubrió el queso?, todo empezó porque hubo una gran nevada y la leche se quedó en una cueva. Por la nevada la gente se olvidó de la leche. Luego cuando llegó el verano la leche estaba estropeada, más y más estropeada. Doce años después alguien entró en la cueva y lo vio. "Uff...gracias a Dios, que aún no he comido". Entonces se tomó esa leche y la llamó queso.

En India la palabra "cheese" (queso) se utiliza en el idioma Urdu para denominar algo especial, también en música se usa para referirse a una composición especial cheese. Pero aquí, cheese (queso) significa leche tan estropeada que ni hombre, ni animal deberían comer. Quizá los gusanos lo podrían comer.

En Holanda y Suiza hay un queso con gusanos, os podéis creer que se comen tanto el queso como los gusanos; ¡se comen los gusanos!

Lo que quiero es que veáis a dónde nos lleva todo este instinto consumista. El vino tiene que tener más de cien años para ser el mejor. Comemos tantas cosas putrefactas, y el olor es terrible. Tienen un olor horrible, pero no lo identificáis porque coméis ese queso; incluso si se les lleva a las alcantarillas no olerán nada podrido porque están acostumbrados a este sucio olor. Es la mugre, incluso en el infierno no se sentirían mal porque el olor es el mismo.

Entonces, ¿dónde les ponemos? Son tan inmunes a este olor sucio que es incluso subhumano. Así que, este instinto está en la sociedad de élite. La sociedad francesa en cierta ocasión fue considerada sociedad de élite, la más diplomática en todos los sentidos, pero su comida se hacía con vino, vino por todos sitios, y esta sociedad diplomática marcaba las normas en todas las áreas diplomáticas. Pero no se dieron cuenta de que toda su cultura no era más que comida y bebida, y más adelante, algunos políticos aparecieron. Pero este comer y beber les ha llevado al límite de que ahora nadie les quiere, se les ha echado de la diplomacia, porque nunca piensan de forma correcta. A los diplomáticos franceses no se los quiere en las reuniones -"¿es francés? pues entonces es mejor no avisarle porque si no vendrán con sus extrañas ideas".

Ahora la élite se ha desviado hacia América, y están tomando drogas. La droga es una creación de este instinto consumista. ¿Por qué deberíamos culpar a los colombianos y a nadie más? Evidentemente ellos están obteniendo dinero, pero es América quién se está alimentando. América es hoy el principal foco del instinto consumista. ¿Y qué es lo que consiguen? He observado que esa sociedad solo habla de drogas; y no solo hablan, es como una gran tienda de drogas. Todos saben dónde conseguirla, todos esos embajadores, sus esposas y su gente. Sus esposas visten de la manera más simple, no visten formalmente como esposas de embajadores. No me extrañaría que un día vinieran con vaqueros agujereados.

Como podéis observar este instinto consumista que se encuentra en la alta sociedad les ha llevado finalmente a la droga o a falsos gurus. Aquellos que ya están cansados de esto (consumismo) van a los falsos gurus puesto que no tienen discriminación para saber lo que está bien y lo que está mal.

¿Qué utilidad tiene el mirar a un hombre que no es tu marido? Este consumismo nos ha llevado a una vida muy inmoral, a una sociedad inmoral que ha perdido el sentido de respeto por la edad. Una mujer de noventa años teniendo líos amorosos con su nieto de dieciocho años, pensadlo bien, semejante tontería, semejante cosa absurda.

Esto solo es posible si se tiene un pervertido instinto consumista. Incluso el arte está pervertido, todo está pervertido, porque la maldición de Occidente es que no hay Maryadas. La Kundalini solo asciende en su propia Maryada, Ella hace renacer de nuevo vuestras Maryadas, os mantiene en ellas. Vosotros sois seres humanos, no viváis como animales o incluso peor que animales, no tenéis derecho a hacer eso. Dios no os ha creado para ser subhumanos sino para ser superhumanos. Así es cómo funciona, podéis reflexionar sobre esto, hasta dónde llega este instinto consumista con todo.

La segunda maldición del instinto posesivo de Occidente es que quieren poseer, agredir a las personas. Es la agresión y la agresividad. Creen tener derecho a agredir a otros países; invadieron nuestro país durante trescientos años. ¿Por qué? ¿Por qué esta agresión? No éramos mala gente, fue por el oro, los diamantes, las perlas, porque teníamos muchas cosas; solo se llevaron cosas materiales y nada de espiritualidad.

Así los franceses agredieron, siempre agredieron, los japoneses también los siguieron. Esta agresión lleva a toda la sociedad hacia una fuerza destructiva. Podéis ver todos los días las guerras que están teniendo lugar, este lucha con ese, aquel lucha con el otro, ellos quieren esto, y aquellos quieren lo otro, y la agresión ha penetrado también en los países en desarrollo, también en el tercer mundo. De esta manera la enfermedad continúa, pero la Kundalini mata este afán de posesión; ¿cómo?, dándoos gozo. Vosotros disfrutáis de todo. Si estáis sentados en la selva vosotros gozáis, aquí en una incómoda posición, disfrutáis porque buscáis el confort de vuestro Espíritu; puesto que él os da gozo, por último, este gozo es lo que obtenéis de todas las cosas.

Creéis que el gozo lo obtenéis por la posesión, pero no es así, es a través del despertar de la Kundalini por lo que conseguís el gozo. Y en este gozo no queréis nada, no pedís nada, simplemente gozáis de vosotros mismos, sois propiedad del gozo. En sánscrito se dice "...., "el Espíritu es satisfecho por su propio Espíritu".

Por lo tanto debéis ver el gozo en las cosas pequeñas y debéis contemplar el Universo entero de esta manera. Lo que quiero decir es, por ejemplo, cuando estoy viajando y preguntó: "¿Qué árbol es ese?" -"¡No lo sabemos!" "¿Cómo es posible?, vivís aquí desde hace tanto tiempo y no lo sabéis". - "¡No, Madre, no sabemos nada de árboles!" "Y esas flores, ¿lo sabéis?" ¿Qué hacéis? ¿Qué habéis hecho que no conocéis los árboles del lugar dónde habéis crecido? ¿No los mirabais? Pero si les pregunto dónde obtuvieron el vino, lo sabrán. "Madre este es el sitio donde se producen los mejores vinos", "esta bien, me hago cargo"; y al año siguiente no tuvieron fermentación (risas).

Entonces, este instinto consumista, se convierte en una especie de ventaja política para invadir a otros países, agredir a otra gente y usáis todo tipo de cosas que realmente están matando. Así, toda la actitud de la humanidad está cambiando, se creen grandes señores que pueden odiar y agredir a todos, ser arrogantes y demandar cualquier cosa, quitar la esposa, los hijos de los demás, matar a nuestros niños, y como resultado el amor se ha perdido, no existe compasión y así desarrolláis el afán del "mío, mío": mi hijo, mi país. Como está pasando ahora en Yugoslavia; no se quién le puso el nombre de YUGO; yugo significa yoga, esta es la gente de yoga (yugo-slave) luchando entre ellos. Esto ha venido de la misma raíz, del esto es mío, mi país. ¿Por qué? ¿Cómo que es vuestro país? ¿Acaso podéis crear una sola hoja? Entonces, ¿quién sois? ¿Podéis crear un poco de barro? No, no podéis. ¿Cómo decís, que este es vuestro país? ¿Cómo os atrevéis? Todo pertenece a Dios, Él lo ha creado o podéis decir que la Adi Shakti lo ha creado. Vosotros no habéis creado nada, ¿cómo podéis decir que esto es mío?, ¿que yo lo debería tener? Así que, este "mío, mío" es muy común. Lo mismo ocurre a veces con los sahaja yoguis, muchas veces, dicen "mi hijo", esta es la primera maldición; mi esposa, mi familia, así empieza todo, el corazón se encoge. Para un hombre de gran corazón el mundo entero es el Universo, todo está en el interior, todo es suyo.

Cuando experimentáis en vuestro interior un corazón así, entonces la Kundalini asciende de repente porque, como sabéis, el Sahastrara es el chakra de Corazón. No hay posibilidad de obstrucción en el Sahastrara si tenéis un gran corazón, y para mantener el Sahastrara abierto solamente tenéis este sentimiento, esta sabiduría de que nadie es mío, todo el mundo pertenece a Dios. Así que, abandonad estos sentimientos, los sahajas yoguis los tienen, tengo que decirlo, lo he visto en ellos, se encierran en sus familias, "mi hijo no tiene la Realización ni mi hermano, etc."

Este "mí" tiene que abandonarse, es algo muy sutil que os obstruye el Sahastrara. Todo el mundo es vuestro. Porque la Kundalini de los sahaja yoguis esta hecha de amor, de puro amor. El amor puro solo tiene puro deseo dirigido hacia el amor. Amor a todo el mundo por igual. Cuando decís que es difícil, es que no estáis practicando Sahaja Yoga. Engrandeced vuestro corazón y nunca os sentiréis perdidos. Cuando estaba viviendo en Inglaterra, me ocurrió algo parecido a como cuando la Luna atrae al mar; y sentí como si alguien sujetase mi corazón; pero cuando llegué aquí, y vi de nuevo a mis niños esperándome, se fue, se acabó y me sentí, como ahora me siento, con el fondo de mi Corazón lleno de Amor.

Vosotros sois mis hijos y ellos también. Para una madre así, ¿cómo puedo decir "es mío?" De esta forma, tratad de romper ese condicionamiento. En un principio la gente de Occidente no quería a su familia, se divorciaban constantemente; se publicaban casos de mujeres que se habían divorciado diez veces. Ahora no se divorcian pero se apegan a sus familias, a sus maridos como con pegamento. A veces me pregunto qué he hecho para hacerles así.

Así que, es importante saber que el corazón es el Sahastrara o el Brahmarandhra, y que tenemos que llegar al corazón. No razonéis mentalmente, no discutáis sobre ello, no lo enfoquéis mentalmente desde los libros y otra cosa sino desde el corazón. Si funcionáis así comprenderéis que no hay nada más importante que amar a alguien y lo más elevado es amar a todo el mundo por igual. Naturalmente que con amor podéis decir las cosas a una persona. El otro día tuve que decir algo a un sahaja yogui, entonces mi marido me dijo que no le dijera eso o ella se convertiría en mi enemiga. Le dije, deja que se convierta en mi enemiga, no importa, es mi deber decirle lo que está mal, de lo contrario sería su enemiga por no decirle la verdad y dejarla sufrir.

Por eso se os ha dado discriminación. El amor es la verdad. La Kundalini es el río que describí ayer, Nirvaj, que no espera nada a cambio. Es el río del puro amor que ha despertado en vosotros, lleno de amor, amabilidad y ternura. Deberíais usar este poder dentro de vosotros para llegar a ser así, porque es vuestro trabajo. Ella os ha dado la Realización para la emancipación del mundo entero, no solo para vosotros.

Todo el mundo tiene que dar la Realización o de lo contrario su Kundalini bajará, retrocederá de nuevo. Hablad de Sahaja Yoga. Sahaja Yoga no es de media jornada, ni vuestra actividad complementaria, debería estar siempre con vosotros. Allí donde tengáis una oportunidad, hablad de Sahaja Yoga, tenéis que trabajar con éxito y dar la Realización o de lo contrario todo esto no sirve para nada.

Que Dios os bendiga.