26 sierpnia 1990
Ganeśa Pudźa
Lanersbach (Austria)

Dziś obchodzimy urodziny Shri Ganeshy.

Wszyscy znacie historię Jego narodzin i nie muszę jej powtarzać. Ale ponieważ został stworzony wyłącznie przez Matkę, przez Adi Shakti, w ten sam sposób wy wszyscy zostaliście stworzeni na Jego wzór. Więc już jesteście na ścieżce Shri Ganeshy. Wasze oczy błyszczą tak samo, jak błyszczą Jego oczy. Wszyscy macie piękny blask na twarzach, tak jak On. Nie ma znaczenia, czy jesteście mali, duzi czy starzy. Całe piękno dociera do nas przez blask Shri Ganeshy. Jeśli On jest zadowolony, to nie musimy się martwić o jakiekolwiek inne bóstwa, ponieważ moc wszystkich bóstw to Shri Ganesh. On jest jak wicekanclerz zasiadający na każdej czakrze. Dopóki nie podpisał, Kundalini nie może przejść dalej, ponieważ Kundalini to Gauri i jest dziewiczą Matką Shri Ganeshy.

Teraz musimy zrozumieć, że jesteśmy tutaj w społeczeństwie zachodnim, gdzie tak wiele poszło nie tak, ponieważ nigdy nie dbamy o Shri Ganeshę. Przyszedł Chrystus, a Jego przesłanie rozprzestrzeniło się po całym świecie. Mówił o rzeczach, które nie są w ogóle praktykowane przez chrześcijan. Ponieważ cokolwiek zaczęli, nie opiera się na prawdzie. Prawdę mówiąc, Shri Ganesha urodził się jako Chrystus. Jeśli to jest prawda, to muszą zrozumieć w świetle Shri Ganeshy tę wielką inkarnację Chrystusa. To znaczy, że powiedział ludziom: „Nie miejcie cudzołożnych oczu”. W rzeczywistości, dla świętego, On nie wie, czym są cudzołożne oczy, ponieważ On po prostu widzi. Po prostu widzi. Jak pięknie powiedział Shri Gyaneshwara, NIRANJANABANI widzieć bez żadnej reakcji, po prostu widzieć.

To jest cecha niewinności, która została ujawniona przez Chrystusa, naszego Pana, ale nie przyswoiliśmy żadnej z tych cech. Przypuśćmy teraz, że dziś oddajecie cześć Shri Ganeshy. Dlaczego więc czcicie Shri Ganeshę? Czcicie, ponieważ wasz Ganesha musi być przebudzony, abyście mieli w sobie cechy Shri Ganeshy, abyście czuli tę niewinność w swoich oczach. W przeciwnym razie jesteście obłudni. Jeśli siedzicie tutaj i czcicie Shri Ganeshę i nie staracie się skierować uwagi na swój wzrost jako Shri Ganesh, to jest bezcelowe. A wtedy On jest wiecznym dzieckiem. Nie ma ego, nie ma żadnych uwarunkowań. Więc jest wiecznym dzieckiem. Musimy stać się wiecznymi dziećmi naszej Matki.

Aby osiągnąć ten stan, musimy zrobić coś prostego, podnieść naszą Kundalini, ustabilizować ją, medytować i skupić naszą uwagę do wewnątrz i nie reagować. Powiedzenie by nie reagować, oznacza po prostu obserwować. A kiedy obserwujecie, nie myśląc o tym, wtedy prawda, która jest naprawdę poezją, ujawnia się. Dlatego poeta widzi znacznie więcej niż zwykły człowiek potrafi zobaczyć. Wewnętrzne piękno zaczyna przenikać do waszego wzroku i zaczynacie je dostrzegać. Więc widzieliście dzieci, niezależnie od ich pochodzenia, z jakiegokolwiek kraju pochodzą, czy to Japonia czy to Anglia, Indie, Australia, skądkolwiek, zobaczcie, dzieci są zazwyczaj bardzo piękne. Byłam kiedyś w Japonii i było tam sanktuarium, które chcieli Mi pokazać, ujrzałam kilka pań schodzących - trzy, cztery panie. To są zachodnie panie. Powiedziały: „Nie idź. Nie idź.

Tam są jakieś dzieci - okropne”. Zapytałam: „Dlaczego?” „Nazwą nas czarownicą, nas wszystkich, „czarownice, czarownice, czarownice”, japońskie dzieci.” Zapytałam: „Skąd to wiecie? Muszą mówić po japońsku”. „Nie, zapytaliśmy o znaczenie, powiedzieli, że to oznacza czarownice. Wyglądamy dla nich jak czarownice, więc lepiej nie iść”. Powiedziałam: „W porządku. Pozwólcie Mi iść”. A kiedy weszłam, wszystkie podbiegły, przytuliły Mnie, całowały, to wszystko. Nie pozwoliły mi iść do sanktuarium, a potem poszły całą drogę do sanktuarium, wróciły. Nie znałam ich języka ani niczego.

Takie słodkie. Całowały moje sari, całowały moją rękę, takie były słodkie. I byłam zaskoczona, jak to możliwe, że nazywają inne panie czarownicami, a dla nas, dla Mnie, a moje córki również były z nami. Moje córki bardzo lubią dzieci. Więc powiedziały: „Widzicie, po co iść do sanktuarium? Będziemy się bawić z dziećmi”. Powiedziałam: „No dobrze, mimo wszystko chodźmy do świątyni”. Więc kiedy poszliśmy na górę, te dzieci również poszły z nami i zeszły na dół. A ich matki były takie zaskoczone, widzicie, mówiły normalnie o wszystkich obcokrajowcach, do wszystkich obcokrajowców mówią „czarownice”, nawet do mężczyzn mówią, że są diabłami. „Nadchodzą diabły”.

Ponieważ Japończycy są niskiego wzrostu, a nasi zachodni ludzie są dość wysocy, i być może to jest powód, cokolwiek to jest - a może coś innego, nie wiem. A one nie chciały nawet z nimi rozmawiać. Wszystkie uciekły, wołając: „Czarownice...”, z okien i z każdego kąta. Wtedy zrozumiałam, że w tych małych, drobnych dzieciach, Ganesha jest przebudzony. Ganesha w każdym jest przebudzony, gdy się rodzicie. Wszystkie zwierzęta mają swego Ganeshę nienaruszonego, szczególnie ptaki. Nigdy nie zastanawiamy się, jak ptaki, przemierzają całą drogę z Syberii do Australii. Z jakiego kierunku przychodzą do nich, skąd? Mają w sobie magnes. To jest Shri Ganesha.

Magnes to Shri Ganesha. Więc ten magnes, który jest w nas, może przyciągać niewinnych ludzi, i odpychać przebiegłych, okropnych, jak nazywają ich czarownicami, diabłami itp. Więc ten magnes ma obie te cechy, że odpycha tych, którzy nie są w porządku a przyciąga tych, którzy są niewinni. I dlatego w Sahadźa Jodze odkrywamy, że nie możemy tolerować pewnych ludzi w taki czy inny sposób, próbujemy, próbujemy... Ale w jakiś sposób to jest trochę trudne. Nie wiedzą, jaki jest powód. Powodem jest Ganesha. Teraz, w społeczeństwie zachodnim, jak wiecie, nie dlatego, że nie zwracają uwagi na swoją jakość Ganeshy, ale zbyt dużo rozmawiali o perwersji Shri Ganeshy. Mówią w telewizji, mówią tutaj, tam, na wszelkie sposoby. Dzieci to widzą i tak wiele małych, malutkich dzieci cierpi z powodu problemu Shri Ganeshy, bardzo małych dzieci. Jak wpadają w te problemy?

Ponieważ atmosfera jest tym przepełniona. Teraz, w Sahadźa Jodze również mamy pewnych ludzi, którzy trwają w hipokryzji i mają problem z Ganeshą. A są tacy, którzy [ich] wspierają. Ten gość może powiedzieć: „Och, byłem takim chorym człowiekiem, nie miałem żony, albo nie zaznałem miłości od moich rodziców“ lub coś w tym rodzaju, a inni zaczynają [go] wspierać. Tego rodzaju współczucie jest bardzo niebezpieczne, jest niezwykle niebezpieczne. Przede wszystkim, to współczucie niszczy tę osobę, która nie potrafi poradzić sobie ze swoimi problemami, i stopniowo wy również przejmujecie te problemy. Zamiast mu pomóc, powinniście medytować o Ganeshy, po prostu siedzieć na Matce Ziemi, mówić „Atharva Sheersha“, używać świecy. Wasz problem zniknie. Zamiast tego, [oni] zaczynają wyrażać współczucie. To nie jest współczucie.

To jest sym-patia. „sym“ oznacza „dzielić się“, „pathy“ oznacza „patos“. Więc sami dzielicie się wszystkimi problemami tej osoby. Dlatego nigdy nie wspierajcie złych spraw. Jeśli naprawdę kochacie tę osobę, troszczycie się o nią, musicie jej powiedzieć: „To jest złe. To jest złe. To jest złe“. Co więcej, w Sahadźa Jodze widziałam ludzi mających siedemdziesiąt lat, którzy również chcą się ożenić. Nie mogę tego zrozumieć. W końcu samotność nie jest możliwa w Sahadźa Jodze, macie tylu Sahadźa jogów.

Gdzie jest samotność? Nigdy nie czuję się samotna. Czasami chciałabym być samotna. Jeśli wy nie jesteście ze Mną, jest za Mną moja rodzina. Nigdy nie jestem sama, i tak naprawdę, gdy jestem sama, nie jestem sama. Najlepiej bawię się, gdy jestem sama, ponieważ mam czas, by zastanowić się, co osiągnęliśmy, jak pięknymi momentami były te chwile spotkań z wami wszystkimi, wszystkie te piękne miejsca, które odwiedziłam z wami, wszystkie te przyjemności. Więc wszyscy tacy ludzie, którzy tłumaczą się ze swoich problemów z Mooladharą, muszą wiedzieć jedno, że to jest pewny dowód dla nich, że pójdą do piekła, absolutnie. Ponieważ z Mooladhary, pojawiają się wszystkie rodzaje chorób, które są nieuleczalne, według lekarza. Powiedzmy, weź stwardnienie rozsiane. Począwszy od stwardnienia rozsianego przez wszystkie niepełnosprawności mięśni, nawet nowotwory mogą być zapoczątkowane przez problem Mooladhary.

Dlaczego w krajach zachodnich jest tak wiele nowotworów, więcej niż w innych krajach? Każdy ma swoje wytłumaczenia. Ktoś powiedział, że nie ma tylu lekarzy od raka, dlatego jest tak dużo nowotworów. Ale to nie tak. Teraz weźmy taką chorobę jak schizofrenia, również może pochodzić z problemu w Mooladharze. Oczywiście, AIDS to nic innego jak problem od Mooladhary. Ale mimo to, jeśli chcecie uczynić z tego męczeństwo, że „jesteśmy żołnierzami AIDS kroczącymi ku swojej śmierci“, to co możecie zrobić z takimi głupimi ludźmi? A głupota również pochodzi z Mooladhary, ponieważ On [Ganesha] obdarza mądrością. Jak zdobyć mądrość? Tylko przez przebudzenie waszego Shri Ganeshy.

On jest dawcą mądrości. Teraz wszyscy ludzie robią głupoty, niewiarygodne – niewiarygodne. Na przykład, niedawno poprosiłam w Indiach o większe bransoletki, ponieważ panie mają tu większe dłonie i odpowiedzieli, że obecnie wszystkie duże bransoletki trafiają do Ameryki. Dlaczego? Ponieważ w Ameryce mężczyźni postanowili nosić bransoletki. A w Indiach, jeśli dasz mężczyźnie jedną bransoletkę, oznacza to dla niego obelgę, że „nie jesteś mężczyzną”. Wszystkie takie głupoty, sto i jedna, widzimy teraz na całym świecie, ponieważ wyszliśmy z tego. Wszystkie rodzaje rzeczy pojawiają się, ponieważ ich Mooladhara nie jest w porządku. Na przykład w Indiach, wszyscy nosimy sari. Nikt nie wie.

To znaczy, logicznie również powinniśmy nosić sari, ponieważ sari są robione przez wieśniaków, a oni na tym zarabiają, i w ten sposób to wspieramy. Kulturowo, podoba nam się to również dlatego, bo sugeruje, że jesteśmy nieśmiałymi kobietami, nie chcemy zbytnio eksponować naszych ciał, i po trzecie, to jest bardzo dobre dla matek, aby matki mogły karmić dzieci i o nie dbać. Ma więc różne aspekty, ale nikt nie myśli o logice. Uważają, że jest to bardzo praktyczne i ma swoje tradycje. Teraz, przypuśćmy, że mówicie: „Dobrze, chodźcie, porzućcie swoje sari i noście coś innego“. Odpowiedzą: „Teraz powiedzcie nam coś innego. Nie, nie. Nic z tego“. Nikt by tego nie zaakceptował. Nikt by tego nie zaakceptował, ponieważ uważają, że sari są elegantsze, sprawiają, że wyglądacie kobieco.

Jest tyle pięknych ubrań, i daje to szansę artyście na wyrażenie siebie. Ale tak tylko niektórzy intelektualiści mogą myśleć, Bo zwykle na wsiach, jeśli powiecie im, że się zmieniacie, odpowiedzą: „Nie”. Więc nic w rodzaju mody nie może się udać. Nic w rodzaju mody nie może się udać ponieważ tradycyjnie osiągnęli teraz pewien etap mądrości: „Teraz, to jest dla nas najlepsza opcja”. Więc nie zaakceptują żadnych głupot. Gdyby to było coś sensownego, co nigdy takie nie jest, powiedziałabym, że z Zachodu mogliby [to zaakceptować]. Ale ponieważ zachodni ludzie stracili swoją mądrość, nie ma nic, co byłoby sensowne dla Indii, nic. A cokolwiek mają sensownego, to też zanika. Wczoraj słyszeliście takiego pięknego walca. Mam na myśli, że kto dziś gra walce?

Tysiące zgromadzą się przy jakiejś hałaśliwej muzyce pop, ciężkiej muzyce, która może przeniknąć wasze uszy i sprawić, że staniecie się głusi. W tym wszystkim nie ma mądrości. Cały czas chcą jakiejś sensacji. Powiedziano Mi, że ludzie przyjeżdżają tu na narty. Teraz widziałam niektórych ludzi skaczących ze spadochronem. Zapytajcie Hindusa. Powie: „Lepiej to zrób. Nie jestem tu, by złamać nogi”. On rozumie mądrość, że „moje ciało jest ważniejsze niż cokolwiek innego. Po co te [mocne] wrażenia?” Narciarstwo, tak wiele osób widziało, że stracili nerki.

Stracili nogi. Będą mieli sztuczne nogi do jazdy na nartach. Te wrażenia stanowią wielką atrakcję dla ludzi, którzy nie mają mądrości. To nie przemawia do rozsądku. Zatem ludzie mądrzy nie poddają się głupotom. Chociaż Shri Ganesha jest dzieckiem, to On obdarza mądrością. Więc możemy powiedzieć, że nasze dzieci są dawcami mądrości, jeśli utrzymamy je na ścieżce mądrości. Słuchacie ich, jak mówią, jak mądrze mówią. Czasami mają konferencję ze Mną i opowiadają Mi wszystko o was, co robicie, i całkowicie Mi ufają, mówiąc: „Nie mów wujkowi ani cioci, ale my Ci to powiemy”. I mówią o drobnych, drobnych sprawach, że „ciocia miała na sobie sari, które Ty jej dałaś, a potem, położyła je na ziemi”.

Wszystkie drobne, drobne rzeczy, o których wiedzą, one są takie słodkie. Zobaczcie, wczoraj jak przybiegły i całowały Mnie tak słodko, bez nich świat byłby jak pustynia bez żadnych kwiatów. Więc Shri Ganesha stworzył was. Dzięki Niemu się urodziliście. To On troszczył się o was, gdy byliście w łonie matki. To On zadbał o to, abyście urodzili się we właściwym czasie. To On dbał o wasze odżywianie, o wszystko. To On dbał o rozwój płodu, o mózg i o wszystko. Wszystko to zostało dokonane przez tę wspaniałą osobowość, Shri Ganeshę. Tak wiele Mu zawdzięczamy.

Poza tym, On daje nam podstawową mądrość. To znaczy, wieśniak, przypuśćmy, że rozmawiacie z wieśniakiem, który nie jest narażony na te wszystkie bezsensowne doznania, stwierdzicie, że jest nadzwyczaj praktyczny i mądry. Jest historia, że pewien wieśniak podróżował pociągiem z innymi chłopcami, którzy byli bardzo ekstrawaganccy i myśleli, że są bardzo mądrzy. Więc próbowali drażnić mężczyznę. Tak więc chłopiec zadał mu pytanie. „Jeśli masło sprzedaje się za jednego funta, za jedną czwartą funta, jaka będzie cena jajka na następnej stacji?“ Spojrzał na niego. Powiedział: „Dobrze, powiedz mi coś. Jeśli nie możesz podać ceny jajka, to czy możesz mi powiedzieć mój wiek?“ Spojrzał na niego. Powiedział: „Musisz mieć dwadzieścia dwa lata”. Zapytał: „Skąd wiesz?” Odrzekł: „Mam brata, który ma jedenaście lat i jest w połowie szalony, ale ty jesteś całkowicie szalony”.

Więc zwykły wieśniak odpowiedział temu sprytnemu facetowi, a sprytny facet nie wiedział, gdzie się podziać. Tak więc cała ta bystrość i spryt kończą się w konfrontacji z niewinnością. Teraz wiele osób czuje, że „straciliśmy naszą niewinność”. To jest wieczna cecha, którą posiadacie. Nigdy nie tracicie swojej niewinności. Tak jak chmury mogą zakryć całe niebo, wasze ego, uwarunkowania i wasze błędy mogły ją przykryć, ale ona zawsze tam jest, zawsze tam jest. Jedyne, co musicie zrobić, to szanować ją, zachowywać się w sposób, który szanuje waszą niewinność. Nigdy nie wstydźcie się swojej niewinności. Sama wasza niewinność jest mocą i wasza niewinność na pewno da wam tę mądrość, dzięki której możecie bez żadnych trudności rozwiązać wszystkie problemy. Ale jeśli spojrzycie głębiej, kim jest Shri Ganesha, On jest dzieckiem Adi Shakti.

Ona stworzyła Go z Omkary. Teraz, Omkara to Logos, jak to nazywacie, to pierwszy dźwięk, kiedy Sadashiva i Adi Shakti się rozdzielili, dla stworzenia. Ten dźwięk jest używany jako Omkara, czyli wibracje, które mają w sobie światło. Mają wszystkie moce sprawcze wszystkich elementów, tylko po prawej stronie. Potem lewa strona, ma moc waszych emocji. W centrum ma moc waszego wznoszenia się. Mamy więc bardzo potężne bóstwo, które jest figlarne. Dzieci rzadko są okrutne. On nie jest okrutny, ale jeśli coś zostanie zrobione przeciwko Matce, wtedy wpada w szał. Następnie karze i w ten sposób boska sprawiedliwość jest wymierzana ludziom.

Tak więc, jeśli poddamy się Shri Ganeshy, On nas chroni, daje nam mądrość, daje właściwe zrozumienie protokołu Matki. Nie zna żadnego innego bóstwa oprócz swojej Matki. Nie przejmuje się żadnym innym bóstwem oprócz swojej Matki, i wie, że Ona jest najpotężniejszym bóstwem. I to jest Jego mądrość, którą trzeba przyswoić. Kiedy się modlicie, musicie spróbować to przyswoić. Wielu ludzi na Zachodzie nadal pragnie naśladować innych, wracają do błędnych idei, które naprawdę oddzieliły ich od Prawdy. Dzięki Bogu wszyscy wyszliście z tego, a kiedy widzicie piekło, w które wpadło społeczeństwo zachodnie, próbujecie zrozumieć i cieszyć się, że jesteście w zupełnie innym stanie. Ale nadal, wśród was będą tacy, którzy będą się wahać. Spróbujcie ich wyciągnąć, a nie w to wrzucać i iść również z nimi. Jeśli im współczujecie, pójdziecie razem z nimi na dno.

Spróbujcie ich wyciągnąć i powiedzcie im, że „musicie z tego wyjść“. Może to być dla nich trochę bolesne, nieważne, ale zostaną ocaleni. Więc jesteście tutaj jako zbawiciele i macie moc Shri Ganeshy, którą trzeba wykorzystać. Tak więc dzisiejsza Puja ma być celebrowana ze specjalną modlitwą w waszym sercu: „Shri Ganesho, prosimy, okaż nam łaskę, miłosierdzie i przebaczenie, abyś objawił się wewnątrz nas. Niech wszystkie te obłudne rzeczy, wszystkie te uwarunkowania i wszystkie te niewłaściwe pomysły, które mamy oraz całe złe życie, które wiedliśmy, rozpłyną się w powietrzu, i niech piękny blask księżyca twoich kojących cech niewinności objawi się poprzez nas”. Pozwólmy, aby te cechy się objawiły. O to właśnie należy prosić. Dzisiaj jest wspaniały dzień. Bardzo się cieszę, że jesteśmy w Austrii, którą nazywam krajem boskiej broni. To cudowny kraj, jak wam wcześniej mówiłam, nie ma tutaj fundamentalizmu.

To bardzo zaskakujące, ale odkryłam, że w Austrii byli ludzie z całego świata, i zawierali tu małżeństwa, to mały kraj, więc wszyscy trzymali się razem. To bardzo miłe miejsce, szczególnie to miejsce, w którym jesteśmy. Słyszałam, że nazywa się świętą ziemią Tyrolu. Widzieliśmy też mnóstwo łaski spływającej przed naszymi oczami. Wszyscy mogli ją zobaczyć, tę spływającą łaskę. Nie padał deszcz, ale można było zobaczyć tę łaskę. Co więcej, wczoraj wieśniacy zauważyli, że ta rzeka wzbiera. Cały lodowiec topnieje, a ta rzeka wzbiera, ale nie przelewała się. Trzymała się swoich maryad. Są dość zaskoczeni, jak do tego doszło, że trzymała się swoich maryad.

To jedno, a drugim jest to, że mówili, iż nigdy nie słyszeli tak wspaniałego, absolutnie wulkanicznego dźwięku, ryczenia chmur, nigdy wcześniej nie słyszeli takich dźwięków, i było naprawdę niezwykłe, że padało tak intensywnie, wszystko się wydarzyło, a my jesteśmy w porządku. Jedynie na centralnej ścieżce Sushumna została oczyszczona. Może dlatego, że musiałam przez to przejść, więc ta część się oczyściła. Ogólnie rzecz biorąc, wszystkie nasze programy poszły bardzo dobrze, i wszyscy cieszyliśmy się wczorajszym programem wieczornym, muzyk również stracił poczucie czasu, grał sam przez cztery godziny. Myślałam, że zagra tylko jedną ragę. Kontynuował i chciał grać dalej, ale potem, dzięki Bogu, pomyślał chyba o pujy i przestał. Więc spróbujmy być niewinni wewnątrz siebie. Bądźcie dumni, że jesteście niewinni. Nie musimy być mądrymi ludźmi. Mądrość to wasze nastawienie psychiczne, a niewinność to wasza wrodzona cecha, która jest połączona z tą Wszechobecną Mocą.

Więc niech Bóg błogosławi was wszystkich! Przynajmniej podczas pujy nie powinno być żadnych ruchów na zewnątrz lub w pobliżu. Jeśli dzieci siedzą, to dobrze, w przeciwnym razie możecie wyjść. Ale nie powinniście przeszkadzać innym, ponieważ ich uwaga skierowana jest na was. Więc wszyscy, którzy wykonują jakiekolwiek ruchy, wszyscy powinniście przyjść i usiąść ze swoimi dziećmi. Dlaczego dzieci nie mogą usiąść? Usiądą, weźcie je do środka. Lub jeśli nie siedzą, idźcie za zasłonę, ponieważ się niepokoją, widzicie, wciąż są tam Sahadźa jogini, którzy bardzo łatwo się niepokoją przy najmniejszym ruchu tu i tam. Więc pierwszą rzeczą jest otworzenie swojego serca na Shri Ganeshę. Tak jak otwiera się wasze serce, gdy widzicie dziecko.

W ten sam sposób, proszę, otwórzcie wasze serca. Dobrze. Ach, widzicie, jedną rzeczą jest to, że ma w ręku trzcinę, a jeśli pamiętacie, Chrystus użył trzciny, by uderzyć wszystkich ludzi, którzy sprzedawali towary w pobliżu świątyni. Mógł użyć jakiejkolwiek innej broni, ale użył trzciny.