Puja de Navidad, alcanza el estado de conciencia sin pensamientos 

Ganapatipule, India. 24 de diciembre de 1998

[falta traducir la parte que Shri Mataji habla en Hindi]

Primero hablaré en inglés y luego en hindi.

Hoy, hace mucho tiempo, nació Cristo. Todos conocéis la historia de su nacimiento y todo el sufrimiento que tuvo que soportar. Él es quien nos ha dado el modelo de sahaja yogui porque no vivió para Sí mismo, de ninguna manera, sino que vivió para los demás poniendo en funcionamiento el Agnya chakra. Uno puede ser Divino, uno puede tener muchos poderes, pero este mundo es tan cruel que no entiende de espiritualidad; no entiende la grandeza espiritual.

No solo eso sino que hay muchos factores que atacan la espiritualidad. Siempre lo han hecho. Todos los santos han sufrido mucho, pero considero que quien más sufrió fue Cristo. Como sabéis, vino con todos los Poderes de Shri Ganesha, pues es su reencarnación. Él primero fue la inocencia; Él fue el Niño Eterno. Nunca pudo entender la crueldad ni la hipocresía de este estúpido mundo. De todas maneras, aunque lo hubiese entendido, ¿qué podría haber hecho? Pero con un gran coraje decidió nacer en un país donde la gente no tenía ni la menor idea sobre la espiritualidad.

He leído un libro acerca de Él en el que se afirma que viajó a Kashmir, donde se encontró con uno de mis antepasados, Shalivahana. Resulta muy interesante porque está todo en sánscrito y el autor parece que no sabía sánscrito, pero lo escribió en esa lengua, lo cual no armoniza mucho con la mente occidental. Gracias a Dios el autor no sabía sánscrito, de lo contrario hubiera sido muy peligroso.

Está escrito que le preguntó a Cristo: ¿Por qué has venido a India? Y Él respondió: Este es mi país, por eso he venido aquí, donde las personas respetan la espiritualidad. Pero yo he vivido entre gente que no entiende de espiritualidad en absoluto. Su conversación con Él fue muy interesante. Shalivahana le dijo: Con mayor razón deberías volver a tu país y enseñarles nirmala tatwam, es decir, el principio de la purificación. Así lo hizo y, después de tres años y medio, lo crucificaron.

Personalmente creo que la mayor diferencia entre la ejecución en Occidente y la de la India es que, en Occidente, matar es una gran profesión. Matan gente con el mínimo pretexto. Todos los santos fueron asesinados o considerados locos. Esa es la mejor manera de evitar la espiritualidad.

En la India, cuando un santo dice alguna cosa nadie le contradice nunca, sino que creen en Él porque se trata de un santo, de una personalidad mucho más elevada que cualquiera de nosotros. Hubo gente malvada a su alrededor que los torturaron; sin embargo, en general, la gente los respetó. Si hay falsos gurus, normalmente no se quedan en este país porque saben que los descubrirán.

También ellos son tan materialistas que se van a América o a cualquier otro país y se establecen allí para ganar dinero. Esta es una de las señales que debemos ver y una de las razones por las que Cristo nació en una familia muy normal. No tuvo una cama cómoda para dormir, ni siquiera cuando fue niño. Todo se ha descrito: cómo durmió, cómo sus padres vivieron en un lugar lleno de bueyes y vacas. Fue así para demostrar que la espiritualidad no necesita ningún tipo de lujo ni de pompa.

Es un poder interior; es un brillo, una luz interior, que se muestra automáticamente; no tenéis que hacer nada para mostrarlo. Una persona así no necesita del dinero ni de la posesión de otras cosas. Se preocupó mucho por la gente que sufría físicamente, incluso por los leprosos, y trató de curarlos; intentó ayudar a mucha gente que estaba enferma físicamente.

En esa época no existían hospitales ni médicos, así que, su atención se centró en las personas que sufrían físicamente. También trató de prepararlos mentalmente. De hecho hay muchos hermosos sermones que dio en las montañas. De alguna manera, en esa época la gente no era tan materialista y lo escuchaban, pero no sabemos cuántos le entendieron. Es muy importante que sepáis que, si alguien no es un ser realizado, es muy difícil que entienda la espiritualidad. Tanto el que está hablando como el que está escuchando deberían tener como mínimo su Realización.

De su maravillosa existencia debemos aprender que, hasta que no seamos almas realizadas, estaremos torturando el Espíritu de Cristo. Lo hemos visto en todos aquellos que hablan de Cristo. Él lo dijo muy claramente: Me llamarán por mi nombre "¡Cristo, Cristo!", y no los reconoceré.

No sé por qué no quitaron esto de la Biblia. Significa que no reconocerá a aquellos que hablan y sermonean y se visten para aparentar que son espirituales en el nombre de Cristo. Es tan simple como eso. Y ahora, en estos tiempos del Juicio Final, va a juzgar a todo el mundo sobre la base de la espiritualidad, es decir, según las vibraciones.

Su Juicio ya ha comenzado. Lo podéis ver en muchos países; las cosas están desapareciendo. Todo su ego, toda su agresividad, todas sus crueldades se están rebatiendo y también se está censurando a aquellos que obraron mal en las guerras. En la historia, también serán juzgados aquellos que han hecho daño a las comunidades y a las personas. No tenían ningún derecho a ser agresivos ni a torturar a la gente. Este es el Principio de Shri Ganesha actuando a través de Sahaja Yoga.

Cristo no dijo eso, pero sí dijo que habría un Juicio Final. Por un lado fue muy tierno y compasivo; por el otro fue realmente Shri Ganesha porque cogió un látigo para pegar a la gente que estaba vendiendo cosas en el templo. No se pueden hacer negocios en nombre de la religión. Fue un hecho muy importante que debieron haber entendido, pero los cristianos no siguieron esa enseñanza; no la siguieron. No sé a dónde han ido a parar.

También nosotros tuvimos a Mahatma Gandhi que habló de espiritualidad y de nada más. Pero sus sucesores olvidaron su espiritualidad y empezaron un nuevo mundo con nuevas ideas y un nuevo estilo de vida. Aquellos que se suponen son sus seguidores ahora desean tener muchos bares y todo tipo de cosas. ¿Podéis imaginarlo? Mahatma Gandhi inició este Congreso, pero ved lo que está haciendo hoy el Congreso de "wallas". ¿Dónde van a ir a parar?

La belleza y el tesoro de este país es su espiritualidad. En lugar de volcarse hacia ella, ¿dónde van? Tal vez no sean cristianos, pero respetan a Cristo y la Biblia. Es un hecho que la gente no conoce. No son cristianos en el sentido de que no están bautizados, pero lo respetan porque saben que en Cristo hubo mucha espiritualidad. Él era la personificación de la espiritualidad. Esa es la belleza de los indios, que no importa si uno es hindú o musulmán. Hubo muchos musulmanes que fueron santos y sufis en India y todos los respetaron sin importar si fueron musulmanes o hindúes.

Así que nadie estuvo en contra de Cristo; por el contrario, ayer visteis cómo todo el mundo estaba contento con esto, porque son almas realizadas. Pero incluso si no lo son, Cristo es muy respetado en este país. No pueden entender cómo escudriñan la vida de Cristo. ¿Cómo lo pueden juzgar así? ¿Cómo pueden hacer películas tan vulgares sobre su vida? No lo pueden tolerar porque tienen gran respeto por la espiritualidad. Mucho más que el que existe en otros sitios. En nombre de Cristo las personas han hecho muchas cosas horribles y han cometido terribles asesinatos. Se han aceptado todo tipo de hechos equivocados y siendo así, uno no puede entender cómo se han atrevido a juzgar a Cristo.

Por ejemplo, me impactó mucho de Inglaterra que si alguien moría, bebían y si alguien nacía también lo celebraban bebiendo. Beber es la única manera que conocen para relacionarse unos con otros (Madre se ríe). ¿Cómo podéis beber? -les pregunté. Y ellos me contestaron: ¿Por qué? Cristo creó vino. Yo les dije: ¿Cuándo? En unas bodas -contestaron. ¿En unas bodas? Les dije: Eso no era vino, era solo el zumo de las uvas que metieron allí. En nuestra lengua lo llamamos drakshas. ¿Cómo puede ser eso vino? Tendría que haber fermentado y haberse podrido, ¿cómo es posible? Este es su dharma más grande, beber.

Pero en India sabemos que, aunque nadie haya dicho nada en contra de la bebida, beber es un pecado. Todo el mundo sabe que si alguien bebe se vuelve completamente loco. No hay nada que decir desde el punto de vista religioso, pero todo el mundo sabe lo que significa beber. No es que la gente, fuera de India, no sepa lo que significa; ellos también lo saben. Pero de alguna manera se ha vuelto una moda. Incluso en nuestro país ha entrado recientemente. No sé cómo la gente comenzó a beber después de la independencia. Beben en todas las fiestas, incluso el día de Navidad beben en nombre de Cristo. Es un insulto tremendo hacia su santa y maravillosa vida.

Entonces cuando llegaron a esta tierra, quizá se destruyeron todos sus poderes de santidad. Lo bueno de los indios es que al menos respetan los lugares sagrados y saben lo que significa la santidad. Por supuesto, ahora se están modernizando y americanizando mucho. Pero todavía saben lo que está mal y lo que no debe hacerse.

Me siento muy feliz al decir que gracias a Sahaja Yoga, los sahaja yoguis extranjeros también se han convertido en algo verdaderamente bello. Estoy sorprendida porque en su cultura no existe la espiritualidad. Pero no sé cómo han dejado a un lado toda esa frivolidad y han florecido como hermosos lotos, con esa fragancia y de una espiritualidad tan bella. Es un milagro. Todo el mundo lo dice: Madre, no lo podemos creer, ¿cómo ha podido ocurrir? ¿Cómo has hecho esto? Yo les digo que es la bendición de Cristo. Han visto cómo la gente está trabajando en nombre de Cristo de una manera muy degradante y han desarrollado una especie de consciencia en la que ven que hay algo que está mal en ello, que esto no es de Cristo, que no están representando su vida sagrada. Es otra cosa. Por eso, creo que en Occidente hay un mayor deseo y una fuerza más grande de ascenso.

Ayer alguien vino y me dijo: Madre, no hay meditación colectiva. Me sentí muy feliz de escuchar esto. Lo más importante en Sahaja Yoga es la meditación, sin duda. Pero es sorprendente comprobar que los extranjeros meditan mucho más que los indios. Y tengo que reconocer que los hombres y mujeres extranjeros están bastante preparados para la espiritualidad. Especialmente los rusos. Me sorprendió que en América me dijeran: Madre, estos americanos no son sahaja yoguis. Yo les pregunté: ¿Por qué? No tienen respeto por Ti, no meditan. Aquellos que no meditan no son sahaja yoguis. Yo les dije: Estoy de acuerdo. E hicieron que todos los americanos meditaran. No sé cómo la gente de los países del este, búlgaros, rusos y rumanos se han volcado tanto con Sahaja Yoga. Sufrieron la maldición del comunismo sobre ellos. Quizá sintieron que se habían perdido algo de la vida y profundizaron en su interior y así es cómo lo han conseguido.

Pero debo decir a los indios que deben meditar. Tienen uno o dos defectos muy serios y uno de ellos es el grupismo. Por ejemplo, si son "brahmines", se sentarán todos juntos, si son "kayasthas", se sentarán todos juntos; si son "bhaniyans" se sentarán todos juntos. Y si no son nada de eso, entonces buscarán un nombre nuevo y se agruparán juntos. Esta es la peor maldición de mi país, porque una vez que se inicia un grupo, nunca podrán ver lo bueno de los otros ni lo malo de sí mismos. Este grupismo puede traer muchos problemas a este país.

En el tiempo de Cristo había gente muy diferente, tanto si estaban interesados en la espiritualidad como si no. Ahora tenemos personas que están interesadas en la espiritualidad, pero todavía mantienen un pie fuera. En algunas partes todavía prevalecen viejos problemas y esta es la ruina de nuestro país. No nos podemos mezclar, no podemos ser amigos entre nosotros. Por supuesto, este no es el caso de Sahaja Yoga. Debo decir que se ha solucionado muy bien.

Pero, incluso en su tiempo, Cristo tuvo problemas con sus discípulos. Especialmente con Pedro, sucedió algo. A él le dijo: "Se te presentará un demonio". Porque creo que la gente cae en manos de las fuerzas satánicas. Él mismo dijo que había liberado a personas de demonios satánicos a los que después puso en cerdos. Es verdad, hay una fuerza satánica trabajando con intensidad. Cuanto más desarrollamos la seguridad en la espiritualidad, más se crecen.

La fuerza satánica es diferente en Occidente y Oriente. Pero hay que ser cuidadosos a la hora de descubrir las fuerzas satánicas en Occidente. Puede que no os afecten porque sois almas realizadas, pero debéis luchar contra ellas. Por ejemplo, el racismo. El racismo es todavía muy poderoso, muy, muy poderoso. Tenéis que luchar contra el racismo casándoos con personas que pertenezcan a otra raza. Sin embrago, todavía es difícil casar una persona negra con una blanca, es una situación imposible. Cuando lo intento nunca sé qué puede ocurrir.

En una ocasión celebramos el matrimonio entre una mujer blanca francesa y un hombre negro. En lugar de que la parte dominante fuera la mujer blanca, sucedió al revés: el hombre negro era el dominante. No sabía cómo había podido ocurrir. La razón fue que él quizá se estaba vengando, era su revancha. Entonces en primer lugar ha de crecer el amor y el afecto entre las personas. Esto del color está muy en la superficie. No tiene nada que ver con el amor que se siente dentro, nada. Gracias a Dios en nuestro país uno puede ver parejas en las que la esposa es de piel muy oscura y la del esposo, muy blanca o viceversa. Pero ellos jamás se mirarán desde ese ángulo. No creo que el racismo exista en este país.

Pero tenemos otro obstáculo. La discriminación que hace el ego es un problema típico de los seres humanos. Cristo trató de luchar contra el ego. Nació en una familia muy humilde y no tuvo la piel blanca en absoluto. En vuestro idioma sería moreno, pero en el lenguaje de la India sería negro. Sin embargo, desde el punto de vista de la espiritualidad, solo se ve al Iluminado. No se mira el color de su piel, es muy superficial.

Pero este es uno de los peores enemigos de la vida en Occidente y ha de ser superado. Otro enemigo es el materialismo. Pero el peor de todos los que van contra Cristo es la inmoralidad. La inmoralidad está muy aceptada en Occidente. Se aceptan toda clase de comportamientos inmorales. Por ejemplo, toda esta gente inmoral vota a un candidato que llega a ser presidente de América, y ya está. Todo está bien, nada importa y se permite todo tipo de inmoralidad. Pero esto va totalmente en contra de Cristo.

La gente no entiende que la inmoralidad los llevará a un reino que ni siquiera sé cómo llamar porque es mucho peor que el reino animal. Y son tan inmorales, escuchan a personas como Freud, como si no tuvieran un cerebro, no tuvieran un Espíritu para darse cuenta de semejante persona. Solo después de Sahaja Yoga se puede tener el modelo de la vida de Cristo. El pasado ha pasado y ya ha terminado.

Hoy sois almas realizadas y la moralidad es vuestra fuerza. Olvidaos del pasado. Estoy segura de que podéis traer mucha más gente a Sahaja Yoga, si lleváis una vida moral. Al mismo tiempo, otro enemigo muy terrible que tenemos es la ira. La gente se enorgullece y dice: Me enfadaré, ¿sabes? Ahora estoy muy enfadado. No les da vergüenza y siguen diciendo: "Estoy muy enfadado"; como si no hubiera nada de malo en decir "estoy enfadado".

También dicen: "Te odio". Imaginaos si se utilizara esta palabra en cualquiera de las lenguas de la India; significaría: Estoy cometiendo un pecado. Toda esta agresividad viene de la ira. Si alguien tiene que estar enfadado, debería estarlo consigo mismo. Lo mejor para deshacerse del mal genio es tirarse de los pelos, morderse o darse golpes con la almohada (Madre se ríe). Esa sería la mejor manera de sacar la ira. Pero mirad: ¿Por qué estáis enfadados? Algunas veces es totalmente innecesario. En ocasiones ni siquiera tiene sentido. En otras es estúpido y de locos. Pero con tal de que dejéis de decir: "Estoy muy enfadado", ya es suficiente. Es el momento de saber que estáis cayendo completamente.

Cristo no habló del aspecto sutil. Yo lo he hecho porque se me asignó ese trabajo. Sin la Realización, ¿cómo se puede hablar de cosas sutiles? No se puede. La última vez os hablé sobre las vibraciones; qué son, para qué sirven y cómo pueden llegar a esa energía sutil llamada "tanmatra". De nuestra luz: "Tejas", del agua: "Jala" y Prithvi, agni. Pero no os he hablado de algo muy especial, que en inglés llamáis éter.

El éter es la energía que es manejada por otro "tanmatra" que denominamos "akash". Hoy es un día especial porque Cristo sacrificó su vida para abrir nuestro Agnya chakra. Por eso alcanzamos el estado de "akash". Sin Él no hubiera sido posible. Podemos tener una comunicación global. Como el que podemos hablar con otras personas, decirles cosas; también podemos usar nuestros dedos para expresarnos y nuestras manos para comunicarnos. Pero para comunicar vibraciones, hay que tener vibraciones. Si no, es imposible sentir a otra persona. Pero estar al nivel del Agnya significa ser aún mental. Entonces las vibraciones también estarían cayendo, en el sentido de que ni siquiera sabríamos lo que realmente están diciendo. No se pueden "juzgar" las vibraciones porque serían mentales.

Me dicen: Madre, le preguntamos a las vibraciones. Yo les digo: ¿De verdad? Pero si no las sentís, ¿cómo podéis preguntar a las vibraciones? Es algo muy común. Le preguntamos a las vibraciones, pero estas están en el nivel mental. Lo que Cristo ha hecho es sacaros del nivel mental y eso es lo más difícil. Me sorprendió comprobar que aquellos que siguen el cristianismo tienen la peor posición mental.

Son muy mentales, están siempre allí, como la niebla en Delhi; no se puede atravesar. Esto es lo que Cristo rompió. Cuánto le debemos. Eliminó el mayor obstáculo para el ascenso humano y esto fue la apertura del Agnya, el ser mental en nosotros. Leemos como locos. Escuchamos a la gente como locos. Nos gustan aquellos que alimentan nuestra mente. Son tan mentales, tan argumentativos; creen que su inteligencia no tiene fin, que uno debe decirles a todos: "Muy bien, namaskar". No se puede luchar contra su actitud mental.

Por eso Cristo ha sido venerado por gente muy mental. Y este sin sentido mental les ha hecho creerse superiores a los demás. Hagamos lo que hagamos, ¿qué hay de malo en ello? ¿Qué hay de malo? No saben corregirse a sí mismos. Porque hasta que no se haya cruzado el límite del ser mental, uno no puede verse a sí mismo. No se puede hacer introspección. No pueden verse a sí mismos. Verán a otros: los sahaja yoguis son así, Sahaja Yoga es asá... Pero no podrán verse a sí mismos porque todo eso es mental. Esta actitud mental debería ser doblegada por completo a través de la ayuda de nuestro Señor Jesucristo. Pero Él también es algo mental es sus cerebros; Cristo es también un concepto mental, entonces, ¿qué hacer? Él, que rompió la actitud mental, es también mental, la gente lo ha hecho mental, como una estatua de piedra.

Entonces lo primero que debemos hacer es decirnos a nosotros mismos: "No pienses, no pienses, no pienses, no pienses", cuatro veces. Entonces podréis superar el plano mental; esto es muy importante. En la meditación tenéis que ir más allá de la mente. Y esto es posible gracias a Cristo, que está sentado en el Agnya para acabar con el absurdo del ser mental. Creo que la gente debería dejar de leer. Tal vez incluso mis charlas se hacen mentales, ¿qué hacer entonces? Lo que trato de decir es que todo lo que entra en vuestras cabezas de alguna manera se hace mental.

Luego me hacen preguntas: Madre Tú dijiste esto. ¿Qué dije? Lo dije para dejaros sin pensamientos, para impactaros. No lo dije para que nos sentemos y hagamos análisis, no, no. Dije eso para que os quedarais completamente pasmados, impactados. Por eso, lo mejor para vosotros es que os quedéis sin pensamientos que es la bendición de Cristo y lo que Él ha trabajado para vosotros. Estoy segura de que si lo desarrolláis no pondréis la atención en otros. No reaccionéis. Cada cosa que ven reaccionan. ¿Qué necesidad hay? ¿Para qué sirve? ¿Que vais a hacer con esa reacción? Esa reacción solo crea ondas de pensamiento en vuestra mente. Os lo he dicho cien veces. Y ahora tenéis que quedaros completamente sin pensamientos después de este Puja.

Si esto sucede creo que habremos conseguido mucho. Esta es la mayor bendición que Cristo os ha dado y que podéis gozar. Solo entonces funcionará el "akash tatwa" en vosotros. ¿Y cómo funciona? A través de vuestra atención. Funciona conmigo, como sabéis. Con mi atención puedo hacer muchas cosas. ¿Cómo? Porque mi atención se ha vuelto sin pensamientos. Allí donde va funciona. Pero si ponéis todo el tiempo vuestra atención en pensamientos, entonces no funciona como debería hacerlo. La atención funciona maravillosamente si estáis sin pensamientos, de otra manera no funciona.

Por lo tanto debéis elevaros por encima de vuestro propio Ser y del de los demás hasta alcanzar un nivel más alto de Humanidad, donde estéis en comunicación con el Cielo. Es lo que podemos llamar "Tanmatra" o lo esencial, la esencia del éter. Gracias al éter podéis tener televisión, teléfono; es un milagro. Pero con este "Tanmatra", sentados aquí, podéis hacer el trabajo. Funciona, la atención funciona. Lo sé y vosotros también lo sabéis. No tenéis que pedirme que ponga la atención, simplemente ponedla vosotros y funcionará. Es algo muy importante que habéis recibido. Creo que es lo primero que se manifiesta cuando no tenéis problemas.

Pero nos empezamos a manifestar primero desde el elemento "tierra". Luego desde el elemento "agni", después desde el elemento "jala", y entonces llegamos a "tejas", donde el rostro comienza a brillar. Por último alcanzamos la conciencia sin pensamientos por medio de la cual, nuestra atención es completamente libre para hacer este trabajo especial. Pero si estáis todo el tiempo pensando, entonces esta atención tan pobre está muy ocupada, muy ocupada. No tenéis que pedírmelo: "Madre, por favor, pon tu atención..."; vosotros podéis poner vuestra atención y podéis hacerlo funcionar.

En esta atención, no sentís lo que tenéis, lo que habéis alcanzado, lo que vestís, lo que otros están haciendo, nada. Sois uno con vosotros mismos. Es una vida llena de buen humor, de mucho gozo y de mucha felicidad. No os preocupáis de las cosas por las que la gente se preocupa habitualmente.

Así, hasta ahora, Sahaja Yoga ha funcionado en muchos países y estoy muy orgullosa de todos vosotros, muy orgullosa. Ahora también va a funcionar en los países africanos. Es una gran satisfacción para mí. Todos vosotros podéis hacerlo, podéis hacer que funcione. Solo hay una cosa: debéis entrar en absoluta conciencia sin pensamientos como bendición de Cristo. Si funciona, disfrutaréis plenamente de vosotros mismos.

Que Dios os bendiga.