Navaratri Puja, "The deities are watching you". Arzier, Geneva (Switzerland), 23 September 1990.

De acuerdo con el calendario, este año hay diez días en el Navaratri, no nueve. 

Son nueve días, durante la noche, cuando la Diosa tiene que luchar con los demonios, para salvar a sus niños de los efectos de la negatividad. Por un lado Ella es el océano de amor y compasión, y por otro lado Ella les protege como una tigresa. Porque los tiempos eran tales, que nadie podía meditar, nadie podía tomar el nombre de Dios, nadie podía pensar incluso, en la autorrealización. Pero todos los que estáis sentados hoy aquí, ya estuvisteis en aquellos tiempos y todos fuisteis salvados para hoy, para este día. De forma que pudieseis lograr vuestra autorrealización. La forma de la Diosa en aquellos días, no era Maya Swarupini. Ella vino en su forma real y esto creó un gran respeto, incluso entre sus discípulos. Así es que no era la ocasión de darles la realización, antes de nada, tenían que ser salvados. De igual forma la madre, tiene al niño nueve meses en su vientre,. Durante esos nueve meses o, podríamos decir, por nueve yugas, por nueve veces vosotros habéis sido salvados apropiadamente y al décimo mes habéis tenido el nacimiento. 

También este nacimiento es siete días después de nueve meses. Así es que tenemos que esperar por algún tiempo a que madure. El décimo Navaratri de hoy es, en realidad, para celebrar a la Adi Shakti. Hoy vamos, realmente, a adorar a la Adi Shakti. Por un lado la Adi Shakti es Mahakali. Por otro lado Ella es Mahasaraswati, en el centro es Mahalaxmi, y también Amba, la que es la Kundalini. Pero Ella también está más allá. Ella es Parashakti. Ella está más allá de todos los Poderes, porque es la generadora de Poderes. Así es que tiene que estar más allá. 

Hoy que la estamos adorando, tenemos que hacerlo en todas sus formas. Así entendéis que el décimo día de Navaratri; que tenemos por primera vez en el calendario, es el día en que adoramos a la Adi Shakti. La Adi Shakti, nunca antes fue adorada, nunca. Pero esta vez, cuando fui a Calcuta, les dije que mejor adoraran hoy a la Adi Shakti, y ellos se sorprendieron. ¿Por qué pide Madre que hoy adoremos a la Adi Shakti? Cuando volví a Puna me dijeron, que Adi Shakti; como vosotros sabéis, es Saptashringi, que significa la de las siete colinas, descansa entre siete picos, que quiere decir, en el Sahasrara, en el séptimo chakra. Ella gobierna los siete chakras. Me dijeron, que cuando tuvimos el Puja en Calcuta, en aquel mismo momento, es la única vez en que los seguidores de Saptashringi, que son muy pocos, fueron todos allí. Todos ellos fueron allí. Primero los del lado de la Madre. 

Los del lado de la Madre, de la Adi Shakti, se les considera vishnavitas, los que siguen a Vishnu. Primero fueron ellos a adorarla y después los del lado del suegro, que es el lado de Shiva. El lado de Sadashiva. Fue exactamente, en ese momento cuando tuvimos el Puja. Estuvieron estos dos grupos, juntos en la adoración. Y así tenemos entre nosotros gente de dos tipos. Los que adoran a Brahmadeva en el lado derecho y la gente que adora a Shiva en el lado izquierdo. Los dos lados se tienen que encontrar en un punto y este punto es, que tenemos que adorar la forma completa e integrada de todos estos Poderes, que se han manifestado dentro de nosotros. Cuando dicen que sólo hay un Dios, de acuerdo, sólo hay un Dios. Pero este Dios tiene su cabeza, tiene su hígado, su estómago, tiene su nariz, tiene todo. 

Igual que los seres humanos. Por eso se dice, que Dios hizo a los seres humanos a su imagen y semejanza. Así Él tiene diferentes partes en su cuerpo y tiene que hacer funcionar todas las partes y para estas partes diferenciadas, tiene que tener deidades y estas deidades deben ser comprendidas. Y a menos que las entendáis y adoréis, no podéis despertarlas dentro de vosotros. Pero son parte de la Adi Shakti. Están totalmente bajo el control de la Adi Shakti. Ayer oísteis acerca de los Poderes de la Adi Shakti. Es como una tortuga que recoge todo su cuerpo dentro del caparazón. De la misma forma, Yo tengo todos estos Poderes en mi interior. No podéis descubrirlos fácilmente. 

No podéis verlos fácilmente Excepto por estas cámaras modernas que intentan estafarnos. Ellas son las que os muestran mis formas. Porque hay luz en estas vibraciones y cuando estas vibraciones se emiten las veis en estas cámaras. Incluso aunque no sean muy sensibles, pero de alguna forma, la gente las capta. Se han hecho muchas fotografías milagrosas, como sabéis. Habréis visto una, en la que Shri Ganesha está detrás de Mí. Ahora no veis a nadie aquí. Pero no sabéis lo que está pasando. Y esto es lo que hay que entender, que hemos entrado en un nuevo reino de la magia de Dios. Y su magia funciona de muchas maneras. 

Por supuesto, algunas veces os perdéis debido a vuestros problemas anteriores. Sois tentados. A veces también sois dominados por las fuerzas negativas, y caéis. Y es algo muy triste, que esto le suceda a algún sahaja yogui. Porque quizás no conocéis vuestro pasado, no conocéis cuánto habéis luchado cuánto habéis trabajado para llegar a este nivel. Y si después de llegar a este nivel, no intentáis elevaros más, os quedaréis estancados en el mismo lugar o seréis expulsados. Así que para vosotros, el saber que sois sahaja yoguis, no sois una esposa, esposo, madre, padre. Sois un sahaja yogui, igual que Yo soy la Adi Shakti. Así vosotros sois sahaja yoguis. Mi principal trabajo ahora, es dar la Realización a otros. 

Y como todas mis relaciones, están ahora fijadas apropiadamente no me tengo que preocupar por ninguna deidad, por ningún Dios. Todos hacen muy eficientemente su trabajo. Ayer leísteis la descripción de la Diosa. Como sus manos lanzaban flechas con tal velocidad, que uno sentía que Ella estaba danzando. Es así, no hay duda. Pero vosotros no lo veis. No podéis ver, que cada uno de mis cabellos es como una flecha y actúa tremendamente. Pero para vosotros, estoy aquí sentada tranquilamente, de la misma forma que os sentáis vosotros. Pero no es así, es mucho más. Cuando muestran un león o un tigre, como mi vahana, debéis entender, que en realidad están ahí. 

Están ahí en realidad. No es algo simbólico. En realidad están ahí. La dignidad del tigre. Os lo he dicho muchas veces, que digno es. Porque Yo me siento en él es tan digno. Si tiene que comer carne, matará una vaca o algo así, comerá su carne y dejara el resto para otros. Es tan digno, y come una vez al mes. Así es que incluso para obtener una vahana de este tipo, tenía que evolucionar, desde el estado de ameba hasta este. De otra forma, no estaría aquí. 

Igualmente vosotros habéis evolucionado y en vosotros también están todos estos vahanas y hacen funcionar rápidamente todo lo que queréis. Desead algo y os sorprenderéis como funciona inmediatamente. Pedís algo, e inmediatamente funciona. Pero debería haber, una completa dedicación, a Sahaja Yoga. Cuando digo Sahaja Yoga, sabéis que es el yoga, de vuestra atención en mis pies. Eso es lo que es. Pero si aún os movéis en vuestro ego, pensando en esa línea, cómo nosotros podemos hacer nuestro propio Sahaja Yoga. Podemos hacerlo de esta o aquella manera. O mi esposa es así, mi hijo es así, mi esposo es asá. Tenéis que abandonar todos estos problemas a un lado. 

De otra forma, no ascenderéis. Para Mí, no ha sido difícil daros la Realización. Porque ya estabais listos para ello. Pero para mantener vuestra luz encendida, tenéis que trabajar duro. El tigre se mantiene en su posición, no cambia. El león se mantiene en su posición. Y están allí, siempre disponibles para vosotros, en su posición. Todos los Devatas y Dioses están en su posición, con sus cualidades. Están ahí. En ningún lugar se dice, que estos Dioses os dan Moksha. 

Excepto la Diosa, Ella es la única que os da la Realización, porque Ella está a cargo de los siete chakras, Ella sostiene los siete chakras y puede hacerles funcionar. Así es que hay una gran historia de evolución, de todas estas cosas, en el cuerpo del Virata y en vosotros. Tenéis que cooperar con esto. Si no podéis cooperar, entonces, no funcionará. Los problemas en occidente, son problemas estúpidos, que no encajan, con ningún sahaja yogui. El apego. Primero no estaban apegados a sus mujeres o sus niños y ahora están apegados como con pegamento. No digo que abandonéis a vuestra mujer o vuestros hijos, pero el apego debería ser a Sahaja Yoga. Una vez, que las bendiciones de Sahaja Yoga, fluyan a vosotros, estas llegarán, a vuestros hijos, a vuestra mujer, a todo el mundo, a vuestro país, al mundo entero. Supongamos que esto es el apego, algo eléctrico muy simple. 

Si el apego no es a la fuente, ¿qué sentido tiene?, No dará electricidad a nadie. Es una lógica muy simple, el que tenéis que estar apegados a la fuente de energía primero, una lógica muy simple. Y entonces esta energía, puede fluir a otros. Si vosotros mismos, no estáis apegados a la fuente de energía; ¿cómo puede este Poder, fluir a ninguna parte? Es algo muy simple, que no entendemos en Sahaja Yoga. Y así nuestros apegos, empiezan a crecer y no entendemos qué nos ha pasado. No estáis apegados a la fuente principal. Y este es, el único apego que necesitáis. Entonces todo fluirá de otro modo. Así es que tenemos todos estos apegos. 

También estamos apegados, a tantas cosas miserables, que nos gustan, que nos hacen miserables. Por ejemplo, estamos apegados a un estúpido tipo de negocio de la moda. Estamos apegados a ello. Tanto si está en la cultura sahaja o no, estamos apegados a ello. Y todos estos apegos, no son a la fuente. A la fuente de gozo, a la fuente de conocimiento, a la fuente de energía que os eleva. Esta es la razón, por la cual, nuestra situación de ascenso colectivo está estropeada. El trabajo de la Adi Shakti es; primero daros la Realización. El segundo es daros vida, reconfortaros. Si tenéis problemas físicos Ella os cuidará, hará todo lo posible. 

Si tenéis problemas mentales, tratará de solucionarlo, así es que Ella es la benefactora, os confortará. Al mismo tiempo Ella os protege. He visto a mucha gente, incluso ahora que se asustan, muy fácilmente a la mínima cosa. ¿Por qué os asustáis? Hay un tigre aquí. No podéis verle, pero quizás hoy aparezca en alguna fotografía. Y vuestra Madre es tan poderosa. Tenéis que entender, qué poderosa es. Esta comprensión, no está en vuestra cabeza. A veces, vuestra mujer es más poderosa, o vuestros hijos son más poderosos. 

Cuando sabéis que vuestra Madre es tan poderosa y es vuestra Madre. Entonces deberíais sentiros absolutamente seguros, entonces las cosas funcionan. Os daré el ejemplo de un señor, que conocí en Madrás no hace muchos años, quizás hace dos o tres años. Tan buscador, inmediatamente Me reconoció. Él fue a Bombay, recibió una carta que decía, que su madre iba a morir. Entonces se fue para allá. El médico dijo que tenía cáncer y moriría pronto. Él sabía: "mi Madre es la Adi Shakti". Cogió mi fotografía y se sentó frente a Mi diciendo "Madre no tengo nada que decir, aquello que sea apropiada para mi madre, por favor; hazlo". Así, sólo dijo esto. 

Está conectado. Lo dijeron: tres días después de que ella se estaba muriendo, tres días después, estaba fuera del hospital. La volvió a llevar a Bombay, a un hospital de cáncer y le dijeron que no tenía ningún cáncer, que estaba completamente curada. Si a la energía no se le permite fluir, seguiréis preocupados por vuestra esposa, preocupados por vuestra casa, por vuestros hijos, por esto o aquello, preocupado por mi hijo, mi casa, mi esposa... Cuando este "mi" se cae, entonces Yo puedo actuar. Pero no lo deberíais tomar como que deberíais ser ascéticos. Ningún santo era ascético, todos tenían esposa e hijos, pero toda su atención, estaba a los pies de loto de la Madre. Como dijo Guru Nanak: el niño pequeño juega con su cometa, la cometa va todas partes, y él está hablando con sus amigos, bromeando, pero su atención está en la cometa. Hay una mujer que está limpiando la casa con un niño pequeño sobre ella. Ella limpia, friega, hace todo, pero su atención, esta en el niño. Y hay mujeres en India, que caminan con tres o cuatro cántaros de agua sobre su cabeza. 

Caminan con ambas manos así, para equilibrarse, hablan entre ellas, bromean, y ríen, pero la atención, está en los cántaros. Mi atención está siempre en vuestra Kundalini. No podéis hacer trucos en Sahaja Yoga, hacerme caso, cualquiera que intente hacer trucos será muy duramente castigado. Por favor, tener mucho, mucho cuidado, no ser deshonestos, ni hacer trucos en Sahaja Yoga. Yo no haré nada, pero aquí están ellos. Ya veis, con todos sus dientes. Todos ellos tienen cualidades fijadas, Yo se lo he dicho, tienen cualidades fijadas. Saben que hacer y lo harán, así es que no hay ninguna necesidad de hacer trucos en Sahaja Yoga. Este es otro error de los sahaja yoguis, que piensan que pueden hacer trucos conmigo, o con Sahaja Yoga. Cuando estas cosas vienen a vuestra cabeza, Yo diría, que son ideas demoníacas, porque os destruirán completamente. 

Por un lado, Sahaja Yoga es una bendición, una absoluta bendición para vuestro ascenso. Os eleváis así y alcanzáis una altura, pero debéis saber que ya que habéis alcanzado esa altura, debéis ser muy cuidadosos de permanecer allí, porque una vez que caigáis de esa altura: ¿qué profundo podéis llegar? Es lógico de nuevo, ver que caeréis muy bajo. Aquí, tenéis las bendiciones, toda la belleza, todo el amor, todo el gozo, todo el conocimiento, todos los amigos, todo el cuidado. Pero si no queréis permanecer aquí, ya que aún hacéis trucos. Si queréis estar aquí y hacer trucos, eso no es posible. Eso no funciona, sois expulsados inmediatamente, y una vez que sois expulsados, sólo Dios sabe dónde iréis. No es nuestro asunto, pero sois expulsados por esto. Tenéis que saber que las deidades, están extremadamente alertas y os están observando a todos vosotros porque tienen que guardaros, tienen que cuidaros, tienen que ayudaros, tienen que hacer todo por vosotros. Tienen que hacer funcionar todo para vosotros. 

Ellas son las que crean flores para vosotros, hacen todo tipo de cosas por vosotros, pero al mismo tiempo, sólo están apegadas a Mí, todas ellas, no a vosotros. A causa de que sois mis hijos, ellas os cuidan. Cuando tratáis de portaros mal, estáis acabados y descendéis, pero la compasión de vuestra Madre es tan grande que Ella siempre intenta perdonar, dar más oportunidades y decir a estas deidades que permanezcan quietas, porque ellas obedecen, pero hasta cierto punto. Porque si vosotros queréis ser gente desagradable, si queréis ser crueles, si queréis ser pecadores, y permanecer en Sahaja Yoga, no podéis. No es como cualquier otra religión, como visteis ayer, en la que cometéis cualquier equivocación, hacéis lo que queréis, matáis a alguien, estafáis a alguien y permanecéis allí. No es así. Aquí tenéis que ser sahaja yoguis, en el sentido real de la palabra. Y tenéis que entender esto. Vienen algunos sahaja yoguis y no pueden entrar. Las puertas estarán cerradas. 

Este tremendo Poder, tan alerta, tan afectivo, tan atento; está allí, y la Madre, que es vuestra maestra, la madre enseña a sus hijos con amor, y no sólo eso, sino que nunca habéis sentido cómo os he enseñado Sahaja Yoga. Simplemente lo habéis aprendido. Es un juego de niños para vosotros. Es una materia tan difícil y tan sutil, y la habéis aprendido sin ninguna dificultad. Se hizo con tanto corazón, tan bellamente construyéndolo dentro de vosotros, y ahora sabéis; esto es Sahaja Yoga, esto no es Sahaja Yoga. Todo este conocimiento ha venido a vosotros tan dulcemente. La forma en que cantáis música india, si veis, incluso los indios se sorprenden, ellos no pueden cantar como vosotros. A veces, los músicos que han venido a mis programas, os han visto y han dicho; "estamos avergonzados, ¿cómo puede cantar esta gente tan bien, y pronunciar todo tan bien?" Vosotros tenéis que confiar completamente en este Poder. En aquellos días en que la gente tenía dificultades, siempre eran atacados, y no tenían la realización, tenían que confiar en el Poder Divino, tenían que confiar. 

Pero ahora que habéis obtenido vuestra realización; habéis obtenido vuestra liberación. No debéis nunca olvidar que tenéis que confiar en el Poder Divino todo el tiempo, Él os cuidará. Ahora: ¿cómo hacemos trucos en Sahaja Yoga? Algunos tipos perezosos vienen a Sahaja Yoga, tipos absolutamente holgazanes, que deben de ser del lado izquierdo o algo así. Y si les dices; "mejor haz este trabajo", ellos dirán: "No Madre, no haré ese trabajo, porque entonces aparecerá mi lado derecho". Un truco muy común. Es un truco muy común. "No puedo hacer este trabajo". Cuando viene el trabajo, ellos salen corriendo. ¿Cuánta gente trabaja? 

Muy pocos. El otro día fui a la cocina y pregunté a las chicas indias: "¿qué está pasando?" Y ellas dijeron: "Todas han salido corriendo, no hay nadie aquí para ayudarnos". Nadie quiere tomar la responsabilidad. Pero el truco que se usa en Sahaja Yoga es que "Si yo hago esto me voy a ir al lado derecho". Pero si os vais al lado izquierdo, este está allí . Está muy bien que le halláis puesto aquí, estoy muy feliz. Así es que toda la gente letárgica, holgazanes, siempre hacen esto. Ahora, a alguien se le dice que se levante por la mañana. Él se siente terriblemente con esto; ¿cómo levantarme? 

Pero si volvéis atrás, a vuestros antecedentes, debéis haber tomado drogas, alcohol, todas estas cosas del lado izquierdo, y por eso no podéis levantaros por la mañana. Entonces: ¿cómo vais a neutralizar estos malos hábitos que teníais? ¿Cómo lo haréis? Si empezáis a levantaros por la mañana temprano, poco a poco, el hábito disminuirá, y le abandonaréis. Es simplemente que estéis disponibles cuando el sol de la mañana, va a salir. El alcohol mismo, es un absurdo del lado izquierdo, tanto; que una vez la Diosa bebió todo el alcohol del mundo. No lo creeríais; todo el alcohol. Igual que Sainath; que fumó todo el tabaco de Maharastra. Pero aun siguen fumando. Como Shiva; que bebió todo el veneno, porque Él es el dador de vida. 

Cualquier cosa que ellos han trabajado tanto..., tan sinceramente, con completa concentración. A Mí me veis trabajar así, pero ellos también lo hicieron igual. Así es que, no deis las cosas por sentado. Os he dicho a muchos que escribierais cada día: ¿qué he hecho hoy por Sahaja Yoga? Para mí mismo haré todo; pintaré mi casa, mi cocina, todo, tendré un buen sari y blusa preparado, para mí mismo, pero Yo: ¿qué he hecho por Sahaja Yoga? ¿Cuántos regalos he dado a otros? ¿Cuántas cartas he escrito a otros? ¿Qué experiencias he escrito? Y por encima de todo: ¿Cuánto tiempo he sentido el Amor de mi Madre en mi corazón? Pero os diré la causa por la que en occidente este es un gran problema. 

Lo he descubierto ahora, igual que descubrí Sahaja Yoga. He descubierto el secreto, que os voy a revelar hoy. Este es también la Shakti de penetración, por la cual uno puede descubrir cómo los demonios trabajan en vuestra mente, cómo prosperan. Creo que se lo he dicho a alguna gente, pero hoy os lo voy a decir a todos. Cuando somos niños, hasta la edad de cinco años, estamos orientados hacia el ego en el sentido de que simplemente cuidamos de nosotros mismos. Dais diez juguetes a diez niños y ellos cogerán sus juguetes y jugarán entre ellos, no hablarán con nadie, sólo querrán jugar, no molestarán a nadie. Esto es vivir en paralelo. No molestarán, y si molestan; pueden morder, o hacer alguna otra tontería. Puede ser debido a algún bhoot en ellos. Cuando son niños. 

Pero cuando tienen cinco años de edad: supongamos que preguntáis a algún niño de aquí; ¿qué estás viendo? Él dirá, "veo un tigre, y esas flores, y eso, y eso". Pero si le hacéis quedarse allí y le decís, suponiendo que alguien estuviera en aquel otro lado: ¿qué verá él? Aún dirá, "veo un tigre y esas flores, y eso, y eso". Intentadlo. Porque él no puede ver el punto de vista de otra persona. Está simplemente ocupado con su ego. He descubierto ahora que en toda la cultura de occidente, quizás formalmente no era así, los padres tenían gran atención y responsabilidad hacia sus hijos. Que los niños se comportasen bien, que estuviesen bien, y que no se pelearan entre ellos, quiero decir, pueden pelearse un poco, pero en el dormitorio. Porque Yo no he visto películas, cuando era joven, donde el marido y la mujer estén continuamente peleándose o divorciándose. 

Sin ningún entendimiento entre marido y mujer. Pero cuando es otra mujer, u otro hombre, sus caras estarán así. Si veis en la calle que dos personas van con la cara así; sabéis que esos dos no son marido y mujer. Estos son los tiempos modernos. Estos son los tiempos modernos. Y en occidente es peor. Y, ¿Qué sucede? Que los padres, no han crecido, no han madurado, no tienen el sentido de la responsabilidad de que tienen niños, de cómo comportarse con el marido. Especialmente aquí, las mujeres son extremadamente dominantes. Estúpidas, debo decir. 

No saben nada de cocinar, no saben nada de nada, sólo pueden llevar a las niñas, sentarse en el banco y escribir alguna cosa, son extremadamente estúpidas, no saben cómo manejar a su marido ni cómo manejar a sus hijos. No fueran enseñadas. Sus madres no les dieron atención, ninguna disciplina en absoluto, así es que este niño egoísta, es aún egoísta. Sin amor ni afecto. Mi madre era una mujer muy estricta, extremadamente estricta, pero también extremadamente amorosa. Extremadamente amorosa y extremadamente estricta, igual que Jagadamba. Nos enseñaba cómo cocinar, incluso como sujetar el cazo; esa no es la forma, hazlo de esta otra manera, ¿Por qué estáis así?, ¿Dónde está vuestra atención? Y no había que preguntar nada. Toda esa disciplina que vino a nosotros en nuestra infancia nos está ayudando hoy. Y era extremadamente amorosa, era por nuestro bien, todo lo que hacían era por nuestro bien. 

Pero Yo siento, especialmente en Suiza, que las madres no están educadas y son extremadamente celosas de sus hijas. Mi madre tenía educación, pero su madre no. Pero era una mujer sabia. Tenía sentido de la responsabilidad. Sabía que ella era madre y que tenía que comportarse, que no podía ser infantil y estúpida. Así es que a causa de que no se les dio este amor, estas mujeres están aún orientadas al ego. Son aún bebés, no han crecido. Aún no pueden ver el punto de vista de otra persona y se vuelven extremadamente obstinadas. ¡No, esto es la verdad! Así es que vamos a afrontarnos a nosotros mismos. 

Hoy tenéis el puja de la Adi Shakti, que es muy peligroso porque es como un espejo donde tenéis que veros a vosotros mismos, que encararos a vosotros mismos. Dominar a vuestros maridos es una estupidez sin sentido. Porque no sabéis cómo manejarlos. Yo diría que las mujeres indias dominan muy bien a sus maridos. Los esposos no pueden hacer nada sin su esposa, no pueden hacer nada sin su esposa, no saben cómo guardar sus cosas, como hacer té, no saben cómo cocer un huevo, no saben nada, ni siquiera saben cómo cerrar la casa cómo abrir un armario, o extender la cama, no saben ninguna de las cosas prácticas. Por ejemplo yo diría que mi esposo siempre viene y me pregunta, ¿está bien la corbata? Desde hace tiempo, ahora sabe que soy la Adi Shakti, pero antes también vendrá y me dirá, ¿esta bien así? No, no esta bien, de acuerdo, y se cambiará. Pero debido a que vosotros no habéis crecido no habéis madurado, no sabéis como manejar a vuestros maridos, e intentáis dominarlos, y los niños aprenden de vosotros, y también intentan dominaros. Debéis entender que aparentemente, la autoridad viene de arriba. 

Como Yo, que siempre diría, Yo no soy Dios, Sadashiva es Dios. Gregorie se sorprendió mucho cuando dije esto la primera vez. Pero Yo también soy Dios. Sin Mí, ¿qué es Él? Yo soy su Poder. Él es sin Poder. Pero dejarle ser Dios, muy bien, porque si tenéis que culpar a alguien, culparle a Él. Él es Dios, pero Yo tengo que trabajar duro para mantenerle contento, si no, como sabéis, Él no se preocupa por nadie, Él simplemente destruye, eso es todo lo que sabe. Él os destruirá. A cualquiera que intente hacer trucos conmigo. 

Os destruirá tan malamente que durante muchas vidas no os podréis convertir en seres humano. Él es así. Una persona terrible, es aquel que ha hecho todas estas cosas, ya sabéis. Así, que tenemos que crecer, tenemos que crecer como mujeres sabias, como mujeres que son como la Madre Tierra, como os dije. Y cuando me preguntáis, Madre, Tu trabajas tan duro y pareces tan fresca. Porque Yo disfruto de ello, es como música para Mí. Trabajar es música para Mí, cocinar es música para Mí, todo es música para Mí. ¿Os cansáis de la música? Al contrario; os sentís frescos. Y cuando mato demonios, como habéis visto allí, me ilumino más, más luz viene a Mí. 

Es lo contrario.. Hoy os tengo que hacer entender que por favor, tened completa introspección, buscad en vuestra alma, ¿qué está mal en nosotros? No miméis vuestro ego porque el ego os hace idiotas, esto debéis haberlo visto. Tenemos alguna gente en Sahaja Yoga que son así, idiotas, sólo piensan en sí mismos, todos los conocemos. Tenemos que tener bufones en el circo, pero también tenemos que tener leones y tigres. Lo que impresiona a la gente son los leones y los tigres, no los bufones. Así pues, es importante hacer introspección y ver por nosotros mismos; ¿cuánto hemos hecho por Sahaja Yoga? Por supuesto que tengo que felicitaros por una cosa, porque como sabéis Yo soy así, no he hecho nada para ser así, soy simplemente así. Yo soy, tengo el Poder. Yo tengo el Poder porque soy el Poder. ¿Por qué habría de sentirme entusiasmada por ello? 

No me siento de esa forma en absoluto, pero si Yo no uso mis Poderes entonces me vuelvo como un ser humano. ¿Por qué soy Yo la Diosa? Porque uso cada parte de mis Poderes, y si vosotros no usáis vuestros poderes, por cualquier tontería, por algún miedo, por cualquier tipo de tentación o restricción, por cualquier cosa, si no vais todos fuera, a usar vuestros poderes de amor; no podréis ascender. Y si veis todo claramente; todo el Poder de vuestra Madre es de Amor, todo lo que hace es por Amor a su Creación. Y la introspección empieza, pero no debería ser tarde. He estado diciendo desde hace mucho tiempo cómo estaban extenuando a la Madre Tierra, haciendo tantas cosas, debéis haberme oído decirlo estos últimos dieciocho años o así, y hoy el problema ecológico está como un rakshasa, ante nosotros. Y ahora: ¿Qué vamos a hacer con esto? Encararlo, y automáticamente tenéis que encararos, encarar vuestra destrucción. Introspección. Si no lo hacéis ahora, lo afrontareis en el momento en que será demasiado tarde. 

Así es que no estéis satisfechos con vosotros mismos. Solamente conque ahora sois sahaja yoguis. Habéis venido a mi Puja, por supuesto, como si cayeseis al mar. El mar tiene el poder de absorberos pero también tiene el poder de expulsaros a la orilla, actúa de las dos formas. Entonces; ¿por qué no profundizáis más en Sahaja Yoga? También hay excusas como: "no tengo tiempo", "estoy muy ocupado", "estoy trabajando en la oficina", "estoy haciendo esto". Entonces no sois un sahaja yogui. Todo vuestro tiempo es para Sahaja Yoga y si es así, Sahaja Yoga os da tiempo para todo lo demás. Conozco gente que, sorprendentemente, me la encuentro en los Pujas, a veces en Vancouver, a veces en San Diego, a veces aquí, y les pregunto, "¿Cómo estás aquí y tu negocio? ", Y me dicen, "Es el negocio el que nos ha traído aquí", exactamente este día. 

Cuando este Poder es tan grande, tenéis que daros cuenta de ello, de lo grande que es, y entonces le dejáis todo a este Poder que hace funcionar todo para vosotros. Hoy estamos hablando de Shakti, del Poder de la Diosa, que tiene que ser desvelado mucho más. Es demasiado complejo. Es muy equilibrado y extremadamente eficiente. Pero, cualquier trabajo que estos Poderes han hecho dentro de vosotros intentad respetarlo. Por favor, intentad asimilarlo y permitid que crezca vuestro Ser. No digáis "ahora estoy casado", o "estoy embarazada", "tengo niños" o "tengo trabajo", nada. Todo se hace perfecto tan pronto como os perfeccionéis vosotros, todo esta relacionado con vuestro perfeccionamiento. Entonces ya no me preguntáis; "¿Qué trabajo debo hacer, Madre? ¿Qué tengo que conseguir?" 

Nada, vosotros veis vuestro camino y todo funciona. Todos los demonios fueron matados y de nuevo todos han vuelto a sus asientos. Lo peor es que han entrado en la cabeza de los buscadores. Porque han venido como gurus, han venido como Iglesia Católica y Protestante y todo tipo de templos del fundamentalismo y todo eso. Si los veis, parecen rakshasas. Y cuando os influencian entran en vuestras cabezas. Pero después de venir a Sahaja Yoga, incluso se limpia esto de vuestras cabezas y podéis salir de esto y llegar a estar bien, fuera de ello. Pero después, ¿Qué hacer con esto? Con hacer todo este trabajo, la limpieza, el dar gozo, y todo lo demás, ¿Qué hacer? ¡Tenéis que dárselo a otros! 

Esta es vuestra responsabilidad. Antes de nada, vuestro carácter, vuestro comportamiento, vuestras relaciones, deberían ser tan puras, que por sí mismas emitieran luz. Como cuando tenéis un cristal muy limpio, la luz puede pasar. Y siendo la Kundalini el deseo puro deberíais tener un deseo ferviente, extremadamente vivaz, podríamos llamarlo un absoluto, absorbente deseo que nos empujara hacia; ¿A quién puedo dar vibraciones? ¿A quién le puedo dar la Realización? Dádsela a los árboles, a los perros, a todo el mundo. Y si encontráis seres humanos, dádsela también. Bastante difícil. Esto tiene que hacerse. Y para cualquier cosa que hagáis: mantened vuestra atención en la conexión. 

Pero aquí hacéis Sahaja Yoga y allí perdéis vuestra conexión, entonces: ¿Qué estáis dando?, ¿Sahaja Yoga o qué? ¿Estáis dando oscuridad? Estáis dando ignorancia. Estáis dando locura. Así, debéis mantener siempre vuestra conexión a este tremendo Poder, Shakti, y agradarla. Como el protocolo. Es muy importante, porque si observáis todo esto, todos ellos tienen el sentido del protocolo, porque están fijados. Vosotros también, deberíais fijar vuestro protocolo apropiadamente. Para Mí, como ser humano, es muy difícil y embarazoso deciros cuál debe ser el protocolo con la Diosa. Pero tengo que decíroslo, porque no quiero que sufráis ningún daño. 

Se debería cumplir el protocolo. Y se debería entender. Por supuesto, esto es ahora mucho mejor. La primera vez que hicieron mi Puja en Delhi, me hicieron el Arti con un plato de plástico. Guardaron el kumkum en cajas de plástico. Yo estaba tan preocupada por esas personas, que todo mi cuerpo se encogió. Les dije; no hagáis nada. Si veis mi fotografía de ese Puja, parezco muy diferente. Me sorprendió tanto que no supieran cómo hacerlo. Ahora, por favor, prestad atención a vuestro protocolo. 

Por ejemplo la gente va andando en pijama por la mañana. Esto no es apropiado. Vestiros apropiadamente. No sabéis lo que es la Adi Shakti. ¿O lo sabéis? Si lo sabéis, os vais a enfrentar a la Adi Shakti. Tenemos que entender el protocolo. En India, afortunadamente, la gente tiene más sentido para esto, aunque a veces también fallan. El protocolo es muy importante, porque se pondrán furiosos si no lo mantenéis. Esto es extremadamente importante. 

Por eso Cristo dijo: "Toleraré cualquier cosa en contra mía, pero nada en contra del Espíritu Santo". Él también dijo: "Estad atentos a las almas murmuradoras". Porque si murmuráis algo a mi espalda, Yo oigo todo. Ellos me informan todo el tiempo. Si hacéis algo a mi espalda, Yo sé qué está pasando. Yo puedo dejarlo pasar, pero después actúa. Es por vuestro beneficio, por vuestro bien. Por vuestro ascenso, por el cual habéis luchado durante eras. Debéis respetaros a vosotros mismos. Sois buscadores y ahora habéis encontrado la verdad. 

Haced una corona con esto y ponedla sobre vuestra cabeza. Sois como señores. Hasta que sepáis qué Poderes tenéis, cómo los habéis obtenido, y lo recordéis, y esta verdad se convierta en una parte de vosotros; vuestro ascenso será difícil. No estaréis ni aquí, ni allá. Estaréis como un péndulo colgando en el aire; de aquí para allá, de derecha a izquierda, de izquierda a derecha. Una sahaja yoguini debería sentir vergüenza de estar así; de derecha a izquierda, de izquierda derecha. ¿Cómo podéis ser tan vulnerables? No habéis crecido. Tenéis que ser como la roca de Gibraltar. ¿Cómo podéis coger bloqueos? 

De acuerdo, si pensáis que alguien es muy negativo, no vayáis cerca de él. Pero no podéis volveros unas muñequitas delicadas. Mis niños son Viras, caballeros. Tienen que serlo. Sois mis niños. Ya no sois más cristianos, hindúes o musulmanes, ya no sois más esa gente horrible, demoníaca, sino que sois mis niños y tenéis que ser valerosos, tenéis que ser justos, tenéis que ser buenos, compasivos y dinámicos. Esto es lo mínimo. Espero que después de este Puja nos sentemos, meditemos, y hagamos introspección. Descubrid: ¿Por qué hago esto? ¿Cuál es el problema? 

Ayer vi que alguna gente se estaba durmiendo. Esto es por el Nabhi izquierdo. Corregir vuestro Nabhi izquierdo. Pero si realmente estáis conectados con este Poder Divino, podéis manteneros despiertos durante tres días y tres noches. No estaréis cansados. Os ha sucedido algunas veces. Pero la atención debería estar en este Poder. La atención debería estar en la conexión que tenemos con este Poder. Sólo de este modo, si no, naturalmente estaréis exhaustos. Todo es tan lógico. 

Muy lógico. Gracias a Dios, gracias a vosotros mismos, gracias a vuestra buena suerte, que unos pocos habéis tenido la fortuna de lograr esta conexión y que estáis absorbiendo este Poder en vosotros tan fácilmente. ¿Por qué os comportáis como esa gente ordinaria y estúpida, con sus estúpidas preocupaciones? Os sorprendería que la Diosa, en sus encarnaciones anteriores, nunca habló tanto como Yo he hablado. Eran suficientes una o dos palabras. Diría: "¡Oh! ", Y mataría este demonio, "¡Ah! ", Y acabaría con aquel otro. Simplemente hacía todo así; "¡Ah!, ¡Oh!, ¡Eh!...." Pero nunca dieron la realización a nadie. 

Ninguna de las encarnaciones. Dijeron "No, no, no... yo no", "yo no". "No voy a hacerlo". Deben haber visto lo estúpidos que son los seres humanos. "¡Oh Dios!, Nada, estoy bien", "Puedo ir a la jungla durante catorce años, puedo trabajar como cochero para Arjuna, puedo ser crucificado, o puedo tomar veneno, pero no me pidas que trate con seres humanos. No, no..." Es mejor ir a un zoológico que eso. Por eso no lo hizo ninguno de ellos, e incluso ninguno de ellos, ni siquiera habló del tema. Pensando que si hablaban les dirían "¿Por qué no nos das la realización?". Ninguno de ellos. Esta es la Compasión, el Amor y la Confianza de la Adi Shakti; y vosotros también deberíais de tener confianza. 

Pero Yo no sólo os he dado la Realización, sino que os he dado el Poder para dársela a otros. Ninguna de estas encarnaciones hizo lo que vosotros hacéis hoy. Con todos Sus Poderes no lo hicieron. Pero vosotros podéis hacerlo. A pesar del hecho de que los instrumentos no son tan fuertes. No son tan divinos. Pero todavía tenemos que resurgir y realizar en nuestras propias vidas, las prioridades que tenemos. Para los Dioses su prioridad era sólo el trabajo Divino. Nada más. Ninguno tuvo un empleo, ninguno. 

Ninguno fue a la universidad. Ninguno estudió. Lo único que hicieron fue el trabajo de Dios. Así pues, vosotros haced todo como un trabajo de Dios, y así es como la Energía fluirá en vosotros. Cuando empezáis a hacer el trabajo de Dios todo lo que hacéis se vuelve el trabajo de Dios. En el sentido de que vosotros decidís que vais a hacer el trabajo de Dios y Él toma el mando y hace todas las otras cosas. Vosotros sólo hacéis el trabajo de Dios. Él toma el mando. Espero que lo entendáis. Intentadlo. 

Intentadlo. Tened confianza. Gracias a Dios también, que hay alguien como vuestra Madre que puede deciros, qué está mal en vosotros. Gracias a Dios. Vuestras propias madres no os dirían nada, porque tienen tanto miedo de vosotros. Así pues no digáis; "Madre cuando me dices algo mi corazón se bloquea". Si es así; ¿Qué podemos hacer? Si entendéis que lo hago para que mejoréis, por amor, por preocupación. Entonces haréis que funcione. No creo que se trate de una comprensión mental sino de una comprensión de un nivel mas elevado, en donde se vuelve una parte de vuestra conciencia. 

¿Cómo puede ser un error? Todo ha de ser bueno para vosotros Por último, es que debéis entender que Yo trabajo en los siete chakras, que son cuidados a nivel colectivo por Mí, mi Virata. La cualidad de Viratangana es tal, que Ella crea la Conciencia Universal en vuestro interior. La Colectividad. Debéis daros cuenta de que en los tiempos modernos estamos en un camino espiritual que sólo es de forma colectiva. Esto es así porque hemos llegado al estado del Sahasrara. Y aquí sólo podemos tener un trabajo colectivo. No hay otra forma. Tenemos que entender absolutamente esto. Quienquiera que intente dañar la Colectividad comportándose mal o de cualquier manera, será expulsado, sin duda, pero además caerá en malas manos. 

La Colectividad es el trabajo de la Adi Shakti, porque en el Sahasrara, en el Sahasrara, en el Sahasrara gobierna el Virata. Y el Poder del Virata es Viratangana. Aquel que hace la colectividad. Es el punto más importante que debéis entender. Si no podéis ser colectivos, por cualquier causa; por celos, por sentimiento de inferioridad, por cualquier cosa que viene por detrás, reptando como un gusano, debéis saber que hay algo mal en vosotros, no en el colectivo. No critiquéis a la Colectividad. Hasta que Yo lo descubra y lo corrija. Manteneos sabiamente en la colectividad. Intentad mantener la colectividad unida. Intentad ayudar a la gente a ser colectivos y a gozar juntos. 

No os critiquéis unos a otros. Criticaos sólo a vosotros mismos, si tenéis el hábito de criticar. Es mejor criticaros a vosotros mismos, ya que es sólo un hábito. He visto que la gente de occidente reaccionan por todo. Ven esta alfombra y dicen; "¡Oh!, No me gusta". Pero no es vuestra, ni habéis pagado por ella, qué os importa. "No, no me gusta". Pero no es vuestra. ¿Cuál es el problema? Está puesta aquí. 

¿Por qué os preocupa? "No me gusta esa persona". "No me gusta esa ropa". ¿Quién eres tú? "No me gusta". Esto no está permitido en Sahaya Yoga. "No me gusta". Hay una forma de decir las cosas, aunque no hay necesidad de decir nada en absoluto. Todo este tipo de pomposidad y protagonismo está en contra de la Colectividad. También hay otro tipo de gente estúpida que siempre está ahí para hacerme fotografías. 

Se les dice, no vayáis tan adelante, y dirán: "No quiero ir, no lo hago...". Algunos de ellos están confirmados, certificados. Estúpidos, idiotas, no pueden mejorar. Os he dicho que no hagáis de ellos vuestros ideales, que no sigáis su imagen. Así llegamos a la conclusión, de que el trabajo de la Adi Shakti, es el más importante de toda la Creación. Matar a todos los demonios ya pasó. ¿Qué fue eso? Ya está hecho. El trabajo de Saraswati se hizo. Ella creó los Universos, ¿y qué? 

Mahalaxmi hizo su trabajo y os llevó al nivel humano, ¿y qué? El clímax es ahora que habéis obtenido vuestra realización, que habéis obtenido este Poder especial. Ahora habéis entrado en el Reino de Dios. Así es que ahora comportaros. También debéis tener esa dignidad de saber que ahora habéis entrado en el Reino de Dios. Vi esto una vez que fui a ver al presidente de India. Pero para Mí era sólo otro ser humano, nunca vino a mi cabeza que él era el presidente y todo eso. Estábamos subiendo, y las personas que subían conmigo se volvieron muy conscientes de esto y Yo pensé: ¿Qué le pasa a esta gente? ¿Han visto a algún fantasma o algo así? Simplemente cuando subíamos las escaleras. 

También había allí algunos guardas que estaban riéndose de todo esto. Pero esta gente se volvió muy consciente. Ahora vosotros estáis entrando en el Reino de Dios, ¿Qué conscientes deberíais ser de vuestro comportamiento? ¿Cómo deberíais ser? ¿Cómo os deberíais comportar? Sentid la exclusividad de vuestra personalidad, que ya estáis en el Reino de Dios. Simplemente sentid esto. Si podéis, sentís esto, sabréis qué lugar prioritario habéis obtenido y con qué dignidad deberíais comportaros. Qué bellamente deberíais comportaros. Con qué limpieza, orden y dulzura deberíais comportaros. 

¿Cuántas Mariadas deberíais conocer? Todas. Y cuando os deis cuenta de que sois los ciudadanos más elevados, del Reino de Dios, tenéis que probar que os habéis dado cuenta de ello. Que sentís de esa manera. Deberíais sentiros extremadamente felices y gozosos. Ayer, a la mínima cosa, todo el mundo se reía. Como toda esa gente vulgar. Eso no es Sahaja Yoga. Si hay una buena broma os podéis reír, pero vosotros os reís simplemente hablando. Estaba sorprendida, sois sahaja yoguis. 

Pensad en los santos haciendo esto. ¿Lo harían? Sois santos, sois munindras. Con vuestra meditación os habéis convertido en reyes. ¿Cómo os podéis comportar de una forma indigna? Intentad asumir vuestra posición. Intentad sentirla. Ayer, cuando empezó la última canción, penetró en muchas almas, en muchos corazones. Este gozo único, que llamamos Nirananda. Yo lo sentí ayer, pero mantenedlo. 

Hay que mantenerlo a salvo en vuestros Kumbas. Es la Kundalini, y Ella es la que se ha elevado, por eso hoy mi idea era no sólo adorar vuestro Kumba, donde reside vuestra Kundalini, sino que la Kumba se convirtiera en un florero. Así ha sucedido. Y como alguna gente dijo, "Madre, estos floreros se convierten en lámparas de mesa". Yo dije: "Vosotros lo habéis dicho". Así que Kumba se convierte en flores y las flores se convierten en luz. Y la luz en fragancia. Espero que entendáis mi visión y estéis a mi lado. Que lleguemos a eso. Yo dependo completamente de vosotros para mi visión. 

Tenéis que cambiar este mundo en un lugar bello. Para esto no se necesita mucho sacrificio. Ya estáis situados, no tenéis que hacer mucho. Lo único es mantener vuestra atención en la Fuente del Poder. Que Dios os bendiga. Gracias, pero debéis prometerlo. Muchas gracias. Todos deberíais escribir sobre algunos milagros y cómo funcionan las cosas. Como cuando fuimos a París y queríais comprar saris para las mujeres de aquí y en ningún lugar encontrábamos de 45 pulgadas, o eran de 36 pulgadas o de 58. Entonces cuando íbamos en el coche, de repente dije: "¡Parad!". 

Me dijeron, "¿Por qué, Madre?" "En la calle hay alguien vendiendo los saris". Y los conseguimos. Otra cosa, como visteis, ya en Ganapatipule... en el Ganesha Puja, teníamos unos jarrones para vuestros regalos. Siempre dabais regalos muy caros, sin valor artístico, malgastando tanto dinero, incluso para los Pujas nacionales no encontrabais nada. Y conseguimos esto de la misma forma. Cuando veníamos del aeropuerto, simplemente dije: "¡Hay algo aquí!". Ellos dijeron: "Madre es sólo una tienda". Yo les dije, "bueno vamos a ver". Dimos la vuelta y estaban todas estas cosas. 

Lo mismo sucedió en América. Yo dije, "China tiene problemas, vamos a comprar algo chino". Fueron a las tiendas chinas y todo era muy caro. Muy caro. Volví la esquina y les dije, "Dejadme ir allí a ver". Entré en una pequeña calle y había una tienda que vendía todo muy barato, nuevamente un 40% menos. A veces tiene que ver con el 40%. Y por casualidad. Cien metros más allá vendían todo cinco o seis veces más caro. ¿Y por qué esta tienda era así de barata? 

Ahora, intentadlo también vosotros. Pero el deseo debe ser puro, la comprensión debe ser pura. Yo sólo pensé que los sahaja yoguis gastan tanto dinero, y compran cosas sin ningún valor. Y todos estos regalos que me dais, en realidad Yo os he pedido muchas veces que pararais de hacerlo. Ahora, de los individuales hemos pasado al nivel de los nacionales. Pero creo que incluso deberíamos dejar los nacionales y tener sólo uno internacional. Podemos hacerlo el próximo año, si os parece bien. De cualquier forma, lo que me deis, no voy a venderlo ni voy a dárselo a nadie. Debe ser sahaja, debemos mantenerlo para que los descendientes vean lo que me habéis regalado. Este es el valor de todo esto, no el valor de cuánto habéis gastado. 

No hay ninguna necesidad de que me deis regalos individualmente. Ya sé que me amáis. También he pedido a los líderes que no pidan para el regalo nacional, que no gasten dinero, pero no sé si ellos no están de acuerdo. Si están de acuerdo podemos parar esto. Y tener sólo el regalo internacional. Esto también podemos dejarlo. Porque como sabéis Yo no necesito nada. Esto funciona, funciona. Como cuando os dije que me dierais marfil. Era muy caro y de nuevo encontramos un lugar muy barato. 

Y una vez que me disteis el marfil, leí en un periódico que el marfil costaba 500 dólares por kilo y ahora en América cuesta 3 dólares por kilo. ¿Es verdad o no? La idea también es ayudar más a la artesanía y al arte. He dicho tantas veces que con un trocito de arcilla podéis hacer algo muy bello con mucho valor. ¿Por qué agotar a la Madre Tierra? ¿Por qué no tener pocas cosas pero artísticas en lugar de tantas otras cosas? Pero si vais a las tiendas no encontráis nada. No encontráis seda, no encontráis esto ni aquello. Es tan difícil encontrar algo natural. Porque la gente sólo está haciendo cosas que no son naturales. 

Con cualquier cosa, deberíais crear belleza. Si empezáis a crear belleza, intentaréis preservarla y usarla, valorándola en vez de tener miles de cosas. Todo desechable. Después de algún tiempo también tendremos seres humanos que son desechables. Tendréis que desecharlos. ¿Cómo van a vivir en esta Tierra? Tenéis que entender que tenemos que vivir en esta Tierra, con sus limitaciones. Os he dicho muchas veces que prefirierais cosas artísticas. Tomad cosas hechas a mano. No vayáis demasiado hacia otras cosas. 

Al menos si tenéis que ir hacia algo artificial, tener algo artificial pero artístico. Hoy deberíamos con gran deseo rezar en todo el mundo por la preservación de la Madre Tierra. Por eso he hablado así. Debemos rezar para que todos desarrollemos el arte, para nosotros y para regalarlo a los demás. También usar cosas artísticas, hechas de arte. Podemos tener pocas cosas pero artísticas. Que expresen arte. No cosas de mal gusto. En toda Francia, vi que el plástico estaba en todas las cosas. En el algodón ,en la seda, en la lana. 

Puede entrar en todas las cosas, excepto en el cerebro de los seres humanos. Es horrible. Cualquier cosa que tengáis, intentar que sean cosas artísticas. No cosas planas, horribles, chabacanas. ¿De acuerdo? Esto es lo que tenemos para hoy. Hoy también tenéis que pedirme durante el Puja, "Por favor Madre, salva esta Tierra". "Da sabiduría a la gente para que se comporte bien y que sean conscientes". Todos los sahaja yoguis deberían ser conscientes acerca de cuanta energía gastamos, cuanta electricidad, teléfono, agua o cualquier otra cosa. Tenemos que ser frugales con esto. 

Si no tomamos la responsabilidad de esto entonces no penetrará en ningún otro lugar. Vosotros tenéis que hacerlo. Vosotros tenéis que hacerlo en vuestra vida diaria. Es una parte de vuestra vida el que intentéis salvar la energía de esta Madre Tierra. Es muy importante. Hoy también es un día en el que hay algunas oraciones especiales en algunas iglesias. Creo que es un buen día, porque deben haber pensado que hoy es el día de la Diosa, por eso hay que pedir. Que Dios os bendiga. Que vengan 14 mujeres que aún no me han hecho el puja.  