23 září 1990
Navaratri Púdža
Geneva (Switzerland)
Navarátri púdža: Božstva vás sledují, 23/09/1990, (nekontrolováno), Arzier, Švýcarsko

Podle kalendáře je tento rok deset dní Navaratri, ne devět.

Je devět dní, nocí, kdy musela Bohyně bojovat s démony a ochránit své děti před účinky negativit. Na jedné straně byla oceánem lásky a milosrdenství a na druhé straně je chránila jako tygřice. Protože to byly časy, kdy nikdo nemohl meditovat, nikdo nemohl používat Boží jméno, nikdo nemohl ani pomyslet na seberealizaci. Ale vy, kteří zde dnes sedíte, jste tam také v těch dnech byli a všichni jste byli zachráněni pro dnešek, pro tento den, takže můžete získat svoji seberealizaci. V oněch dnech Bohyně nebyla ve formě Mája Svarúpi. Byla ve své skutečné podobě a to vzbudilo ohromnou posvátnou úctu dokonce i mezi učedníky. Takže otázka dát jim seberealizaci nebyla na pořadu dne. Nejprve museli být zachráněni. Takže tak, jako si matka musí ponechat dítě po devět měsíců ve svém lůně, těchto devět měsíců, nebo můžeme říct devět jug, devět období, jste vy všichni byli náležitě chráněni a desátý měsíc se rodíte. Zrození je také vždy sedm dní po devátém měsíci.

Takže jsme museli nějakou dobu počkat, než se to vyvine. Dnešní desátý den Navaratri je ve skutečnosti určen k oslavě Ádi Šakti. Takže dnes budeme opravdu uctívat Ádi Šakti. Na jedné straně je Ádi Šakti Mahakálí, na druhé straně je Mahasarasvatí, ve středu je Mahálakšmí a je také Ambou, Tou, která je Kundaliní. Ale je také za tím. Je Parašakti; je mimo všechny síly. Protože Ona je původcem síly. Takže musí být za tím vším. Takže dnes, když Ji uctíváme, musíme Ji uctívat ve všech těchto formách. Takže chápete, že tento desátý den, kdy máme Navaratri poprvé v kalendáři, je proto, že dnešek je dnem, kdy budeme uctívat Ádi Šakti.

Ádi Šakti nikdy dřív nebyla uctívána, nikdy. Ale tentokrát, když jsem jela do Kalkaty, řekla jsem jim: "Raději dnes uctěte Ádi Šakti." Byli překvapeni: "Proč dnes Matka žádá, abychom uctili Ádi Šakti?" Takže když jsem se vrátila do Púny, řekli Mi, že Ádi Šakti, jak víte, je Saptašringi, což znamená - Ta, která má sedm vrcholů. Spočívá na sedmi vrcholech, což znamená v Sahasráře, na sedmi čakrách. Vládne všem sedmi čakrám. Řekli Mi, že když jsme měli v Kalkatě púdžu, že tentýž čas je obdobím, kdy ti, kteří následují Saptašringi, což je velice málo lidí, ti všichni tam přijdou a přijdou tam nejprve lidé z matčiny strany. Takže mateřská strana Ádi Šakti se týká Vaišnavitů, těch, kteří následují Višnua. Takže tam přijdou jako první, aby Ji uctili, a pak přijde tchánova strana, což je Šivova strana, Sadášivova strana. Je to přesně ten čas, kdy jsme měli púdžu.

Společně mají k uctívání tyto dvě skupiny. Takže nyní mezi sebou máme dva druhy lidí. Jedni, můžeme říct, jsou ti, kteří uctívají Brahmadévu na pravé straně, a lidé, kteří uctívají Šivu na levé straně. Obě strany se musí setkat a to v místě, kde musíme uctívat naprosto sjednocenou podobu všech těchto sil, které se uvnitř nás projevují. Když říkají, že existuje pouze jeden Bůh, v pořádku, existuje jeden Bůh. Ale jeden Bůh má hlavu, játra, žaludek, nos. Má všechno, právě tak, jako lidské bytosti, protože se říká, že Bůh vytvořil lidské bytosti k obrazu svému. Takže má v těle různé části a musí je spravovat. A pro tyto různé části musí mít božstva a božstva musí být pochopena. A dokud neporozumíte a neuctíváte božstva, nemůžete je probudit uvnitř sebe.

Ale ona všechna jsou nedílnou součástí Ádi Šakti. Jsou pod naprostou kontrolou Ádi Šakti. Včera jste slyšeli o síle Ádi Šakti. Je jako želva, která schová celé své tělo do krunýře, stejným způsobem jsem stáhla všechny tyto síly do sebe. Chci říct, že je neobjevíte snadno. Neodhalíte je snadno - kromě těchto moderních fotoaparátů, které se nás snaží doběhnout. Ukazují vám Moji formu a podobu, protože ve vibracích je světlo, a když jsou vibrace vyzařovány, začnete je vidět ve fotoaparátech, dokonce i když nejsou příliš citlivé, ale lidé je nějak dokážou zachytit. Existuje tolik zázračných fotografií. Určitě jste viděli fotografii, kde za Mnou stál sám Šrí Ganéša. Zrovna teď tady nikoho stát nevidíte.

Ale nevíte, co se děje. A toto člověk musí pochopit. Že jsme vstoupili do nového království Boží magie. A Jeho magie pracuje mnoha způsoby. Někdy se samozřejmě taky ztratíte. Jste oslabeni kvůli svým předešlým problémům. Jste sváděni. Někdy jste také ovládáni negativními silami a upadáte. A to je velice smutná věc, která by se neměla stát žádnému sahadžajogínovi. Protože možná neznáte svoji minulost a nevíte, jak jste usilovali, jak jste těžce pracovali, abyste vzestoupili na tuto úroveň.

A poté, co přijdete na tuto úroveň, pokud se nesnažíte jít výš, tak buďto se přilepíte na jedno místo, nebo můžete být svrženi dolů. Takže byste měli vědět, že jste sahadžajogíni, nejste manželkou, manželem, matkou, otcem, jste sahadžajogínem. Tak, jako Já jsem Ádi Šakti, stejně tak jste sahadžajogíni. Takže nyní je Mojí hlavní prací dát realizaci ostatním. A protože jsou všechny Moje vztahy správně ustanoveny, nemusím si dělat starosti o žádné božstvo, žádného Boha, všichni všechno řeší velice efektivně. Popis Bohyně, který jste včera četli, že Její ruce střílejí všechny šípy takovou rychlostí, že to vypadá, jakoby tancovala. Je to tak, bezpochyby, ale vy to nevidíte. Nevidíte, že každý Můj vlas je jako šíp. A pracuje tak fantasticky. Ale pro vás tu jen klidně sedím, tak jako sedíte vy.

Ale tak to není. Je to něco mnohem víc. Když ukazují lva nebo tygra jako Můj povoz - vahana, musíte pochopit, že ukazují, že oni skutečně jsou. Skutečně jsou. Není to tak, že by byli symbolicky, jsou ve skutečnosti. Takže důstojnost tygra - mnohokrát jsem vám řekla, jak je důstojný. Je tak důstojný, protože na něm sedím. Musí-li jíst maso, zabije jednu krávu nebo něco podobného, pojí maso a nechá ostatním. Je tak důstojný. A jí jednou za měsíc.

Takže dokonce sehnat vahanu takovéhoto druhu - musela být vyvinuta ze stavu améby do tohoto stavu. Jinak by tu nebyla. Stejným způsobem jste vyvinuti a i ve vás jsou všechny tyto vahany. A vypracovávají velice rychle všechno, co chcete. Něco si přejete; budete překvapeni, okamžitě objevíte, že se to vypracovává. O něco požádáte - okamžitě se to vypracovává. Ale musí tu být naprostá odevzdanost Sahadža józe. Když říkám Sahadža jóga, víte, že je to jóga vaší pozornosti na Mých chodidlech. Je to tohle. Ale jestliže se stále pohybujete se svým egem a jestliže stále přemýšlíte směrem: "My jsme něco a můžeme začít naši vlastní Sahadža jógu, můžeme to vypracovat takto nebo jinak," nebo "moje žena je taková, moje dítě je takové, můj manžel je takový" - musíte všechny tyto problémy odložit stranou.

Jinak nebudete stoupat. Nebylo pro Mě složité dát vám realizaci, protože jste už na to byli nachystaní. Ale udržet si své světlo, pro to musíte tvrdě pracovat. Tygr zůstává na své pozici. Nemění se. Lev zůstává na své pozici a všichni jsou po celý čas k dispozici na svých vlastních pozicích. Všechna božstva a bohové jsou na svých vlastních pozicích se svými vlastními kvalitami, jsou tam. Nikde není žádný z těchto Bohů popsán, že by vám dal mókšu. Vyjma Bohyně. Ona je jedinou, která vám dává realizaci.

Protože Ona zodpovídá za všech sedm čaker. Udržuje všech sedm čaker a v těchto sedmi čakrách to může vypracovat. Takže existuje velká historie, evoluce všech těchto věcí, dokonce i v těle Viráty a také ve vás, lidech. Takže se s tím musíte vypořádat. Pokud se s tím nemůžete vypořádat, tak se to nevypracuje. Nuže, problémy, které na Západě máme, jak víte, jsou hloupé a nehodí se pro žádného sahadžajogína. Připoutanost. Nejprve nebyli připoutaní ke svým ženám nebo ke svým dětem, teď jsou přilepeni jako lepidlo. Neříkám, abyste se vzdali svých dětí nebo manželky, ale vaše připoutanost by měla být k Sahadža józe. Jakmile k vám přijde požehnání Sahadža jógy, poplyne k vašim dětem, k vaší ženě, ke každému, k vaší zemi, do celého světa.

Předpokládejme nyní, že toto je připojení, velice prostá elektřina. Takže pokud není připojena do sítě, ale někam jinam, k čemu to je? Nikomu nemůže dát elektřinu. Je to jednoduchá logika, že byste měli být nejprve připojeni ke zdroji elektřiny. Jednoduchá logika. A pak tato energie může plout k ostatním. Pokud sami nejste připojeni ke zdroji energie, jak může tato síla kamkoliv proudit? Je to jednoduchá věc, které v Sahadža józe nerozumíme. A tak naše připojení začíná rezivět a nechápeme, co se nám stalo. Nejsme připojení k hlavnímu zdroji!

A to je jediná připoutanost, kterou potřebujete. A pak vše poteče na druhý konec. Takže máme tyto druhy připoutaností. Pak jsme připoutaní k tolika ubohým věcem, které máme rádi, které z nás dělají ubožáky. Například jsme připoutaní, řekněme, k nějakému druhu hloupé podnikatelské módy. Jsme k tomu připoutaní, ať je to sahadž kultura nebo ne, jsme k tomu připoutaní. A všechny tyto připoutanosti nejsou ke zdroji, ke zdroji radosti, ke zdroji vědění, ke zdroji energie, která vás pozvedá. To je důvod, proč je naše situace kolektivního vzestupu tak slabá. Prací Ádi Šakti je za prvé dát vám realizaci, za druhé dát vám život, utěšit vás. Pokud máte fyzické problémy, postará se o vás.

Udělá, co je v Jejích silách. Pokud máte mentální problémy, pokusí se je vyřešit. Takže je utěšitelem, dává vám útěchu. Zároveň vás chrání. Viděla jsem dokonce i nyní mnoho lidí, kteří se velice rychle vystraší při nejnepatrnější věci. Proč byste měli být vystrašení? Tady stojí tygr. Nevidíte ho, možná dnes může být na fotce. A vaše Matka je tak mocná. Musíte pochopit, jak je mocná.

Je to tím, že to pochopení není ve vašich hlavách. Někdy jsou vaše ženy mnohem mocnější, nebo vaše děti jsou mnohem mocnější. Když víte, že je vaše Matka tak mocná - je to vaše Matka! Tak byste se měli cítit naprosto bezpeční. A pak se věci vypracovávají. Dám vám příklad jednoho džentlmena, se kterým jsem se kdysi setkala v Madrasu, není to moc dávno, myslím tak před dvěma, třemi roky. Byl takový hledač, okamžitě Mě rozpoznal. A pak jel do Bombeje, byla tam pošta, a dostal dopis, který říkal, že je jeho matka na smrtelném loži. Tak odjel. Doktor řekl: "Má rychle postupující rakovinu a velice brzy zemře."

Věděl: "Moje Matka je Ádi Šakti." Jen vzal Moji fotografii, sedl si před ni, řekl: "Matko, nemám k tomu co říct, cokoliv si myslíš, že je vhodné pro moji matku, prosím, udělej to." Jen to takto řekl. Byl ve spojení. Po třech dnech, co řekli, že zemře, tři dny nato se dostala z nemocnice. Vzal ji do Bombeje, ukázal ji v nemocnici, kde se léčí rakovina. Řekli: "Žádnou rakovinu nemá, nic, je zcela vyléčena." Pokud není energii dovoleno, aby plynula, bojíte se stále o svou ženu, bojíte se o svůj dům, bojíte se o své děti, bojíte se o toto, o "mé děti, můj dům, moji ženu". Když toto "moje" odpadne, tak mohu pracovat. Nemělo by se to ale brát tak, že říkám, abyste se stali askety, v žádném případě.

Žádní svatí nebyli askety, všichni měli manželky, všichni měli děti. Ale celá jejich pozornost byla na Lotosových chodidlech Matky. Stejně jako říkal Guru Nanak, že si malý chlapec hraje s papírovým drakem - drak jde všude a on si povídá se svými přáteli, žertuje a podobně, ale jeho pozornost je na drakovi. Žena, která uklízí dům s malým dítětem u pasu, uklízí dům a upravuje ho. Dělá všechno, ale její pozornost je na dítěti. Pak jsou v Indii ženy, jak víte, mají tři, čtyři džbány naplněné vodou a kráčejí s oběma rukama takto. Vědí, jak udržovat rovnováhu. Mluví spolu, smějí se, dělají si legraci, žertují. Ale pozornost je na džbánech. Moje pozornost je stále na vaší Kundaliní.

Nemůžete v Sahadža józe hrát triky, přijměte to. Kdokoliv, kdo se pokouší hrát nějaké triky, bude velice těžce potrestán. Takže buďte, prosím, velmi, velmi opatrní, abyste nebyli nečestní, a nehrajte v Sahadža józe triky. Já nic dělat nebudu, ale tady jsou oni! Už jste ho viděli... se všemi jeho zuby. Jsou to všechno dané veličiny, řekla jsem jim. Jsou to všechno dané veličiny. Vědí, co dělat a udělají to. Takže není třeba, abyste v Sahadža józe hráli jakékoliv triky. Toto je další omyl sahadžajogínů, že si myslí, že se Mnou mohou hrát triky, nebo se Sahadža jógou.

Když tyto věci přijdou do vaší hlavy, měla bych říct, že to jsou ďábelské myšlenky, protože vás naprosto zničí. Na jedné straně je Sahadža jóga požehnání, naprosté požehnání pro váš vzestup, takto postupujete. Jdete na vrchol, ale také musíte vědět, že jste dosáhli určité výšky; musíte tam být velice opatrní. Protože jakmile z této výšky spadnete, jak hluboko to bude? Opět je logické vědět, že spadnete velice nízko. Takže jste tady a dostáváte všechna požehnání, všechnu krásu, všechnu lásku, všechnu radost, všechno vědění, všechny přátele, všechnu péči. A tady - jestli tu být nechcete jen proto, že hrajete triky - chtít být tady a hrát triky - to není možné. Nefunguje to, jste okamžitě vyhozeni. A jakmile jste jednou vyhozeni, Bůh ví, kam půjdete. To není naše starost.

Ale jste vyhozeni těmito. Takže člověk musí vědět, že božstva jsou nesmírně ostražitá. A všechna vás sledují. Protože vás musí chránit, musí se o vás starat, musí vám pomáhat, musí pro vás všechno dělat. Musí pro vás všechno vypracovat. Jsou těmi, která pro vás vytvářejí květiny; dělají pro vás všechny druhy prospěšných věcí. Ale současně jsou oddána pouze Mně, ona všechna, ne vám. Protože vy jste Moje děti, tak se o vás starají. Jakmile se pokoušíte chovat špatně, jste vyřízeni a jdete ke dnu. Ale milosrdenství vaší Matky je tak velké, stále se snaží odpouštět, dát šanci a říká těmto božstvům, aby byla potichu.

Samozřejmě, že poslouchají - do určitého bodu. Pokud ale chcete být neslušnými lidmi, pokud chcete být krutými, chcete-li být hříšnými a zůstat v Sahadža józe - nemůžete. Není to jako nějaké náboženství, jak jste včera viděli, že se dopustíte jakýchkoliv chyb, děláte, co chcete, kohokoliv zabijete, kohokoliv podvedete a stejně tam budete. Takto to není. Tady musíte být sahadžajogíny v pravém smyslu slova. A kvůli tomu to člověk musí pochopit. Přišli nějací sahadžajogíni, nemohou dovnitř, myslím, že jsou zavřené dveře. Takže je tu taková ohromná síla, tak pozorná, tak láskyplná, tak laskavá. A Matka, která je vaším učitelem. Matka učí děti s láskou.

Nejen to, ale nikdy jste dokonce nepocítili, jak jsem vás učila Sahadža jógu. Prostě jste se ji takto naučili. Je to pro vás dětská hra. Je to tak těžký a důmyslný předmět; pochytili jste ho bez jakýchkoliv obtíží. Bylo to uděláno tak důmyslně, bylo to uděláno nádherně, vystavěno uvnitř vás, nyní víte, že toto je Sahadža jóga a toto není Sahadža jóga. Všechno toto vědění k vám přišlo tak sladce. To, jak zpíváte indické písně, víte, dokonce i Indové jsou překvapení, někdy neumějí zpívat, jako vy. Ti, kteří přišli na Můj program, vás viděli. Nějací hudebníci řekli: "Byli jsme opravdu zahanbeni. Jak mohou tito lidé tak dobře zpívat?

A všechno tak dobře vyslovovat?" Musíte této síle plně důvěřovat! V dobách, kdy byli lidé v nesnázích, stále byli napadáni, neměli svoji seberealizaci, museli vložit svoji víru v tuto Božskou sílu. Museli. Ale nyní, když máte realizaci, máte svoji svobodu. Nikdy byste neměli zapomenout, že musíte důvěřovat této Božské síle. Že se o vás bude po celý čas starat. A teď - jak hrajeme v Sahadža józe triky? Nějací líní nekňubové přijdou do Sahadža jógy. Naprosto líní nekňubové, to znamená, že musí být levostranní nebo něco podobného.

A když jim řeknete: "Raděj udělej tuto práci." "Ne, Matko, nebudu tuto práci dělat, protože by vzestoupila moje pravá strana." Velmi běžný trik. Je to velice běžný trik: "Nemůžu tuto práci udělat!" Když přijde na práci, prostě utečou. Kolik lidí pracuje? Velice málo. Onehdy jsem zašla do kuchyně a zeptala jsem se indických dívek, co se děje. Řekly: "Všichni utíkají pryč. Není tu nikdo, kdo by nám pomohl."

Nikdo nechce převzít zodpovědnost. Ale trikem je, že se to hraje v Sahadža józe, že: "Když udělám tohle, stanu se pravostranným." Ale pokud se stanete levostrannými - tady ten je tu! Je moc dobře, že jste ho sem dali, jsem ráda. Takže všichni letargičtí lidé, líní nekňubové, tohle vždy dělají. Nyní - někdo někomu řekne: "Musíš vstávat zrána." Vyvolá to v nich hrozný pocit: "Ó, jak vstávat?" Ale když se ohlédnete za svým vlastním zázemím - řeknete, že jste museli brát drogy, museli jste pít alkohol, museli jste brát všechny tyto levostranné věci, proto nemůžete vstávat zrána! Nuže, jak ukončíte nebo zneutralizujete tyto špatné návyky, které máte? Jak to uděláte?

Když začnete vstávat brzo ráno, vytvoříte si pomalu návyk a můžete se toho zbavit. Je to jen o tom, udělat si čas ráno před východem slunce. Alkohol sám je takový levostranný nesmysl. Natolik, že Bohyně kdysi vypila všechen alkohol světa. Nebudete tomu věřit, všechen alkohol! Světec Sai Nath vykouřil všechen tabák Maháráštry, ale lidé přesto kouří. Stejně jako Šiva vypil všechen jed, protože je dárcem života. Cokoliv takhle vypracovali, tak upřímně, svědomitě, s plnou pozorností. Vidíte Mne takto pracovat, ale oni pracovali také tak. Takže neberte věci za samozřejmé.

Řekla jsem mnohým z vás, abyste napsali - co jsem dnes udělal pro Sahadža jógu? Pro sebe udělám všechno - natřu dům, vymaluji kuchyň, všechno, vyspravím si krásné sárí, blůzu, já sama. Co jsem udělala pro Sahadža jógu? Kolik dárků jsem dala ostatním? Kolik dopisů jsem napsala ostatním? Jaké zážitky jsem popsala? A především, kolikrát jsem v srdci cítila lásku své Matky? Ale řeknu vám důvod, proč je na Západě velký problém - nyní jsem to objevila. Tak jako jsem objevila Sahadža jógu, tak jsem také objevila tajemství, které vám dnes řeknu. Je to také síla pronikání, že člověk může odhalit démony, jak pracují v našich myslích, jak prosperují.

Myslím, že jsem to některým lidem řekla, ale řeknu vám to teď všem. Když jsme dětmi, do věku pěti let jsme orientovaní na ego v tom smyslu, že se staráme jen sami o sebe. Dáte deset hraček deseti dětem, vezmou si své hračky a budou si spolu hrát, nebudou s nikým mluvit, jen půjdou a budou si hrát. Nebudou nikoho jiného rušit, je to naprosto souběžné žití. Nebudou rušit. Pokud ruší, mohou tlouci, mohou dělat něco jiného, nesmyslného. Může to být díky nějakému druhu bhúta uvnitř, když jsou dětmi. Když je jim ale pět let - dejme tomu, že se zeptáte nějakého dítěte tady: "Poslyš, co vidíš?" Řekne: "Vidím tu tygra a tyto květiny, to, to, vidím tohle všechno." Ale když ho postavíte tam: "Řekněme, že někdo stojí tamhle, co uvidí?"

Pořád bude říkat, že uvidí tygra, květiny, to a to. Zkuste to. Protože nedokáže vidět z úhlu pohledu jiného člověka. Prostě je zaneprázdněný svým egem. Nuže, nyní jsem objevila, že celá kultura na Západě, - nevím, dříve to tak nebylo - rodiče své děti ovládali a měli za ně zodpovědnost, chovali se správně, takže děti mohly být v pořádku. Ne neustále před dětmi vzájemně bojovat. Chci říct, trošku bojovat musí, ale musí to dělat v ložnici. Protože - když jsem byla malá, tak jsem neviděla filmy, kde manžel a manželka celý čas bojují nebo se rozvádějí. Vůbec žádné porozumění mezi mužem a ženou, ale když je to jiná žena nebo jiný muž, jejich tváře budou takhle. Když na ulici vidíte dva lidi, kteří spolu jdou takto, pak víte, že tito dva nejsou manželé.

Je to moderní doba. Jsou to moderní časy. A na Západě je to nejhorší. Takže se děje to, že ani rodiče nejsou dospělí, jsou nedozrálí, nemají žádný smysl pro zodpovědnost. Mají děti, nevědí, jak se chovat k manželovi, zejména zdejší ženy jsou neobyčejně, nesmírně dominantní a hloupé. To musím říct. Nevědí nic o vaření; nevědí nic o ničem. Mohou dělat pouze poslíčka, mohou sedět v bance a něco psát. A jsou nesmírně hloupé; nevědí, jak zacházet se svými muži, nevědí, jak zacházet se svými dětmi. Nemají žádnou průpravu.

Jejich matky jim nevěnovaly žádnou pozornost. Vůbec žádná disciplína. Takže toto dítě zaměřené na ego je stále dítětem zaměřeným na ego. Žádná láska. Měli bychom říct, že Moje matka byla velice přísná. Neobyčejně přísná. Ale byla také neobyčejně milující - neobyčejně milující, neobyčejně přísná, zrovna jako Džagadamba. Chci říct, nutila by nás vařit, dokonce jak držet náčiní, řekla by nám: "Toto není správný úhel, dělej to takto! Proč stojíš takto? Kde máš pozornost?"

A nebyly povolené žádné otázky. Všechno ukázňování a všechny tyto věci, které jsme měli v dětství, nám dnes pomáhají. A byly nesmírně milující. Byly pro naše dobro, cokoliv dělaly, bylo pro naše dobro. Ale myslím si, že zejména ve Švýcarsku jsem vždycky cítila, že matky jsou nevzdělané a také nesmírně závidí svým dcerám. Naše matky - Moje matka byla velice vzdělaná, ale její matka ne. Ale byla to moudrá žena. Měla svůj smysl pro zodpovědnost, věděla, že je matkou a že se musí chovat slušně. Nesmí být dětinská a hloupá. Takže - protože těmto ženám nebyla dána láska, jsou stále orientovány na své ego.

Jsou stále nemluvňaty. Ještě nedospěly. Stále nedokážou vidět věci z pohledu někoho jiného a stávají se nesmírně tvrdohlavé: "Ne, toto je pravda!" Nuže, postavme se tomu, dnes jste měli tuto púdžu k Ádi Šakti, která je nebezpečná, protože je jako zrcadlo, kde uvidíte sami sebe jasně - postavte se sami sobě. Ovládat svého manžela je hloupý nesmysl. Protože nevíte, jak si poradit se svým manželem - proto to je. Řekla bych, že indické ženy ovládají své manžele dobře svým způsobem. Muži se bez svých žen neobejdou, neobejdou se bez svých žen. Neví ani, jak si zabalit věci, ani neví, jak uvařit čaj, neví, jak uvařit vejce, neví nic. Neví ani, jak zamknout dům, otevřít - dokonce otevřít skříň, jak ustlat postel.

Neví nic, co je praktické, chci říct, že Můj muž se Mě vždycky přišel zeptat: "Je tato kravata v pořádku?" Je to už dlouho, nyní ví, že jsem Ádi Šakti, ale dřív také chodíval a ptal se: "Je to v pořádku?" "Ne, ne, to není dobré." Dobře, převlékl se. Ale protože nejste dospělé, nevyzrály jste, nevíte, jak se svými manželi zacházet, zkoušíte je ovládat. A pak se to děti od vás učí, také vás zkoušejí ovládat. Zjevně musíte pochopit, že je to autorita přicházející shora. Například vždycky řeknu: "Já nejsem Bůh, Sadášiva je Bůh." Gregoire byl zcela šokován, když jsem mu to poprvé řekla. Ale já jsem Bůh také.

Co je On beze Mne? Jsem Jeho silou. On je bezmocný. Ale nechme Ho být Bohem, fajn. Protože pokud musíte někoho obviňovat, obviňujete Jeho, On je Bůh. Ale Já musím tvrdě pracovat, abych Ho udržela spokojeného. Jinak víte, že Jemu na nikom nezáleží. On bude jenom ničit, to je vše, co zná. Zničí vás, kdokoliv na Mne zkouší hrát nějaké triky, zničí vás natolik, že po mnoho životů se nebudete moci stát lidskou bytostí. Takový je On hrozný chlapík.

Je Ten, který udělal všechny tyto věci. Takže musíme růst. Musíme se vyvinout v moudré ženy, ženy, které jsou jako Matka Země, jak jsem vám řekla. A když se Mě ptáte: "Matko, Ty pracuješ tak tvrdě a vypadáš tak svěží." Protože Já se tím těším. Je to pro Mě jako hudba. Něco dělat je pro Mě jak hudba. Vaření je pro Mě hudbou. Všechno je pro Mě hudbou. Unavíte se hudbou?

Naopak, cítíte se osvěženi. A když zabiju démony - museli jste vidět, že jsem víc rozzářená, vchází do Mne více světla. Je to zrovna naopak. Takže vás musím přimět porozumět, abyste dnes, prosím, udělali plnou introspekci, průzkum duše. Zjistěte, co je s námi špatného. Nerozmazlujte své ego, protože ego vás činí hloupými, což jste museli vidět. Máme v Sahadža józe nějaké lidi, kteří jsou jako tito hlupáci. Ale myslí si o sobě kdo ví co. Všichni to víme. V cirkusu musíme mít také nějaké šašky. Ale musíme mít lvy a tygry.

Na lidi udělají dojem lvi a tygři a ne šašci. Takže je důležité, abychom dělali introspekci a sami pro sebe viděli, kolik jsme toho udělali pro Sahadža jógu. Samozřejmě, že vám musím blahopřát k jedné věci. Protože, víte, Já taková jsem. Neudělala jsem nic, abych taková byla, prostě taková jsem, jsem. Takže Já jsem síla. Mám sílu, protože jsem tou silou. Proč se kvůli tomu cítit tak nadšená? Vůbec se tak necítím. Ale když nebudu používat svoji sílu, pak budu jako lidské bytosti.

Proč jsem Bohyní? Protože používám každičký kousek své síly. A pokud vy, lidé, nebudete používat svoji sílu, kvůli jakémukoliv nesmyslu, jaké- mukoliv strachu, který můžete mít - můžete mít jakýkoliv druh pokušení, nebo omezení, cokoliv. Jestliže nebudete naplno používat svoji sílu lásky, pak nemůžete stoupat. Takže pokud vidíte jasně celou věc, veškerá síla vaší Matky je láska. Cokoliv dělá, je z lásky k tomu, co stvořila. A začíná introspekce, ale nemělo by to být pozdě. Už dávno jsem říkala, že způsob, jakým vyčerpávají Matku Zemi, vytvářejí tolik věcí... Museli jste Mě slyšet to říkat, říkám to posledních osmnáct let. Dnes před námi stojí ekologické problémy jako rakšasa - démon. Nuže, co s tím děláte?

Postavte se tomu. Automaticky se musíte postavit sami sobě, své destrukci. Pokud nyní neděláte introspekci, budete tomu čelit v době, kdy bude očividně pozdě. Takže nebuďte jen sami se sebou spokojeni, že teď máte Sahadža jógu, tak hotovo. Samozřejmě, když přijdete na Moji púdžu, je to jako byste spadli do moře, moře má sílu vás vstřebat. Ale také má sílu vás vyhodit zpátky na břeh. Jedná oběma způsoby. Takže, proč nemohu jít hlouběji do Sahadža jógy? Existují také výmluvy, nemám čas, jsem velice zaneprázdněný, pracuji v úřadě, dělám toto. Pak nejste sahadžajogín.

Všechen váš čas je pro Sahadža jógu. Ale díky tomu vám Sahadža jóga dá dostatečný čas dělat cokoliv. Znám lidi, které jsem najednou objevila na púdžích, někdy ve Vancouveru, někdy v San Diegu, někdy tady. Řekla jsem: "Jak to, že jsi tady? Co tvé podnikání?" Řekl: "Podnikání nás sem přivedlo, přesně v tento den." Když je tato síla tak ohromná, když ji pochopíte, když víte, jak je ohromná, pak všechno této síle přenecháte. Všechno pro vás vypracovává. Takže dnes mluvíme o Šakti, o síle Bohyně, která musí být mnohem více objevena a která je velmi složitá, velice dobře vyvážená a neobyčejně efektivní. Ale jakoukoliv práci tyto síly uvnitř vás udělaly, prosím, pokuste se jich vážit.

Prosím, pokuste se je přijmout a dovolte své bytosti růst. Neříkejte, že: "Nyní jsem ženatý," nebo: "Nyní jsem těhotná, mám děti, mám práci." - Nic. Všechno bude dokonalé, jakmile se sami zdokonalíte. Všechno souvisí s vaší dokonalostí. Pak se Mě nebudete ptát: "Jakou mám, Matko, dělat práci, čeho mám dosáhnout?" Ničeho. Jen se dívejte z nadhledu a všechno se vypracuje. Všichni démoni byli zabiti, ale jsou zpátky na svých místech. Nejhorší je, že vstoupili do hlav hledačů, protože teď přišli jako guruové.

Přišli jako katolická církev, jako protestantská církev, jako všechny druhy chrámů a všechny druhy fundamentalistů a podobně. Všichni také vypadají jako rakšasové, pokud se na ně podíváte. A když na vás mají vliv, jdou do vašich hlav. Ale po příchodu do Sahadža jógy, jsou dokonce i tyto hlavy vyčištěny a jste v pořádku, jste z toho venku. Co pak ale s tím dělat, s konáním vší té práce, čištěním, dáváním radosti a všeho, co pak dělat? Musíte to dát ostatním! Toto je vaše zodpovědnost. Takže nejprve by vaše povaha, vaše chování, vaše vztahy, měly být natolik čisté, že samy o sobě budou vyzařovat světlo. Jako když máte velice čisté sklo, světlo může projít. Avšak také vzhledem k tomu, že je Kundaliní čistým přáním, musíte mít velice vroucí a nesmírně překypující, můžete to nazvat naprosto chrlícím přáním, komu dát vibrace, komu dát realizaci?

Dáváte je stromům, dáváte je psům, dáváte je každému, a pokud objevíte lidské bytosti, dáte to i jim. Poněkud obtížné. Takže to se musí stát. Cokoliv ale děláte, udržujte pozornost na vašem spojení. Ale tady dělají Sahadža jógu, a vaše spojení je volné, co pak dáváte? Sahadža jógu, nebo co? Dáváte temnotu? Dávate nevědomost. Dáváte bláznovství. Takže musíte po celý čas s touto mocnou silou udržovat spojení a udržovat ji spokojenou.

Jako je velice důležitý protokol, kvůli všem těmto, víte... Mají smysl pro protokol, protože jsou upevnění. Vy byste také měli svůj protokol dobře upevnit. Je to poněkud obtížné nebo trapné Mně, jako lidské bytosti, vám říkat, jaký by měl být protokol k Bohyni. Ale musím vám to říct, protože nechci, abyste byli zraněni. Ale protokol musí být dodržován a mělo by mu být dobře porozuměno. Samozřejmě, dnes je to mnohem lepší. Poprvé, když ke Mně měli v Dillí púdžu, tak Mi dělali árti umělohmotným táckem a kumkum byl v umělohmotné dózičce. A tolik jsem se o tyto lidi bála, že celé Moje tělo bylo takto smrštěné, jak jsem Je kontrolovala: "Teď nic nedělejte!" Když se podíváte na Moji foto- grafii, uvidíte Mě naprosto jinou. Byla jsem tak překvapená, že nevěděli, co dělat.

Dobře, nuže, dávejte, prosím, také pozor na svůj protokol. Například, lidé chodí třeba časně zrána ve svých pyžamech - to není správné. Musíte se vhodně obléct. Jdete - nevíte, kdo je Ádi Šakti. Nebo víte? Pokud víte, pak jdete před Ádi Šakti. Protokolu musí být porozuměno. Naštěstí v Indii pro to mají lidé dobrý smysl; někdy i oni něco přehlédnou. Takže protokol je velmi důležitý, protože tito budou opravdu rozzuření, pokud nebudete protokol dodržovat. Je to nesmírně důležité.

Proto Kristus řekl, že: "Budu tolerovat jakýkoliv nesmysl proti Mně, ale nic proti Duchu Svatému." A také řekl: "Mějte se na pozoru před reptajícími dušemi", protože pokud za Mými zády reptáte, Já slyším všechno. V jednom kuse Mne informují. Pokud cokoliv děláte za Mými zády, vím, co se děje. Poskytuji čas. Ale pak to působí. Je to pro vaši benevolenci, pro vaše dobro, pro váš vzestup, za který jste po léta bojovali! Musíte si vážit sami sebe, že jste hledači, a nyní jste našli pravdu, takže z toho vytvořte korunu a vložte si ji na hlavu. Nyní jste jako šlechtici. Dokud nevíte, co máte za síly a jak jste je získali, a pokud to nemáte na paměti a také dokud se tato pravda nestane vaší nedílnou součástí, váš růst bude velmi těžký.

Nebudete ani tady, ani tam, budete zavěšeni ve vzduchu jako kyvadlo, chodíce sem tam, zleva doprava, zprava doleva. A sahadžajogíni by se měli stydět říkat, že: "Půjdu doleva, nebo půjdu doprava." Jak můžete být tak zranitelní? Protože jste nedospěli. Musíte být jako skála Gibraltaru. Jak můžete něco chytit? V pořádku, pokud si myslíte, že je někdo nesmírně negativní, nechoďte blízko takové osoby. Ale nemůžete být přecitlivělým zlatíčkem. Moje děti jsou Šivovi bojovníci. Musí jimi být.

Vy jste Moje děti. Nejste více křesťany, hinduisty, muslimy, nejste více těmito hroznými ďábelskými lidmi, ale jste Mými dětmi a musíte být odvážní, musíte být poctiví, musíte být dobří, musíte být milosrdní, musíte být dynamičtí. To je minimum. Doufám, že po této púdže si sednete, budete meditovat a dělat introspekci a zjistíte: "Proč dělám tohle? Co je to za problém?" Pomyslete, někteří lidé včera podřimovali, viděla jsem je. Kvůli levému Nábhí. Takže opravte své levé Nábhí. Ale pokud jste opravdu s touto Božskou silou spojeni, můžete být vzhůru tři dny a tři noci, nebudete unaveni. Někdy se vám to stalo.

Ale pozornost by měla být na síle, pozornost by měla být na spojení, které máme s touto silou. Pouze tehdy. Jinak budete pochopitelně vyčerpaní. Všechno je tak logické, je to tak logické. Děkujte Bohu a děkujte sami sobě, děkujte svému osudu, že máte takové štěstí, je vás velmi málo, kdo jste dosáhli tohoto spojení, a kteří jste do sebe nasáli tuto sílu tak snadno. A co jste, proč se chováte jako tito obyčejní lidé z ulice se svými hloupými otázkami? Budete překvapeni, že Bohyně v předešlých životech nemluvila tolik, co mluvím Já. Jedno nebo dvě slova stačila, řekla třeba: "Hu!" a zabila tohoto, "Ha!" vyřídila tamtoho.

Všechno to zvládala jen říkáním: "Hu, ha, hi, hej". Ale žádná z inkarnací nedala nikomu realizaci. Říkali: "Ne, ne, ne, ne, ne, já ne. Já ne, lituji, já to dělat nebudu. Museli poznat, jak jsou lidské bytosti hloupé. "Ó, Bože, nic. Já jsem v pořádku. Můžu jít na čtrnáct let do džungle, můžu dělat Ardžunovi vozataje, nebo se mohu nechat ukřižovat, nebo pozřít jed, ale neříkej mi, abych se věnoval lidským bytostem! Ne, ne, ne, ne. Lepší je jít do ZOO než za nimi."

A proto nikdo z nich, nikdo z nich, a někteří o tom dokonce ani nemluvili, mysleli si: "Když o tom budeme mluvit, řeknou: Tak proč nám nedáte realizaci?" Nikdo z nich. Takže toto je soucit, láska a sebejistota Ádi Šakti, že vy byste také měli mít sebedůvěru. Nejen, že jsem vám dala realizaci, ale dala jsem vám i síly, že můžete dát realizaci ostatním. Žádná z těchto inkarnací nedělala, co dnes děláte vy. Nedělali to ani se všemi svými silami, zatímco vy to dělat můžete navzdory tomu, že nástroje nejsou tak silné, nejsou tak božské. Ale stejně - stejně musíme být k dispozici a vypracovat v našich vlastních životech, jaké máme priority. Pro bohy byla prioritou pouze božská práce, nic jiného. Nikdo se nezačal věnovat zaměstnání, nikdo. Nikdo nešel na univerzitu, nikdo nestudoval.

Jediná věc, kterou dělali, byla práce Boha. Takže dělejte všechno ostatní jako práci Boha a takto do vás bude vtékat energie. Když začnete dělat práci Boha, všechno, co děláte, se stane prací Boha ve smyslu, že děláte práci Boha, a když se rozhodnete: "Budu dělat práci Boha," pak se toho Bůh ujme. Dělá všechny ostatní věci, vy děláte pouze práci Boha, On se toho ujme. Doufám, že tomu rozumíte, pokuste se. Snažte se. Mějte důvěru. A také děkujte Bohu, že je tu někdo, jako vaše Matka, kdo vám řekne, co je s vámi špatného. Děkujte Bohu! Dokonce vaše matky vám neřekly, co s vámi nebylo v pořádku, protože z vás byly vystrašené.

A neříkejte pak - když pak řeknete: "Matko, mám napadené srdce." Chci říct, co pak můžete dělat? Pokud porozumíte, že tohle je pro vaše zdokonalení, dělám to z lásky, pro dobro, pak to vypracujete. Ale nemyslím si, že je to tolik o rozumovém pochopení, ale je to pochopení vyšší úrovně, kde se to stává prostě nedílnou součástí vašeho vědomí. "Jak to může být špatné? Všechno to musí být pro mě dobré, vše je pro mě dobré." V neposlední řadě člověk musí pochopit, že tak, jako pracuji na všech sedmi čakrách, jsou pod Mojí kontrolou na kolektivní úrovni, ve Virátě. Povaha Viratangany je taková, že ona vytváří toto univerzální vědění uvnitř nás, kolektivitu. A pokud nepochopíte, že v moderních dobách jste na duchovní cestě pouze kolektivním způsobem. Takto to je.

Protože jsme dosáhli stavu Sahasráry a tady musíme mít pouze kolektivní práci - neexistuje jiný způsob! Toto musí být zcela pochopeno. Každý, kdo se pokouší poškodit kolektivitu špatným chováním, nebo něčím jiným, bude vyhozen, bezpochyby, ale také padne do špatných rukou. Takže kolektivita je prací Ádi Šakti. Protože v Sahasráře, v Sahasráře, v Sahasráře je zákon Viráty. A silou Viráty je Viratangana. Ten, kdo dělá kolektivitu. Toto je nejdůležitější bod, který si musíme uvědomit; pokud nemůžeme být kolektivní - kvůli čemukoliv, možná žárlivosti, možná pocitu méněcennosti, čemukoliv, čemukoliv, co přichází zezadu jako plazící se červ, pak byste měli vědět, že je s vámi něco špatně, s kolektivitou nic špatného není. Nekritizujte kolektivitu, dokud to sama nezjistím - a pak to napravím. Držte se kolektivity moudře a vroucně a snažte se držet kolektivitu pohromadě.

Pokuste se pomoct, aby se lidé v kolektivu navzájem těšili. Nekritizujte jeden druhého; kritizujte pouze sami sebe, pokud máte zvyk kritizovat, raději kritizujte sami sebe. Je to lepší, protože toto jsou také zvyky. Lidé - viděla jsem, že zejména lidé ze Západu, na všechno reagují. Když vidí koberec: "Ó, to se mi nelíbí!" Ale on není váš, nebyl vyroben pro vás, co s ním máte společného? "Ne, nelíbí se mi!" Není ale váš, tak kde je problém? Leží tady, proč byste se kvůli němu znepokojovali? "Nemám rád tohoto člověka!

Toto oblečení se mi nelíbí!" Kdo jste? "Nelíbí se mi." Toto v Sahadža józe není dovoleno - "Nelíbí se mi." Existuje způsob, jak to říct. Ale není žádný důvod cokoliv říkat. Takže všechny tyto druhy domýšlivosti a předvádění se jsou proti kolektivitě. Pak existují další typy hloupých lidí, kteří jsou tu stále, aby Mě fotografovali. Řeknete jim: "Nebuďte tak vpředu, nechoďte tam." "Ne, půjdu, nejsem vpředu, ne.

Konec!" Ale někteří z nich jsou opravdu zarytí, zaručení hlupáci, tupci. Není možné je polepšit. Ale řekla jsem vám, abyste si z nich nevytvářeli vzory, nenásledujte jejich představy. Takže jsme přišli do bodu, kde práce Ádi Šakti je tou nejdůležitější prací v celém tvoření. V pořádku, zabíjení démonů je pryč, co je to? Hotovo! Práce Sarasvatí je hotová, vytvořila dinosaury, no a co? Práce Mahálakšmí je hotová. Přivedla vás na lidskou úroveň, v pořádku, no a co?

Ale vrchol je teď, že jste získali svoji realizaci, že jste získali tuto zvláštní vlastnost, že nyní jste vstoupili do Království Boha. Takže se chovejte slušně. A také musíte mít sebeúctu, abyste si uvědomili, že nyní jsme vstoupili do Království Boha. Jednou jsem byla navštívit prezidenta Indie. Pro Mě ale byl další lidskou bytostí, chci říct, že Mi nikdy nepřišlo na mysl toto prezidentství a podobné věci. Procházela jsem se a ti, kteří se procházeli se Mnou, si toho začali být velmi vědomi, zrovna takto. Řekla jsem: "Co se s těmito lidmi děje? Viděli nějaký přízrak, nebo něco podobného?" Šli jen tak po schodech. A někteří lidé tam stáli s kopím a podobnými věcmi jako stráž, nebo něco podobného.

Jen jsem se tomu všemu smála. Ale tito lidé si to velice uvědomovali. Když vstupujete do Božího království, nakolik byste si měli být vědomi svého chování! Jací byste měli být, jak byste se měli chovat? Jednoduše cítit jedinečnost své osobnosti, že již jste v Království Boha. Cítit. Když to jen pocítíte, pak budete vědět, jakou hrdost jste získali a jak důstojní byste měli být. Jak nádherní byste měli být. Jak upravení a čistí a příjemní byste měli být. Kolik musíte znát maryád, všechno.

A jakmile si uvědomíte, že nyní jste žádanými, nebo, můžeme říct, nejvyššími občany Království Boha, pak musíte prokázat, že jste si toho opravdu vědomi. Že to opravdu cítíte. A měli byste se cítit neobyčejně radostní, šťastní. Jako včera - každý se smál těm nejmenším věcem jako ostatní lidé z ulice. To není Sahadža jóga. Smějte se, pokud někdo řekl velký vtip, jinak - někdo mluví a vy se smějete! Byla jsem překvapená, jste sahadžajogíni. Pomyslete, že by to dělali svatí, dělali by to? Jste světci; jste "munindras", prostřednictvím meditace jste se stali králi. Jak se můžete chovat nedůstojným způsobem?

Pokuste se zaujmout svoji pozici! Snažte se to vnímat. Včera, když začala poslední píseň, víte, že do mnoha duší, mnoha srdcí pronikla, jedinečná radost, kterou nazýváme niránanda. Včera jsem to cítila. Ale udržte si to, jen to musí být pevně uchováno ve vašich Kumbách, což je Kundaliní. A Ona je Tou, kdo přichází. Takže můj plán byl, že dnešek je nejen dnem uctívání Kumby, kde sídlí Kundaliní, ale Kumba se stává jakoby květináčem. Je to takto, takto se to stalo a pak také může, jak někdo řekl: "Matko, tyto květináče se také mohou stát lampami." Řekla jsem: "Podívejte, teď jste to řekli!" Takže Kumba se stává květinami a květiny se stávají světlem a to vonícím světlem!

Doufám, že porozumíte Mé vizi a postavíte se za Mě, stane se vám to. Naprosto na vás ohledně své vize spoléhám. Musíme tento svět přeměnit na nádherné místo. Není pro to potřeba mnoho obětí. Jste také požehnáni, nemusíte mnoho dělat, jedinou věcí je udržet svoji pozornost na zdroji síly. Nechť vám Bůh žehná. Děkuji vám. Mathias říká: "Slibujeme." Všichni to řekněte. Mnohokrát vám děkuji.

Všichni byste měli napsat o nějakém zázraku, a jak se věci vypracovávají. Například jsme jeli do Paříže a chtěli těmto ženám koupit nějaká sárí a nikde jsme nemohli sehnat nic ve velikosti 45. Buď to byla velikost 36, nebo 58. Pak, když jsme jeli autem, tak jsem najednou řekla: "Zastavte!" Řekli: "Cože, Matko? Na ulici?" Řekla jsem: "Zrovna tam na ulici někdo prodává sárí." A dostali jsme je. Nebo - jak už víte, v Ganapatipule na Ganéša púdže, jaké jsme měli štěstí ohledně vašich dárků. Vždycky jste přinášeli velmi drahé dárky, ale s žádnou uměleckou hodnotou, utráceli jste tolik peněz.

Dokonce na národní púdže jste nic nemohli sehnat. A jak jsme získali tohle? Úplně stejně. Cestou z letiště jsem jen řekla: "Tam něco je!" Řekli: "Matko, žádný obchod tam není." Řekla jsem: "Pojďme se podívat!" Jen jsme to obešli a byly tam všechny tyto věci. Teď se to stejné stalo v Americe. Sešla jsem dolů a řekla jsem: "Čína má potíže, kupme něco čínského." Tak jsme šli do čínských obchodů; měli tam tak draho, velmi draho.

Zašla jsem za roh a řekla jsem: "Dobře, nechte Mě jít do malé uličky." A tam byl obchod, kde pro- dávali všechno velice lacino alespoň o 40 %. Něco kolem 40 %. A jen tak náhodou, myslím, sto metrů odtamtud prodávali pětkrát, šestkrát dráž. A proč? Takže nyní to také zkuste. Ale přání musí být čisté, porozumění musí být čisté. Takže jsem si jen pomyslela, že tito sahadžajogíni utratí tolik peněz, vyhodí tolik peněz, a dostanou něco, co nemá žádnou hodnotu. Protože všechny dárky, které Mi dáváte - ve skutečnosti jsem je požádala, aby s tím přestali, aby to přestali dělat. Nyní jsme přešli z individuální na národní úroveň.

Ale dokonce i národní - myslím si, že bychom teď neměli mít žádné národní, ale jeden mezinárodní, pokud byste to příští rok zvládli a pokud byste souhlasili. Ale o cokoliv se jedná, cokoliv Mi dáte, nechystám se to prodat, nechystám se to nikomu dát, měli bychom to uchovat pro potomky, aby viděli, co jste dali. Ta hodnota je v tomto, ne v tom, kolik jste utratili. Takže není třeba, abyste Mi jednotlivě dávali jakékoliv dárky, já vím, že Mě milujete. A nyní - nevím, řekla jsem lídrům: "Nežádejte, prosím, o národní dárky, nevyhazujte peníze." Ale nevím, jestli s tím už souhlasili, ale jestli s tím souhlasili, tak s tím můžeme přestat. A mít pravidelný mezinárodní dárek, který může být také zrušen. Protože, víte, Já nic nepotřebuji. Ale ono to pracuje. Pracuje to.

Jako jsem řekla: "Dejte Mi tentokrát slonovinu." A slonovina byla tak drahá, a také jsme ji objevili na tak levném místě. A jakmile jste Mi dali slonovinu, nebudete tomu věřit, dočetla jsem se v novinách, že slonovina bývala pět set dolarů za kilo, a nyní je v Americe tři dolary za kilo. Takže to pracuje. A záměrem je také více podporovat rukodělnou výrobu a umění, protože tolikrát jsem řekla, že můžete vzít kousek hlíny a přetvořit ji na nádhernou věc, která má takovou hodnotu. Takže, proč bychom měli vyčerpávat Matku Zemi? Proč nemít pár uměleckých věcí místo vlastnění tolika věcí? Ale když jdete do obchodů, nic neseženete. Neseženete hedvábí, neseženete toto, neseženete tamto. Je to tak těžké sehnat něco přírodního, protože lidé vytvářejí pouze nepřirozené věci.

Ať je to jakkoliv, měli byste vytvářet krásu. Pokud začnete vytvářet krásu, tak se ji pokusme zachovat a používat šetrně místo toho, abychom měli tisíce nesmyslných věcí, všechno na jedno použití. Po nějaké době budeme muset mít lidské bytosti na jedno použití. Budeme je muset zlikvidovat. Jak budou na této zemi žít, když neporozumíme, že musíme žít na této zemi s jejími omezeními. Víte, že jsem vám mnohokrát říkala, abyste se dali na umělecké věci, abyste se dali na rukodělné věci, více na ručně dělané. Na toto se moc nedávejte. Nakonec - dokonce, i když musíte koupit něco, co je, řekněme, umělé, alespoň se postarejte, aby to bylo umělecké. Takže, jakmile budete mít velké přání - dnešek je dnem, kdy se na celém světě chtějí modlit pro zachování Matky Země - kvůli tomu jsem toto téma začala - že bychom se měli modlit, že bychom všichni měli rozvíjet umění pro sebe, dávat dárky ostatním, a také používat umělecké věci, vytvořené umělci. Můžeme mít pár věcí, ale uměleckých, které vyjadřují umění.

Ne levné věci. Po celé Francii jsem viděla, že se umělé hmoty vplížily do všeho, ať je to bavlna, ať je to hedvábí, ať je to vlna. Může to vstoupit do čehokoliv, kromě mozků lidských bytostí. Je to hrozné. Takže ať je to jakkoliv, postarejte se, abyste kupovali umělecké věci, ne řadové, hrozné, levné věci. Ano? Takže toto dnes musíme, také se dnes musíte ke Mně modlit, když děláte púdžu: "Ó, Matko, ó Matko, prosím, zachraň naši zemi a dej lidem moudrost, aby se chovali rozumně. A aby byli uvědomělí." A každý sahadžajogín by si měl být vědom, kolik energie využívá z elektřiny, z telefonů, kolik spotřebovává vody a ostatního. Musíme být šetrní.

Pokud za tyto věci nepřevezmeme zodpovědnost, tak to nepronikne nikam jinam. Je to na vás. Musíte se tím zabývat ve svém každodenním životě jako nedílnou součástí svého života; pokoušet se uchovat energii této Matky Země. Je to velmi důležité. Takže dnešek je dnem, kdy vysílají zvláštní modlitbu, samozřejmě, je to děláno některými církvemi, ale myslím, že je to dobrý den, protože si dnes musí myslet, že je to den Bohyně a takto o to žádali. Nechť vám Bůh žehná. Čtrnáct vdaných žen, které ještě nebyly na Mé púdži.