Shri Bhumi Dhara Puja. Shuddy Camps, Reino Unido. 3 de agosto de 1986.

Hoy nos hemos reunido aquí para hacer el Puja a la Madre Tierra. Le llamamos Bhumi Puja, Shri Dhara Puja. Ella es llamada Dhara. Como sabéis dha significa soporte. Radha, es aquella que sostiene la energía. Y Dhara es aquella donde Ella misma es el sustento, nos sostiene, vivimos sobre Ella. Como sabéis, la Madre Tierra está girando a una velocidad tremenda y sin su gravedad no existiríamos aquí. Además de esto, soporta una gran presión de la atmósfera. Ella comprende, piensa, coordina y crea. Esto solo podéis comprenderlo cuando sois un alma realizada. Habéis visto cómo absorbe vuestra negatividad cuando estáis sobre Ella con los pies desnudos, y le pedís con respeto que absorba vuestra negatividad; con una luz frente a vosotros, frente a mi fotografía. Me conoce, porque Ella es mi Madre. Podemos decir que es vuestra abuela, por eso os nutre y os cuida.

Por la mañana temprano, cuando nos levantamos y ponemos nuestros pies sobre Ella, deberíamos decir: "¡Oh Madre!, por favor, perdónanos por tocarte con nuestros pies". Pero no importa, los hijos pueden tocar a la madre con sus pies o con sus manos, no hay diferencia. Ella es la creadora del cuerpo de Shri Ghanesa y está representada dentro de nosotros como la Kundalini. Y se mueve en espiral alrededor del Sol. El Sol se mueve hacia arriba y hacia abajo. Y Ella se mueve alrededor del Sol en espiral. A causa de que sus movimientos son relativos, no veis el movimiento del Sol.

La relación entre la Madre Tierra y todas las otras estrellas, planetas, y constelaciones se mantiene en equilibrio con gran cuidado. Cuando hablamos de materialismo actuamos en contra de la Madre Tierra. En vez de aprender de sus cualidades sutiles, tratamos de explotarla, de perforarla y usarla para nuestros propósitos egoístas. ¿Qué hace Ella por nosotros? Crea estos frutos tan bellos para que comamos; crea bellos árboles para que nos hagamos muebles y buenas casas. Os da la hierba verde para relajar vuestros nervios. Lleva sobre Sí misma muchos ríos y océanos enormes. Ella siempre es más grande que el mayor de los océanos. Y con todo lo que hace por nosotros, la explotamos completamente e indiscriminadamente. Entonces hay tal reacción, que el bello ciclo de la Naturaleza se rompe a causa de nuestra actitud agresiva y absolutamente indiscriminada.

A pesar de todo, esta Madre Tierra no hace nada para salvarse, pero el éter empieza a actuar y entonces tenéis problemas con las llamadas lluvias ácidas, plástico y de esta actuación imprudente vienen todo tipo de dificultades.

Empezamos a construir máquinas sin ninguna sensatez. Como locos, y ahora como resultado de esto nos hemos vuelto esclavos de las máquinas. No podemos hacer nada con nuestras propias manos. A causa de las máquinas la gente se ha quedado sin empleo. He dicho muchas veces que las máquinas son para nosotros y no nosotros para ellas, pero hoy la situación es muy diferente. Nosotros estamos totalmente en poder de las máquinas. De nuevo el mismo comportamiento indiscriminado y el mismo desequilibrio. La Madre Tierra nos enseña el equilibrio. Si Ella no estuviera en equilibrio, nosotros no habríamos existido. Nos enseña la gravedad, cómo ser atractivos para otras personas sin que ellos se den cuenta. Sin ningún deseo de esclavizar, sin hipnotizar, sin obligar a nadie, y nos enseña a dar sin ninguna expectativa. Ella nos da sin ninguna expectativa. Nos da, aunque no la respetemos, aunque la maltratemos. Pero en ese caso Ella se siente disgustada.

Como habéis oído, en México, entró en erupción. Ya sabéis lo que sucedió allí, yo os había estado avisando desde hacía mucho tiempo. Estaban usando la magia negra y produciendo toda clase de drogas. Colombia está haciendo lo mismo y si hacéis estas cosas para dañar a la gente, entonces Ella se convierte en un volcán que entra en erupción. Como sabéis, Los Ángeles y toda la costa occidental de América está aún bajo el peligro de los volcanes. Todo tipo de gurus han ido y se han establecido allí, practican toda clase de magia negra. Hay una organización de brujas que está oficialmente reconocida y registrada allí. A nadie le importa lo que hacen, porque tenéis la libertad humana para hacer todo tipo de cosas demoníacas. En el nombre de la Libertad están haciendo todo tipo de cosas horribles. Como resultado de esto la Madre Tierra se toma una tregua. Siempre es una tregua colectiva, por favor recordadlo.

Cuando Sita quiso dejar a Shri Rama, la tierra misma se abrió y se la llevo al interior. Esta es la acogida de la Madre. Esto no es destrucción o erupción. La erupción daña colectivamente y algunas veces, incluso muere gente inocente de este modo. La muerte no existe en el leguaje divino. Aquellos que mueren pueden renacer. Pero la muerte a veces se usa para castigar a la gente, para destruirlos, para sacarlos de escena. Esto es lo que hace a veces la Madre Tierra. Su enfado puede ser tan grande que deliberadamente puede destruir a miles y miles en alguna zona de la tierra, a aquellos que han sido extremadamente irreligiosos y anticolectivos en Sahaja Yoga, también aquellos que son o intentan ser anticolectivos, son dañados por Ella pero de una forma reservada, para que aprendan. Podríamos decir de una forma muy sutil.

Cuando los sahaja yoguis empiezan a decir: "Esta es mi casa, mi hogar, mi privacidad, mi esposa, mi hijo, mi pariente, no puedo ir al puja porque tengo este problema, no puedo hacer este trabajo por Sahaja Yoga porque tengo aquel problema". Así, se vuelven anticolectivos. Entonces, de una forma sutil, esta Madre Tierra que está representada en nuestro interior como la Kundalini se enfada. Cuando se enfada empieza a actuar de un modo muy peligroso para la gente. Ser posesiva no es una cualidad de la Madre Tierra. Ella no posee a nadie. Por ejemplo si sois indio, podéis venir a Inglaterra, podéis ir a cualquier sitio, vivir en cualquier lugar. Ella no posee a nadie como tal; solo los seres humanos han dividido este mundo en diferentes países, diferentes lugares, en base a nuestras estúpidas ideas. ¡Solo hay un mundo!

Dios solo ha creado un mundo. Él no ha creado... (Shri Mataji prueba el micrófono) Ella no ha creado todas estas naciones. Solamente ha creado los valles a través de los cuales fluyen los grandes ríos. A veces hay montañas donde se ha elevado. Hay diferentes dilataciones y variedades para crear belleza. Si toda la tierra fuese como la cabeza calva de un señor, ¿qué nos habría ocurrido? En principio creo que nos escurriríamos. ¿Qué ocurriría si solo hubiese bosque por todas partes, solo montañas o solo ríos? Ella ha usado todas estas cosas para crear belleza y hacernos felices, para darnos gozo y para entretenernos. Ha creado este lugar tan bello para nosotros. ¿Y qué hacemos nosotros? La hemos dividido en partes, como: "este es mi país, este es tu país, este es su país". Al morir, ¿cuál será nuestro país? Seremos solo cuerpos muertos, tanto si sois enterrados en una iglesia o en el exterior, estaréis todos en la Madre Tierra.

Nuestro país es la Madre Tierra. Tenemos que entender que este cuerpo está hecho de la Madre Tierra a la que tiene que volver; y somos estúpidos al sentir que pertenecemos a este o a aquel país. Por supuesto este es el milagro más grande de la Maya, la gente sabe esto, pero aun así no quieren creerlo. Hay tantas verdades que la gente sabe, que les han sido mostradas y que conocen, pero aun así no quieren creerlo. Creen en ello pero no quieren aceptarlo, incluso aunque lo acepten, no quieren saber nada de ello. Es un gracioso milagro humano el hecho de que sepan que nada les pertenece. Cuando venimos a la Tierra nuestras manos están así (cerradas), y cuando nos vamos están así (abiertas) A pesar de que entendemos esto, aún jugamos con nosotros mismos, nos engañamos e intentamos creer: "yo soy de este país o aquel país, soy tan grande, tan esto o lo otro".

Pero los seres humanos nacieron en algunos países antes que en otros. Esto ha creado una diferencia en las tradiciones y en la comprensión de la vida humana. El arte permanece igual, pero esto cambia. El clima puede ser diferente y por eso algunas frutas son diferentes. Es un ajuste. Todo el plan está tan bien ajustado, sin luchas ni problemas. Es de nuevo la variedad.

Supongamos que las bananas se produjesen en todo el mundo, ¿quién se iba a preocupar por ellas? Por ejemplo, si dais bananas a los indios se reirán. Pero si les dais manzanas dirán: "¡Oh manzanas!" Con los ingleses será al revés. Si le regaláis a alguien una manzana os mirarán extrañados y dirán: "¿qué le pasa a esta persona?" Este es de nuevo su estilo de jugar, dándoos diferentes tipos de clima, diferentes productos, para que disfrutéis de cosas diferentes. Si no hay variedad, entonces, no seréis capaces de gozar. Ella nos entiende tanto, ¿y nosotros? ¿cuánto la entendemos a Ella?

Para un sahaja yogui es importante entender, que no nos vamos a llevar nada de aquí, todo esto no es más que arcilla y la arcilla permanecerá aquí y se desvanecerá para siempre. ¿Qué vamos a llevarnos y a tener con nosotros? Lo único que nos llevaremos será nuestra evolución, nuestro Espíritu. Somos el Espíritu, no somos esto, ni aquello ni lo de más allá. Lo que nosotros somos es el Espíritu y de ningún modo estamos contaminados por ninguna materia.

Deberíamos ver la esencia de la Madre Tierra y cómo usa sus métodos para dar gozo a los demás. Del mismo modo, si nosotros la usamos a Ella para dar gozo a los demás, entonces estáis siguiendo su camino. Por el contrario, si intentáis explotarla es lo mismo que hacer agujeros, o perforarla a Ella, que es vuestra Madre. Si intentáis dividirla en partes, significa que estáis cortando su cuerpo en trozos. Todos estos conceptos humanos son anti-Madre. Pero lo peor es que no respetamos a Shri Ganesha en nuestro interior, que es la creación de esta Madre Tierra.

No respetamos a Shri Ganesha que es la inocencia en nuestro interior. No respetamos la inocencia que ha venido a nosotros. La forma en que se tortura, masacra y abusa de los niños es increíble. ¿Cómo la gente no está temerosa de que algún día un gran volcán estallará en el país en el que los niños son maltratados? En ese caso la Madre Tierra destruirá a todos los seres humanos que se comporten de este modo y acogerá a todos los niños dulces en su regazo y los reproducirá en algún otro lugar.

Es importante entender que hasta que no respetemos a Shri Ganesha, a nuestra inocencia y castidad en nuestro interior, no nos podemos llamar a nosotros mismos sahaja yoguis. Esto es lo primero que hay que hacer, el primer escalón de nuestro ascenso. No podemos hablar de ninguna otra cosa hasta que estos cimientos se establezcan en la Madre Tierra. Por esta razón hoy he decidido que tengamos un Bhumi Puja en Inglaterra, espero que gracias a ello, en este país, la inocencia sea respetada, amada, protegida y alimentada. Con esto la inocencia será despertada en las personas adultas, de forma que respeten su inocencia y su castidad por encima de cualquier cosa. Con este Bhumi Puja respetamos la esencia de la Madre Tierra que es la Kundalini en nuestro interior y respetamos nuestra Realización. Espero que con lo que voy a hacer hoy podamos transformar este país en su verdadera forma, que es lo que yo llamo el Corazón del Universo. Espero que con esto la Madre Tierra derrita los corazones de piedra de este país y los convierta en bellos lotos, en margaritas fragantes.

Que Dios os bendiga.

El puja de hoy será corto, no será muy largo, será un puja a Shri Ganesha y un puja a Shri Gauri, no será muy largo. Lo único es que debéis sentaros con total atención con la mano izquierda hacia mí y la derecha sobre la Madre Tierra, la mano derecha sobre la Madre Tierra. Si estáis sentados en sillas, podéis poner la mano izquierda hacia mí y la mano derecha hacia la Madre Tierra.