Guru Puja. Cabella Ligure, Italia. 23 de julio de 2000.

Hoy estamos aquí para saber sobre el Principio del Guru. ¿Qué hace un guru? El guru descubre, para vuestro conocimiento, todo lo que tenéis, todas las cosas preciosas dentro de vosotros. De hecho, todo está ahí, todo, todo el conocimiento, toda la espiritualidad, todo el gozo están allí (en el momento justo). Todo está contenido dentro de vosotros. Lo único que hace un guru es haceros conscientes de vuestro conocimiento, de vuestro propio Espíritu. Todo el mundo tiene el Espíritu en su interior. Todos tienen espiritualidad en su interior. No hay nada que se obtenga de afuera. Pero antes de tener este conocimiento, vivís en la ignorancia. En esa ignorancia, no sabéis el tesoro que lleváis dentro. Así, el trabajo del guru es haceros saber lo que sois. Este es el primer paso, el de comenzar este despertar en vosotros, por medio del cual sabéis que no sois este mundo exterior, que es solo una ilusión, y comenzáis a iluminaros en vuestro interior. Algunas personas logran una luz completa, otras lo van logrando gradualmente.

La esencia de todas las religiones es "conócete a ti mismo". A los que pelean en nombre de la religión debéis preguntarles: "¿Te ha hecho tu religión conocerte a ti mismo?" Si todas las religiones han dicho lo mismo, el objetivo de hacer todas esas cosas debe ser conocerse a sí mismo. Sin embargo, la gente cae en el ritualismo. Creen que haciendo todos esos rituales se acercan a Dios. Viven en una ignorancia absoluta sobre sí mismos y todos los días trabajan en algo que no tiene nada que ver con el Ser. Hacen muchas acrobacias, oraciones, pujas, etc. porque hay una total ignorancia. La gente da su dinero, ellos se hacen muy ricos y solo les interesa el dinero. Quieren quitaros todo vuestro dinero y burlarse de vosotros. Hinchan vuestro ego; con ello comenzáis a desviaros hacia el océano de la ilusión y termináis ahogados en esa ilusión, creyendo que sois muy religiosos y que estáis conectados con Dios, cosa que no es cierta.

Para conocer a Dios, primero debéis conoceros a vosotros mismos. Sin esto, no se puede conocer a Dios. Es esencial que os conozcáis a vosotros mismos. Pero cuando os conocéis a vosotros mismos, vuestro conocimiento es parcial, la experiencia no es suficiente. Este conocimiento debe llegar y es el guru quien da el conocimiento sobre uno mismo. Pero vosotros tenéis que analizarlo, debéis comprobar todo lo que el guru os ha dicho. ¿Es bueno o no? ¿Es correcto o no? ¿O es simplemente una ilusión más?

En este ascenso, la gente se encuentra con muchos problemas. El primero y más importante es el problema del ego, especialmente en Occidente. El ego se infla y empezáis a sentiros muy importantes, a creer que sois mejores que los demás y que sois alguien especial. Esta ignorancia es más peligrosa que la ignorancia mundana, creo yo. Porque en la ignorancia mundana uno siente las consecuencias de los errores. Pero cuando uno está a mitad de camino, cuando la ignorancia es sobre uno mismo, cuando se está yendo a un reino superior, entonces hay que entender que no se puede tener ego.

Entonces comienza la introspección. Empezáis a miraros a vosotros mismos. ¿Qué errores hay en mí? Cuando comprendéis que tenéis ego, entonces empezáis a veros a vosotros mismos. O cuando os dais cuenta de que os falta algo o que algo va mal, también entonces empezáis a hacer introspección. Esto debería ser un esfuerzo muy honesto, muy honesto. Algunas personas, en Sahaja Yoga, desde muy temprano, empiezan a creer que son muy elevados, y que no necesitan introspección. Ascienden de nuevo hacia las nubes de la ignorancia sin alcanzar su Ser, sin lograr la Realización del Ser. Por eso, tenéis que hacer introspección y descubrir por vosotros mismos lo que habéis estado haciendo, lo que sois, hasta dónde habéis llegado.

(Por favor no traduzcáis ahora, podéis hacerlo más tarde. Debéis escuchar con completa concentración. Incluso si no entendéis, la charla tiene efecto en vosotros).

El estilo de una persona así va cambiando gradualmente. Una persona que es muy agresiva, con muy mal genio y llena de ego, empieza a volverse muy amable y suave. Otro tipo de personas, las que se asustan mucho, tienen miedos y son muy precavidas, empiezan a no tener ningún miedo. En ese estado, no tenéis ningún miedo. Estáis seguros de que vais por el camino correcto y de que os movéis en la dirección adecuada. No os sentís molestos fácilmente, pero aun así, todavía tenéis que llegar más y más alto. Hasta el punto en que, en meditación, comprendéis que algo no funciona bien en vosotros. Habéis logrado la Realización del Ser y habéis obtenido las bendiciones de ello, vuestra salud es buena, tenéis más bendiciones que las que podéis contar, todo esto os ha sucedido. Pero todavía tenéis que llegar más lejos. Todavía tenéis que comprender todo el conocimiento sobre Sahaja Yoga. Tenéis que tener esta comprensión, primero con vuestra capacidad mental y luego, tenéis que verificar hasta qué punto es correcta, hasta qué punto la habéis comprendido, hasta qué punto habéis trabajado con ella, hasta qué punto sabéis.

Cuando empezáis a veros a vosotros mismos, comenzáis a entrar en el reino del bhakti (devoción), y os volvéis una persona suave, una persona dulce, no habláis demasiado, no acosáis a nadie, sois una persona muy agradable, muy amable, muy comprensiva. Una persona así tiene que verificar cómo se está comportando hacia los demás. La atención comienza a moverse desde uno mismo hacia el otro y empezáis a ver cómo os comportáis, cómo amáis, cuál es la calidad de vuestra compasión. Cuando amáis a alguien, sin expectativas, simplemente por amor, entonces os dedicáis absolutamente a esa persona. Simplemente obedecéis. Hacéis cualquier cosa por esa persona. Hay un amor que es como una entrega. Es simplemente amor. Entrega no es otra cosa que amor. Pero ese amor da mucho gozo. Entonces comienza el bhakti (devoción). Esta dedicación comienza y el bhakti os limpia.

Todas vuestras malas cualidades o podemos llamarlas vuestras deficiencias, todos vuestros problemas, los comprendéis y superáis. Si veis a alguien con las mismas cualidades, con los mismos problemas, en el amor por esa persona, intentáis tolerarlos. Una persona así simplemente tolera, no hay agresión, y las personas así perdonan. Las almas realizadas perdonan siempre, su capacidad para perdonar es tremenda. No guardan ningún rencor contra nadie. No se enfadan con nadie. Simplemente toleran y perdonan todo el tiempo a todos. Este perdón es como la música de vuestro bhakti. La cantidad de perdón que estos maestros pueden tener, la podéis ver en la vida de Cristo. Se le torturó, se le crucificó. La mayoría de los santos fueron torturados. A la gente no le gustan. Y los crucificaron. Pero, como sabéis, nunca guardaron resentimiento, nunca se vengaron, nunca hicieron nada que no fuera compasivo.

Tenían compasión y en su compasión por aquella gente, sintieron y le pidieron a Dios que perdonara a sus agresores, porque no sabían lo que estaban haciendo. Eran extremadamente compasivos. Y eran así, esa era su naturaleza. Cuando expresan su auténtica naturaleza, se vuelven gente con una paz absoluta. No se sienten perturbados por nada de lo que esté sucediendo, piensan que todo es la voluntad de Dios. Nada les puede perturbar, nada consigue molestarles. Simplemente gozan de su devoción, de su devoción hacia su guru y hacia Dios. En esa devoción quizá escriban hermosa poesía, o puede que bailen o que canten, porque tienen paz en su interior y gozan. Cuando están solos, nunca están solos, gozan. Saben que somos uno con el Divino y disfrutan de la bendición del Divino.

Otro aspecto es que nunca adoptan actitudes artificiales, nunca están preocupados, nunca afectados, no se proyectan al futuro ni piensan en el pasado, sino que están en el presente. Cuando están en el presente, están absolutamente en silencio. Si hay algún problema o algo les sucede, se quedan en consciencia sin pensamientos inmediatamente. Esta es su capacidad. Para convertiros en un guru, vosotros debéis desarrollar una personalidad así. No sentiros atados por nada. Os pondré el ejemplo de mí misma. Yo nunca tengo prisa, no me preocupo de los asuntos de la vida. Una vez yo iba a viajar a América. Si estáis seguros de que el Divino tiene planes para vosotros, entonces no os preocupáis. El Divino os está cuidando, entonces, ¿de qué hay que preocuparse?

Yo iba a viajar a América y una niña se cayó. Yo me estaba levantando para irme, cuando ella se rompió el brazo. Cuando la vi, dije: "Voy a ayudar a la niña". Me dijeron: "Pero te tienes que ir a América". Yo dije: "Iré, en cualquier caso". Curé a la niña, lo que me llevó aproximadamente media hora, y salí y les dije: "Vámonos al aeropuerto". Me dijeron: "Pero Madre, llegarás muy tarde". Respondí: "Yo nunca llego tarde. ¡Vámonos!" Fuimos al aeropuerto y el avión que se suponía que iba a coger se había estropeado. Habían puesto otro vuelo a Washington, no a Nueva York, pero en realidad yo quería ir a Washington. Ved cómo las cosas funcionan, de una forma que llamamos "sahaja". Decimos "funcionó de forma sahaja". Es decir, que fue sin esfuerzo. Pero antes que nada, vuestra personalidad debe ser tal, vuestra devoción debe ser tan grande, que el Divino se vea obligado a cuidar de vosotros.

Debéis comprender que la Fuerza del Divino está a vuestro alrededor, y que esta Fuerza divina es la garantía absoluta de vuestra seguridad para cualquier cosa que queráis hacer. Quizá digáis: "Madre, es que Tú eres muy poderosa". Vosotros también podéis volveros muy poderosos. Si os dedicáis completamente al trabajo del Divino, también vosotros tendréis todos los poderes y el Divino os proveerá de todo lo necesario para el trabajo que queráis hacer, de todo el tiempo que necesitéis, todo os los proveerá el Divino.

Cuando la compasión se extiende, de otras personas hacia Dios o hacia alguien divino, o hacia vuestro guru, entonces vivir se convierte en algo muy simple, muy sencillo, no hay complicaciones, todo se soluciona, y nada os preocupa. Simplemente cerráis vuestros ojos, y las cosas salen bien. Todo funciona de acuerdo a vuestra voluntad, pero no tenéis que desearlo, no tenéis que pensar sobre ello, simplemente funciona y el Divino cuida de todo. Cuida de vuestro confort, de vuestra salud, de todo.

Pero esta ayuda divina vosotros no la buscáis, no la pedís, sino que sois una personalidad de la que el Divino es responsable. Sois una responsabilidad especial del Divino. Y Él sabe lo que es bueno para vosotros y lo que no. Un ejemplo, aunque puedo dar muchos, es cuando alguien me va a venir a visitar y la gente me dice que es alguien muy negativo. Al final esa persona nunca llega. Todas las cosas positivas suceden y si alguna vez sucede algo negativo, entonces usad vuestra compasión. Si es algo negativo, usad vuestra compasión y resolveréis el problema. Podéis solucionar vuestros propios problemas, los que están a vuestro alrededor, los de vuestra comunidad.

Ahora todos tenéis vuestra Realización del Ser. No sé lo lejos que habéis llegado en ella. He recibido quejas de que las mujeres no meditan, y de que no se están cuidando, de que no son almas realizadas. Por eso muchos hombres se quieren divorciar, porque piensan que sus mujeres no valen para nada. Algunos hombres también son así. Para solucionar este problema, tenéis que tener compasión. Y con compasión, tenéis que conquistar a vuestro compañero o compañera en la vida, ganándoos su voluntad. Después de todo, los hombres están mucho más ocupados que las mujeres. Pero las mujeres se dedican a muchas otras cosas. Tienen que cuidar a la familia, a los niños, etc. y su mente se involucra tanto en todas esas cosas mundanas que no tienen tiempo de meditar. Sin meditación no podéis ascender. Tenéis que meditar. La gente cree que ahora, como ya tenemos la Realización, ya no hay que hacer nada. No es así, todos los días debéis meditar, porque entonces se produce vuestra limpieza. Con la limpieza comprendéis lo que no necesitáis, y os limpiáis. Eso lo hace el Divino, pero vosotros debéis meditar religiosamente.

Gradualmente veréis que vuestra meditación se hace muy profunda, os volveréis personas muy profundas y vuestros poderes comenzarán a manifestarse. Donde vosotros estéis, la negatividad huirá. Todos los problemas tendrán solución. Todo lo que queráis hacer, lo podréis hacer. Todo lo que deseéis para ayudar o para darlo a los demás, simplemente lo tendréis. Esto es algo que he experimentado yo misma. Tenéis que meditar al menos diez minutos por la noche, y al menos cinco por la mañana. Con completa devoción, con completa admiración. He visto a algunas personas aquí con una gran devoción o bhakti tanto que es más bien shraddha (fe), algo más elevado que el bhakti, y que se vuelve una parte de vuestro Ser. Simplemente os envuelve completamente. Cuando tenéis esa shraddha o fe todo es algo milagroso, suceden muchos milagros.

Es cierto que algunas personas se han curado solo con pensar en mí, es un hecho. Pero eso no quiere decir que tuvieran una shraddha o fe de un nivel muy elevado, sino que tenían que desarrollarla. ¿Cómo se puede desarrollar la fe o shraddha, que es la luz natural del Espíritu? La gente trabaja mucho para intentar desarrollarla. Pero esta no se puede desarrollar por medio de actividad mental ni por ninguna otra actividad que no sea la meditación, el silencio. Haced meditación, siempre os digo que meditéis. Yo sé inmediatamente qué persona ha estado meditando y quién no. Vienen al puja, hablan de Sahaja Yoga, saldrán buscando popularidad, hay mucha gente así. Trabajan exteriormente buscando popularidad, pero interiormente no han hecho crecer a su propio Ser.

En esta etapa de vuestro desarrollo, deberías tener mucho coraje y entender que podéis alcanzar ese estado muy fácilmente, por medio de la meditación y de la introspección.

Con la introspección, desarrollaréis una nueva cualidad de entendimiento, que es la de encontrar soluciones a las cosas. Esta es otra cualidad que tiene una persona realizada. Puede encontrar soluciones a todos los problemas. Puede sugerir de qué forma se puede ayudar. Así se desarrolla una especie de hermandad, como consecuencia de esta shraddha. Puede que deis grandes conferencias sobre Sahaja Yoga, que estéis haciendo todo tipo de cosas, pero a menos y hasta que tengáis shraddha o fe, no podréis ascender. Esta shraddha es una especie de amor en vuestro interior, que se extiende, como un fuego amable que no quema, que no da calor, sino que refresca, queda un sentimiento interior de hermosa dicha, y que os hace comprender.

Nunca hablaréis mal de un sahaja yogui, nunca. Hasta cierto punto, yo nunca escucho a nadie que me hable en contra de los sahaja yoguis. Si se trata de una queja colectiva, entonces me intereso un poco y hablo de ello con el líder. Pero si no, cuando alguien viene a decirme cosas así, yo solo le digo que haga introspección él mismo. Encontrar fallos en los demás es un juego muy practicado por los seres humanos. Nunca ven sus propias faltas. ¿De qué sirve encontrar errores en los demás? Ver los fallos de los demás no va a ayudaros a vosotros. Intentad encontrar fallos en vosotros mismos, fallos que podáis corregir, para ayudar a que se solucionen. Debéis saber que esta es una responsabilidad que tenéis hacia vosotros mismos, la de encontrar vuestros defectos y corregirlos.

Algunas personas se sienten muy orgullosas de sus gustos. Dicen: "A mi me gusta esto, o aquello..." Pero, ¿y el Espíritu? Os gusta tal y tal cosa pero, ¿le gustan esas cosas a vuestro Espíritu? ¿Goza él de ellas? Luego también dicen: "Esto y esto no me gusta". Es algo muy común en Occidente. Pero, por ejemplo, estas alfombras las han hecho unas mujeres. Son tan gruesas, que cuando camino sobre ellas pierdo un poco el equilibrio. Pero las han hecho con tanto amor que me producen mucho gozo, me hacen tan feliz, que no podéis imaginar lo que siento al respecto.

Este gozo, este océano de gozo, está dentro de vosotros. Y cuando comienza a removerse, no os atormenta, sino que os produce algo, no sé qué palabras utilizar para describirlo, es como una hermosa llovizna sobre vuestro Ser. Es como Gracia sobre vosotros. El amor de las otras personas os encanta, vosotros no lo pedís, pero si veis a alguien que es muy amable y amoroso, entonces hay verdadera amistad en vuestra relación.

Hablar mal de los Sahaja Yoguis es algo muy malo. Y contar a todo el mundo los errores de otra persona, lo que hizo y lo que no hizo, está muy mal. Crea un sentimiento colectivo en contra de la persona, en vez de ayudarla. Siempre que la gente tiene problemas, hay que ayudar a la persona colectivamente, no hablar mal de ella. Quizá haya cometido algún error, pero si empezáis a hablar en su contra y a contar todos sus defectos, entonces no sois un sahaja yogui. Sois un sahaja yogui siempre y cuando podáis ver vuestros propios defectos a través de la introspección.

La mayoría de vosotros habéis tenido vuestra Realización y la habéis experimentado. Pero algunos de vosotros no tenéis el conocimiento. Tenéis que adquirir ese conocimiento y verificar si está ahí realmente o no. En América, en el NIH, el Instituto de la Salud, quisieron poner a prueba a una sahaja yoguini. Había varios médicos. Uno de ellos le dijo a la sahaja yoguini: "Dime cuál es mi problema, según las vibraciones". La chica dijo: "Hay algún problema en el corazón". Él dijo: "Es correcto", porque le habían puesto un by-pass apenas hacía un mes, y había salido del hospital. Absolutamente correcto. Les sorprendió ese diagnóstico, porque recorre la mitad del camino en la curación de un paciente. Esta es una forma muy simple de diagnosticar, simplemente por medio de sentir las vibraciones. Nos han atendido muy bien, y quieren desarrollar Sahaja Yoga en los hospitales.

Por eso, vosotros también tenéis que responder por vosotros mismos, examinaros y averiguar cuál es el problema. Por ejemplo, en la relación marido–esposa. La esposa medita, lo sabe todo, conoce cuál es el problema del marido. Pero ella no le dice nada. Ella tolera, no se queja, no pide nada, simplemente tolera. Y esta tolerancia convence al marido de que ella está más elevada que él mismo. Sea como sea él, comprende que ella ha logrado una gran personalidad.

Tenemos muchas imperfecciones. Especialmente en Occidente, a nivel moral la gente está como si le hubiera picado una serpiente. Lo que se hace aquí ni se le pasa por la cabeza a la gente menos desarrollada. Por eso, el desarrollo ha traído todo tipo de abandono, un temperamento de vagabundos. Pero ellos creen que son muy libres, que pueden hacer lo que quieran y divertirse. Este estilo es muy común, pero vosotros juzgaos a vosotros mismos: "¿Soy yo uno de ellos o soy uno de los que se han superado en su ascenso?" Es un proceso que tengo que poder asumir. No es que se alcance ese nivel automáticamente.

A veces, algunos sahaja yoguis que son muy nuevos son mejores que algunos sahaja yoguis antiguos, porque tienen un deseo muy fuerte. ¿Qué estamos buscando? Debemos entender por qué estábamos buscando. Porque queríamos conocernos a nosotros mismos. De alguna forma sabíamos que teníamos que conocernos a nosotros mismos, pero no sabíamos cómo. Entonces buscamos y hacemos todo tipo de cosas, incluso cosas erróneas, en nombre de esa búsqueda. Pero esta búsqueda os trae a Sahaja Yoga. Después obtenéis vuestra Realización de una forma muy fácil, gracias a la Kundalini. La Kundalini hace la mayor parte del trabajo.

Alguien me contó que de un día para otro, había dejado la bebida y el tabaco. ¡De un día para otro! Yo nunca os pido que dejéis cosas, pero en un solo día lo logró. Ella también me contó que era muy quisquillosa con el pelo, que siempre cambiaba de peinado, iba a la peluquería, pasaba mucho tiempo en el salón de belleza, etc. Y lo dejó todo. También se ponía vestidos que no eran muy morales, pero empezó a respetar su cuerpo y a vestirse de forma adecuada. Todo este conocimiento os llega. Está dentro de vosotros espontáneamente, porque os pertenece. También, cuando vuestro Guru os habla os está guiando. El trabajo del guru es guiar a la gente.

En este punto, ¿qué falta en Sahaja Yoga? Esto os lo tengo que decir. Se están produciendo muchos desastres colectivos, de todo tipo. Tenemos terremotos, inundaciones, lluvias, desprendimientos de barro, tantos desastres en el mundo. Pero los sahaja yoguis están a salvo. Todos los sahaja yoguis están a salvo de esto, sin duda. Pero, después de estar a salvo, ¿cuál es vuestro entendimiento? ¿Qué sabéis vosotros sobre por qué suceden estos desastres?

La razón es que Sahaja yoga no es muy colectivo. Tiene que volverse muy colectivo. Tiene que expandirse mucho más, por todas partes. Tiene que llegar a mucha más gente, a la que no ha llegado todavía. Estamos estancados, aunque trabajamos un poco. ¡Salid todos a esta tarea! Mirad a los discípulos de Cristo. Por supuesto la gente tomó caminos erróneos, pero ¡cuánto trabajaron, con qué intensidad lo hicieron! Si no tenéis esa intensidad, y si no os dedicáis completamente a expandir Sahaja Yoga, entonces los problemas colectivos no se pueden solucionar.

Estáis ocupados solo con vuestra vida diaria y mundana, con vuestros trabajos, etc. Está bien, en Sahaja Yoga no se pone ninguna objeción. Pero vuestra atención debería estar más sobre este aspecto de la vida, sobre qué hacemos por el colectivo. ¿Estamos hablando de ello? ¿Estamos extendiendo Sahaja Yoga? ¿Estamos dándolo a conocer a la gente? Me quedé sorprendida una vez al viajar en avión. Junto a mí se sentó una señora que tenía muy malas vibraciones. Yo me di un bandhan y le pregunté sobre qué estaba haciendo por su espiritualidad. Y ella me nombró a "Bahai".

Yo pensé: "Oh, Dios mío". ¡Cuánto se ha extendido esta gente! Se han extendido tanto, son tantos que, entonces, ¿qué sucede? Desastres. Son gente tan negativa que es imposible que puedan hacer nada bueno al mundo. Igualmente, veis cómo la gente es conducida hacia cualquier falso guru, cómo la gente se adhiere a ellos y cómo expanden su mensaje. He visto a gente cantando en la calle, cantando alabanzas a su guru, y poniéndose vestidos raros. Nosotros no queremos eso. Vosotros por supuesto tenéis el conocimiento. Por supuesto sois almas realizadas. Pero, ¿qué habéis hecho por Sahaja Yoga? Esa es la cuestión.

Tenéis que expandir Sahaja Yoga en todas partes. Por ejemplo, llevando una chapa. La gente os preguntará en qué consiste eso. Entonces debéis explicárselo. Haced algo, pero comenzad a hablar de Sahaja Yoga. Y no habléis de otra cosa que no sea Sahaja Yoga. Tenéis que hablar todo el tiempo de Sahaja Yoga, extenderlo todo el tiempo. A menos y hasta que hagáis esto, Sahaja Yoga no será colectivo y todos los desastres, que son debidos al sin sentido colectivo, seguirán ocurriendo.

Vosotros estáis a salvo de muchas cosas. Incluso de la contaminación, esto no importa para un sahaja yogui. Incluso si hay un terremoto, un sahaja yogui estará a salvo. Pero, ¿por qué no salvar al mundo entero? Suceden calamidades una tras otra, y si tenéis compasión, debéis pensar en aquellos que pueden sufrir cualquier tipo de calamidad. Yo sin duda puedo curar a mucha gente, pero no sé cómo hacer que Sahaja Yoga sea algo muy colectivo. Ahora sois muchos y todos podéis empezar a dar la realización a al menos cien personas cada uno. Id a todas partes, hablad de Sahaja Yoga, cantad la alabanza del Divino, y salvaréis a todo el mundo. No es por salvar a unos pocos que alcanzaréis el gran Sattya Yuga, sino que también tenéis que salvar a esta Madre Tierra. Tenéis que salvar a los que viven en Ella.

La forma en que la gente habla sin vergüenza hasta en la televisión, de cosas de las que no saben nada. Y tienen miles y miles de seguidores. Y no es que la gente sea tonta, no es que quieran coger el camino equivocado, lo que sucede es que esta gente falsa sabe cómo encandilarlos, cómo capturarlos, cómo hablarles. Pero los sahaja yoguis, si se encuentran con alguien que tiene malas vibraciones, saldrán corriendo, no se le acercarán, escaparán diciendo: "Es que tiene muy malas vibraciones". Por eso, debéis ser fuertes, entrar en estos lugares, hablar a la gente y hacer de Sahaja Yoga algo colectivo. De otro modo, no podéis salvar a este mundo de la ira de Dios. Dios tiene ira, sin duda, a vosotros os salvará pero, ¿de qué servirá? Tenemos que salvar a esta Madre Tierra, y para ello debéis estar preparados. Tenéis que hacer que funcione. Y donde haya una posibilidad, debéis extender Sahaja Yoga.

Algunas personas me dicen: "Madre, si Tú vienes, funcionará". ¿Por qué? ¿Por qué tiene que ser así? Vosotros también podéis ser como yo. Podéis hablarle a la gente. Comencé Sahaja Yoga con solo una persona, y en aquel tiempo había completa oscuridad alrededor. No había buscadores, nada, solo gente horrible, pero funcionó y lo logré. Por tanto, si una persona puede conseguir tantos sahaja yoguis, ¿por qué vosotros no podéis hacer lo mismo y hablar de ello? Vuestro comportamiento, vuestro estilo, definitivamente todo les impresionará.

Hay que hacer que funcione de tal forma que alcancemos nuestra meta de consciencia colectiva. Esto no es solo para los sahaja yoguis, es para todo el mundo, para que todas estas calamidades que suceden, todas estas cosas horribles, dejen de ocurrir completamente. Os aseguro que pueden cesar. Vosotros siempre estáis a salvo, y todos los que reciban su Realización estarán a salvo. Entonces, ¿por qué no hablar abiertamente de ello diciéndole a la gente que si hacen cosas erróneas, si somos inmorales, si engañamos o intentamos oprimir a los demás y nos convertimos en un poder destructivo, entonces se producirán estos desastres colectivos, y nosotros seremos responsables de ello?

No hace falta crear una organización para defender cualquier cosa que queráis hacer o cualquier tema que queráis tratar. Será solo vuestro poder de convencer a la gente y de traerlos a Sahaja Yoga lo que marcará la diferencia.

Espero que comprendáis como gurus lo que debéis hacer. Como guru tenéis muchas cosas, como vuestro carácter. Ayer nos mostraron cómo Lao Tse escribió sobre los maestros. ¡Cómo estaban ellos por encima de todo! Por encima de las revueltas, de los celos, de los chismes. Ellos son grandes personalidades, son los maestros y serán los maestros. Y vosotros seréis los gurus si intentáis ser así.

Eso es lo que tenéis que lograr. Sé que algunos ya lo han alcanzado, pero la mayoría de vosotros tenéis que lograrlo con compasión y amor.

Que Dios os bendiga.