Guru Puja, Twórczość, 23.07.1989 Lago Di Braies, Włochy

Dzisiaj musieliśmy spędzić trochę więcej czasu niż zwykle, by osiągnąć poziom, gdzie możemy naprawdę czcić Guru.

Kiedy czcimy naszego Guru, musimy wiedzieć, że rzeczywiście staramy się obudzić zasadę Guru w nas samych. Chodzi nie tylko o to, że jesteście tutaj, aby czcić swojego Guru. Możecie oddawać cześć bardzo wiele razy, być może wibracje będą płynąć, być może poczujecie się nimi napełnieni i poczujecie się uwzniośleni i odżywieni. Ale te wartości odżywcze muszą zostać zachowane

w nas samych.

Więc zawsze pamiętajcie, że ilekroć oddajecie cześć jakiejś zasadzie na zewnątrz, staracie się czcić swoją własną zasadę w sobie. Jak wiecie, w nas, w każdym z nas, znajduje się Zasada Guru. Bardzo interesujące jest zobaczyć, jak Zasada Guru przepięknie otacza czakrę Nabhi. Nigdy nie widzimy żadnych czakr połączonych z zasadą Guru. Widzicie Nabhi, a wokół jest Bhavasagara. Zatem ten Bhavasagara, który jest Oceanem Iluzji, nie może być Guru.

Ale istnieją ukryte czakry wewnątrz tego Bhavasagary, które mają zostać obudzone i wydobyte na światło dzienne, aby się objawiły. Jak możecie zobaczyć, granice tej zasady wynikają z ruchu czakry Swadisthana. Swadisthan jest tą czakrą, która daje wam przede wszystkim kreatywność. Osoba będąca Guru musi być twórcza z natury. Jeśli nie jesteście osobą kreatywną, nie możecie zostać guru.

Na przykład, macie do czynienia z uczniami, z którymi musicie rozmawiać. Musicie wykreować słowo boskiej magii, aby wywrzeć wrażenie na uczniach lub ludziach, których przyciągacie do siebie jako guru, aby pokazać, że macie o wiele więcej boskiej magii niż oni. Jeśli jesteście osobą bardzo przyziemną, bardzo pospolitą, to nie możecie stworzyć przepięknego kupletu czy pięknej wypowiedzi, albo dowcipu lub żartu, czy też pięknego obrazu lub pięknego gobelinu, ani pięknego domu. Jeśli brakuje wam kreatywności, zabraknie wam Zasady Guru, ponieważ guru musi tworzyć ze zwykłych ludzi coś niezwykłego. On musi być w stanie stworzyć nową osobowość ze starej osobowości, która jest w stanie rozkładu.

Więc pierwszą zasadą, którą musicie zrozumieć wewnątrz siebie jest to, że powinniście być w stanie stworzyć nową osobowość w człowieku. Jak to robimy? Oczywiście, macie moce, by unosić Kundalini, macie moce by uzdrawiać ludzi, macie moce mówienia o sprawach istotnych i nieistotnych. Pomimo tego wszystkiego, jeśli nie potraficie stworzyć nowej osobowości u ludzi, którymi się zajmujecie, to nie jesteście guru. A ta nowa osobowość musi być wyjątkową osobowością, która stanowi unikalne połączenie współczucia i dynamizmu.

Dlatego ważne jest, aby w swojej kreatywności używać energii współczucia. Możecie kształtować ludzi wyłącznie za pomocą współczucia, nigdy przez gniew, nigdy poprzez represje, nigdy poprzez popisywanie się mocami "wielkiego guru". Dopóki nie zajmiecie się sytuacją i osobowością bardzo ostrożnie, okazując pełen szacunek, okazując całą troskę i całą miłość osobie, której dajecie Realizację. Popisywanie się, że jesteście wielkim guru, wywoła wyłącznie coś w rodzaju strachu przed wami a po jakimś czasie ludzie nie będą chcieli oglądać waszych twarzy. Zatem najważniejszą rzeczą w Zasadzie Guru jest to, że musicie tworzyć.

Wielu ludzi dostaje Realizację, w porządku, oni dostają Realizację a potem być może mieszkają

w ashramach. Oni chodzą na puje, słuchają muzyki, może tańczą, śmieją się, są kolektywni, ale mimo to ich Zasada Guru nie jest obudzona dopóki nie stworzą wielu, wielu nowych Sahaja yoginów. Zatem wizja guru powinna brzmieć: "Ilu Sahaja yoginów zamierzam stworzyć? Jak zamierzam wykorzystać tę kreatywność, aby stworzyć więcej Sahaja yoginów?"

Zatem, chociaż podstawą czy istotą czakry Swadisthana jest estetyka, to siłą i energią czakry Swadisthana jest uwaga. Jeśli macie chwiejną uwagę, jeśli wasza uwaga jest w jednej minucie tu

a w następnej minucie tam, jeśli macie uwagę, przez którą możecie tylko krytykować innych i nie widzicie własnych błędów; jeśli macie uwagę, przez którą pokazujecie ludziom, że jesteście osobą niepoważną, bezsensowną, wtedy wasza Zasada Guru jest zmarnowana. Jest to wysiłek Sahaja Yogi, który jest zmarnowany, i praca waszego Guru jest też zmarnowana. To jest absolutne minimum, najpierw uwaga musi być czysta. Ale czysta uwaga nie oznacza szorstkości, nie oznacza ascetyzmu, to nie oznacza dyscyplinowania oczu klapkami jak u konia, lecz w całkowitej wolności wasza uwaga [powinna] być skoncentrowana.

Czemu poświęcamy najwięcej uwagi?

Jeśli jesteśmy uczciwi, możemy myśleć na poziomie ludzkim, poświęcamy uwagę swoim dzieciom, swojej żonie, swoim mężom, swojej rodzinie, relacjom związanym z miłością. Zatem wtedy, gdy wasza uwaga zawiera współczucie i miłość dla drugiej osoby, tylko wtedy możecie wypracować Realizację innych. Jeśli macie wypracować Realizację innych, to musi być ogromna miłość do drugiego człowieka. Jeśli nie macie tej głębi, a tylko ruszacie rękami, żeby podnieść Kundalini, bo wasza Matka dała wam moce - to koniec. Tylko ta głębia miłości może przynieść wam sukces wraz z waszą czystą uwagą i myślę, że tylko czysta uwaga może kochać. Nieczysta uwaga nie może kochać, gdyż cała nieczysta uwaga jest ukierunkowana na siebie, na własne "ja". Nie jest skierowana na "Jaźń" w sensie duchowym. Ale idea, że duchowość jest miłością, wydaje się być nową dla wielu ludzi. Oni sądzą, że duchowość oznacza osobę, która jest całkowicie wysuszona jak łodyga fasoli i nikt nie może zbliżyć się do tej osoby, nikt nie może się komunikować z taką osobą, ponieważ ta osoba jest "zbyt czysta". Jeśli mydło nie może oczyścić ciała, jaki jest pożytek z posiadania mydła? Jeśli mydło boi się zbliżyć do ciebie, wtedy lepiej nie nazywać się mydłem.

Tak więc doszliśmy do punktu, że twórczość, jeśli jest ona naszym celem, lakshya, dla niej uwaga musi zostać oczyszczona a oczyszczona ma być przez miłość, przez współczucie. I ta sama uwaga, gdy jest przepełniona miłością i współczuciem, daje wam dynamizm, daje wam siłę, daje wam niestrudzony zapał. A radość z ujrzenia swojego odbicia w drugim człowieku jest bardzo piękna. Żadne słowa nie potrafią tego opisać. W rzeczywistości, kiedy dajecie Realizację innej osobie, tym, co staracie się zobaczyć, jest wasze własne odbicie w tej osobie, tak jakbyście ze zwykłej szyby robili piękne lustro, i wtedy chcecie w nim to zobaczyć.

To w ten sposób tworzycie, tworzycie swoje własne odbicia i poprzez oczyszczanie reflektorów, zrozumiecie, że bez kreatywności ta Guru Puja jest bezużyteczna dla was. Jeśli żyjecie tylko dla siebie, dla swojej rodziny, dla swojego męża czy tylko dla ashramu, to w ogóle nie rozwinęliście się, nie wypełniliście żadnego obowiązku wobec swojego Guru. Oczywiście, jak tylko przyjmiecie tę zasadę, rozwiniecie tak wiele przymiotów wewnątrz was. Pierwszym, który rozwiniecie, jest mądrość, ponieważ zdajecie sobie sprawę, że zmierzacie w złym kierunku, dlaczego to nie działa, dlaczego jest problem, dlaczego wasza kreatywność nie działa.

Staje się to dla was widoczne i oczywiste, i zaczynacie się uczyć a mądrość przychodzi do was

i zaczynacie rozumieć. Mądrość jest wtedy, gdy zdajecie sobie sprawę ze swoich błędów i naprawiacie je. A razem z tym rozwijacie równowagę i zrozumienie, jak postępować z drugim człowiekiem.

Zawsze opowiadam historię o samochodzie, jest tam gaz i jest również hamulec. Na początku musicie używać obydwu nie rozumiejąc, co to takiego, jeszcze nie jesteście Guru, nawet nie jesteście kierowcą. Potem, kiedy umiecie, wtedy prowadzicie automatycznie; wtedy jesteście kierowcą, ale nadal mistrz siedzi z tyłu. Więc teraz musicie stać się mistrzem, a kiedy staniecie się mistrzem, możecie panować nad pojazdem i możecie widzieć kierowcę, gaz a także hamulec. I możecie po prostu nim kierować w bardzo prosty sposób. Tak więc Zasada Guru jest ograniczona i przesuwa swoje granice jak [linia] horyzontu. Kiedy zaczyna wzrastać wasza kreatywność, tym więcej ludzi tworzycie.

A centralnym punktem tego jest Nabhi, jest centrum, które jest jak wielki kluczowy punkt, wokół którego cały ten ruch ma miejsce. Czakrę Nabhi, jak wiecie, dostaliście od swojej matki na początku. Zatem Guru musi być matką. Musi posiadać przymioty Matki, nie współczesnych matek, lecz w prawdziwym znaczeniu tego słowa. Czyli Guru musi kochać swoje dzieci i musi mieć siłę i odwagę, by swoje dzieci korygować. A najszczerszym pragnieniem powinno być kierowanie dzieci we właściwą stronę, prowadzenie ich, pomaganie im we wzrastaniu. Zatem pierwszy pokarm przychodzi do nas nawet kiedy jesteśmy w łonie matki - poprzez matkę, tak też wy jesteście matką, niezależnie czy jesteście mężczyzną lub kobietą, ale pod względem jakości jesteście matką. I cokolwiek myślicie lub cokolwiek robicie - ma to wpływ na dziecko. To, jak się zachowujecie, jak mówicie, sposób w jaki żyjecie, wszystko to ma wpływ na rozwój dziecka. Podobnie, gdy przypuśćmy, Sahaja yogin, który próbuje dać Realizację, jest hipokrytą, jeśli jest niewłaściwym typem osoby, jeśli nie szanuje swojego własnego Guru… dzieci będą zachowywać się w ten sam sposób i przejmą złe rzeczy dużo szybciej, najpierw widzą złe rzeczy.

Toteż powinniście być doskonali w waszym zachowaniu wobec swojego własnego Guru, musicie w pełni szanować swojego Guru. Całkowite poddanie się swojemu własnemu Guru jest ważne; wtedy zobaczą, jak potraktowaliście swojego własnego Guru, i właśnie tak będą was traktować. Jeśli wy nie odnosicie się do swojego Guru z takim szacunkiem, z takim zrozumieniem, z takim oddaniem, to nie spodziewajcie się, że wasze dzieci albo ludzie, których prowadzicie, będą respektować was.

Zatem ta cecha Guru w nas musi być jak wielki mędrzec czy wielki wizjoner, który znajduje się wyżej niż normalni przyziemni ludzie i widzi rzeczy we właściwej perspektywie i przynosi swoim uczniom właściwe zrozumienie tej całej perspektywy, którą widzi, nie daje im wypaczonych ani niewłaściwych idei. Ktoś mógłby powiedzieć: "Matko, w jaki sposób mamy wyrażać miłość, a także przekazywać im Prawdę?" Musicie troszczyć się o ich dobro - hitha. Musicie dbać o dobro waszych uczniów, Może się zdarzyć, że komuś nie spodoba się to, co dzisiaj mówicie tej osobie. Ale przyjdzie dzień, gdy on pomyśli: "Dzięki Bogu, że mój Guru poprawił mnie i naprowadził mnie na właściwą drogę". Jeżeli celem ucznia nie jest wzrastanie, tylko bycie tam dla jakiegoś [innego] celu, wtedy lepiej jest nie mieć takich uczniów. Nie mieć nikogo takiego, kto nie jest zainteresowany swoim wzrastaniem, lecz innymi zyskami, które nie przynoszą absolutnie żadnego pożytku.

Czasem pojawia się to pytanie: "Jak kochać?" To bardzo zabawne pytanie, że nie wiemy jak kochać istoty ludzkie. Umiemy kochać nasze rzeczy, umiemy kochać nasze bezużyteczne przedmioty, umiemy kochać jakiś piękny widok, ponieważ to daje nam radość. umiemy kochać jakąś miłą restaurację, bo można tam dostać dobre jedzenie albo pewnego rodzaju rzecz, która jest bardzo przyziemna. Ale miłość dla samej miłości jest taka, że gdy naprawdę kochacie dla miłości wówczas staracie się wpoić lub zaszczepić tę miłość w kimś innym tak, że czynicie tę drugą osobę równie godną miłości, jak wy sami. Cały system staje się inny, jeśli rozumiecie że musimy oprzeć na miłości cały swój rozwój, wszystkie nasze działania, wszystkie nasze zachowania, całe nasze rozumienie. W przeciwnym razie nasza Zasada Guru jest niezwykle słaba, i po jakimś czasie zauważycie, że znajdujecie się poza granicami Sahaja Yogi.

Każdy, kto jest przywiązany lub stronniczy i ma uwarunkowania, nie może stać się Guru, nie może, ponieważ, nawet jeśli zostanie tak zwanym [guru], wszystkie te rzeczy znajdą odzwierciedlenie w tej osobie. Także jeśli ktoś jest pełen ego, myśli bez końca o sobie, i myśli: "Ja jestem wielkim Guru" to jego ego również się przejawi. Jeśli na przykład taki "guru" za dużo mówi, to znajdzie podobnych sobie uczniów.

Jeśli jest spokojny, znajduje uczniów o podobnym usposobieniu. Zatem dochodzimy do wniosku, że najpierw musimy rozwinąć naszą własną Zasadę Guru. Jeśli nie możemy jej rozwinąć, nie ma sensu robić żadnej Guru Pujy, ponieważ jest to tylko tymczasowe, zbytnio wam to nie pomoże, dopóki rzeczywiście nie postanowicie, że będziecie odżywiać, rozwijać i ugruntowywać waszą Zasadę Guru. Zatem dzisiaj, gdy czcicie Mnie jako Guru, musicie wiedzieć, że jak wiele bym nie mówiła, jak wiele bym nie dała błogosławieństw czy cokolwiek, to nie zadziała, dopóki rzeczywiście nie rozwiniemy naszej własnej Zasady Guru oraz głębi. Ponieważ guru sprawia, że jego uczeń przekracza Bhavasagarę [ocean iluzji], on jest jak łódź, która zabiera uczniów i przepływa z miłością i z właściwym ukierunkowaniem. Tak powinno być z każdym z was. Gdy tak jest, wszyscy jesteście Zrealizowanymi Duszami i jak wam powiedziałam, wszyscy jesteście aniołami. Ale jeśli nie ustanowicie swojej Zasady Guru… wiecie o aniołach, jak one upadły i przepadły na zawsze. Zatem bądźcie ostrożni - łatwo jest być aniołem, ale trudno to utrzymać. Trudno jest być Bogami i Boginiami, ale łatwo to utrzymać.

Więc wszyscy jesteście tutaj. Jestem bardzo szczęśliwa, widząc że przybyliście, aby czcić Mnie jako waszego Guru, i oczekiwałabym, aby Moje dzieci były podobne do Mnie. Aby Mój wizerunek był taki, by Moje dzieci czuły tę Jedność z Moim wizerunkiem, i żebym była Matką, dumną z tak wielu dzieci, które przybyły z tak wielu krajów.

Niech was Bóg błogosławi.

Teraz z tak wieloma ludźmi tutaj, tak wieloma dziećmi tutaj, możemy mieć wszystkie dzieci, żeby umyły Moje stopy a potem będziemy potrzebować parę dziewcząt, które mają ponad szesnaście lat do dwudziestu jeden lat. A potem kilka pań, aby czcić Shakti, Boginię. Bez Shakti nic nie można zrobić.

Więc najpierw dzieci muszą podejść, żeby umyć stopy. I mam nadzieję, że światowi liderzy też tu będą.

Oni są teraz na podobieństwo guru. A liderzy muszą być czymś wyjątkowym. Nie jesteś liderem, jeśli jesteś takim zwyczajnym, przyziemnym typem osoby.

Gdzie są muzycy? Gdzie są muzycy? W porządku.

Więc najpierw musicie powiedzieć Atharva Sheersha, a potem musicie zaśpiewać Ganesha Stuthi, a może umiecie jeszcze coś innego o Ganeshy.