Shri Krishna Puja - De drie paden - Canajoharie, USA - 29 juli 2001

Translation not verified. Dear yogi, register as volunteer to do so.
Vertaling niet geverifieerd. Beste yogi, registreer als vrijwilliger om dit te doen.

Vandaag zijn wij hier tezamen om Shri Krishna te vereren. Hij was de Virata en hij bestreed alle mogelijke soorten van kwaad zonder een gevecht aan te gaan. Het leven van Shri Krishna is zeer mooi, zeer creatief en zeer liefdevol, maar het is niet eenvoudig Hem te begrijpen. Bijvoorbeeld tijdens de oorlog in Kurukshetra, waar de moedeloze Arjuna Hem vroeg : “Waarom zouden wij vechten, vechten tegen ons eigen vlees en bloed, vechten tegen onze naaste relaties, onze vrienden en goeroes? Heeft dat nog iets met godsdienst te maken? Is dát dharma?” Shri Krishna had eerder in de Gita beschreven wat een heilige man is. Wij zullen hem een heilige noemen. Hij noemde hem een stitapragya. Wanneer men Hem naar de definitie van stitapragya vroeg, gaf Hij als beschrijving : iemand die volledig in vrede met zichzelf en zijn omgeving leeft. Het is zeer opmerkelijk dat Hij al deze kennis eerst in de Gita gaf. Het beste daarvan noemde Hij Gnyanamarga. Dat is Sahaja Yoga, waardoor je de subtiele kennis verkrijgt. Maar het is tezelfdertijd heel opmerkelijk dat Hij alleen over spiritualiteit en volledige onthechting spreekt wanneer hij Arjuna raad geeft. Hij zegt aan Arjuna: “Je moet ten strijde trekken.

Zij zijn reeds dood. Tegen wie vecht je dan eigenlijk?”

Dit conflict is moeilijk te begrijpen. Hoe kon Skri Krishna, dezelfde die predikt dat wij allen stitapragya moeten worden, plots aan Arjuna zeggen dat hij de tegenkrachten moet gaan bevechten.

Aan de ene kant is er de volledige onthechting en aan de andere kant oorlog. “ Hoe kan je dit uitleggen?” Met Shri Krishna’s eigen woorden: “Eens je een gerealiseerde ziel bent en je de hoogste staat van bewustzijn bereikt hebt, is alles voor je onbeduidend.” Maar wat je juist nu moet doen, is het dharma verdedigen - niet het dharma waarover men praat. Dit dharma staat voor het evolutieproces van de mensen en als al de goede mensen die de deugdzaamheid vertegenwoordigen, verdwijnen, hoe kan dan de kracht van deze evolutie gered worden?

Dus je moet ze redden en als je daarvoor moet doden, dood je niemand, want ze zijn reeds dood, het zijn geen ontwikkelde zielen en zij geven niet om de realisatie. Dus moet je ze bestrijden. Je moet de negatieve krachten bestrijden. Je moet de misdadigers bevechten.

Hij legt dit alles op een mooie wijze uit, Hij zegt dat we in ons drie krachten hebben - wat wij reeds weten - en dat wij door de kracht van het middenkanaal boven alle materiële, fysieke, mentale en emotionele problemen uitrijzen, al deze problemen die wij tegenkomen in dit nieuwe rijk van de spiritualiteit. En dit wilde Hij redden van de wrede en agressieve mensen die ook de anderen misleidden.

En het is heel goed dat je begrijpt wie je relatie, je broer en je zuster zijn. De geëvolueerde zielen zijn je relaties. Zij zijn je dierbaar en als je voor hen de agressieve mensen moet bevechten dan doe je het. Je moet het doen. Dat is de weg van het dharma.

Zoals je weet, kennen wij in Sahaja Yoga drie paden. Het ene pad is bhakti. In bhakti bezing je de glorie van God, heb je devotie, doe je allerlei rituelen, doe je van alles en denk je dat je heel dicht bij God staat. Dit wordt door vele, vele mensen en de zogenoemde godsdiensten aangenomen, dat we God volledig moeten toegewijd zijn. Hoe komt het dat je nog niet met God verbonden bent? Wat ben je aan het doen?

Hoe kun je enige toewijding tot God hebben als je op geen enkele manier met Hem verbonden bent? Het tweede pad is het karma, waardoor je je taak volbrengt. Je volbrengt je taak met een onthechte geest. Dat is onmogelijk , maar dat is wat ze zeggen, namelijk dat wij onze karma’s beleven, goede karma’s, wij doen allerlei goede zaken. Wij bezoeken verschillende plaatsen om ons te reinigen, wij ontmoeten vele belangrijke spirituele mensen en gaan naar verschillende plaatsen om te bidden. Wij bezoeken al de aangeduide [spiritueel] gunstige plaatsen. Wij voeren allerlei soorten rituelen uit. Dat is de karma yoga.

Volgens ons gaat het hierbij om de rechterkant. Je weet dat vele mensen rechts zijn. Je weet dat rechtse mensen vervuld zijn van ego, dat ze arrogant zijn en dat ze zich heel belangrijk voelen. Het is zeer moeilijk om ze te verbeteren. Zij zien ook nooit hun eigen fouten. Zij gaan ervan uit dat wat ze ook doen het beste is. Dat is karma yoga, maar Hij zegde ook dat je de vruchten van je eigen karma niet kan zien, wat voor karma je ook beleeft. Hij zei dat eerder aarzelend, want als Hij dat met overtuiging gezegd had, dan zouden de mensen Hem niet begrepen hebben. Dus heeft Hij gezegd dat het niet mogelijk is dat het de karma’s zijn die je nu volbrengt die de zegeningen van de Godheid aantrekken. Dat heeft Hij gezegd. Welke karma’s zouden wij moeten meemaken?

Of zouden wij alle karma’s moeten opgeven? Moeten wij de strijd opgeven? De meningen waren verdeeld.

Het is de stijl van Shri Krishna om de meningen van de mensen te verdelen opdat zij hun onderscheidingsvermogen zouden gebruiken. Ten derde is er het onderscheidingsvermogen, dat Hij aanduidt met de term gnyanamarg. Dit is de middenweg waardoor je evolueert. Je evolueert naar een nieuwe toestand, een nieuwe toestand van je geest, een nieuwe toestand van je bestaan, waardoor je helemaal boven alle de nonsens uitrijst. Zo word je ook begiftigd met de kracht om al het slechte, al het corrupte, al hetgeen deze toestand vernietigt, te bestrijden.

In dit stadium ben je uitgerust met de goddelijke kracht om al de negativiteit rondom je te vernietigen. Je moet begrijpen dat dit een werkelijke toestand is en niet enkel theorie. Je moet niet geloven dat het zo is, maar het is een feit. Als je deze toestand kunt bereiken, dat je boven al deze zaken staat en waar je de kennis, de ware kennis , de subtiele kennis van het bestaan bezit, dan heb je gnyanamarg.

Vele mensen zeggen dat niet iedereen tot gnyanamarg kan komen en dat je daarvoor een speciale persoonlijkheid moet hebben, maar dat is zeer misleidend. Iedereen kan gnyanamarg bereiken. Dit evolutionaire principe is ons werkelijk aangeboren. Het is in ons aanwezig en wij kunnen het allen activeren. Het enige probleem is dat wij geen vertrouwen hebben, dat wij het trachten te vermijden en ons met goedkopere zaken bezighouden zoals toegewijd zijn aan iets anders, rituelen verrichten, zogenaamde heilige plaatsen bezoeken, allerlei nonsens waardoor je niet de evolutionaire toestand bereikt die je toelaat om de kennis, de zuivere kennis, de ware kennis te verwerven. Tot nu toe komt al wat je weet uit geschriften, van wat je ouders vertelden of van datgene waar je jezelf naar gezocht hebt. Maar de zuiverste kennis, ware kennis, is de gnyana en die kan je enkel bekomen door je [spirituele]evolutie en door jezelf in deze toestand te vestigen. Indien je dit blijft ontkennen, kan je het niet bereiken, maar iedereen bezit het recht om het te krijgen. Je hoeft niet geschoold te zijn, je hoeft niet over-eenvoudig te zijn, je moet niet arm noch rijk zijn, dat heeft geen belang, zolang je een mens bent en je nederig blijft en dat je die toestand wil bereiken. Zoals je allen wel weet, kan je die toestand bereiken.

In deze toestand bekom je al de kennis, de kennis over jezelf, de kennis over de anderen, de kennis over al wat er gebeurt. Maar je moet deze toestand onderhouden en je moet trachten om daar bovenuit te stijgen en de toestand te bereiken waar je zonder twijfels bent. Dat is wat Shri Krishna onderwees en dat is wat men tot stand moet brengen. Maar Hij is een diplomaat en hij vertelde ook andere verhalen. ”Probeer dit, probeer dat.” Maar wat Hij werkelijk aanbeval, was gnyanamarg.

Wij bezitten de gnyanamarg. Het is de kennis, de weg van de kennis waardoor je alle kennis verwerft. Zolang je de volledige kennis niet bezit, ben je geen gnyani, iemand die weet.

Op deze wijze heeft Hij vastgelegd dat ons evolutieproces belangrijker is dan elk ander menselijk bewustzijn. Elke andere vorm van menselijk bewustzijn heeft geen belang voor de spirituele mensen. Wij weten wel een en ander, bijvoorbeeld de afstand van hier naar New York, of welke treinen er naartoe rijden. Al deze kennis is niet echt – hoeveel kost dit kledingstuk, wat kost dit tapijt, in welke winkel kan je het kopen?

Al deze kennis is nutteloos, het is niet de ware kennis.

Zo iemand bezit deze kennis niet, maar hij weet alles over je, hij weet alles over het heelal, niet hoeveel sterren er zijn en hoeveel universums er bestaan, maar hij kent de subtiele innerlijke kern van alles. In dit subtiele gebied ontdekt hij vele nieuwe zaken, waarover hij zelfs nog nooit gehoord had en zo bereik je de die toestand waar je allerlei zaken te weten kunt komen. Dit moeten wij bereiken. Wij zijn als mens geboren en wij weten reeds zeer veel. De mensen kennen zovele zaken, maar dit kennen zij niet. Deze kennis verkrijg je niet door te lezen of door intellectuele activiteiten of door je emotionele ontwikkeling – neen.

Het is shashwat. Het is er altijd. Ze bestaat. Ze zal er altijd zijn. En je moet het zelf begrijpen en weten. Ze is onveranderlijk. Ze kan niet vervormd worden. Ze is wat ze is. En dat is wat je nu beseft.Niemand twijfelt er aan omdat zij die deze toestand bereikt hebben, ondanks alle twijfels, ondanks alle verdachtmakingen, altijd op klare wijze de volle waarheid vertellen. En als je daarvoor met je hart en je brein openstaat, zal je op dezelfde wijze de echte waarheid kennen en al hetgeen je moet weten. Daarvoor moet je volgens Shri Krishna verscheidene testen ondergaan. Eén ervan is voor Hem te bidden. Hij zegt: “Als je voor Mij bid en Mij bloemen geeft, zal Ik ze aannemen. Wat je Mij ook geeft, zal Ik aannemen. Als je Mij water geeft, zal ik het aannemen.” Hij zegt het duidelijk , maar het is belangrijk wat je ervan maakt. Hij zegt niet: “Als je Mij iets geeft, zal Ik je iets geven.” Dat bedoelt Hij niet.

Hoe zou het dus moeten zijn ? Wat zijn de voorwaarden? Hij zegde: “Je looft Mij, je aanbidt Mij, je geeft Me geschenken en je doet nog vele andere zaken, je bent Mij echt toegewijd, maar je zou ananyabhakti moeten doen.” Het woord is ananya. Ananya betekent dat de andere niet bestaat [dat er niets anders bestaat]. Wanneer we één zijn, wanneer we verbonden zijn en wij aanbidden Hem, wat ook de muzikale devotie moge zijn, wat voor bloemen wij ook mogen geven of hoe wij ons ook uitdrukken, het zou ananya moeten zijn. Dat is het woord dat Hij gebruikte : “Verricht ananyabhakti. Wat je Mij geeft, zal Ik aannemen.”

Hij aanvaardt alles. Hij is uniek. Bopta betekent dat Hij de enige is die geniet. Maar wat zal jij krijgen?

Hij zegt:”Wanneer verricht je ananyabhakti ? Als je één bent met Mij.” Dat betekent dat je met Hem verbonden bent. Dat is hoe Hij bhakti heeft uitgelegd.

De betekenis van bhakti is heel duidelijk, maar de mensen begrijpen het niet. Zij denken dat bhakti bestaat uit zingen op straat : “Hari Rama, Hari Krishna” en dat zulke dingen bhakti zijn. Dat is het niet. Als dat wel zo was, zouden zij iets verwezelijkt hebben, maar dat is niet zo. Maar dat moet je Shri Krishna niet verwijten. Hij heeft heel duidelijk gezegd dat het ananayabhakti moet zijn. Het heeft niet met enkel iets te maken met van kleding veranderen of een speciale stijl aan te nemen. Dat is enkel de buitenkant. Dat is alleen maar opschepperij ; in feite is ananyabhakti inwendig : als je één bent met God. En zolang je dat niet verwezelijkt hebt en in jezelf gevestigd, brengt het je niets bij.

Zovele mensen zegden Mij : “Moeder, wij doen heel veel bhaktiyoga, maar het levert ons niets op.” - ”Werkelijk, wat voor bhaktiyoga?” – “Wij lezen de Gita van Shri Krishna. Wij staan iedere morgen om vier uur op, wij nemen een bad, we lezen de Gita van Shri Krishna, doen van alles ... Dan zingen wij bhajans. En wij bekomen nooit iets. Hoe komt dat?” De reden is dat je niet met God verbonden bent. En wat geeft Hij je als je één bent met God? Hij zal je geen goedkope zaken geven die in minder dan geen tijd verdwijnen, maar wel die eeuwig duren. Dus geeft Hij je vrede, de vrede van het hart. Hij brengt je in evenwicht. Hij geeft je een rustige aard vol levensvreugde. Wij hebben al deze zaken in ons wanneer wij bhakti bezitten, de bhakti die ons na de yoga verenigt met de Yogeshwara. Dit is wat wij moeten begrijpen. Maar er zijn vele karmayogi’s die als gekken werken, totaal gek. Zij denken dat zij nishkama doen, dat zij zonder enig verlangen de mensen ten dienste staan, zij dienen de Natie, zij dienen van alles. Wat brengt dat uiteindelijk op? Het brengt misschien geld op. Misschien verwerf je een mooi huis, al deze dingen, maar het brengt geen vrede in je hart. Het brengt je geest niet tot rust. Je verwerft geen vreugde, die vreugde die geen grenzen heeft, die niet te verklaren is, die onbeschrijfbaar is, die grenzeloze vreugde krijg je niet. En de eeuwige vrede die oorlogen kan stoppen, verkrijg je niet.

Dit kan werkelijk een eind maken aan de wrede natuur van de mensen, maar dat bereik je niet. Maar je verkrijgt wel krachten. Je verkrijgt de kennis, de subtiele kennis over iedereen. Je weet van iedereen op welk punt ze verkeerd zijn. Je hebt deze kennis over jezelf en de anderen. Deze kennis verkrijg je niet in een collegezaal of in de scholen, maar de oceaan van de kennis is binnen in jezelf aanwezig en hoe je het ook bekijkt, hoe je het ook wil verwezenlijken, het is er, het is daar aanwezig. Dat noemen wij de ware kennis die je kan bekomen door de sukshmagnyana, t.t.z. de subtiele kennis, de kennis van de chakra’s, de kennis over het heelal. Je kan er alles mee te weten komen. Maar dan geraak je meer geïnteresseerd om die kennis aan anderen door te geven. Je wil niet meer zoveel weten.

Wat is het belang om het bankwezen te kennen, bijvoorbeeld wie de rijkste man is in de hele wereld. Al deze dingen wil je niet weten. Je hele houding verandert en wat overblijft is een rustige geest die alles weet wat er te kennen valt. Dat moeten wij bereiken.

Nu is jullie land, Amerika, zeer kharmakandi. Altijd maar werken, werken, werken. Het zijn werkverslaafden. Zij werken zo hard en wat blijft er over? Jullie kinderen zijn drugsverslaafden. Jullie vrouwen lopen van hier naar ginder. Jullie families zijn verdeeld en er is geen vrede. Jullie ondersteunen oorlogen. Het enige tot nu toe is dat dit land op een of andere manier beschermd is, maar jullie hebben vele inboorlingen gedood, zoveel fundamentele zaken [overboord gegooid] die jullie hadden moeten behouden. Op een dag zullen zij beseffen wat zij gedaan hebben en dat het zeer verkeerd was. Er zal een dag komen dat wij in Amerika heel veel gerealiseerde zielen zullen hebben. Maar nu is de situatie zo dat de mensen gek geworden zijn door de obsessie van geld verdienen en ze ontdekken nu dat het nutteloos is. Wat moet er nu gebeuren? Wat moeten ze doen?

Kom naar Sahaja Yoga. Doe aan Sahaja Yoga en je zal je eigen innerlijke schatten ontdekken die je alle comfort, alle vreugde en beheersing zullen geven, meer dan enige geldsom of macht je kan geven. Dat is wat wij moeten doen: Sahaja Yoga aanvaarden en van de anderen ook Sahaja yogi’s maken opdat zij ook die vrede, die vreugde en die voldoening zouden bekomen en die dwaasheid om van over en weer te hollen zal ophouden omdat je daarmee nooit voldaan kunt geraken. Vandaag wil je dit kopen, morgen wil je iets anders, dan wil je iets anders doen. Je bent nooit tevreden. Je puurt geen enkele vreugde uit wat je verlangt. Je zuiver verlangen zou dus moeten zijn : één te worden met God. Zo zal het uitwerken.

De specialiteit van Shri Krishna was dat Hij altijd de mensen ondersteunde die gerealiseerd waren, die op het rechte pad waren, die rechtschapen waren. Hij zou nooit iemand ondersteunen die rijk of belangrijk was. Zo was er de grote koning Duryodhana. Hij nodigde Shri Krishna uit in zijn huis, in zijn groot paleis, als zijn gast. Shri Krishna zegde : ”Verontschuldig Mij.” Hij ging naar Vidura, die de zoon was van een meid die Dasiputra heette, omdat Vidura een gerealiseerde ziel was. Omdat hij een gerealiseerde ziel was, stond hij bij Hem veel hoger aangeschreven dan Duryodhana die een dief en een slecht mens was. Het onderscheid tussen goed en kwaad wordt een kwaliteit van je geest, wordt een onderdeel van je temperament en je bent altijd heel tevreden omdat je weet dat je geen verkeerde dingen doet.

Het onderscheidingsvermogen is een geschenk van Shri Krishna.

Los van al het andere geeft Hij ons het geschenk van het onderscheidingsvermogen.

Ik zou zeggen dat het Zijn stijl is om ons te leren hoe wij het onderscheid moeten maken en dan worden jullie deskundigen van het onderscheidingsvermogen, deskundigen in [het hanteren van] vibraties.

Met de vibraties kan je alles klaar en mooi beoordelen.

De anderen zullen misschien niet met je akkoord gaan, maar dat is iets anders; jij kent het verschil tussen goed en kwaad. En dat is het geschenk van Shri Krishna. Zoals je weet, beheert Hij in ons zestien subchakra’s : Hij controleert alles. Hij controleert jullie keel, neus, ogen, oren. Hij controleert dit allemaal, maar wat zegt Hij uiteindelijk?

Hij zegt dat Hij de Virata is. Met Virata bedoelt men diegene die de grote, grote Heer is, die wij “Akbar” noemen en daarom zeggen de Moslims: Allah Hu Akbar. Ik denk dat het deels duidelijk en deels onduidelijk is omdat het poëzie is. Hij was een Virata en Hij toonde Zijn gedaante aan Arjuna en Arjuna was verwonderd dat kon zien dat Hij de Virata was.

Hij is groot en neemt alles in zich op en Hij is diegene die alles [wat verkeerd is] wegneemt. Hij is Yama. Hij is de God van de dood. Hij is zoveel. Jullie weten dat Zijn namen opgeschreven staan : al deze krachten, die Hij gebruikt waar dat nodig is. Zo hebben de Sahaja Yogi’s ten eerste de kracht van de tevredenheid. De tevredenheid is een geweldige ervaring. Stel je voor : jullie beleven hier zoveel vreugde, jullie zijn hier heel gelukkig. Wat toont dat aan? Je bent zeer voldaan. Anders zou niemand er van houden. En ze zouden zeggen: ”Neen, wij hebben een mooie zaal nodig.

Wat is dit? Wij willen hier niet met iedereen [opeengepakt] leven.”

Maar deze collectiviteit met de anderen beleven, is ook een zegen van Shri Krishna. Hij leert jullie hoe je collectief kunt zijn, het plezier van de collectiviteit, de vreugde van de collectiviteit. Iemand die zich afzondert en [ver van alles] wegblijft, gelijk een dronkaard, is niet iemand die Shri Krishna vereert. Hij die één is met Shri Krishna, geniet van de aanwezigheid van de anderen, zeker als het gerealiseerde zielen zijn., Zo iemand geniet heel veel van hun gezelschap. Het is zo gemakkelijk te begrijpen als je ziet hoe gelukkig jullie leven, ook op moreel gebied, werkelijk perfect. Jullie doen geen immorele dingen, jullie stelen niet en hebben geen wrok tegenover andere mensen. Het is iets verwonderlijks dat jullie overkomen is, jullie leven allen zo gelukkig samen op één plaats met satya. Omdat Ik altijd zeg dat Shri Krishna de godheid van Amerika is, dient zijn collectiviteitsprincipe goed begrepen te worden. Amerika is ook heel collectief. Het toont voor ieder land belangstelling. Het is bezorgd over iedereen, maar tracht op een verkeerde manier te helpen. Neem bijvoorbeeld een land is waar ze veel drugs produceren. Waarom niet dit land binnenvallen in plaats van andere landen?

Zij zijn zo. Ze hebben geen onderscheidingsvermogen. Zolang je dat niet hebt, kan je de kracht van de collectiviteit niet ten volle gebruiken. Wat voor collectief werk hebben zij gedaan, ondanks het feit dat zij collectief zijn? Zelfs nu nog gaan ze er van uit dat zij anders zijn, dat zij verschillend zijn. “De problemen die wij onder de ogen moeten zien, zijn de onze.” Zo werd het collectiviteitsprincipe in het land van Shri Krishna zelf geminimaliseerd. Ondanks het feit dat zij het in zich hebben, dat gevoel dat zij over elk land moeten meepraten, dat zij elk land leiding moeten geven, dat zij elk land raad moeten geven, nemen zij altijd de verkeerde beslissing aangaande deze landen. Dit komt omdat zij hun onderscheidingsvermogen niet gebruiken.

Zij zouden hun onderscheidingsvermogen moeten gebruiken.

Er kan zoveel over de Vishuddi chakra gezegd worden, maar Ik hecht meer belang aan twee chakra’s langs beide kanten. Zoals je weet, is een ervan de Lalita chakra aan de linkse kant en de Shri chakra aan de rechtse kant. Ik heb de dames altijd gezegd dat zij die moeten bedekken. Het is zo eenvoudig, maar het is zeer belangrijk. Ontbloot ze niet, want hun kracht moet bewaard blijven. De Shri chakra en de Lalita chakra zijn heel belangrijk. Het zijn vrouwelijke krachten ; het zijn de vrouwelijke krachten van Shri Krishna, die je doen begrijpen dat de toestand van je chakra’s zal overeenkomen met de wijze waarop je je lichaam respecteert en dat die toestand ook bepaalt hoeveel je zal lijden.

Als je bijvoorbeeld Shri Ganesha niet respecteert, zal je lijden. En als je Shri Ganesha eerbiedigt en je niet gedraagt zoals je je zou moeten gedragen, zal je lijden. Je zal problemen hebben. Je hele lichaam zal reageren. Je lichaam zal op zulke manier op invloeden van buitenaf reageren dat je zal inzien dat er iets verkeerd gaat en dat je daarom zo reageert.Ook de ogen worden door deze chakra ondersteund; als je dus iets bekijkt, moet het met een zeer zuivere blik gebeuren. Hoe zuiverder, hoe meer vreugde je er aan zal hebben. Maar als de blik niet zuiver is, als hij stiekem wordt, van hier naar daar schiet, van daar naar ginder, dan ga je in feite tegen je dharma in, tegen je eigen ontwikkeling en op een dag kan je blind worden, kan je cataract krijgen.

Je kan allerlei kwalen aan de ogen ontwikkelen, die te belangrijk zijn om er geen aandacht aan te hechten.

Dan is deze chakra ook met de tong verbonden. Men let op zijn tong, maar sommige mensen hebben de slechte gewoonte om plots gruwelijke dingen te zeggen, of plots negatieve zaken te vertellen of iemand aan te vallen met heel negatieve opmerkingen. Al deze zaken zijn slecht voor de tong en daarom houdt Shri Krishna er niet van. Als je je tong gebruikt om ruwe dingen aan anderen te zeggen, om sarcastisch te zijn, om onbehouwen te zijn met anderen, scheldwoorden te gebruiken, dan weet Ik niet hoe je tong op een dag zal reageren.

Ze zal op verschillende manieren reageren. God mag het weten, ze kan bijvoorbeeld opzwellen. Ze zal niet meer bewegen.

God mag het weten, ze wordt misschien naar binnen gezogen. Dat is de fysieke kant, maar er is ook de mentale kant, dat je niet meer beseft waarover je praat. Als je iets wil zeggen, zeg je iets anders. Dat kan je tong overkomen. Het is ook mogelijk dat wij niet meer kunnen spreken, dat het niet meer mogelijk is om iets te zeggen. Alles is mogelijk als je je tong voor verkeerde doeleinden gebruikt. Je tong is er niet om voor verkeerde dingen te gebruiken - ook niet zoals sommige mensen die extra lief en vriendelijk zijn om iets te bekomen. Zoiets is ook heel, heel gevaarlijk voor de tong en je zou er blaren op kunnen ontwikkelen en wel zo dat mensen die altijd maar ruw spreken tegen anderen, een soort van kanker kunnen krijgen. Sommige mensen denken dat het goed is alles te verdragen. Dat is niet zo. Als iemand je wil onderdrukken, tracht dan niet het te aanvaarden. Gooi het van je af, want als je het op je neemt, ga je misschien naar links en kan je afschuwelijke dingen krijgen zoals kanker. Je kan kanker krijgen. Zij die agressief zijn, kunnen ook ziektes opdoen en zij die van het heel verdraagzame type zijn, kunnen ook in moeilijkheden komen. Dus zou je in een harmonische toestand moeten zijn en zou je niets mogen aanvaarden. Veronderstel dat iemand je uitscheldt, blijf rustig, bekijk die persoon – dat is alles. Weet dat hij een domme dwaas is. Maar aanvaard het niet. Als je het aanvaardt en je begint er over te klagen en te wenen, dan kan je kanker krijgen. Maar stel dat iemand iets zegt en je weet dat hij een domme dwaas is, blijf er dan tussenuit en er zal niets gebeuren. Je moet dus aan beide kanten voorzichtig zijn, want Shri Krishna speelt zijn spel en kijkt toe tot waar je kan gaan. Nu de keel ; de keel is heel belangrijk. Je moet er zorg voor dragen. De mensen die roepen en tieren, kunnen uiteindelijk hun spraakvermogen verliezen, kunnen echt uitzinnig worden over de problemen van hun keel. Speciaal de keel kan afschuwelijke ziektes ontwikkelen; ze kan bijvoorbeeld opzwellen. Wij noemen het de slangenziekte en het voelt aan of als je stikt. Dus als je het woord tot iemand richt, spreek duidelijk en op een zachte manier, maar schreeuw nooit. Laat nooit slecht humeur in je taalgebruik doorschemeren. Als je slecht gehumeurd bent, kan er kanker ontstaan. Dus moet je langs beide zijden voorzichtig zijn omdat jullie Sahaja yogi’s zijn. Je dient te weten dat je geen nonsens hoeft te verdragen van iemand die spreekt, dat betekent dat je ze niet zal aanvaarden. Men kan je iets vertellen. Dat is in orde. En soms zal je de spreker terechtwijzen: ”Dat je zoiets vertelt, is niet juist.” Het beste is het niet te verdragen en er niet onder te lijden. Je bent Christus niet. Jij hebt zijn krachten niet.

Want als je het doet, zal je kanker ontwikkelen. Tracht dus gecentreerd te zijn, bekijk alles en als er agressie of recessie [terug-trek-gedrag] voorkomt – één van de twee – geef er dan niet aan toe, maar ontwikkel een houding waarbij je stevig op je eigen benen staat.

Ik las bijvoorbeeld een Chinees verhaal waarin een koning wou dat zijn twee hanen een wedstrijd zouden winnen. Dus raadden ze hem aan ze naar een wijs man te sturen en ze te laten africhten. Bijgevolg werden ze naar een wijs man gezonden. Zij werden heel goed afgericht. En als ze werden teruggebracht, stonden ze in de arena waar er vele hanen waren die hen aanvielen. Maar deze twee stonden daar zomaar, zonder er zich iets van aan te trekken. De andere hanen probeerden en probeerden, maar deze twee bleven daar zomaar staan. Tenslotte liepen ze allen weg. Zo een karakter zou je moeten hebben. Je moet niet aan iets toegeven omdat iemand agressief is en je moet de anderen ook niet aanvallen, noch ze pijnigen, noch ze op de kop zitten. Het is heel, heel gevaarlijk voor je keel en zo een keel zal altijd blootgesteld staan om sommige afschuwelijke ziektes op de doen.

Ik heb je dit alles verteld omdat wij de vele zaken die wij kennen, moeten trachten waar te maken. Over de Vishuddhi chakra hebben wij een zeer subtiele kennis. Wij zouden ook een beetje ruw mogen zijn, zodat we weten wat er met onze Vishuddhi chakra kan gebeuren als wij er geen aandacht aan besteden. Dit is dus het werk van Shri Krishna. Hij beheert ook de tanden. Hij controleert de oren. Jullie weten hoe je tanden en oren moet behandelen. Dit zijn zijn eigen zestien werken. Wij kunnen ze karias noemen, het zijn er zestien waarmee Hij op heel verschillende vlakken werkt. En jullie moeten trachten om de krachten van onze Vishuddhi chakra op vele wijzen en met vele oefeningen te ontwikkelen, door te begrijpen wat er met ons gebeurt als wij onze Vishuddhi chakra niet begrijpen noch zijn waarde inzien.

Doordat Amerika de Vishuddhi van de ganse wereld vertegenwoordigt, is het zeer belangrijk dat de mensen die hier verantwoordelijk zijn, al de krachten van de Vishuddhi zouden kennen en verder weten hoe ze te bewaren en hoe ze over gans de wereld te verspreiden.

Met deze twee handen die ook van de Vishuddhi chakra afhangen, moeten jullie Sahaja Yoga verspreiden. Jullie moeten naar verschillende continenten, verschillende landen en zelfs naar kleine dorpjes gaan om Sahaja Yoga te verspreiden. Je moet dus eerst de koele bries in je handen voelen. Dat betekent dat je de universele kracht van God in je handen aanvoelt. Dit is dus de collectieve, universele liefde die zich in je handen nestelt en je onderwijst. Zo belangrijk is deze chakra. Op dezelfde wijze is Amerika heel belangrijk en zouden jullie als Amerikaanse burgers moeten trachten om hier de godsvrucht en het dharma te behouden en een groot begrip voor de wereldproblemen te creëren en trachten om aan al de mensen, van welk land ze ook zijn, liefde te geven.

Dat God jullie moge zegenen.