20 agosto 2000
Krishna Puja
Campus, Cabella Ligure (Italy)
Shri Krishna Puja. Cabella Ligure, Italia. 20 de agosto de 2000.

Hoy estamos aquí para adorar a Shri Krishna dentro de nosotros. Como sabéis, todos vosotros habéis sido buscadores antes de llegar a Sahaja Yoga. Fuisteis a distintos lugares, leísteis muchos libros e incluso algunos de vosotros os perdisteis. En esa búsqueda, quizá no sabíais lo que buscabais. Lo que buscabais era "conoceros a vosotros mismos". En todas las religiones se ha dicho: "Conócete a ti mismo". Esto es algo común para todos y aparece en absolutamente todas las religiones, porque sin conocerse a sí mismo, no se conocerá a Dios, no se conocerá la espiritualidad. Por tanto, el primer paso es conocerse a uno mismo. Y en este aspecto, han intentado jugar con vosotros, os han hecho todo tipo de trucos y os han engañado. Pero todo esto ha terminado. Ahora habéis llegado a Sahaja Yoga y habéis obtenido la Realización del Ser.

¿Cuál es el propósito de la Realización del Ser? Es conocer a Dios o a la Diosa. Esta es la finalidad de la Realización. Pero después de obtenerla, ¿qué debería sucederos? Muchos de vosotros habéis perdido el interés por cosas disparatadas, como las drogas, etc. Tampoco queréis ahora leer libros que son inútiles ni os interesan otros hábitos como la bebida, etc. Pero esto no es suficiente. Esto podría pasar de cualquier manera. Lo que os debe suceder al conocer a Dios es aquello para lo cual Dios quiere que le conozcáis, y es que Él pueda ver su propio reflejo en vosotros. Él quiere ver su reflejo en vosotros y para eso os ha creado. Lo mismo sucede con la Diosa. Ella os ha dado la Realización porque desea ver su propio reflejo en vosotros. Así que tenéis que prepararos para ser este reflejo, que es tan puro, hermoso, amoroso, compasivo, y sobre todo, lleno de sabiduría.

Uno debe llegar a este punto en el que comprende que hay que tener sabiduría. Si os falta sabiduría, es que no sois personas realizadas. A nivel de Shri Krishna, Él quiere que os convirtáis en parte del Virata. Y Viratangana desea lo mismo, que seáis parte del Virata. No es que ahora, por ser almas realizadas y estar por encima de los pensamientos, estéis perfectamente bien y no debáis hacer nada más al respecto. Lo que hay que hacer para llegar más allá, después de la Realización, es ver el reflejo que debería existir en vuestro interior, a partir de la vida de gente como Shri Krishna.

Inicialmente, Shri Krishna nació en una situación muy difícil como ya sabéis. Enseguida lo llevaron a Gokul, donde fue criado por Yashoda y allí desarrolló su naturaleza juguetona. Vosotros también tenéis que ser así, tenéis que crear diversión y gozo, y no sentaros en solitario como un gran sabio en los Himalayas. Por el contrario, mezclaos con los niños, hablad con ellos, jugad con ellos, divertíos. Al mismo tiempo que jugaba, Shri Krishna destruía las fuerzas negativas que actuaban sobre Él, y lo hacía siempre de forma jocosa, cuando aún era un niño. Pero era un niño tan maduro que mató a Pothana y a otros dos horribles rakshasas, todo al mismo tiempo que jugaba con las gopis, gastándoles bromas y riéndose con ellas, porque quería que ellas también fueran juguetonas.

Generaba todo tipo de situaciones felices. Una vez, hubo una tormenta muy fuerte, y Él levantó con un solo dedo toda una montaña. La gente debería haber entendido quién era ese niño, era un milagro, pero Él simplemente se quedó ahí de pie con la montaña sobre su dedo de una forma muy simple y modesta, protegiendo de la lluvia a los otros niños que estaban jugando. En otra ocasión, destruyó a Kalia, que tenía forma de serpiente y vivía en el agua. Allí este horrible individuo creaba un veneno que estaba matando a mucha gente. Shri Krishna lo resolvió rápidamente, saltó al agua del río Yamuna y así evitó la muerte de todas estas personas al golpear y vencer a Kalia. Pero las esposas de esta gran serpiente le pidieron que le perdonara la vida, y Él lo hizo. Todo esto muestra a un niño de seis o siete años, haciendo cosas grandiosas prácticamente sin darse cuenta o sin pensar en ello. Pero las lograba, porque Él era consciente de que era Shri Krishna.

Por eso, en primer lugar tenéis que ser conscientes de que sois almas realizadas. No sois gente ordinaria comportándose de forma ordinaria. Sois personas especiales, creadas especialmente para reflejar las cualidades de Dios Todopoderoso. No se espera de vosotros que destruyáis a Kalia, pero la situación hoy es tal que estáis protegidos todo el tiempo, nadie puede haceros daño ni mataros, sino que siempre sois cuidados porque sois sahaja yoguis.

Hay que entender cuál debe ser la actitud de un sahaja yogui a la hora de tomar decisiones. Las decisiones deben ser espontáneas. No hay que medirlo todo, ir a diferentes sitios, averiguar aquí y allá, sino que de forma inmediata y espontánea tenéis que tomar las decisiones, como cuando Shri Krishna saltó al río. De la misma manera vuestras decisiones para todo deben ser muy espontáneas. Por ejemplo, si queréis comprar una alfombra, entráis en la tienda e inmediatamente sabéis cuál es la adecuada. En todos los aspectos de la vida, vuestras decisiones deben ser muy espontáneas, instantáneas.

Pero lo que veo es que hacéis algo muy diferente, vais de una tienda a otra, hacéis una lista, tomáis todas las medidas, luego vais a casa y decís que la decisión la tomaréis mañana. Esa no es la forma en que se comporta un sahaja yogui. Un sahaja yogui lo decide todo en el momento, de una forma absolutamente espontánea. Debería ser como cuando alguien se está ahogando, que el primer impulso es simplemente: "tengo que salvarle". ¿Y cómo le salváis? Simplemente saltando al agua. Porque vosotros estáis protegidos, nada os puede pasar. Simplemente os tiráis al agua y salváis a la persona.

Vuestra actitud, vuestra personalidad, deberían ser así como mínimo, tomando decisiones muy espontáneas. Todas las formas en que tomáis decisiones dando una conferencia al respecto, todos esos pensamientos etc., todo eso debe terminar. También en la vida diaria debéis ser así. Y también en vuestra vida política, económica y en todos los campos, tenéis que ser muy espontáneos.

¿Cómo os volvéis espontáneos? ¿Qué cualidad debéis tener? ¿Qué arma vais a utilizar para saber cuál es la decisión correcta? Para eso tenéis las vibraciones. Tenéis la percepción de las vibraciones y sabéis qué son las vibraciones. Sabéis lo que os dicen las vibraciones, cómo os hablan, os comunican. Por eso, a través de las vibraciones, deberíais saber, en un segundo, lo que hay que hacer. Por ejemplo, alguien me ha comentado: "Madre, cuando llegué a Cabella sentí unas vibraciones tremendas". Es un hecho pero, ¿cuántos de vosotros podéis sentir esto?

Vuestra sensibilidad no está desarrollada. Tenéis que ser sensibles con las vibraciones. Solo con mirar a alguien o sentaros a su lado o incluso con darle la mano, deberías saber qué vibraciones tiene esa persona. Si desarrolláis este tipo de sensibilidad, definitivamente podréis tomar decisiones espontáneas. A mí se me da muy bien. La propiedad de Cabella la compré en cinco minutos. Cuando vine aquí, me dijeron que no podía llegar hasta allí porque mi coche era demasiado grande. El alcalde me invitó a ir en su coche y fui con él en ese coche.

Cuando vi la casa, estaba toda desmantelada, sin duda, absolutamente arruinada, y parecía un lugar fantasmal. Todos los que estaban conmigo, me decían: "Vaya lugar, Madre, no puedes comprar eso". Yo le dije al alcalde: "La compro, hoy, ahora". Él estaba sorprendido. "Dígame cómo la puedo comprar". Él dijo: "Muy fácil. Aquí en Italia, para comprar un lugar, se paga la tercera parte del precio y ya se puede ocupar. Si hay algo que no le complace, puede rechazar la casa pero pierde el dinero aportado. Pero si es el vendedor quien se echa atrás, entonces él le paga a Usted el doble de esa cantidad". Yo dije: "¡Qué oportunidad tan buena! Le dije que la compraba y la compré".

Todos estaban asombrados de lo que Madre estaba haciendo. Lo que me llevó a esa decisión fueron las vibraciones, las vibraciones del lugar. Simplemente lo decidí y la compré. Me habían llevado a ver anteriormente unos siete castillos, y desde afuera, dije que no a todos. Se sorprendían de que ni siquiera entraba a ellos. Pero yo preguntaba: "¿Quién ha vivido aquí?" Me contestaban: "Había un convento".

Igualmente, vosotros debéis desarrollar este tipo de decisión espontánea. Entonces os sorprenderá cómo en tan poco tiempo, podéis conseguir cosas tan buenas. Pero esto no significa que ahora todos empecéis a comportaros así, antes debéis tener esa sensibilidad con las vibraciones. Si tenéis esa sensibilidad con las vibraciones, entonces puedo decir que estáis maduros en Sahaja Yoga. Esta madurez tiene que darse. No podéis decir simplemente: "Ahora, como ya tengo la Realización, soy capaz de hacerlo".

Primero, medid vuestra sensibilidad. ¿Cómo sabréis que habéis decidido bien? Por ejemplo, si decidís algo espontáneamente y al final no obtenéis ningún resultado, no es posible que la decisión fuera la correcta. Tenéis que verlo vosotros mismos. Si vuestras decisiones son espontáneas pero fallan, son erróneas, si habéis cometido un error, el resultado os hará sufrir, ya sea en el campo económico, político o en cualquier otro. Por tanto, todo vuestro sistema de valores puede ser juzgado muy fácilmente, podéis ver fácilmente hasta dónde habéis llegado en Sahaja Yoga, hasta qué punto habéis alcanzado vuestra Realización del Ser, y dónde estáis. De esta forma debéis poneros a prueba. No tengáis miedo de los errores ni os dejéis enamorar por el éxito, porque sois almas realizadas. Por supuesto, si sois sensibles, inmediatamente sabréis dónde está el error. Claro que no puedo decir que vuestra capacidad sea igual a la mía, pero debéis intentarlo.

Algunas personas me hablan de otra diciéndome: "Madre, es buen hombre, debes conocerle, es una gran persona, nos ha ayudado tanto, etc., etc." Yo les pido que me enseñen una fotografía y digo: "Lo siento, no quiero conocerle". Ellos no lo entienden al principio, pues insisten en que es un gran hombre, que va a ser ministro, etc. pero yo no deseo verle. Y al día siguiente, encontráis en el periódico un reportaje explicando sus malos actos. Por eso, debéis examinar vuestra experiencia y vuestra comprensión con relación a lo que habéis decidido espontáneamente. Pero, de todas formas, os pediría que practicarais la decisión espontánea. No os pongáis a pensar en cómo va a funcionar, qué debemos hacer, etc. Esta espontaneidad tiene una amplia influencia incluso en vuestra mente, de manera que veis lo que está bien y lo que está mal.

No sé cuántos de vosotros habéis visto la casa que he construido. Otro aspecto de Shri Krishna era el ser extremadamente creativo. Durante su niñez, Él hizo todas estas bromas. Como adulto, fue el rey de Dwarika. Se vestía como un rey. Cuando era un niño, solía ponerse un trocito de pluma de pavo real, pero cuando fue rey se vestía como tal, se sentaba en el trono y hablaba a la gente como un rey. Tenía toda esa grandeza, y era extremadamente creativo. Construyó un palacio muy hermoso en Dwarika, todo de oro, ¿os imagináis? Finalmente acabó sumergido en el agua. Ahora, los intelectuales de la India, que yo creo que han aprendido de algún occidental, dicen que eso no es posible, que no hay nada en el agua, que Shri Krishna nunca construyó un palacio allí, y que se trata solo de una leyenda.

Pero otras personas sí que creyeron en Él y excavaron en la zona. Encontraron que existía un gran palacio. Quedaba algo de oro, pero no todo. Se sorprendieron mucho de lo inmenso que era el palacio. Terminó sumergido en el agua, pero existió. De igual manera, todas las encarnaciones que vinieron a la tierra, eran extremadamente creativas. Si no sois creativos, ¿para qué sirve la Realización? La cosa creativa más importante que podéis hacer muy fácilmente, es convertir a otros en sahaja yoguis. Lo más fácil y lo que más gozo da es hacer a los demás sahaja yoguis, y darles las bendiciones del Divino, algo que han buscado durante siglos. Con ello, no sabéis qué consuelo, qué bendición les dais.

Ahora vosotros tenéis vuestra Realización del Ser. Debo decir que la conseguisteis muy fácilmente. La llaman el nirvana instantáneo, dicen que Sahaja Yoga es el nirvana instantáneo. Pero no entendéis el valor de las cosas que se obtienen tan fácilmente e instantáneamente. Dicen que la India consiguió su libertad muy fácilmente, pero no fue así de fácil, por eso en India aprecian el valor de esa libertad. Es así, si obtenéis algo gratis y sin ningún esfuerzo especial, entonces no lo valoráis, no lo comprendéis, pensáis que es algo a lo que tenéis derecho.

Pero ya sabéis cuánto han sufrido otras personas para obtener la Realización. Se iban al Himalaya, se quedaban de pie sobre una sola pierna, a veces sobre la cabeza, durante meses, y aun así no la alcanzaban. He oído de unos que permanecieron en una habitación durante veiniocho años, con el fin de obtener la Realización. Pensaron que manteniéndose al margen de otras personas y de otros malos ambientes la podrían conseguir, pero nunca lo lograron.

Por eso debéis entender que, aunque la obtuvisteis tan fácilmente, es algo tan precioso, tan grande... no es nada fácil conseguir la Realización del Ser. Vosotros leéis sobre la gente que es realizada. Quizá ellos ni siquiera saben cómo la obtuvieron, quizá no sabían nada de la Kundalini, pero la tuvieron, tal vez gracias a su guru o a sus propios esfuerzos. ¡Cuánto tuvo que sufrir Buda hasta lograr su Realización! Pensad en ello, en cómo la consiguió.

Uno se entristece al ver su vida, cómo finalmente murió de hambre y pobreza. Pero a vosotros no os ha pasado nada. Todos la habéis obtenido sin ninguna dificultad, de una forma muy dulce, sin pagar ni hacer nada al respecto. Pero eso no quiere decir que no debáis valorarla. Es como una semilla, que puesta en la Madre Tierra, espontáneamente germina y da vida al brote que crece y puede convertirse en arbusto y luego en árbol. Pero hay que echarle agua y ha de ser cuidada por un jardinero u otra persona. En vuestro caso, sois vosotros los que tenéis que hacer todo eso. Primero, tenéis que nutrirla con compasión y amor.

¿Tenéis esa compasión y amor? ¿Amáis a la gente? Hoy alguien me sorprendió diciéndome que no le gustan los niños. "¿No te gustan?", le dije yo. "Me gustan los hijos de los demás, pero no los míos", respondió. Imaginaos, ¿cómo se puede ser así? ¿cómo se puede decir algo así, que no te gustan tus propios hijos? Lo primero para todos vosotros es que nunca debéis decir "me gusta" o "no me gusta". Estas palabras son antimantras. El comentario de que me gusta tal cosa es muy común pero, ¿quiénes sois vosotros para hablar así? "No me gusta esta alfombra, no me gusta este objeto de plata..." ¿Acaso podéis hacer vosotros un objeto parecido?

Hacéis esos juicios de tal manera que parece que son muy espontáneos, pero no lo son, vienen de vuestros condicionamientos. Pensáis que tenéis derecho a decir: "No me gusta", "no lo quiero", ¿pero quiénes sois vosotros? Si sois el Espíritu, nunca utilizaréis tales palabras, porque pueden herir a alguien. Nunca diréis nada que pueda herir a otra persona. Nunca haréis nada que pueda ser peligroso para los demás. Sino que diréis cosas extremadamente amorosas y compasivas, y que den paz. Emitiréis gozo para los demás. Hay un Poder del Espíritu que da gozo a los demás. Si sois una persona hosca, entonces no sois personas realizadas. Debéis ser capaces de dar gozo, amor y compasión, y debería ser algo absolutamente espontáneo.

Hay una historia sobre un santo de Maharastra en la India. Existía la costumbre de llevar agua en un cántaro que llaman "kawad" hasta un templo dedicado a Shri Krishna que hay en Gujarat. Esto se consideraba como una gran ofrenda a Shri Krishna. Este santo también llevaba agua en este cántaro (el kawad), desde su pueblo en Maharastra. Cuando llegó a las puertas del templo, vio a un burro que se estaba muriendo de sed. Él le dio el agua al burro. La gente le dijo: "Traes el agua desde muy lejos, la transportas durante días para ofrecerla a la Deidad y ahora se la das a este burro". Él dijo: "¿No lo sabíais? Dios ha descendido hasta aquí para beber agua". Ved la actitud que él adoptó. Para un alma realizada, la compasión debería ser así, de una naturaleza muy generosa.

Si no sois generosos, si sois tacaños, siempre preocupados por vuestro dinero y vuestros ahorros, entonces, no sois sahaja yoguis. Además, este tipo de dinero nunca os dará felicidad. La tacañería va en contra del Espíritu. El Espíritu es extremadamente generoso. Nunca intenta ahorrar nada ni engañar, ni robar nada. Esto no hay ni que mencionarlo. Puesto que no queda avaricia en el Espíritu, no hay avaricia en absoluto, y por eso una persona realizada no puede ser avariciosa, sino que tiene que ser extremadamente generosa.

He visto a mucha gente que ha sido así, extremadamente generosa, y que ha comprendido muy bien los problemas de los demás. Mientras un sahaja yogui tenga sus propios problemas, no es un sahaja yogui en absoluto. Él está ahí para solucionar los problemas de los demás, y no para solucionar y hablar todo el tiempo de sus propios problemas. La palabra "problema" se ha desarrollado en estos tiempos modernos, os aseguro que antes no se utilizaba. Nosotros solo la utilizamos en geometría. Pero se empezó con la expresión inglesa: "No problem", y ahora todos están en un problema. Creo que, de hecho, ellos son problemas. Lo que hay que entender es que no debéis dar vuestros problemas a los demás.

No debéis pedir nada ni decir: ¿me puedes hacer esto o lo otro? Me sorprende cómo la gente intenta aprovecharse de otros. Algunos quieren ir a algún país y entonces piden a otro: "Me gustaría ir a tu país, por favor, invítame". Un sahaja yogui generoso contestará que venga, por supuesto. Pero el que está fallando aquí es la persona que pide. No debéis pedir nada en absoluto, porque vosotros sois completos. No solo estáis satisfechos, sino que además sois completos. ¿Qué os pueden dar otras personas? Todos los deseos simplemente desaparecen cuando vuestra forma es completa. Como cuando venía hacia aquí hoy, vi que habían salido muchas estrellas. Yo dije: "Tan pronto como la luna salga, todas desaparecerán". De la misma forma, cuando vosotros sois completos, no esperáis que nadie haga nada por vosotros. Por el contrario, queréis averiguar qué podéis hacer vosotros por los demás. En cierta forma, vosotros os volvéis el otro, porque asumís sobre vuestros hombros los problemas de los demás. Os sumergís en ello.

Este es un crecimiento muy, muy, interesante que debería producirse en vosotros. Debería sucederos a todos porque todos tenéis la Realización. Desarrolláis una personalidad que solo vive para los demás, no para ella misma. Os sorprenderá cómo sois capaces de vivir en cualquier parte, podéis dormir en cualquier parte, si coméis o no coméis, o cualquier tipo de comida, todo está bien, porque estáis tan satisfechos. Por el contrario, os gusta cocinar para los demás, darles de comer, y hacer por ellos lo que desean. Si es posible, haréis lo que esté en vuestra mano por ellos. Pero hay personas que solo tienen sus propios problemas. Ellos no son sahaja yoguis. ¿Cómo puede tener problemas el Espíritu? ¿Cómo puede ser? Simplemente, entended que ahora sois el Espíritu, por encima de todo.

Vuestra creatividad también se da en otra dimensión. Por supuesto, comenzáis a dar la Realización a la gente, creáis arte... A Baba Mama se le daba muy mal la literatura, no sabía ningún idioma. Era muy bueno para las matemáticas (porque mi padre era matemático), pero no para los idiomas. Yo le redactaba los trabajos, porque a él se le daba muy mal. Pero después de la Realización, escribió unos poemas tan bellos, es increíble, nadie podía creer que los había escrito Baba Mama. Porque él no conocía bien ninguna lengua, como os he comentado, era yo quien le escribía los trabajos. ¿Cómo comenzó a escribir poesía en urdu, en marathi, en hindi, de esta forma tan asombrosa? Uno de mis hermanos le preguntó: "¿Cómo has podido escribir esta poesía en urdu?" Él dijo: "Es Shri Mataji la que me habla". Ante cualquier comentario, él siempre decía: "Shri Mataji me habla".

Por tanto, la creatividad en vosotros simplemente florece. Y os sorprendéis de vosotros mismos, de cómo os ha llegado tanta creatividad. Imaginaos lo que es para un matemático convertirse de repente en poeta. Es algo imposible. Pero vosotros tenéis esta capacidad. Tenéis todas estas capacidades y os podéis volver muy creativos, y tenéis que ser creativos, en todos los aspectos. Yo soy muy creativa, todo el tiempo estoy sacando algo adelante, y las cosas resultan muy bien. Por otro lado, yo no tengo ese interés que la gente tiene normalmente, en que todos alaben lo que hago, en aparecer en los periódicos, etc.

Uno crea simplemente por el gusto de crear. Y disfruta de lo que ha creado. Y se vuelve muy adaptable, como congeniando con todo lo que la gente comenta al respecto. Puede que sean ofensivos o puede que te estén alabando, pero uno ni siquiera sabe que le están alabando. A veces, cuando decís: "Shri Mataji ki jay", yo también lo digo, olvidando que estáis hablando de mí. De alguna forma, uno está por encima de todas esas cosas. Está ahí pero no comprendo por qué los seres humanos se comportan así, de forma tan rara.

Cuando los seres humanos llegan a Sahaja Yoga tienen un gran deseo de ser líderes o desean ser grandes organizadores de Sahaja Yoga, ser muy famosos en Sahaja Yoga, tener fama de gran sahaja yogui a nivel internacional. Pero no piensan en cuánta creatividad han demostrado, en qué han creado. Esto es algo muy común en los seres humanos, quieren que los demás hablen bien de ellos, que sus cualidades estén expuestas. ¿Pero qué hay que mostrar? Si sois el Espíritu, todo el mundo lo sabe. ¿De qué hay que alardear? ¿Para qué queremos estar en primera fila? Incluso cuando se está al final, si hay luz, se sabe que hay luz.

Tenéis que salir de vuestra oscuridad, porque vosotros sois la luz y expandís luz. Pero si estáis en la oscuridad, ¿qué luz vais a extender? Por tanto, vuestro Espíritu no puede tener problemas. No tiene ningún miedo. Pero, por encima de todo, tiene sabiduría, una sabiduría tremenda, y esta sabiduría es el signo de que sois una personalidad muy elevada. Como ya os he dicho, esto es la evolución, y cuando os transformáis, cuando evolucionáis, os volvéis de una naturaleza muy diferente.

Tenéis que destacar. Si los sahaja yoguis son como las demás personas, entonces, ¿de qué sirve practicar Sahaja Yoga? ¿Quién era Jesucristo? Era el hijo de un carpintero, nunca fue a la universidad. Pero, ¿qué hizo? Él fue el Espíritu. Él reflejó a Dios en su interior. Y por eso Él también fue crucificado. En Sahaja Yoga no tenéis que ser crucificados. Tales pruebas no existen para vosotros. Pero debéis cambiar vuestro sistema de valores. A través de la introspección, debéis averiguar hasta dónde habéis llegado. Debéis preguntaros: "Sr. sahaja yogui, ¿qué tal estás? ¿Estás cayendo en las mismas cosas que la gente no realizada?"

Simplemente, inspeccionaos. Porque el crecimiento en Sahaja Yoga se muestra en vuestro comportamiento, en vuestro estilo, en vuestra cara, una persona así no tiene arrugas. Si no tiene preocupaciones, ¿cómo va a tener arrugas? Una persona así no se molesta por nada, por el contrario, se ríe de las cosas. Una vez, en una iglesia en Suiza, una señora se dirigió a mí para golpearme con una Biblia. Yo me eché a reír, al ver que me iban a golpear con una Biblia. Ella se asustó mucho al verme reír, pero yo veía la estupidez de esta señora que me quería pegar con una Biblia. Puedo entender que me golpeen con una piedra o algo, pero con una Biblia, nunca lo imaginé. Todas estas cosas han sucedido en vuestra presencia y sabéis de qué se trata. Existen fuerzas negativas que tratan de haceros daño, de forma corporal, mental o emocional. Pero cuando estáis por encima de estos aspectos, entonces nadie puede haceros daño, o al menos, vosotros nunca sentís el daño. No os preocupa el daño.

Pero, ¿qué habéis creado? Hoy estuve con algunas mujeres y algunos hombres que querían el divorcio. Después de casarse en Sahaja Yoga, quieren divorciarse. ¿Qué os parece? Me sorprendió las ideas raras que tenían. Una me dijo: "Mi marido es como mi hermano". Yo dije: "¿De verdad?" Todas estas ideas estúpidas que les vienen a la cabeza demuestran que no hay ninguna luz del Espíritu en ellos. Si tenéis la luz del Espíritu, entonces toda vuestra comprensión es muy diferente. No os preocupáis de vosotros mismos, solo os preocupáis por los demás e intentáis encontrar soluciones para ellos. Intentáis ayudarles. Es muy fácil para vosotros. Es tan fácil como arder para una luz. Una vez prendida, la luz arde, lo que es difícil para ella es apagarse. Pero los seres humanos, y esto es algo que no entiendo, incluso después de la Realización, después de crecer durante años, siguen siendo tan tontos que no se dan cuenta del valor de la Realización del Ser.

El Espíritu es tal que no se puede matar, no se puede apagar. La luz de una lámpara se apagará, pero la luz del Espíritu no se apagará. ¿Pero cuál es el aceite que la mantiene siempre viva? Es vuestra compasión. Es el amor, el interés por los demás. Sé que algunas personas son muy dominantes o problemáticas, pero queredlas. Sabéis que no son como vosotros, que todavía no son completas, que tienen problemas, así que amadlas. Pero si en vez de eso, empezáis a pensar: "¿Por qué tengo que quererle? ¿Cómo me va a querer ella a mí?", etc., entonces no hay nada que hacer. Este tipo de reacción no viene de nuestro Espíritu. Las reacciones de una persona espiritual son muy diferentes, en la vida de Shri Krishna lo podéis ver.

Él tenía un amigo que era muy pobre y éste quería reunirse con Shri Krishna. La esposa del amigo le dio lo que llamáis unos "crispies" de arroz para que se los llevara a Shri Krishna puesto que iba a visitarlo. A él le daba un poco de vergüenza esto. Cuando se fue a ver a Shri Krishna, Él estaba en su palacio y los vigilantes de la puerta le dijeron que no podía entrar. El dijo: "De acuerdo, simplemente decidle que ha venido Sudhama". Shri Krishna estaba sentado en su trono, hablando sobre algún tema, cuando le dieron la noticia. Se apresuró a salir, abrió la puerta y le abrazó una y otra vez. Dijo: "¿Por qué estás aquí afuera?" Le hizo entrar y sentarse en el trono que Él mismo ocupaba. Les pidió a sus esposas que vinieran a lavarle los pies. Le trajeron ropas, tomó un baño, y lo llevó a dormir en su cama. Ved el amor de Shri Krishna. Su amigo tenía los pies muy sucios, con rasguños. Intentó aplicar en ellos alguna medicina para que se le curaran, hizo todo lo posible para curárselos. Le pidió que durmiera en su propia cama. Le pidió a sus esposas que le abanicaran para que no sintiera molestias. Ved la compasión de Shri Krishna. Ha sido mostrada de una forma muy bella. ¿Somos nosotros igual de compasivos? Él no tenía necesidad de hacer todo eso, pero su corazón actuó. Tomó esa decisión espontánea. En cuanto supo que Sudhama estaba allí, simplemente corrió hacia él. Sencillamente se sintió muy feliz de que su viejo amigo hubiera venido.

Más tarde, cuando fue a Hastinapur, Duryodhana, el mayor de los Kauravas, le pidió que se quedara en su palacio. Él aceptó, pero dijo que iría a comer con Vidura. Vidura era el hijo de una sirvienta. Fue y comió con él. Vidura, siendo un hombre pobre, no sé qué comida le debió dar, mientras que Duryodhana le hubiera dado una comida suntuosa. Para personas como Shri Krishna, el sabor, el tipo de comida y esas cosas no tienen importancia. Lo que importa es el amor, el respeto por Vidura, quien era un alma realizada.

Respetar a otros sahaja yoguis es lo más importante. No puedo entender que un sahaja yogui respete solo a alguien que es gobernador, por ejemplo. El Espíritu está por encima de todo. Si no respeta a otro sahaja yogui, es que algo va mal en él. Debe entender que una persona espiritual es más elevada que toda esta gente tan famosa.

Este amor se ha mostrado en las vidas de todos los santos y todas las encarnaciones, todos han tenido este amor, que ha estado por encima de todo, sin esperar nada a cambio, sin practicarlo para obtener algo de él. Es un tipo de personalidad que realmente refleja el amor de Dios. Este reflejo debería fluir de vosotros. Sois sahaja yoguis, pero eso no quiere decir que automáticamente seáis más elevados que los demás. Sois diferentes, estáis por encima de ellos pero no tenéis superioridad, por eso sois diferentes. También sois diferentes por lo humildes que sois, por lo gozosos que sois, por los pacíficos que sois, por todo esto sois diferentes.

Hay tantas cosas que os podría contar de la vida de Shri Krishna que demuestran que Él era Yogeshwara, el Señor del Yoga. Lo era porque Él era el Virata, pero solo mostró su forma a Arjuna, a nadie más. Porque no existía nadie como Arjuna. Pero hasta Arjuna se asustó al verla. Por tanto, Shri Krishna vivió en Gokul cuidando de las vacas y nunca alardeó de sus poderes. Él tuvo siempre esos poderes consigo, y se expresaban espontáneamente. Este poder tiene sabiduría y discreción, completa discreción. Si no es así, no se trata de un Poder divino, sino de algún poder demoníaco.

Si sois amables con una persona porque ella lo es con vosotros, no tiene ningún valor. En India llamamos "avadhuta" a las almas realizadas que se apartaron de la sociedad, de las multitudes, y se fueron a vivir a algún lugar pequeño o a alguna cueva, y se escondieron de los demás. Porque pensaron que nadie les iba a comprender, y entonces, ¿de qué serviría intentar hablar a los demás? Eran personas aisladas, una aquí, otra allá, ¿qué podían hacer? No eran como vosotros, con tantos sahaja yoguis juntos.

Vosotros tenéis muchos amigos, hay muchos otros yoguis con vosotros. Ellos eran personas solitarias, y se escondían de la sociedad. No querían encontrarse con nadie, porque si intentaban algo, los crucificarían. Pero a vosotros no os pasa eso, pues vosotros tenéis una sociedad, una hermosa sociedad iluminada, de muy buenos amigos, de personas muy buenas y espirituales. Con todo esto, tenéis que poder crear algo. Quizá arte, música, poesía, literatura, ensayos, lo que sea, pero tenéis que crear. Y por encima de todo, tenéis que crear sahaja yoguis. Esa es la creación más importante que tenéis que lograr. Lo más importante que debéis hacer es crear sahaja yoguis por todas partes.

Yo estoy ahí, voy a diferentes lugares, hago programas, pero sois vosotros quienes tenéis que mostrar, con vuestro ejemplo, que es algo grande, que habéis alcanzado ese estado, y que ellos también pueden alcanzarlo. Vosotros sois los que verdaderamente les vais a inspirar, quienes realmente haréis que os sigan y adopten una vida de sahaja yoguis. De hecho, sois mahayoguis, si os volvéis completos. Y tenéis que volveros completos. Nada es más importante que convertirse en un mahayogui, gracias a lo cual vuestro Espíritu dará gozo, paz, y bendiciones a todos.

Que Dios os bendiga.