Puja de Cumpleaños. Delhi, India. 21 de marzo de 2002.

(Primero habla en hindi, a continuación habla en inglés)

Les estoy hablando del amor, del Amor Omnipresente de Dios Todopoderoso. Él lo ha creado todo, y este sentimiento de amor llena el ambiente por completo. Pero existe solo para aquellos que son inocentes como niños. Si vuestro odio ya se ha desarrollado mucho, entonces no tenéis salvación. Encontraréis diez argumentos que justifiquen ese odio, y llegaréis a cualquier extremo para justificarlo.

En nuestro país, que se supone que es muy moderado y muy pacífico, hemos tenido personas que solo creen en matar, en acabar con esto y con lo otro. Así que incluso en este país, en el que no creíamos en la violencia, ya llevamos muchos años cayendo en ella.

Pero básicamente somos un pueblo que cree en la paz, ya que sin ella no puede producirse ningún crecimiento; debe haber una paz completa. Cuando se tiene paz en el corazón y hay paz alrededor, entonces se desarrolla una hermosa nación. No se logra por el miedo o la presión, sino que viene del interior, de personas que tienen una paz completa en su corazón. No es que no tengan miedo de nada, sino que emiten paz. Una persona así da paz, y cualquiera que se le acerca recibe esa paz, esa sensación de tranquilidad.

Todos vosotros sois sahaja yoguis y tenéis la Realización. Eso quiere decir que vuestro Espíritu está emitiendo vibraciones de paz y gozo. Dondequiera que estáis, emitís vibraciones de paz. Generáis paz, encontráis formas de crear paz y sabéis cómo establecer un ambiente pacífico. Es muy importante que crezcáis de tal manera que generéis y deis paz a los demás, y os convirtáis en un ejemplo de ello.

No puedo creer que haya tantas almas realizadas en Delhi. Nunca lo hubiera imaginado. En primer lugar, tuve que esperar a que la gente estuviera en disposición de entender mi trabajo, porque con la división del país, mucha gente había perdido la vida o sus propiedades. Yo misma afronté todo eso, lo vi con mis propios ojos. La gente sencillamente no podía perdonar.

El perdón es un método muy bueno para entender el dolor y los problemas de los demás, pero se necesita desarrollar cierta profundidad. En vez de enfadaros, de ser vengativos, si podéis desarrollar esa paz en vuestro interior, si lográis que vuestra mente esté en paz a través del Amor divino, no necesitaréis hacer nada más. Se trata tan solo de la paz que ahora tenéis en vuestro corazón. Simplemente sentidla. Sois personas pacíficas. No se os molesta fácilmente. Nunca tendréis razones para enfadaros ni para perturbar el humor de los demás. Nunca haréis algo así. Estáis por encima de la ira y de la estúpida venganza.

Es difícil explicar esto a aquellos que no son almas realizadas, porque cuando se lo digo, no les gusta. Pero si reciben la Realización, entonces se les puede hablar. Por eso, lo mejor es expandir Sahaja Yoga. Extendedlo entre los sikhs, los musulmanes, los cristianos, por todas partes, y especialmente entre los hindúes, porque creo que actualmente están perdiendo el entendimiento de nuestro país y su cultura. Y por eso se vengan. Yo no entiendo la venganza, pero, ¿qué se puede hacer? La gente ha llegado a un nivel tan bajo que ya no entiende muchas cosas.

Por ejemplo, ahora no quieren que se construya un templo a Shri Rama en cierto lugar. Como no son sahaja yoguis no puedo explicarles que ese es el lugar en el que Shri Rama nació, y que debemos rendir todo el respeto a su encarnación. Podemos sentir que ese es su lugar de nacimiento por las vibraciones. Entonces, ¿por qué negar los hechos y la verdad? ¿Solo porque no quieren construirlo? Es muy difícil razonar con ellos.

Lo que hay que entender es: ¿Qué hizo Babar por nosotros? ¿Quién era Babar? Era un extranjero y ese lugar ni siquiera fue fundado por Babar, no lo fue. Lo estableció uno de sus jefes militares, y por eso lo llaman Babri Masjid. Pero veamos qué sucedió con este Sr. Babar. Murió, pero era extranjero. Ni siquiera era de la India. Pero no importa que no naciera allí, lo que quiero decir es que él no tenía nada que ver con ese lugar. Sin embargo, sé con toda certeza y todos vosotros también lo sabéis, porque podéis sentirlo ahora mismo en vuestras manos, que este Babri Masjid es el lugar donde nació Shri Rama.

Si se construye un templo ahí, ¿qué le va a pasar la gente? ¿Qué ocurrirá si se construye un templo en ese lugar? Es solo una cuestión de respeto y de sensibilidad. Yo también recito el nombre de Shri Rama. Todo el mundo dice el nombre de Shri Rama, porque es muy calmante y reconfortante. Pero la gente se toma las cosas de tal forma que no se puede hablar con ella.

Otra tontería de la que se está hablando mucho últimamente es que en Cachemira tienen un cabello de Mahoma. Ahora alguien dice que no es de Mahoma. ¿Cómo lo sabe? ¿Bajo qué criterio se decide de quién es el cabello? En realidad os sorprenderéis de que cuando fui a Cachemira, viajábamos en coche cuando de repente sentí unas vibraciones tremendas. Le pregunté al conductor que por qué no tomaba la carretera de al lado. Me dijo: "¿Para qué?" Le respondí: "Me gustaría ir por allí". Me contestó que era una carretera vieja y que allí solo vivían unas cuantas personas. Le dije: "No importa, cógela". Nos acercamos más y más hasta donde estaban las casas de unos musulmanes. Les llamamos y les preguntamos qué había allí. Contestaron: "El Hazrat Bal". Incluso el nombre da mucha paz. Era el cabello de Mahoma.

Así que los hindúes no quieren saber nada de Mahoma y los musulmanes no quieren saber nada de Shri Rama. Muy sorprendente. Cada uno tiene sus propias tiendas y venden sus propias cosas sin comprender que unos y otros venden lo mismo. Por ejemplo, unos lo llaman "Alá". ¿Quién es Alá? Según Sahaja Yoga, Alá no es otro que Vishnu, y Vishnu también encarnó como Shri Rama. De manera que al que llaman Alá es el mismo Shri Rama. Solo un sahaja yogui puede entender esto. Si levantáis las manos ahora, os asombraréis de las vibraciones que hay, porque es a Shri Rama, quien es Alá, a quien estáis insultando con vuestra estupidez.

Por tanto, hay estupidez por parte de los seguidores de Mahoma y por parte de los hindúes. Los hindúes tampoco lo entienden. Aunque de alguna forma saben que es el lugar de nacimiento de Shri Rama. No sé, alguien debe habérselo dicho. No sé cómo lo saben porque no conocen las vibraciones. No he conocido a muchos hindúes fundamentalistas que tengan vibraciones, los llamados "fundamentalistas" nunca las tienen. Por eso me preguntaba cómo saben que este es el janma bhumi (el lugar de nacimiento) de Shri Rama. Se habrán enterado de alguna forma, pero no pueden demostrarlo.

El problema es que si fueran almas realizadas, si los jueces del Tribunal Supremo tuvieran la Realización, si nuestro Gabinete de Gobierno fuera de almas realizadas, podríais hablar con ellos. Pero son personas totalmente cerradas. ¿Cómo explicarles que esta discusión no tiene sentido? Es perfectamente adecuado construir un templo a Shri Rama. Pero el problema es que, digáis lo que digáis, primero tienen que recibir la Realización.

En este momento en el que hablamos de esto, no hay suficientes personas que tengan la Realización. Todos vosotros sois almas realizadas. Alguien me comentó que estaba dando la Realización a estos mahantas (personas a quienes se considera santos) y que todos ellos, al recibir la Realización, eran desenmascarados, y que no sabía qué hacer con ellos. Eso os puede pasar con cualquiera, incluso en las iglesias cristianas o con los judíos, en todas partes os encontraréis con este problema.

Si les dais la Realización, quedarán desenmascarados. Entonces, ¿de qué sirve molestar a toda la gente que tiene fe en ellos y que los considera importantes? La única forma en la que se les puede juzgar es a través de las vibraciones. Pero por el amor que siento, yo no puedo decirles: "No sois almas realizadas. No os compete hablar de Shri Rama o de Mahoma, ellos están muy por encima de vosotros".

El problema está en la distancia que existe entre la gente que tiene el conocimiento y la que no lo tiene. Anteriormente existía una gran brecha entre ambos. Solía haber una sola persona realizada, a la que apedreaban, golpeaban y hacían todo tipo de cosas. Ahora sois muchos, pero si presentáis vuestros argumentos en cualquier sitio, incluso en este escenario, nadie os va a escuchar.

Os pediría una sola cosa. Y es que deis la Realización a tantas personas como sea posible, pero a ninguna de las llamadas "figuras espirituales". Porque quedan desenmascarados, ¿y de qué sirve? Es algo muy común. Muchos me han dicho: "Le dimos la Realización a un sacerdote y fue desenmascarado". "¿Y qué pasó?" "Fue descubierto, Madre, y lo metieron en la cárcel". Esto es demasiado, después de recibir la Realización, acaba en la cárcel. Este es el problema. Con el amor no se puede ser hipócrita. Para amar, hay que ser una personalidad pura. Esforzaos en purificaros a vosotros mismos. Tenéis que cambiar. Si todavía os enfadáis, si todavía sois avaros, si tenéis todos esos defectos, el amor no funcionará en absoluto.

Para amar a alguien de forma divina, lo primero es comprender el valor de la inocencia. ¿Por qué amo yo a los niños? Porque son inocentes, no tienen estos defectos. Actualmente en nuestro país ha comenzado la epidemia de la corrupción. No es fácil. En cualquiera que veáis, detrás de cualquier intermediario, se extiende la corrupción. ¿Por qué? Porque quieren dinero. De acuerdo, ¿y qué hacen con su dinero? No saben dónde esconderlo, así que lo guardan en algún recipiente o en cualquier lugar y el dinero se pierde. Si no, los cogen. Pero esto no es lo más importante.

¿Por qué tienen esta avaricia?, eso es lo importante. Los ricos son más avariciosos que los pobres, porque al menos los pobres sienten algún temor de Dios. Pero los ricos son muy codiciosos. Ansían poseer esto y lo otro, es algo que no tiene fin. Es sorprendente que esta nueva enfermedad haya aparecido en nuestro país. Como consecuencia, incluso hay gente que ha hecho negocio y gana dinero a costa de Sahaja Yoga. La avaricia es algo que os viene del lado derecho y que comenzáis a justificar. No hay lugar para el amor en el lado derecho.

Esta codicia ha llegado tan lejos que está arruinando el país entero. Así nunca progresaremos. Nunca se logra nada porque en todas partes hay gente avariciosa que se apropia de las cosas. Pero si amáis a vuestro país, si sentís amor por él, no os comportaréis así. Por tanto, falta ese amor. No sé a quién ama la gente. Aman a sus hijos de tal forma que les arruinan la vida.

El amor no tiene ningún límite. Tiene que ser ilimitado, un amor ilimitado que una al mundo entero. Esta fuerza existe, y ya está actuando, pero vosotros tenéis que convertiros en agentes de esa fuerza, tenéis que convertiros en personas capaces de comunicar ese amor. Tenéis todo el derecho de obtener esa gran riqueza de amor y podéis expandirlo a vuestro alrededor. Pero veo que incluso aquí la gente piensa en términos de dinero. El dinero es el enemigo del amor. Os aseguro que si os interesa el dinero, nunca podréis progresar en Sahaja Yoga.

Yo soy un caso perdido, estoy de acuerdo, ni siquiera sé cómo interesarme en el dinero. ¿Qué tiene de interesante? La gente se ríe de mí, y me dicen: "No sabes lo más sencillo, ni siquiera contar el dinero". Yo les digo: "Sí que sé, puedo deciros cuánto dinero hay ahí, pero no me interesa". Hay muchas otras cosas por las que interesarse. Mirad a los niños. Ved a la gente encantadora. En todo el mundo hay muchas personas hermosas y muchas cosas bellas. ¿Para qué prestar atención a esta cuestión inútil, que es algo que viene y se va? Sin embargo, yo diría que es lo que más aprisiona a la gente.

Creo que lo peor está en India. Dicen que India es el país más corrupto, pero no lo sé. Nunca he visto esa corrupción, aunque debe ser cierto. En una ocasión como ésta, es muy auspicioso que penséis que el dinero no tiene ningún valor para vosotros, que no vale nada, y os asombraréis de que nunca sufriréis escasez de dinero en absoluto., Considerar que el dinero no vale nada y no interesaros por él, es algo que debéis lograr en Sahaja Yoga. Vuestra riqueza es el número de personas que tenéis en Sahaja Yoga, a cuántos habéis traído a Sahaja Yoga, cuántas personas han obtenido este gozo. No lo habéis comprado. Nadie tiene que comprarlo. Es gratis, fluye por todas partes. Y da mucho gozo. ¿Qué más deseáis con el dinero? Nada. El dinero solo da dolores de cabeza, miedos y todo tipo de problemas.

Junto con Sahaja Yoga, deberíais llevar una vida de completa libertad y gozo, sin ninguna preocupación. Nada depende del dinero. He visto a personas que viven en muy precarias condiciones económicas y que son tremendamente felices y dichosas, mientras que aquellos que tienen mucho dinero, especialmente en el extranjero, la gente rica sufre depresiones, se dan todo tipo de situaciones extrañas, se suicidan ... ¿Por qué? Si el dinero lo es todo, ¿por qué se suicida la gente en los países ricos? ¿Qué consiguen con ello? Piensan todo el tiempo en cómo seguir cualquier moda. Allí están las modas y si no se tiene dinero, no se pueden seguir. Se han convertido en algo tan común, que la gente aspira a seguirlas. Y si no las pueden seguir, piensan que algo no funciona, etc. Pero vosotros no pensáis así, porque sois sahaja yoguis.

Observáis todos estos hechos, ¿y qué debéis hacer? Tened compasión por esas personas; no desprecio, sino compasión, y decidles: "¿Qué estáis haciendo? ¿Por qué perdéis el tiempo así? Este es el mejor momento para que alcancéis la meta más alta de vuestra vida, la Realización del Ser, ¿por qué anheláis todo eso? ¿Qué os hace participar en esta carrera tan degradante?"

Creo que en todo el mundo nos encontramos en un momento de cambio y que la gente está reflexionando. Deberíais ser vosotros los que les proporcionaran una solución. Podéis lograrlo a gran escala. He visto a gente que no tiene nada en su interior. No son espirituales ni son personas que puedan dar la Realización. Pero son muy famosos porque llevan a cabo alguna obra social. ¿Qué es el trabajo social? Cuidar de los pobres y cosas así. Ahora bien, cuando vuestro amor que es tan grandioso y tan efectivo comienza a funcionar, sentís que tenéis que hacer algo. Entonces os sorprenderéis de cómo la gente entenderá Sahaja Yoga.

Hasta ahora, Sahaja Yoga funciona bien, los sahaja yoguis son muy agradables, muy buenos y santos. Pero se deben ver sus efectos, la gente tiene que sentir los efectos de vuestro amor. Lo primero es el perdón. Tenéis que perdonar a los demás. Son totalmente absurdos, ya os acabo de explicar lo estúpidos que son. Por eso, no tenéis que preocuparos. Si sois personalidades sabias, tenéis que intentar juzgarlo todo con sabiduría y no caer en la trampa de sentir que tenéis que hacer ciertas cosas porque está de moda o porque lo hacen determinados grupos. No es necesario, porque somos sahaja yoguis. Somos autosuficientes, no necesitamos nada. Si somos uno, estamos bien, si somos muchos, también.

Debéis saber que habéis alcanzado un estado muy elevado y que habéis sentido ese amor, el Amor universal de Dios. Por tanto, expresad más ese amor en vuestra vida diaria, en el trato con los demás y de tal manera que les hagáis felices. Debéis reflexionar sobre esto. ¿Cómo podéis discutir cuando sois verdaderos sahaja yoguis? ¿Cómo podéis humillar a otros siendo sahaja yoguis? ¿Cómo podéis engañar a otras personas si sois sahaja yoguis? No es posible. No deberíais tener ningún interés en estas cosas. Eso significa que habéis sido purificados y que estáis limpios, y que ahora sois nirmal (puros). Nadie os puede tocar.

Deberíais tener este tipo de actitud, este respeto y este entendimiento sobre vosotros mismos. ¿Cuál es vuestro papel? ¿Cuál es vuestra posición? Debéis saber que sois almas realizadas y lo que tenéis que hacer como tales. No sois como los otros locos en su triste y absurda carrera, ni tampoco estáis en ninguna competición. No competís contra nadie. Simplemente progresáis gracias a vuestro amor y a las bendiciones.

Sé cómo funcionan las bendiciones, pero antes que nada, tenéis que ser dignos de esas bendiciones, si no, no se puede hacer nada. Debéis ser amorosos. Por eso Cristo dijo que para entrar en el Reino de Dios hay que ser como niños. Vosotros ya estáis en el Reino de Dios, pero tenéis que ser como niños. ¡Qué inocentes son, qué sencillos! Y son felices con las cosas más pequeñas. No les gustan las cosas extraordinarias. Es muy sorprendente cómo nuestro amor, que de hecho está iluminado por el Amor divino, puede cambiar el mundo entero. Yo tenía esta idea y ha prosperado. Si todos me ayudáis, estoy segura de que Sahaja Yoga puede hacer muchas cosas que todavía no se han logrado.

Ahora iros a casa y pensad en todo lo que os he dicho. Reflexionad sobre ello. Lo que necesitáis es introspección. Necesitáis comprender: "¿Qué he hecho con mi vida como sahaja yogui?" Entonces descubriréis que podéis hacer muchísimo. Y que hay que hacerlo.

Que Dios os bendiga.