4 mayo 1985
Sahasrara Puja
Laxenburg (Austria)
Charla antes del Sahasrara Puja: "Tenéis que estar en Nirvikalpa". Viena, Austria. 4 de mayo de 1985.

Es muy gratificante ver que tantos sahaja yoguis han venido para celebrar el día del Sahasrara. Sin abrir el Sahasrara no podríamos haber alcanzado el ascenso en masa. Pero en Occidente el Sahasrara, que es el cerebro, ha entrado en muchas complicaciones y los nervios están muy retorcidos unos sobre otros.

Mantener el Sahasrara abierto debería ser muy fácil si los cerebros occidentales pudierais entender y ser conscientes de vuestra Madre. Al ser vuestra Madre la Deidad del Sahasrara, el único modo de mantener el Sahasrara abierto es la completa entrega. Para ello muchos me preguntan: "¿Cómo podemos hacerlo?" ¡Es una pregunta muy graciosa! Es irrelevante. Si vuestro Sahasrara ha sido abierto por alguien, y afortunadamente estáis frente a esa Deidad, debería ser muy fácil entregarse a Ella. Pero no es así. Es difícil porque la atención -que ha aparecido a través de las células del cerebro, que se expresa a sí misma a través de las células del cerebro- está contaminada, es impura; es destructiva y echa a perder los nervios. Y cuando los nervios se echan a perder la luz del Espíritu no brilla en ellos y os sentís incapaces de entregaros. Normalmente debería ser lo más fácil de hacer.

De modo que debemos encararnos a nosotros mismos mentalmente. Debemos hablar con nosotros mismos y decirnos: "¿Qué estás haciendo?", ¿qué es la entrega? ¡Es gozar! ¡Es simplemente gozar! Entonces, ¿por qué no puedo entregarme?, ¿qué falta en mí? ¿Acaso soy una persona de un nivel muy bajo? ¿Acaso digo que soy un buscador pero en realidad no lo soy? ¿Acaso soy una persona deshonesta que no puedo rendirme? Si es así, ¿por qué habría de estar orgulloso de mí mismo? Si esta es la situación, ¿por qué estoy tan enamorado de mi ego?

¿Qué tenéis que entregar? Una gota ha de disolverse en el océano para volverse el océano. Y una gota no puede ser más grande que el océano, ¿podría serlo? ¿Qué es la entrega entonces? Es entregar vuestros condicionamientos, vuestro ego y las barreras artificiales que hemos construido a nuestro alrededor. Uno puede abordar esto mentalmente. Uno puede encararse a sí mismo emocionalmente y también físicamente. Uno puede encararse a sí mismo a través de mantras, a través de vernos a nosotros mismos, a través de conocernos a nosotros mismos. Pero uno debería saber que esta es la más grande de las oportunidades para vosotros, no para el Divino.

Si vosotros no estáis disponibles el Divino puede encontrar sus propios modos de satisfacer la última culminación de su expresión. Incluso para entender cuán inmensa es la tarea necesitáis un corazón entregado. Si sólo lo afrontáis de un modo mental llegaréis a desarrollar un ego mezquino con la idea de que estáis haciendo un gran trabajo.

Como cuando telefoneé a América para decirles que iba a ir. En Los Ángeles hay un gran científico indio, de Maharashtra. No le dieron el premio Nobel, un científico tan grande. Inmediatamente me telefoneó y me dijo: "¡Madre, voy a ir a Nueva York a recibirte! Voy a coger quince días de vacaciones. Mientras estés aquí quiero estar contigo. ¿Qué otra cosa hay que hacer? En realidad estoy haciendo Sahaja Yoga de pasada, a mi propia conveniencia, solo cuando me viene bien; eso es lo que estoy haciendo. Pero me gustaría viajar contigo a Europa, a todos los lugares, y pasar algún tiempo contigo. De otro modo, ¿qué estoy haciendo aquí?"

Pero he oído que la gente está llegando en diferentes momentos para el día del Sahasrara. Me quedé sorprendida. Esto es típico de la mente occidental. Todo es "de paso", Sahaja Yoga se hace principalmente de pasada. Si nos viene bien. Debe ser en fin de semana, y de paso podemos pasar por Viena para tener unos días de vacaciones. Por supuesto, de paso tendremos el puja y también de paso Madre elevará nuestra Kundalini. Ella despertará a nuestras deidades y de paso gozaremos de las bendiciones. No podemos hacer ningún sacrificio por Dios. No hay tiempo, ellos no tienen tiempo. ¡Todo es de paso! ¡Es muy sorprendente! Para la guerra la gente abandona toda su vida. Para la destrucción trabajan muy duro desde la mañana hasta la noche. Pero para la construcción de la humanidad, para obtener el destino final de la Divinidad, en Occidente, ¿cuántos están realmente entregados? Si nos encaja, entonces lo haremos. ¡Sahaja! "¡Este es el estilo sahaja! ¡Debemos ser sahaja!" He oído esto muchas veces y aún hay muchos que tienen este tipo de actitud hacia Sahaja Yoga. Esto a veces me sorprende.

Si voy a un pueblo, la gente cogerá quince días o un mes de vacaciones. En Rahuri la gente coge un mes de vacaciones para prepararse para mi llegada. Para ellos un solo día de vacaciones es algo muy grande. Estas son las personas que lo merecen. No se trata de cómo os vestís ni qué coméis ni lo que tenéis. Se trata de cuánto podéis entregar y abandonar. Las ataduras de la vida mundana han de ser eliminadas, debemos entender esto. Se trata del progreso de gente que, como esclavos, están atados con cadenas -cadenas de deseos, cadenas de complacencias, cadenas de letargo, cadenas de ego- que son una carga. De modo que tenemos que entendernos a nosotros mismos. Todo el mundo ha de entenderse a sí mismo y también entender que, a través de vosotros, ha de venir la salvación del mundo.

Vosotros habéis sido elegidos para la emancipación de toda la Humanidad. El Divino quiere que trabajéis como canales para embellecer a este Universo, para la expresión última del Amor de Dios. Cuando digo esto descubro que, de repente, aparece automáticamente un ego. Por el contrario, debería haber entrega para llenar vuestros recipientes con la dicha -la dicha de la Divinidad- de modo que cuando fueseis a los demás vertieseis sobre ellos la belleza y el Amor de Dios. Debéis entenderos a vosotros mismos muy bien y no a los demás. No culpéis a nadie.

Estos momentos que estamos compartiendo juntos, son tan preciosos que las palabras no pueden describir su grandeza. Debéis sentir en vuestro interior la misión que se os ha encomendado a través de vuestro propio Espíritu. A través de vuestro propio estado podéis cumplir esta misión. Pero la falta de fe en vosotros mismos no puede daros los poderes para entregaros. La entrega es la apertura del Sahasrara, manteniéndolo completamente abierto para que el estado de Nirvikalpa se establezca en nosotros.

Debería haber un progreso regular de mejora, un progreso regular de apertura. ¿Habéis visto alguna vez un loto o alguna flor que florezca, después deje de florecer, de nuevo florezca, después se desmorone y después vuelva a florecer? ¿Habéis visto alguna vez en la naturaleza un fenómeno tan estúpido? Ascendéis, después descendéis, volvéis a ascender y de nuevo volvéis a caer. ¿Habéis visto alguna vez un árbol que se eleve, de nuevo vuelva dentro del barro, de nuevo se eleve, de nuevo vuelva al barro y culpe a otra gente de ello? ¿Habéis visto alguna vez a un animal que empiece a crecer, de nuevo se haga pequeño, de nuevo crezca y de nuevo vuelva a hacerse pequeño? Incluso estos grandes palacios que han construido tan bellamente para nosotros, ¿habéis visto que de repente se hagan pequeños, de repente se desmoronen y de nuevo se vuelvan a levantar? Solo el balón del ego y del superego hace esto. Y cuando os identificáis con ellos os volvéis personalidades muy peculiares.

El loto de vuestro Sahasrara está ahora abierto. Debe abrirse más y más y más; y no derrumbarse, abrirse de nuevo y volver a derrumbarse. Este es un fenómeno muy complicado que podemos ver en Occidente y que a veces os puede sorprender mucho. A mí me resulta muy chocante ver esto. De repente alguien vendrá y dirá: "¡Oh, estoy muy nervioso con esto o aquello!"

Otra persona vendrá y dirá: "¡Quiero dejar Sahaja Yoga!"

Otro vendrá y dirá: "¡Oh, esto es demasiado! ¡No puedo seguir con ello!"

Debemos darnos cuenta de que hay algo muy peculiar en nuestro interior, hay algo absurdo en nuestro interior. Por eso sucede esto. Avanzamos, retrocedemos, avanzamos y retrocedemos continuamente. ¿Qué es este péndulo? ¡No puede ser el Sahasrara! El Sahasrara no es un péndulo, es un loto. Este péndulo es "chitta", la atención; la atención que se mueve desde la izquierda a la derecha, de la derecha a la izquierda, y así sigue continuamente.

Pero el Sahasrara es el Reino de Dios. Cuando el Brahmarandra se abre plenamente, entonces los cielos se abren en nuestro interior. La Kundalini que se ha elevado y os ha dado la Realización, crea la apertura sutil por la cual el Divino empieza a derramar todas sus sutilezas en el interior de vuestro cerebro. Pero si vosotros estáis presionándole desde ambos lados con estos balones, entonces, a veces se abre a veces se cierra, se vuelve a abrir, y el Divino retira su atención. Debéis saber esto. La atención es retirada y si hacemos esto muchas veces el Divino deja de preocuparse.

De modo que sois vosotros los que tenéis que alcanzar este estado. Todos nosotros podemos alcanzar el estado de Nirvikalpa. En él solo hay progreso. Después de Nirvikalpa no podéis descender. Si alguien aún continua subiendo y bajando debe saber que aún no ha llegado a este punto y debe afrontarse a sí mismo; decirse a sí mismo: "¡No! ¡Debo permanecer en Nirvikalpa, donde ya no desciendo más!"

Las personas que no estén en el estado de Nirvikalpa no van a ser salvadas. Siento tener que decirlo. ¡No van a ser salvadas! ¡Serán castigadas! Quizás no del mismo modo que aquellos que no son almas realizadas, pero no ocuparán los asientos en el Reino de Dios Todopoderoso. Al menos debéis alcanzar el estado de Nirvikalpa. ¡No culpéis a ninguna circunstancia! ¡No culpéis a vuestro padre, madre, hermano, atmósfera, a esto o aquello! ¡No hay necesidad de culpar a nadie! Alguien dijo: "¡Somos influenciados por cualquiera!" ¿Qué pasa con vosotros? ¡Yo estoy aquí y no sois influenciados por mí! ¿Cómo sois influenciados por alguien que es tan estúpido, y obviamente tan dominante? Esto muestra cuál es vuestro nivel.

De modo que he decidido deciros mañana cómo permanecer en el estado de Nirvikalpa. Como os he dicho, nos podemos aproximar a ello mentalmente; pero si os digo mentalmente que os toméis esta medicina y vosotros no la tomáis se quedará simplemente a nivel mental. La medicina se guarda en el armario y vosotros seguís igual. Entonces diréis: "¡Madre, escuchamos tus charlas!" De modo que he decidido que el punto principal, del puja de mañana, es que tenéis que estar en el estado de Nirvikalpa.

Podéis decir que este día del Sahasrara es un gran día porque nunca anteriormente lancé tal ultimátum. Porque ahora nos hemos establecido como Vishwa Dharma, como la religión universal. Nosotros no somos como otras religiones donde, después de la muerte de las encarnaciones, cuando la gente comenzó las religiones lo hicieron a su propio modo. En nuestro tiempo de vida tenemos que hacer de nosotros mismos un instrumento que represente el Vishwa Dharma. Debemos tener deidades fuertes en nuestro interior. Las hemos debilitado con todos nuestros errores, ¡no importa! Son débiles porque tradicionalmente no hemos tenido la fuerza, ¡no importa! Pero ahora que esta religión se ha establecido ya no podemos tener manchas negras nunca más. Hemos hecho todas nuestras elecciones, el entrenamiento y todo lo demás; ahora todos vosotros tenéis que saltar al barco.

Ya no nos queda más tiempo para seguir vacilando. Aquellos que se retrasen serán dejados atrás. Este es un periodo muy intenso, ¡debéis entenderlo! La intensidad de este periodo no es para hacer las cosas "de paso". Esto ya no es Sahaja Yoga. Ahora es Maha Yoga. Y vosotros tenéis que volveros Maha, tenéis que volveros grandes, de otro modo no podréis permanecer aquí. ¡Tenéis que saltar fuera de todas esas cosas!

Mañana intentaré por mi parte todo lo que sea posible. ¡Lo haré funcionar! ¡Pero esta es una cuestión muy seria, debo decíroslo! Una vez que hemos establecido la religión no quiero ningún agujero en ella. Hasta ahora lo he evitado porque no estaba segura. Ahora tengo la seguridad de que hay muchos que podrían ser llamados Nirmalitas. Pero no debe haber más manchas negras en el bello sari de vuestra Madre. Ha de ser absolutamente de la más alta calidad. Gradualmente solíamos echar a alguna gente y hacerlo funcionar así, pero ya no queda más tiempo. Como os he dicho, me vuelvo a India.

Mañana os diré cómo habéis ascendido gradualmente hasta vuestro Sahasrara. Y para alcanzar Nirvikalpa, verdaderamente, ¡os tenéis que dedicar completamente! No se trata de venir a Sahaja Yoga cuando os viene bien. Este es el día del Sahasrara y tenéis que cruzar los Himalayas. Si leéis acerca de la vida de aquellas personas que intentaron ascender al Kailasha sabréis las penalidades que tuvieron que pasar. Yo os he llevado muy dulcemente y delicadamente hasta ese punto, pero no os echéis a perder por eso. Todos vosotros os esfumaréis en el aire a menos que alcancéis el estado de Nirvikalpa.

¡Siento haber tenido que decir esto en Austria! Este es el lugar que debería marcar el final de nuestro viaje de la izquierda a la derecha. "Porque mi esposo es así, mi esposa asá. Porque mi hijo es de tal modo." ¡No vais a ser excusados! ¿A quién se lo estáis diciendo? ¿A vuestro propio Espíritu? ¡Decídselo a vuestro Espíritu!, ¿acaso lo entenderá? Esto se lleva vuestras vibraciones, se lleva vuestro gozo, se lleva vuestra posición. Es muy fácil establecer Nirvichara, pero incluso eso alguna gente no lo ha alcanzado. ¿Entonces qué pasa con Nirvikalpa? ¡Debéis tomaros esto muy en serio!

Este podría ser el último día del Sahasrara que celebramos en Europa, quizá, ¡no lo sé! No se trata de que Madre solo esté feliz con la gente de la más alta cualificación o del más alto calibre, ¡no es eso! Yo tengo una gran preocupación por aquellos que están perdidos o que están fuera. Pero algunas veces, a través de mi experiencia, creo que esta gente se echa a perder. Mi Amor no es para echaros a perder, no es para arruinaros, es para vuestra emancipación, es para que gocéis de la belleza de las bendiciones del Divino sobre vosotros.

Pero incluso ahora hay gente que no es correcta, que no es genuina, que no es virtuosa a nivel del dharma; entonces, ¿qué puedo hablar con ellos? Y si ni siquiera son el Espíritu, entonces, ¿qué voy a hacer con ellos? Las ideologías, las charlas, las discusiones y los argumentos no os van a llevar allí. De ningún modo. ¡Es la meditación! Y la meditación, en realidad, es encararos a vosotros mismos y corregiros a vosotros mismos con la total comprensión de lo que sois.

Tenemos que crear seres humanos ideales. Esto es el Vishwa Dharma. Por el contrario tenemos otros muchos dharmas que aún continúan. Hay muchas actividades religiosas en el nombre de todas las grandes encarnaciones que -de ningún modo están cerca de las encarnaciones- son justo lo opuesto a ellas. Este estado de Nirvikalpa ha de ser establecido de una vez por todas. De este modo no tendré que luchar más con vosotros. El grupo de personas que asista mañana al Sahasrara Puja, debería ser capaz de establecer este estado, de otro modo serán simplemente como la gente nueva. Vienen por primera vez o por décima vez o cien veces, ¿qué diferencia hay?

Para mí está muy claro. Tengo poco tiempo, y los instrumentos han de estar bien. Tenéis que agilizar el crecimiento del instrumento de un modo apropiado, para que el Amor de Dios fluya y para que el Dios de ese Amor se sienta contento con ello. Tenemos que crear bellas flores, que Él aprecie, para que no las destruya. El espectador de este juego ha de estar satisfecho de modo que Él posponga su destrucción. Por eso digo que el tiempo es corto, ¡muy corto!

Si queremos que nuestros hijos crezcan en el Reino de Dios -ellos que son grandes santos que han nacido- si queremos darles todas las posibilidades de gozar entonces seamos, antes de nada, padres apropiados y no gente que sólo vive con espejismos. En Sahaja Yoga no se puede explicar todo. No se puede explicar, no se puede porque vosotros no tenéis los poderes para entenderlo.

Como Gregoire que dijo: "¡Madre, quiero que salga el sol!", porque la gente dijo que el fin de semana sería terrible, que no habría sol. En quince minutos el sol estaba brillando, en quince minutos. El viento empezó a soplar y todas las nubes se movieron hacia las afueras de Viena de un modo muy bello. El cielo se abrió como un Sahasrara, como yo quiero que se abra vuestro Sahasrara.

Toda la naturaleza está ansiosa de trabajar, pero vosotros debéis aprender a cooperar con vuestro Espíritu. Y esta cooperación no es para hacerlo de paso. Es para ser el Espíritu, para convertiros plenamente en el Espíritu. Es muy importante. Nada debería detener esto. Espero que la declaración de hoy nos ayude a todos nosotros a tener la comprensión de nuestras responsabilidades hacia nosotros mismos y hacia nuestro Creador.

Está muy bien que me alabéis por mi Amor, está bien que me alabéis por cualquier cosa que ha sucedido pero, para ser franca, ¡yo no sé si me estáis alabando! ¡Yo no siento las alabanzas porque yo misma no soy yo misma! Me veo a mí misma como algo separado y entonces me digo a mí misma: "¡Mira, tú eres la Adi Shakti! ¡Muy bien, pero has echado a perder a tus niños! No has sido justa con ellos. Toman todo muy a la ligera y de una forma muy mundana".

De modo que mañana debéis tomar un voto en vuestro corazón. Las palabras no son importantes. Ha de ser una acción viviente de vuestro Ser, la que debe probar y convenceros de que estáis completamente entregados. Y el efecto de ello lo sentiréis en vuestra propia personalidad, en vuestro propio Ser, en vuestra propia manifestación.

Con tantos santos, ¿por qué debería preocuparme yo de extender Sahaja Yoga? Pero algunas personas os arrastran hacia atrás, alguna gente es inflexible, algunos otros aún están poseídos y algunos son almas insidiosas. Simplemente no pongáis ninguna atención en ellos. ¡Todos ellos se perderán, no importa! Debemos crear un gran día para que estemos orgullosos de pertenecer a esta gran religión verdadera. Hasta ahora no ha habido ninguna religión verdadera, predican una cosa y practican otra y no tienen nada que ver con las encarnaciones. Vosotros debéis hacer algo por lo que la gente pueda decir: "¡Vemos a vuestra Madre en esta persona!"

¡Hoy quiero bendecir a algunos niños! Yo he bendecido a muchos niños. También quiero bendecir a los padres, para que entiendan que tienen que contribuir mucho en la educación de sus hijos. Hay algunas cintas muy buenas, que han hecho en Inglaterra, acerca de cómo ayudar al niño a crecer apropiadamente en esta loca vida occidental. Y Freud que fue uno de vuestros mayores enemigos trabajó en este lugar. Él es el que os ha arruinado y os ha hecho cometer pecados en contra del Espíritu Santo, pecados en contra de vuestra Madre.

Ahora, en este momento y en este lugar, tenemos que apartar nuestro rostro de todo el pasado y ascender a un nuevo reino de dicha y gozo. Os aseguro que con vuestra dedicación funcionará. Pero simplemente pensad en vuestra mente, ¿qué habéis sacrificado hasta ahora? Ningún sacrificio es suficiente, pero, ¿habéis sacrificado algo? Esto os hará entender que vuestra Madre os ha dado vuestro segundo nacimiento sin ninguna dificultad. Ella ha tomado todos los trabajos dolorosos sobre sí misma. Ahora sois adultos y tenéis que entender que cuando sois adultos no podéis comportaros como niños. Eso ya se ha acabado. Ahora sois adultos y tenéis que volveros responsables de este Maha Yoga, y para ello este gran dharma ha de ser establecido. El dharma que integra todos los otros dharmas. El dharma que purifica a todo aquel que se acerca a él. Es el océano de todos los ríos. Todos los ríos fluyen hacia este gran océano de Vishwa Dharma.

De modo que tenemos que moldearnos a nosotros mismos para adaptarnos a esta nueva forma, a estos nuevos ritmos, a la nueva música de la flauta divina. A menos que suceda esto, no creo que la gente occidental tenga muchas posibilidades. ¡Si habéis venido para el Sahasrara estad preparados! Mañana me gustaría que funcionase lo máximo posible. Yo trabajo durante veinticuatro horas. No malgasto ni un solo minuto. Del mismo modo espero que vosotros os dediquéis veinticuatro horas para vuestra emancipación y para la emancipación de todo el Universo.

Que Dios os bendiga a todos. Que Dios os bendiga.

¡Gracias! ¡Muchas gracias por esta promesa! ¡Hoy le estoy agradecida al viento, al Sol, y a todos vosotros por esta promesa!

¡Yo soy muy simple e inocente! Shri Mataji es complacida muy fácilmente pero no hagáis juegos conmigo. ¡No juguéis conmigo! La inocencia también puede ser muy poderosa. ¡No juguéis conmigo!

Creo que ahora debemos meditar durante diez minutos, sería buena idea.

Gregoire: Shri Mataji sugiere que ahora meditemos juntos durante diez minutos, de modo que cerremos los....

¡Mantened vuestros ojos abiertos!

Gregoire: Yo iba a decir que cerraran los ojos.

Yo estoy sentada aquí, ¿sobre qué otra cosa vais a meditar? ¡Meditad sobre mí! ¡Mantened vuestros ojos abiertos, simplemente mantenedlos abiertos! Ahora todos los niños deben poner sus manos de este modo, ¿de acuerdo? ¡Y miradme!

Levantad vuestras lenguas y ponedlas hacia atrás lo máximo posible. Volvedlas hacia atrás. Permitíos sentir la dicha del Divino en la punta de la lengua. Ahora poned vuestra barbilla hacia abajo, tocando vuestro... No cerréis los ojos. Bajad vuestra barbilla en completa entrega. Pero no cerréis los ojos. Poned la atención en vuestro Sahasrara. Aflojad vuestras manos totalmente, dejadlas relajadas. Sentaos derechos.

No toquéis el paladar. Ahora inspirad. No empujéis la lengua hacia atrás. Mantenedla donde está. Inspirad. Ahora levantad vuestro estómago hacia arriba sin soltar el aire, empujando el aire hacia arriba hacia los pulmones. Empujad vuestro estómago hacia adentro. La atención en el Sahasrara.

Así empezáis a ver la Luz a través del Sahasrara. El Sahasrara pasa a ser vuestros ojos. Ahora dejadlo. Dejadlo ahora. Levantad vuestra cabeza. Poned vuestra cabeza hacia atrás. Poned vuestros dedos en los oídos. Poned la atención en el Sahasrara, eso es todo. No digáis nada, ningún mantra.

Sacad vuestra lengua y empujadla hacia atrás. Inspirad. Empujad el estómago. Así está bien.

Ahora miradme continuamente, sin parpadear. Sin ninguna presión en los ojos. La atención en el Sahasrara. Podéis hacerlo sin parpadear.

Que Dios os bendiga. Esto es físicamente, hemos trabajado nuestra atención en nuestro Vishuddhi y en nuestro Agnya. El Vishuddhi izquierdo aún continúa ahí. Ahora poned vuestra cabeza más hacia el lado derecho, relajadamente, de este modo. Con la atención en el Sahasrara, miradme. Relajarlo. La mano ha de estar relajada. Relajadla.

Ahora está mejor. ¿Podéis sentir la Kundalini elevándose? Ahora nos hacemos un bandhan después de subir la Kundalini. ¡Elevadla! ¡La atención en el Sahasrara! No cerréis vuestros ojos, echad la cabeza hacia atrás. Uno. De nuevo. Sentaos derechos.

¡Subidla a vuestra cabeza! Dos..., tres. Ahora el bandhan. Uno, dos. ¡Hacedlo apropiadamente, sistemáticamente! Todos nosotros debemos hacerlo apropiadamente. Tres..., cuatro..., cinco... Intentad esperar, igual que lo hago yo..., seis..., siete. Aún no lo hemos hecho apropiadamente. Todos nosotros debemos hacerlo al unísono. Hagámoslo de nuevo. Uno, despacio..., dos, con la atención en el Sahasrara..., tres... ¡Cómo lo hago yo...! Cuatro..., cinco..., bien..., seis. La atención en el Sahasrara..., siete.

¿Está subiendo? ¡Atémosla por última vez...! ¡Ved ahora!

¿Está claro? ¡Tremendo!

Que Dios os bendiga.

Gregoire: Si me lo permites me gustaría decir que si hay alguna persona que no puede decidir que Sahaja Yoga es lo más importante de su vida, no debería venir mañana al puja.

¡Por supuesto! Para el puja de mañana no debería haber nadie que al menos no haya alcanzado el estado de Nirvichara. Esto quiere decir que si aún piensan: "¡Sahaja Yoga no encaja conmigo!", y todo esto, no queremos esta gente tan mediocre. Por favor no vengáis. Nada funcionará con ellos, para mí son gente absolutamente inútil. Si tienen que venir al puja deben saber que deben ser de cierto calibre de otro modo, ¡por favor!, que no vengan. Hay muchos que piensan: "¡Sahaja Yoga es la solución y yo he sido elegido para esa solución!" Solo esta gente debería venir mañana.

Pero no la gente que piensa de otro modo. ¡Por favor, perdonadme! ¡Quiero que me perdonéis! No puedo teneros para el Sahasrara Puja. Con gente tan inflexible y tonta es demasiado trabajo para mí. No quiero que venga gente tan inflexible y absurda. Si piensan que lo hacen por compromiso, deben saber que para mí no hay ningún compromiso, pero sí para vosotros. Por favor que nadie de este tipo venga. Puedo sentirlo. Hay algunos así sentados entre vosotros. De modo que esta gente no debe venir a molestarnos. Deben salir de Sahaja Yoga, limpiarse fuera y después volver. No sé qué posibilidades tendrán, pero en cualquier caso así ha de ser.

Debéis saber que venir a Sahaja Yoga es un privilegio especial y cualquiera que no piense así no debería estar aquí. Yo os lo agradecería mucho. ¡Muchas gracias!