Guru Puja, Cabella Ligure (Włochy), 4 Lipca 2004.

To dla Mnie ogromna przyjemność, największa radość, widzieć tak wielu Sahaja yoginów na Guru Pujy. To daje dużo satysfakcji myśleć, że tak wielu, że tak wielu z was jest uczniami. 

Nigdy się nie spodziewałam, że będę miała tak wielu, tak wielu ludzi, podążających za Mną. Istnieje nadzieja, że wy wszyscy podążycie za Moim przesłaniem miłości. Nie muszę nic mówić o miłości. Miłość jest absolutnym darem, po prostu darem odczuwania innych. Nie ma co o tym mówić, dyskutować o tym, nic z tych rzeczy, po prostu czujecie tę miłość. Powiedziałabym, że aby czuć tę miłość, trzeba mieć serce, ale jak można mieć serce? To nie wasze działanie, to wszystko istnieje. To jest coś, co wam już podarowano, macie to, możecie odczuwać tę miłość. To daje tyle radości, tyle spokoju. Miłość ma swoje własne cechy i jedną z nich jest to, że miłość rozumie. Jej zrozumienie nie zawiera się w słowach, ani w myślach, lecz ona rozumie wewnątrz. Ona potrafi odczuwać wewnątrz, to jest bardzo ważne. Najważniejsze w tym jest to, aby uświadomić sobie, że tę miłość można tylko odczuwać. Nie da się o niej mówić, nie da się jej przedstawić, ale ona jest wewnątrz i możecie ją odczuwać. 

I dlatego właśnie dziś świętujecie Guru. To jest święto, kiedy możecie odczuć tę miłość dla swojego Guru. To uczucie jest wewnątrz i tylko wewnątrz możecie je odczuwać. Więc powinniśmy zrozumieć, że to nie jest pokaz, to nie jest nic innego, jak tylko wewnętrzne odczucie, gdy wiecie, że macie Boską miłość. Możecie ją mieć, gdyż ona po prostu istnieje. Nikt nie może wam tego dać, nikt nie może tego sprzedać, nikt nie może tego podzielić - to po prostu istnieje. I tę miłość trzeba poczuć i dzielić się nią. To nie ma nic wspólnego z innymi, czy ktoś was kocha, czy nie, to nie robi różnicy. To jest uczucie wewnątrz was, tam istnieje ta głębia, którą się cieszycie. 

To jest zdolność każdy to ma, mnóstwo tego. Czasami czujecie, że to utraciliście, czasami czujecie, że to zdobyliście, ale to istnieje tak samo jak bezmiar morza. Nie możecie powiedzieć o morzu, że dzisiaj jest pełne, a jutro nie jest. To jest wieczne. Tak samo źródło waszej miłości jest wieczne. Nie możecie tego zmierzyć, to jest trudne. To wykracza poza wszelką ludzką ekspresję i ujawnia wasze zrozumienie, wasze zrozumienie miłości, która nie ma słów, której nie można wyjaśnić, ale sami będziecie wiedzieć, że "mam tę cechę kochania wewnątrz siebie i potrafię cieszyć się tą miłością wewnątrz siebie". To bardzo unikalny dar, który posiada tylko niewiele istot ludzkich. Wśród zwierząt także znajdziecie ludzi, którzy mają miłość, ale ta miłość nie jest głęboka, ta miłość nie ma znaczenia. Być może ma to jakiś cel, ale to nie jest ludzkie, więc brakuje temu piękna ludzkiej miłości, brakuje temu zrozumienia ludzkiej miłości. 

Nie łatwo jest opisać lub objaśnić miłość ludzkimi słowami. To możecie tylko odczuć wewnątrz siebie. To jest coś takiego, że kiedy raz to poczujecie, wtedy będziecie potrafili odczuwać, kto według was jest waszym Guru, kto was uczy, kto wam tłumaczy i skłania do życia w określony sposób. To wszystko jest możliwe. Wszystko jest możliwe, możliwe w ludzki sposób, ale kochać i cieszyć się miłością nie jest tak łatwo, dopóty, dopóki nie zanurzycie się w niej. To bardzo miłe i bardzo słodkie, widzieć jak ludzie wzajemnie się kochają i jak ta miłość się rozprzestrzenia. Miłość rodzi miłość. Jeśli ktoś ma miłość, to ona po prostu się rozprzestrzenia. Nie musicie nikomu mówić, nie musicie jej wyznawać, a ona i tak się rozprzestrzeni. I to jest to, czego trzeba się nauczyć, jak dostrzec tę miłość w innej osobie. 

W jakiś sposób, z powodu Sahaj wydarzenia mamy już tutaj miłość. Wszyscy kochamy i cieszymy się miłością; to że kochamy, widać na naszych twarzach widać w naszych charakterach, w naszym życiu widać to że kochamy. Cóż to za rzecz, która nie jest zwyczajna, a staje się tak zwyczajna i tak łatwo dostępna. To bardzo wielkie błogosławieństwo, że jesteście istotami ludzkimi i że istnieje to źródło miłości, plus istnieje to uczucie miłości. To bardzo złożona sytuacja, której nie da się wyjaśnić słowami, można tylko w tym być i cieszyć się tym. 

Więc dziś jest dzień, kiedy świętujemy Guru Puję. Największym Guru, jakiego mamy, jest miłość, Sahaj miłość. To jest Guru w nas, który nas uczy, który w taki czy inny sposób nas prowadzi. Jesteśmy prowadzeni ku tej wspaniałej drodze zrozumienia, dla której nie musimy chodzić na żadną uczelnię ani do żadnej szkoły na naukę. To jest coś, aż tak wewnątrz, że to działa i objawia się samo, objawia się jak światło. Takich ludzi potrafimy odróżnić, gdyż oni są całkowicie oświeceni. Oni mają światło i poprzez to światło widzą cały świat, to jest dla nich bardzo niewinne i proste. 

Naturalnie mamy miłość dla naszych dzieci, naturalnie mamy miłość dla naszych rodziców, mamy miłość dla niektórych ludzi, ale ta miłość różni się od miłości Boga, o której wam mówię. To ma wprawdzie powiązania, jakieś znaczenie, ale ta miłość, która jest nie można jej opisać słowami, trzeba ją poczuć wewnątrz. Tak samo, kiedy mówicie o swoim Guru, powinniście mieć tę miłość w sobie. Dlaczego odczuwacie to tak mocno? Powodem jest to, że Guru was kocha i wy kochacie Guru. To jedyny powód, dla którego powinniście kochać swojego Guru. Obecnie nie ma powodu do tego, ponieważ miłość jest miłością i w ten oto sposób Guru staje się w życiu bardzo ważny. Mamy ludzi, którzy kochają swojego Guru, i którzy bardzo czysto pojmują swoją miłość. 

To wspaniała okazja do miłości, że jesteśmy, że jesteśmy tutaj, aby z całego serca, w pełni cieszyć się sobą nawzajem i że ten ocean istnieje w nas. Musimy tylko zanurzyć się w tym oceanie. Jeśli zatracimy się w tym oceanie, wtedy nie będziemy mieć problemów ani wątpliwości. Wszystko będzie nasze własne i będziemy umieli radzić sobie ze wszystkim bez żadnych sporów, bez żadnych wątpliwości. To właśnie jest bycie Sahaj. Jeśli macie tę miłość w stylu Sahaj, cieszycie się. Cieszycie się sobą i cieszycie się innymi, gdyż to jest Sahaj. Nie musicie czynić żadnych wysiłków, nie musicie niczego próbować. To po prostu istnieje i działa. 

Uczucie miłości nie wyraża siebie w żaden sposób. Ono po prostu istnieje i nie może się wyrazić, gdyż ono nie ma ekspresji. Macie je tylko odczuwać w sobie. Wtedy chcecie robić mnóstwo rzeczy: chcecie każdemu pomóc, chcecie pomóc sobie, chcecie czynić dobro dla innych. Tak wiele zostało zrobione przez wielkich przywódców świata, gdyż oni mieli tę miłość. Nie mieli nic innego, poza tą miłością, której nie mogli w sobie pomieścić, więc starali się ją rozprzestrzeniać. A teraz nazywa się ich naszymi Guru, naszymi mistrzami, mającymi tę miłością wewnątrz, która przyszła do ludzi w ten unikalny sposób. To jest coś, czego nie możemy posiadać, nie możecie się tego domagać to jest i to działa, działa automatycznie. 

To jest to, co powinniśmy wiedzieć, że jesteśmy tą miłością. Ta miłość jest wewnątrz nas. Musimy mieć wiedzę, musimy mieć kompletną wiedzę, że jesteśmy tą miłością. To rozwiąże nasz problem, ponieważ będziecie potrafili wszystko wyjaśnić, całe wasze zachowanie, wszystkie wasze niepowodzenia. Potraficie wszystko wyjaśnić, kiedy wiecie, że jesteście obdarzeni tą miłością. Tym właśnie jest Guru, tą miłością wewnątrz was, która chce dzielić się miłością z innymi, która chce dawać miłość innym. To właśnie jest pokój i radość. 

Mogłabym bez końca mówić o miłości, ale największą rzeczą jest odczuwanie jej w sobie. Jak woda: jeśli chce wam się pić, możemy dać wam wody, ale nie możemy się napić. Wy musicie wypić wodę i musicie poczuć jej smak, poczuć to odczucie, jakie ona daje, wszystko to jest razem, to nie jest odseparowane. 

Nie sądzę, żeby ten temat był dla was ludzi zbyt subtelny. Wszyscy osiągnęliście pewien poziom zrozumienia tej miłości. Mam nadzieję, że ona wzrośnie i wy wzrośniecie w niej, każdy z was, i będziecie się nią cieszyć. 

Niech was Bóg błogosławi. 
