Velikonoční púdža 11/04/1993 Magliano Sabina, Řím, Itálie

Dnes jsme se tu všichni sešli na vrcholu této krásné hory, abychom oslavili vzkříšení Krista.

Pro sahadža jogíny je velice důležité, aby pochopili velkou událost Jeho vzkříšení, kterým ukázal, že Duch neumírá. On jím byl - On byl Ómkarou, On byl Slovem a On byl Duchem, a proto mohl chodit po vodě. Také jsme teď natočili film, kde ukazujeme, že múládhára, která znázorňuje atom uhlíku, má jasné tvary - když se na ni podíváte zprava doleva, uvidíte tam svastiku a při pohledu zleva doprava uvidíte Ómkaru. Když se ale podíváte zdola nahoru, uvidíte tam alfu a omegu. To bezpochyby dokazuje to, co řekl Kristus: "Já jsem alfou a omegou." Což jasně ukazuje, že byl inkarnací Šrí Ganéši. Takže máme pro sebe vědecký důkaz a můžeme proto říct lidem, že je to pravda! Nevím, jestli byla alfa a omega za dob Krista známa matematikům. Jemu ale určitě, když řekl: "Já jsem alfou a omegou." On byl velice pozoruhodnou a velice důležitou inkarnací pro náš vzestup.

Kdyby se nevzkřísil, nemohli bychom vůbec dosáhnout svého vzestupu. Takže je to velký přínos. Vzkříšení Krista je teď jasně vidět ve vašem životě. Jací jste byli předtím a jací jste dnes? Je to taková změna! Takový rozdíl! Taková transformace! Je to Jeho vlastní oběť na kříži a Jeho vlastní nádherné vzkříšení, co pro nás všechny vytvořilo cestu k tomuto novému přeměněnému stavu. Tento stav je však něco jiného pro lidské bytosti a něco jiného pro Krista. Kristus sám byl Svatostí, byl Čistotou.

Takže můžeme říct, že Jeho zmrtvýchvstání bylo jen tělesnou událostí. Protože On nepotřeboval proměnu. On nemusel projít žádným procesem očisty. Ale co se stalo v Jeho případě, bylo to, že byl vzkříšen ze smrti. Což symbolizuje, že život lidských bytostí bez duchovnosti je jako smrt. Protože dělají všechno bez pochopení úplnosti, skutečnosti, absolutní Pravdy. Vše, co dělají, je nakonec přivádí k jejich destrukci. I náboženství, která byla ustanovena těmito velkými inkarnacemi, jsou úplně v úpadku. Nenajdete ani stopu duchovního života mezi těmi, kteří o sobě prohlašují, že mohou zastupovat tyto inkarnace. Když se na to podíváte subtilním způsobem, je to také velmi bolestné, že ve jménu těchto velkých inkarnací, ten druh práce, kterou lidé dělají, ty aktivity, do kterých se pouštějí - to je něco nemožného!

Protože oni vůbec nemají strach z Boha. Ve jménu Boha dělají všechny ty strašné věci - po celém světě. Samozřejmě, můžete říct, že tady byla katolická církev odhalena. Všude lidé vidí, že se všechny tyto špatnosti odhalují. Ale oni tyto špatnosti udělali pod rouškou Boha, pod rouškou duchovnosti a krásy. Protože to je ten nejlepší způsob, jak je mohou schovat! Veškerou tu surovost, všechno to násilí, všechnu ošklivost - kam až to dopracovali. A došlo to tak daleko, že mezi těmito lidmi nenajdete ani nejmenší stopu náboženského života. Jako kdyby to převzali všichni zloději, všichni darebáci a podvodníci světa. To všechno se děje jen proto, že to, co bylo napsáno ve všech písmech světa - že musíte hledat své pravé Já - to se nikdy neprovedlo.

 ́Musíte poznat své pravé Já ́ - to se nikdy nestalo. Kolikrát řekl Kristus: "Poznej sebe sama." Také řekl, že se musíte znovu zrodit. Tak si hned dali osvědčení  ́já jsem podruhé narozený ́ a začali využívat všech výhod takového osvědčení. Oni si ale vůbec neuvědomují, jaké dobrodiní jim vzkříšení Krista přineslo! Nanejvýš mohli vydělat nějaké peníze, nanejvýš mohli mít nějakou povrchní moc, neprovedli ale žádnou vnitřní přeměnu, když to vidíte instinktivně. Člověk je musí litovat kvůli stavu jejich duševního zdraví - jakou cestu si zvolili  ́podle ́ Kristova života nebo života některé jiné inkarnace, která měla tak vznešený hodnotový systém - a oni dělají tak nízké a ubohé věci. Vy jste se teď v Sahadža józe přeměnili. Řekla bych - vaše Kundaliní udělala tu práci. Přesto je ale rozdíl mezi vámi a Kristem v tom, že vy pocházíte z prostředí, ze stylu života, ze způsobu myšlení, který byl jen pro vaše zničení.

Podíváte-li se zpátky, uvidíte, že to bylo zničující. Když z toho teď tedy vycházíte, ještě stále vás tyto věci straší. Ještě stále na vás mají vliv. Přestože stoupáte výš a výš, zjišťujete, že vás to náhle znovu táhne dolů do nějaké podivné situace, k něčemu ponižujícímu. Samozřejmě, někdy jste sami sebou šokováni. Někdy to vše dokonce přijímáte! A tak je pro sahadža jogína velice důležité, aby byl po realizaci velmi introspektivní. Místo toho, aby se díval, co je špatného v ostatních, měl by se podívat, co je špatného v něm samotném. Je velmi důležité, abyste věděli, jak daleko jste došli na cestě ke své duchovnosti. Protože Kristus tohle nepotřeboval.

On ani nemusel dělat introspekci. Byl něčím, co bylo daleko nade vší zkažeností. A pro něj to byla jen tělesná přeměna v tom smyslu, že  ́zemřel ́ a potom se zase vzkřísil. Ale pro nás je to něco úplně jiného! My jsme teď sahadža jogíny, ale byli jsme obyčejnými lidskými bytostmi. Neměli jsme uvnitř sebe žádné Světlo. Teď to Světlo do nás přichází a my jej vidíme. Čím se ale stáváme? My se musíme stát Světlem samotným. Kristus byl Světlem, nemusel se jím stát.

Ale my se musíme Světlem stát. Musíte ho teď střežit, musíte si dávat pozor, aby ho nic nerušilo, aby se nezmenšovalo nebo dokonce úplně nevyhaslo. Když s sebou tedy nesete toto Světlo, musíte zaprvé vědět, že když Světlo vidíte, tak to není správné. Znamená to, že Světlem nejste. Vy se Světlem musíte stát. Když jste Světlem, můžete v jeho záři snadno vidět, jak pracuje vaše mysl, jaké vám dává myšlenky, co ovlivňuje vaši mysl, když stoupáte. Jsou to nějaké obavy? Nebo pocit zodpovědnosti? Nebo to pochází ze zlozvyků, které jste měli dřív, že je tu nějaká překážka, nějaký blok ve vašem růstu k duchovní osobnosti? Takže se stále musíte hlídat a sledovat, jak postupujete.

Je to tak krásná cesta, nádherná cesta! Včera jsem byla velmi šťastná, když jsem slyšela píseň Rusů, kde popisovali cestu - cestu Kundaliní. Je to pravda, bezpochyby, že jste realizované duše! Předtím jste nebyli, ale teď jste realizované duše. Jste ve vyvinutějším stavu. Co vám teď ale škodí, je představa, že:  ́My jsme absolutně v pořádku a nic nám nemůže ublížit, nic nás nemůže shodit dolů. ́ Jestli si vyvinete tak egoistickou představu, tak vám to vůbec nepomůže. To, co musíte dělat, je stále provádět introspekci. Kvůli tomu je meditace - abyste sami viděli, jak silně se držíte svého duchovního vzestupu. Nikdo jiný to nemůže udělat. Je to vaše individuální práce.

Samozřejmě, když přijdete do kolektivu, okamžitě poznají, jaké čakry máte napadené - bezpochyby. Nemusí vám to říkat, nemusí na to poukazovat, ale budou to s jistotou vědět, že ta a ta čakra je napadená a tento člověk má takový problém. Ale oni sami nebudou vědět, kde jsou napadení, jaké jsou jejich problémy. Takže když vám někdo řekne: "Myslím, že máš napadenou tuhle čakru," nikdy byste se kvůli tomu neměli cítit špatně. Protože když tu čakru tak necháváte, ničíte si svůj vlastní život! Takže musíte vědět, že když vám někdo řekne: "Myslím, že máš něco s touhle čakrou," měli byste tomu člověku poděkovat: "Díky Bohu, že jsi mi to řekl." Jako zrcadlo. Když se vidíte v zrcadle, že na vašem obličeji není něco v pořádku, můžete to okamžitě napravit. Stejně tak, když vás někdo na to upozorní, měli byste být dost dospělí na to, abyste věděli:  ́Je to pro mě velké požehnání, že mi to někdo řekl. ́ Jako nedávno tu byl jakýsi spor mezi dvěma lídry. Vždycky, když jsou někde dva lídři, je tam nějaký spor.

Neměl by být! Tak jako mezi sebou nebojují dvě oči, dvě ruce nebo dvě nohy. Ale když jsou někde dva lídři, tak je tam vždy nějaký problém. Musíte proto mít jen jednoho lídra. Jinak jsou velké problémy. A tak se mezi sebou přeli - dva lídři - a přišli ke mně. Okamžitě jsem viděla, že jeden z nich je úplně napadený. Řekla jsem mu: "Dej ke mně ruce." Jakmile ke mně vztáhl ruce, okamžitě ucuknul. - "Co se stalo?"

Řekl: "Matko, cítím horko." Já na to: "To je ono. Víš, co s tebou není v pořádku?" Řekl: Mám velmi prudkou povahu, já vím, jsem velmi egoistický, neměl jsem se chovat takto." Ale vlastně by se mohl cítit velmi špatně, protože jsem mu to řekla! Ale on se tak necítil, protože je sahadža jogínem a ví, co je pro něj prospěšné, co je pro něj dobré. Vůbec se necítil špatně, naopak, byl mi tak vděčný: "Matko, díky Tobě jsem byl odhalen, jinak bych to v sobě pořád skrýval." Nuže, naším problémem je, že jsme uvnitř sebe dosáhli velkého vývoje a upevnili jsme se, ustrnuli jsme. Také máme velikou kolektivní sílu - vidím ji v každé zemi. Tolika lidem můžeme dát realizaci a můžeme v našem životě upevnit všechny velké pravdy (ctnosti).

Můžeme to udělat! Stále bychom se měli snažit je upevňovat. Je tu ale jeden bod, ve kterém byste si neměli být příliš jistí - že jste už úplně dosáhli Poslední Pravdy. V tom musíte být velmi opatrní! Viděla jsem lidi, kteří v Sahadža józe vystoupí velmi vysoko, velmi vysoko a najednou klesnou strašně hluboko. Z toho jsem moc smutná, velmi smutná. Důvodem je, že nemají žádnou víru - víru v sebe a víru v sahadž. Tato víra schází. Musíte mít víru v sebe a víru v sahadž. Sahadž znamená, že je tu božská síla.

A tato Všepronikající božská síla se o nás stará. Je cítit i nyní, cítili jste ji, není to jen, že to říkám. Vy jste ji sami poznali. Ale přesto, že to víte, jste ještě v sobě tuto víru neupevnili. To je ta víra, o které mluvil Kristus. To je víra s osvícenou myslí - ne slepá. Se slepou vírou můžete dělat chyby, zatímco s osvícenou, když máte víru, stanete se extrémně mocnými. Velmi mocnými. Nemůžete mít žádné problémy, jestliže je vaše víra osvícená. Tak tedy v Sahadža józe uvidíte mnoho těch, kteří jsou velmi pevní, velmi přímí a velmi hodnotní.

Jsou jako ti, kteří vědí, že stojí na skále. Ale ti, kteří ještě nejsou pevní, jsou jako ti, kteří si myslí, že se stále utápějí v nějakých podivných vodách života. Ty skály jsou tu a vy na nich stojíte. A to také vzešlo z víry:  ́Nic nás nemůže rušit, nic nám nemůže dělat problémy. ́ Co se týče Krista, věděl vše a byl si tím zcela jist. Nikdy se netrápil, nikdy se neunavil a nikdy nepochyboval. Věděl, že je Synem Boha - a byl to fakt, který věděl velmi dobře, který nikdy neodmítal, nad kterým nikdy nezapochyboval, ne. Je to tak. A proto říkám, že stál na skále. Zatímco ostatní lidé - dokonce i sahadža jogíni - se musí stát takovými, jako byl Kristus, co se týče víry. Tuto víru je třeba chápat.

Je to osvícená víra. Jako Kristus, který šel vstříc svému ukřižování, který podstoupil všechno možné - jen proto, že věděl, že je to jen drama a hra a že v tom není nic vážného, že na tom nezáleží a že se zase vzkřísí. Hrál toto drama. Pro něj to nebylo nic vážného. Viděl, že si z něj lidé dělají blázny, že se mu vysmívají, ale také uvnitř sebe věděl:  ́Ti lidé, jež se mi posmívají, nevědí, kdo jsem. ́ Ale zároveň byl ztělesněním víry. Víry v sebe samého a v tuto Všepronikající sílu. Nikdy vás nezklame. Ale musíte v ní mít absolutní víru. Například mám někoho, komu důvěřuji. Přirozeně mu všechno svěřím, ve všem se na něj spolehnu, nechám mu klíče nebo peníze - nikdy o něm nebudu pochybovat.

Stejně tak, když máte víru v sebe, víru v Sahadža jógu, kde jste upevněni, budete překvapeni, jak bude všechno fungovat, jak se život zlepší a jak budete  ́stát na skále ́ - budete se tak cítit. Nebudete mít žádné pochybnosti, žádné problémy, žádné nemoci. Takže takový je to stav - a to je možné pouze s vírou. Jak však získat tuto víru? To je problém - jak získat víru? Není na to žádný kurz, není o tom žádná literatura, nejsou o tom žádné přednášky. Ve vás je ale probuzení, které se zeptá: "Co jsem?" - to probuzení. "Co jsem? Čeho jsem dosáhl?"

Víte, ono se to zeptá: "Co je to, čeho jsem dosáhl? Co jsem získal Sahadža jógou?" Všechny tyto otázky se ve vás vynoří. Ale když máte víru - ne slepou, ale osvícenou, která je upevněna mnoha zázraky ve vašem životě, mnoha zázraky i ve velmi malých věcech, zjistíte, že se vám i v maličkostech dějí zázraky. Máte zázraky i ve velkých věcech a tam, kde byste nikdy nečekali, že se stanou. Takže teď dobře víte, že jste se velmi hezky upevnili v Sahadža józe. Například začne pršet. Polovina z vás by si kvůli tomu začala dělat starosti.  ́Proč prší? ́ Ale oni budou vědět, že je tu krásná střecha a že se nám nemůže nic stát. Ať si prší, jak chce.

A pak budete mít víru, že na vás pršet nebude, že nezmokneme. Stejně tak v nás musí být tato víra úplně pevná. A to vás učiní extrémně silnými a zodpovědnými za vzkříšení tisíců a tisíců a tisíců lidí. Tento nádherný život teď máme díky našemu vlastnímu upevnění, díky našemu vlastnímu chápání, našemu vlastnímu pozorování. Upevňujeme se v sobě samých, upevňujeme se v Sahadža józe. Je to něco pozoruhodného, co se stalo a co se děje a co by se s vámi všemi mělo stát. Vy všichni byste měli mít šanci poznat Ducha a své pravé Já. A tak musí mít člověk víru v sebe. Stále přicházejí nějaké sahadža jogínky a říkají: "Matko, nejsem dobrá, nejsem k ničemu, nic nedělám, jsem jen líné nemehlo," a tak podobně. Tak dobrá, myslíte si to?

Jen mě požádejte - co chcete? Dokonce i když mě o to nepožádáte, tak to bude fungovat. Dokonce i když ani nepožádáte. Jen když na to pomyslíte, bude to fungovat. Jen když na to zaměříte pozornost, bude to fungovat. Protože tato Všepronikající síla je jedinou skutečnou silou, ostatní síly jsou k ničemu. A je tak účinná, tak soucitná, že může vyřešit cokoliv - a to ve zlomku sekundy. Jednou jsme tu měli kohosi z Austrálie. Byl někým podveden a přinucen k tomu, že musel koupit nějaký pozemek a dům za velmi nehoráznou cenu. Na což neměl peníze.

A tento muž mu řekl: "Nic se neděje, i když nebudeš mít hned peníze, nikdo nebude nic namítat." Věřil mu. Měl špatnou víru, měla bych říct, tak řekl - "dobrá". Zaplatil vše, co měl, jen jako zálohu. Někdo tam jel - byla tam púdža, takže jich tam jelo hodně. Tolik se toho stalo a tolik lidí přijelo a viděli to všechno. Ale tento chlapík byl tak vzrušený a rozčílený. Nemohl pochopit, proč se mu to stalo, že je postaven do tak obtížné situace. Byl podveden a úplně vyjevený. Neměl vůbec představu, jak se z toho průšvihu dostat ven.

Vložil do toho všechny svoje peníze, vše bylo komplikované a kdyby nezaplatil, šel by do vězení! Napsala jsem mu jen: "Měj víru v sebe", to je vše. "Měj víru!" A jaký zázrak se stal! Někdo mu za to nabídl daleko vyšší cenu a řekl mu, že všechno zaplatí a že mu dá ještě mnohem víc. Je to něco neuvěřitelného! Tolik jich tam šlo, tolik jich to chtělo vyřešit, dělali leccos, setkali se, říkal, že to nezaplatí nic nefungovalo, nic. Jen jeho víra. A tak si teď můžete představit, že z něho bude boháč. Měl jít do vězení, a nyní z něho bude boháč.

Takových zázraků jsou spousty. Toto je jen finanční stránka, ale vy víte, že se děje mnoho jiných takových zázraků. Když po seberealizaci nemáte víru, ukazuje to, že jste velmi ubohou osobností! Alespoň po realizaci byste měli přijmout víru. Je to opravdu překvapující, že lidé získají realizaci a všechno kolem, ale přesto nemají víru v sebe samé. Ti, kteří ji měli a mají, dokázali skutečně mnoho! Nuže, rozdíl mezi námi a Kristem je v tom, že víra byla nedílnou součástí Jeho bytosti. Nebylo to tak, že by musel mít víru - On byl vírou. My ji ale musíme mít. My musíme věřit v sebe sama.

Je tolik příhod, které vám mohu uvést nebo které mi můžete říct sami, kdy pomohla jen samotná víra. Myslím, že to bylo v Rumunsku - přišla tam na pódium jedna paní, nemohla chodit, dovezli ji na vozíku. Řekla mi: "Matko, já vím, že mě můžeš vyléčit. Nikdo mě nemůže vyléčit, ale já vím, že Ty ano." Opakovala to třikrát. Řekla jsem jí: "Ano? Věříš tomu, že tě mohu vyléčit?" "Ano." Řekla jsem: "Tak vstaň." A ona prostě vstala, sešla dolů a pak tam začala pobíhat!

A každý se smál. Povídali mi: "Matko, ale vždyť ona není sahadža jogínka!" Řekla jsem: "Podívejte se na její víru!" Protože, když má člověk víru, převezmou to všechna božstva. Jsou vyzvaná, musí to udělat! Ukázali víru na takové osobě. Jak pořád říkám, v Sahadža józe důvěřujeme lidem. Věříme jim. Jeden ze sta nás může podvést, nevadí, to je jedno, přesto důvěřujeme. Víra, kterou máte v nějakého člověka, funguje také v jeho mysli:  ́Oni ve mne mají takovou důvěru... ́ A co božstva?!

Když v ně ukážete víru, funguje to. Pracují okamžitě! Jako když mi Guido sdělil: "Matko, říkají, že na tyto dva dny očekávají velké deště." Řekla jsem mu: "Dobrá, nedělej si starosti." A kde je teď déšť? Zmizel. Můžete ovládat cokoliv, když ovládnete svoji víru. Když mluvíme o víře, víte - - je to výzva pro tuto Všepronikající sílu, která všechno organizuje, která všechno ví, která je tak inteligentní, pohotová, výkonná a navíc a především vás miluje. Vy jen ukažte víru! Vzkříšení v Sahadža józe znamená, že vaše víra se stane pevnou.

Toho musíte dosáhnout - pevné víry. Pak se necítí špatně, řekněme, když se se mnou nesetkají, když jsem předtím třeba řekla, že přijdu tehdy a tehdy, a nejsem tam - na ničem nezáleží! Jestli se s vámi Matka setká nebo ne, jestli se to stane nebo ne. Všechno je pro naše dobro. Například se někde ztratíte - vězte, že to tak má být. Když se podíváte na život Krista, On musel být ukřižován! Musel nést kříž! Musel toto vše udělat - v pořádku, cokoliv.  ́Je to předurčeno. Udělám to! ́ Nikdy nereptal, nikdy se nezdráhal, nikdy nechtěl s nikým sdílet své problémy.

Ale ta víra v sebe mu dala tak obrovské síly! Mohl udělat cokoliv! Mohl zabít všechny ty lidi, kteří se Ho pokoušeli pronásledovat - snadno! Jen jeden jediný jeho pohled je mohl zabít! Ale ne! On věděl, že musí projít tím, čím prošel. A nakonec - On je tím, kdo vítězí! On je tím, kdo vše vyhrál! Stejným způsobem se musí sahadža jogín podívat na svůj vlastní život. Je to velice cenný život.

Velice cenný v tomto světě - kolik je tu dnes sahadža jogínů? Kolik lidí se v tomto evolučním procesu stane sahadža jogíny, to nemohu říct. A když se podíváte na svět, začnete cítit, že většina z něho bude zničena! Většina lidí tu nebude! Ne proto, že pro ně nejsme dostupní, ale proto, že nejsou předurčeni, aby přišli do Sahadža jógy. Není jim určeno přijít do Sahadža jógy. Takže vy máte takové štěstí, že jste dostali svou realizaci, svoje vzkříšení. Teď ale mějte víru v toto svoje vzkříšení, ve své vzkříšení, které je nyní vaší existencí! A s touto vírou budete vědět, jak jste cenní pro celý svět! A to, co musíte udělat, není myslet na nějaký materiální zisk, tělesný zisk nebo nějaký emocionální zisk, ale - na duchovní zisk.

 ́Co jsme udělali pro duchovnost vlastní a pro duchovnost ostatních? ́ To je to jediné, na co musíte myslet a budete ohromeni, jak je všechno organizované, jak se vše vypracuje, jak všechno v pravý čas ukáže své výsledky. Jsem si jista, že alespoň 80% z vás věří tomu, co říkám, možná 90%. Ale mohlo by tu být asi 10% těch, kteří si stále myslí:  ́Dobrá, Matka to tak říká, ale proč se stalo tohle a tamto? ́ Jako nedávno, když jsem se setkala s jedním novinářem, velice známou osobností, řekl mi: "Já nemohu věřit v Boha." Povídám: "Proč?" "Protože, jak může být na tomto světě tolik neštěstí? Jak se může narodit slepé dítě, jak se může stát to či ono...?" Začal mi dávat příklady. "Dobrá". Povídám mu: "Tak, řekl jste mi všechno?" "Ano."

Povídám: "Nuže, řekněme například, že sedíte v sféře kongresu nebo vaší vlády Andreottiho nebo jak to nazýváte - takže ta situace je vysvětlitelná. Ještě jste se nedostal do sféry Boha! Až dojdete do toho stavu a až ho dosáhnete a až se v té říši usadíte, pak mi řekněte - máte nějaké problémy? Žádný." Řekla jsem mu: "Proč se díváte na tu negativní stránku? Nyní, když říkáte, že je tu cesta, jak z toho ven a že tu je řešení a že může přijít čas, kdy v této rase sahadža jogínu už nebudou žádné nemoci, žádné potíže, žádné problémy, tak proč nevidět tohle? Proč chcete vidět jednoho chlapce, který je slepý, ale proč nechcete vidět, jak se slepý uzdraví?" Takže tento druh negativního postoje mohou mít i sahadža jogíni. Viděla jsem je: někdo je nemocný, řeknou: "Matko, on je nemocný, musím ho k Tobě přivést, musíš se na něho podívat..." Není to vůbec třeba! Vy ho můžete vyléčit!

Vaše víra ho může vyléčit! Víte o jednom, jehož strýc byl nemocný, nebyl to sahadža jogín. On se na něj šel podívat a žena jeho strýce mu řekla: "Ty jsi schopný modlit se k Matce, proč Ji nepožádáš, aby mému muži vrátila zdraví?" Strýc měl rakovinu, na smrtelné posteli... - A on řekl: "Dobrá." Poklonil se a požádal: "Matko, prosím, uzdrav mého strýce." Za tři dny byl z nemocnice venku a teď se toulá po celém světě! I když to není sahadža jogín, přesto to fungovalo, protože nyní stačí, aby to sahadža jogín řekl a božstva se toho chopí. I když se nejedná o sahadža jogína, na tom nezáleží. Božstva jsou připravena pomoci. A člověk musí věřit v sebe sama - plně, když jsou tyto síly s námi, proč je nepoužívat?

Proč si nevyvinout tuto úplnou víru, že jsme teď sahadža jogíny, jsme v království Boha a že tato síla se o nás bude starat? Pak nebudeme mít na výběr, nebudeme váhat, nebudeme si dělat starosti, jestli musíte odjet do Singapuru nebo musíte odjet do Afriky, kamkoliv - no a? Jsme stále v království Boha, kamkoliv jdeme, všechno je úplně v pořádku. O nic se nemusíme strachovat! Jsme otroky tolika věcí - našich hodinek, našich zvyklostí, takových věcí... - toto všechno odpadá! Nevadí! Na čem záleží? Nic není důležité. Dokud jste sami sebou, je všechno v pořádku. Lidé se mě ptají: "Matko, Ty tolik cestuješ, jak to všechno zvládáš?"

A já jim říkám: "Já nikdy necestuji! Tak, jak sedím tady v křesle, sedím v křesle tam, to je vše. Jen to křeslo se vymění. Vůbec nemyslím na to, že bych cestovala. Hezky si sedím ve svém křesle, takže jsem v pořádku a nejsem unavená!" Takže, když máte úplnou víru v sebe, ve své pravé Já, tak si neděláte starosti. Hodně lidí si bude dělat starosti ještě než někam přijedou, jestli tam bude koupelna nebo ne, jestli tam bude postel nebo ne. Nic! Vy hledáte jen pohodlí svého Ducha! Jestli to dostanete - výborně, jestli ne - můžete spát kdekoliv!

Nic vás nemůže svazovat. Nic vás nemůže stáhnout dolů. Žádný zvyk vás nemůže porazit, protože tato víra vás očistí, úplně. Osvítí vás, dá vám všechnu výživu. Tato víra není nic, co by mohlo být vloženo do vaší hlavy nebo do vašeho srdce. To není možné. Je to stav, kterého musíte dosáhnout a kterého můžete dosáhnout pomocí Sahadža jógy. Takto bude naše vzkříšení úplné, bude upevněno, bude účinné a bude vzorem celému světu. Nechť vám všem Bůh žehná! Jsou tu jen děti, je tu tolik dětí.

Dnešek je dnem Krista, V každém případě by má chodidla měly omývat děti. Můžete to tam připevnit nebo to budete muset posunout?