Navaratri Puja. Los Ángeles, Estados Unidos. 27 de octubre de 2002.

Hoy vamos a adorar a la Diosa. Ella actúa en primer lugar en el lado izquierdo y posteriormente se convierte en la Adi Shakti, en el Sahastrara. Todo lo que hace en el lado izquierdo ha sido descrito, como ya habréis visto; Ella es la memoria y la sabiduría. Y su capacidad protectora se manifiesta cuando utiliza su Poder sobre los ganas.

Como sabemos, existen ganas que son responsables de todo tipo de "correcciones" en vosotros. Estos son los ganas que actúan a través del lado izquierdo. Como sabemos muy bien, el cáncer está causado por los problemas del lado izquierdo. Y en el lado izquierdo se encuentran estos ganas que están en completa armonía con los poderes de la Devi. Ella no les tiene que decir nada ni les tiene que guiar, pues ya han sido creados así. Yo diría que estos ganas son los que localizan el objetivo. Localizan las enfermedades y las curan. Hemos curado a muchos enfermos de cáncer y a muchas personas del lado izquierdo a través de los ganas.

Sin embargo, los ganas no escucharán a nadie más que a Ganapati, que es su líder o, digamos, quien los controla. Por tanto, si vuestro Ganapati está bien, no hay tantos problemas. Pero si está mal, entonces pueden surgir muchos problemas que os pueden torturar. Este es uno de los aspectos en los que más insisto meticulosamente, y es que debéis corregir vuestro Ganesha.

El otro día recibí un gran sobre con cartas que decían: "Madre, es difícil controlar a los ganas". Pero lo realmente difícil es controlar a Ganapati. ¿Qué nos ocurre entonces? Que padecemos un trauma, y en una situación así, en la que no podemos superar el efecto de Ganapati en nosotros, lo que debemos hacer es meditar. La meditación es la única manera en la que podéis superar el efecto de los Ganas.

Pero lo primero de todo es la educación de los niños y la atmósfera que creáis con ellos. Cuidando de estos dos importantes factores, os irá bien con los Ganas. El problema es que los seres humanos se pierden a sí mismos y no cuidan de su Ganapati. Vosotros, al adorar a la Diosa, ya estáis adorando a Shri Ganesha, que es el Poder que hay detrás de Ella.

El Poder más grande de la Madre es el de vuestra protección; protección de todo tipo de cosas. Os protege de las cosas del lado izquierdo. Ya habréis leído en el Devi Mahatmyan toda la protección que os da. Ella os otorga total protección. Su Poder de protección es tremendo, y os hace ver lo bondadosa que es con vosotros y lo mucho que os protege. En el lado izquierdo, os guiará siempre que necesitéis protección. A través de sus ganas, Ella cuida de vosotros. Y con los que estáis en el lado derecho, la Diosa utiliza sus poderes para corregiros, para que volváis a un estado de normalidad, os hagáis más humildes y entendáis que sois un niño de Madre y que os tenéis que comportar como tal.

Pero si vais a los extremos, entonces surgen muchas complicaciones, tanto del lado derecho como del izquierdo. Hoy día, los problemas del lado derecho son muy comunes y he visto que mucha gente no puede superarlos. En consecuencia surgen enfermedades como el Alzheimer y otras. Todo empieza en el hígado. El hígado es el elemento principal, y caemos en su trampa. Si pensáis demasiado, si sois futuristas o agresivos, el hígado se agota, ya que usáis su poder para hacer todo eso. Y una vez que acabáis con el poder del hígado, podéis desarrollar muchas enfermedades y tener muchos problemas que no sabréis cómo superar. Es muy difícil.

Por supuesto, con Sahaja Yoga muchas personas han podido curar su hígado, y este ha continuado haciendo su trabajo perfectamente. Pero deberíais ser humildes e intentar mantener el hígado bien. Los ganas desarrollan la protección en vuestro cuerpo en el lado izquierdo, y las acciones en el lado derecho. Pero lo más grande son las bendiciones de la Madre; el modo en que os cuida, os ama y se preocupa por vosotros, algo que no deberíais dar nunca por sentado.

Debéis meditar. Es muy importante, muy importante. Sin la meditación no podéis manteneros bien, sin lugar a dudas. La meditación es lo más importante que debéis hacer, porque así es cómo os acercáis a sus vibraciones, a Ella, a su naturaleza, diría yo. Incluso los animales son muy sensibles a la Madre y a las vibraciones. Los animales son así, pero los seres humanos tienen su propio entendimiento, tienen libertad, tienen lo que llaman inteligencia, y caen en esa trampa. Siguen aquello que no deberían seguir.

Lo que verdaderamente es necesario en un país como América es la devoción y la dedicación. Estos dos aspectos no están ahí. Los indios entran en Sahaja Yoga y profundizan mucho porque saben lo que es bhakti (adoración), lo que es la devoción. Ambas diluyen el ego y todo lo demás. Pero el bhakti es para que lo disfrutéis. No sé cómo crear bhakti en el interior. No lo sé poner en palabras. He visto a mucha gente con bhakti. Han ascendido mucho, aunque es un movimiento del lado izquierdo. No sé cómo el bhakti y shraddha (fe) les han ayudado tanto.

Debo decir que en esto los indios son los mejores porque tienen este poder de bhakti y shraddha. No existe la locura que hay aquí. He visto que algunas personas que entran en ciertas sectas se vuelven locas. Pero el bhakti no es locura, es amor, y un amor que comprende, comprende lo que es bhakti y lo que es shraddha. Hasta que no desarrolléis bhakti y shraddha en vuestro interior, no podréis crecer. No podréis ascender sobre vuestros problemas, no podréis superar vuestra personalidad, porque el bhakti no se puede imponer a otros; no lo podéis forzar. No podéis volver loco a alguien, y después decir que puede hacer bhakti. No puede. Debéis mantener todas vuestras cualidades totalmente intactas. Deberíais ser inteligentes y comprensivos. Todo eso es necesario. Y cuando ocurre, el gozo del bhakti está en vuestro interior. Cuando empieza a fluir, la misma Diosa entra en vuestro Ser.

He visto mucha gente, bhaktas, grandes santos de India, que han alcanzado un nivel muy elevado. Han profundizado mucho. Si leéis sobre ellos y les entendéis, os sorprenderá cómo, sin ninguna ayuda ni orientación, pudieron llegar a tal profundidad y a adorar a la Diosa. La adoración no consiste en absoluto en leer o cantar, sino que es la profunda atención del corazón. Yo creo que es el Espíritu. Si el Espíritu está despierto en vosotros, desarrolláis bhakti y desecháis todas esas ideas absurdas y demás historias que hay en vuestra cabeza. Simplemente desarrolláis bhakti.

Todas estas cualidades descritas de la Devi, como la memoria, smriti rupena samsthita, y otras también, son del lado izquierdo. Están en el cerebro, y cuando el bhakti alcanza este nivel, simplemente lo neutraliza todo. Todos los problemas del cerebro se neutralizan y os convertís en una persona sabia. Por tanto, el mayor don que os otorga la Devi es la sabiduría. Podéis llamarlo consciencia o algo así. Es un tipo de sabiduría que os convierte por completo en una personalidad divina, y debéis conseguirla a través de vuestro bhakti.

Pero ya veis que aquí hay gente muy distinta. Algunos tienen mucho shraddha, bhakti, devoción, pero están en el lugar equivocado y no comprenden a quién deberían adorar y adónde deberían ir. Sahaja Yoga es una realidad. Sahaja Yoga es sakshat, una verdad en la que sabéis a quién adorar y a quién rendiros. No es algo ciego, de ninguna manera. La devoción ciega os puede llevar a cualquier tipo de licencia, y así es cómo han surgido muchos cultos y muchas otras cosas. Pero la fe ciega ni ve ni conoce, ni comprende. Vuestra inteligencia, todas vuestras cualidades deberían entender en qué consiste vuestra vida de bhakti.

Debo decir que, a través del despertar de la Kundalini habéis alcanzado un alto entendimiento del bhakti y su poder. El mayor poder del bhakti es que os protege. Aquellas personas que se encuentran en una situación difícil, que tienen cualquier problema, simplemente salen de ello porque su bhakti les da el correcto entendimiento de sí mismos, de lo que les rodea y de todo el universo, diría yo. ¿Por qué se comporta la gente de esta manera? ¿Por qué son así? Todo esto se puede solucionar a través de vuestro bhakti. Pero no a ciegas sino con sabiduría.

Yo creo que esto solo es posible a través de Sahaja Yoga. Todo bhakti que la gente hace ciegamente no puede ser bhakti. Vosotros no os volvéis locos. Os convertís en personas sabias, como muchas de las personas que tuvimos en el pasado, y resulta sorprendente cómo hablaron sobre cualquier tema. Es extraordinario lo que dijeron sobre la conciencia humana y sobre vuestro crecimiento. En ocasiones siento que, verdaderamente, me prepararon el camino, un terreno adecuado para que yo hablara a la gente. No sé por qué, pero en India, tradicionalmente, somos muy devocionales.

En todo el mundo deberíamos ser así. En India, por supuesto, también hay gente loca. Sin duda existen sectas y otros muchos movimientos. Pero allí han vivido santos que nos han guiado muy bien. A pesar de eso, en India podéis encontrar gente que está perdida, que sigue cometiendo errores y adorando a personas equivocadas. Es cierto, es una extraña locura en la que no hay sabiduría. Lo que diferencia a una persona loca de otra sana es que la que está loca no tiene sabiduría. Y aquellos que dicen tener sabiduría, aquellos que afirman: "nosotros somos muy sabios", están tristemente equivocados. A veces resulta sorprendente cómo se comportan, los errores que cometen, cómo está su atención y lo que hacen. Eso es porque no tienen sabiduría. Antes que nada, observad cómo estáis vosotros y preguntaos: "¿Soy sabio? ¿Estoy haciendo cosas sabias o no?"

Me llegan muchas quejas de los sahaja yoguis. Me sorprenden: ¿Por qué se comportan así? Yo diría que todavía no han alcanzado el estado de bhakti y shraddha. Debo decir que estos dos aspectos se han perdido en la vida occidental. Deberíamos volver atrás. Deberíamos desarrollarnos y crecer. Pero hoy en día estas cualidades han desaparecido incluso de la vida oriental. Ahora para ellos el ideal es la vida occidental. Una vez que os adaptáis a ese estilo de vida, bhakti y shraddha desaparecen porque todo se juzga con ideas como: "qué es beneficioso, qué es útil en la vida". Para ellos, estas cualidades no sirven para nada; no ayudan. Hoy día la mayoría de la gente piensa así. Sois muy pocos los que habéis entendido qué es bhakti y qué es shraddha.

Por tanto, es la Diosa la que os da bhakti y shraddha. ¿Cómo? A través de vuestra meditación. Veis que ocurren muchos milagros y os sorprendéis por cómo han podido suceder. "Nunca creímos que esto pudiera suceder. ¿Cómo ha ocurrido? ¿Cómo ha funcionado así?" Ella también os corrige constantemente. Si estáis atentos, os corrige y os dice por dónde no debéis ir. Ella os comunica si os estáis yendo hacia el ego o hacia el lado izquierdo. Ella es la que os corrige en todo.

Cogéis enfermedades; caéis en muchas trampas. Eso es porque no tenéis bhakti. Con bhakti pasáis a depender de la sabiduría de la Madre, de la Shakti, que cuida de vosotros, os descubre el camino y os ayuda. Si empezáis a ir por vuestra cuenta y a pensar: "yo estoy bien, puedo hacer esto y lo otro", inevitablemente descubriréis que no estáis en lo cierto, que os habíais hecho una idea equivocada sobre vosotros mismos y sobre el Divino.

La cuestión más importante es la entrega. La palabra Islam significa entrega. Mahoma dijo que antes de entregaros deberíais tener la Realización. Pero habéis visto que incluso después de la Realización la gente tarda en asentarse. Sin embargo, una vez que os habéis establecido, comprendéis que estáis bajo la protección de la Diosa; cada día veis cómo trabaja y cómo os ayuda. Muchas personas que dicen estar en Sahaja Yoga tienen gran respeto por mí, pero no están totalmente ahí. Entonces sufren, tienen problemas y me preguntan: "Madre, ¿cómo es que tengo este problema?" Yo no se lo digo porque ya veis que no se les puede decir nada a los seres humanos. Son muy agresivos.

Esto ocurre porque no sois Uno con el Divino. Si sois Uno con el Divino, no tendréis nada más que compasión y amor. Y todo lo haréis con gran suavidad y amabilidad. Puede que la gente no lo entienda; así es cómo crucificaron a Cristo. De acuerdo, hicieron cosas terribles. Pero ahora deberíais pedir la protección de la Diosa, porque esa es su mayor cualidad: Ella os protege de todos los problemas, de todas las dificultades y situaciones absurdas que pueden suceder. Pueden ocurrir muchas cosas. Me dijeron que uno de los líderes de Sahaja Yoga, un sahaja yogui, había sido asesinado. Yo les dije que eso no era posible. Y el individuo en cuestión estaba ahí, no había sido asesinado. No es posible que un hombre joven muera de esa manera. Por supuesto, si os hacéis mayores, morís. Pero no estaba bien que alguien así fuera asesinado.

Por tanto, lo que recibís es una protección no solo física, mental o emocional, sino también espiritual; una protección espiritual por la que no hacéis cosas equivocadas. No matáis ni torturáis a nadie, no sois desagradables con nadie. Esta es una situación que todos podéis lograr porque sois sahaja yoguis. La podéis conseguir. Tenéis el poder para hacerlo porque en vosotros hay shraddha y un gran entendimiento de que habéis alcanzado un determinado estado de protección, de crecimiento y de sabiduría. En primer lugar, examinad vuestra sabiduría. Debéis ponerla a prueba. "Si hago esto, ¿es sabio? ¿Es bueno? ¿Por qué lo hago?" Primero debéis hacer esto, porque así descubriréis que están mal muchas cosas que hacéis y que no deberíais haber hecho. Pero antes de nada debéis desarrollar vuestra sabiduría y ver que funciona y os ayuda.

En la obra que se representó ayer, veríais a esa chica. Era muy sensible, y gracias a su sabiduría podía ver lo que era bueno. Si no sabéis descubrir lo que está bien y lo que está mal, carecéis de sabiduría. Si no sois capaces de ver lo que deberíais hacer, entonces es que no tenéis sabiduría. Si la tenéis, inmediatamente sabréis qué es lo que está mal. Además, estaréis a salvo de cualquier problema. Es un hecho. He visto que le ha ocurrido a mucha gente, que se ha salvado no solo de la muerte sino de muchas otras catástrofes. Y me sorprendió la manera en que el Divino ayudó a estos sahaja yoguis.

El Divino es Poder. Está en todas partes. Pero solo ayudará a los que son sahaja yoguis, a los que son espirituales, y no a las personas que no lo son. Nunca lo hará. Al contrario, puede que los castigue de una manera jamás imaginada. Así que uno ha de procurar mirarse a sí mismo, hacer lo que yo llamo introspección. ¿Habéis sido sabios al tratar con ciertos problemas? ¿Cuál ha sido vuestro estilo? ¿Está orientado al dinero o a la dominación? ¿Qué tipo de poder está funcionando debajo?

Debéis hacer introspección para descubrirlo. Y os sorprenderá mucho comprobar que incluso en nombre de Dios podéis hacer cosas equivocadas. En su nombre se han cometido muchos errores, y por eso hoy existe un gran caos en las llamadas religiones. Al principio no había nada malo en la religión como tal ni en las personas religiosas que hablaban de ella. Pero el cómo la asimiló y la utilizó la gente fue equivocado, porque carecían de sabiduría. Y lo cierto es que la sabiduría no es solo dar por supuesto que uno es muy sabio y ya está, sino que es algo que defiende, determina y muestra lo que está bien y lo que está mal.

La sabiduría es el indicador de que una persona es, verdaderamente, un alma realizada de muy alto nivel. Si no tenéis sabiduría, puede que os sintáis satisfechos de lo que hagáis, pero la sabiduría es muy importante. Es el aspecto que más rige nuestro interior. Y como sabéis, Ganesha es el dador de sabiduría. Por eso debéis adorarlo. Shri Ganesha se establece a través de una educación adecuada, es quien nos otorga la sabiduría. Y esta sabiduría es innata. No tenéis que cuestionarla. Existe de manera innata en nuestro interior, y se desarrolla como cualquiera de las cualidades que hay en nosotros. A algunas personas les lleva tiempo, sin duda, pero una vez que se establece, esas personas se vuelven tranquilas, sencillas y totalmente honestas. Conocen su sabiduría, y eso es lo que deberíais desarrollar: "¿hasta qué punto soy sabio?"

En este mundo la gente protesta por esto, por lo otro, lucha por aquello y hace todo tipo de cosas. Pero si tenéis sabiduría, no tenéis que hacer nada de eso. Lo que ocurre es que automáticamente la gente se da cuenta de que sois personas sabias. Desde la antigüedad, en todas partes se ha alabado al hombre sabio. No está preocupado por su situación económica o emocional, por nada. De lo que se preocupa es de si se está comportando o no como una persona sabia. Esa es la primera señal de las bendiciones de Dios. Aquel que tiene las bendiciones del Divino es una persona muy sabia, y su silencio demuestra su sabiduría.

Todo el Poder divino utiliza a esa persona como instrumento y hace un gran trabajo. Ese mismo hombre se sorprende de cómo ha podido suceder. Tanto el hombre como la mujer pueden tener esta sabiduría. Cualquiera puede tenerla, y también esa profundidad, ese temperamento que es tan hermoso y tan lleno de autoridad.

Una persona así no insulta a nadie, no se molesta en maldecir a nadie porque su sabiduría se hace cargo. Nunca se enfada con nadie; pero algo opera (en silencio). No pierde los nervios. Sin embargo, el propio enfado o cólera opera de tal manera que os hiere, algo que no esperabais. Ser sabios es una capacidad que está en vosotros, en vuestro poder como seres humanos. He visto animales que tienen una gran sensibilidad a las vibraciones; son extremadamente sensibles. ¿Cómo es posible? Porque su sabiduría está intacta. Funciona en su interior, pero no son conscientes de ella. La diferencia está en que los seres humanos son conscientes de su sabiduría. Esta es la única diferencia. Los animales tienen sabiduría, pero es automática, natural diríamos. Ahora bien, ¿cómo hemos establecido o desarrollado esta sabiduría en nuestro interior? A través de la meditación y a través del entendimiento de bhakti y shraddha.

Por eso es muy importante entender el valor del bhakti en vuestro interior. No podéis alcanzarlo superficialmente. Aquellos que son superficiales nunca lo conseguirán. La sabiduría solo viene a través del entendimiento de lo que significa sabiduría. Puede que encontréis a alguien extremadamente sabio; puede que sea vuestro sirviente, vuestro conductor o cualquiera. Os sorprenderá cómo una persona así puede ser tan sabia; puede que tenga esta sabiduría desde su vida anterior o puede que la haya buscado y la haya encontrado. No es que sea el estado de una sola persona ni la propiedad de una sola persona, sino que puede pertenecer a muchos.

Ahora bien, el sahaja yogui sí que debe tener sabiduría. ¿Por qué haces esto? ¿Qué necesidad hay de hacerlo? Él no tiene que hacer ninguna pregunta. Simplemente no hace cosas malas. Siempre está en el camino correcto. Sinceramente, creo que esa es la señal de un sahaja yogui, y es la bendición de la Diosa. Si el Poder de la Diosa está trabajando en vosotros, tendréis la sabiduría para solucionar todo.

Habéis visto que mucha gente ha venido a América y han hecho todo tipo de cosas. Todos han desaparecido. Nadie les ha apoyado. ¿Dónde están? Están acabados, pues solo les preocupaba el dinero y el poder. No sé hacia qué estaban orientados, pero lo han perdido. Sin embargo, una persona que solo depende de su sabiduría es un santo, o así lo llaman. Todo sahaja yogui podría ser un santo, un sabio. Pero si perdéis vuestra sabiduría, entonces perdéis vuestro valor.

Debo deciros una cosa: es vuestra sabiduría la que os salvará. Ella os ayudará inconscientemente. Había un sahaja yogui que, en cierta ocasión, iba en su coche y de repente decidió desviarse por otra carretera. En la que él dejó, hubo un grave accidente en el que hubiera estado implicado. Como ese, son muchos los incidentes que la gente me ha contado: "Madre, cómo nos salvaron, estuvimos a punto de morir y sin embargo estamos vivos". Eso es porque el Divino os necesita. El Divino no quiere que muráis o desaparezcáis. Os necesita muchísimo. Tiene que llevar a cabo su tarea y vosotros sois su instrumento. Si tenéis sabiduría, sois el mejor instrumento para que el Divino lo consiga.

Al principio los poderes de la Devi estaban solo en su cuerpo, y así es cómo mató a muchos demonios y gente maligna. Pero ahora no es necesario porque vosotros estáis aquí. Vosotros sois el instrumento y todo funcionará de tal manera que aquellos que os están intentando destruir, que están intentando eliminar lo bueno y a la gente sabia, serán destruidos, se acabará con ellos. Todos serán eliminados. Esto no se llevará a cabo con ningún elemento externo, sino con vuestra sabiduría, pues es el instrumento más grande para conseguirlo.

Como sabéis, cuando vine a América por primera vez, vi algo horrible: la gente corría detrás de gurus terribles. No volví más hasta pasados nueve años. En aquel momento dije: "esta gente está loca. ¿Cómo siguen a esas personas tan horribles y por qué creen en ellas? No tienen la sabiduría para entender cómo es la verdad". Hoy está funcionando. Podéis ver que somos mucha gente.

Así que ya sabéis en qué consiste la sabiduría, y si esta sabiduría llega a los americanos, vendrán a Sahaja Yoga. Y no solo eso, sino que ganarán profundidad. Con sabiduría tendrían que ver, "¿qué vamos a hacer? ¿Qué vamos a conseguir? ¿Cuál es nuestra meta?" Esto se lo tenéis que dar vosotros, y es algo que no se suele hacer. Debéis hablar con ellos y decirles que lo que hay en su interior es el Espíritu. Os deberíais convertir en el Espíritu. Todos los santos lo han dicho. Entonces, ¿por qué no llevarlo a cabo? En ese momento ellos mismos sentirán: "Sí, es verdad". Se ha dicho que deberíais convertiros en el Espíritu. Ellos van a las iglesias, a los templos; acuden aquí y allá sin entender por qué lo están haciendo. Necesitan protección, por eso lo hacen. Pero la protección procede de vuestro status espiritual. ¿Dónde os encontráis con respecto al Espíritu? He visto que aquellos que han disfrutado del Espíritu no se desvían del camino correcto. Pero aquellos que no lo han hecho, aunque se llamen así mismos sahaja yoguis, pueden estar muy equivocados.

Así que, primeramente, descubrios a vosotros mismos, ved si sois un verdadero sahaja yogui. Si de verdad queréis ser un instrumento de este poder, entonces lo que tenéis que hacer es llenaros de bhakti y shraddha, lo cual da mucho gozo, lo sé. Nunca os hace sentir cansados, ni os molesta, nada. Al contrario, es muy nutritivo y hermoso. Pero debería ser en el lugar correcto, con un entendimiento y un propósito correcto. Para ello, lo que necesitáis de nuevo es sabiduría, y por eso deberíais intentar descubrir si sois lo suficientemente sabios. ¿Sois sabios o no? A todo ser humano le resulta muy difícil saber si está en lo cierto o no, porque ya veis los efectos de esta sabiduría a vuestro alrededor.

Así pues, tener bhakti y shraddha hacia la Diosa, definitivamente, os da sabiduría. En India tuvimos algunas personas que hacían mucho bhakti y mostraban mucha fe (shraddha), pero no era real. No eran genuinos. Simplemente hablaban de ello o hacían cosas por ello, pero no eran honestos. La sabiduría es una cualidad muy, muy innata. No es superficial. No podéis decir simplemente que esta persona es sabia o no. Se muestra como un poder; es el poder de entendimiento, y está sostenido por el Poder de la Diosa. Ella es la dadora de sabiduría y esa es su cualidad más elevada. La sabiduría viene como parte del proceso evolutivo. Ella es la que ha generado todas las evoluciones hasta ahora, y para ir más allá, os va a convertir en personas muy sabias.

Incluso un simple sabio en un pueblo de un lugar muy lejano es respetado si es un verdadero sabio. Pero si es un estúpido, ¿qué podéis hacer? Puede que os engañe, que os juegue una mala pasada, etc. Y en ese caso, ¿consigue algo bueno para vosotros? No, nada. Así que lo primero es que la persona que se supone que es vuestro guru o guía debe tener bhakti, el bhakti de la Diosa. Es muy importante que entendáis esto. La modernidad ha llegado a tal límite que no se tiene respeto por la Diosa. Ni siquiera hablan de Ella; solo hablan de aquello que no se puede explicar ni entender. Si hablan de Cristo, no hablarán de Él, de que Él fue el que dijo en la cruz: "Contemplad a la Madre". ¿Qué necesidad tenía de decir eso? La razón es que Él no quería que su Madre tuviera problemas. Sin embargo dijo: "Contemplad a la Madre". Eso significa: "Esperad a la Madre, que va a venir".

Todos han señalado y han dicho eso. Y sin embargo, estamos preocupados con nuestro ego y nuestras propias ideas, y corremos detrás de cosas que no son reales. En primer lugar, debéis seguir solo aquello que sea real y no ilusorio. Para eso también necesitáis de nuevo la sabiduría. Creo que, precisamente para eso, necesitáis mucha más sabiduría. O tenéis primero la sabiduría o las bendiciones de la Madre; está entre estas dos cosas.

Debo deciros algo, y es que antes de que empecéis a extender Sahaja Yoga, por favor, juzgaos a vosotros mismos. Simplemente observad si sois sabios. También ved por vosotros mismos si tenéis las bendiciones de la Madre. Solo los sabios saben si tienen las bendiciones de la Madre o no. Y para ello tenemos muchas maneras de saberlo.

Lo primero y más importante es la meditación, sentir vuestras vibraciones ante la foto y haceos frente con claridad. Si sois un alma realizada, ¿sois verdaderamente un buen alma realizada o no? ¿Sois profundos o no? ¿Funcionan vuestras vibraciones o no? Si podéis ver eso, entonces os daréis cuenta de que, más grande que todas las ambiciones, es convertirse en una personalidad devota y sabia. Eso es lo que os dará gozo, gozo por todos los sahaja yoguis. De lo contrario, simplemente seréis como cualquier otro ser humano que va por ahí.

Ahora ha llegado el momento de hacer funcionar esto. Yo diría que es un tiempo especial, aunque de mucha lucha para mí, sin duda, pero no importa. Lo sé porque he venido a un lugar en el que las cosas no son tan sencillas. No importa. En general lo que siento es que podéis ayudarme mucho. Podéis apoyar mi trabajo si tenéis esa sabiduría. Y la sabiduría está en juzgaros a vosotros mismos; a cuántas personas amáis, cómo amáis, cómo os dirigís a la gente, qué queréis de ella. Todo esto es lo que deberíais hacer: juzgaos y haced introspección. Todo lo podéis ver a través de la introspección. Por tanto, es importante que un sahaja yogui haga introspección.

En segundo lugar debéis meditar, y en tercer lugar tomar las vibraciones. Es muy importante. En ciertas ocasiones veo que algunos dicen: "Madre, no hacemos esto ni lo otro". ¿Pero por qué? ¿Por qué no lo hacéis? "Hacemos trabajo sahaja". ¿Qué trabajo sahaja? Si no hacéis estas cosas tan básicas, ¿cómo es que sois sahaja yoguis? Y entonces traen muchas complicaciones y también sufren. Creo que de nuevo uno debe tener la sabiduría para entender lo que es Sahaja Yoga. Nadie entiende esto y a veces forman grupos que no comprenden lo que es Sahaja Yoga en absoluto.

Se trata de tener una personalidad muy, muy profunda. Sahaja Yoga no consiste simplemente en decir: "yo soy un sahaja yogui", sino que hay que tener una personalidad muy profunda, que otros han de sentir como muy sabia. No sois importantes por lo mucho que habléis, gritéis o por las muchas conferencias que deis. Sois importantes por la paz, la tranquilidad y la capacidad de amar que hay en vuestro interior. Y así es cómo la gente puede juzgar si vuestra Madre os ha bendecido o no.

Esta es una de las razones más importantes por las que he venido a América, para protegerla de los problemas, porque de repente se han generado muchos problemas. Era inevitable porque estaban tan ciegos como para no entender lo que iba mal, y esa ceguera les ha traído hasta este punto, en el que empiezan a ver especialmente su ego, que les ha arruinado. El afán de dinero les ha mostrado qué tontos han sido al creer que eran gente muy rica, y que podían hacer todo lo que quisieran con su dinero, dominando a otros países y otra gente.

Primero dominaos a vosotros mismos. Antes que nada tenéis que conoceros. ¿Qué es eso de dominar a otros? Aquellos que no saben dominarse a sí mismos siempre están tristes y tienen problemas porque reaccionan. Si intentáis dominar a otros, habrá reacción. Por ello, debéis ser totalmente introspectivos. Lo he venido diciendo una y otra vez: haced introspección. Por supuesto, debo decir que ahora hay muy buenos sahaja yoguis que lo han conseguido, y que son personas muy buenas, sencillas y sabias. Es una gran esperanza para mí. Nunca imaginé que lo lograría hacer tan bien, pero así ha sido. Y tened siempre presente que tenéis el poder en vuestro interior, que debéis usarlo y no caer en ideas absurdas.

Muchas gracias.