Shivaratri Puja. Puna, India. 17 de marzo de 2002.


Hoy nos hemos reunido aquí para celebrar el Shri Shiva Puja. Solo las personas limpias de Corazón pueden hacer este Puja. Un sencillo precepto de Shri Shivaratri es que los que no tienen el Corazón limpio no pueden hacer el Puja a Shri Shiva.

Como pudisteis observar ayer, unas serpientes horribles vigilan detrás del Shiva Linga. Esto significa que el Poder de Shiva, que son las serpientes, siempre protege a las personas de Corazón limpio y llenas de amor por los demás. Es muy simbólico. Pero debo decir que los animales entienden las fuerzas divinas mucho mejor que los seres humanos, porque tienen un corazón limpio. Mantienen la forma de vida propia de su naturaleza. Pero en su corazón no existe la malicia ni los celos, ni ningún sentimiento mezquino. Se comportan de esa forma porque se supone que así debe ser.

Sin embargo, los seres humanos tienen una cualidad única: la capacidad de amar y perdonar. La capacidad de amar de los seres humanos es tal que les permite vencer todas sus fuerzas negativas. Se dan cuenta fácilmente de que los defectos no son buenos, o comprenden que no está bien caer en comportamientos inhumanos. No tienen que caer en ellos necesariamente ni se les pide que lo hagan; pero de repente, son tentados por situaciones que les llevan al odio, los celos y la avaricia.

Ved cómo vive Shiva, en los Himalayas. Ved la ropa que lleva, lo que come. No necesita nada porque es completo, perfecto. Así es Shiva. Si le veneráis, debéis averiguar qué sentimientos alberga vuestro Corazón, qué tipo de malicia alimentáis.

Hoy en día, en India, la avaricia se ha convertido en el principal problema. La gente es muy mezquina y muy baja. Resulta imposible de entender, pero piensan que el dinero lo es todo. Es algo que no pertenece a la cultura de India en absoluto. Considerar el dinero como lo más importante lo han asimilado de otros países y se está extendiendo mucho.

Pensad en Shiva. Él nunca pensó en el dinero. Nunca lo deseó. Nunca quiso aparentar. Hay mucha diferencia entre la actitud de Shiva y la de la Shakti. Shiva es una personalidad absolutamente liberada, simplemente nada le preocupa. Si la gente comete errores, Él la destruye y ya está. No se preocupa por curarla ni por que se mejore, nada de eso. Sin embargo, estas cosas son importantes para la Shakti, porque el Universo es su niño, su hijo pequeño. Ella lo ha creado todo y naturalmente le preocupa y no le gusta la gente que se comporta de forma mezquina y absurda.

En primer lugar, los seres humanos cayeron en el deseo de poder. Iban de un país a otro para conseguir más poder. ¿Dónde está ahora ese poder? No queda nada. Sin embargo, lo que pasó es que transmitieron su estilo de vida a otros. Y ahora es muy normal que la gente sea desvergonzadamente avariciosa. La solución contra estas personas es Shiva. Él destruirá a todos los que son así. Primero quedarán expuestos y luego serán destruidos completamente.

Otro aspecto de Shiva es que respeta a las personas que tienen buen carácter, que tienen buena conducta. Sin embargo, no perdonará a quien tenga mal carácter o se comporte mal. La Shakti es pues, quien crea, protege, cuida y saca adelante a los seres humanos. Pero Shiva está sentado ahí, solo para destruir. Este aspecto de destrucción es muy importante. La Shakti no tiene esa cualidad. Ella quizá destruya algún rakshasha, pero Él puede destruir naciones enteras una detrás de otra.

En primer lugar, vuestro ego. ¿Quién lo destruirá? De alguna forma, Shiva también destruye el ego. Recordad que Él reside en vuestro Sahasrara, por encima de todas las cosas. El otro día vi a un presentador de las noticias muy tonto que estaba hablando de una forma muy desagradable. Vi su Ekadesha Rudra. Me dije: "Díos mío, este señor va a tener problemas". El Ekadesha no es otra cosa que los once poderes de Shiva. Se desarrollan aquí arriba y producen todo tipo de enfermedades. La peor de todas es el cáncer. Supe que este señor iba a pasarlo muy mal. Pero, ¿cómo puedo decírselo si no es sahaja yogui? ¿Cómo puede explicárselo alguien? Todo le vendrá del Ekadesha Rudra.

Estos once poderes de Shiva han sido muy bien descritos. Empiezan a trabajar en la gente, incluso en los sahaja yoguis, cuando no siguen los preceptos de Sahaja Yoga. Podríamos decir que Shiva lo observa todo, cada parte de vuestra vida, cómo os comportáis, lo que hacéis, vuestro dharma, todo. Muchos santos y encarnaciones os han advertido, pero os aseguro que si no les escucháis, entonces Shiva tampoco os escuchará a vosotros. Él no escucha a nadie. Si está enfadado, está enfadado de verdad, y pase lo que pase, es muy difícil convencerle de que perdone a una persona. Sin embargo, su cualidad básica es el perdón. ¿Os imagináis? Su cualidad básica es el perdón, pero cuando ya no perdona más, entonces es el fin. Perdona hasta un cierto punto, pero después la situación se hace extremadamente difícil.

Me parece que la gente no se da cuenta de quién es Shiva. En el sur de India hay dos tipos de devotos. Unos son los shivaites, y otros los vishnuvaites. Entre ellos hay grandes conflictos, aunque ahora mucho menos que antes. El trabajo de Vishnu es dar la Realización, la emancipación y la evolución a los seres humanos. Pero si falláis en vuestra rectitud, en vuestro dharma, entonces Shiva entra en vuestra vida. Debemos entender que sus poderes nos rodean, que estos nos han creado, y que la Shakti es quien os protege. Pero hasta un cierto punto. Ella no puede estar por encima de Shiva, no puede interferir en sus decisiones.

Hoy en día veréis que mucha gente se involucra en política. Todos lo hacen para ganar dinero. Lo que todos intentan hacer es dinero, no política. No hacen ningún bien a ninguna comunidad, en ningún sitio donde se padezca miedo o desamparo. Se comportan de tal manera que no tienen temor de Dios, no les asusta que su atención esté sobre ellos. Quizá no saben que Shiva les está observando. Él vigila a todos y cada uno, ya sean australianos, ingleses o indios. No importa de qué religión seáis; Él os observa. Esto es algo que debéis entender. Y cuándo lo entendáis, aceptaréis que hay que ser buenos y dharmicos. Tenéis que ser personas íntegras. ¿Por qué se habla de buena conducta? Intentad comprenderlo. La sinrazón de estos tiempos hace que la gente no crea en ello. Hacen todo tipo de cosas, beben, se dedican a enriquecerse, hacen cualquier cosa sin ningún temor a la ira de Dios. Y esa ira viene de Shiva.

Me gustaría advertiros a todos, aunque seáis mis niños: ¡tened cuidado! Intentad sopesar cada paso que dais. Por supuesto, estoy aquí para apoyaros, para ayudaros y protegeros. Pero no puedo ir más allá de Shiva, no puedo estar por encima de Él. El poder y la autoridad de Shiva son grandiosos. Venerarle significa venerar la bondad. La bondad puede ser compasión, puede ser amor, perdón, muchas cosas. A Él solo le gusta la gente buena, y solo protegerá a aquellos que sean buenos.

Por ejemplo, algunas personas están muy orientadas al poder; unas lo están al dinero y otras al poder. A veces, los orientados al poder lo hacen por dinero, la meta es el dinero. Esos no permanecerán en Sahaja Yoga. Serán expulsados. Se comportan así y luego vienen a pedir perdón: "Madre, perdónanos por lo que hemos hecho". No intentéis hacer nada parecido. Por supuesto que yo os perdono, pero Shiva no os perdonará. Os reprenderá y luego acudiréis a mí: "¡Madre, sálvanos!" Es muy difícil escapar de su control. Pero Él también perdona mucho. Os perdona muchas cosas. Lo hace por mí. Pero después de un determinado tiempo, cuando toma las riendas, entonces no hay súplica ni refugio que valgan.

No quiero asustaros, sino deciros la verdad, y esa es la verdad. Debéis intentar ser personas buenas. Tenéis que intentar ser gente verdaderamente íntegra. Me han contado que algunos sahaja yoguis se dedican al lavado de dinero y cosas así. También hay otros que se comportan muy mal. Van detrás de las chicas, las miran, etc. Esto ha arruinado especialmente a Occidente. Y ahora los indios lo están aprendiendo. Tenemos que respetarnos a nosotros mismos. Si no os respetáis y os comportáis mal, yo solo puedo ayudaros con la Kundalini. Pero si vais demasiado lejos, entonces sin ninguna duda, vuestro Ekadesha Rudra se obstruirá. Es como una gran barrera que hay en vuestra frente. El Ekadesha Rudra es muy eficiente y actualmente está muy activo. Es el origen de todas las enfermedades incurables que están apareciendo, así como de las posesiones que sufre la gente.

El otro día me encontré con alguien que estaba muy obstruido. Su Ekadesha estaba trabajando. Supe que estaba bajo alguna influencia fanática. No quiero hablar de estos hechos que hemos descubierto, pero no son correctos. En todas las religiones hay gente que difunde ideas absurdas. Si no tenéis discernimiento sobre ellas, nadie puede ayudaros. Deberías tener completo discernimiento para saber qué está bien y qué está mal. Entonces, Shiva está con vosotros. Pero debo deciros que caer en todos esos disparates es autodestructivo. Pero lo que destruye al Ser, es el Poder de Shiva. Lo que aquí llamamos "Ser" es el Poder de Shiva. Él destruye de muchas formas diferentes. Puede que perdáis la reputación, la salud o la riqueza, os puede suceder cualquier cosa hasta ser completamente destruidos.

He conocido a personas que incluso en el lecho de muerte empiezan a hablar de dinero, de lo que les tienen que dar, de cómo conseguirlo, etc. En vez de hablar de Dios o de la Realización, hablan de dinero; es algo muy común. Pero mirad a Shiva, Él no posee nada, no quiere nada. No acepta lo que le dais como samarpana (ofrenda), se lo entrega a la Shakti para que Ella haga lo que desee con ello.

Ella es quien hace que todo funcione para vuestro bien, para haceros felices. Pero a Él eso no le importa. En este caso, sois vosotros los que debéis complacer a Shiva. Él no va a intentar complaceros. Sois vosotros quienes debéis hacer todo lo necesario para complacerle. Shiva tiene una personalidad muy difícil. En el Corán, no se diferencia a Shiva de Alá. Porque la gente con la que Mahoma tuvo que tratar no tenía ninguna cultura, era muy ignorante. Así que no dio detalles sobre las diferentes formas de Dios, y solo conocen a un "Alá". Pero no hacen diferencias entre las distintas tareas o aspectos de Dios. Estoy de acuerdo en que la que ama es la Shakti, pero también Ella puede enfadarse mucho. Y cuando se enfada, su ira no tiene fin.

Como sahaja yoguis, os tengo que pedir que desarrolléis las cualidades que complacen a Shiva. Tenéis demasiados deseos, anheláis demasiadas cosas. Nada de eso es necesario. Por supuesto que quiero que viváis bien, de una forma bella y no de una manera absurda, yendo a la selva o comportándoos como hippies; no se trata de eso. La cuestión es que el apego a las cosas debe desaparecer de vuestro corazón. A un Shiva bhakta no le importa el dinero, no sabe mucho sobre él. Es una persona extremadamente generosa. Es sencillamente generosa. Por la forma en que se comporta, la gente piensa que es tonta, pero yo no pienso así. No se le puede describir así. Un bhakta de Shiva se caracteriza por ser una persona a la que no le interesa el dinero; es generosa y dará cualquier cosa que se le pida.

Mahavira era así. Había ido a meditar a su jardín cuando vinieron Shri Vishnu y Shri Krishna y le dijeron: "Mira, no tengo ropa. Tú llevas esa prenda, ¿por qué no me das la mitad?" Él respondió: "De acuerdo, aquí tienes, quédatela.". Pues decía: "Aquí está mi casa y en ella solo me pondré mi propia ropa". No lo hizo para mostrar que la desnudez es importante. Sin embargo, los jainistas erigen estatuas inmensas de Mahavira completamente desnudo. Así es la perversión humana. Hay que saber por qué lo hizo realmente. Era muy desapegado, tan despegado que regaló su propia ropa, ¿qué hay de malo en ello? No lo hizo para exhibirse en absoluto. Pero la gente no entiende la generosidad. Y los jainistas son los menos generosos de todos.

Las cualidades de estas grandes encarnaciones no se han comprendido porque existe una especie de ilusión. Por ejemplo, Shiva siempre lleva muy poca ropa, muy poca. Nadie sabe lo que come ni cuáles son sus deseos, qué es lo que quiere. Si una persona que sabe mucho de música toca para Él, le parece bien. Si viene un necio a cantar, también le parece bien. No le importa. No es meticuloso para la música o las notas, si está bien interpretada o no. Está por encima de todas esas cosas, por encima de las formalidades establecidas en todos los campos. Él está más allá. Es la espiritualidad misma, está más allá de todo eso. Ya seas músico o artista, seas lo que seas, Él gozará. Su cualidad es gozar. Disfruta de todo lo que es simple y que se da con el corazón, goza de todo lo que se expresa con el corazón.

No tiene condicionamientos, como que "debe ser moderno" o "tiene que ser así o asá". No tiene ningún condicionamiento. No piensa como los seres humanos, que analizan meticulosamente cómo tiene que ser cada detalle, y que intentan desanimar incluso a quien produce arte, a quien crea con el corazón. La gente tiene muchos condicionamientos, pero si algo caracteriza a Shiva es que no tiene ningún condicionamiento de ningún tipo. Por eso se le llama "mast-maula" (aquél que está inmerso en el gozo y sin preocupaciones).

Si en vuestra mente hay algún condicionamiento, entonces no sois un shivabhakta. Está bien que vayáis bien vestidos, por ejemplo, pero no debéis tener el condicionamiento de que "si no lo hago, no soy como los demás, no estoy a la moda, etc." A la gente le cuesta mucho no aceptar las modas. Hoy en día hay modas de todo tipo. Les pregunto: "¿Qué es esto?", y responden: "Está de moda". ¿Acaso hay un dios detrás de esa moda o alguna deidad que os pide que la sigáis? Hoy aparecen y mañana desaparecen.

Lo que os estoy diciendo es que si tenéis que venerar a Shiva deberíais eliminar vuestros condicionamientos. Vivís en el mundo del Sahasrara. Pero si alguien no va vestido adecuadamente o lleva ropa demasiado común, es el acabose. Los seres humanos tienen la capacidad de criticar a todo el mundo. Esa crítica no tiene fundamento. Si al menos se hiciera basándose en las vibraciones, podría entenderse. Pero no se usan las vibraciones, simplemente se critica a alguien porque "no va a la moda". ¿Qué moda sigue Shri Shiva? Decidme, ¿sigue alguna? Es feliz con cualquier cosa que Le deis. Come cualquier cosa que Le ofrezcáis. Está lleno de aprecio porque es la personificación del gozo. Él es paz y gozo. Si veneráis a Shiva, no deberíais tener ningún condicionamiento de ningún tipo.

Yo normalmente llevo saris muy sencillos. Y por eso la gente piensa que soy una mujer muy pobre. Soy pobre porque no me interesa el dinero, no me importa en absoluto. Debemos saber que Shiva es la persona más pobre, y el Dios más puro. No se pone ningún alankara (ornamento), no se pone nada, vive simplemente con su cuerpo. Porque Él no es sino la personificación del gozo, nada más que completa dicha y completo gozo.

Otra cualidad de un shivabhakta debería ser el gozo. Debería daros gozo todo, todo lo que veis, todas las personas que os encontráis. La única forma de lograrlo es abandonando la cualidad humana de la crítica, dejando de criticar a los demás. Por ejemplo, cuando los ingleses van a casa de los indios, dicen: "No nos gusta". "¿Qué es lo que no os gusta?" "No nos gusta la alfombra". La frase misma de "no me gusta" va en contra de vuestra shakti. O si un americano va a casa de un inglés, dirá: "No me gusta". Es algo muy común. Todo el mundo dice "no me gusta". Pero, ¿quiénes sois vosotros para afirmar "me gusta" o "no me gusta"? No os dais cuenta de que al hablar así estáis demostrando que no tenéis el Principio de Shiva en vuestro interior.

Puedo entender que se permita llevar bastón a alguien que no puede andar, estoy de acuerdo. Pero que él diga: "No me gusta tal persona porque no usa bastón", demuestra que es un individuo muy egoísta. Como él usa bastón pretende crear normas en un país democrático para que todo el mundo vaya con el bastón en la mano. Así es muy difícil. En Occidente es muy normal, por ejemplo, llevar un determinado sombrero o vestido. Hay condicionamientos para todo. Actualmente las mujeres llevan el cabello muy raro. No se ponen aceite en el pelo, no quieren que esté grasiento. Cuando van a reunirse con alguien, se lavan la cabeza. No me parece que quede bonito. Por supuesto, no digo que tenga que verse aceite en la cara o en las orejas, ¿pero qué importancia tiene?

Otro aspecto de nuestra vida es que somos muy egocéntricos. Queremos impresionar a los demás. Por ejemplo, la ropa que nos ponemos tiene que impresionar. Supongamos que impresiona, ¿y qué? Si viene una serpiente, te morderá independientemente de la ropa que lleves o de cuál sea tu país. Este tipo de identificaciones no son propias de un shivabhakta. Un shivabhakta debe estar totalmente inmerso en el éxtasis del gozo. Sin embargo, la gente es muy quisquillosa con el peinado, con la ropa, no sé con cuántas cosas más. ¿Qué ganan con eso? ¡Nada! ¿Es que gustan más así? ¿De qué sirve esta popularidad tan superficial?

Debéis tener respeto por lo que sois. No solo como seres humanos, sino como sahaja yoguis. Somos sahaja yoguis, somos los bhaktas de Shiva, y estos aspectos externos no nos preocupan. No nos importan, porque en cualquier caso, Shiva está en nuestro interior y brillamos con el poder interior de la Kundalini. ¿De qué sirve vestirse muy bien, si no tenéis buenas vibraciones? Si no se puede juzgar a una persona por las vibraciones, ¿qué valor tiene juzgarla por absurdos como el vestido o el bigote?

En Sahaja Yoga, vuestro sistema de valores tiene que ser sahaja. Mucha gente dice cosas como: "No me ha gustado su casa, no me ha gustado aquello...." La frase "no me gusta" es nishiddha (prohibida), y los sahaja yoguis deben abandonarla por completo. Si hay algo que no os gusta es que no sois sahaja yoguis. Por supuesto quizá os referís a alguien antisahaja o algo así pero, incluso entonces, ¿qué ganáis diciendo "no me gusta?" Es malgastar la energía. Por culpa de esto mucha gente me ha dado muchos problemas en Sahaja Yoga, porque son muy egocéntricos. Dicen: "Ese hombre es malo, aquella mujer es mala, tal persona es así o asá, etc". Y a veces me sorprendo porque cuando esas personas vienen a mí, descubro que son muy agradables.

La gente también es muy egoísta. He observado que algunos no se molestan en asistir a las reuniones o a los pujas. Tienen cosas que hacer. En total se celebran once pujas, pero ellos no asisten a ninguno porque están muy ocupados. Al menos deberíais venir a un puja. Los shivabhaktas no disfrutan de nada más que de los pujas. Todo su Ser está absolutamente vibrado de Shiva bhakti. Para ellos, lo más importante que se puede hacer es un puja.

También hay otros en Sahaja Yoga que intentan ganar dinero a costa de Sahaja Yoga. Esto está muy, muy mal. Sahaja Yoga es para obtener punyas, para conseguir bendiciones y, si esto no es lo que está en vuestra mente, entonces es mejor que abandonéis Sahaja Yoga. Podéis entrar en cualquier negocio o cualquier práctica deshonesta muy fácilmente. Allí estaréis hasta que acabéis en la cárcel.

Pero para gozar de vuestros poderes espirituales tenéis que aprender ciertas cosas. Una de ellas es "descondicionarse". Las frases "me gusta" y "no me gusta" deben desaparecer de vuestro vocabulario. Los gustos y desapetencias son solo para gente de comprensión limitada. Deberíais aprender a apreciar. Vuestro poder de apreciar las cosas demostrará lo dotados que estáis espiritualmente. Y vuestro poder de observación expresará lo que observáis. Por ejemplo, algunos vienen y me dicen: "No me ha gustado esa señora, llevaba un sari muy raro". ¿Pero qué es esto? "No me gustó porque se ponía la mano en la cabeza". ¿Y qué? Hacéis vuestra propia imagen de la gente y queréis que todos sean así, de lo contrario, no os gusta. La gente no va a cambiar porque a vosotros os guste o no. ¿Para qué malgastar vuestra energía?

A veces algunos músicos no son muy buenos. Recuerdo que una vez fui a casa y le pregunté a mí padre: "¿Qué tal canta este músico?" Me dijo: "Es muy decidido, muy valiente". "¿Por qué? ¿Qué ha pasado?" Me contestó: "Canta sin preocuparse demasiado, a veces desentona, otras pierde el ritmo, pero no le importa, sigue cantando. Es muy decidido. De esta forma solía apreciar mi padre. Cuando oí cantar a este señor comprobé que así era, pero mi padre exclamaba: "Wa-wa, wa-wa" y le animaba. He visto en mi padre estas cualidades divinas, su tolerancia, y no solo eso, su forma de apreciar. Solía apreciarlo todo.

Si los sahaja yoguis tienen esa capacidad de aprecio, gozarán de todo. Pues normalmente destruís el gozo, ¿sabéis? Aquí estáis una gran variedad de gente, con una gran variedad de vestidos, de familias y de países. Para mí solo sois sahaja yoguis, nada más que eso. Sois mis niños, eso es todo. No os juzgo por vuestra ropa o por vuestro peinado.

Todo lo moderno condiciona mucho. Os condiciona tanto que os volvéis irresponsables. Sois irresponsables como sahaja yoguis. Vuestra primera y más importante responsabilidad es Sahaja Yoga. Deberíais saber lo grande que es este trabajo. Transformar al mundo entero es una tarea grandiosa; ésa es mi visión. A mi avanzada edad sigo pensando lo mismo. Si ésa es mi visión, ¿cuál debería ser vuestra actitud? La de hacer lo imposible por expandir Sahaja Yoga. Eso es lo más importante. Os llamo a los pujas para que os renovéis, para daros más energía y todo eso. Pero si solo lo tomáis como una gran bendición y os quedáis sentados en casa, entonces no sirve de nada. Debéis extender Sahaja Yoga.

Me sorprendí cuando me dijeron que en Lucknow solo hay doscientos sahaja yoguis. ¿Cómo puede ser? La primera vez que fui allí había por lo menos tres mil, y eso sin haber establecido un lugar para las reuniones. ¿Os imagináis? Y de repente me encuentro con que se ha ido tanta gente. ¿Cómo puede ser que solo queden doscientos sahaja yoguis? O estáis mintiendo o no valéis para nada.

Por tanto, la primera y más importante responsabilidad de todos los sahaja yoguis es extender Sahaja Yoga. ¿A cuántas personas habéis dado la Realización? ¿Dónde habéis hablado de Sahaja Yoga? He visto que hasta cuando viajo en avión, cualquiera viene y me dice: "¿Sabes? Mi guru es tal persona, es genial", etc. Hablan de sus horribles gurus abiertamente, sin vergüenza. Mientras que vosotros sois muy tímidos para hablar de Sahaja Yoga. Nunca lo hacéis públicamente, a no ser que sea en los programas o en un programa público. Tampoco tenéis tiempo para Sahaja Yoga, sois gente muy ocupada.

Si queréis seguir a Shiva y obtener siempre sus bendiciones y su protección, tenéis que ser sahaja yoguis de muy alta calidad. Eso se demuestra cuando salís a extender Sahaja Yoga. Eso es lo que os falta. Estoy muy contenta de que en Australia Sahaja Yoga se haya extendido tanto. No sé lo que ha pasado, en un lugar tan alejado como Australia. Al principio hubo algunos obstáculos pero ahora se ha expandido. También ha sido así en Austria, y en Italia. Pero en otros lugares, sencillamente no crece. ¿Qué es lo que pasa? Lo que pasa es que los líderes no están haciendo todo lo posible. Por ejemplo, he recorrido Inglaterra de norte a sur, de este a oeste, en todas las direcciones. Sin embargo los sahaja yoguis de allí no son profundos. Tenéis que ir a las universidades, dirigios a la gente más joven. Si se extendió el movimiento hippy, ¿por qué no Sahaja Yoga? Si eso se propagó como el fuego, ¿por qué no puede propagarse Sahaja Yoga?

Tengo que advertiros de todas estas cosas, tened cuidado. Si tenéis la Realización, tenéis una responsabilidad y es la de dar la Realización a los demás, y la de extender Sahaja Yoga. Y si no podéis hacerlo, que Dios os proteja. Yo no tengo nada que decir. Tenéis que hacer introspección: "¿Qué he hecho yo por Sahaja Yoga? ¿Qué he recibido de Sahaja Yoga?"

Estoy segura de que después de este Puja a Shiva os dedicaréis a establecer el Principio de Shiva en vuestro interior. El Principio de Shiva no se conmueve, sino que es extremadamente firme y muy poderoso. Tenéis que dedicaros y rendiros. Por encima de cualquier otro trabajo, más allá de cualquier otra actividad, esto es lo más elevado.

Le pido a Shiva que os dé todas sus bendiciones para que os transforméis en la personalidad de Shiva.

Que Dios os bendiga.