Sahasrara Puja, "Salta al océano de amor"

Sorrento, Italia 6-5-1989

Anoche fue una noche de completa oscuridad. Se la conoce como Amavasia, y ahora acaba de empezar la primera fase de la luna. Hoy estamos aquí para celebrar el día en el que el Sahasrara fue abierto. También habéis visto la fotografía, que de hecho es una foto de mi cerebro, en la que se muestra que el Sahasrara fue realmente abierto. La luz del cerebro ha podido ser fotografiada; esto es algo grande que han logrado los tiempos modernos. Los tiempos modernos han traído muchas cosas que pueden mostrar la existencia del Divino. También me pueden probar a mí y os pueden convencer de lo que soy. Esto es muy importante porque en esta época actual este Advenimiento ha de ser reconocido, ha de ser plenamente reconocido, y esta es una de las condiciones para todos los sahaja yoguis.

Ahora bien, veamos qué está ocurriendo en la actualidad en los cerebros de la gente. Hoy día en los cerebros de las personas se está produciendo un ataque al Sahasrara. Este ataque viene de mucho tiempo atrás pero el ataque actual es el peor de todos los tiempos; porque están intentando hacer que el área límbica sea muy poco sensible. Hay novelas muy depresivas, pensamientos muy deprimentes y música muy triste y oscura; es como la absurda tragedia griega. Todo esto viene desde el periodo medieval hasta ahora en que esta nueva era ha comenzado. Aquella época no fue buena para el área límbica, pues nos hizo muy depresivos y caímos en el alcoholismo para escapar de las, así llamadas, "miserias".

Después vinieron estos tiempos modernos en los que la gente se hizo hiperactiva; la sobreactividad comenzó y con esto también el cerebro se volvió hiperactivo. De la oscuridad y tenebrosidad de antes se ha pasado al extremo opuesto, que es la sobreactividad. Para ensombrecer esto también la gente cayó en las drogas, se aficionó a una música horrible y así es cómo hicieron esta área límbica tan, tan insensible. Entonces una droga, que al principio era simplemente un estímulo, empezó a tomarse en mayor cantidad. Después tuvieron que tomar drogas mucho más fuertes. Así continuaron hasta el punto de pensar, como sabemos, que la droga es el único camino en el que pueden sobrevivir.

¿Por qué? A causa de las tensiones de las que hablan. En la época actual tenemos algo llamado tensiones. Nunca antes las hubo; la gente nunca habló de sus tensiones. Ahora todo el mundo dice: "Estoy en tensión". "Me produces tensión". ¿Qué es esta tensión? Es a causa de mi venida. El área límbica quiere saber sobre mí y la Kundalini también. Al extenderse Sahaja Yoga, intenta ascender en la gente. Como os convertís en canales, a dondequiera que vais generáis vibraciones y estas vibraciones incitan a la Kundalini o le lanzan un mensaje, y en algunas personas sube. Puede que no suba hasta el Sahasrara, incluso puede subir al Sahasrara, pero cae porque no hay un reconocimiento.

Así que, cada vez que hacen algo, la Kundalini sube en ellos y eso les produce una presión porque su Sahasrara no está abierto, es una puerta cerrada. Debido a esa puerta cerrada, se les produce una especie de presión en la cabeza que no identifican y la llaman tensión. En realidad, es la Kundalini empujando porque quiere salir hacia fuera pero no puede. También en aquellos que han recibido su Realización, si no mantienen su Sahasrara limpio, estas tensiones seguirán produciéndose. Por tanto, aunque el Sahasrara fue abierto hace muchos años, todavía nos quedan algunas cosas por hacer, y lo primero de todo es limpiar nuestro Sahasrara.

Así pues, lo primero que tiene lugar es la apertura del Sahasrara. Después, una vez abierto, tiene lugar la apertura del Brahmarandra y entonces empezamos a sentir la Gracia, que se mueve por nuestro Ida y Pingala Nadi. Es la Gracia, no la Kundalini. Y la Gracia, que es el Chaitanya, suaviza nuestro lado izquierdo y derecho, con lo que nuestros chakras se abren más, al tiempo que más hilos de Kundalini comienzan a abrirse camino hacia arriba. Por eso siempre les digo a los sahaja yoguis que deben meditar. Si vuestro Sahasrara está bien, todos vuestros chakras estarán bien porque, como sabéis, los Pitas o los centros que controlan estos chakras están en el cerebro, alrededor del área límbica. Por tanto, si vuestro Sahasrara está limpio todo funciona de una manera muy diferente.

"¿Cómo mantener el Sahasrara limpio?" Este es el gran problema sobre el que la gente siempre me pregunta. Sabéis que yo resido en el Sahasrara. He encarnado en el loto de los mil pétalos, por eso pude abrirlo. La forma que tengo, el modo en que me veis, es por lo que dicen que el Sahasrara es Mahamaya. Esta es la Ilusión que está ahí constantemente para vosotros. Es muy esquiva y tenía que ser así porque de otro modo no hubierais podido afrontarme, con todas las luces saliendo de mí, o de la manera en que ayer visteis el Sahasrara, como colores abstractos emitidos en todas las direcciones y las luces saliendo hacia fuera.

Por favor, no saquéis fotografías cuando estoy hablando, ¿de acuerdo? Las podéis hacer más tarde, no hay prisa. Simplemente prestad atención a mi charla; por favor, prestad atención, es importante. Se debería decir antes de comenzar que nadie sacara fotos durante el Puja, porque es algo muy intenso que ha de funcionar en cada uno. Por favor, prestad atención. Incluso aunque no entendáis la lengua, tiene un efecto en vosotros. Así que, os pediría que me prestaseis plena atención cuando estoy hablando. Funciona mucho mejor.

El Sahasrara tiene que ser cuidado por vosotros; es el templo de vuestra Madre. Cuando decís que me ponéis en el Corazón, en realidad me ponéis en vuestro Sahasrara. Porque como sabéis, el Brahmarandra, en el área del hueso de la fontanela, tiene el centro o pita que controla el Corazón; que a su vez es el asiento de Sadashiva, o podemos decir de Shiva. De modo que cuando me ponéis en el Corazón, en realidad me ponéis en la cabeza.

Ahora bien, el llevarme del Corazón al Sahasrara o del Sahasrara al Corazón, es el problema de dos tipos de persona. Hay personas que son muy sensibles de Corazón. Yo diría que en Europa los italianos son muy sensitivos en su Corazón. Lo primero que hacen cuando me ven es poner su mano en el Corazón. Y así es cómo debe ser; si para empezar intentáis sentirme en el Corazón, es mucho más fácil. Y para sentirme en vuestro Corazón, puede que os preguntéis: "¿Cómo hacerlo?" Tenéis que amarme como yo os amo; tenéis que amar a todos y cada uno de vosotros, porque todos estáis dentro de mí. Y no se puede enseñar a alguien cómo amar. El amor está dentro y se manifiesta si simplemente abrís vuestro corazón.

Pero deberíamos examinar qué es lo que impide que el Corazón se abra. En primer lugar, el condicionamiento. En Occidente, expresar amor se considera pecaminoso. A la gente le cuesta mucho decir: "Te quiero". Sin embargo: "Te odio", es algo que hasta un niño puede ir repitiendo sin parar: "Te odio, te odio". Pero odiar a alguien sí que es pecado. Por tanto, decir "Te odio, te odio", es un acto pecaminoso. Así que, lo que uno tiene que hacer es no dejar de decir: "¡Te quiero!" Después de todo, debéis amar a una persona que os es muy querida. Amáis a cualquier persona que ha hecho algo bueno por vosotros. Y si la misma Adi Shakti es la que os ha dado vuestro segundo nacimiento, amarla debería ser la cosa más fácil. Y si Ella dice: "Todos estáis dentro de mi cuerpo", entonces, debería ser incluso más fácil amaros entre vosotros.

Toda la limpieza del Sahasrara se lleva a cabo a través de este amor; un amor que no es condicionado, que no está cohibido, que no quiere ningún descanso, que no quiere nada a cambio, Nirvach. Pero los condicionamientos son demasiados. El primer problema del condicionamiento viene a vosotros cuando pensáis que una situación o condición os hace odiar a alguien o decís: "No puedo amar a esa persona porque tengo este condicionamiento". Pero en realidad el condicionamiento en sí mismo es absurdo si lo examináis en detalle.

Para hacerlo fácil, me gustaría que comprendierais el tema de los condicionamientos. En cierta ocasión, leí un articulo muy interesante titulado: "¿Quién mató el romanticismo?" El autor decía que los peluqueros; y yo me preguntaba: "¿Cómo relaciona el romanticismo con los peluqueros?" Porque la gente solía ir a la peluquería. Y si había una persona a la que le gustaba determinado tipo de peinado, entonces decía: "¡Oh, me encanta ese peinado!" Pero suponed que su novia o su esposa llevase otro tipo de peinado; porque todos los días salen cosas nuevas, entonces, inmediatamente el marido diría: "¡Oh, te odio por ese peinado!" Porque a él le gusta un tipo de peinado; por eso lo ama. Y si el peinado es otro, entonces lo odia: "¡No me gusta!"

El mero hecho de decir: "Me gusta". "No me gusta" es un signo de que el condicionamiento es muy fuerte. Os peináis y vestís apropiadamente, salís y de pronto la gente dice: "¡Oh! ¡Lo odio!" ¿Quiénes sois vosotros? ¿Qué derecho tenemos a decir eso a nadie? No sois ningún juez nombrado por un tribunal, así que, ¿por qué lo decimos? Decimos: "Odio esto" para dañar a alguien. Al contrario, debe decirse: "Vale, me gusta, pero podría estar mejor". Ese es el signo del amor, cuando queréis que una persona se vista de una forma hermosa. Pero esto hablando desde un nivel muy básico de ver a la gente. Después vamos más allá viendo en una persona lo inteligente que es, lo elegante que es, lo carismático que es, lo encantador que es. Esta última palabra es un término muy engañoso.

Estos son también condicionamientos de la mente por los que pensáis que una persona con un estilo particular es muy seductora, que os encanta esa persona. Todo es muy superficial. Luego hay otras personas que en realidad no aman, pero que aparentan que aman porque alguien tiene mucho dinero. Él no va a compartir su dinero, no hay duda, pero se ama a esa persona porque tiene más dinero, porque tiene un coche mejor o va mejor vestido, por lo que sea. Pero este tipo de ideas matan el amor. Y si se mata al amor, el gozo se pierde, porque no puede haber gozo sin amor. Gozo y amor son la misma cosa.

Entonces el condicionamiento se va haciendo más y más sutil, y ahí empezamos a amar solo a nuestros propios niños. Esto es muy común, aunque también se da el caso de gente que ni siquiera ama a sus propios hijos. Hay de todos los tipos. Los del caso anterior andan siempre diciendo: "Este es mi niño, este es mi hijo" y esto es, de nuevo, la muerte del amor. Como ya os he dicho antes la savia del árbol sube, llega a todos los frutos, a todas las hojas, llega a todas las partes del árbol y luego regresa; no está apegada. Si estáis apegados a una parte o a una flor por el hecho de que sea más bonita, entonces el árbol morirá, la flor también morirá y así es la muerte del amor.

Por tanto, debéis sentir un amor que no se enrede o no se apegue. Siempre que digo esto, la gente se pregunta: "¿Cómo conseguirlo?". El amor del Espíritu es de esa clase. El amor de la mente condicionada es diferente; una mente condicionada solo puede amar de una manera limitada porque está condicionada. El enemigo más grande del amor es el ego, que está dentro de nosotros, que es como un globo encima de nuestra cabeza. Y este ego nos produce una gran tensión.

Respecto al condicionamiento, digamos, por ejemplo, que alguien ve una alfombra y según su condicionamiento dirá que no es buena. Dirá: "¡Oh, qué alfombra!". Este es un condicionamiento de un nivel muy bajo. Un condicionamiento "más elevado" es, como mucho, que uno ame a su propio país. Entonces dice: "Mi país es el mejor"; tanto si su país está matando gente como si está destruyendo la paz del mundo, da igual, puesto que: "Yo pertenezco a un país en concreto, este país es el mejor, etc." Nunca podemos criticar a nuestro país o a sus ciudadanos.

Todo este condicionamiento se va haciendo más y más sutil, pero cuando llegamos al nivel de la inteligencia es aún mucho peor. Porque si, a través de vuestra inteligencia, habéis entendido que algo es bueno, entonces nadie puede salvaros, ya que lo habéis entendido a través de vuestro cerebro. Esto es realmente sorprendente. Estaba leyendo un libro escrito por Rabidranath Tagore y un inglés había hecho un prefacio muy bonito para este libro; en la introducción decía que la creatividad en Occidente había sido aniquilada y entonces le preguntaba a un caballero que era un crítico hindú: "¿Ustedes no critican a sus poetas? ¿No tienen críticos?" "¡Sí, sí, tenemos críticos!" "¿Y a qué hacen críticas?" "¡Ah!, pueden criticar que ha sido época de pocas lluvias, que por eso tuvimos problemas y cosas así". "¡No, no!, me refiero al poeta. ¿Se critica al poeta, al artista?" Y el otro responde: "¿Es que acaso hay que criticarlo? Ha hecho una creación. Él ha creado lo que ha sentido. En el caso de que haya puesto algo muy vulgar, claro que no nos gusta, pero si ha sido creado por una mente hermosa, tiene que ser bello." "Entonces, ¿ustedes no hacen críticas?", dijo el inglés. "¡No!", contestó el hindú. "Porque nosotros no podemos crear así. Si no, ¿qué sentido tiene crear?"

Esto es lo que hemos hecho desde la inteligencia. Tenemos normas respecto a todo, respecto al arte, respecto a cualquier creación. No nos gusta esta alfombra. ¿Por qué? "Porque no se corresponde con el entendimiento intelectual que hemos llegado a tener de las normas; y en ese marco no encaja, así que, no nos gusta." ¿Acaso vosotros podéis crear siquiera un solo centímetro de algo así?

Este ego os da un acción no autorizada, que no está permitida, Anadikara Chesta, no autorizada. No tenéis autoridad para criticar. No podéis crear nada, entonces, ¿por qué deberíais criticar? Es mejor apreciarlo y ver por vosotros mismos que no tenéis autoridad, que no la merecéis para criticar. Si no la merecéis, ¿por qué habríais de criticar nada? Y por otra parte, también debéis saber que sois esclavos de vuestro ego, cualquier cosa que dicta vuestro ego y vuestra inteligencia, o así llamada "inteligencia", os lleva a un punto, a una norma, que al final se convierte en un ego colectivo de una comunidad en particular, de un país determinado, de una ideología en concreto. Se hace colectivo y luego dicen: "Nosotros creemos que esto no es arte".

Esta es la razón por la que ya no podemos tener maestros en arte; no podemos tener un Rembrandt, no podemos. Pobre Rembrandt, debió sufrir mucho. Como sabéis, Gauguin también sufrió mucho. Todos esos artistas sufrieron mucho, incluso Miguel Ángel sufrió mucho, y no solo económicamente, sino de otras maneras también. Fueron criticados, muy criticados. Por eso creo que los artistas se han rendido. Conocí a un artista que había hecho muchas obras de arte y le pregunté: "¿Por qué no me las enseña?" "No, no quiero mostrárselas; las he creado para mí mismo". "Pero me gustaría verlas", le dije. Vi que eran verdaderamente hermosas, muy hermosas y le pregunté: "¿Por qué no las exhibe?" "No sirve de nada", contestó. "La gente solo las criticará. Las hago por propio placer, pues ellos echarían a perder todo el gozo de mi creación".

Por tanto, una de las cosas básicas que deberíamos evitar es criticar a los demás. Mejor criticaos a vosotros mismos; criticad a vuestros hermanos o hermanas, criticad a vuestro país, criticad todos los hábitos que tenéis y reíros de vosotros mismos. Eso es lo mejor. Si sabéis cómo reíros de vosotros mismos, entonces no tendréis objeciones ni os meteréis con la creatividad de otra persona. Así que, con vuestro ego os desautorizáis tanto que podéis llegar a criticar cualquier cosa. Creéis que tenéis el derecho. ¿Quién os ha dado el derecho a criticar? Esa es la pregunta que uno debería hacerse a sí mismo. ¿Cómo podemos criticar a nadie?

Como santos que sois ahora, desde luego podéis diferenciar quién tiene obstrucciones, quién es el que ha dado malas vibraciones, quién tiene el problema. Vosotros sabéis todo eso. Lo sabéis, no es un condicionamiento, no es algo que hacéis porque hay ego, sino que lo sentís en vuestros dedos. Es un sentimiento real dentro de vosotros; es el Boddha, por el cual sabéis. Entonces, ¿qué deberíais hacer? En vuestro amor tenéis que decirle a la persona, si es posible: "Esto está mal en ti, mejor que lo corrijas". Pero hacedlo de tal manera que la persona lo haga. Si por el contrario se lo decís de forma que el problema se agrava aún más, entonces es que no amáis a esa persona en absoluto. Permitid que todo el mundo crezca.

Hay muchas personas en Sahaja Yoga que son muy, muy buenas, excelentes, sin duda, pero también hay personas a las que podemos llamar muy "difíciles", mucho; es como si tuvieran una grieta en su cabeza, como si les faltara algún tornillo. Creo que, a veces, se comportan como payasos. Hemos conocido algunas personas así, no lo pueden evitar, aunque a veces sean muy inteligentes, o en otras ocasiones muy agudos. Pero en Sahaja Yoga no pueden bajar a ese nivel donde podáis decir entonces: "El crecimiento es posible".

Supongamos que la Madre Tierra estuviese tan caliente como el Sol; entonces no hubiera habido crecimiento. O si estuviese fría como la Luna, tampoco hubiera habido crecimiento. Tenía que estar en el centro, donde tenía ambas cosas, frío y calor, en la proporción adecuada para crecer. De la misma manera, el ser humano ha de conseguir mantener una moderación y un equilibrio, y comprender que no hay que ir a los extremos de nada. Ese equilibrio lo aprendéis cuando amáis a alguien.

Como sabéis, en Sahaja Yoga, a veces tenemos que pedir a algunas personas que dejen Sahaja Yoga; pero esto se hace por amor a ellos, porque una vez que salen fuera, mejoran mucho. He visto que mejoran tremendamente. Sin embargo, cuando están dentro de la colectividad de Sahaja Yoga, se convierten en una molestia y quieren ser aún más molestia, porque su ego entra en juego o quizá porque su condicionamiento toma parte en el asunto. Pero sea lo que sea quieren ser una molestia; así que, tenemos que decirles que, por favor, se vayan por un tiempo.

Ahora bien, si esta actitud de molestar, en la forma que sea, desaparece de la persona entonces tiene que ser una persona muy humilde y no puede volver a ser una molestia. Lógicamente puede ocurrir que si le decís a una persona: "Mira, esta es la razón por la que queremos que salgas", esta reaccione. Puede tratarse de personas extremadamente problemáticas, lo sé, pero debéis mostrar una paciencia infinita y un total entendimiento y debéis hablar como una persona que ama.

El amor tiene tal poder que nadie quiere hacer nada que sugiera que no ama. Es algo muy poderoso; une a las personas de una manera tan hermosa que provoca que se quiera hacer algo. Por ejemplo, queréis darme flores porque sabéis que me encantan las flores. Así pues, queréis darme flores para dar a entender: "¡Madre, te queremos!" Yo sé que me queréis, pero queréis algo así como enfatizarlo, reforzar ese pensamiento en mí. Por eso queréis darme una flor, para mostrar vuestro amor, una expresión de vuestro sentimiento interno hacia mí. Todos los objetos materiales pueden ser utilizados para expresar vuestro amor; pueden expresarlo fácilmente, de tal manera que la otra persona sepa lo que es amor.

Pero todo el Poder del Sahasrara es Amor. Por tanto, ved que este cerebro tiene que amar; el cerebro ha de amar. Después de verificar los poderes de Sahaja Yoga a través de vuestro cerebro e inteligencia, si llegáis al punto en el que comprendéis que "no, no sirve de nada analizar ni sintetizar ni hacer nada de estas cosas, sino que simplemente es amor, es solo amor", entonces el mismo Sahasrara, que ha sido usado antes junto con el cerebro para analizar, para criticar, para hacer todo tipo de cosas absurdas, ahora quiere amar y gozar del amor. Y esta es la culminación, cuando el cerebro simplemente ama. Esta es la situación que uno ha de alcanzar: que el cerebro simplemente ame, que solo conozca el amor, porque ha visto el poder del amor.

Llegáis a una conclusión lógica y finalmente lo veis claro. Como Adi Shankara, que escribió el Viveka Chudamani y todos esos tratados hasta que lo dejó todo y dijo: "No, no hago más". Y simplemente escribió la alabanza a la Madre, nada más. Una vez que llegáis a ese punto, entonces podéis decir que estáis en Nirvikalpa, porque no hay Vikalpa, no hay dudas en vuestra cabeza, y porque amáis. Cuando hay amor no tenéis dudas, no os hacéis preguntas. Solo cuando pensáis, dudáis; pero cuando amáis, no dudáis, simplemente amáis porque gozáis amando. Y por esa razón "el amor es gozo y el gozo es amor".

Después de mucho tiempo, el Sahasrara ha sido abierto. Tenemos que abrir nuestro Sahasrara de nuevo a través de nuestro proceso meditativo, entendiéndonos a nosotros mismos y a los demás, o quizá llegando a la conclusión lógica de que ahora no hay otra salida. Hemos llegado al final; toda la lógica ha terminado ahora. Saltad al Océano del Amor y ya está. Una vez que saltáis al océano del amor ya no queda nada por hacer, solo gozar de cada una de sus olas, de cada uno de sus matices, del contacto con este océano. Eso es lo que uno debe aprender razonando que "Sahaja Yoga no es nada más que amor".

Que Dios os bendiga a todos