
Introspekcja i Medytacja
18.06.1988 Seminarium , Shudy Camps, Wielka Brytania,

Myślę, że w tym roku nie będziemy mieli, programów publicznych w Wielkiej Brytanii, z powodu pewnych okoliczności. Jeśli kiedykolwiek dzieje się tak, że coś w taki czy inny sposób zmienia nasze programy, musimy od razu zdać sobie sprawę, że za całą tą zmianą kryje się jakiś powód. I od razu musimy to zaakceptować z otwartym sercem. Boskość chce, żebyśmy się zmienili. 

Przypuśćmy, że jadę drogą i ludzie mówią "Matko, zgubiłaś drogę". Wszystko w porządku, nigdy się nie gubię, ponieważ jestem sama ze Sobą. Ale musiałam pojechać tą konkretną drogą, w tym rzecz. Musiałam to zrobić. Prawdopodobnie dlatego nie powinnam znaleźć się na tej drodze i z tego powodu zgubiłam drogę. Jeśli macie ten rodzaj zrozumienia i takie zadowolenie w waszych sercach, wtedy zauważacie, że życie warte jest znacznie więcej niż wam się wydaje. 

Myślałam o tym, jaki był powód tego, że zdecydowaliśmy się przeprowadzić programy publiczne w tym roku, a nie mogliśmy ich zorganizować? Powód jest taki, że musimy się umocnić. We wzroście drzewa, które jest żyjącym drzewem, dzieje się tak, że ono rośnie w określonym kierunku, do pewnego punktu, gdzie musi się zmienić, ponieważ z tej strony nie pada światło słońca, może nie dociera w to miejsce woda, więc zaczyna się zmieniać. 

Należy zrozumieć, że w ten sam sposób my znajdujemy się w rękach Boskości. I jeśli jakieś plany ulegają zmianie, odzwierciedla się to w nas i musimy zrozumieć dlaczego. A powodem jest to, że musimy się umocnić. Wzmocnienie Sahaja yoginów jest bardzo ważne. Aby siebie wzmocnić, przede wszystkim musicie robić introspekcję. Musicie robić introspekcję. To znaczy odbijać światło wewnątrz siebie i przyglądać się sobie. Czego dokonaliście w Sahaja Yodze do tej pory? Gdzie się znajdujecie? Jak daleko zaszliście? I jak daleko musicie zajść? Czego w was brakuje? 

Będziecie zaskoczeni, kiedy zaczniecie obserwować siebie w bardzo obiektywny sposób, nie usprawiedliwiając siebie, nie winiąc żadnych buców i nie winiąc żadnych badhas w was, czy kogokolwiek innego. Jeśli zaczniecie się przyglądać, co poszło z wami nie tak, że nie mogliście odpowiednio się wzmocnić, będziecie zaskoczeni, że wciąż były to "zasiedziałe" problemy, które trzeba skorygować. A te problemy możecie bardzo wyraźnie zobaczyć. W świetle Ducha, możecie bardzo wyraźnie je zobaczyć, że "to poszło we mnie nie tak". 

Jedną z najciekawszych rzeczy, jakie zauważyłam jest to, że Sahaja Yoga cały czas przykryta jest pewnego rodzaju mayą. A ta maya jest ignorancją, czasami całkowitą, czasami częściową. Kiedy przychodzicie do Sahaja Yogi zostajecie pobłogosławieni. Być może wasze rodziny są pobłogosławione, wasze dzieci są pobłogosławione. Otrzymujecie pewne błogosławieństwa dotyczące zdrowia fizycznego, a także finansowe, dostajecie pracę, pieniądze. Otrzymujecie coś wyjątkowego, co jest prawdziwym cudem. Ludzie bardzo się gubią w tych osiągnięciach, zaczynają dryfować i myślą: "Dostaliśmy te błogosławieństwa, nie musimy już nic robić", że zostaliście sowicie wynagrodzeni za wszystko, co do tej pory zrobiliście. To nie tak. To jest tylko pewien rodzaj wsparcia, które dostajecie, żeby wasza wiara w Sahaja Yogę została w pełni ustanowiona. W szczególności powinniście poznać Mnie, czym Ja jestem. Ale jeśli wy wciąż będziecie dryfować, wtedy niektóre z tych błogosławieństw mogą przemienić się w przekleństwa. I wtedy możecie czuć, że spadło na was wielkie nieszczęście i jak bardzo to wszystko poszło w złym kierunku. 

U niektórych ludzi potrzeba czasu, żeby poczuli i żeby zaczęli odczuwać błogosławieństwa. Na przykład, przeważnie zgodnie ze współczesnymi pojęciami, wydaje nam się, że pieniądze są największym błogosławieństwem i wielu również je otrzymuje, ale w rzeczywistości nie są. Uzyskanie wewnętrznego spokoju, uzyskanie stanu świadka i prawidłowe odczuwanie swoich wibracji, bycie w centrum, nieprzerwany wzrost - to są prawdziwe błogosławieństwa. Ponieważ dzięki temu uzyskujecie wszystko inne. 

Spełnienie możliwe jest tylko wtedy, kiedy wewnątrz was tętni absolutna radość. W końcu wszystko jest tylko środkiem do osiągania radości, odczuwania radości. To nie jest koniec. Gdyby tak było, to ci ludzie, którzy mają pieniądze, dobre zdrowie, którzy odnoszą tak zwane sukcesy, powinni być szczęśliwi i spokojni, ale nie są. Oni cierpią, bardzo cierpią. I w pewien sposób oni niszczą siebie, dzień po dniu, ponieważ nie znoszą swojego życia, nie mogą go znieść. Nie mogą zrozumieć, po co przyszli na świat. 

Wszystkie te błogosławieństwa, które otrzymujecie, wszystkie te zmiany, które wam się przytrafiają, wszystkie te nowe perspektywy, które otwierają się przed wami, musicie wiedzieć, że są dla waszego dobra, wszystko jest dla waszego dobra. A waszym dobrem jest wasz wzrost, nic innego tylko wasz wzrost. Cała reszta jest bezużyteczna i bezowocna. Jak tylko zrozumiecie, że właśnie to musicie osiągnąć w życiu, tym musicie się cieszyć, wtedy to zacznie się wypracowywać. 

Ale, jak widzicie, w Sahaja Yodze jest miłość i współczucie. Nie ma wielu restrykcji. Wasz rozwój jest pozostawiony wam samym. To wasz Duch ma was prowadzić. Nie ma nieustannego namawiania czy poprawiania. To wam pozostawione jest zrozumienie siebie, obserwowanie siebie i wypracowywanie tego. A jednym z kryteriów powinno być: Co ja zrobiłem dla Sahaja Yogi? Co zrobiłem dla Matki? Te dwie rzeczy należy zrozumieć, to bardzo ważne. Każda najdrobniejsza rzecz, jaką mógłbym zrobić dla Sahaja Yogi jest istotna, ponieważ jeśli macie inteligencję, to możecie zobaczyć, że najwspanialszą rzeczą, jaką macie robić, jest praca dla Boga. To jest najważniejsza rzecz, w jaką do tej pory zaangażowały się istoty ludzkie, to jest najwyższego rodzaju przedsięwzięcie, w jakie kiedykolwiek istoty ludzkie miały okazję zaangażować się. A jakaż jest to szansa! 

Mówicie: "Matko, jesteśmy przeciętni, do niczego, bezużyteczni" - ale to wy jesteście wybrani. Jesteście wybrani, więc musi w was coś być. Mogliście nie dostrzec tej części siebie, która będzie wykonywać tę wielką pracę Boga. Musicie więc odkryć i dowiedzieć się: "Dlaczego zostałem wybrany do Sahaja Yogi? Co mogę zrobić w Sahaja Yodze? Co mogę wypracować w Sahaja Yodze?" Powinniście stale sobie przypominać: "Zostałem wybrany do Sahaja Yogi. Chcę w pełni skorzystać z tego, co daje Sahaja Yoga". Przypuśćmy, że ktoś nie ma pieniędzy. On oczekuje, że Sahaja Yoga powinna dać pieniądze, pracę, musi dać to, tamto, dzieci, dobre zdrowie i tak dalej. Oczekiwania są w porządku. Ale "co ja zrobiłem dla Sahaja Yogi?" To kolejny punkt introspekcji. 

Bardzo ważne jest, żeby zrozumieć, iż musimy zrobić coś dla Sahaja Yogi. To nie są pieniądze, to nie jest praca, to nie jest myślenie, to nie jest żaden rodzaj wsparcia. Ale jedną z tych rzeczy, najważniejszą, jest to, jak wielu ludziom daliście Realizację. Musicie policzyć, ilu osobom byliście w stanie dać Realizację, ilu ludziom mówiliście o Sahaja Yodze. Może myślicie, że dajecie Realizację jakimś ludziom, a oni przychodzą i znikają, to nieistotne. W końcu do was przyjdą. Dzisiaj spróbujcie z kilkoma, zagubią się. Jutro znowu. Musicie być nieugięci. 

Jak wiecie, Ja ciężko pracuję w Anglii. Samo moje przybycie do Anglii było z góry ustalone. Była potrzeba, abym tu przybyła, żeby serce lepiej funkcjonowało. Ale serce jest letargiczne, wiecie o tym. A letargiczne serce łapie różnego rodzaju problemy. Pomimo tego, pracowałam przez te wszystkie lata, każdego roku, gdy tylko mogłam, poświęcałam czas Sahaja yoginom, ich problemom, Sahaja Yodze, ich najmniejszym problemom, jakiejkolwiek pomocy potrzebowali, cokolwiek to było, starałam się to wypracować. 

Bezpośrednio i pośrednio, wszyscy jesteście pobłogosławieni. A więc, jak to jest z wami, którzy teraz jesteście yoginami? Jesteście świętymi. Mam zdjęcie, musicie je zobaczyć, to bardzo ciekawe zdjęcie, które potwierdza, że wszyscy jesteście świętymi. Czy widzieliście to zdjęcie? Jeszcze nie? Lepiej je zobaczcie, przynieście je, chyba jest w Moim pudełku. Wszyscy jesteście świętymi poświadczonymi przez Boskość, a nie przez jakiegoś kardynała, czy papieża. 

Więc co ci wszyscy święci robią? Jeden święty, poświadczony przez papieża, poświadczony sztucznie, to coś takiego wielkiego, sami wiecie. A co z wami, którzy zostaliście poświadczeni przez Boga Wszechmogącego. Wciąż zajęci jesteście swoją pracą. Wciąż zajęci jesteście swoimi małymi, małymi sprawami. Wciąż zajęci jesteście swoimi małymi życiami i małymi rodzinami. A o świętym powiedziano w Sanskrycie: "Udara charitanam vasudhaiva kutumbakam". Dla osoby, która ma szlachetną naturę, to znaczy dla osoby, która jest świętą, cały świat jest rodziną. Czy nadal martwicie się tylko o własną rodzinę? W takim razie, nie jesteście jeszcze świadomi własnej świętości. A święty martwi się nie tylko o własną żonę, o własne dziecko, o własny dom - on martwi się o cały świat.

Jako Sahaja yogini jesteście potężnymi jednostkami. Jesteście bardzo potężnymi ludźmi. Mamy problemy na całym świecie, dobrze o tym wiecie. Nie jest konieczne, żebyście byli wielkimi intelektualistami, ani ludźmi, którzy są czymś w rodzaju polityków, czy czymś takim, ale musicie wypatrywać problemów, które nękają ten świat. Musicie, nie możecie żyć we własnym świecie, ponieważ jesteście teraz świętymi. "Teraz jestem w Niranand!"Tak nie może być. Nie możecie po prostu być w Niranand. Musicie wiedzieć, że powinniście żyć w tym świecie i musicie znać wszystkie problemy tego świata I powinniście myśleć o nich, nie tylko o swoich problemach "ależ Matko, jak ja będę w stanie zrobić to, zrobić tamto". Lecz musicie martwić się o cały świat, i myśleć o tym, co dzieje się na świecie, jakie są problemy świata. Jesteście za to odpowiedzialni. I nie tylko to. 

Powinniście także się modlić. W waszych modlitwach mówcie: "Matko, rozwiąż ten problem". Kolektywnie, indywidualnie musicie przenieść swoją uwagę z was samych, z waszego małego życia w kierunku szerszych tematów. Wtedy jesteście świętymi. I musicie myśleć, że to wasz obowiązek, aby prosić Boskość o pomoc w rozwiązywaniu wszystkich tych problemów. To jest wasza praca, do której zostaliście wybrani. Wasze prośby będą pracować, ponieważ jak wiecie, Ja nie mam pragnień. To wy musicie tego pragnąć. Czegokolwiek zapragniecie, to się wypracuje. Ochrona, miłość, współczucie Matki jest z wami. Ale musicie się troszczyć o ten świat i pokazać, że taką troskę macie, a nie żyć w bardzo ograniczonych sferach i w ograniczony sposób. 

Na przykład teraz Brytyjczycy myślą - Brytyjczycy są tutaj, to dobrze - "problemy Wielkiej Brytanii są naszymi problemami". Nie. Wasze problemy obejmują wszystkie te miejsca, w których jest Sahaja Yoga i o nie wszystkie musicie się martwić. Mamy teraz problemy powiedzmy w Australii. I jest tam ktoś, kto sprawia dużo kłopotów. Musicie przyjrzeć się temu, wyszubitować tę osobę i przywrócić porządek. Lider powinien mówić, kogo szubitować i to wypracowywać, czy to będzie w Australii, Ameryce, czy w Indiach. Jeśli widzicie, że gdzieś jest problem dotyczący Sahaja Yogi lub atak na Sahaja Yogę, wszyscy powinniście skierować na to swoją uwagę i wypracować to. 

Są jeszcze ogólne problemy. Widzimy, że Ameryka staje się idiotyczna, czy jakkolwiek by to nazwać, więc powinniście skierować uwagę na Amerykę. Powinniście rozciągnąć swoją uwagę na zewnątrz, a nie do środka, martwiąc się tylko o siebie, swoją rodzinę, swój dom, swoje dzieci. Jak tylko rozciągniecie swoją uwagę na zewnątrz, wasze problemy w domu, wszystkie najmniejsze rzeczy się rozwiążą. Musicie skierować uwagę na zewnątrz. Mamy w naszych czasach telewizję. Mówiliśmy wcześniej, żeby nie oglądać telewizji, bo nie było żadnego pożytku z oglądania jej przez Sahaja yoginów. Od oglądania telewizji tylko łapali blokady. Ale teraz dzieją się ważne rzeczy, o których sami możecie się przekonać. Możecie wybadać, jakie problemy ma świat i zobaczyć, gdzie skierować swoją uwagę. Powinniście stać się świadomi osobowości - nie jest to osobowość, która może całkowicie zaangażować się w jakiś bardzo mały obszar. 

Wasza osobowość powinna zaangażować się we wszystkie problemy Wszechświata, we wszystkie, jakie są. I będziecie zaskoczeni, że wszystko może się wypracować w bardzo kolektywny sposób. Na tym poziomie, na którym jesteście, możecie sami się przekonać - wszyscy Sahaja yogini mają wibracje na szczycie głowy. Czy wy wszyscy chcielibyście to zobaczyć? Tylko popatrzcie! Wy wszyscy siedzący w Ganapatipule. Rozciągnijcie swoje wibracje, rozciągnijcie swoją uwagę. I będziecie zaskoczeni, że wszystkie wasze błahe problemy się skończą. 

Teraz zobaczmy. Niech dzieci zobaczą to jako pierwsze. Tylko spójrzcie. Wszyscy macie wibracje na szczycie głowy. Pozwólcie im rosnąć, mówię wam, Ja tylko czekam kiedy urosną! A zatem nastawienie do samych siebie powinno być pełne świadomości naszej chwały, naszej własnej pozycji, powinniśmy wiedzieć, że jesteśmy świętymi, że osiągnęliśmy poziom, w którym jesteśmy na szczycie, i że staliśmy się światłem, i musimy dawać światło innym. Zajrzyjcie do Biblii, Chrystus powiedział coś bardzo ważnego, żeby nie chować światła pod stół. O to chodzi.

Musicie umieścić światło na piedestale. I właśnie o to chodzi, że musicie umieścić wasze światło na cytadeli, w najwyższym punkcie, aby dać je innym. To działa w obie strony, jeśli tylko zaczniecie rozumieć, czym jesteście, czego macie być świadomi, jaka jest wasza sytuacja, jakie macie moce, co osiągnęliście w Sahaja Yodze, jaki macie dług wobec Sahaja Yogi i co musicie dać Sahaja Yodze, jak Sahaja Yoga uczyniła was tak zdolnymi, dobrymi, miłymi. Czy jesteście wystarczająco prawi? Czy zachowujecie się właściwie? Czy robicie wszystkie te prawe rzeczy, które są niezbędne? Ponieważ tylko wy możecie to zrobić. Jesteście ludźmi z bardzo, bardzo szczególnymi energiami i szczególnymi połączeniami z życiem duchowym. I jeśli zaczniecie zachowywać się jak wszyscy inni, przyziemni, bezsensowni ludzie, ograniczając się do rodziny, waszych dzieci, bezsensownych przeszłych żyć - będziecie zgubieni, straceni dla siebie i dla innych. 

Problemy mają o wiele większe znaczenie niż to, co o nich wiecie. Powinniście osiągnąć takie zrozumienie, że Matka uczyniła nas yoginami. Jesteśmy świętymi i musimy pokazać światu właściwą ścieżkę. Powiedziała nam, że jesteśmy światłem i musimy pokazać ludziom, którędy iść, jak dalej iść. Zamiast tego, każdy wydaje się stanowić problem, wydaje się być w bardzo malutkim wirze, kręcąc się wciąż w kółko. Jak to możliwe?! Mówiłam wam wiele razy, spójrzcie na tych fałszywych guru. Oni nie mają wibracji. Oni nic nie wiedzą o Kundalini, nic o Sahaja Yodze. A jak wiele robią! 

A my co robimy? Wciąż zmagamy się ze sobą i z naszymi problemami, z naszymi pomysłami, z naszym brakiem rozumu i tchórzostwem. Teraz to wy macie zrozumieć. To wy macie zdecydować o sobie. To jest wasze własne pragnienie, wasza własna wielkość, wasza własna wielkoduszność, którą musicie zaoferować, abyście mogli sami zobaczyć, do czego jesteście zdolni, co możecie zrobić. Łatwo jest ludziom mówić: "Matko, to zbyt wiele, nie mogę nic z tym zrobić" albo: "Matko, jestem zajęty swoją rodziną", "Jestem zajęty swoimi dziećmi". 

Czy po to przyszliście do Sahaja Yogi? Czy po to dałam wam Realizację? Czy po to otrzymaliście wszystkie te błogosławieństwa? Więc bardzo ważne jest, żebyście się wzmocnili. Możecie wyraźnie to zobaczyć, dlatego nie mogliśmy mieć programów publicznych, ponieważ potrzebujemy wzmocnienia w Wielkiej Brytanii. To dlatego, że mieszkam w Anglii przez tyle lat, ludzie tutaj traktują Mnie jak coś oczywistego, bo jestem tutaj, przebywam tutaj. Myślą: "Powinniśmy pojechać na lotnisko i wystarczy!" "Odbyliśmy całą tę pielgrzymkę i wszystko to, byliśmy na lotnisku, widzieliśmy Matkę, załatwione". Jaki jest pożytek z oglądania Mnie? Co Ja wam dałam? Czy wasze światło się rozprzestrzenia? Ilu ludzi otrzymało od was Realizację? Po prostu dowiedzcie się, ilu ludzi nauczyło się od was Sahaja Yogi, z waszego życia lub z waszej mądrości albo z waszego zachowania? To jest sposób, to jest kryterium. 

Nie chodzi o to, że "w porządku, wysłałem Matce Jej pieniądze na Jej podróż". To nie wystarczy. Spójrzcie na jakąkolwiek kobietę z Indii w Moim wieku, będzie chodzić o lasce, nie da rady wspiąć się nawet na jeden schodek. Kobiety w Indiach nie mogą tego zrobić z powodu gorąca, od którego cierpią. Ale Ja podróżuję, wy wiecie ile podróżuję, jak dużo robię. A co z Moją rodziną? Pozbawiam ich Mojego towarzystwa. Pozbawiam męża Mojego towarzystwa. Wszyscy są beze Mnie. Ja podróżuję, podróżuję codziennie, wiecie o tym dobrze. I tak ciężko pracuję. Czasami chodzę spać o drugiej nad ranem, czasami o trzeciej. Kiedyś był ze Mną Harsh i widziałam, że był wyczerpany! 

Ciągle wam mówiłam, że uprawiacie tylko bieg sztafetowy. Jestem w Australii, w porządku, Australijczycy działają. Następnie jestem w Austrii, wtedy pracują Austriacy, a potem spędzają miło czas! Jestem w UK, dobrze, trochę w Anglii, trochę zrobionej pracy. Potem wszyscy miło sobie siedzą i cieszą się. A co ze Mną? Ja mam maraton! Musicie to czuć w ten sam sposób, bo w końcu, co Ja na tym zyskuję? Jakie mam z tego zyski? Coś zyskuję. Przywróciłam Moje dzieci do normalności, przyprowadziłam je do Królestwa Bożego. Wy musicie zrobić to samo, przyprowadzać ich do Królestwa Bożego. Ale jeśli wy sami jesteście wplątani we własne maye, to każdego dnia będziecie iść w dół i w dół. Mogę krzyczeć, cokolwiek powiem, nie trafi to do waszych głów, nigdy tego nie pojmiecie. Będziecie zdani na własne siły, gdziekolwiek będziecie, ponieważ nie chcecie zrozumieć.

Powiedziałabym przy tym, że macie jedną zaletę, szczególnie w Anglii. Jesteście wszyscy bardzo inteligentni. Posiadacie inteligencję, niewątpliwie nie jesteście idiotami jak Amerykanie. Jesteście inteligentni. Dawno temu ta inteligencja stała się przebiegłością. I teraz jesteście zmęczeni własną przebiegłością. Indusi nauczyli się przebiegłości od was. Stali się naprawdę bardzo przebiegli. Ale to wy jesteście zmęczeni własną przebiegłością, więc teraz macie już dość, jesteście znużeni, wyczerpani i letargiczni. Ale dzięki waszej inteligencji możecie zrozumieć, że praca, którą wykonuje Matka jest tak istotna. Zapiszecie się w historii! Każde słowo, jakie wypowiadacie, wszystko co mówicie, każde wasze zachowanie, wszystko będzie zapisane w historii. Nie to, ile dzieci spłodziliście, albo jaką mieliście żonę, ale to, co zrobiliście dla Sahaja Yogi. Zapamiętajcie to. Historia zapisze wszystko, cokolwiek zrobiliście, cokolwiek osiągnęliście w Sahaja Yodze. 
To nie jest na pokaz, to nie jest żadna demonstracja, to nie jest przechwalanie się, nic z tych rzeczy. Zapisane będzie całkowicie to, co tak naprawdę w rzeczywistości osiągnęliście. Bóg przynajmniej wie, co to jest hipokryzja. I Bóg zna się na tym, co jest napuszone. Bóg wie, gdzie jesteście i co zamierzacie. Nie możecie Go oszukać. Musicie zrozumieć jedno, kiedy oszukujecie Boga, oszukujecie samych siebie, swojego Ducha, swoją Realizację, swój własny wzrost! Więc musimy być ostrożni. 

Jako matka powiedziałabym wam, żebyście próbowali przeprowadzać bardzo dokładną introspekcję. Co zrobiliśmy dla Sahaja Yogi? Co zrobiliśmy dla innych ludzi, którzy dryfują? Jakie było nasze zachowanie w stosunku do innych Sahaja yoginów? Jak wiele pokoju, miłości i współczucia daliśmy innym? Jak wiele zrozumienia i tolerancji okazaliśmy innym? Jeśli ktoś tutaj dostaje trochę więcej pieniędzy, to staje się taki nadęty, taki agresywny. Staje się taki nieuprzejmy. Nie mogę w to uwierzyć! Jak pieniądze mogą was kusić w kierunku takich występków? 

Nie jesteście zwykłymi ludźmi, jesteście świętymi, których stopy zostały obmyte przez rzekę Ganges. Spróbujcie zrozumieć swoją chwałę. Spróbujcie zrozumieć własne moce, własną pozycję, jako świętych ludzi, Sahaja yoginów, którzy są ponad wszystkimi świętymi, bo wy wiecie, jak dawać Realizację. Wiecie wszystko o Kundalini. Wiecie wszystko o Realizacji. Jak wielu ludzi o tym wiedziało? W przeciwnym razie zacznę się zastanawiać, czy dałam całą tę wiedzę grupie głupców, którzy nie umieją tego docenić. Jak mówił Chrystus: "Nie rzucajcie pereł przed wieprze". Nie sądzę, żebym popełniłam taki błąd. Nie wierzę, że popełniłam taki błąd, że rzuciłam perły przed wieprze. Nie zrobiłam tego.

Ale to wy musicie zdecydować, gdzie stoicie, w jakiej kategorii. To takie oczywiste, że żyjemy w bardzo niestabilnych czasach. To bardzo ważne. Musimy to zwalczyć. To dużo więcej, niż jakiekolwiek wojny, które stoczyliście. To dużo więcej, niż jakiekolwiek zmagania, przez jakie przeszli ludzie. Stworzono taki okropny świat, a my mamy go przetransformować. To jest ogromne zadanie. Dlatego musicie pracować w bardzo szczery i naturalny sposób. 

Jestem pewna, że przyjdzie kiedyś taki dzień w historii tego świata, że imiona Sahaja yoginów będą wypisane złotymi literami. Jestem pewna, że to się wypracuje. Jestem pewna, że to się musi wypracować i że wy wszyscy musicie to osiągnąć, kolektywnie, jednym umysłem, jednym sercem. Co powinienem poświęcić? Co powinienem zrobić? Jak powinienem pomóc? Jaki jest mój wkład? Chciałabym zobaczyć te dni za Mojego życia. 

Więc dziś powinniśmy przeprowadzać introspekcję. Zatem wszyscy powinniśmy wejść w medytację. 

Proszę zamknijcie oczy. Wszyscy zamknijcie oczy. Teraz będziemy medytować, w taki sposób, w jaki robiliśmy to na programach publicznych. 

Najpierw połóżcie rękę na sercu. Będziemy pracować na lewej stronie. Skierujcie lewą rękę w Moją stronę. Najpierw połóżcie rękę na sercu. W sercu rezyduje Shiva, czyli Duch Podziękujcie więc swojemu Duchowi za wniesienie światła do waszej uwagi, ponieważ jesteście święci i to światło, które weszło do waszego serca ma rozświetlić cały świat. Proszę, módlcie się teraz w swoim sercu: "Niech to światło Boskiej Miłości ogarnie cały świat". Z całą szczerością i zrozumieniem, że jesteście połączeni z Boskością i z pełną wiarą w siebie, że cokolwiek zapragniecie, spełni się. 

Teraz połóżcie prawą rękę w górnej części brzucha po lewej stronie, w górnej części, po lewej stronie waszego żołądka. Tutaj znajduje się centrum waszej Dharmy. Módlcie się w następujący sposób: "Niech Vishwa Nirmala Dharma rozprzestrzeni się na cały świat, niech ludzie zobaczą światło poprzez nasze dharmiczne życie, poprzez naszą prawość. Niech ludzie to zobaczą i zaakceptują Vishwa Nirmala Dharmę, poprzez którą otrzymają oświecenie i pomyślniejsze życie, na wyższym poziomie oraz pragnienie rozwoju". 

Teraz połóżcie prawą rękę w dolnej części brzucha, po lewej stronie. Naciśnijcie to miejsce. Jest to centrum czystej wiedzy. Teraz musicie jako Sahaja yogini powiedzieć: "Nasza Matka dała nam pełne wyobrażenie o tym, jak działa Boskość. Ona dała nam wszystkie mantry i tyle czystej wiedzy, ile jesteśmy w stanie znieść i zrozumieć. Spraw, abym dobrze się na tym znał, każdy z nas". Zauważyłam, że jeśli mężczyzna jest liderem, to jego żona nie wie nic o Sahaja Yodze. A jeśli żona wie, to mąż nie wie nic. "Abym był profesjonalistą i ekspertem w tej dziedzinie. Tak, abym mógł dawać ludziom Realizację, wytłumaczyć im, czym jest Boskie prawo, czym jest Kundalini i co to są czakry. Niech moja uwaga będzie bardziej skierowana na Sahaja Yogę niż na wszystkie te przyziemne sprawy". 

Teraz połóżcie prawą rękę w górnej części brzucha. Zamknijcie oczy. Teraz tutaj, po lewej stronie, uciśnijcie. Tu mówicie: "Matka dała mi Ducha, a Duch jest moim własnym mistrzem. Jestem swoim własnym mistrzem. Niechaj z tego nie zrezygnuję. Niechaj będzie w moim charakterze godność. Niechaj będzie w moim zachowaniu hojność. Abym miał współczucie i miłość dla innych Sahaja yoginów. Abym się nie popisywał, ale miał głęboką wiedzę o Boskiej Miłości i jej działaniu. A kiedy ludzie do mnie przyjdą, abym był w stanie opowiedzieć im o Sahaja Yodze i umiał przekazać im tę wielką wiedzę z pokorą i miłością". 

Teraz podnieście prawą rękę na serce. Tutaj podziękujcie Bogu za to, że poczuliście ocean radości, że poczuliście ocean przebaczenia i zdolność przebaczania, tak ogromną jaką ma wasza Matka. "Niech moje serce stanie się wielkie i obejmie cały Wszechświat. A w mojej miłości niech rozbrzmiewa imię Boga. Serce, w każdym momencie, powinno wyrażać piękno Boskiej Miłości". 

Połóżcie teraz prawą rękę na Vishuddhi, na lewym Vishuddhi, pomiędzy szyją a ramieniem. "Nie będę pogrążać się w fałszu poczucia winy, gdyż wiem, że jest ono fałszem. Nie będę uciekać od swoich wad, ale stawię im czoła i usunę je. Nie będę szukać wad u innych ludzi, ale dzięki wiedzy Sahaja Yogi, postaram się usunąć ich wady". Mamy tyle sposobów, dzięki którym sekretnie możemy usunąć wady u innych. "Niech moje poczucie kolektywności wzrośnie tak, że cała rasa Sahaja stanie się moją własną rodziną, moimi własnymi dziećmi, moim domem, moim wszystkim. Niech poczucie bycia częścią całości zostanie całkowicie we mnie wbudowane, ponieważ my wszyscy mamy jedną Matkę. Niech moja troska obejmie cały świat, abym poznał jego problemy, oraz w jaki sposób, poprzez moje szczere pragnienie i moc, mogę je rozwiązać. Pozwól mi poczuć problemy tego świata w moim sercu i pozwól mi usunąć je wszystkie od podstaw, u podłoża, gdzie powstają. Pozwól mi poznać przyczynę wszystkich tych problemów, i spróbować usunąć je poprzez siły Sahaja Yogi, poprzez moje święte siły". 

Teraz połóżcie prawą rękę na czole. Najpierw musicie powiedzieć: "Przebaczam tym, którzy nie przyszli do Sahaja Yogi, tym, którzy są na jej peryferiach, którzy przychodzą i odchodzą, którzy pojawiają się i znikają. Ale przede wszystkim przebaczam wszystkim Sahaja yoginom, bo oni wszyscy są lepsi ode mnie. Ja jestem tym, który stara się znaleźć w nich winę, ale to ja jestem na najniższym poziomie. I przebaczam im, bo wiem, że muszę jeszcze znacznie się rozwinąć. Ciągle jeszcze jestem dużo niżej. Muszę się doskonalić". Musimy rozwinąć w sobie pokorę, dlatego powiedzcie: "Wprowadź do mojego serca pokorę szczerą, a nie zakłamaną, wypracuj to uczucie przebaczania, tak abym pokłonił się rzeczywistości, Bogu i Sahaja Yodze". 

Teraz połóżcie rękę na potylicy. odchylcie głowę do tyłu i powiedzcie tutaj: "Matko, cokolwiek złego dotychczas uczyniłem Tobie, cokolwiek złego przyszło mi do głowy, jakąkolwiek mierność okazałem Tobie, w jakikolwiek sposób sprawiłem Ci przykrość i sprzeciwiłem się Tobie, proszę, przebacz mi". Powinniście prosić o wybaczenie. W swojej inteligencji powinniście wiedzieć, kim Jestem. Nie muszę wam tego ciągle powtarzać. 

Teraz w Sahasrarze musicie Mi podziękować. Połóżcie prawą rękę na Sahasrarze, poruszajcie nią siedem razy i podziękujcie Mi siedem razy. 
"Matko, bardzo Ci dziękuję za Realizację. 
Matko, bardzo dziękuję ci za to, że zrozumiałem moją wielkość. 
Matko, bardzo ci dziękuję za wszelkie boskie błogosławieństwa. 
Matko, bardzo ci dziękuję za wzniesienie mnie na wyższy poziom, o wiele wyższy niż ten, na którym byłem. 
Dziękuję Ci również bardzo za wspomaganie mnie, za pomoc w doskonaleniu i korygowaniu samego siebie. 
I na koniec dziękuję ci Matko za to, że przyszłaś na tę Ziemię, że narodziłaś się, i że tak ciężko dla nas wszystkich pracujesz". 

Naciskajcie mocno I mocno poruszajcie. Teraz opuśćcie rękę. Wszystkie głowy są bardzo gorące. Więc teraz dajmy sobie porządny bandhan. W bandhanie Matki przenieśmy naszą lewą stronę na prawą. Raz – porządnie, rozumiejąc kim jesteście! Czym są wasze aury, teraz drugi raz, teraz trzeci teraz czwarty teraz piąty teraz szósty a teraz siódmy. Teraz podnieście swoją Kundalini, podnieście swoją Kundalini, powoli, bardzo powoli podnieście ją pierwszy raz, musicie robić to bardzo powoli. 

Teraz odchylcie głowę i zróbcie węzeł, jeden węzeł. Teraz drugi raz, zróbmy to bardzo powoli, z pełną świadomością, kim jesteście. Jesteście Świętymi. Zróbcie to uważnie, uważnie, zróbcie to uważnie, bez pośpiechu. Podnieście to, odchylcie głowę i zróbcie dwa węzły, jeden i dwa. 

Teraz zróbmy to jeszcze raz. Za trzecim razem zawiążcie trzy węzły. Zróbcie to pomału, bardzo pomału, teraz zróbcie to uważnie. Teraz odchylcie głowę, zróbcie to trzeci raz. Trzy razy. Teraz sprawdźcie swoje wibracje. Sprawdźcie swoje wibracje. W ten sposób. Wszystkie dzieci niech sprawdzą swoje wibracje w ten sposób. Połóżcie ręce. w porządku, dobrze. Pięknie! Dostaję od was wibracje! 

Niech was Bóg błogosławi. 

