Sahastrara Puja. Cabella Ligure, Italia. 5 de mayo de 2002.

Hoy es un gran día, en el que celebramos el Puja del Sahastrara. El hecho de la apertura de vuestro Sahastrara es algo muy especial. Ha habido muy poca gente en el mundo que tuviera el Sahastrara abierto: algunos sufis, algunos santos y algunas personas en China. Pero fueron muy pocos. Por eso la gente nunca entendió lo que decían o escribían. De hecho los torturaron, los crucificaron, les hicieron cosas horribles, porque no se soportaba a alguien que tuviera la Realización.

Por eso hoy es un gran día, porque se celebra que el Sahastrara fue abierto a nivel colectivo. Todos vosotros lo tenéis y en todo el mundo también hay muchas personas con el Sahastrara abierto. Por supuesto, todavía tiene que haber más, para que puedan entender la importancia de este gran acontecimiento colectivo que es la apertura del Sahastrara. Algunos han crecido mucho después de obtener la Realización. Han entendido Sahaja Yoga muy bien, han desarrollado mucha profundidad y perciben realmente esa gran consciencia de ser Uno con el Divino.

La mayor bendición para un ser humano es ser Uno con el Divino. Antes de eso, los seres humanos viven en un nivel más bajo. Tienen todos los inconvenientes de ese nivel: envidia, odio, y sufren todos los problemas que existen hoy en día, como las guerras, la persecución, la destrucción y la falta de amor hacia los demás. Todos estos problemas existen porque su Sahastrara no está abierto.

Por tanto, nuestra principal preocupación es abrir el Sahastrara de todo el mundo, lo cual es muy sencillo; todos lo podéis hacer. Funcionará mejor si lo hacéis colectivamente. Si sois colectivos, lo conseguiréis fácilmente. De esa forma, muchas personas han venido a Sahaja Yoga y, con su Sahastrara completamente abierto, han sentido su profundidad. Primero tenéis que sentir vuestra profundidad. Si no la sentís, y si no sois uno con vuestra personalidad, que es muy profunda, entonces no podéis gozar de la Realización del Ser.

En primer lugar debéis comprenderos a vosotros mismos. Si no os conocéis, ¿cómo vais a comprender a los demás? No podéis. Por tanto, lo primero es abrir el Sahastrara completamente. "Completamente" quiere decir que exista una unión completa con el Divino. No es difícil. Solo tenéis que meditar un poco y funcionará. Me alegra ver y encontrarme en Sahaja Yoga con mucha gente que ya lo ha conseguido, personas que han alcanzado una gran colectividad y la consciencia de un alma realizada.

¿Cómo es la consciencia un alma realizada? Esto es lo que debemos entender hoy. Como ya he dicho, hoy es un día muy importante. La consciencia debe ser tal que sepáis lo que está pasando en el mundo y cómo podéis ayudar. ¿Cómo podéis contribuir a que la gente alcance esta consciencia? Hasta que no tengáis un conocimiento pleno de vosotros mismos, una fuerza total y una confianza absoluta en vosotros mismos, no podéis ayudarles.

El día del Sahastrara se celebra para reforzar vuestro vínculo con el Divino, para que vuestra consciencia se vuelva absolutamente iluminada y para que veáis el quid de la cuestión en todo.

He visto que en muchos países, la gente ha aceptado Sahaja Yoga muy rápidamente. Sorprendentemente en África, que no es un continente muy desarrollado, ha funcionado bien, porque hay miles de personas que tienen la Realización. Creo que los países desarrollados ya han traspasado ese punto en el que se puede conseguir el ascenso. Parece que ese es el problema: que tienen que retroceder desde su estado de desarrollo hasta el estado en el que se puede ascender. Por eso, los que a pesar de todo tienen la Realización, no ascienden tan rápido como los que todavía no son tan avanzados o modernizados. Aun así, ha funcionado en mucha gente y muchos están ascendiendo muy bien.

Pero diría que, cuando meditéis, y también cuando vuestra atención esté en el exterior, debéis desarrollar el estado de testigo. Deberíais averiguar cuál es el problema, en qué estáis fallando, en qué fallan los demás y cómo podéis ayudar para solucionarlo. Tan solo con las vibraciones se pueden corregir muchas cosas en vuestro país, en vuestra familia, en todas partes.

Como veis, Sahaja Yoga está creciendo y hay una gran necesidad y un gran deseo de obtener la Realización del Ser. Pero para eso, vuestros métodos deben estar llenos de amor y de comprensión. La gente viene de la oscuridad, de la ignorancia, para entrar en el elemento, en la naturaleza del Divino, lo cual es deslumbrante para ellos. Por tanto, si poco a poco desarrolláis esa amabilidad y amor entusiastas por ellos, estoy segura de que podréis hacer mucho más por su crecimiento. No sirve de nada enfadarse con ellos, porque son muy ignorantes, no saben lo que están haciendo. Como Cristo dijo: "No saben lo que hacen".

Por tanto, lo que hay que hacer es lograr que comprendan que sus acciones y su entendimiento todavía son pobres, no abarcan lo que podrían abarcar si fueran almas realizadas. Veo que incluso después de la Realización, la gente tiene un problema, y es que continúan apegados a su vida anterior, la cual ya ha terminado, ya ha muerto; pero todavía siguen con ella. Y su consciencia, su grado de iluminación, no les muestra cuáles son sus problemas.

Por ejemplo, veamos el caso del ego. El ego está muy desarrollado. En los países occidentales, que son muy desarrollados, el ego también se ha desarrollado. Hay que averiguar dónde está el problema. Este ego viene de que sentís que habéis sido importantes, o que sois tal y tal cosa, o quizá de que vuestros padres eran personas importantes, o de que tenéis muchas posesiones o muy buena posición, etc. Puede venir de cualquier cosa. Esta percepción va en contra de vuestra verdadera consciencia, pues no es real. Ninguna de estas cosas externas modifica lo que sois. Es la consciencia en vuestro interior lo que os moldea. Esta consciencia tiene que crecer. ¿Cómo? Entendiendo de dónde nos viene el ego, cómo empieza.

Ayer sentí que muchos estabais muy del lado derecho. Este lado derecho no sirve para nada; os acarreará problemas y enfermedades. No sirve de nada tener sahaja yoguis del lado derecho.

Lo principal es comprender el poder del amor. El poder del amor es lo más elevado y lo más importante que existe, y si de alguna manera lográis abandonar la ira, la avaricia y el ego, si podéis dejar estas cosas, podréis estar en el Sahastrara. Ved a qué juega el ego. Frena vuestro ascenso. En el ego uno se pierde, porque con ego solo se puede ir a los lados, o demasiado al lado izquierdo o demasiado al derecho, incluso a sus extremos. Por eso, en primer lugar tenemos que corregir nuestro ego. Para eso, ¿qué debemos hacer? Para combatir el ego, tenemos que observarnos y reírnos de nosotros mismos. ¿Cómo es nuestro ego? ¿De dónde nos viene? Somos seres humanos y ahora nos hemos convertido en seres divinos. Y con el Divino en nuestro interior, con esa luz en nuestro interior, tenemos que comprender que somos parte integrante de ese Divino, que somos solo una gota en el océano de amor. Si lográis reducir vuestro ego, si conseguís darle el sentido que verdaderamente tiene en vuestro Ser, entonces funcionará mejor.

En Occidente, el ego es extremadamente fuerte. Piensan que todo lo malo que hacen está bien, porque el ego les respalda en todo. Por el contrario, en los países en vías de desarrollo, donde todavía no están muy desarrollados, el problema de la gente no es de ego, sino de superego. El superego se puede corregir, pero el ego es vuestro enemigo personal, lo habéis creado vosotros mismos. Tenéis que combatirlo y descubrir por vosotros mismos de dónde viene. Puede provenir de vuestro país, de vuestra familia..., de cualquier cosa. Por tanto, si queremos entrar en el Sahastrara, lo primero que tenemos que hacer es vigilar nuestro ego.

Cuando estaba esperando el acontecimiento colectivo de la apertura del Sahastrara, sentí que lo que entorpecía mi trabajo era el ego de la gente. Tuve que luchar contra él. Solían avasallarme porque soy una mujer de costumbres muy sencillas, sin orgullo ni nada, y me decían todo tipo de cosas. Pero yo comprendía que tenían un problema de ego. Cuando este ego evoluciona e intenta dominar, entonces en ese país puede haber personas como Hitler, y puede haber ese tipo de personas horribles en todo el mundo.

Lo primero es entender que nunca debemos someternos a personas que tienen ego. Por supuesto, no debéis poneros a pelear, sino tener fe en vosotros mismos y en que tenéis la Realización del Ser. Sois mucho más poderosos que ellos. Mis poderes solo funcionan en personas realizadas. Os sorprenderá comprobar que en ellas funcionan muchas cosas que no funcionarían en personas con ego.

El otro día oí que en África, la gente se vuelve invisible de repente. Hubo un golpe de estado, y el Presidente, que es sahaja yogui, se volvió invisible, nadie lo pudo encontrar. Esto sucede porque son personas completamente rendidas. Están tan entregadas que reciben los beneficios de mis poderes. También vosotros deberíais utilizar mis poderes de protección. Este poder de protección es extremadamente poderoso, especialmente en las personas que están profundamente establecidas en Sahaja Yoga y que están muy dedicadas. Por eso en primer lugar debéis tener absoluta fe en vosotros mismos y en que sois sahaja yoguis, pero no debéis tener ego. Ser sahaja yogui significa que no se puede tener ego.

El ego puede tener diferentes orígenes, ya lo sabéis. Pero hay que limpiarlo. Es como un río, que cuando fluye recibe todo tipo de suciedad e impurezas. Pero cuando llega al mar, entonces se convierte en el mar. De la misma forma, vosotros tenéis que convertiros en el mar. Para lograrlo, lo que tenéis que hacer es olvidar todas las pequeñeces e ideas equivocadas que vienen a vuestra cabeza. Pueden provenir de cualquier fuente. Ni siquiera las puedo nombrar porque la lista es muy larga. A veces la gente enloquece de tanto ego.

Lo importante es observar y ser testigo de vuestro ego, de cómo trabaja, cómo estropea vuestro carácter, vuestras relaciones, cómo os vuelve estúpidos. La primera cosa que hace el ego es volveros tontos. Comenzáis a comportaros de tal forma que los demás piensan que sois la persona más absurda que ha existido nunca. Y no sirve de nada porque, ¿qué pasará si os consideran tontos?

Por el contrario, si tenéis sabiduría, si tenéis esa paz, ese temperamento especial que goza de todo en la vida, y también si sois colectivos, entonces funcionará. Se quedarán impresionados. Porque en esa luz podrán ver su propia estupidez, su propia falsedad, todo, y se darán cuenta de que lo que piensan no es verdad. Pensarán: "Este señor es mucho más profundo que yo. Tiene algo que yo no tengo". Esto es lo principal para todos nosotros.

En Sahaja Yoga hay líderes. Eso no significa que sean líderes literalmente hablando, sino que tienen una mayor profundidad. Si no la tienen, dejan de serlo. Pero si tienen esa profundidad, entonces son líderes en el sentido de que los demás los ven y realmente disfrutan de que lo sean. mdicen: "Después de todo, Madre es Madre, ¿cómo podemos parecernos a Ella?" Pero de los líderes aprenden lecciones, entienden lo que no está bien, lo que no es adecuado.

Primero debéis ser modelos de Sahaja Yoga. Y en eso consiste lo que os he estado diciendo siempre: "Eliminad vuestro ego". El ego es lo peor que hay, porque en primer lugar provoca la ira. Os creéis importantes, y creéis que podéis hacer esto y aquello porque sois sahaja yoguis. No es así. Por el contrario, sed muy humildes, extremadamente humildes, y haréis las cosas bien. No volveréis a ser arrogantes nunca más ni estaréis llenos de ira. La ira desaparece de vosotros totalmente, por completo. Ello os da equilibrio y sabiduría, gracias a la cual comprendéis cuál es vuestro trabajo, por qué estáis en esta tierra, por qué esta energía ha llegado a vosotros, por qué sois una personalidad divina. Es una responsabilidad muy, muy grande. No necesitáis cuidaros, no, el Divino cuidará de vosotros siempre. Os protegerá, os cuidará, hará lo que sea necesario por vosotros. Pero si tenéis ego, os cerráis la puerta de la realidad y de la verdad, y os volvéis muy malhumorados y muy arrogantes. Esto tiene que terminar.

Los sahaja yoguis son santos, y no solo eso, son más que santos, porque pueden expresarse mejor que ellos. Tienen poderes en su interior que saben utilizar, y pueden demostrar a los demás que son muy poderosos y que manejan las situaciones mucho mejor de lo que creen.

Por ejemplo, supongamos que hay un problema por el que el mundo entero está preocupado. Con tan solo ser capaces de ser testigos, el problema desaparecerá. ¡Desaparecerá del mundo entero! No puede durar. Como veis, hoy en día el mundo está lleno de conflictos, de gente absurda, de gente combativa y dominante que se impone. En estos momentos, si lo podéis ver todo desde el estado de testigo, desaparecerá. Porque sois muy, muy poderosos. Pero sabed que primero tenéis que estar preparados para usar ese poder. Si lo estáis, podéis hacerlo. Pero con ego, no se puede. El ego es el mayor obstáculo para vuestro ascenso. Ved que el ego está situado exactamente en el lugar que debéis atravesar para llegar al Sahastrara. Si no fuera por él, atravesar el Sahastrara sería muy fácil. Pero si hay ego, os perdéis en él.

Para luchar contra esto, tenéis que entender que debéis observaros. ¿Es egoísta mi ego? ¿Qué piensa de sí mismo? El ego es muy limitado. Os hace limitados y no veis el propósito de vuestra vida. ¿Por qué os habéis convertido en almas realizadas? No lo entendéis, solo os preocupan vuestros propios asuntos, vuestra familia, vuestros hijos, en cosas así, de un nivel muy bajo. Pero si vuestra personalidad es sin ego, entonces sois muy eficientes, todo vuestro poder funciona.

He observado que el poder del Sahastrara es muy grande. En algunas personas ha hecho maravillas. Lo han hecho funcionar de una manera impresionante. Pero a causa del ego, todavía hay mucha gente que no está a un nivel en el que podamos decir que son sahaja yoguis.

En estos momentos yo estoy aquí para explicaros todo. Pero en los tiempos en que vivieron los santos, no había nadie que les guiara ni les explicara nada. Por el contrario, su entorno los destruyó en gran medida, y la gente nunca comprendió por qué no tenían ego ni por qué eran tan humildes. Así que abusaron de ellos. Pero ahora tenéis poderes y debéis saber cómo utilizarlos. Pero el hecho de tener poderes, en ningún caso debería produciros ego. Por el contrario, tenéis que ser humildes. Tenéis el poder de ser humildes. Debéis serlo y comprender que estas personas todavía no son almas realizadas, que están a un nivel inferior, todavía dominadas por su ego, y que aún tienen que crecer. Cuando comprendáis eso, no solo sentiréis compasión por ellos, sino que también los entenderéis y obtendréis la ayuda del Divino para resolver vuestros problemas.

Me parece que normalmente la mayoría de vosotros tenéis problemas de un nivel muy bajo. Y me sorprende que os preocupen esas cosas. Sois muy poderosos. Debéis saber qué poderes hay en el Sahastrara. Hay mil poderes en vuestro interior que están siendo iluminados. Si podéis entender esto, entonces también entenderéis que de qué sirve tener ego cuando tenéis tantos poderes en vuestro interior que no habéis utilizado. Debéis utilizarlos, pero no podéis a causa del ego. Pero si tenéis amor, sí que podéis. Con amor, podéis hacer y conseguir muchas cosas.

Por eso hoy os pediría a todos que prometáis que no volveréis a dar ninguna oportunidad a vuestro ego; que abandonaréis el ego completamente. Porque no tiene ningún sentido, es solo una obstrucción entre nosotros. Cuando el Sahastrara quiere trabajar, no puede a causa de la obstrucción del ego. Así que lo mejor es no tener ego por nada. Quizá seáis buenos cantantes o seáis buenos en cualquier otra cosa, o gente importante; estas cosas no significan nada. Lo que se necesita hoy es gente sin ego, en la que fluyan sus poderes permanentemente.

Con la apertura del Sahastrara, si el chakra está completamente abierto, estos poderes deberían fluir. Los poderes del amor deberían fluir. Es asombroso cómo la gente se enamora de mí en cualquier parte a la que voy. No sé por qué, no les hago nada, sencillamente sienten mi amor. Debería ser así, que la gente sintiera vuestro amor y supiera que sois una persona amorosa.

Habéis sido transformados en personas muy, muy especiales para la emancipación del mundo entero. Ese es vuestro trabajo, y no acumular dinero o dedicarse a cosas absurdas. Estáis aquí para un trabajo muy sensato, que es elevar la Kundalini de la gente y hacerles conscientes de su grandeza. Los seres humanos no han sido creados solo para la lucha y la guerra, tampoco para hacer política ni fraudes de ningún tipo. No están aquí para llevar una vida indecente y mezquina. Estamos aquí para hacer el gran trabajo de Dios, nuestro Creador.

Esto es posible si sois conscientes de que vuestro Sahastrara está abierto y de que en Él reside la pureza, y no todas esas pequeñeces que os preocupan. Algunos tratan de aprovecharse de Sahaja Yoga, pensando: "Ahora nos irá mejor, los demás nos ayudarán, etc." Nada de eso, cada uno puede ayudarse a sí mismo. No necesitáis ninguna ayuda. Al contrario, sois vosotros los que tenéis que ayudar a los demás. No hay que esperar ninguna ayuda de ningún sitio. Miradme a mí, una sencilla ama de casa, y cómo ha funcionado en todo el mundo. ¿Cómo? Gracias al Poder del Amor. El único problema es que yo sé cómo usar mi poder de amor, y vosotros no. Ese es el único problema.

Si queréis utilizar vuestro poder de amor, debéis desarrollarlo meditando. Con él podéis conquistar y comprender a los demás. Su problema es que no son sahaja yoguis, no están recibiendo las bendiciones ni tienen la conexión con el Divino. Imaginaos, vosotros estáis conectados con el Divino. Y el Divino es tan grandioso que ha creado el Universo entero, os ha creado a vosotros y ha hecho todas las maravillas. ¿Qué sois vosotros? Sois parte integrante de ese Poder divino. Entonces, ¿por qué no usar siempre el Poder divino que hay en nuestro interior, con amor y con comprensión, y así desarrollar la sabiduría?

Debéis deciros a vosotros mismos: "Somos almas realizadas". Un alma realizada es una personalidad tremendamente especial. Ha habido muy pocas personas realizadas en el mundo. Pero ahora veo que somos muchos. Sin embargo, todavía falta algo, hay problemas a causa del ego. Uno no debería tener ego por nada, todo en la vida es perecedero. Lo que no muere nunca es el amor divino. La personalidad divina no perece. Constantemente veis que se sigue recordando a los santos y personas así, aunque hayan muerto. Se recuerda toda su poesía. Aunque no pudieron hacer mucho a nivel del Sahastrara y no pudieron dar la Realización a la gente, aun así se les respeta por su carácter, y se sabe que hicieron cosas maravillosas y milagrosas.

De la misma forma, podéis ver vuestros propios milagros, podéis ver de lo que sois capaces, gracias a vuestra conexión con el Divino. Es una realidad que debéis conocer. En cualquier situación de peligro, siempre que haya un problema, diréis: "Te vas a salvar". Muchos se han salvado gracias a vosotros, sin lugar a dudas.

Pero eso no es suficiente. ¿Para qué habéis sido salvados? ¿Cuál es el valor de vuestra vida? ¿Por qué vivís? ¿De qué se trata? ¿Por qué os ha salvado Dios? ¿Por qué os ha dado todo esto? Porque hay mucho que hacer por el mundo. Yo diría que sois los soldados de la verdad, de la bondad, y debéis hacer todo el trabajo con mucho coraje y con una gran comprensión de vuestro Ser.

Para ello debéis tener el conocimiento del Ser. Tenéis que conoceros a vosotros mismos. Debéis tener autoconocimiento, saber lo que sois. Si no lo tenéis, ¿de qué ha servido la apertura del Sahastrara? El conocimiento del Ser no os implica orgullo ni nada parecido, sino el deber de lograr muchas cosas.

Sahaja Yoga no es solo para vosotros. Vosotros sois para el mundo entero, intentad comprenderlo. A veces pensamos que Sahaja Yoga es para que mejoremos, para tener buena salud, etc. No es así. Sahaja Yoga es para que mejoren los demás. Tenéis poderes, pero no los utilizáis. Todavía estáis ocupados con cosas como: "Tengo este problema, me pasa esto....." ¿Por qué no podéis corregiros a vosotros mismos? Si no lo podéis hacer, ¿cómo vais a corregir a los demás? De eso se trata.

Se ve que en vuestro entendimiento está entrando cierta comprensión de que "sois alguien importante". No sois personas comunes, y esto es algo que debéis practicar y utilizar de tal manera que se vea que sois sahaja yoguis. No sois menos que ningún sufí, ni ningún alma realizada, ni ningún santo. Además tenéis poderes que ellos no tuvieron, o de los que no fueron conscientes. ¡De verdad que los tenéis! Intentad comprender cuáles son vuestros poderes. Pero cuando lo entendáis, no sintáis orgullo de ningún tipo, sencillamente es vuestro trabajo, tenéis que hacerlo. Estáis ahí y lo disfrutáis porque no hay ego, es un trabajo sin ego. Si podéis lograr esto, estará muy bien.

Debo decir que el ego ha disminuido mucho. La gente me comenta que ahora hay mucho menos ego. Pero todavía os preocupáis, os peleáis a veces y cosas así. Sin embargo, a pesar de todo, debo decir que la gente ha aplicado en sí misma el trabajo de todos estos años. Tenéis que observaros, descubrir qué tipo de ego tenéis, y ver por qué sois egoístas. Algunos tienen ego por su país, otros por otra cosa... Todo es un mito, no es real. Podríais haber nacido en cualquier sitio, pero tenéis ego por haber nacido en un determinado país. Esto es algo por lo que deberíais avergonzaros. Si además ese país no va tan bien, no es un país fuerte a nivel espiritual, entonces, ¿de qué os sentís orgullosos? Cuando mejore y profundice espiritualmente, entonces podréis sentiros orgullosos de él. Pero no veo que eso esté pasando, y por eso mismo tenéis que trabajar.

Estoy muy contenta de ver que Sahaja Yoga se ha extendido mucho por todas partes. Se está extendiendo muy rápidamente, incluso en países donde nunca lo hubiera esperado. Por tanto, es que hay gente en todas partes del mundo que desea obtenerlo. Desean su Realización y también quieren saber qué hay más allá de esta vida humana. Ya no quieren malgastar su vida como seres humanos corrientes, sino que desean ser lo que podríamos llamarles "súper seres humanos", es decir, sahaja yoguis.

Por tanto, debemos ver nuestro ego desde el estado de testigo, cómo trabaja y cómo intenta desviarnos del camino correcto. Hay que tener cuidado en este punto, porque se trata del último centro que hay que abrir. Cuando esté completamente abierto, seréis Uno con el Divino y todos vuestros problemas se resolverán. Como todos esos problemas son superficiales y no significan nada, desaparecerán inmediatamente, siempre que mantengáis este chakra completamente abierto.

Hoy es un día muy bonito y muy significativo, en el que estas tres estrellas han aparecido juntas, lo cual es una bendición especial. Si vuestros poderes aumentan, toda la gente malvada o la que intenta atrapar a la sociedad con sus tonterías políticas y todo eso, desparecerá. No tienen ningún poder, y por eso todos desaparecerán. Vuestro carácter sin ego será lo que primero ayudará a todo el mundo.

Que Dios os bendiga.