31 juli 1982
Talk to Sahaja Yogis
Cowley Manor, Cheltenham (England)
Toespraak tot Sahaja yogi’s - Volledige toewijding - Cowley Manor, UK - 31-07-1982

Translation not verified. Dear yogi, register as volunteer to do so.
Vertaling niet geverifieerd. Beste yogi, registreer als vrijwilliger om dit te doen.

Vandaag wil ik iets zeggen dat ik al veel eerder had moeten zeggen.

Het is noodzakelijk mij te erkennen. Deze voorwaarde staat vast. Ik kan het niet veranderen. Zoals Christus reeds zei: "Om het even wat tegen mij gedaan wordt, zal worden verdragen en vergeven, maar om het even wat tegen de Heilige Geest gedaan wordt niet."Dit is een zeer ernstige waarschuwing. Misschien beseffen de mensen niet wat dit betekent. Natuurlijk is niemand onder jullie tegen mij en niemand van jullie onderneemt iets tegen mij. Dat staat vast. Uiteindelijk zijn jullie mijn kinderen. Ik hou heel veel van jullie en jullie houden van mij. Dit is de enige waarschuwing die Christus jullie gegeven heeft. Maar we moeten bedenken dat wij niet zo snel vorderen als wij zouden moeten.

Als mensen gehypnotiseerd worden, vallen zij plat op de grond voor hun goeroe neer. Zij geven hem hun geld, zij geven alles op: thuis, huis, families, kinderen en laten zich op de grond vallen, als ze gehypnotiseerd zijn. Zonder vragen te stellen, zonder discussies aan te gaan of uit te zoeken hoe de goeroe leeft. Mensen zoeken heel vlug de duisternis op, een nog grotere duisternis en tot de volledige vernietiging.

Maar jullie zijn sahaja yogi's en jullie moeten jezelf vormen. Ik wilde voordien jullie ego's niet kwetsen, jullie nooit op deze toespreken. Misschien is het de eerste keer dat ik dit tot jullie zeg. Jullie moeten je volledig aan mij toewijden. Niet aan Sahaja Yoga, maar aan mij. Sahaja Yoga is slechts één van mijn aspecten. In volle overgave moet je je toewijden (aan mij). Volledige overgave, anders kan je nooit spiritueel groeien. Zonder vragen te stellen, zonder te argumenteren. Volledige toewijding is de enige weg waardoor je het kan bereiken. Maar mensen laten zich nog steeds vangen en geraken in problemen verwikkeld. Wat is de reden? Veel mensen vragen me: "Hoe komt het, Moeder, dat we terugzakken nadat we onze realisatie gekregen hebben?"

De enige reden is dat de toewijding niet volledig is. Zolang volledige overgave en volledige toewijding niet gevestigd zijn, besef je nog altijd niet dat ik goddelijk ben, in die mate dat je het zou moeten weten. Ik zeg dat niet iedereen onder jullie (zo reageert). En toch, als je in je hart en in je geest kijkt, zal je merken dat de volledige toewijding er niet is, zoals je die had, laat ons zeggen, voor Christus of voor Krishna, of voor één van hen die er vroeger waren. Krishna zei: "Sarva dharmanam parityajya mamekam sharanam vraja." "Vergeet alle godsdiensten van de wereld.” Hij had het niet over hindoeïsme, christendom, moslim, maar Hij bedoelde de voedingsbodem. "Vergeet al die voedingsbodems en wijd je volledig aan mij toe." Dat is zesduizend jaar geleden. En velen zouden nu ook nog zeggen: "We hebben onszelf volledig aan Shri Krishna toegewijd." Waar is Hij nu? Zelfs diegenen aan wie ik realisatie gegeven heb, spreken zo. Natuurlijk is er geen verschil tussen hem en mij, maar ik ben degene die jullie realisatie gegeven heb. Maar onze eerste bekommernis kunnen onze jobs, onze eigen problemen, onze familieproblemen, onze financiële problemen zijn. En toewijding komt op de laatste plaats. Ik ben illusie. Mijn naam is Mahamaya. Ik ben illusie, zonder twijfel. Maar ik ben enkel illusie om over jullie te oordelen.

Toewijding is een heel belangrijk onderdeel van de spirituele groei. Waarom? Als jullie in een onzekere toestand verkeren, als een onmiddellijk gevaar jullie bestaan bedreigt, als de wereld zich in een onzekere positie bevindt en volledig verwoest gaat worden, is het heel belangrijk je met alle macht en volledig geloof te houden aan wat jullie kan redden.

Zoals wanneer je nat wordt van gewoon water, dat is niet erg. Maar als je in de zee zinkt en er is op dat ogenblik de vraag over bestaan of vernietiging en als er op dat moment een hand komt om je te redden, dan heb je geen tijd meer om te denken, maar om je er aan vast te klampen met al je kracht, met al je geloof.

Als we badha’s hebben, als we door negativiteit omgeven worden, dan worden wij ervan bewust en we geraken een beetje verward. Op dat moment willen we ons vastklampen. Maar de badha’s bezorgen je schadelijke ideeën. Zo ontstaat er een grote strijd. Wat is op dit ogenblik de beste weg? De beste manier is om al de rest te vergeten. Vergeet dat je bezeten bent, of dat er een badha is of wat dan ook. Klamp je aan mij vast met al je macht, wat er ook gebeurt.

Maar de stijl van onze toewijding is zeer modegericht en modern en Sahaja Yoga en de Moeder zijn bijzaak, en. Het spijt me, maar zo zal het niet uitwerken. Ik hoef dit niet aan Indiërs te vertellen want het is voldoende dat je de Devi Mahatmyam leest. Zelfs als je haar duizend namen leest, is het voldoende om te begrijpen dat zij alleen door bhaki bereikt kan worden. Zij kan alleen door toewijding bereikt worden. Zij houdt van haar bhakta’s, haar toegewijden... . Het staat nergens geschreven dat zij meer houdt van mensen die beter kunnen spreken, die beter kunnen argumenteren, die beter gekleed zijn, die beter leven, die uit een betere omgeving stammen - maar van haar toegewijden. En deze devotie en toewijding moet niet onzinnig of wat dan ook zijn, maar zij moet onderhouden worden en continu, steeds vloeiend, steeds groeiend zijn. Dat is de enige manier voor verdere ontwikkeling.

Voor ons zijn zo veel kleine problemen belangrijk. Iemand bezit een huis, iemand krijgt een benoeming aan een universiteit, iemand moet een job uitvoeren. Al deze beschouwingen zijn dharma’s die Shri Krishna beschreef als volgt: "Sarva dharmanam parityajya mamekam sharanam vraja.” "Geef al je dharma’s op", al deze zogenaamde dharma’s. Zo is de patni- dharma de plicht van de vrouw, de pati-dharma de plicht van de echtgenoot, de putra-dharma de plicht van de zoon, de pita-dharma de plicht van de vader, de plicht van een burger en de plicht van een wereldburger. Al deze dharma’s dienen 'volledig' opgegeven te worden. En je moet je volledig vanuit je hart overgeven.

Ik ben wat ik ben, ik ben dat geweest en ik zal dat zijn. Ik zal niet meer of minder groeien. Dit is een eeuwige persoonlijkheid. Het is aan jullie om alles wat mogelijk is uit mij te halen, om het best mogelijke gebruik van je geboorte te maken in deze tijd, om tot volledige rijpheid te groeien, om in staat te zijn het plan uit te werken dat God langs jullie om wil volbrengen. Van zodra de toewijding er is, worden jullie heel dynamisch. Klamp je daaraan vast.

Hiertoe is meditatie de enige weg. Natuurlijk kan je rationeel (gezien) van alles doen. Je kan mij rationeel aanvaarden. Emotioneel kan je je in je hart dichter bij mij voelen. Maar je geeft je over door meditatie. Meditatie is niets anders dan overgave, is volledige overgave, wat een zeer moeilijke taak is voor een modern mens in het westen. Hij (de westerling) geeft zich enkel over aan mensen die hypnotiseren, die hem volledig hypnotiseren. Zij worden slaven van mensen die hen hypnotiseren. Maar in hun eigen vrijheid is hun ego veel krachtiger dan hun Spirit, in hun eigen vrijheid. Dit is de reden waarom al de vrije landen naar de bliksem gaan. Omdat ego een belangrijke rol speelt en niet de Spirit. Zij kunnen hun ego niet beheersen als ze vrij zijn. Enkel wanneer iemand hun ego in verwarring kan brengen en hen hypnotiseert, zijn ze in orde. Ze klappen dicht, ze geven zich volledig over. En de wijze waarop deze valse mensen die kunst beheersen om slaven van jullie te maken, is zeer duidelijk.

In volle vrijheid, volledige vrijheid moet je je overgeven. Vrijheid betekent niet ego, dat moet je goed begrijpen. Vrijheid wordt gedood door ego. Niet enkel gedood, maar misvormd, ontluisterd en lelijk gemaakt. Vrijheid in zijn subtielste vorm is egoloos, zonder hoeken, hol als een fluit, zodat de melodie van God mooi gespeeld kan worden. Dit is volledige vrijheid - geen dwangvoorstelling!

Wij moeten beseffen dat wij in een moeras zitten, het moeras van de onwetendheid, het moeras van de zonde. Onwetendheid brengt zonde voort. Hoe kunnen wij uit het moeras geraken? Wie er ons probeert uit te trekken, valt er zelf in. Om het even wie nabij komt, wordt erin gezogen. Hij wordt er een deel van. Hoe meer we proberen hulp van anderen te krijgen, hoe meer we hen verder in het moeras duwen.

En we zinken er steeds dieper in.

De boom van de Kundalini moet groeien en de Paramatma zelf zal jullie er uit trekken. Het groeit vanuit het moeras en Parabrahma zelf zal jullie er een na een uittrekken. Hij zal je bij de hand nemen en je eruit trekken. Maar zelfs als jullie er uit zijn is je greep niet voldoende, jullie glijden opnieuw naar beneden. Je komt er gedeeltelijk uit en je gaat opnieuw naar beneden. Het is vreugdegevend om eruit te zijn, maar toch zijn de voeten er niet volledig uit. Je bent nog steeds niet volledig gezuiverd. Hoe kan je ten volle gezegend worden zolang je niet gezuiverd bent? Je moet volledig gezegend worden door het goddelijke, gekleed door de liefde van God.

Het is verrassend te zien hoe de mensen die naar deze valse goeroes gaan, hem of haar trouw blijven, met zo'n buitengewone toewijding dat je er verbaasd over bent. Ze worden precies sufkoppen! Tot ze volledig vernietigd worden staan ze alles af wat ze hebben.

Maar als mensen naar Sahaja Yoga komen, geven ze zich niet, maar ze worden gevoed, ze worden verzorgd. Hun gezondheid verbetert, hun rijkdom verbetert, hun verstand verbetert, hun relaties verbeteren; over het algemeen voelen ze zich beter, hun levensomstandigheden verbeteren. Ze halen er voortdurend voordeel uit. We hebben mooie ashrams die de goedkoopste zijn, en voedsel. Alle voordelen zijn aanwezig op de best mogelijke manier. Alles is er. Maar we beseffen niet waartoe al deze voeding dient. Waarvoor dienen al die zegeningen? Voor een hogere spirituele groei. Om volledig uit het moeras te kunnen stappen.

Je moet vasthouden, je moet je toewijden. We zijn terughoudend, we verbergen dingen. We proberen slim te zijn. Dit is een gevaarlijke situatie. Jullie zouden allemaal binnenin jezelf moeten proberen te zien wat er in ons nog zo heimelijk is. Welke conditionering houdt je weg van de toewijding? Wat bezorgt je reserves? Welke schrik? Welk ego? Welke angel houdt je in het moeras gevangen? Welke gehechtheden? Welke relaties? Je moet ervan loskomen. Zolang je er niet van loskomt, zal het niet uitwerken. Er is geen plaats voor halfbakken zaken. Het is een kwestie van nu of nooit. Christus (Krishna?) heeft het gezegd. Hij heeft gezegd: "Zorg voor devotie en toewijding en laat de rest aan mij over."

Ik weet wie vooruitgaat in toewijding en devotie. Ik heb (sommige) mensen echt zien groeien. Het is niet nodig tegenover mij te staan of mij te zien. Ik moet niet persoonlijk aanwezig zijn. Het is allemaal in de alles doordringende kracht. Dat is heel mijn licht, dat alles over jullie weet. Alleen door middel van bhakti, door devotie en toewijding kunnen jullie mij bereiken.

Mijn doel is de volledige manifestatie van jullie goddelijke krachten. Het is zeer eenvoudig, zo eenvoudig gemaakt. Alleen mensen die eenvoudig, onschuldig, niet sluw, liefdevol, medevoelend voor elkaar zijn, kunnen mij behagen. Het is zeer eenvoudig om mij te behagen. Als ik zie dat jullie elkaar liefhebben, positief over elkaar spreken, elkaar helpt, elkaar respecteert, samen lacht, vreugde beleeft aan elkaars gezelschap, krijg ik mijn eerste zegening, mijn eerste vreugde. Probeer elkaar lief te hebben, in overgave, omdat jullie allemaal mijn kinderen zijn, gecreëerd uit mijn liefde.

Jullie verbleven allemaal in de schoot van mijn liefde. Vanuit mijn hart heb ik jullie deze zegeningen gegeven. Het verstoort mij, mijn handen beven en je valt terug in het moeras als ik jullie onderling ruzie zie maken. Jaloersheid en onbeduidende dingen die tot je vorig leven behoren. De hulp is niet zo groot dat ze voelbaar is, maar het is een veel dieper gevoel van veiligheid dat aan je broers en zusters geschonken wordt. Er zou een diepe liefde moeten zijn. Egoïsme heeft geen plaats in Sahaja Yoga. Gierigheid heeft geen plaats in Sahaja Yoga. Gierigheid is een teken van een heel klein verstand. Natuurlijk bedoel ik hiermee niet dat jullie mij geld moeten geven. Het gaat om de manier waarop we naar geld kijken, de manier waarop we eraan vastkleven, aan de materiële dingen, de materiële rijkdom, de materiële voorwerpen, de bezittingen.

Het grootste bezit dat je hebt is je Moeder. Door haar heb je broers en zusters (gekregen). Doe afstand van het verleden. Het verleden is een moeras. Dat zou nu voorbij moeten zijn. Jullie zijn er je zeer goed van bewust hoe ik jullie beschermd heb met de kracht van mijn liefde. Jullie weten hoe ik jullie op elk ogenblik geholpen heb. Om elk onderdeel van je verlangen te vervullen. Dat is zoals ik zei, de ene zijde: de voedingsbodem. Maar nu moet de spirituele vooruitgang van jullie komen. Het moet van jullie komen. Dat moet door jullie, en jullie alleen uitgewerkt worden. Niet door een andere sahaja yogi of door mij. Ik kan je enkel suggesties geven. Niet alleen suggesties, maar ook de waarschuwingen. En alles is aanwezig, het is zo goed uitgewerkt. Ik verschijn in een (menselijke) vorm voor jullie. Je hoeft niet elders te gaan(zoeken). Alles is in jezelf aanwezig. Je hoeft geen geld geven, je moet niets geven. Maar ontwikkel die toewijding binnenin jezelf.

De man die mij interviewde, zei dat de werklozen door de politici gemanipuleerd worden. Laat God jou manipuleren. Maar hoe? Veronderstel dat ik een borstel in mijn hand heb, en ik iets wens te schilderen en dat ik de borstel niet kan manipuleren.

De borstel is hoekig, niet goed, ongerieflijk, of je kan zeggen, onhandig, onpraktisch, lomp. Hoe kan je hem dan gebruiken?

Toewijding is de gemakkelijkste weg om van al je hoekigheden, al je problemen, al je badha’s af te geraken. Kijk nu binnenin jezelf: Ben je toegewijd?

Zij die zich fanatiek aan mij vastklampen, zijn ook niet goed bezig. Er zou geen fanatisme mogen zijn. Alles wordt zo volledig logisch. Er is geen fanatisme. Zoals iemand zei die naar een dokter moet gaan. Een fanatiek persoon zou dan zeggen: "O, ik zal niet naar de dokter gaan. Ik ga niet naar de dokter omdat Moeder me gezegd heeft dat zij voor mij zou zorgen." En wanneer zij ziek wordt, zal zij naar Moeder komen en vechten: "Moeder! U hebt mij gezegd dat u voor mij zou zorgen, hoe kan ik dan ziek worden?" Dit is fanatisme.

Wat is overgave? Zeer diep binnenin zou je moeten zeggen: "Het is de Moeder, zij is daar, zij is mijn dokter. Of zij mij behandelt of niet, of zij mij geneest of niet, ik heb niets te zeggen. Ik ken alleen haar. Ik ken niemand anders." Het is zeer logisch. Het logische is dat Moeder het meest krachtvol is: dat weet je logischerwijze, het is de waarheid. En als dit zo is, zal Zij mij genezen. Maar als Zij mij niet geneest, is het haar kracht, is het haar goodwill. Als Zij mij wil genezen, zal Zij mij genezen. Als Zij mij niet wenst te genezen, hoe kan ik mijn wil aan haar opdringen?

Zoals de toewijding van Shri Ganesha, toen zijn Moeder zei: "Wie van de twee broers, Kartikeya en Hij, als eerste rond Moeder Aarde cirkelde, de eerste prijs kreeg." De arme Ganesha had een kleine rat om zich te verplaatsen, maar hij was wijs. En Kartikeya had een zeer snel bewegende pauw om te vliegen. Hij keek naar de pauw en hij zei: "Wie is groter dan mijn Moeder? Zij is de Adi Shakti! Wat is deze aarde? Wie heeft deze aarde gecreëerd? Mijn Moeder heeft haar gecreëerd. Wie heeft de zon gecreëerd? Mijn Moeder heeft haar gecreëerd. Wie is groter dan mijn Moeder? Niemand. Waarom niet enkel rond mijn Moeder gaan? Waarom rond de hele aarde gaan?" En lang voor Kartikeya aankwam, zat hij daar met de prijs in zijn hand!

Zijn onschuld gaf Hem deze wijsheid om te begrijpen. Dat is logisch. Het is zeer logisch. En het is ook logisch dat Moeder mijn pijn beter voelt dan ik zelf." Wat zou jij zeggen wanneer Christus voor zijn Moeder gekruisigd werd? Zij was Mahalakshmi zelf, zo krachtig! Zij was zo krachtig Haar Zoon zijn leven te laten offeren, lijden als een menselijk wezen. Het was te veel, haar zoon te laten lijden als je alle kracht in handen hebt om er een einde aan te maken! Maar het was een zeer delicate job om deze agnyachakra te creëren.

Wat betekent dit? Betekent dit dat Hij in zijn devotie tekortschoot? Integendeel, zij was zeker van hem, van zijn devotie, zodat zij Hem dit kon vragen. Als je dus verwacht dat Moeder iets voor jou zal doen... Er zijn mensen die zeggen: "Goed Moeder, ik geef deze thesis, ik moet erdoor komen.” In orde, geef een bandhan en je zal het krijgen. "Moeder, ik probeer dit te ontdekken." In orde, je krijgt het. "Moeder ik probeer deze job te krijgen." Je krijgt hem.

Nu is het andersom. Hoevelen hebben zulke toewijding als Christus? Niemand. Dit is een feit! Waarom is hij de oudste broer? Omdat er niemand is zoals hij. Hij ging doorheen dit alles, doorheen die vreselijke lijdensweg, omdat hij een onderdeel was van zijn Moeder. Zij leed meer dan hij. Hij onderging dit lijden voor een hoger doel, voor een groter geluk, voor een groter leven, voor een hoger leven. Dat is echte toewijding. Maar deze valse mensen kunnen hier voordeel uit halen.

Als zij mensen laten lijden, zeggen ze: "Uiteindelijk moet je toch lijden." Zie hoe zij het voorstellen! "Je moet lijden, anders kan je niet groeien." Het is een zeer subtiel begrip. Het is zeer subtiel. Dat zal je duidelijk maken: in Sahaja Yoga word je eerst gevoed, grootgebracht. Je wordt getraind, je wordt in orde gebracht. En alles wat je daarna doet, het lijden, is voor jou geen lijden meer omdat je de Spirit geworden bent. Het kan door niets gedood worden. Het kan niet weggerukt of door de wind weggeblazen worden. Het kan door geen vuur verbrand worden. Er is geen enkele weg om het te vernietigen. Dat is de Spirit die je bent. Zo word de voeding nu gegeven. Je bent gegroeid, gevoed. Als mensen sahaja yogi’s zien, zeggen ze: "Ze zijn als bloemen! Hun gezichten, hun glans! Hoe vertrouwensvol, hoe waardig, hoe mooi!" Maar waarvoor? Om de wielen te zijn van Gods strijdwagen. Je moet de beproevingen en het offer doorstaan, wat voor jou geen opoffering is, omdat de Spirit geeft, hij lijdt nooit. Zijn kwaliteit is: geven. Je volbrengt geen offer, je geeft alleen maar. Eerst heeft de moeder weeën. Zij heeft alle problemen. Als het kind is opgegroeid, steunt het zijn moeder en zij steunt hem. Hij is de fiere zoon. Zij is fier: Zij is fier over hem en hij is fier over haar. Zij staan tezamen, zij strijden tezamen. Dit is enkel mogelijk als je volledige toewijding en voorbereiding voor een toekomstig leven als sahaja yogi aanvaardt. Het leven ziet er uiterlijk als een strijd, een probleem uit, maar innerlijk is dit zeer bevredigend.

Eens kwamen sahaja yogi's bij me. Voor hen was zitten op de grond zelfs een te groot offer. Zelfs schoenen uitdoen was een groot offer. Gisteren verlieten drie mensen het programma omdat hen gevraagd werd hun schoenen uit te doen, alsof iemand hen kaal schoor. Zij gingen gewoon buiten.

Waarom moeten we groeien in Sahaja Yoga? Om te groeien, erbij staan als grote kinderen van een grote Moeder. Het werk is enorm. Middelmatige mensen kunnen deze job niet doen. Mensen met vrees, schrik, arrogantie, brutaliteit kunnen het niet doen; zij hebben geen moed.

De toewijding in meditatie, volkomen toewijding in meditatie moet worden geoefend. Het is niet voor jouw goed dat je het doet. Het zogenoemde jou goed. Eerst was je een kleine baby, een klein ding. Nu ben je dat collectieve wezen, dus werk je niet meer voor jezelf, maar voor dat collectieve wezen. Je groeit om bewust te zijn van het geheel dat je zal worden. Je jobs, je geld, je echtgenotes, je echtgenoten, je kinderen, je vader, moeder, relaties, dit is nu voorbij. Jullie moeten allemaal de verantwoordelijkheid voor Sahaja Yoga opnemen. Iedereen van jullie is zeer bekwaam, je bent ervoor grootgebracht.

Doe het op de manier die je zelf wenst, wat ook je capaciteiten zijn. Met volle toewijding zal je het kunnen. Toewijding is de essentie. Volledige toewijding in de enige weg om verder te groeien. Sommige yogi's zijn halfbakken. We gooien ze eruit. We kunnen ze niet houden. Je sympathiseert niet met hen. Daar zit niets goed in. Als het blijkt dat zij in orde zijn, zullen wij hen terug laten komen. Maar dat laat je aan mij over. Jullie doen er geen inspanning voor, en je zet ook je aandacht niet op hen. Jullie zelf moeten vooruit komen. Jullie waren zoekers, dan heb je het gevonden, je bent voorspoedig gegroeid. Nu ben je volwassen (in Sahaja Yoga). Waarvoor? Om sterk te staan. Zoals ik vandaag voor jullie sta, zo moeten jullie je voor de anderen opstellen, je moet het doen. Toewijding betekent niet dat je niet over Sahaja Yoga moet praten. Veel mensen denken zwijgen toewijding is. Enkel in meditatie moet je dit zijn. Maar je moet uit die schelp (van stilte) komen. Vertel de grote boodschap aan al de naties en al de mensen over de gehele wereld dat het nu de tijd is van de verrijzenis (wederopstanding). Nu, op dit ogenblik, en dat iedereen bekwaam is om het te doen. En als iemand hierdoor met je spot, probeer dan met begrip en wijsheid de dingen uit te leggen.

Persoonlijke voorkeur en afkeer moeten opgegeven worden. "Ik hou hiervan en daarvan" moet verdwijnen. Dit betekent niet dat je allemaal machines wordt. Neen. Maar de verslaving aan dit 'Ik' moet opgegeven worden. Verslaving aan gewoonten moet opgegeven worden. Je zal verrast zijn. Eens je toegewijd bent, zal je niet veel meer eten. Soms zal je ook niets eten. Je zal geen behoefte hebben om aan voedsel te denken. Je zal je niet herinneren wat je gegeten hebt. Je zal je zelfs niet herinneren waar je geslapen hebt, hoe je sliep. Het is een leven als een telescoop: zich uitbreidend! Je zal je eigen visies scheppen en ze uitwerken, ze volbrengen. Jullie zien er zo'n eenvoudige, ordinaire mensen uit, maar dat zijn jullie niet. In toewijding, in volledige devotie moet je het 'nu' doen. Niet voor je eigen goed, voor je eigen doel. Dat is nu voorbij. Het is om volledig uit het moeras te komen en op het land te staan en luid de lof van je Vader te zingen. Welke muziek kunnen zij die in het moeras zitten maken? Welke liederen kunnen zij zingen? Welke veiligheid kunnen zij geven? Welke hulp kunnen zij aan anderen bieden?

Jullie moeten er volledig uit zijn. Hiervoor is standvastige wijsheid nodig. Vastberaden! Op ieder ogenblik. Je moet noch je linker zijde noch je rechterzijde hiervoor de schuld geven. Niets. Kom er gewoon uit. Klem je eraan vast. De Parabrahma is naar jou gekomen om voor je te zorgen. Klem je eraan vast. Zelfs de dood moet wijken. Wat dan met deze onbeduidende zaken?

De naam van je Moeder is zeer krachtig. Je weet dat dit de meest krachtige naam is, krachtiger dan alle andere namen, de krachtigste mantra. Maar je moet weten hoe hem te gebruiken. Met volledige overgave moet je die naam zeggen. Niet als elke andere naam. Je weet dat men in India aan de oren trekt als men de naam van de Goeroe zegt Dit betekent: "Vergeef me alstublieft als ik een fout maak bij het zeggen van die naam." Het betekent dat. Dit is een zeer krachtige mantra. Het enige wat je nodig hebt is toewijding, het dynamiet van de toewijding. Vandaag vertelde ik Rita dat in Engeland alle madeliefjes nu geuren. Ze kond het niet geloven. Zij zei: “Ik heb dit nooit geweten. Integendeel, ik meende altijd dat madeliefjes geen geur hadden, maar dat ze eigenaardig geurende bloemen waren." Ik zei: "In orde, ruik gewoon aan de madeliefjes. " Zij was zo verrast toen ze eraan rook. De naam! Verwonderlijk! De naam! Hoe subiel is dit! Ze zijn de meest geurige bloemen van Engeland. Alleen de naam! Hij betekent Nishkalanka, Nirmala, wat volledig zonder enige mala is. Wat is die mala? Dit is het moeras, zonder maya: Nih, Absoluut! De vreugde van de Sahasrara wordt sinds lange tijd nirananda genoemd. Sinds vroegere tijden wordt nirananda of nirmala-ananda genoemd. Zovelen noemen hem Nirmala-ananda of Nirananda. Deze vreugde is de vreugde die je zelfs beleeft als je gekruisigd wordt. Die vreugde is de vreugde die je ervaart zelfs als je vergiftigd wordt. Zelfs op je sterfbed ervaar je die vreugde. Die vreugde is Nirananda.

Wees dus voorbereid op de tweede fase. Je staat vooraan. Ik heb heel weinig tijd nodig. Maar ik heb echt mensen nodig met standvastige wijsheid en toewijding. Standvastigheid. Zelfs geen seconde zou het die of die richting mogen uitgaan. Dan kunnen we sneller vooruitgaan, we kunnen voorop gaan om de strijd te strijden.

Misschien ben je je nu bewust van de subtiliteit van de negativiteit, hoe zij haar kracht gebruikt - natuurlijk is dit beperkt - om Gods werk te vernietigen. En hoe alert, wel uitgerust en toegewijd je moet zijn. Dit kan ik alleen tegen jullie zeggen, en niet tegen de mensen die naar de Caxton Hall komen. Sommigen onder hen zijn halfbakken, sommigen zijn zeer nieuw, naïef, en sommigen zijn absoluut van de derde rang. Maar nu jullie hier vandaag voor mij zitten, wil ik jullie dit zeer openhartig zeggen, zoals Krishna enkel aan Arjuna gezegd heeft: "Sarva dharmanam parityajya, mamekam sharanam vraja."

Er is geen andere uitweg. Vraja betekent diegene die tweemaal geboren is, als een betrouwbare persoonlijkheid. Als je stevig gevestigd bent, moet je je toewijden. Als je volmaakter geworden bent, moet je je toewijden. Het zal je helpen uit het moeras te komen en dat zal het grote werk vooruithelpen. Niemand verstaat waarom Moeder hen probeert te helpen. Ze denken dat zij te genereus is. Dat ben ik niet. Ik heb veel gezond verstand. Omdat jullie diegenen zijn die bekwaam zijn om Gods vreugde op deze aarde te manifesteren.

Jullie zijn de fluiten die de melodie van God zullen spelen. Jullie zullen door God gebruikt en gemanipuleerd worden. Ik doe dit alles om jullie te vervolmaken opdat jullie de mooiste instrumenten van God zouden zijn. Om het juiste instrument van God te zijn. Ik weet niet of je begrijpt hoe zacht en mooi het leven zou zijn, een leven van toewijding, met begrip, volledig toegewijd, alle voeding en toewijding benuttend voor een hoger doel. Een beetje zoals de bladeren (kracht) putten uit de zonnestralen en kleur geven, kleur krijgen voor henzelf, voor een hoger doel, zodat ze later door menselijke wezens gebruikt kunnen worden. Niets op deze wereld werkt op een andere manier. Alles werkt uit voor een doel, maar zo'n onegoïstisch, zo’n wijds, zo'n groot en dynamisch doel.

Je wordt de oceaan, je wordt de maan, je wordt de zon, je wordt de aarde, je wordt de ether, het firmament, en je wordt de Spirit. Je werkt voor hen allemaal. Je wordt al de sterren en de universums, en je neemt hun werk op. Dat is het. Omdat je je oorsprong, je tattva aanvaard hebt. Dat is de manier waarop je naar ieders tattva gaat. Maar wees toegewijd aan dit tattva, want ik ben de oorsprong van dit alles. Ik ben de tattva, tattvamasi. Ik ben de oorzaak. Hou je aan je oorzaak. Ik ben de Kundalini. Ik ben de essentie.

We kunnen toewijding enkel begrijpen voor iets dat groter lijkt, dat groter verschijnt. Maar we kunnen onszelf niet toewijden aan iets dat zoveel subtieler is, dat zoveel kleiner is, dat zoveel dieper is, zo effectief is, dat zo dynamisch, zo universeel en eeuwig is. We kunnen ons niet indenken ons daaraan toe te wijden. We kunnen onszelf toewijden aan iemand die op een berg lijkt, die komt om ons als een berg te onderdrukken, die als Hitler is, die als een valse goeroe is. Maar je overgeven aan je subtieler wezen, dat je met je ogen niet kan zien, dat je niet kan horen, maar dat in feite zo krachtig is. Als een atoombom, als het atoom gesplitst is. Als het niet gesplitst is, is het overal. Maar op het meest subtiele punt is het zo dynamisch dat, wanneer het gesplitst wordt, het zo'n dynamische destructieve kracht wordt. Omdat je aandacht nu binnengegaan is in het subtiele deel van het universum en er dieper en dieper ingaat. De kracht die het uiteinde van de wortel naar de bron brengt, is de zelfde als de bron. Je Kundalini is dezelfde als de Adi Kundalini en het is de kracht, de Parabrahma.

Al deze dingen moet men na realisatie verstaan, en na het volwassen worden. Daarvoor is het niet mogelijk. Daarom heb ik deze dingen gedurende de laatste acht jaren niet tot jullie gezegd. Ik was zeer beschermend en sprak met zeer zoete woorden tot jullie. Ik heb jullie steeds laten aanvoelen dat je verplichtingen tegenover mij hebt. Het is geen verplichting. Los van al deze concepten ben je je Zelf geworden, klaar om je verantwoordelijkheid op te nemen voor datgene waarvoor je gemaakt werd. Zoals het schip wordt gebouwd, naar de zee gebracht, uitgetest en zeewaardig bevonden om nu uit te varen in de zee. Dit is de tweede fase, waar je moet uitvaren, want je weet alles over het schip, alles over de zee. In volledige vrijheid en wijsheid, moet je nu varen. Je hoeft niet bang te zijn voor stormen of tyfoons omdat je nu alles weet. Je job is er doorheen te gaan.

Moge God jullie zegenen.