Šrí Ekadeša Rudra Pudža, Faggeto Lario, Como (Taliansko), 16. septembra 1984

Dnes robíme mimoriadnu pudžu, ktorá sa koná pre slávu Ekadeša Rudry.

Rudra je deštrukčná sila Šívu, Ducha. Jedna sila, ktorá je mu vlastná, je odpúšťanie.

Odpúšťa, lebo sme ľudia, robíme chyby,robíme zlé veci, necháme sa zlákať, naša pozornosť je narušená - takže nám odpúšťa. Tiež nám odpúšťa, keď si poškodíme svoju cudnosť, keď robíme nemorálne veci, kradneme a robíme veci, ktoré sú proti Bohu, keď hovoríme proti Nemu.

Tiež nám odpúšťa naše povrchnosti, žiarlivosť, našu žiadostivosť, náš hnev. Rovnako odpúšťa naše pripútanosti, obmedzenú závisť, namyslenosť a tiež vlastníctvo. Odpúšťa naše egoistické správanie a tiež našu podriadenosť nesprávnym veciam.

Ale každá akcia má reakciu a keď odpúšťa, tak si myslí, že vám udeľuje veľkú značku milosti a táto reakcia v ňom vytvára hnev proti tým, ktorým bolo odpustené a ďalej sa snažia robiť väčšie chyby. Obzvlášť po Realizácii, lebo Realizácia je také veľké požehnanie. Dostali ste svetlo a ak sa v tomto svetle držíte svojho hada, tak narastá Jeho hnev, lebo vidí, akí ste boli hlúpi.

Povedala som, že obzvlášť po Realizácii je oveľa citlivejší na ľudí, ktorým bolo odpustené a ktorí dostali tak veľkú vec, akou je Sebarealizácia a stále robia zlé veci, tak potom sa hnevá oveľa viac.

Takže v rovnováhe sa začína zmenšovať odpúšťanie a hnev začína narastať.

Ale ak odpustí a ako dôsledok tohoto odpustenia cítite vďačnosť, tak k vám začnú prúdiť Jeho požehnania. Dá vám obrovskú schopnosť odpúšťať druhým. Upokojí váš hnev, utíši vašu chtivosť, ukľudní vašu nenásytnosť, Jeho požehnania k nám prichádzajú ako nádherná kvapka rosy a my sa zmeníme na skutočne nádherné kvety a začneme žiariť na výslní Jeho požehnaní.

Používa svoj hnev alebo svoju deštrukčnú silu na zničenie všetkého, čo sa nás snaží trápiť.

V každom ohľade, v každom smere ochraňuje realizované duše. Negatívne sily sa snažia útočiť na sahadža jogínov ale vďaka Jeho ohromnej sile ochrany sú všetky neutralizované. Pomocou jeho vibračného vedomia sme vedení na správnu cestu. Všetky jeho nádherné požehnania sú opísané v 23. žalme, je to tak, 23. žalm... Pán je mojím pastierom. Je tam všetko opísané, ako sa o vás stará ako pastier.

On sa ale nestará o zlých ľudí. Tých zničí. Tí, ktorí prišli do Sahadža jogy a stále pokračujú so svojou zlou povahou, tých zničí. Tí, ktorí prídu do Sahadža jogy a nemeditujú a nestúpajú, tých zničí, alebo sú zo Sahadža jogy vyhodení. Tí, ktorí reptajú proti Bohu a žijú spôsobom, ktorí nie je hoden sahadža jogína, tých odstráni. Tak jednou silou ochraňuje a druhou vyhadzuje. Ale ak sa jeho deštrukčné sily príliš rozvinú, tak to voláme: "Teraz je aktívna Ekadeša Rudra."

Táto Ekadeša Rudra sa prejaví, keď samotný Kalki začne konať, čo znamená, že ničivá sila zničí všetko, čo je na tejto zemi negatívne a zachráni všetko pozitívne. Tak pre sahadža jogínov je veľmi potrebné urýchliť svoj vzostup, neuspokojiť sa so spoločenským alebo manželským životom, alebo so všetkými požehnaniami, ktoré vám Boh dal. Vždy sledujeme to, čo Boh pre nás urobil, aké vykonal zázraky, ale my musíme vidieť, čo sme my urobili pre seba, čo robíme pre svoj vzostup a rast.

Jedna z jedenástich ... Ekadeša znamená jedenásť, päť prichádza z pravej strany vášho Voidu a päť z ľavej strany vášho Voidu.

Prvých päť na ľavej strane pochádza z toho, ak ste sa klaňali nesprávnym guruom alebo ak ste čítali nesprávne knihy, alebo ak ste boli v spoločnosti nesprávnych ľudí, alebo ak ste sympatizovali s ľuďmi, ktorí nasledovali nesprávne cesty, alebo vy sami ste boli agentami alebo guruami týchto zlých ľudí.

Týchto päť problémov možno vyriešiť, ak sa úplne vzdáme všetkého zlého, čo sme robili. Ako povedal Mohamed Sahib: "Musíte biť šatana, čo znamená Satana, pomocou topánok." Ale toto treba urobiť nie mechanicky, ale zo srdca. Mnoho ľudí, ktorí prišli do Sahadža jogy, mi povedia: "Môj otec nasleduje toho gurua, ten otec nasleduje tamtoho gurua." A zapletajú sa so svojím otcom, sestrou, tým, tamtým a snažia sa ich dostať od tých guruov a tiež sa zapletú. Alebo niektorí z nich podľahnú iným silám.

Ako viem od Maureen, ktorá bola so mnou, a jej rodičia a svokrovci povedali, že to dieťa musí byť pokrstené. Ja som jej povedala - nemôžeš dať pokrstiť to dieťa, je to realizovaná duša. Ale nedokázala sa im postaviť a vzala dieťa na krst a dieťa začalo byť veľmi divné - bolo skutočne ako šialené. Teraz sa toho všetkého vzdala, a tak bola zachránená. Ale povedzme, že by mala ďalšie dieťa a urobila by to isté, druhé dieťa by dopadlo veľmi, veľmi zle.

Problémom sahadža jogínov je, že ktokoľvek, kto príde na program Sahadža jogy, si myslí, že je sahadža jogín - nie je to tak.

Buď by ste mali mať silnú vnímavosť alebo by ste to mali cítiť vo svojom tele, alebo by ste mali rozumieť svojou inteligenciou, čo je Sahadža joga. Človek, ktorý je stále negatívny, je vždy priťahovaný k druhému, ktorý je veľmi, veľmi silno negatívny, a nerozumie tomu, že ten druhý človek je tak silno negatívny, ale urobí to naňho dojem. Za takýchto okolností je takáto osoba zasiahnutá tou negatívnou osobou a Šíva ho nemôže ochrániť.

Človek by nemal chovať sympatie k nikomu, kto je negatívny, či je to šialenec, či je s ním niečo v neporiadku, či je to váš príbuzný, alebo čokoľvek. Vôbec žiadne sympatie, naopak, mal by tu byť istý druh hnevu na toho človeka. Určitá odpútanosť, nahnevaná odpútanosť. A táto nahnevaná odpútanosť je jediné, kedy sa máte hnevať. Ale videla som ľudí, ktorí sa hnevali na veľmi dobrých sahadža jogínov, ale nie na svojich manželov alebo manželky, ktorí sú extrémne negatívni.

Takže ak Ekadeša Rudra začne konať na týchto piatich stranách, môžeme povedať, že sa pohybuje doprava, lebo prichádza zľava a pohybuje sa doprava, tak sa človek začne stávať negatívnym, lebo koná so svojím egom.

Taký človek môže prevziať situáciu do svojich rúk a povie: "Som taký a taký sahadža jogín a som taký, mali by sme urobiť toto a takto by sme sa mali správať" a začne ľuďom diktovať. Môže urobiť čokoľvek. A niektorí polovičatí alebo niektorí nedopečení sahadža jogíni sa môžu snažiť mu porozumieť, ale väčšina to bude vedieť: "Tento človek je mimo, je na ceste preč!"

Takže všetky tieto veci vedú k rozvoju ľavej strany alebo na hlave to môžeme pomenovať pravá strana vašej medha, táto vrstva, mozgová vrstva sa v jazyku sanskrit nazýva medha.

Pravostranné pochádzajú z myšlienok ľudí ako: "Ja sám som veľký guru." Začnú tiež kázať o Sahadža joge, akoby sa stali veľkými guruami. Poznali sme nejakých ľudí, ktorí robili veľké prednášky na každom programe a nikdy nedovolili púšťať moje pásky a podobne. Myslia si, že sa teraz stali expertami.

Ďalej niektorí z nich povedali, že teraz sme sa stali tak veľkými, že nepotrebujeme robiť žiaden fútsok ani nič podobné, nepotrebujeme meditovať - je zopár aj takýchto. A potom sú takí, čo hovoria: "Hriech sa nás nikdy nedotkne, teraz sme sahadža jogíni, sme veľké rozvinuté duše."

Ale najhorší sú tí, ktorí používajú moje meno hovoriac: "Matka to povedala a ja vám to hovorím, lebo to Matka povedala." - aj keď som nikdy nič také nepovedala, všetko je to faloš.

Existujú ľudia, ktorí používajú peniaze Sahadža jogy a takýmto spôsobom využívajú Sahadža jogu, niekedy využívajú aj sahadža jogínov. A takíto ľudia sa stanú veľmi neblahými. Ktokoľvek, kto sa pokúša o takéto veci, pôjde s hanbou preč zo Sahadža jogy. Ale nik by sa k takému človeku nemal približovať, nemal by mať s ním nič spoločné, žiadne sympatie. Lebo táto neblahosť každému ublíži v rôznej miere, takže je lepšie takých ľudí držať mimo.

Keď sa týchto desať Ekadeší v človeku rozvinie, tak s určitosťou taký človek dostane choroby, ako rakovina a hrozné neliečiteľné choroby. Obzvlášť, keď sa rozvinie jedenásta, ktorá je presne tu, je to čakra Viráty, čo je kolektivita, keď je aj táto napadnutá, tak sa človek tej choroby nemôže zbaviť.

Ale tieto... z týchto ak sa spojí čo i len päť, povedzme s Muladhárou alebo s Agnyou, tak dostanú veľmi vážne špinavé choroby. Preto vždy hovorím, aby ste si dali pozor na svoju Agnya čakru, lebo to je jedna z najhorších vecí, keď sa raz začne spájať s týmito Ekadešami, časťou Ekadeší, človeku sa môže stať čokoľvek. Môže ho stretnúť hrozná nehoda. Môže ho zrazu niekto udrieť, môže ho zabiť. Čokoľvek sa môže stať takému človeku, ktorý má pravú Agnyu a ktorúkoľvek z Ekadeší, vpravo či vľavo.

To znamená, týchto päť, ktorákoľvek z týchto piatich ak sa skombinuje s Agnya čakrou, tak ochranná sila Boha je na minime.

Takže na to, aby ste si udržali svoju Agnya čakru v poriadku, povedzeme, že teraz hovorím, teraz by ste ma mali nepretržite sledovať tak, aby tu bolo bezmyšlienkové vedomie a Agnya čakra sa upokojí.

Ale nevenujte stále pozornosť veciam tu a tam. Potom zistíte, postupne sa vaša pozornosť neutralizuje do bezmyšlienkového vedomia a vaša pozornosť sa tak upevní, že sa nebudete kvôli ničomu trápiť.

Nikto sa vás nemôže dotknúť v bezmyšlienkovom vedomí, je to vaša pevnosť. Človek si musí upevniť bezmyšlienkové vedomie pomocou meditácie, to je znakom, že stúpate vyššie. Veľa ľudí medituje a hovorí: "Dobre Matka, meditujeme." Robia to mechanicky a hovoria: "Áno, urobil som to, urobil som to a urobil som to!" Ale dosiahli ste minimálne svoje bezmyšlienkové vedomie? Cítili ste váš chladný vánok vychádzať z vašej hlavy? Inak ak robíte veci mechanicky, to vám nepomôže, nepomôže to vám ani nikomu.

Takže po Realizácii ste veľmi dobre chránení, máte všetky požehnania a veľkú budúcnosť, tiež máte veľké možnosti úplného zničenia.

Ak by som mala povedať analógiu, šplháte sa a každý podporuje váš výstup, držia vám palce a existuje veľa vecí, ktoré vás chránia, aby ste vystúpili hore, tiež nie je možné, aby ste spadli kvôli chybám, ale ak sa snažíte odstrániť svoje spojenia s Pravdou a s Láskou a stále sa pokúšate udierať do ľudí, ktorí sa snažia vás podporovať, tak potom spadnete z veľkej výšky. Z väčšej výšky. Myslím tým, čím vyššie vystúpite, tým hlbšie padnete a tiež s väčšou silou, oveľa hlbšie. Ale Božské vynakladá všetku snahu, dostávate všetku podporu, všetku starostlivosť. Ak napriek tomu chcete spadnúť, potom z tej výšky je to veľmi nebezpečné.

Ale Ekadeša Rudra vtedy, v takom čase, keď sa niekto snaží ublížiť podstate Sahadža jogy, potom, ako bol v Sahadža joge, udrie vás to tak silno, že celý ten útok je veľmi rozsiahly. Ale celá rodina môže byť ochránená, ak niektorí z rodiny robia prácu Sahadža jogy, mohla by byť ochránená. Ale v prípade rodiny, ktorá je stále proti sahadža jogínom a snaží sa im ubližovať, môže byť úplne zničená veľmi zlým spôsobom.

Tieto Ekadeša Rudry prichádzajú, ako som vám povedala, z Voidu. Takže môžeme povedať, že ich ničiaca časť pochádza hlavne z Voidu. Ale tieto všetky sily sú dané jednej osobe, ktorou je Mahavišnu, je to Pán Ježiš Kristus. Lebo On je podporou celého vesmíru. Je zosobnením Omkary. Je zosobnením vibrácií. Takže ak sa On rozhnevá, tak sa celý vesmír začne lámať. Zosobňuje silu Matky, ktorá preniká do každého atómu, do každej molekuly a do každého človeka, do všetkého, čo je živé a neživé, ak je raz vyrušený, tak je všetko v nebezpečenstve. Takže tešiť Krista je veľmi dôležité.

Kristus povedal: "Musíte byť ako malé deti." Znamená to, že nevinnosť, čistota srdca je najlepšou cestou, ako ho potešiť.

Obzvlášť na západe si ľudia príliš rozvinuli svoje mozgy, snažia sa hrať so slovami a myslia si, že nikto nevie, čo robia. Všetci títo musia vedieť, že všetko, čo máte urobiť, je poznať Boha.

Ak nie ste v srdci čistí, tak je pre každého nebezpečné tváriť sa ako dobrý sahadža jogín. Takíto ľudia nie sú posadnutí, nemajú ani predsudky, nie sú ani egoistickí, ale sú to veľmi prefíkaní, vychytralí ľudia a sú si dosť vedomí toho, čo robia. Ale sú tiež ľudia, ktorí sú tiež posadnutí, a tak sa v tom snažia sami seba zničiť a plačú a nariekajú a robia všetko možné.

Niektorí si myslia, že ak si ublížia alebo urobia niečo extrémne, tak Boh bude šťastný - smutne sa mýlia.

Ak sa nedokážete tešiť v Sahadža joge, tak vedzte, že s vami nie je niečo v poriadku.

Ak nemôžete byť šťastní v Sahadža joge, tak musíte vedieť, že určite je s vami niečo zlé.

Ak sa nemôžete tešiť spoločnosťou sahadža jogínov, tak si buďte istí, že s vami je niečo zlé.

Ak sa nemôžete smiať a oceňovať veľkosť Boha, tak je s vami niečo zlé.

Ak sa stále trápite s negatívnymi ľuďmi a ich problémami, tak vedzte, že s vami je niečo zlé.

Ak chováte sympatie k negatívnym ľuďom, tak tiež je s vami niečo zlé.

Ale ak sa hneváte na negatívne a všetko, čo je negatívne proti Sahadža joge, tak ste tam.

Keď tieto sily dozrejú, tak sa sami stanete silou Ekadeša Rudry. Každý, kto sa vás pokúsi uraziť alebo vám nejako ublížiť, stroskotá. Stalo sa to mnohým, ktorí sa ma snažili urážať alebo akokoľvek my ubližovať ... Niekedy sa o nich bojím.

Takže človek by mal byť tak nastavený, že sa stane Ekadešou. Takých ľudí sa nikto nemôže dotknúť. Ale taký človek je plný súcitu a odpúšťania. Dôsledkom toho Ekadeša pracuje ešte rýchlejšie. Čím viac ste milosrdní, tým mocnejšia sa stáva Ekadeša. Čím viac ste kolektívni, tým viac Ekadeša koná.

Mnohí majú zvyk uzatvárať sa do svojej samoty a hovoria: "Ó, radšej budeme doma, a tak je to dobre." Ale nevedia, o čo prichádzajú.

Môžete mať rôzne skúsenosti s druhými, mali by ste držať spolu, vždy navštevovať programy, viesť, ísť dopredu, vypracovať to a tisíckrát budete požehnaní.

Ekadeša Rudra sú dohromady všetky sily deštrukcie, povedala by som. Je to deštručná sila Šrí Ganéšu. Je to deštrukčná sila Brahmu, Višnua, Mahešu. Je to deštrukčná sila Matky. Je to deštrukčná sila Ganešu ... a týchto štyroch - Bhairava a Hanumana, Kartikeya a Ganeša. Tiež sú to sily Sadašivu a Adišakti. Ekadeša sú všetky deštrukčné sily všetkých inkarnácií.

Nakoniec ale nie posledné, je to deštrukčná sila Hiranyagarbha, čo je kolektívny Brahmadeva. A keď táto sila koná, tak každý atóm exploduje, celá atómová energia sa mení na deštrukčnú silu.

Takže Ekadeša Rudra je úplná deštrukčná sila. Je extrémne silná, výbušná, ale nie je slepá. Je utkaná mimoriadne jemne a s veľkým rozlišovaním. Obchádza všetko dobré a útočí na zlé veci a v správnom čase udrie na správne miesto, priamo, bez toho, aby udrela na niečo dobré, čo sa tam nachádza.

Povedzme, že pohľad Ekadeša Rudry sa zameriava na niekoho a medzi tým je tam niečo, čo je božské, alebo niečo, čo je pozitívne, tak cez pozitívne prenikne bez toho, aby tomu ublížila a udrie na negatívne. Niekoho schladí a iného spáli. Nezmrazí, ona nemrazí, schladí.

Takto funguje s veľkou starostlivosťou a jemnosťou. A je tiež ohrmone ostrá. A to je veľmi bolestivé. Nie je to ako odseknúť hlavu jedným úderom. Pracuje pomaly, pomaly.

Všetky hrozivé muky, o ktorých ste sa učili alebo počuli, sú len vyjadrením Ekadeša Rudry. Zoberme si príklad rakoviny. Pri rakovine odstránia nos, odstránia jazyk, potom odstránia pažerák, tak to pokračuje, odstraňujú jednu vec za druhou s hroznou bolesťou, viete. Zoberme si napríklad malomocenstvo. Malomocní si necítia prsty, nemôžu ich cítiť, tak ... potkani alebo čokoľvek im zožerie prsty, necítia to, tak strácajú svoje prsty. Takto Ekadeša pojedá ľudí, zožiera.

Ale tento hnev Otca môže byť veľmi jemný a mohol by byť veľmi milý, ak sa jedná o Jeho vlastné deti. Príbeh je o Matke - raz sa veľmi rozhnevala, Prapôvodná Matka. A bola tak nahnevaná, že chcela zničiť celý svet svojimi Ekadeša silami a snažila sa ničiť celý svet. Keď sa dostala do tohoto stavu, tak sám Otec cítil, že je tak trochu príliš nahnevaná. Takže keď začala ničiť a šla hlava-nehlava, nevedel čo má urobiť, tak vzal Jej dieťa, predstavuje to sahadža jogína, môžeme povedať, predstavuje to Krista alebo to predstavuje ktorékoľvek z týchto Jej veľkých detí a položil to dieťa pod Jej nohu. Takže keď dupala, zrazu uvidela svoje vlastné dieťa pod svojou nohou a vyplazyla veľký jazyk. Hneď prestala. Vyvážila sa. Ale toto sa stalo len raz.

Takže po Ekadeša Rudre nakoniec prichádza úplné zničenie cez hnev Sadašivu. Kedy nastane konečné úplné zničenie.

Tak sme videli, ako pracuje Ekadeša Rudra a ako sa sami sahadža jogíni stanú Ekadeša Rudrou.

Na rozvinutie tejto sily si musí človek rozvinúť ohromné sily odpústanosti, silu odpútanosti, odpústanosti od negatívneho. Napríklad, negativity môžu prísť od veľmi blízkych ľudí, ako brat, matka, sestra, môžu prísť od priateľov, môžu prísť od príbuzných. Môžu prísť z krajiny, môžu prísť z politických presvedčení, ekonomických ideí, z čohokoľvek. Každé nesprávne stotožnenie môže zničiť vašu silu Ekadeša Rudry.

Takže nie je postačujúce len povedať: "Som odovzdaný Sahadža joge a som sahadža jogín." Ale musíte tiež mentálne vedieť, čo je Sahadža joga. Tak, že intelektom rozumiete, čo je Sahadža joga. Lebo najmä na západe sú ľudia príliš inteligentní a ak svetlo Sahadža jogy neprenikne do ich inteligencie, nikdy neprekonáte svoje pripútanosti.

To neznamená, že máte o Sahadža joge veľa hovoriť alebo robiť o tom prednášky, ale mentálne by ste mali tiež rozumieť, čo je Sahadža joga.

Dnes je zvláštny deň, keď bolo požiadané, aby sme mali Ekadeša Rudra pudžu a je to kvôli všetkým falošným náboženským sektám a falošným guruom a falošným náboženstvám, ktoré sú nasledované v mene Boha alebo iných nábožestiev, ktoré nehovoria o Sebarealizácii a nedosahujú Sebarealizáciu a nedávajú spojenie s Bohom, všetky sú falošné.

Všetky tieto veci, ktoré sú len vierami a rozprávaním o Bohu, ale nemajú spojenie s Bohom, nemôžu byť pravými náboženstvami. Samozrejme, dávajú ľuďom rovnováhu, ale pri dávaní rovnováhy, ak ľudia žijú z peňazí a snažia sa tešiť bohatstvom z týchto peňazí, tak potom to nie je náboženstvo ani na veľmi nízkej úrovni. Pozrite ako rovnováha, náboženstvo má dávať hlavne rovnováhu, ale ak pri tomto vyvažovaní povedia: "Musíte byť vyvážení, ale dajte mi za to peniaze, musíte mi dať peniaze, dajte mi celú vašu peňaženku, dajte mi všetko." Tak toto nemôže byť rovnováha. Nemá to ani náznak Božieho požehnania. Alebo náboženstvo, ktoré vás núti klaňať sa hocikomu, len nie inkarnácii, tak to nie je náboženstvo. To je ďalšia úplná faloš.

Skutočné náboženstvo vám dá rovnováhu a vždy bude hovoriť o vzostupe. Ale nikdy nebudú pýtať peniaze alebo z niekoho neurobia niečo veľké - uctievaniahodné. Mali by sme sa teda naučiť rozlišovať medzi falošnými, negatívnymi a skutočnými vecami.

Keď si rozviniete toto rozlišovanie cez vibračné vedomie alebo cez vašu inteligenciu, ste pod svojou vlastnou kontrolou. A vtedy sa stanete tou silou Ekadeša, keď si upevníte svoju zrelosť.

Dnes vám všetkým žehnám, aby ste sa všetci stali silou Ekadeša Rudry a rozvinuli si úprimnosť, ktorá vás dovedie do tohoto stavu.

Nech vám Boh žehná!
