Puja de Pascua. Roma Ashram, Italia. 19 de abril de 1987.


¡Feliz Pascua a todos vosotros! Hoy es un gran día para venir a Roma a celebrar la Resurrección de Cristo. Ahora nosotros tenemos que lograr la resurrección de la cristiandad, que se está moviendo justo en la dirección opuesta a la resurrección de Cristo. Como sabéis, Cristo era solo chaitanya y encarnó en un cuerpo de chaitanya. Todo su cuerpo era chaitanya. Y resucitó para mostrar al mundo que vosotros también podéis resucitar, si podéis llenar vuestro cuerpo de chaitanya.

Hay una lucha entre la materia y el Espíritu. Según vemos, en la vida humana, la materia siempre intenta dominar y sustituir al Espíritu. Por esta razón fracasamos en nuestra resurrección. Fracasamos en nuestra resurrección porque le cedemos el paso a la materia. Nosotros venimos de la materia y es muy fácil volver a ella. Todos los países cristianos han seguido un desarrollo material identificándose con la materia en vez de sublimarla.

La razón por la que nos hemos equivocado es que la materia se ha vuelto muy importante para nosotros. Estamos muy identificados con la materia, con nuestro cuerpo, con todo lo que es material para nosotros. La gente está muy preocupada por las cosas materiales. Encuentro que toda la cultura se ha vuelto materialista y aunque la gente está absolutamente avergonzada de ello, aun así continúan de este modo tan vergonzoso y degradante. Esto degrada a los seres humanos.

Cuando vine a Occidente pude ver esta tendencia claramente. Por ejemplo, todo lo que se compra en el hogar se hace pensando en que se venderá después. De modo que, en todo lo que compran, observan que tenga cierta calidad. Si fuese un diamante, tiene que ser un diamante perfecto porque tendrá que ser revendido de nuevo. Si compran una casa, tienen miedo de estropear algo o de decorarla; porque no quieren hacer nada que pueda reducir el precio de esa casa por tener una decoración en particular. Todo es para ser vendido. Nunca gozan de la materia. No hay ningún gozo. Cualquier cosa que compran lo hacen pensando en si podrán revenderlo de nuevo. Esto ocurre incluso con las piedras preciosas. En India todo el mundo puede permitirse tener piedras preciosas, aunque el rico tendrá las más caras y la gente pobre las más sencillas. Lo mismo sucede con la plata, que todo el mundo puede conseguirla. Algunos pueden tener plata 100%, otros tendrán plata un poco mezclada y otros con poco porcentaje de plata. Pero si vais a algún país de Occidente, tiene que tener un sello. Ha de estar certificada. Nadie la compraría a menos que tenga un sello, porque este sello significa que puede revenderse.

Ahora bien, supongamos que compráis algo en India. Aunque, por supuesto, no tienen ningún sello; cuando queréis venderlo de nuevo vais al mercado y ellos saben cuál es el valor intrínseco de esa pieza de plata en particular, y os pagan de acuerdo a él. Pero nosotros no tenemos sellos.

Con el oro ocurre lo mismo. Tienen un oro de nueve quilates con sello. ¿Qué es oro de nueve quilates? No es oro en absoluto. Pero le ponen una marca y así será más caro. Porque no tiene mucho oro, así que, le ponen una marca y lo encarecen. Toda la economía está basada, estúpidamente, en el materialismo. Y no usan la materia para gozar sino para venderla. De este modo no gozan de nada en su vida.

Hoy en día, no sé si incluso el plástico puede revenderse o no; pero he visto que algunas personas son muy particulares, incluso con el plástico, con el acero inoxidable, con todo lo que tienen. Aunque no puede revenderse, han construido su psicología de tal modo que incluso quieren preservar las cosas de plástico, un hilo, un alfiler, cualquier cosa. Quieren preservar cualquier cosa. No quieren tirar nada.

Todas estas cosas nos conducen a la infelicidad, a la frustración y a la estupidez. Y así han formado una anticultura. Esta anticultura no es otra cosa que otra forma de materialismo, es fealdad. Como cuando os pintáis el pelo, así os volvéis anticultura. Si lleváis pantalones con agujeros sois anticultura. Si lleváis ropas sucias sois anticultura. Pero incluso estas cosas son revendibles. Hay muchos mercados donde podéis conseguir estas ropas sucias, "lavadas a la piedra". Todas estas modas vienen de los dos lados o dos aspectos de la actitud materialista de los seres humanos. Y no tienen ninguna vergüenza con el modo en el que piden algunas cosas. Por ejemplo, suponiendo que conocen a alguien que ha olvidado devolverles una cuchara; le telefonearán tres veces para decirle: "¿Tienes tú mi cuchara?, ¿tienes mi cuchara?" No les da ninguna vergüenza, esto no es cultura en absoluto.

En India quizá anteriormente era mejor, pero lo que yo conozco ahora es que en una buena familia siempre se decía: "Si tienes el lápiz de alguien, ten cuidado y devuélvelo. Pero si alguien tiene incluso tu oro no lo pidas, no debes hacerlo porque esto no es signo de buena educación ni es de buen gusto". Pero hoy día toda la sofisticación se ha vuelto materialista. Una locura que está enloqueciendo la mente occidental. Por ejemplo, si tenéis que servir vino, debéis tener diferentes tipos de copas, diferentes tipos de platos, diferentes tipos de cucharas. Tenéis una cuchara para el aguacate y otras para otras cosas. Quiero decir que os podéis volver locos. Y si no hacéis esto los demás se reirán de vosotros. Si vienen a tu casa dirán: "¡Dios mío! ¡Han servido el aguacate con la cuchara del helado!" Este es el peor pecado que uno puede cometer. De modo que toda la idea de lo que es pecado se vuelve materialista y absurda. De este modo, cuando la materia está tan muerta, la resurrección no puede producirse.

Entonces esta materia entra en el cerebro. Cuando entra en el cerebro se pudre ahí. Después empezáis a discutir acerca de ello, digamos de bancos y de cómo ahorrar. Quiero decir que el mantra de Londres debe ser: "¡Ahorra libras!" Tan pronto como llegáis al aeropuerto hay un gran mantra escrito: "¡Ahorra libras alquilando un taxi en Heathrow!" ¡Imaginaos!, y ni siquiera son conscientes de lo que están haciendo. Continuamente, ¡ahorra libras, ahorra dinero, ahorra esto, ahorra aquello! ¿Por qué? Porque están muy frustrados. Todo este asunto de la materia es tan frustrante que tienen que ahorrar dinero para superar esa frustración. Y la frustración la equilibran con drogas: bebiendo vino y toda clase de cosas estúpidas, comiendo queso putrefacto u otras cosas que son absolutamente materia muerta, cosas inútiles que os adormecen y os destruyen.

De este modo escapáis de la realidad. Estáis tan frustrados que queréis tomar algo para contrarrestarlo. Y cuando ven que con esto no han podido conseguirlo se sienten aún más enfadados. Entonces, ¿qué harán después? Si sois tan infelices tenéis que descubrir otra cosa.

Como en la historia que os conté, donde había dos niños que eran traviesos y la madre tenía que salir. De modo que les dijo: "Sois unos niños muy traviesos, así que os voy a encerrar en la cocina", porque en cualquier otro lugar podéis romper algo, estropear alguna cosa y no podré venderla de nuevo. De modo que les dejo en la cocina pensando: "¿Qué pueden romper ahí? Cuando volvió ellos dijeron: "¡Nos hemos comido todas tus hojas de té!" De este modo, cuando se sienten tan frustrados, no saben qué hacer, así que, ponen alfileres en sus orejas, piercing en sus mejillas, alguna otra cosa en su nariz. No saben qué hacer con ellos mismos, de modo que se arrancan los bigotes, se pintan el pelo o hacen todo tipo de cosas estúpidas. Son gente absolutamente frustrada. Pero lo peor de todo, que no se puede entender, es que lo hacen con una gran confianza. No lo hacen con inseguridad sino con una completa confianza. Su atención está siempre pendiente para ver qué tendencia seguir. Si ven un árbol con hojas que se ha quedado muy deteriorado a causa de una mala nutrición, ellos quieren ser igual. Quieren ser gente mal nutrida. De modo que tienen un aspecto miserable, sus mejillas están hacia adentro, las narices hacia afuera. Si los veis, parecen gente enferma. Esta es la señal de que han descubierto un modo de expresar su frustración.

Pero Cristo pavimentó un camino muy diferente. El dijo: "¡Poned chaitanya en vuestra materia, de modo que gocéis de este chaitanya!" ¡Poned chaitanya, vibraciones, en la materia! Este es su mensaje. Él no solo resucitó con su Espíritu, sino que lo hizo con todo su cuerpo. De modo que, habló de la resurrección del cuerpo, de la materia en nuestro interior.

Cuando venimos a Sahaja Yoga la Kundalini se eleva y os da vuestra Realización. Sentís el chaitanya en vuestras manos y a vuestro alrededor. Vuestras caras empiezan a brillar como bellos lotos, vuestra piel mejora, parece que estáis floreciendo. Todo esto está bien pero, aun así, continúan los apegos materiales que pueden ser muy sutiles o muy groseros. Los groseros podrían ser: "Esta es mi alfombra, este es mi coche, esta es mi joya", algo de este tipo. Pero si fueseis del estilo de Cristo tendríais que estar identificados con la materia que esté vibrada, que esté vibrando, que tenga un valor vibracional y no material, un valor espiritual, un valor divino. Podría ser cualquier cosa, podrían ser flores, agua, un sari, un asiento. Podría ser cualquier cosa que tenga este valor. De este modo la atención va cambiando de lo grosero hacia las vibraciones.

Pero, incluso ahora, si tenéis una atención que siempre acecha las cosas materiales entonces os resultará muy difícil ascender rápidamente. Todas las cosas que usáis, ¿son de ayuda para vuestras vibraciones o no? Todo lo que hacéis, ¿es bueno para vuestras vibraciones o no? ¿O seguís acarreando las viejas modas, como la gente loca que vimos ayer? Ellos habían venido de vacaciones y no sabían cómo gozar, intentaban cualquier cosa. Los pobres deben de haber pagado mucho dinero a sus agentes de viaje, a los hoteles, en los restaurantes; pero yo sentía que no estaban gozando en absoluto. Ninguno de ellos estaba gozando, se sentían muy miserables y no sabían qué hacer. Y al final yo estaba pensando que podrían acabar rompiéndose la cabeza de pura frustración.

De modo que la materia nunca puede daros gozo. Solo la materia que está vibrada, que tiene vibraciones, puede daros gozo. Un ser humano nunca puede daros gozo. Puede ser vuestra esposa, vuestros hijos, vuestro padre, madre o cualquiera. A menos que esa persona tenga vibraciones no podrá hacerlo, porque el gozo es la bendición de Dios. Y a menos que estéis conectados con Dios, intentéis lo que intentéis, adquiráis lo que adquiráis, nunca podréis tener gozo. Podríais tener una confianza artificial, como una persona que está frustrada y que trata de mostrar exteriormente: "¡Oh, no! ¡No estoy frustrado! ¡Estoy muy feliz!" Es como estar tenso y decir: "¡Estoy muy relajado!", es justo así.

De modo que simplemente para mantener su imagen podrían decir: "Nosotros tenemos mucha confianza", aunque sean gente sin ninguna seguridad en sí mismos. Son muy débiles. Podrían ser vuestros hijos o cualquier otra persona, cualquier ser humano. Aunque penséis muy bien de esa persona, aunque estéis muy identificados con ella, aunque penséis que es una gran persona, la mejor que habéis conocido, no podrá daros gozo. Pero una persona sencilla, un trabajador, un mendigo, un sadhu sentado en solitario en el bosque, será una personalidad que emite un gran gozo. Puede que hable o que no lo haga, pero será muy apreciado y de mucho más valor que una persona rica, bien situada y adorada por todos. Aquí es donde ha fallado la cristiandad, donde han codiciado ser como reyes. Mi esposo fue a ver al Papa y este fue muy amable con él, porque él es una persona importante en el mundo material. ¡A mí no me verá! ¡O quizá sea yo quien no le vea a él!

Todo el sistema de valores ha de cambiar a un sistema de valores en el cual solo os preocupe vuestro Espíritu. Solo importa el Espíritu. El Espíritu os da la comodidad de un palacio. Os da la dicha de una total protección. Os da el gozo de todas las relaciones de este mundo. ¿Por qué os debería preocupar entonces algo que no es tan bueno como esto? Podéis verlo muy claramente. Si tenéis una visión clara, podéis ver a vuestro alrededor que esta gente parece muy infeliz y miserable corriendo detrás de esto o aquello. Primero eran hippies, después se volvieron punks y ahora se han vuelto caballeros bien vestidos. Van de una cosa a la otra y después a otra, lo cual no les conduce a ninguna parte.

Podéis ver claramente que vosotros estáis lejos de ellos. Estáis en un reino diferente y podéis verlos. De modo que no os acerquéis a ellos. Intentad mostrar esta belleza en vosotros de modo que ellos puedan venir y ver por si mismos que vosotros sois personas resucitadas, que habéis resucitado. El Espíritu siempre está en vuestro corazón, siempre está ahí, observándoos, viéndoos. Pero como ahora la materia que rodea al Espíritu ha sido resucitada, ha sido vibrada, vuestros ojos brillan, vuestra piel brilla, vuestro rostro brilla y parecéis muy hermosos. Esto es la resurrección.

En Sahaja Yoga no hay lugar para la estúpida seriedad. ¿Por qué habríais de estar serios? "¡Oh, tengo que vender mi diamante y me han dicho que tiene una pequeña mancha!" ¿Y qué? Ponéoslo. Toda esta seriedad viene de la materia muerta en vuestra cabeza y, como sabéis, en lo muerto crecen los hongos; y como también sabéis, los hongos producen todo tipo de enfermedades. De modo que manteneos apartados de todo lo muerto. Solamente el chaitanya hace vibrar a la materia y, a menos que estéis conectados con Dios, no podréis vibrar nada. Aquellos grandes santos y profetas, las encarnaciones que vinieron a la Tierra, intentaron decirnos a todos nosotros: "¡Obtened la conexión con Dios!" Todos ellos dijeron lo mismo. Por supuesto yo misma he hecho el trabajo. (Algunos niños se ríen). ¡Eso está bien, lo están apreciando! Y vosotros simplemente tenéis que pensar que esta conexión no debe perderse ni perturbarse, ni deberíais dudar de ella. Fijadla apropiadamente. Entonces nunca la perderéis por ninguna razón como: "mi mujer es así, mi marido asá, mi hermano es de esta manera". Estos son signos de una personalidad muy débil. Si sois una personalidad fuerte, si sois fuertes con estas vibraciones, entonces también haréis fuerte a la otra persona y la traeréis a Sahaja Yoga para darles el néctar de la vida.

De modo que el mensaje de hoy es que tenemos que resucitar nuestra materia, en nuestro interior y en el exterior. Estáis subiendo vuestra Kundalini hacia arriba lo cual está bien. Pero también tenéis que extenderla horizontalmente: a vuestras manos, a vuestros pies, a vuestro cuerpo, a vuestra cara, a vuestro pensamiento, a todas las cosas. Un mantra no es otra cosa que un pensamiento que ha sido vibrado. Cualquier pensamiento que está vibrado es un mantra. Pero para contener las vibraciones se necesita un coeficiente particular. En la vestimenta, en el pensamiento, en cualquier cosa mundana, existe un tipo de coeficiente que hace funcionar las vibraciones. Si este coeficiente no está allí no podréis recibir vibraciones ni tampoco podréis dar vibraciones.

Solo hay dos divergencias una es la izquierda y otra la derecha, no hay demasiadas por lo que es muy fácil eliminarlas. En Italia solo hay dos giros posibles: o hacia la izquierda o hacia la derecha. Del mismo modo, en nuestro interior, si no vais ni a la izquierda ni a la derecha sino que os mantenéis en el centro, sois vibrados y podéis vibrarlo todo. ¡Pero manteneos en el centro, no os vayáis a los extremos!

Incluso en Sahaja Yoga hay gente que meditan como locos durante doce horas. ¿Por qué hay que meditar durante doce horas? Quiero decir, vosotros ya estáis en meditación. O si no, harán de Sahaja Yoga un picnic. De un extremo al otro. Lo que se necesita es pensar: "¡Yo soy el Espíritu y estoy conectado con Dios! ¿Con qué intensidad estoy conectado? ¿Cuánto estoy absorbiendo de ello? ¿Cuánto estoy consiguiendo de ello? Eso es todo. No tenéis que hacer demasiado. Aquellos días en que la gente se rompía la cabeza permaneciendo cabeza abajo o yendo a los Himalayas ya se han acabado. Pero las peculiaridades en el temperamento no son señal de un buen sahaja yogui. Todas las peculiaridades vienen de la materia. De modo que en Sahaja Yoga, una persona peculiar podría ser o bien una persona con bhuts o una persona egoísta. Una de estas dos cosas se da en una persona peculiar. No hay peculiaridades en un sahaja yogui. Hay individualidades pero no peculiaridades.

Esto significa que todo el mundo tendrá la nariz que tenga la cual no cambiará, tendrán los ojos que tengan pero llenos de luz. Del mismo modo en nuestra vestimenta, empezaremos a vestir ropas sobrias pero no pálidas o sucias: "Vestiremos ropas llenas de color porque nosotros estamos llenos de color". En el Sahasrara hay siete colores. Hoy visto de este color, porque en India este es el color de la primavera. Porque todas las flores son amarillas y de color mostaza, que también es amarillo. Por eso en India a este color se le llama el color de la primavera. Hay un día en que visten este color en particular para celebrar la primavera, porque nosotros estamos conectados con la naturaleza.

Hoy hemos recibido un mensaje muy bueno de Nueva York, en el que nos cuentan que han soñado que yo iba a vestir con el color de la primavera. Me gustaría que alguien leyera lo que han dicho y os sorprenderá como coincide con lo que estoy vistiendo hoy. Tan pronto como me puse este sari el tiempo se volvió más cálido, lo cual yo ya sabía que ocurriría. Este es el momento en que empieza el calor y lo siento porque para vosotros es demasiado.

Así pues, hoy es el día en que celebramos la primavera. Como sabéis yo nací en primavera y Cristo resucitó en primavera. De modo que la primavera comienza después de la resurrección de Cristo. Del mismo modo nosotros estamos ahora en un estado de ánimo primaveral, para gozar, para ser felices, para ser dichosos. Pero no para ser frívolos o vulgares, no para ser infantiles. De este modo ha de ser un sahaja yogui. Estoy muy feliz de que con este suceso espontáneo de mi venida a Roma tantos de vosotros hayáis acudido. Esto muestra cuanto me amáis y solo puedo expresar lo que siento con lágrimas en los ojos. Por todo esto Cristo sacrificó su vida. Que Él sacrificase su vida y sufriese tanto fue un acontecimiento terrible. Pero el resultado de aquello es que todos vosotros estáis hoy aquí, vosotros que habéis resucitado; vuestros Agnyas se han limpiado y todo está muy bien.

¡Que Dios os bendiga!