Brahmapuri Puja. Brahmapuri (Indie), 30 Grudnia 1989.

Przykro mi z powodu tego, co się wczoraj stało, ale myślę, że rozpoczęła się wojna między złem, a dobrem i mimo wszystko dobro zwycięża.

W dzisiejszych czasach zło dominowało nad dobrem, ale teraz, w tej Krita Judze zło zostanie całkowicie pokonane przez dobro, i nie tylko to, ale dobro będzie szerzyło się wszędzie. Zło może posunąć się do skrajności, a następnie całkowicie wypaść z procesu ewolucyjnego. Ponieważ oni są ślepi, nie widzą dobra, dlatego są źli. Gdyby mogli zobaczyć dobro, porzuciliby swoje zło. W naszym kraju, który jest krajem jogi, zwłaszcza Maharasztra, która jest krajem świętych, byłam zdumiona, słysząc, co robią ludzie. Jednym z prawdziwych źródeł tych nonsensów wydaje się być Rajneesh, okropny facet, ponieważ zrobił tutaj wystawę, całkowicie potępiając wszystkie bóstwa i mówiąc wszelkiego rodzaju sprośne rzeczy. Myślę, że gubernator tego miejsca również mu w tym wtóruje i wszyscy próbują udowodnić, że nie ma Boga, nie ma duchowości. Chcą dowieść, że nauka jest wszystkim. W Indiach nie mamy dziedzictwa naukowego, mamy duchowe dziedzictwo. To znaczy, nikt nie jest znany jako wielki naukowiec w tym kraju.

Nikt nie dokonał żadnych wyjątkowych odkryć, a sposób, w jaki ludzie to organizują w imię nauki, sprawia, że mało kto zrobił coś w nauce. Więc to zło przybrało tę nową formę mówienia o nauce i potępiania Boga. Oczywiście na Zachodzie w dużej mierze wydarzyło się to samo, ale nie w aż takim stopniu. Nie odrzucili wszystkiego, co duchowe. Ale tutaj poszli na oślep, ci nieliczni ludzie, którzy tam są, bardzo, bardzo nieliczni, ale oni tam są. Więc to jest bardzo zły wzrost w tym kraju, nie przetrwa, wiem, nie przetrwa, bo ten kraj jest przepełniony duchowością. Na Zachodzie, ponieważ ludzie zajęli się nauką, stracili całą kulturę społeczeństwa. Nie ma kultury społecznej. Etykiety ograniczają się do widelca i łyżki lub sposobu składania sobie życzeń. Nie ma innej kultury.

To jest takie zewnętrzne, tak naprawdę nie ma nic głębokiego. Ponieważ całkowicie poszli w nowoczesność albo można powiedzieć, że jest to industrialna ewolucja ludzi, skierowali się ku temu i stracili kontakt z rzeczywistością. Kultura każdego kraju może przetrwać wyłącznie dzięki duchowości. Nauka nie może o tym mówić i ma tak wiele ograniczeń, że nie potrafi odpowiedzieć nawet na kilka prostych pytań, które przed nią stoją. Przede wszystkim oni nie mają pojęcia, czym jest miłość, nie mają pojęcia, czym jest Wszechprzenikająca Moc. Wy wszyscy to poczuliście i teraz wiecie, co to jest i wiecie, jak tego używać. Zatem, w tych okolicznościach stwierdzam, że ci ludzie, którzy są przeciętni w Sahadźa Jodze, nie mogą wiele pomóc w ustanowieniu dobroci. Musicie być bardzo czyści wewnątrz siebie, musicie być bardzo potężni wewnątrz siebie i musicie być niezwykle wrażliwi. Nie powinniśmy więc marnować naszej energii, naszej uwagi na powierzchowne i bezsensowne sprawy. Musimy się z tego wydostać i stać się ludźmi odwiązanymi, odwiązanymi od wszystkiego, co stwarza problemy.

Jeśli spojrzycie na wszystko z dystansu to będziecie mieli życie, które będzie odżywiać wasze społeczeństwo, a które jest teraz chore, jest chorym społeczeństwem, jest społeczeństwem dekadenckim. A dla tego dekadenckiego społeczeństwa potrzebujecie ludzi, którzy są bardzo silni moralnie, którzy są niezwykle czyści i którzy wiedzą wszystko o Sahadźa Jodze. Na zachodzie przeciętność w Sahadźa Jodze jest bardzo powszechna, bardzo powszechna. I są tak bardzo zaangażowani w swoje osobiste problemy że nie mogę zrozumieć, jak wzniosą się ponad ten bezsensowny, osobisty punkt widzenia. Trzeba więc zdać sobie sprawę, że całe drzewo, które tak bardzo wyrosło na zewnątrz z powodu rewolucji przemysłowej, musi szukać swojego odżywienia w duchowości, która jest w Indiach. Bez wątpienia. Duchowość bez rozwoju nie ma znaczenia. Duchowość musi rozwijać się na zewnątrz, inaczej przepada w Matce Ziemi. Musi wykiełkować i ukazać rezultaty, które bez wątpienia pokazujemy. Na tak wiele sposobów indyjscy Sahadźa Jogini próbują to pokazać, chociaż są w tym raczej powolni.

Więc to jest coś zabawnego, że na Zachodzie ludzie są raczej powolni, Sahadźa Jogini są raczej powolni w swojej duchowości, a w Indiach ludzie raczej powoli manifestują się na zewnątrz. Dopóki naprawdę się do tego nie przyłożymy, to się nie uda. Mam więc nadzieję, że skoro rozesłaliśmy listy, że przybyliśmy tutaj nie dla zabawy, ale dla poświęcenia i dla naszego wzrostu i że jest to pielgrzymka. Oczywiście gadulstwo, rozmowy o drobiazgach, przegadywanie się czy kłótnie w ogóle nie wchodzą w rachubę. Ale dominacja, straszna dominacja fałszu, tylko po to, by pomyśleć, że jesteście liderami, albo "Dlaczego on jest liderem?" pokazuje, że nie jesteśmy jeszcze godni. Tak więc wartościowość statku jest bardzo ważna, jeśli ma walczyć z turbulencjami na morzu. Jeśli nie może walczyć z turbulencjami morza, to zdecydowanie nie nadaje się do żeglugi i jest absolutnie bezużyteczny, ponieważ nie może przepłynąć. W ten sam sposób, jeśli musicie być kimś, musicie to wypracować w taki sposób, abyście naprawdę stali się godni przekroczenia tego oceanu iluzji i aby wielu mogło przejść z wami. Tak jak w Indiach, oni założyli centrum (SY) w każdym domu, w każdej rodzinie, w każdym miejscu.

Jeśli zapraszają ludzi to nie rozmawiają o niczym innym, tylko o Sahadźa Jodze. Teraz wszędzie możecie o tym mówić, daję wam pozwolenie, abyście im powiedzieli, że przybyłam, nie ma nic do ukrycia. Musicie iść i otworzyć drzwi wielu kościołów, wielu świątyń i wielu organizacji i powiedzieć im, że przybyłam. Nadszedł już czas, widać to tak wyraźnie, to takie oczywiste. Wcześniej mawiałam: "Nie poszłabym do gazet, to jest niedobre, tamto jest niedobre, wypracujmy to". Ale nadszedł już ten czas, do tego stopnia, że muszę powiedzieć pewne rzeczy i zrobię to, bardzo otwarcie powiem to wszystko. Ale chcę, żebyście wszyscy byli tacy żeby nikt nie wskazywał na was palcem, żeby powiedzieć: "Och, to jest Sahadźa Jogin. I jak ten Sahadźa Jogin się zachowuje". Jeśli ktoś jest głupi i nie wypracowuje tego, lepiej się pozbyć takiej osoby. Albo pomóc tej osobie i powiedzieć jej: "Musisz się wznieść.

Nie możesz tu być, nie chcemy tu przeciętnych ludzi. Chcemy bardzo niezwykłych, czystych ludzi". Czystość jest najważniejszą kwestią, który musimy mieć. Kiedy jesteście czyści, nie musicie się martwić, wtedy Ja się wami opiekuję. Ale czystość umysłu, czystość serca i czystość waszej uwagi, te trzy rzeczy są bardzo ważne. Kiedy to się wypracuje, będziecie zaskoczeni, w jak krótkim czasie kolektywność wzrośnie". Jest również ciągle tendencja wśród Sahadźa Joginów, by wracać do dawnego materializmu i dążyć do posiadania własnego domu, własnej rodziny, własnych dzieci - tego rodzaju nonsens. Musimy żyć w aszramach i musimy to wypracować, musimy to wypracować bardzo pięknie, żebyśmy wszyscy umieli żyć wspólnie w aszramie. Ale widzę, że ludzie nadal nie mogą tego wypracować w ten sposób. Są bardziej zajęci swoją pracą, zaabsorbowani swoimi sprawami.

Jeśli zamieszkacie w aszramie, to Ja dopilnuję, żebyście mieli wszystko pod dostatkiem. Ale jeśli nie chcecie dostać błogosławieństw od Boga, to jak ktokolwiek może wam pomóc? Potrzebne jest więc ogromne poświęcenie. Oczywiście, jak wiecie w Sahadźa Jodze w cale nie potrzebuję od was żadnych pieniędzy, ale poświęcenie jest bardzo ważne i poświęcenie bezsensownych pomysłów, które macie. W każdy możliwy sposób musimy pokazać, że jesteśmy Sahadźa Joginami. Sposób, w jaki się ubieracie, sposób, w jaki żyjecie, sposób myślenia, sposób, w jaki się zachowujecie sposób, w jaki utrzymujecie relacje między sobą sposób, w jaki prowadzicie życie małżeńskie i sposób, w jaki wychowujecie swoje dzieci. Dopóki nie osiągniecie czystości, to światło miłości nie będzie świecić, światło miłości nie będzie świecić. Musicie wchłaniać światło miłości do wewnątrz. Ale nie umiecie, dopóki nie staniecie się czystą osobowością. A ta czysta osobowość musi się rozwijać poprzez waszą medytację, ciężką pracę, to kwestia kilku lat.

W przeciągu dziesięciu lat możemy zmienić cały świat, za dziesięć lat. Ale musicie być naprawdę bardzo oddani. To wy musicie się zmienić, nie Ja. To wy musicie to wypracować, nie Ja. Osiągnęłam swój poziom najlepiej, ale w ciągu dziesięciu lat powinno być możliwe, że każdy Sahadźa Jogin stanie się potężną siłą Sahadźa Jogi. Więc proszę, starajcie się unikać wszystkich tych, którzy są przeciętni. Jeśli napotykacie przeciętność, to liderzy muszą zrobić wszystko, aby ich skorygować, wszyscy, aby ich zbesztać. Nie toleruj. Nie musicie być bardzo łagodni w tej kwestii. Musicie im powiedzieć szczerze, że: "Widzisz, jesteś wyjątkowo przeciętną osobą dla Sahadźa Jogi.

To nie jest przeznaczone dla miernych. Nie jest przeznaczone dla durnowatych ludzi, nie jest przeznaczone dla głupich ludzi, jest przeznaczone dla tych, którzy są gotowi poświęcić wszystko w imię prawdy". Ci ludzie mówią, że: "Dlaczego nie pójdziesz drogą nauki?" Ja mówię: "Dlaczego nie pójdziesz drogą prawdy?" Zwróć się ku prawdzie. Nauka jest nie prawdą. Dzisiaj może się tak wydawać, ale jutro już nie. Dzisiaj możesz myśleć, że to prawda, ale każda hipoteza jest kwestionowana, każde prawo jest kwestionowane, to nie jest żadne prawo. Musicie używać Sahadźa Jogi w praktycznym życiu, wszędzie. Ale w żadnym wypadku nie możecie być fanatyczni.

Tak jak widziałam, że niektórzy ludzie zaczynają dawać wibracje lub zaczynają zakładać sobie bandhan, mimo że Ja tu jestem, to oni tak robią. Nie ma w tym miejsca na głupotę, to musi być bardzo dostojne, stosowne i przyzwoite. Ale by tak było to naprawdę potrzebujemy wartościowych ludzi. I muszę powiedzieć, że potrzebna jest całkowita posłuszność. Powiedziałam wtedy Hindusom, że muszą się odpowiednio zająć tą sprawą. Ale oni po prostu nie posłuchali Mnie wtedy, powiedzieli: "Matko, dlaczego tak chcesz, wiesz, będziesz wtedy miała kłopoty i tak dalej". Gdyby Mnie posłuchali to nie byłoby dzisiaj kłopotów. Musicie Mnie słuchać, co mówię, a nie dawać Mi wymówki, ani logiki, Ja wszystko wiem i wy o tym wiecie. Ja wiem wszystko. Teraz mamy dla was coś miłego, jest to lista małżeństw.

Ale małżeństwo nie jest tak ważną rzeczą, jak wam się wydaje. To nie jest aż tak ważna dla was sprawa, żeby poświęcać temu całą swoją uwagę. To jest tak przy okazji, bo trzeba mieć małżeństwo, to dlatego. Czasami nawet nie ma takiej potrzeby. Ale musicie to mieć, tylko że potem listy za listami o waszych małżeństwach, o waszych dzieciach, Ja już po prostu nie chcę tego czytać. Nic o Sahadźa Jodze. Jeśli jesteś odwiązany, to bez względu na to jakie jakości ma twoja żona, ty nie upadniesz, bez względu na przymioty twojego męża nie upadniesz. Więc powinniśmy się bardziej przejąć tym czym my się zajmujemy, co my robimy? Co osiągnęliśmy? Co damy światu?

Dla Mnie jesteście moimi instrumentami. Nie muszę nikogo innego prosić. Jesteście moimi instrumentami i musicie to wypracować. Nie jesteście dla Mnie bezużytecznymi ludźmi, bardzo ciężko z wami pracowałam, bardzo ciężko. Więc proszę, nie marnujcie także moich energii i pod każdym względem starajcie się być bardzo dobrymi Sahadźa Joginami, powinniście być oddani we wszystkim, pod każdym względem starajcie się być kimś o wspaniałych cechach. Widzieliście, jak teraz ludzie stają się agresywni i ta przemoc trwa. Oczywiście to może nie trwać dalej, ale jest to jeden ze znaków, że musimy być przygotowani aby być bardzo silnymi ludźmi, bardzo silnymi i jestem pewna, że to się wypracuje. Rzucili około 400 kamieni, co najmniej, może więcej według raportu policyjnego i bardzo niewiele osób zostało rannych. Co to znaczy? Że jest ktoś, kto unika tych wszystkich problemów.

Jeśli chodzi o naszą dalszą trasę, to teraz zdecydowałam, że nie pojedziemy do Atith, ponieważ tam jest – komisarz, ESP powiedział mi, że lepiej tam nie jechać, to bardzo – ci ludzie są bardzo źli i są przestępcami. Zatem, dopóki nie nadejdą wybory, oni będą zachowywać się w ten sposób. Po wyborach oczywiście zostaną stłumieni. Więc należy się zachować ze zrozumieniem aktualnej sytuacji i pojechać bezpośrednio do Sangli, więc pojedziemy do Sangli, tam będziemy mieli pudżę, można zrobić zakupy, czy cokolwiek chcecie, a stamtąd pojedziemy do Ganapatipule. Ale tu nie chodzi o zabawę, to nie jest zabawne. To jest nasz rozwój. W przeciwnym razie wrócicie z Indii tak samo jak przyjechaliście, z pustymi rękami. Chcę, abyście wszyscy byli nadzwyczaj aktywni we własnej sferze życia, rozmawiajcie o Sahadźa Jodze. Musicie nosić moje broszki, musicie nosić moje pierścionki, musicie nosić moje wisiorki, żeby ludzie pytali: "Kto to jest?" Wtedy powinniście odpowiedzieć: "Ona jest Duchem Świętym".

Możecie powiedzieć: "Uważamy, że jest Duchem Świętym". Zobaczmy, co się stanie. Zatem to jest poważna sprawa, czułam, że muszę z wami porozmawiać, i że musimy być bardzo, bardzo ostrożni, jeśli chodzi o to, jak na siebie patrzymy. Musimy być świadomi, musimy być świadomi siebie i tego, co się dzieje. Mówiłam wam to wiele razy, musimy być świadomi tego, kim jesteśmy i co się dzieje. Ale jeśli wasza praca zawodowa jest ważna, wszystko inne jest ważne, to jak zamierzacie wypracować Sahadźa Jogę? Więc musi być świadomość, a wraz z waszą świadomością światło się rozprzestrzeni. Ale nie jest ciche, musicie o tym mówić. Potrzebna jest elokwencja, to musi być elokwentne, całe wasze światło musi mówić, światło musi mówić, światło musi się wyrażać i to musi być zrobione z całkowitą pewnością. Zobaczmy teraz czy po odbyciu tego touru, do jakiego stopnia ludzie będą w stanie ustanowić nowe rzeczy.

Jak dotąd, według Mnie, 50% Sahadźa Joginów na Zachodzie jest nadal dość przeciętnych, a 25% z nich jest tylko po to, by coś na tym skorzystać. Robią to tylko dlatego, że mogą dostać coś za darmo. 25% ludzi jest takich. To bardzo smutne, ale tak jest. Muszę powiedzieć, że Hindusi to biedni ludzie, nie zrobiliby nic takiego, nie braliby czegoś ode Mnie tylko dlatego, że to jest za darmo, nic takiego. Nie zrobiliby, oni bardzo samych siebie szanują. I to właśnie musimy rozwijać, ten szacunek do samego siebie. Tak jak z Moim domem w Hounslow, wszyscy tam przychodzili i mieszkali bez opłat. Teraz mamy dom w Shuddy Camp, do którego schodzą się ci wszyscy, którzy nie mają pracy, przychodzą tam mieszkać. To taka niedorzeczna sytuacja.

Więc boję się nawet założyć jakikolwiek aszram w Londynie, ponieważ zacznie się to samo. Jeśli mogą skorzystać, to będą chcieli tam być. Nawet łyżkę, chcieliby w ten sposób nosić. Uważam, że to bezczelne zachowywać się tak będąc Sahaja Joginem. Musimy mieć pełen szacunek do samych siebie i musimy zrozumieć, że musimy się poświęcić, żeby coś z tym zrobić. Ponieważ to jest ostatni etap [touru], można rzec, kiedy mówię wam o tych wszystkich rzeczach i w tej pięknej atmosferze, tu, nad brzegiem rzeki Kryszny, musimy zrozumieć, że rzeka płynąc, wydaje dźwięk, wydaje dźwięk, aby pokazać, że ona - istnieje. Ale my nie jesteśmy tylko rzekami, jesteśmy pasmami górskimi, rzekami, jesteśmy każdą częścią wszechświata. A nasza manifestacja jest jak wielkie nic, jakby Matka Ziemia została opustoszona. Nadszedł czas, abyśmy się przyjrzeli samym sobie, abyśmy zobaczyli siebie, co jest z nami nie tak. To bardzo ważne.

Musiałam to powtarzać raz za razem, ale nie lubię mówić takich rzeczy, ponieważ tak bardzo was kocham i bardzo Mi na was zależy, a wy również Mnie kochacie. Ale kochanie Mnie nie wystarczy, musicie kochać siebie i szanować siebie. Tylko wasza Jaźń to wypracuje. Jak powiedział Shivaji Maharaj: "Swa-dharma rajya" "Musisz rozwijać religię swojego Ducha". To, co musimy zrobić, to rozwinąć religię naszego Ducha. A kiedy to się stanie, możemy całkowicie wyzwolić cały świat. To jest nasza praca, a jeśli nam się nie uda, to jest to odpowiedzialność Sahadźa Joginów i nikogo innego. Zatem, mówię każdemu z was, że to nie Ja muszę was zadowalać, to wy musicie zadowolić Mnie. Ludzie reagują na drobne rzeczy, czują się źle z powodu błahostek. Jeśli nie uśmiecham się do kogoś, to on czuje się źle.

O małe sprawy, o drobnostki czują się źle i reagują. Jeśli coś powiem, reagują. Więc jak cokolwiek może do was dotrzeć? Jeśli to jest taka wypukłość, to jak to przyswoicie? Ważne jest, abyśmy starali się przyjmować to z pokorą, ze zrozumieniem. Jesteście Sahadźa Joginami, wiecie, że jestem Adi Shakti, mieliście zdjęcia, wiedzieliście, że jestem Adi Shakti. Ale jak wiele potrafimy wchłonąć? Ile przyjmujemy do środka? Ta praca to znacznie więcej, niż musiała wykonać którekolwiek z inkarnacji. To znacznie więcej niż Chrystus, znacznie więcej niż Rama, znacznie więcej niż Śri Kryszna.

Więc stwórzcie pośród siebie tak wspaniałych ludzi. Ponieważ chodzi tu o to, że Ja mam tę moc, ale to wy musicie mieć zdolność wchłaniania, tę przyjmowalność. Ale jeśli uganiacie się za czymś bardzo tanim i bardzo frywolnym, to jest to niemożliwe. Musicie prosić o swoją głębię i musicie przyjąć to, czym emituje Moja istota. Mam nadzieję, że teraz wszyscy potraktujecie to poważnie. Medytujcie każdego poranka, niezależnie od godziny. Każdego poranka musimy medytować i musimy dopilnować tego, że gdy skończymy naszą prace wieczorem, to wtedy też zrobić przynajmniej małą medytację przed pójściem spać. Bez medytacji nie możecie się rozwijać i dlatego bez względu na wszystko musicie wiedzieć, że rano trzeba wstać i zrobić medytację zanim zajmiecie się waszą pracą. W ciągu dnia, jeśli chcecie, możecie chwilę odpocząć. Teraz jesteśmy w takim miejscu, że mamy czas by chwilę odpocząć, ale rano trzeba wstawać niezależnie od tego, o której poszliście spać.

Musicie trochę przezwyciężyć wasz sen, on daje wam dużo letargii. Nie wydaje mi się, że zeszłej nocy położyłam się spać przed godziną trzecią czy coś w tym stylu, a potem cały dzień byłam zajęta pisaniem raportów, tym, i tamtym. Jeśli Ja tak potrafię w tym wieku, to wy tym bardziej powinniście sobie poradzić z czymś takim. Nie mamy czasu na spanie, nie mamy czasu na dyskusje, kłótnie czy jedzenie. Mamy tylko czas na medytację, to wszystko. Życzę wszystkim, abyście przyswoili moje słowa i zrozumieli je, nie reagując na nie. Proszę nie reagujcie. Nie myślcie: "Matka próbuje cię skarcić". Nie. Próbuję pomóc wam się rozwijać, w ten sposób czasami wzrastacie bardzo szybko.

Więc martwię się tylko o wasz wzrost o nic więcej. Niech Bóg błogosławi was wszystkich. Bardzo podobało Mi się, jak śpiewaliście wszystkie te piosenki i jak wyraziliście siebie.