21 diciembre 1986
Devi Puja
Chalmala, Alibag (India)
Shri Mahadevi Puja: "Puja de bienvenida". Chalmala, Alibagh, India. 21 de diciembre de 1986.

Me inclino ante todos los sahaja yoguis. En este hermoso lugar, en estos parajes, muchos de vosotros os estaréis preguntando por qué Dios ha creado estas cosas tan bellas. Porque teníais que venir a esta Tierra y disfrutar de la belleza. Esa es una de las razones. Y ahora Dios se siente repleto de gozo, satisfacción y de algo parecido a la culminación de su deseo. ¿Por qué Dios ha creado este hermoso Universo?, ha sido una pregunta formulada durante miles de años.

La razón es muy sencilla de entender. Así como la belleza que se crea no puede verse a sí misma, tampoco Dios -que es la fuente de la belleza, de toda belleza- puede ver su propia belleza. Así como una perla no puede entrar en sí misma para ver su belleza, ni el cielo puede comprender su propia belleza, ni las estrellas pueden ver su propia belleza, ni el Sol contemplar su propia brillantez; de la misma manera, Dios Todopoderoso no puede contemplar su propio Ser, necesita un espejo. Y así es cómo Él ha creado este hermoso Universo a modo de espejo. En este espejo ha creado cosas bellas como el Sol. El Sol también necesita ver su propio reflejo y por eso ha creado estos hermosos árboles para ver cómo, cuando Él brilla, los árboles crecen maravillosamente y muestran todo su verdor.

Luego, ha creado las aves que se levantan por la mañana temprano y saludan al Sol, y así el Sol sabe que sí, que Él está ahí, que existe. También ha creado preciosos lagos para que los árboles puedan ver su reflejo y los lagos puedan percibir su existencia cuando las ondas de las olas se empiezan a mover en ellos. Y entonces creó al ser humano. Los seres humanos tampoco pueden ver su propia belleza, su propia gloria, y es por eso que viven en la oscuridad, son ignorantes, no pueden ver lo que subyace en su interior. Por eso persiguen cosas que van absolutamente en contra de sí mismos, cosas horribles, autodestructivas. La lucha por alcanzar la realidad es tan fuerte, que como resultado se destruyen a sí mismos. Como algunas personas, que han empezado a consumir drogas y han adquirido toda clase de malos hábitos. De este lugar se dice que hay mucho contrabando y que la gente asume toda clase de riegos porque desconocen que son seres preciosos

Así que, ahora hay que crear un espejo para ellos, para que vean por sí mismos lo hermosos que son. Su espejo es su Espíritu y -ese Espíritu- tiene que llegar a su conciencia, a su atención. Si llega a su atención, entonces pueden ver su propia imagen. Ahora bien, esta atención que surge como atención iluminada, en sánscrito se llama Chidabhas, que es la expresión de la atención que está iluminada. Pero también se dice que tiene una naturaleza muy transitoria o, digamos, que se desvanece a cada momento. Cuando esto ocurre, ¿qué se puede hacer? Para eso tenéis que recobrar el equilibrio a través de la meditación, escuchando charlas iluminadas, viendo las cosas buenas de la vida sin pensar en ellas, viendo también lo bueno que hay en los demás, y entonces empezáis a ver también lo bueno que hay en vosotros mismos.

Por eso siempre digo que no hay que sentirse culpable, porque os sentís culpables de algo que es totalmente ilusorio. Os sentís culpables por tener sombra, algo así es lo que sucede. Así que, si sois conscientes de que sois unos seres preciosos y que tener una sombra no tiene nada que ver con vosotros y con vuestra belleza, si podéis ver vuestra propia belleza, entonces os sorprenderá ver que dentro de nosotros residen todas esas cosas bellas tan dichosas que vemos fuera; lo único es que ahora el espejo no está bien. Por eso debéis observar la naturaleza y la belleza. Pero cuando sois uno con vuestro Ser, entonces veis toda esa naturaleza en vuestro interior, todas las cualidades gozosas de la naturaleza en vuestro interior. Y por eso quería que vinierais a este lugar, para que vierais cómo Dios ha creado este hermoso paraje para que disfrutéis y estéis aquí.

Que Dios os bendiga.