5-ty Dzień – Navaratri, Niewinność i Oświecona Wiara, 09.10.1994 Cabella, Włochy

Dzisiaj zamierzamy spełnić Puję Navaratri. Wczoraj widzieliście piękny opis Navaratri i to, w jaki sposób Matka Bogini stworzyła wszelkiego rodzaju moce w was. To nie jest tak, że tylko Ona ma moce, ale wy wszyscy macie moce. I wszyscy możecie to wypracować. Wszyscy możecie odkryć, czy są te moce czy ich nie ma. 

Dla nas Realizacja jest bardzo ważna, ale to Kundalini dała wam tę Realizację. Oczywiście, Kundalini jest częścią, można powiedzieć odbiciem Adi Shakti i także Jagadamba jest również częścią Adi Shakti. 
Ona jest umieszczona pośrodku obu serc, gdzie jest bardzo ważny punkt. Wszystkie te moce są umieszczone w tej czakrze. Możecie więc sobie wyobrazić, jak wiele tych mocy musi tam być. I Jej moce wyrażone są poprzez centralne serce we wszystkich Ganas, które macie wokół waszego ciała. 

Te Ganas dają wam ochronę, dają wam sen, dają wam energię, dają wam błogosławieństwa i wszystkie pracują cały czas. I te ciała są niezwykle oddane i cały czas połączone z Matką Ambą, którą możemy nazwać Jagadambą. Ona jest Matką Wszechświata. Możecie zatem wyobrazić sobie, jak bardzo Ona musi być zajęta troszczeniem się o cały Wszechświat. 

Kiedy to centrum staje się słabe, to oznacza, że Jej połączenie z Ganas jest ograniczone. Ganas także są słabe i wszystkie moce, z których można byłoby skorzystać, nie mogą być użyte z powodu tej słabości. Jest to bardzo subtelne centrum, bo jest to centrum Matki. Nie jest możliwe, aby zrozumieć miłość matki. Jest to absolutnie niemożliwe. Kiedy dziewczęta wychodzą za mąż i zostają matkami, to dopiero wtedy zaczynają rozumieć, ile ich matka musiała zrobić, aby je wychować. 

W taki sam sposób, kiedy Sahaja yogini stają się dobrymi Sahaja yoginami, jak Ganas, to uświadamiają sobie, jak wiele cierpliwości muszą mieć Ganas, jak wiele muszą mieć miłości i inteligencji, żeby walczyć z negatywnością. Tak więc wszystkie moce Jagadamby działają w kierunku uderzenia w negatywność wszelkiego rodzaju. Pierwszą i najważniejszą istotą Jej natury jest zniszczyć całą negatywność, która jest na tym świece, a która jest przeciwko Sahaj, przeciwko wam. Jej destrukcja ma miejsce na bardzo wiele sposobów.

Przede wszystkim, musimy wiedzieć, że jeśli popełniacie grzech przeciwko Bogini, wtedy zaczynają się wszelkiego rodzaju problemy fizyczne, takie jak choroby psychosomatyczne, wszelkiego rodzaju takie jak rak, AIDS, wszystkie    z nich. Ale niektóre choroby są także związane z Ganapati. Ganapati jest Panem wszystkich Ganas. Zatem Matka ma Ganapati i Ona kontroluje wszystkie Ganas poprzez swojego syna Ganapati. Jest to tak połączone. Zatem, kiedy popełniamy grzech przeciwko Matce, tzn. wtedy, kiedy stajemy się niemoralni. Niemoralni oznacza, że zaczynamy wchodzić w sprawy, które nie są dozwolone przez Dharmę. Cokolwiek jest dozwolone przez Dharmę, jest legalne. Teraz wy ludzie rozumiecie Sahaj dharmę od wewnątrz, od urodzenia, Ja nie musiałam wam tego mówić. 

Teraz wiecie, to co jest złe, jest złe, a to co jest dobre, jest dobre. Więc, kiedy próbujecie czynić wszelkiego rodzaju rzeczy tego typu, ponieważ jest Matką, Ona niewątpliwie ukaże was po jakimś czasie. Ale kiedy popełnicie grzech przeciwko Ojcu taki jak samochwalstwo, gadatliwość, okrucieństwo, surowość i tym podobne zachowania, to wtedy natychmiast pojawia się kara. Ale jeśli chodzi o Nią, o Tę, która jest Oceanem Miłosierdzia - to kara jest bardziej odwlekana. 

Tak więc taka osoba dostaje pełną szansę, aby mogła się poprawić i lepiej się prowadzić. Ale kiedy kara zaczyna działać, to chorujecie na choroby, które mają bardzo poważną naturę. 

To pochodzi z tego, co nazywamy lękiem. Kiedy ktoś was straszy albo zachowuje się wobec was agresywnie, można powiedzieć wtedy, kiedy staje się jak komar, to ten który jest gnębiony poprzez ludzi agresywnych albo grożą mu, zastraszają go, to taka osoba zaczyna tracić wiarę w moce Matki. I w rezultacie taka osoba... Tak więc należy troszczyć się o to Centralne Serce. Jeśli ktoś odczuwa strach, lęk to jest wyrzucony na lewą stronę, z dala od Matki, ponieważ Ona jest tą, która daje nam wiarę w siebie, która daje nam odwagę i męstwo. Ale jeśli jesteście wystraszeni albo pod wpływem lęku, to także możecie zostać wyrzuceni na lewą stronę. I możecie zachorować na wszelkiego rodzaju choroby, które są bardzo poważne i są nieuleczalne, jak oni to nazywają. 

Inną sprawą jest, kiedy jesteście prowadzeni poprzez własne zmysły w różne sprawy, które nie są dharmiczne,         to także można powiedzieć, że jesteście wyrzucani z tej centralnej ścieżki na lewą stronę, bo nie jesteście godni być    u lotosowych stóp swojej Matki. To centrum jest takie, że kiedy odczuwamy strach, to mostek zaczyna drgać i jak urządzenie zdalnie sterowane informować wszystkie Ganas, że nadchodzi atak. Ale kiedy celowo kierujecie się na lewą stronę i pobłażacie sobie, to one nie przejmują się tym. Mówią: "Dobrze, dalej, rób co chcesz, zachowuj się jak chcesz". Te wszelkiego rodzaju ruchy w kierunku lewej strony oddalają was od waszej Matki. 

Opowiem wam historię o kimś w Ameryce. On jest bardzo starym hinduskim Sahaja yoginem. Wyszedł ze swojego sklepu, w którym pracował, wsiadł do samochodu i zastał w nim mężczyznę ze sztyletem i ten mężczyzna ugodził go w środkowe serce. On zaczął krwawić. Powiedział: "Matko, nie wiem, co mi się stało. Taka siła we mnie wstąpiła, złapałem go i zacząłem z nim walczyć, zabrałem mu sztylet. On miał rękojeść a sztylet został w moim ręku i tamten mężczyzna uciekł. Ale wciąż nie martwiłem się moim krwawieniem. Co zrobiłem? 
Zawołałem mojego kolegę, który właśnie wychodził z samochodu i pobiegłem za nim, on wziął mnie do samochodu i pół godziny zajęło nam szukanie tego mężczyzny". Oni nie poszli na policję. Później oni przybyli na policję. Policjanci byli zaskoczeni - koszula była cała we krwi. On powiedział: "Nikt nie uwierzyłby" nawet policja była zaszokowana. "Pół godziny szukałeś tego mężczyzny, dlaczego nie poszedłeś na policję?" On powiedział: "Przyjście zajęłoby nam pół godziny, więc pomyśleliśmy, że lepiej zrobić to samemu". Zauważcie, jaka odwaga. Potem oczywiście zabrano go do szpitala i był w porządku. Tylko go zszyli. 
Teraz on jest zdrowy. To jest oznaka osoby, która nigdy nie zachoruje na jedną z tych strasznych chorób, ponieważ  w jego umyśle nie ma żadnego rodzaju lęku. On jest Hindusem. Powiedział: "Nigdy nawet nie uderzyłem swoich dzieci, nigdy z nikim nie walczyłem, nie jestem zapaśnikiem w żadnym wypadku, nic z tych rzeczy. Ale to się wydarzyło". I on powiedział: "Nie wiem jak, skąd wziąłem tę Shakti [siłę] i jak to zrobiłem, ja po prostu tego nie wiem". 

Jest bardzo wiele historii tego typu, oni mogą wam opowiedzieć o Sahaja yoginach i o wielu świętych, jak oni nigdy nie bali się zaatakować kogoś, kto ich atakował lub ochronili siebie przed wszystkimi strasznymi rzeczami, dzięki swojej odwadze. To jest coś, w co można czasami i nie wierzyć, ale to dzieje się codziennie i otrzymuję listy od ludzi, jak oni byli odważni. Jeśli macie wiarę w Boginię, to wiecie, że Ona jest niezwykle potężna, bardzo inteligentna i jeśli ma was ochraniać, to będzie ochraniać was w taki sposób, że nawet nie będziecie wiedzieć, w jaki sposób byliście chronieni. Ale należy rozwinąć tę wiarę. 

Tę wiarę należy rozwinąć także poprzez doświadczenie, w jaki sposób zawsze byliście chronieni, w jaki sposób zawsze otrzymywaliście pomoc, jak wyszliście z tak wielu kryzysów. Ale jeśli pomimo to jesteście niezadowoleni, martwicie się, gdy pojawiają się jakieś chmury na niebie waszego życia, to jeśli się martwicie, to znaczy, że wciąż jesteście słabi. Więc pierwszą rzeczą jest to, że jeśli rzeczywiście czcicie Boginię, nie powinniście mieć w ogóle żadnych zmartwień, ani żadnego lęku, w ogóle. Idźcie do przodu, bez obaw. Cokolwiek czynicie, róbcie to bez lęku. 

Ale w tym samym czasie muszę powiedzieć wam o drugiej stronie, że nie możecie zachowywać się jak zombie; nie miałam tego na myśli, żebyście mówili bezsensowne rzeczy wychodzące z prawej strony. Ale jeśli macie coś zrobić, róbcie to z jasnym zamysłem a także bez żadnego lęku. Tak więc wszelkie Jej moce zaczynają się w was objawiać. Człowiek, który nie ma lęków, nie musi się o nic martwić: o sen, o swój dobrobyt, o nic. Jest bez leków. 

Znów powiem, że "bez lęków", nie oznacza, że uderzacie każdego i mówicie różne rzeczy, nie. Oznacza to, że jeśli nie macie lęków, to kiedy ktokolwiek was zaatakuje, wy zawsze możecie siebie ochronić. Opowiedziałam wam tę historię, bo ta ochrona nie pochodziła od wewnątrz, jak wtedy, kiedy to Bogini ochrania ich, ale on sam siebie ochronił. Tak więc przez niego zaczęła pracować ta moc. Powinniście pozwolić swojemu umysłowi i swojemu ciału na projekcję tych mocy, bo jeśli nie, to możemy powiedzieć, że Puje, to wszystko, jest w porządku, i moc jest tutaj; ale umysł mówi wam: "Nie, nie, nie, to tak nie jest". 

Jest tak wiele historii i tak wiele cudów, ludzie to opisali. Więc przede wszystkim nie powinniście się niczego obawiać. Jeśli nie zrobiliście nic złego i jesteście na właściwej ścieżce, zawsze będziecie mieli ochronę. Zapamiętajcie to, że zawsze będziecie mieli ochronę. Pamiętajcie o tym i wierzcie w to, że "ja zawsze mam ochronę". 

To jest coś bardzo trudnego, bo być może nasz umysł podpowiada nam takie pomysły: "O Boże, co się teraz zdarzy, co się wydarzy? Taka sprawa, inna sprawa". Więc jak powiedziałam, pierwszą i najważniejszą sprawą jest to, żeby nie mieć lęków, ażeby Bogini mogła sama siebie wyrazić. Załóżmy teraz, że wszystkie Ganas podążają za wami. Jeśli dowódca armii jest osobą przestraszoną, to co inni zrobią? I dlatego stajecie się zależni tylko od samych siebie.         Tę wiarę także należy rozwinąć. Widziałam ludzi, którzy są chorzy, więc oni muszą przyjść i zobaczyć się ze Mną, bo oni nie polegają na sobie. Oni sami mogą siebie leczyć. Nie ma potrzeby, aby przychodzili do Mnie i spotykali się ze Mną. 

Jest bardzo wiele przypadków, kiedy ludzie wyleczyli sami siebie, wyleczyli innych tylko poprzez modlitwę. Ale jeśli wiara nie jest dojrzała, wtedy oni myślą, że Ja powinnam ich leczyć, Ja powinnam ich dotykać, Ja powinnam zrobić to, Ja powinnam zrobić tamto. Teraz zaprzestałam tego. Kiedyś to robiłam. Powód jest taki, że teraz wy polegacie na sobie. Nie tylko możecie pomóc sobie, ale także możecie pomóc innym. Ale jeśli nie macie wiary w siebie, że możecie leczyć, możecie sami troszczyć się o siebie, sami siebie ochraniać, to cała sprawa wygląda tak, jakby cały czas Matka musiała wykonywać całą pracę. Najpierw musicie nakarmić małe dziecko, czyż nie? Możecie dać mu wsparcie, troszczyć się o nie, robić wszystko, ale kiedy ono dorasta, to nie chce, aby matka je karmiła. W ten sam sposób dzieje się z Sahaja yoginami. 

Jak wiele lat Ja pracuję, a teraz wy musicie godnie dorosnąć i musicie dojrzewać, a wtedy sami będziecie robić rzeczy prawidłowo. Ta dojrzałość jest obecna, ponieważ Matka pobłogosławiła was, dała wam wszystkie swoje moce.       Ale jedna z tych mocy, cierpliwość - jest trudna. Musicie być cierpliwi jak wasza Matka. Możecie pomyśleć, że to jest bardzo trudne, ale spróbujcie. Musicie mieć cierpliwość przede wszystkim wobec samych siebie. Znam wielu ludzi, którzy myślą, że pod względem duchowym są nikim, i że niczego nie osiągnęli. To jest absolutnie pewien rodzaj eskapizmu, że chcecie uciec przed swoją osobowością. Tylko zobaczcie, że gdy zrobicie introspekcję to odkryjecie, że teraz rozwinęliście się do rozmiaru wielkiego duchowego człowieka. Nikt nie może was dotknąć, możecie robić wszystko, sami możecie troszczyć się o siebie, możecie wspierać innych. 

Jakiekolwiek są moce, tak jak wczoraj śpiewali, to wszystkie te moce przejawiają się w was. Ale wciąż, musicie dać im szansę. Powinnam powiedzieć, że powinniście przekazać je innym, a nie trzymać dla siebie. Sprawa polega na tym, że nikt do tej pory nie wykonał tego rodzaju pracy jak połączenie wszystkich uczniów z Boską Mocą. Ponieważ jest to Boska Siła Miłości, musicie wiedzieć, jak kochać innych. To jest bardzo ważne. Ale jeśli chodzi o miłość to znów, oni będą kochać swoje dziecko, swoją żonę. Myślę, że jest to bardzo powszechne w Sahaja Yodze; ludzie są zbyt przywiązani do swoich dzieci. A przedtem oni znani byli z tego, że byli całkowicie egoistyczni, w ogóle nie byli przywiązani ani do dzieci, ani do żony, do niczego. A teraz są oni jak sklejeni ze sobą. 

Dzieci są sklejone z nimi, żona jest sklejona z nimi i teraz rodzina jest bardzo ważna. To jest inny rodzaj skłonności, od której musicie się uwolnić. Ja nie mówię, że macie porzucić swoją rodzinę czy swoje dziecko, ale znów mówię o odwiązaniu. Odwiązanie jest waszą mocą. Obserwujcie wszystko z odwiązaniem. Nie myślcie o tym, że: "Och, przyszedłem zaledwie kilka dni temu do Sahaja Yogi", nie. Nie myślcie: "Ktoś stoi wyżej niż ja, ja nie jestem dobry", nie. Po prostu, róbcie introspekcję siebie samych i sami przekonajcie się, jak wiele mocy do tej pory zdobyliście. A im więcej będziecie wiedzieć, tym bardziej staniecie się pokorni. To jest bardzo zaskakujące. 

Staniecie się pokorni. Nie będzie żadnego rodzaju lęku. Możecie bać się, kiedy macie powiedzmy, dużo pieniędzy ze sobą. Jeżeli jesteście bardzo dobrze wykształceni, to możecie obawiać się zazdrości. Jeżeli macie inne drogocenne rzeczy jak ozdoby i takie rzeczy, to możecie się bać, że przyjdą do was wielcy złodzieje. Jeśli jesteście politykami to możecie się obawiać, że ktoś może zająć wasze miejsce podczas waszej nieobecności. Ale jeśli naprawdę chodzi o Sahaja Yogę, to jest odwrotnie. Kto może wam ukraść waszą Samorealizację? Powiedzcie Mi! Kto może wam ukraść wasze moce? 

Kto może wam ukraść wasze wibracje, pomyślcie o tym! I kto może ukraść waszą miłość? Bo to pochodzi od Ducha, który jest wieczny i cały czas przepływa. Jedynie wtedy, kiedy jesteście z dala od Ducha, tylko wtedy czujecie te wszystkie rzeczy, które można poczuć w ciemnościach. Następnie, innym rodzajem mocy Matki jest to, że Ona daje wam stan, w którym jesteście ‘sakshi’ – jesteście świadkiem, obserwującym wszystko. Wtedy macie niesamowitą cierpliwość, niesamowitą cierpliwość. Cokolwiek się wydarza, to w porządku, niech tak będzie. To będzie dobrze, tamto będzie dobrze. Więc pozbywacie się tej strasznej rzeczy, nazywanej złością. I to daje wam tak spokojny stan świadka, że zaczynacie stawać się coraz młodsi i młodsi. 

Powiem wam, że są niektórzy yogini, którym dałam Realizację, powiedzmy rok temu, teraz spotkałam ich i nie mogłam ich rozpoznać. Nagle stali się o 10 lat młodsi. To bardzo zaskakujące i sama musiałam przyznać, że naprawdę nie mogłam was rozpoznać. Czy jesteście tymi samymi ludźmi, czy jesteście synem tego człowieka? Zatem, dzieje się z wami to, że stajecie się spokojną osobowością. Dlaczego? Bo wasza Matka jest zawsze obecna. Ta wiara, że Ona jest zawsze obecna, zawsze jest z nami, zawsze nas ochrania a teraz jesteśmy dorośli, więc Ona dała nam wszystkie moce. Dała nam wszelkie dobra materialne, no więc co? Czego mamy się bać? 

Ale ta wiara nie może być jedynie ślepą wiarą, ale musi być wiarą oświeconą. Różnica polega na tym, że jak macie ślepą wiarę, to macie wiarę, ale nie macie mocy. A jak macie oświeconą wiarę, to macie wiarę i wszelkie moce. Kiedy tak się z wami stanie, to zaczniecie rosnąć znacznie szybciej, najpierw w waszej Dharmie, i nie obawiacie się o swoje cnoty. Rozmawiacie z ludźmi, wszędzie mówicie o Sahaja Yodze. I to pracuje, to działa. Kiedy nie będziecie mieć żadnego lęku, cały obraz będzie dla was jasny, ponieważ stajecie się wizjonerem, w sanskrycie nazywamy to drishtas. 

Tak jak C. S. Lewis mógł zobaczyć nasz pochód. W jaki sposób William Blake mógł przepowiedzieć naszą przyszłość? Jak Gyaneshwara mógł napisać "Pasayadan", który jest opisem wszystkich Sahaja yoginów? 
Ale on cały czas mówi: "Teraz wstańcie i idźcie, i róbcie to, wy jesteście tym, otrzymaliście to". Cały czas stara się utwierdzić w tym ludzi. Jak Rabindranath Tagore mógł zobaczyć, że będziemy w Ganapatipule? Jak to się mogło stać? To dzieje się jedynie wtedy, kiedy ludzie mają oświeconą wiarę. Gdy macie oświeconą wiarę, to Matka daje wam kolejną bardzo dużą moc rozróżnienia, rozpoznania. 

Przyszedł do Mnie ktoś: "Matko, ten pan jest bardzo dobry, to, tamto, Ty wiesz, nikt się nim nie zajmował, to, tamto, on jest bardzo dobrze wykształcony, bardzo zamożny to i tamto". Powiedziałam: "No dobrze, pokaż Mi jego zdjęcie". Zobaczyłam zdjęcie i powiedziałam: "Nie! Lepiej trzymajcie go z dala. Absolutnie. Trzymajcie go z dala!" On był zdumiony: "Dlaczego powiedziałaś, żeby go całkowicie trzymać z daleka?" Zobaczyłam zdjęcie i jedynie na podstawie zdjęcia, jak Matka mogła tak powiedzieć? Ja mogłam czuć wibracje i natychmiast powiedziałam: "Są niedobre". 

Pewien pan przyszedł tutaj i powiedział Mi, że pewni Nigeryjczycy napisali do niego list: "Wpłać do banku 35 tys. funtów", czy coś takiego, "i my wpłacimy całkiem sporo, w milionach, a potem możecie mieć jedną trzecią z tego". On przyszedł do Mnie i opowiedział tę historię. Powiedziałam: "Naprawdę? Trzymaj się od tego z daleka". On zapytał: "Dlaczego?". "To jest oszustwo". Kiedy wrócił do Ameryki, oni odkryli, że to było oszustwo. On zapytał: "Matko, skąd wiedziałaś?" Powiedziałam: "Możesz czuć wibracje - tak gorące! Więc to jest oszustwo". 

Wy dostaliście wibracje. Możecie czuć swoje wibracje. Jeżeli nie chcecie używać tej nowej świadomości, to jaki jest sens przyjścia do Sahaja Yogi? Był bardzo niezadowolony, kiedy mu powiedziałam: "Zapomnij o tym". 
Pomyślał: "Dlaczego Matka tak mówi?" Zapytałam: "Na co potrzebne ci są pieniądze? Potrzebujesz pieniędzy? Dobrze. My mamy. Nie wchodź w tego typu rzeczy". Kiedy powiedziałam mu, że to jest oszustwo – był zaszokowany. Kiedy wrócił, odkrył, że to było oszustwo, więc już na lotnisku padł Mi do Stóp, a Ja zapytałam: "Co się stało?" "Matko, miałaś rację. Tak jak powiedziałaś, tak się stało". Odrzekłam: "Ale to były wibracje, które powiedziały Mi, że to jest oszustwo. Jeśli on mówi tak, że zamierza ci dać tak dużo pieniędzy, to nieprawda, bo jego wibracje były tak bardzo złe". 

W ten sposób możecie stopniowo doświadczać. Doświadczając tego, starajcie się umieścić to doświadczenie w swoim sercu i uwierzcie w to doświadczenie. Czym byliście? Czym staliście się teraz? Jak wiele doświadczeń Sahaja Yogi mieliście, kiedy uwaga Matki była na was. A jeśli macie tę oświeconą wiarę, oświeconą wiarę w siebie, to stajecie się pełni mocy. Nie macie mocy, bo wiara wasza jest taka. Ale jeśli naprawdę staniecie się dojrzałą rozwiniętą Zrealizowaną Duszą , to wszystkie wasze moce będą działały. 

Jest pewien rybak w Indiach, który jest wykształcony, chociaż jest rybakiem. Pewnego dnia miał zamiar udać się łódką na drugą wyspę, żeby rozprzestrzeniać Sahaja Yogę. Gdy wyszedł ze swojej chaty to zobaczył wielkie, ogromne, czarne chmury wiszące na niebie i grę Vishnumayi. Stanął tylko na brzegu i powiedział do Vishnumayi: "Proszę, powiedz tym chmurom, żeby zachowywały się porządnie. Mam zamiar wykonać pracę dla Matki. Niech nie stają mi na drodze". Tylko tak powiedział. Ludzie, którzy byli z nim powiedzieli Mi, że ten Harishchandra tak mówił. Wsiedli do łódki, zrobili program i wrócili do domu. Kiedy wysiadł z łódki, zaczęło padać. 

Tak więc dzięki waszej oświeconej wierze kontrolujecie wszystkie 5 elementów i nawet nic nie musicie mówić. Moce są tak wielkie, że działają. Zobaczcie, dzisiaj, kiedy Puja miała być spełniona, nagle zrobiło się przyjemnie. Ja nie prosiłam, po prostu zrobiło się przyjemnie, znacznie lepiej niż wczoraj, choć mogłoby być bardzo zimno. Ale znów, to powinno stać się wiarą, która jest rzeczywistością. Jeśli pamiętacie ostatni raz, mieliśmy straszny deszcz i wszystko podskakiwało i ludzie musieli złożyć wszystkie maszty namiotów. Jak tylko zaczęli wypowiadać Moje "Jay!" wszystko ustało. To doświadczenie powinno uczynić was… Nie było żadnej potrzeby składania masztów, lecz jedynie powinniście zaśpiewać "Jay" dla Mnie i to wszystko. Zamiast tego wszyscy byliście zajęci składaniem tych rzeczy, a Ja tylko patrzyłam na was i nie wiedziałam, co powiedzieć, po prostu powiedziałam: "Niech próbują". 

Te ciężkie próby pojawiają się także i po to, żebyście mogli dojrzewać. Jeżeli nie byłoby tych prób, gdyby nie pojawiły się ciężkie próby, to wy nie moglibyście ich pokonywać a gdybyście ich nie pokonali, to nie wiedzielibyście, czym jest wasza wiara. Osoba, która stoi nad brzegiem, powie: "Ja nie umiem pływać". Ale przypuśćmy, że sprawicie, iż skoczy do wody i popłynie, to wtedy będzie wiedział, że umie pływać. Bo wy nie wiecie kim się staliście, nie wiecie, że potraficie pływać. Nie wiecie także, że możecie uratować innych. Wciąż jesteście zajęci tymi małymi, małymi rzeczami tu i tam. Ale jeśli będziecie wiedzieć kim się staliście, wtedy całkowicie się zmienicie. Wasza niepozorność, która wygląda jak mała drobinka, pokryje całe niebo. Ale ta moc, którą macie w środku nie wywoła w was ego. 

Jedna sprawa, to jest test, który sprawi, że będziecie pokorni. Jest to jedna z rzeczy, która sprawia, że stajecie się pokorni, niezwykle kochający i miłosierni, nie będziecie ranić innych ludzi tymi mocami. I to jest oznaką, że jest to Miłość Matki, Moc Miłości Matki. Osoba, która ma bardzo kochającą i miłą matkę - jest to fakt psychologiczny - staje się bardzo miłą osobą. Jest to fakt psychologiczny. Tak więc teraz uświadamiacie sobie kim jesteście, kim staliście się. 

Z tego powodu Navaratri Puja jest bardzo, bardzo mocną Pują, ponieważ ona objawia się poprzez otwarcie kanałów waszej mocy. I dlatego jest Ona bardzo, bardzo ważna. I Ja właśnie od samego rana opływałam wibracjami, niesamowitymi wibracjami, to było jak wodospad wibracji. I cały czas widzę światło, światło, światło, światło. Myślałam: "Teraz nie wiem, o czym będę mówić, czy coś takiego". To dlatego zamknęłam oczy, bo cały czas będę widziała coś jeszcze, a nie was, ludzi. Więc pomyślałam, że lepiej zamknę oczy. A teraz wy jesteście światłem. Wy jesteście światłem. Światło nie boi się ciemności, czyż nie? Ponieważ ono może usunąć tę ciemność. Tym właśnie jesteście, choć o tym nie wiecie, czym jesteście. I żyjecie z bardzo, bardzo małym wyobrażeniem o samych sobie. 

Nie mówię, żebyście stali się jak guru, którzy chodzą wszędzie i wygłaszają wielkie mowy, z dwoma rogami na głowie, nie! To, co stanowi waszą ozdobę, to jest wasza pokora, to jest wasza uprzejmość, to jest wasza słodycz i sposób, w jaki obchodzicie się z ludźmi. To was zdziwi, ale Ja także mówię ludziom, kiedy odkryję, że coś z nimi nie jest w porządku, bez wątpienia, ale robię to w sposób, że ta osoba rozumie, że to jest dla jej dobra. Cała osobowość, cały charakter, wszystko się zmienia. Cała twarz się zmienia, cały styl poruszania się zmienia. Styl mówienia zmienia się automatycznie tak jakbyście wiedzieli, że maszyna się zmieniła. Więc rozwijacie w sobie cechy prawdziwego Mahayogina. Przedtem także wielu ludzi osiągnęło ten poziom Mahayogina, ale musieli przejść przez bardzo zawiłe życie. Musieli wszystko porzucać, nie na pokaz, ale naprawdę, z serca musieli się odwiązać. Musieli się z tego wydostać, odejść w oddalone miejsca, żyć spożywając zwykłe jedzenie, wszelkiego rodzaju… Nawet Buddha cierpiał tak bardzo. 

Chrystus cierpiał tak bardzo. Oni byli inkarnacjami, ale pomimo to musieli cierpieć. Rama tak bardzo cierpiał,         Shri Krishna cierpiał także, wyobraźcie sobie. Teraz wy ludzie nie musieliście cierpieć. Wręcz przeciwnie, wy wyszliście z tych cierpień: radość, muzyka, wszystko to, aby cieszyć się Sahaja Yogą, w Niranand - całkowicie bez niczego oprócz radości - należy wiedzieć, że powinno się porzucić wszelkie mity, z którymi żyjemy, wszelkiego rodzaju mity. Niektórzy ludzie mają mity: "Jesteśmy bardzo biedni". Niektórzy mają mity: "Jesteśmy bardzo bogaci". Niektórzy myślą: "Jesteśmy bardzo nieszczęśliwi", a inni "Jesteśmy bardzo szczęśliwi". To są wszelkiego rodzaju mity, to wszystko są mity. 

Sprawa polega na całkowitej pustce, całkowitej pustce, która jest radością. Ta pustka wypełniona jest radością. Całkowita pustka. Wtedy nie oczekujecie niczego od nikogo. I ta pustka, która jest wewnątrz was, w rzeczywistości daje ona szansę, abyśmy mogli zapełnić ją miłosierdziem i miłością. Np. coś jest już w garnku, to co możemy tam wlać? Co możemy tam dodać? Kiedy jesteście całkowicie puści w środku, nie ma nic z tego nonsensu z przeszłości ani z przyszłości, żadnych aspiracji, ambicji, nie ma nic z tych rzeczy, ani żadnego fałszu. 

Jeśli po prostu stajecie się puści, to jest ona wypełniona niczym innym jak radością. A ta radość ma wieczną naturę. 
Nigdy o nią nie prosiliście, nie oczekiwaliście na nią, ona tam jest cały czas. I to jest to, czego życzę wam, ludzie, abyście dzisiaj mogli to poczuć. Jak wiecie, sprawy związane z Devi są tak bardzo głębokie i subtelne, to, jak Ona przybrała formę Matki i jak Ona troszczyła się o swoich bhaktas z miłością, jak Ona walczyła z demonami i także z negatywnością. 

Ale teraz demony wkroczyły do waszych serc, ci fałszywi guru weszli do waszych mózgów. Tak wiele rzeczy przychodzi do was przez te straszne książki i cały czas was atakują. Nawet jeśli zabijecie te demony, to wciąż będą utrzymywać się w waszych głowach. W rzeczywistości one powinny zostać zabite, kiedy one po odbiciu w waszym umyśle, odeszły. Tylko wtedy istnieje możliwość wyeliminowania ich. W przeciwnym razie one odejdą, ale zostawią swoje buce w waszych głowach, czyli te negatywności, które pochodzą ze złych rzeczy, które robiliście, ze złych książek, które czytaliście. 

Również jest możliwe, że kiedy przyjdziecie do Sahaja Yogi, to możecie być wprowadzeni w błąd przez niektórych ludzi. W tym tym przypadku przebaczcie tej osobie. Ta osoba może się poprawić, ale wy możecie w dalszym ciągu tkwić w tych samych ideach i dziwnych rzeczach, i nagle może się to pojawić. Tak więc jakość polega na miłosierdziu i miłości, na stanie bez lęku i odwadze, i całkowitej pustce. W tej pustce nie martwicie się tym, co macie osiągnąć, jak wielu ludzi musicie zgromadzić wokół, ilu ludzi musi przyjść do Sahaja Yogi, nie przejmujcie się tym. To będzie działało automatycznie, ale nie będziecie tego pragnąć. Nie będziecie tęsknić:  "O mój Boże, jest tak niewielu ludzi, co robić?" To i tamto. Tak jest w pewien sposób dla nas lepiej, bo gdzie jest miejsce w niebie dla tak wielu głupich ludzi? 

Więc nie powinniśmy się uganiać za tymi, którzy są negatywni i bezużyteczni. 
Ale zdecydowanie musimy zaopiekować się tymi, którzy są naprawdę dobrzy. Jest jeszcze jedna rzecz, o której chciałam wam powiedzieć, że automatycznie tacy ludzie odpadną z Sahaja Yogi, odejdą za jednym zamachem. Oni nie zostaną, ponieważ nie zasługują, żeby być tutaj. Nie zasługują, aby mieć moce Matki. I to dzieje się w bardzo piękny, subtelny sposób. Ja zawsze przychodzę spóźniona na programy i widzę, że ci, którzy są bezużyteczni po prostu znikają. Niektórzy znikają w połowie drogi, ponieważ nic im nie wchodzi do głowy, niczego nie rozumieją, więc odchodzą. A ci, którzy zostają to prawdziwi poszukiwacze prawdy i wszyscy oni dostają Realizację. W sanskrycie nazywa się to "cheyen", co oznacza selekcję. Ma tutaj miejsce naturalna selekcja. 

Jest bardzo interesujące, w jaki sposób ludzie odchodzą i w jaki sposób wracają do Sahaja Yogi. Wy wiecie, że to jest bardzo powszechne zjawisko w Sahaja Yodze. Nie powinniście się tym przejmować. Jest możliwe, że myślicie w ten sposób, że jeśli będziecie mieć zbyt wielu ludzi, powiedzmy, z Rosji, a nie tak wielu ze Szwajcarii – ale teraz nie jest aż tak źle. Zatem nie powinniśmy się martwić, bo nie jesteśmy już ani Rosjanami, ani Szwajcarami. My jesteśmy nadzwyczajnymi ludźmi, my jesteśmy Sahaja yoginami. Czy oni są Rosjanami, czy Hindusami, czy pochodzą z jakiegoś afrykańskiego państwa, wszystko w porządku. Dopóki są Sahaja yoginami, dopóty powinniśmy być szczęśliwi. Jeżeli Szwajcarzy przychodzą do Sahaja Yogi, to powinniśmy czuć się szczęśliwi. To przywiązanie, że musimy mieć więcej Szwajcarów, na początku jest może i dobre, bo chcecie mieć towarzystwo. 

Nie możecie żyć tylko z jedną osobą w dżungli, z innymi nie-Sahaja yoginami. To jest trudne, więc chcecie mieć towarzystwo, więc chcecie mieć więcej, więcej i więcej. Ale nie szkodzi, tak wiele osób ile jest, to wystarczy, i nie powinniśmy martwić się o te rzeczy, o ilość osób. Ale kiedy chcemy dzielić się swoją miłością, to wtedy odczuwamy niedostatek. Nie z tego powodu, że jesteśmy Szwajcarami, ale dlatego, że nie możemy się dzielić z innymi. I wtedy rodzi się nowa osobowość i ta nowa osobowość jest tego rodzaju, że ona działa. Mam na myśli to, że nie dajemy wam żadnych pieniędzy, nie ma żadnych nagród dla was, nie ma żadnego rodzaju dopingowania was do pracy, w taki sposób, że nie mamy żadnych waszych zdjęć, które tu wiszą, nic z tych rzeczy. Wyobraźcie sobie, czy w jakiejkolwiek innej organizacji ktokolwiek pracowałby tak, jak wy pracujecie? Nikt nie pracowałby. Dają wam nagrody, dają wam premie, dają wam także awanse, robią wszelkiego rodzaju rzeczy, aby sprawić, byście szli dalej. 

My niczego takiego nie robimy w Sahaja Yodze. A więc, co sprawia, że pracujecie tak ciężko w Sahaja Yodze, co sprawia, że rozprzestrzeniacie Sahaja Yogę? Jedyną rzeczą, która to powoduje jest to, że chcecie się dzielić z innymi.  I nie można tego zmienić. To jest tak jak z pijakiem, że jeśli ma butelkę, to musi podzielić się nią przynajmniej z jedną osobą. Bo on myśli, że to jest grzeszne: "Ja grzeszę, więc dlaczego nie miałbym podzielić się z kimś innym?" Wtedy grzech będzie podzielony pół na pół. Ale w Sahaja Yodze dzielicie się, chcecie to rozprzestrzeniać, bo jesteście kolektywni. Ponieważ wy staliście się kolektywni. Chcecie, żeby więcej ludzi przyszło, dołączyło się i radowało. 

Widzicie, staliście się bardzo szlachetni. Oczywiście, pijacy tak robią, ale załóżmy, że np. ktoś ma loterię, albo ktoś prowadzi duży biznes, to nie będzie chciał się dzielić. A wy myślicie: "Dlaczego nie? Jeśli ja jestem taki radosny, dlaczego inni nie mogą być? Dlaczego ludzie nie mieliby mieć takiego błogosławieństwa, jak ja mam?" Bo wy stajecie się niezwykle szlachetni, tak szlachetni, pracujecie tak ciężko, tak bardzo ciężko, żeby to osiągnąć. Żadne słowa nie opiszą Mojej radości, kiedy widzę, jak wy, ludzie, wypracowujecie to tak spontanicznie. Wczoraj widziałam film, całą sztukę i byłam naprawdę bardzo zdumiona i poruszona, że muzyka marathi przybyła do Cabelli. Czy możecie sobie wyobrazić, żeby jakiś Włoch pomyślał o tym? 

Nawet po 100 latach nie przyszłoby mu to do głowy. Ale jak to pojawiło się tak spontanicznie i to działa. Ponieważ jest w tym poczucie kolektywności. Ludzie mówią o tym, że jest tutaj ‘Nowa Era’, bez wątpienia, jest to Nowa Era i także nowa świadomość. A to, co teraz jest nowe, to nowa kolektywność i ta kolektywność działa w ten sposób, że chcecie rozprzestrzeniać. To działa jak głód w was, to jest inny rodzaj głodu, że chcecie wykreować więcej Sahaja yoginów, chcecie mieć więcej braci i sióstr i chcecie im pomóc, żeby mogli przyjechać na puje, żeby mogli stać się dobrymi Sahaja yoginami. Ten rodzaj ambicji czy radości, jakkolwiek to nazwiecie, jest to cały plan, który pokazuje, że w waszym sercu rozkwita kolektywność. To dlatego nie możecie mieć radości z Sahaja Yogi w samotności, siedząc w Himalajach, nie. Chcecie mieć innych ludzi. To jest oznaka tego, w jaki sposób miłość Matki zakorzeniła się               w waszych sercach, i w jaki sposób wy wszyscy będziecie rozprzestrzeniać Sahaja Yogę. 

Oczywiście, powiedziano Mi, że ktoś w Australii robi pieniądze. Australia zawsze stanowiła problem. Oni robią na tym pieniądze, Ja po prostu nie wiem, co powiedzieć, bo Ja tego nie jestem w stanie zrozumieć. Jak oni mogą myśleć, że można robić pieniądze i robić tego typu rzeczy, wszelkiego rodzaju rzeczy nie-Sahaj? W jakiś sposób powoduje to ból głowy. Nie szkodzi, zostawcie to Mi, Ja się tym zajmę, cokolwiek to jest. A wy stańcie się po prostu wielkimi światłami swojej Matki. I o to was proszę tej nocy. Macie wszystkie moce, które płyną przez was, macie światło, które jest oświecone, ale musicie rozwijać się, coraz bardziej, bardziej i bardziej. I będziecie zdumieni tym, co powiedział Tukarama, że "Ja jestem jak drobinka kurzu, a także jestem całym niebem". Taka jest właśnie wasza osobowość. 

Niech was wszystkich Bóg błogosławi.

