Navaratri Puja. Cabella Ligure, Italia. 24 de octubre de 1993.

Hoy nos hemos reunido aquí para hacer el puja a la Devi. La Devi tiene muchas formas, aunque es realmente la personificación de la Shakti. La Adi Shakti da la Shakti a todas estas encarnaciones y por ello hemos tenido muchas diosas que han venido a esta tierra en diferentes ocasiones. Hicieron todo lo que era necesario para el ascenso de los buscadores. Especialmente la que conocemos como Jagadamba, Durga; intentó proteger a todos los buscadores de la Verdad destruyendo todas las fuerzas negativas. Porque sin el ascenso de los seres humanos no es posible que ellos mismos lleguen a conocer la Verdad, por eso, cualquier cosa que los humanos intentan hacer, es una proyección mental, y cualquier proyección mental, si no está sustentada por la Verdad, por el Dharma, decae, muere. En Sánscrito lo llaman "Glani"(?), y cuando este "Glani" tiene lugar, es cuando las encarnaciones nacen en la tierra para resolver el problema.

En todas las encarnaciones de la diosa se han dado también encarnaciones de las fuerzas satánicas; Ella tuvo que luchar contra ellas para destruirlas. Pero esta destrucción no era por el mero hecho de destruir fuerzas negativas, sino por el hecho de que las fuerzas negativas siempre intentan destruir o dañar a los buscadores, a los santos. Todas estas fuerzas destructivas, normalmente nunca vienen al mismo tiempo, sino en ocasiones diferentes, por lo que resulta más fácil manejarlas. Pero el propósito de las encarnaciones es salvar, proteger a aquellas personas que son buscadores; porque estas personas son las más importantes dentro del reino de la espiritualidad. Los demás a su lado son como polvo, no sirven para nada. Si no están buscando la Verdad, para los ojos de Dios son como vidas inútiles que un día mueren y ya está. No tienen valor, no tienen dignidad ni entendimiento de nada. Por tanto, en el Juicio del Amor divino tenemos dos tipos de personas: las que son buscadoras de la Verdad y las que no lo son; puede que sean muy buenas personas y que hagan algunos trabajos como trabajos sociales o de misiones, etc., pero si no están buscando la Verdad, no llegan a esa categoría en la que Dios tenga que encarnar. Por tanto, intentad comprender el valor y la importancia de los buscadores.

Esto es lo que vosotros habéis estado buscando; si veis el porcentaje de buscadores que lo han conseguido veréis que son muy pocos, pero muy importantes, porque, por ejemplo, un pequeño trozo de oro tiene un valor muy superior a un gran montón de acero. De la misma manera, un buscador tiene muchísimo más valor en el crecimiento de la espiritualidad que una persona normal. El Universo entero se creó, toda la atmósfera se generó, todo el proceso evolutivo tuvo lugar y, ¿para qué? Para que los seres humanos conociesen la Verdad.

Pero esta atmósfera moderna es como una maldición, es algo mucho más maligno que todos los Sumbhas y Nishumbas juntos; y lo peor de todo es el materialismo, porque el materialismo os hace groseros, mundanos. Cuando estáis ascendiendo en vuestra búsqueda, de repente, este materialismo os agarra, os sujeta, lo he observado muchas veces. Cuando la gente viene a Sahaja Yoga empiezan a profundizar en sí mismos, comprenden todo lo que digo, quieren saber o tener todo el conocimiento interior, lo que se llama Atmagnya. Atmagnya significa dos cosas: el conocimiento del Espíritu y el conocimiento del Ser (de uno mismo). Todo esto lo van descubriendo. Este es el estado por el cual los buscadores han estado haciendo todo tipo de cosas, como ir a los Himalayas, meditar a la intemperie sin apenas ropas de abrigo, meditar en las cuevas viviendo de algunos frutos etc.., hicieron todo tipo de tapasyas porque su búsqueda era muy profunda, muy intensa, y no podían apartarse de esta fuerza interior de búsqueda.

Pero en los tiempos modernos, el materialismo impide esta entrega, esta dedicación. Para los buscadores es algo que los desvía completamente, es como una locura. He visto que la gente, antes de venir a Sahaja Yoga solía viajar, gastar dinero en ir a los Himalayas, a Nepal, a Japón, viajaban a muchos lugares, pero después de venir a Sahaja Yoga, después de llegar a ser el Espíritu para el crecimiento de vuestra consciencia, el progreso se ve muy retardado, es demasiado lento. También es comprensible que, después de dar tantas vueltas y finalmente encontrar algo tan valioso, uno debería asentarse, establecerse y sentirse satisfecho con uno mismo; esto está bien, pero, ¿y después? Vuestro crecimiento no debería detenerse. Y sin embargo se detiene; una de las razones principales es el materialismo. Debido al materialismo también la fe en vosotros mismos es menor.

Ya habéis visto que los dioses pidieron a la diosa que viniera, Ella vino y aniquiló todas estas fuerzas negativas. La razón fue que el gran deseo de los dioses obligó a la Diosa a encarnar; el deseo de los santos era tan sincero..., a veces no conseguían comida o agua, pero trabajaron muy duro por su ascenso que, sin embargo, se veía perturbado por las fuerzas negativas. Su llamada era tan del corazón, tan desesperada, tan genuina y sincera, que la Diosa tuvo que encarnar en esta tierra para salvarles, protegerles y cuidar de ellos.

Ahora bien, una vez que habéis llegado a vuestro destino sentís que es mejor establecerse, asentarse; pero establecerse, ¿con qué? Si después de recibir la Realización sois personas completas, estáis en la totalidad, sois uno con la realidad, entonces ya no hay que hacer nada, simplemente os convertís en santo, y un santo no necesita ninguna publicidad, no necesita nada. Su mensaje se extiende por sí solo, la gente, en cuanto le ve, sabe que es un gran santo. Ha habido muchos santos que ni siquiera salieron de su casa. Hay un refrán en India que dice: No deberías nunca dejar tu takya, y significa que, no deberías nunca dejar la almohada sobre la que descansas. Este era el criterio de un Guru. Aquellos que eran buscadores tenían que acudir al Guru y escalar al menos seis o siete millas hasta encontrar al Guru que, a lo mejor, después de llegar hasta allí les golpeaba o les podría incluso tirar montaña abajo. Les sometía a muchas pruebas y de muchas maneras. Finalmente el Guru seleccionaba a una persona para darle la Realización. Por tanto, este esfuerzo desesperado, este constante intento siempre estaba en ellos.

Y ahora venimos a Sahaja Yoga, en estos tiempos modernos. A veces siento, no solo que Sahaja yoga es muy fácil sino que os mima demasiado. Sabéis que tenéis la Realización, sabéis que sois mejores que otros, que habéis solucionado muchos de vuestros problemas y que ahora sois vuestros propios maestros. Pero con todo esto, la responsabilidad que tenéis hacia vosotros y hacia los demás, decrece, porque os sentís muy satisfechos con vosotros mismos.

El otro día me llamó una sahaja yoguini; me llaman para todo. Me dijo "el otro día fui al médico, me hicieron una radiografía y vieron que estaba embarazada, así que, ¿qué debo hacer respecto al bebé?" Por cosas tan pequeñas me llaman y me preguntan. O bien, ¿qué nombre le podría poner a mi niño?, etc., tengo que hacer mucho más trabajo, por ejemplo, que cualquier cura. Se preocupan por cosas muy pequeñas. Está bien, todo esto lo hago, el deciros todo lo que hay que hacer, etc., pero incluso si pierden el tren me llaman para decirme: "Madre, hemos perdido el tren, ¿qué hacemos?" Y tengo que decirles: "Bueno, dad un bandhan". Hasta cosas así tengo que decirles. O bien, el padre de alguien está enfermo, con un problema de corazón, entonces me llaman y me dicen: "Madre, mi padre está enfermo del corazón, no es un sahaja yogui, ¿qué puedes hacer por él?" Y Madre tiene que poner su atención en alguien que ni siquiera es un sahaja yogui. Me escriben por cosas muy, muy pequeñas, me dicen cosas que no podéis ni imaginar.

Todo esto demuestra que no entienden para qué estoy aquí. Pero aun así, yo nunca les digo que es algo muy tonto o estúpido el preguntarme cosas así, que no deberían malgastar mi tiempo; nunca digo esto. Pero debéis verlo ahora, que si no os valoráis a vosotros mismos como almas realizadas, no podéis tampoco valorar mi tiempo, ni tampoco podréis ver lo que yo soy. Esta encarnación puede ser malgastada completamente debido a esta actitud materialista.

En estos tiempos modernos, no sé qué problema tienen los seres humanos, porque lo más importante en sus vidas es el ascenso, el crecimiento. Intentad tener una visión global de todo: ¿Por qué se creó este Universo?, ¿por qué fuisteis creados como seres humanos?, ¿qué necesidad había de ello?, ¿para qué? Si tenéis una gran visión global de todo, intentad después localizar vuestra posición, ¿dónde estoy yo? Y ver entonces: "El Divino me ha elegido y me he convertido en un sahaja yogui". ¿Cuál es mi responsabilidad?, es lo que uno tiene que ver. Pero, por el contrario, por ejemplo, he visto que la gente que va a venir me llama para preguntarme, ¿nos llevamos la silla o no? Esto muestra que no se valoran a sí mismos ni me valoran a mí tampoco. Ambas cosas. Porque, se preocupan por tales pequeñeces que uno realmente no entiende cómo los sahaja yoguis pueden hacer preguntas así.

Podemos tener una perspectiva de la Diosa. Viene a esta tierra bajo formas diferentes y en momentos diferentes para salvar a los buscadores de la Verdad y para ayudar a los buscadores en su crecimiento. ¿Podéis imaginarlo? Hay una gran diferencia en la encarnación de la Diosa antes del Kali Yuga. ¿Por qué? Por que se trata de algo muy distinto; vosotros habéis venido a esta tierra para ser sahaja yoguis. Debéis tener un cuerpo, una mente, llenos de espiritualidad o por lo menos debería ser así; porque, ¿cuántas vidas habéis tenido ya en las que habéis estado buscando a Dios? Y ahora justamente os encontráis aquí, ¡qué casualidad!, ¡qué coincidencia!, ¿de qué se trata? Tenéis una gran ventaja pues habéis llegado a Sahaja Yoga debido a vuestra búsqueda y ahora os sentís satisfechos, pero, ¿cuál es vuestra responsabilidad?

Tenéis la ventaja de que la misma Diosa ha venido no solo para protegeros, para nutriros y matar a los demonios, sino que ha venido a esta tierra para hablaros de todo lo que es más sutil en nuestro interior y de cuál debería ser vuestra relación con lo externo así como con lo interno. Anteriormente nunca estuvisteis conectados con la Verdad, con este Poder Omnipresente, nunca estuvisteis conectados con Dios Todopoderoso. Por tanto uno debería entender que ha ocurrido algo grande, "en mi interior ha emergido esta Kundalini y ha alcanzado estos centros superiores, ¿cómo ha ocurrido?" Esto no había ocurrido anteriormente; simplemente los buscadores eran protegidos y se cuidaba de ellos, pero en ninguna parte está escrito que la Diosa haya dado la Realización a la gente. Podría haberlo hecho, hay al menos diez nombres que describen que es Ella quién os da el Nirvana, vuestra libertad, vuestra liberación. Todas estas cosas están escritas, pero lo que ahora está ocurriendo es que la gente no es capaz ni siquiera de entender el valor de su propia vida. Ved las preguntas que hacen, las cosas que les preocupan, "mi hijo ya ha crecido, ¿qué debería hacer?", "¿que qué deberías hacer?, pues llévalo al colegio o haz lo que quieras". "Madre, dime por favor, a qué colegio le llevo?, ¿has visto este colegio?" "No, no lo he visto" "Por favor ve a verlo". Imaginad, Kali Mata haciendo estas cosas; Ella os habría dado dos buenas bofetadas. ¿Qué se puede esperar de alguien así? Hasta este extremo una Madre tiene que volcarse; pero estoy segura que ni vosotros haríais esto por vuestro propio hijo. Ahora bien, cuando miramos la parte que corresponde a los niños, ¿qué están haciendo ellos? Todavía ser materialistas.

Hoy es un día especial que se llama Dasera(?); como sabéis es el día en el que Ravana fue quemado; ahora se queman Ravanas en todas partes (para conmemorar este día).Esta fue la victoria de Shri Rama. Pero su victoria no fue dar la Realización o crear sahaja yoguis, no; su victoria fue que mató a Ravana. Aquello fue hecho en aquel tiempo para preparar el presente de hoy día. Todo esto fue hecho hace mucho tiempo para hacer posible lo que hoy está ocurriendo, para que llegara un día en el que las personas tuvieran un apropiado sistema de valores por la victoria de Shri Rama. Pero no ocurre, no ocurre porque esta encarnación de Mataji Nirmala Devi es muy diferente, muy elusiva, es Maha Maya; a vosotros se os deja a vuestro libre albedrío, para que hagáis lo que queráis. Podéis hacer lo que queráis. Y por eso hay gente que me pregunta: "Madre, ¿sabes una cosa?" "¿Qué?" "Que no sabemos qué sillas comprar". Con cualquier pequeñez acuden a Madre. Pero nunca para cosas importantes. Es como un mal uso o un mal entendimiento de toda la situación, como si algo realmente grande o importante es utilizado para algo absurdo o sin sentido.

Así que, ved la diferencia entre las encarnaciones; una encarnación viene para salvar a la gente, para sacarles de la malla de la propia maya, y otra encarnación ha venido no solo para hablar de ello, sino para daros la Realización y cuidar de vuestros detalles más insignificantes.

Así, cuando esta mujer me llamó para decirme: "Madre, dime qué puedo hacer, por favor, cúrame"; vi que la actitud de los bhaktas de aquellos tiempos y la actitud de hoy día, es muy diferente. Aun así le contesté a esta mujer: "Nunca me dijiste cuando hiciste todo eso, pero no importa, sea lo que sea lo que hayas hecho creo que es mejor que vea al niño, cuidaré de él, veré qué tiene, pero tú ven también". Entonces me di cuenta de que esta mujer estaba tremendamente apegada a su niño; llamé por teléfono al líder y me dijo que era terrible el apego que le tenía. Estamos siempre así, de una cosa absurda pasamos a otra igual. Esta encarnación tiene tal variedad de trabajos por hacer..., incluso los sesenta y cuatro Kalas o expertos de Shri Ganesha no son suficientes para resolver todo esto. ¿Por qué es tan complicado?

Después de vuestra Realización deberíais estar en una marcha firme hacia vuestra meta y vuestro crecimiento. Pero, ¿por qué constantemente este complicado sinsentido os está perturbando? Deberíamos preguntarnos, ¿qué quieres?; quiero un niño. Después de Sahaja Yoga no deberíais querer nada, ¿por qué queréis tener un niño?, en sahaja yoga ya hay muchos niños, podéis cuidar de ellos. Este "yo quiero" debe desaparecer de vuestra mente, "quiero esto y quiero aquello". Este "querer cosas" ya ha terminado, pues lo que queríais era vuestra Realización. Sin embargo, lo que ha ocurrido es que ahora lo que yo quiero es más importante, y lo que yo quiero es que os desapeguéis por completo del materialismo. Esto no significa que os convirtáis en un "Hare Rama Hare Krishna", nada de eso, ellos no son nada desapegados sino muy apegados a todo. El desapego es un estado en el que nada os puede atar, en el que nada es importante excepto vuestro ascenso espiritual, nada os puede atraer más que vuestro progreso. Esto es exactamente lo que se espera que hoy entiendan los sahaja yoguis.

Cuando leo todas las cosas por las que la gente ha tenido que pasar y las comparo con la trayectoria de los sahaja yoguis, me siento fatal. Aquí todo es vuestra conveniencia, "venid, venid, gozad de esto, buena comida, buena compañía...," es como un constante festival. Todo a vuestro ritmo, y si algo falla o algo falta, yo soy quién tiene que decirle a los organizadores: "¿Por qué no habéis hecho esto?, o deberíais haber hecho aquello".

Pero llegamos a un punto en el que debemos entender qué es lo que queremos, ¿de qué sirve matar a Shumba o Nishumba? ¿O de qué sirve matar a esta Iglesia Católica?, ¿de qué sirve? Porque estáis estáticos, estáis estancados en un solo lugar, así que, ¿de qué sirve pues destruir constantemente toda esta negatividad?, ¿cuál es el propósito? Todo es muy arbitrario. Me dicen, "Madre, Tú les has dado permiso, así que, hacen las cosas a su manera". El otro día vino a verme una mujer, su niño estaba muy enfermo y le pregunté, ¿estás meditando?, se quedó callada. Le dije: Sé inmediatamente que no estás meditando, porque sé de qué se trata. Y es que ni siquiera meditáis.

Así que hoy, en este día de Dasera, en el que toda la gente sale fuera de los límites de su localidad y trae oro para sus padres, lo que vosotros tenéis que hacer es cruzar los límites de este materialismo, esta absurda y "empequeñecedora" fuerza que opera dentro de vosotros. Tenéis que trascender esto y, como os decía, traer oro que es algo puro, de la frontera de Sahaja Yoga.

¿Cuántos de vosotros estáis realmente trabajando? ¿Cuántos de vosotros estáis hablando de esto a la gente? ¿Qué estáis haciendo realmente? ¿Por qué os hablo así a vosotros y no a los hindúes? Porque su actitud es diferente, su actitud es espiritual y no materialista; desean su ascenso espiritual por el cual sufrieron mucho, hicieron el máximo por llegar a ese estado en el que pudieran rendirse o entregarse con facilidad. Este estado de entrega es el que aún tiene que llegar. Por ejemplo, supongamos que tenéis un problema, como el no tener vacaciones y querer ir a un Puja. Si queréis ir al Puja id, y no solo tendréis facilidades en el trabajo sino que además seréis promocionados. Pero no tenéis fe en vuestro ascenso, no tenéis fe en que sois los elegidos; esta fe os falta debido al materialismo.

Recientemente en América, tenemos un buen sahaja yogui, David Damby (??), y le dije "David, es mejor que seas tú el líder de América, porque esta persona no está bien, etc..." "Muy bien, Madre", me dijo inmediatamente. Él vive en Honolulu, los programas se hacen a través de Los Ángeles y parecía muy extraño que le hubiera pedido a él que se hiciera cargo, pero, ¿dónde estamos? Nosotros somos las personas que han sido bendecidas con todos los poderes, hemos sido bendecidos con ello, pero no queremos practicarlo, no queremos comprobar nuestros poderes, y seguimos preocupados por nuestros niños, por el sari que nos vamos a poner o por el líder, o por quién debe dar el líder. Todas estas cosas no nos van a ayudar en absoluto. No estáis aquí para eso, estáis aquí para llegar a ser el Espíritu y extender después la luz del Espíritu. Nada es importante. Una vez que empecéis a actuar así os sorprenderá ver cómo funciona la fe, pero no es una fe ciega. No tendréis ni que decir nada, simplemente veréis que funciona. Es cuestión de pocos días el obtener resultados, el obtener aquello que tanto habéis anhelado, incluso algo material o superficial; pero todavía os falta lo más importante. Digamos que alguien quiere dedicar su, así llamada, vida a Sahaja Yoga. Entonces, ¿qué hacéis? Lo primero es que debéis ver cómo está vuestra fe respecto a todo. ¿Creéis realmente en ello o no? Si creéis, ¿qué habéis hecho al respecto? En este punto debéis hacer introspección, ¿qué estáis haciendo? ¿Qué tenemos que hacer? ¿Hasta dónde hemos de llegar? Este es un tiempo muy importante, y vosotros sois almas muy importantes que os encontráis aquí sentados hoy, pero, si no valoráis vuestro propio sistema, ni os valoráis a vosotros mismos, ¿por qué habría Dios de preocuparse por vosotros? ¿Por qué debería Dios preocuparse en daros ideas?, o incluso, ¿por qué debería mostrar interés por vosotros si sois personas de tal nivel?

Por tanto, hoy tengo que deciros en este Puja, en el que se da esta combinación del día de Dasera y yo me encuentro aquí -y también es el último día del Puja a la Devi- que deberíamos hacer introspección y preguntarnos: ¿Qué he hecho por Sahaja Yoga aparte de cuidar del niño, cocinar para el marido...? Y los hombres también se lo deben plantear. ¿Qué hemos hecho? ¿Qué hemos hecho por Sahaja Yoga? Quiero ir a ver a esta persona, a esa otra, a este político, pero, ¿para qué? Ellos deberían venir a verte a ti. Pero la fe en vosotros mismos es muy pobre y creo que esa es la razón principal de este estancamiento. Esta fe de la que hablo no es una fe ciega, sabéis lo que es, habéis visto mis fotografías, estáis convencidos de ello, aunque no se trata de ser convencido de nada, pero lo que ocurre es que esta fe no es "una" con vuestro corazón. No está en vuestro ser, sino afuera, y me decís "vale, Madre, haremos esto y aquello".

Pero ante mí, la situación es que me siento obligada a deciros que hagáis algún tipo de tapasya. Le pregunto a alguien, ¿meditas? "¡No, Madre...!" Pero, entonces, ¿qué estáis haciendo aquí? "Madre, hemos venido porque tengo un dolor en la rodilla, pero honestamente, no medito. Te pido por favor que cures mi rodilla, pero soy honesto, no medito. "¿Cuántos de vosotros meditáis realmente por la noche? Guido me dijo: "Madre, si les dices eso dirán: vale, entonces meditamos por la noche pero no por la mañana, porque Madre ha dicho que meditemos por la noche". No hay ningún entusiasmo ni iniciativas propias...", bueno..., si no meditamos hoy meditaremos mañana, Madre dice que no es necesario..., no es importante, está bien..." Y así os quedáis satisfechos, pero, ¿quién es el que pierde? Yo no. Yo no necesito Sahaja Yoga; y estoy haciendo toda una tapasya por vuestro Sahaja Yoga, ¿qué tal si vosotros también hacéis un poco de tapasya?

Lo que os estoy intentando decir es que ahora tenéis vuestra Realización, y habéis llegado a un estado en el que tenéis el conocimiento interior, la conexión con el Espíritu y con Dios Todopoderoso. Ahora sabéis muchas cosas, y a pesar de ello todavía no hacéis las cosas desde el corazón, desde vuestro deseo más sincero; el engañarse a sí mismo no ayuda a nadie en absoluto, nunca. Todo esto no se lo estoy diciendo a nadie en particular sino a todos vosotros, así que, no os engañéis a vosotros mismos. Estáis aquí para un gran propósito, y este es un propósito colectivo, el liberar a nuestra mente de todas estas fuerzas destructivas y después extenderlo por todas partes hablando de ello. Mi propia convicción es esta: que algo tiene que ocurrir a los sahaja yoguis para que se den cuenta de lo importante que es el desarrollar algo que está en nosotros, que es nuestro potencial y que está a punto de florecer.

Esta responsabilidad, tanto si sois judíos como cristianos da igual, está ahí afuera para todos vosotros. Y para eso habéis entrado en un reino de una consciencia nueva, en un reino de una vida más elevada, donde conocéis vuestro Ser interior, donde sabéis lo que está bien y lo que está mal; y si después de saber todo esto no crecéis, entonces, ¿a quién se va a culpar por ello? Así llegamos a un punto en el que hay que entender la importancia de este Kali Yuga en el que vuestra Madre está aquí para ayudaros, para cuidar de vosotros muy amorosamente y deciros todo con gran ternura. De hecho, no puedo enfadarme con nadie por más de un minuto. Así estoy aquí para explicaros lo que deberíais haber hecho, lo que podríais hacer, y lo que tenéis que hacer. Esto lo he estado haciendo constantemente, haciéndoos comprender las cosas, explicándoos todo y diciéndoos que este es vuestro propio poder, que tenéis que cuidarlo, alimentarlo. Tenéis muchos libros y muchas maneras por las que podéis entender todo esto. Pero lo que hacéis es decir "tengo este conocimiento interior para construir todo esto, pero no lo hago". Tan simple como eso, simplemente no lo hago; tengo este conocimiento interior, tengo un "doctorado", pero estoy loco, es así.

En Sahaja Yoga hay muchas personas muy bien equipadas mentalmente, lo sé, pero en lo que se refiere a lo que es realmente seguir Sahaja Yoga, para eso no están disponibles. Así que, ahora os estoy avisando. Ya lo dijo Cristo, algunas semillas que han germinado caen sobre terreno no fértil y mueren. El juicio está constantemente teniendo lugar, ahora incluso cuando os estoy hablando el Juicio continúa. Así que, cada noche tenéis que meditar y plantearos: en el día de hoy, ¿qué he hecho? ¿Qué he conseguido? Pero sois tan calculadores...", si voy a tal sitio a las cinco, estaré de vuelta a las siete, si no, no llegaré a tiempo para esto .... (cambio de cara A a cara B, no es copia Master).

....se dice que Dasera es un Puja para el lado derecho, porque se adora a Shri Rama y a su arco. Pero pensad en esta encarnación. Pasó catorce años en prisión; por alguna razón particular tuvo que hacerlo. Para cualquier persona el hacer esto solo por un año sería terrible. Él fue al desierto estos catorce años, pero, de hecho, para Él era como la cárcel. Era hijo de un rey y ni siquiera tenía un lugar para vivir o para dormir. A donde quiera que fuera tenía que construirse su pequeña choza. Pero tenía que hacerlo, ahora bien, ¿por qué? Porque tenía fe en Sí mismo. Él era Shri Rama y debía hacer todas estas cosas, tenía gran fe en Sí mismo y en Dios , sabía que cualquier cosa que hiciera la hacía como deseo de Dios. Esto es lo que tengo que hacer y no me importa si tengo que enfrenarme a Ravana o si tengo que hacer cualquier otra cosa, no me importa.

Yo soy un sahaja yogui y tampoco me importa. Mi trabajo es extender Sahaja Yoga, limpiarme a mí mismo y conocerme a mí mismo. Este es mi trabajo y esto es lo que tengo que hacer. Nada me importa si me admiten en la Universidad o no, o si alguien tiene que viajar en avión, nada me importa si consigue el billete o no. No lo creeréis pero en cuanto expreséis la fe en vosotros mismos, os admitirán en la universidad, tendréis el billete, todo lo tendréis a vuestra disposición. No tendréis que luchar por nada ni preocuparos por nada, simplemente lo tendréis. Esto me ha ocurrido durante toda mi vida, aunque mi fe es sólida como la roca de Gibraltar, sin duda, porque sé lo que soy y lo que se espera de mí, así que, no tengo ningún problema. Tengo toda la fe, conozco a todo el mundo y puedo distinguir perfectamente cómo es cada uno. Puede que a veces no lo aparente, y puede que diga, "está bien, esto está bien...", pero lo que sé con toda seguridad es lo que yo soy y lo que tengo que hacer.

De la misma manera vosotros debéis saber quiénes sois, porque sois una categoría de gente diferente, no sois quienes necesitáis protección de Dios o de la Madre, nada de eso, sino que sois vosotros los que debéis dar protección a otros, debéis dar luz a otros, tenéis que mostrarles el camino. Estáis aquí para esto y no para comprar una casa, o para conseguir descuentos en vuestros impuestos. No estáis aquí para eso, olvidad todas esas tonterías, a la larga seguro que os acaban haciendo los descuentos. Yo lo he comprobado por mí misma. Yo nunca me preocupo cuando viajo de si hay billete o no, o de si quedan plazas o no, no me preocupa lo más mínimo. Cuando viajo ni siquiera pienso que estoy viajando, simplemente que estoy allí, eso es todo.

A veces digo cosas que parecen muy jactanciosas o del ego, como el decir que esta Iglesia Católica está a punto de morir, lo he dicho. Si os preguntan a vosotros diréis: "Puede ser, quizás ...". Uno tiene que cambiar su propio lenguaje, su estilo, y nuestro entendimiento debe ser que somos gente dura, somos gente dura con nosotros mismos, pero con los demás somos amables, dulces. En lo que a nosotros se refiere, somos duros, muy duros. En cierta ocasión ocurrió que fuimos de viaje y paramos en una casa muy grande donde no había nada para dormir; bueno, había una cama pequeña donde durmió mi marido, pues él no podía pasar sin ella. Pero yo me dije, vale, no importa, acepta el desafío y dormí sobre el suelo. Al día siguiente me dolía el cuerpo y le dije a mi cuerpo: "¡Compórtate, porque también vas a aprender a dormir sobre piedras!" Y durante un mes dormí sobre el suelo. Por tanto, uno tiene que ser duro con su cuerpo, y con su mente cuando le sugiere ideas materialistas o que retardan su crecimiento espiritual. Pero uno aprende a escapar y escapar; finalmente se llega al último punto donde uno ya no mira por su vida material ni piensa en su vida mental, ni en su vida espiritual sino que simplemente uno se siente muy libre y puede hacer todo lo que quiera. Supongamos que llegáis a un estado así, entonces decís: "¡Oh!, he llegado a este estado". Pero, ¿cómo os lo vais a creer? ¿Cuál es la prueba de que habéis llegado a ese estado? Tendrá que verse, ¿no?

Hay un gran mito en Sahaja Yoga que es este de los sahaja yoguis "viejos" o "antiguos"; ¿antiguos?, no puedo entenderlo, ¿qué es esto?, ¿cómo puede haber antigüedad en Sahaja Yoga? No puede existir esto en absoluto. Es como si alguien entra en el mar y ve que algunos llevan años ahí agarrados a la tierra porque tienen miedo de nadar y otros que llegaron solo ayer puede que estén saltando, avanzando, gozando del mar; así que, ¿qué es esto de antigüedades en Sahaja Yoga? No tenemos nada que se le parezca. No hay antigüedad. También hay otro mito, que quizá sea una excusa, no sé, pero es algo muy común el decir que tal persona es un sahaja yogui muy antiguo. No puedo entenderlo, es como hablar diciendo que un burro es más antiguo que otro.

Otra cosa de la que padecemos mucho es este "Madre lo dijo". Hay muchas personas que dicen: "Madre me llamó y me dijo esto". ¿Y qué es lo que dijo? "¡Oh!, que eres un gran sahaja yogui, esto y aquello". Hay dos posibilidades: puede que lo haya dicho solo para engañaros, pues soy Maha Maya. O quizá lo dije solo para mimarle el ego y que así viniese a Sahaja Yoga. Así usáis este "Madre dijo..." Y luego la gente dice: "¡Oh, qué sahaja yogui!" Estos sahaja yoguis utilizan palabras muy jactanciosas, muy jactanciosas para impresionar. Por tanto, el juicio de cómo es un sahaja yogui está no en lo que aparenta sino en lo que ha alcanzado o conseguido. He visto también que algunos sahaja yoguis son extremadamente arrogantes, creen que son los mejores; todo esto aún está ahí, he visto a muchos sahaja yoguis así, con esta arrogancia, intentan constantemente hacer un show de su persona. Ahora bien, ¿cuál es el estilo del sahaja yogui que no es así? Simplemente será testigo de todo, gozará y se reirá de todo lo que ocurra: "¿Qué hace este hombre hablando así...?"

Una persona que sea un sahaja yogui, es una piedra preciosa. Dondequiera que vaya, toda la gente dirá de esa persona que es una joya. Mi propio estilo es este, que, cuando veo a una persona o a un sahaja yogui, lo primero es que entro dentro de mí misma, esto lo primero. No sé si vosotros podéis hacerlo, pero yo lo hago, y luego miro a esta persona desde una perspectiva muy diferente, con un entendimiento diferente. Y todos estos poderes también están dentro de vosotros. No son solo mis poderes, vosotros también los tenéis. La única diferencia entre vosotros y yo es que yo tengo absoluta fe en mí misma y vosotros no tenéis ninguna fe en vosotros mismos.

Nos encontramos ahora en un punto en el que tenéis que ver quién va a conseguir algo más elevado y quién no; y después comparar cuál es vuestra posición en relación a esa persona. Se ha dicho siempre que hay que sufrir mucho, que hay que hacer esto y aquello; no es así en absoluto, ¡gracias a Dios! Pero, ¿qué le ocurrirá a un sahaja yogui?, ¿cómo sabréis quién es un sahaja yogui?, ¿cómo sabréis quién es sahaja yogui solo en apariencia? La única manera de saberlo es que vosotros evolucionéis, que crezcáis, de forma que os convirtáis en un espejo y veáis claramente qué tipo de persona es la que tenéis enfrente; al mismo tiempo os veis a vosotros mismos, cómo sois.

La charla de hoy es especialmente inspiradora, para dar entusiasmo. Pretende comunicar que todo lo que hoy hemos hecho es entender nuestro propio sistema de valores, nuestra propia vida, deberíamos entender por qué estamos en esta tierra, cuál es nuestro propósito, qué tenemos que lograr; y para todo ello os doy todas mis bendiciones desde mi corazón. Y quiero que aceptéis mis bendiciones de ser las grandes luces del deseo de Dios. Intentad comprender la importancia de los tiempos en los que habéis nacido, y que os habéis convertido en gente hermosa de Dios.

Que Dios os bendiga.