13 octubre 1991
Navaratri Puja
Campus, Cabella Ligure (Italy)
Navaratri Puja. Cabella Ligure, Italia. 13 de octubre de 1991.

Hoy nos hemos reunido aquí para celebrar el Navaratri Puja. En nueve ocasiones se han manifestado las principales encarnaciones de la Madre del Universo. Se manifestaron con un propósito. Este propósito era proteger a sus bhaktas, a sus discípulos, a sus niños. Este amor es imperativo, Ella no podía evitarlo. El amor de Madre es ineludible. No puede evitarlo y tiene que encarnar y trabajar para la protección de sus niños.

En los tiempos modernos esta protección ha cambiado de forma. En aquellos tiempos el demonio trataba de dañar y destruir a la gente que era honrada, a los bhaktas, a los que hacían buenas acciones, a aquellos que querían llevar una vida religiosa. De modo que, para salvarlos, Ella encarnaba. Encarnaba para protegerlos. Pero ellos sabían lo que era correcto y lo que estaba mal. Querían preservar la bondad en su vida, su preciosa vida. No les preocupaba el dinero ni el poder, simplemente querían su vida, es decir, querían estar vivos para adorar a la Diosa. Y cuando eran dañados, atacados o destruidos por las fuerzas demoníacas, Ella tenía que manifestarse.

Pero en los tiempos modernos esto se ha hecho mucho más complicado porque los tiempos modernos son complicados. En primer lugar, en la mente, en el estilo de vida, en la sociedad de los seres humanos buenos y correctos ha entrado el miedo a lo erróneo. Tienen miedo de sus curas, de sus iglesias, de sus templos, de sus mezquitas, que es todo falso. No tienen temor de Dios, no creen en Dios. Piensan que ellos mismos han creado a Dios y pueden manejarlo. Pero, ¿quién es Dios? Por el modo en que se comportan podéis ver claramente que no reconocen la existencia de Dios. Dios Todopoderoso, que es un Dios colérico. No les preocupa en absoluto lo que puede sucederles. Ni siquiera creen en una segunda vida ni en la resurrección. Tienen miras muy cortas y son gente demoníaca que hace todo tipo de cosas demoníacas.

Así pues, de algún modo, tan pronto como nacéis lleváis alguna clase de etiqueta. Cuando nacéis pertenecéis a este grupo, a tal otro o al de más allá. Y la primera marca que recibe un hombre moderno es la de la religión a la que pertenece. No puede evitarlo, tiene que aceptar de buen grado el pertenecer a cierta religión. Antes incluso se mencionaba en el pasaporte, aunque hoy día ya no se hace. Pero te solían preguntar: "¿Cuál es tu religión?" En India, si no tenías religión ni siquiera te daban el pasaporte, porque no eras una persona demoníaca cualificada o no seguías a gente demoníaca cualificada.

De modo que aquella gente buena y crédula, aquella gente correcta que creía en Dios, desarrolló un temor en su mente a causa de esta gente falsa. Como cuando dicen: "Si no haces tal cosa, si no nos pagas dinero, entonces Dios se enfadará. Si no vienes a confesarte, entonces Dios se enfadará contigo. Si no toleras nuestras estupideces Dios se enfadará contigo". Todas estas cosas empezaron a entrar en la cabeza de la gente con mucha facilidad. En algunas religiones creen que beber no es pecado. En otras religiones creen que casarse con muchas mujeres no es pecado. En otras creen que se puede tener un sistema de castas. Todo esto es anti-Dios. Una actividad absolutamente anti-Dios, que ha sido perpetuada en la sociedad por los sacerdotes, que se supone que están a cargo de la religión. Este es el primer condicionamiento horrible que tenemos, cuando empezamos Sahaja Yoga.

De modo que nos resulta muy difícil empezar algo nuevo. Y así, la primera protección que ha de dar la Madre es frente a este condicionamiento. El segundo es el del país al que pertenecemos. O bien pertenecéis a este país o a aquel otro o al de más allá. Y hoy día todos los países están compitiendo entre sí, en todo tipo de corrupciones, mafias, todo tipo de cosas. De repente se descubre algo. Tenéis fe en un país y se descubre que estaba apoyando a cierta persona en secreto. Ya sean países democráticos o de cualquier tipo, en todas partes está funcionando una clase de mafia. De modo que las así llamadas leyes son solo para la gente sencilla, crédula, para los buenos ciudadanos, y no para la gente que les impone dichas leyes. Ellos reciben sobornos y todo tipo de cosas. Se supone que ellos están a cargo de las leyes a pesar de que hacen toda clase de cosas ilegales. Como ellos han hecho las leyes saben cómo ser ilegales. Este es el segundo temor que está en la mente de la gente en los tiempos modernos.

Lo tercero han sido las guerras. Ha habido una guerra tras otra y, de este modo, mucha gente ha desarrollado un temor por las guerras. Como resultado han desarrollado un estúpido ego que dice: "Es para protegernos a nosotros mismos". Para protegerse a sí mismos han construido un gran ego y ahora se están volviendo gente muy agresiva. Y a una escala mayor este temor puede ser dirigido en cualquier dirección, hacia cualquier persona. Después viene el miedo al racismo. Me han dicho que ahora está apareciendo el neo-nazismo como una pequeña serpiente. Este es otro aspecto muy peligroso, y que está creciendo.

Después está la mente de los buscadores. Como son buscadores han ido a muchos gurus, han leído toda clase de libros en su búsqueda. En su búsqueda han bebido todo tipo de aguas y han desarrollado todo tipo de enfermedades. ¿Qué podemos hacer? Después de todo estabais buscando, estabais sedientos. Esto ha de ser perdonado. Pero de este modo han desarrollado problemas de todo tipo, no solo en su cuerpo sino también en su cerebro. Esto es algo muy delicado. Si le dices a alguien que ha estado en tal y cual guru no querrá oír nada, porque para él su guru es incuestionable. No puedes decir nada en contra de su guru. Cuando empiece a sufrir quizás lo acepte. Pero sacarle a este guru es también muy delicado, porque al hacerlo esta persona puede resultar dañada. De modo que es una operación muy delicada.

Después está la sociedad moderna, cuanto menos digamos mejor. Las normas de la sociedad moderna han sido establecidas por gente sin carácter, como Freud -que no tenía ningún sentido de la moralidad- o por borrachos. Aunque no hay estatuas de ningún borracho. Pero en la mayoría de los casos, si veis el abandono de nuestro sistema de valores, ha sido a causa de la bebida. Aunque la bebida existió anteriormente nunca llegó hasta este extremo. Quiero decir, no todo el mundo era borracho; sin embargo hoy día todo el mundo puede ser un borracho. Y no sienten ninguna vergüenza por ello. Con la bebida nuestro sistema de valores empezó a decaer y la gente ahora acepta que lo normal es el abandono. Este es otro aspecto.

Anteriormente los padres solían mantener a alguien que quería dedicarse a Dios, si quería llevar una vida correcta o alcanzar algo grande. Si veían estas cualidades en su hijo se sentían felices. Pero hoy día es justo al revés. Esto no es del agrado de los padres. Es como si los padres no tuvieran nada en sí mismos, y por eso quisieran mantener y poseer a sus hijos y a sus nietos. Son criaturas sin cerebro, porque les han lavado el cerebro y no queda nada en ellos. Luchar con los padres es otro gran problema. De modo que también existe el temor de: "Mi madre no debe enterarse, mi padre no debe saberlo", o esto o aquello. Podemos decir que en todas direcciones el miedo está ardiendo en llamas.

Y ahora estamos aquí en el Kali Yuga, donde hemos empezado Sahaja Yoga. Ahora, hemos de trabajar en nuestra protección de forma recíproca. Por supuesto la Madre siempre está ahí para protegernos. Sus poderes siempre están ahí para protegernos. Pero sorprendentemente, en los tiempos modernos, hay una condición que ha de ser satisfecha. Porque en aquellos tiempos lo bueno era bueno y lo demoníaco demoníaco. No había mezcla. Cuando imploraban a la Diosa la aceptaban. Ella venía en su verdadera forma y hacía el trabajo.

Pero en los tiempos modernos, debéis saber que todas estas cosas demoníacas también están enganchadas en vuestras cabezas, un poco aquí y allá. La gente es extremadamente superficial. Son muy propensos a seguir a las masas, a las modas y cosas por el estilo. Su personalidad no está tan desarrollada como en aquellos bhaktas que sabían que eran justos, que estaban haciendo lo correcto y permanecían con firmeza en su posición.

Por eso, el sahaja yogui moderno es muy diferente del sahaja yogui de la antigüedad. Porque antiguamente no era fácil obtener la Realización. La conseguía uno entre un billón o entre un trillón. Y debían trabajar muy duro, muy duro para limpiarse y desarrollarse a sí mismos. Igual que una obra artística que necesita mucho tiempo y se hace con gran cuidado es, definitivamente, mil veces mejor que este arte moderno donde simplemente ponéis dos o tres líneas y ya está. El ser humano actual es como este arte moderno. Ponéis una línea y decís: "Debes ver tal cosa en esa persona, debes tener tal identidad". ¿Qué identidad puede tener la gente? Con una línea decís: "¡Descubre la identidad!"

De modo que los sahaja yoguis que están hoy aquí, tienen que darse cuenta de que todas estas cosas están alrededor nuestro, y que las fuerzas demoníacas también están ahí. Algunas están en nuestro interior y otras en el exterior. Y aunque parece una tarea muy difícil, en realidad no es así.

Una condición, si podéis entenderlo, es que debéis reconocerme. Ya sé que soy Mahamaya, que soy muy astuta con esto. Pero soy verdadera, no tengo lágrimas de cocodrilo. No puedo tenerlas. Soy verdadera, pero también soy Mahamaya.

Entonces, ¿qué debéis hacer para reconocerme? Si me reconocéis, estáis protegidos. Y la limpieza en Sahaja Yoga es muy simple si sois colectivos. Si no sois colectivos debéis saber que hay algo mal en vosotros. Si sois colectivos es como si tomarais un baño en el río Ganges. No tenéis que ir a los Himalayas, no tenéis que hacer demasiada sadhana individual, nada de eso, simplemente sed colectivos. Si sois colectivos, si disfrutáis de la colectividad, entonces debéis saber que estáis limpios. No tenéis ninguna mancha, estáis absolutamente bien.

La segunda parte es este asunto de Mahamaya. Yo tengo que estar muy cerca de vosotros, hablaros, tener una relación, contaros todo acerca del yoga, haceros completamente conscientes de vosotros mismos. Esto debía hacerse y -con todas las complicaciones que hay en vuestra mente, en vuestro corazón y en vuestro cuerpo- tenía que hacerlo funcionar. Acercarme a vosotros en mi forma real podría haber sido muy peligroso, por eso tenía que venir como Mahamaya.

Pero a pesar de todo, si podéis entenderme y reconocer que soy una personalidad divina, una encarnación, sabed que eso es todo lo que quieren las deidades. Entonces cuidarán de vosotros en todos los modos posibles. Os darán todos los poderes, toda la satisfacción, toda la protección que queréis.

Para una mente racional es muy difícil entender: "¿Cómo puede estar la Adi Shakti en un cuerpo? ¿Cómo puede el infinito volverse finito? Los seres humanos no pueden hacerlo. Solo son seres humanos. Pero Dios puede hacerlo. Después de todo es Dios. Y tenéis muchos milagros, muchas fotografías, muchas cosas que podéis ver, para que podáis reconocerme.

Veo que cuando la gente habla conmigo lo hace de un modo un poco frívolo, no con la profundidad, ni con el sentimiento de que yo soy Mahamaya. Algunos de ellos incluso me contestan. Algunos de ellos, cuando les digo algo, están preparados para darme una contestación, una explicación.

Por supuesto, yo os he dado esta libertad deliberadamente, pero debéis entender que tenéis que hablar conmigo en el modo en que lo haríais con la Adi Shakti. Esto es muy importante. También es muy importante cómo os comportáis. No debéis ser artificiales, ni superficiales. Lo mejor es poner vuestra mano en el corazón, ambas manos, y tratar de sentir esto. Vuestra Madre es la Adi Shakti. Ella ha creado todo este Universo, ha creado todo el mundo y siempre está ahí para protegeros. Ni siquiera Shri Krishna pudo proteger a los Pandavas, tuvieron que ir al bosque y tuvieron que sufrir. Pero no los sahaja yoguis. Tan pronto como sé de vuestros problemas, mi atención los soluciona. El mismo Shri Rama tuvo que ir a la selva. Se os da toda esta protección porque sois buscadores de la verdad. Y la verdad es que yo soy la Adi Shakti encarnada.

Una vez que esta verdad se vuelve una con vosotros no hay nada que temer. Porque todas las deidades conocen este hecho, conocen a esta encarnación muy bien. Todas ellas están preparadas para esto y harán cualquier cosa para confirmar vuestra fe. Intentan mostraros mis fotografías de muchos modos, en el cielo, de esta o aquella forma, hacen todo tipo de cosas. Solo Dios sabe qué harán hoy. Están ansiosos. Están detrás del escenario, delante del escenario, por todos los lados del escenario, escuchándome, sintiéndose muy felices de que os estoy diciendo la Verdad. Pero ellas me reconocen y actúan de tal modo que nunca desobedecen. Si vosotros os comportáis del mismo modo, estaréis completamente protegidos de todos estos problemas que os he contado. Yo no os diré que no deberíais odiar a nadie, no lo haré... De ningún modo. Yo no os diría que no debéis robar. No os diría que no os aprovecharais ganando dinero con Sahaja Yoga. Ni siquiera os digo que no bebáis, que no fuméis, nunca os lo he dicho.

Pero de un modo automático, una vez que sabéis frente a quién estáis, quién os protege, automáticamente lo sabréis. Automáticamente. No tendréis ningún miedo. Una vez que me habéis reconocido no tendréis ningún miedo de nadie. Y cuanto más mostréis este reconocimiento, cuanto más lo asumáis, os elevaréis más y más. No solo espiritualmente, sino de todos los modos posibles: mentalmente, socialmente, económicamente, políticamente. Es muy importante el que me reconozcáis, no solo como una Madre que os ama mucho, sino como una Madre que es muy poderosa para protegeros, muy poderosa. Si os dais cuenta de esto y si lo sentís dentro de vuestro corazón, incluso aunque os corrigiera en algún momento, en vez de sentiros tristes por ello, sentiríais: "¡Que afortunado soy, que la Adi Shakti misma me está corrigiendo! Ella tiene interés en mí. ¡Que afortunado soy de haber nacido en este tiempo, de estar con Ella en su gran trabajo! ¿Qué habré hecho para merecerlo?"

Este reconocimiento mismo llenará de satisfacción a todas las encarnaciones del Navaratri.

De modo que hoy estamos adorando a Durga, a Kali, a todas estas grandes Diosas, a esos Poderes, incluso a Radha. Radha fue quien mató a Kamsa y no Shri Krishna. El tuvo que pedir a Radha que le matara. El poder es el que mata.

De este modo, debéis daros cuenta de que vuestra Madre es la Adi Shakti.

Yo conozco a muchas personas. Hay un hombre que trabaja en el aeropuerto de Londres. Alguien trató de crearle problemas. El dijo: "¡Tened cuidado...! ¡Mi Madre es muy poderosa, no la conocéis!" Al día siguiente aquel hombre perdió su trabajo, perdió su negocio, perdió esto y aquello. Entonces fue a ver a este hombre y le dijo: "¿Quién es tu Madre? ¡Permíteme verla!"

Había un campesino cerca de Rahuri y por la noche tres hombres vinieron a robarle un poco de caña de azúcar. Al día siguiente vinieron a verle y le dijeron: "¿A qué Diosa adoras tú?"

El dijo: "¿Por qué?"

"Había tres personas muy fornidas vigilando tu campo y nosotros pensábamos coger un poco de tu caña de azúcar, ya que tenía muy buen aspecto. Entonces ellos empezaron a pegarnos. Aunque no resultamos dañados".

De este modo, detrás de este reconocimiento están todos los poderes. Hay muchas, muchas historias que puedo contaros, cómo han sucedido cosas, cómo ha funcionado todo. Pero si dudáis, si todavía estáis a medio camino, entonces las cosas no funcionarán.

No deberíais preocuparos por vuestra reputación. Simplemente avanzad a toda velocidad en cualquier dirección, sabiendo que sois mis niños y que yo soy la Adi Shakti. Todo lo que parece horrible mejorará. Hemos visto lo que ha sucedido en el caso francés. No os preocupéis por nada, simplemente sabed que yo soy la Adi Shakti. Que todos los poderes de los dioses y las diosas están en mi interior. Ellos están en mi interior y están cuidando de vosotros. Pero si este reconocimiento no está ahí, ellos tampoco os van a reconocer a vosotros.

De modo que para el Navaratri de hoy os tengo que decir que intentéis tener presente que hoy estáis adorando a la Adi Shakti y no solamente a Durga. Y estáis adorando a Durga y a todas las diosas para darles vuestro agradecimiento. Porque si no os hubiesen salvado en aquellos tiempos, habríais estado tan atemorizados que os habríais hecho malas personas y no podrías estar hoy aquí. Por eso les estamos agradecidos, por salvarnos y darnos la protección en los tiempos en que estábamos desamparados.

Que Dios os bendiga.

El puja de hoy es muy sencillo. Simplemente lavaremos los Pies con un Ganesha Atharva Shersha. Cualquiera puede lavarlos. Creo que no es necesario que vengan los líderes, solo los de Inglaterra. Porque el puja de hoy lo hace la gente de Inglaterra. Por eso quisiera pedir a dos o tres personas de Inglaterra que vengan y laven mis pies.

Este es el nombre de la Diosa, Charu, que significa bella o -podemos decir- auspiciosa. Y Keshi, significa pelo, aquella que tiene el pelo auspicioso. Esta palabra, Charukeshi, proviene de Bengala. Esta es la descripción de la Diosa, sus nombres. El nombre de la Diosa. De modo que es el momento apropiado.

Hoy es el día en que la Diosa va a Bengala. Y es maravilloso que él vaya a tocar la raga Charukeshi, que es Bengali. Esta raga proviene de Bengala.

Hay tantas coincidencias, tantas coincidencias, debe de haber un sentido en todo ello.