Shri Shiva puja. Delhi (India), 14 de Febrero de 1999.

Primero hablaré en el lenguaje hindi y después en inglés.

(Parte en Hindi)

Hoy estamos aquí reunidos para hacer la Puja de Shri Maha Deva – Shri Shiv Shankara. La Puja de Shiva ha sido aceptada ampliamente por la gente debido al énfasis de Adi Shankaracharya. Dos sectas han surgido en el Sur de India: una es la de los shaivitas y la otra es la de los vaishnavitas. Los shaivitas son los adoradores de Shiva y los vaishnavitas son los que adoran a Vishnu. En nuestro país somos muy expertos en dividirnos. También dividimos a las deidades pero cuando tratamos de reunirlas las cosas toman una forma muy mala. Como por ejemplo el culto de Ayyappa en el Sur de India. Según ellos cuando el Dios Vishnu asumió la forma de Mohini y ella tuvo un hijo de Shiva. ¿Cómo es posible que tales creencias sin sentido sean propagadas en nuestro país? Entonces forman diferentes grupos y encuentran excusas para pelear entre ellos. Si los indios no tienen nada para pelear entre sí, entonces crean algo en su propia imaginación. 

Asimismo estas dos cosas están conectadas entre ellas como el sol está conectado con la luz solar; la luna está conectada con la luz lunar y la palabra con su significado. Quiero decir que Sopan Marga, el camino del Sushumna, el sendero central es el sendero de Vishnu. A través de este sendero obtenemos el principio de Shiva. El principio de Shiva es el destino y el camino lo hace Vishnu. Este sendero central es la creación de Vishnu y la Adi Shakti. Shiva no toma parte en esto:  Él se sienta cómodamente en su asiento sin preocuparse de nadie; si alguien desea venir puede venir. Para alcanzar el principio de Shiva debemos ir por este sendero de Vishnu (sendero del Sushumna) y corregir todos los centros que son creados ahí. Cuando los centros son limpiados se abre el sendero de Vishnu y nuestro ascenso comienza. Muchas veces les he hablado acerca de estos centros. Hay un centro en el Corazón que llamamos “Corazón Izquierdo”. Este no es el centro del corazón. De cierta manera es el reflejo de Shri Maha Deva en el corazón. La morada de Shiva está por encima de nuestras mentes y pensamientos.

Para alcanzar el principio de Shiva debemos ver que tan puro es nuestro corazón. En nuestro corazón le damos lugar a muchos pensamientos malvados, como por ejemplo los celos. No sirve de nada convertirse en celoso, nunca debemos sentirnos celosos de nadie. Aun cuando nos hayan acosado o nos hayan dañado, los celos no te hacen ningún bien. Si tu corazón es puro entonces el espejo en que Shiva tiene que reflejarse se mantendrá puro. Pero si está lleno de celos entonces el espejo no puede permanecer limpio y así el reflejo de Shiva no será perfecto. Enemistad y sentimientos negativos hacia otros no deben ser acogidos en el corazón. Es por eso que Cristo ha dicho que debemos perdonar a todos. Perdonar es muy importante. Muchos santos antes y después de Cristo han dicho lo mismo: “perdona a todos”. En el momento en que perdonas a tu enemigo inmediatamente Shiva toma el control. El poder de Shri Mahadeva (Dios Supremo) es el más sutil y castiga al que comete maldades de manera precisa. Este es el trabajo de Shri Shiva, no de ustedes. Es muy malo tener envidia de quien sea.

Sin embargo encuentro que hasta en Sahaja Yoga hay muchos celos. Los Sahaja yoguis están celosos entre sí. Si una persona es nombrada fideicomisario entonces algún otro se siente celoso. Estos nombramientos no significan nada en Sahaja Yoga. Es todo falso, es el drama de su Madre. Su Madre ha extendido una red de maya (maya jalam, los trucos de la ilusión). Aun así los perturba, ¡una persona se siente perturbada y los demás se sienten mal acerca de esto! No entiendo que debo hacer. En diferentes países del mundo está sucediendo un trabajo de Sahaja Yoga enorme y necesito alguien que sea el enlace entre los yoguis y yo. Claro que ahora las cosas se están resolviendo pero les sorprenderá que hasta este día hay mucha discusión acerca de quién es el líder  y quien es qué.

En segundo lugar, los indios se sienten celosos en materia de dinero. Aún en Sahaja Yoga la gente tiene celos en materia de dinero. Algunos tienen más dinero y otros menos. Mientras hacen trabajo de Sahaja se fijan en cuanto dinero ganan otros y cuanto dan por Sahaja Yoga. La persona que tiene un corazón obsesionado con dinero no tiene ninguna utilidad en Sahaja Yoga ya que el materialismo ha atrapado su corazón. Si están atrapados en las garras del materialismo entonces su ascenso es muy difícil. Esta es la especialidad de nuestro país, no lo he visto en países extranjeros. En Rusia y los países del bloque oriental hay muy poca riqueza pero no se preocupan del dinero. Sus corazones son mucho más puros, muy puros. Bhatki (devoción) es solo posible con el corazón puro. Antes de meditar nos lavamos las manos y nos bañamos, sería mejor si purificáramos nuestro corazón y rogáramos al Divino que remueva todas las negatividades dentro de nosotros.

En tercer lugar están los seis enemigos. De todos estos, Shri Krishna ha puesto énfasis en krodha (ira). La ira es el peor de los enemigos ya todas las otras negatividades emanan de krodha. La ira nos trae un apego y luego la persona se arrepiente de lo que ha dicho, pero en el ataque de ira la persona se sale de su propio control y bruscamente dice lo que estaba escondido en su corazón desde hace tiempo, eso sale de su boca. Debemos tener cuidado de esta ira. Debemos reflexionar cual es la razón por la que nos enojamos.

Hay gente que está enojada con una persona en particular, otros enojados con la sociedad. La gente se enoja por diferentes causas pero debemos pensar ¿por qué nos enojamos? Alguien Me dijo “Shri Mataji, nos sentimos muy enojados si alguien habla en Tu contra.” Pero si alguien habla en contra de Mí entonces realmente siento ganas de reírme de esa persona, porque no significa nada que hablen en contra de Mí. Voy a amar a todos aunque hablen en contra Mía. ¿Qué puedo hacer? Algunas personas son insensibles, debemos sentir pena por ellos. Tenemos que pensar que esa persona es un gran tonto y deberíamos mirarle con mucha compasión. Esta actitud aplacará su rabia. En nuestro país hay diferentes tipos de gentes y organizaciones que se enojan. Estarán enojados con alguien, golpearán y matarán a otros. Esto se está convirtiendo en una maldad social. Esta violencia es muy peligrosa y para ejercerla reclutan un ejército propio, es muy peligroso. Si alguien hace esto para protegerse a sí mismo, se justifica hasta cierto punto, pero si alguien es un buscador (un bhakta) ¿ entonces por qué necesita protección? Un buscador esta siempre protegido. ¿Quién puede tocar a la persona en cuyo corazón reside Shri Maha Deva? ¿Quién podría destruir a tal persona? Ninguna cosa que se haga en su contra, ninguna cantidad de problemas puede destruir a tales buscadores pero los que los acosan si serán destruidos, deben tener fe completa en esto. Mantengan su corazón absolutamente puro. Solo en un corazón puro puede funcionar ya que el reflejo de Shiva cae en nuestro corazón y para ello el corazón debe ser puro.

Se dice que Shiva se enoja solo una sola vez pero yo lo he visto enojarse muchas veces. Si alguien trabaja en contra de la Adi Shakti entonces Él tiene el derecho y tiene manos muy largas. Termina con tal tipo de gente porque sabe que la Adi Shakti no lo hará por Si misma, ella no castigará a nadie. Ella perdonará a todos los que cometen pecados en contra de Ella. Los poderes de Shiva son ilimitados. Cuando Él quiere castigar nadie puede pararlo ¿Quién puede controlarlo? Él tiene sus propios protocolos que no pueden cambiar. Así que en sus vidas individuales los Sahaja yoguis tienen que seguir a Shri Shiva. Si no Lo siguen el primer problema que tendrán es con el corazón, es el primer castigo. Funciona de dos maneras: primero con la ira excesiva el corazón se bloquea  y segundo, como efecto de la ira, cuando la persona se arrepiente le da la enfermedad de angina. Ambas cosas, ira y arrepentimiento son dañinos. Pero uno no puede deshacerse de la ira porque se convierte en un hábito igual que beber. Una vez que empieza a disfrutarlo, la cara de una persona iracunda se distorsiona y entra en estado de delirio, nadie puede controlar a esa persona. Entonces como solución he pensado que si se sientan frente al espejo y se enojan con ustedes mismos, repréndanse y digan “soy el más estúpido” quizás así pueden deshacerse de su ira. Quiero decir que es posible deshacerse de la ira.

Aunque los problemas son tan complicados que es difícil encontrar soluciones. Para ir más lejos, he visto que mientras más atención le ponemos a algo lo más que reaccionamos: hay una reacción a todo y esta reacción es más grande en los países extranjeros. Si hay una alfombra inmediatamente dirán “no me gusta, me gusta”. ¿Quiénes son para decir todo esto? pero es una moda decir “me gusta, no me gusta”, como si todo mundo fuera un famoso doctor que dice “me gusta, no me gusta”. Esto no debería decirse, es indicación de un Agnya Posterior en mal estado. ¿Qué piensan de ustedes mismos que dicen “me gusta, no me gusta”? No tienen derecho a decirlo. Alguien les ofrece una hermosa flor e inmediatamente dicen “no me gusta esta flor”. No pueden entender el sentimiento de amor de la otra persona porque el principio de Shiva está ausente en ustedes. No pueden entender los sentimientos de amor con los cuales les han dado ese regalo.

En India tenemos el ejemplo de Sudama. Sudama fue a encontrarse con Krishna y llevo como regalo arroz tostado. Shri Krishna comió ese arroz con gran respeto y amor. Todo lo que se regala con amor es como el químico paras que cuando lo pones detrás del vidrio se convierte en espejo. Similarmente, si sienten amor por alguien y le ofrecen un pequeño regalo, debería ser recibido con el mismo amor y respeto. Este sentimiento de amor le da una visión sutil a la persona. Es artístico, el arte emana de ello. ¡Qué artístico es el arte del amor! Por medio de esto pueden ver cuanto amor hay en esa persona, que amoroso es, que amable y agradable es. Cuando empiecen a ver esa cualidad en otros entonces mirarás dentro de ti y pensarás: “¿qué soy?, ¿tengo tanto amor?, ¿soy tan amable?, ¿tengo tanta bondad en mi o solo estoy hablando hipócritamente y confundiendo a la gente?” De hecho que con nuestras fechorías nos confundimos a nosotros mismos y a nadie más. Con nuestros pensamientos incorrectos y estilos de vida no podemos darle consuelo a nadie: ni a nosotros mismos, para nada. De esa manera desde el punto de vista de svartha (inferencia del propio ser o interés propio). La palabra svartha es muy hermosa, Sva significa ‘ser’. Deben conocer el significado del Ser. Con este propósito la gente ofrece puja a Lord Shiva. Pero yo he visto que los adoradores de Shiva son irascibles, miserables y otras cosas más. Ninguna deidad es tan generosa y amorosa como Lord Shiva. Él es la fuente de amor. El amor que está fluyendo hoy esta emanando de Sus pies sagrados. Debido a Él, los seres humanos se están bañando en el océano de amor y todo este trabajo está siendo hecho. Después de la Realización del Ser cuando logran el estado de Jiva Atma (alma individual), entonces su atención se establece a los Pies Sagrados de Lord Shiva y las cualidades de los 5 elementos (Pancha Tattva) se hacen muy sutiles y se manifiestan.

Ya les he dicho acerca de los cuatro elementos pero el quinto, éter, no lo he explicado. En hindi le llamamos Akash Tattva (elemento cielo). Cuando un buscador asciende logra Akasha sutil, la sutileza del elemento éter. No hay necesidad de activar este elemento. Si un buscador tiene un problema este elemento esta omnipresente, está presente en todos lados. Su atención llega adonde es requerida. ¿No es simplemente maravilloso? Es así. La gente le puede llamar milagro pero no es. En Sahaja Yoga si se despierta su Shiva Tattva (Principio de Shiva), se despiertan las más sutiles de todas las cualidades sutiles y el estado más sutil dentro de ustedes. Por lo tanto lo primero es que deberíamos purificar nuestro corazón.

Hasta ahora les he hablado acerca de tres enemigos, el cuarto enemigo dentro de nosotros es ego. Las damas egocentristas se comportan como hombres: empiezan a caminar como los hombres, no pueden caminar como damas. El ego les viene por varias razones: por el dinero, belleza, educación superior, etc. Cualquiera que sea la causa, bajo el impacto de su ego las damas empiezan a caminar como hombres y los hombres afectados por el ego se empiezan a comportar como mujeres. Me refiero a que tal hombre se sienta horas frente al espejo para arreglarse, se peina una y otra vez y toda clase de estupideces. Tal persona se comporta como las mujeres. El acicalarse es para las mujeres. Tal hombre no puede caminar derecho. Si lo ven caminando por detrás sienten que es alguna dama en vestido de varón, moviéndose con ego. Se intoxican como elefantes. El ego es aparente en todas sus actividades. Es difícil entender la causa de su ego, ¿por qué se consideran como algo especial? Todas estas cosas son estúpidas y sin sentido. En Sahaja no tienen ningún sentido. Así que si te consideras algo especial estas acabado, no hay nada dentro de ti. Por lo tanto no es sabio imaginarse como una persona rica o algo grandioso. Actualmente hasta la gente pobre sufre del elemento ego, los dalits (casta baja) también sufren de ello. Esto va más allá del entendimiento: la gente habla de tal manera y piensan que son grandiosos. ¿Qué son como individuos? Pensar así de uno mismo es distanciarse del estado de gozo ya que el poder de Shiva lleva al buscador al estado de gozo. El buscador hace el bhakti (devoción) de Shiva para tener la bendición del gozo. Pero he visto que la mayoría de los devotos de Shiva son irascibles. Nadie pudo hablarles, ¿Qué caso tiene? Natraj Sakshat (El señor de la Danza) de quien emana todo el arte y el gozo, quien es el gozo encarnado, ¿cómo podrían estos pseudo devotos llamarse Sus bhaktas (adoradores)? En el cuello se cuelgan un linga (símbolo de Shiva) tan grande que podría darles un ataque al corazón. ¿Qué necesidad hay de ello? Ustedes mismos son sakshat linga swarupa (la verdadera esencia). ¡Sin que ellos lo sean dicen que son adoradores de Shiva! Por un lado hacen la adoración de Shiva y por el otro se pelean entre ellos. Los adoradores de Shiva tienen diferentes marcas, tienen diferentes maneras de ponerse sándalo en la frente y los adoradores de Vishnu tienen otro estilo. ¿Qué significa? La aplicación vertical de sándalo en la frente significa que estamos ascendiendo. Está bien, si están ascendiendo entonces deberían ser pacíficos. Debería ser aplicado en ambas maneras: vertical y horizontalmente; sino no no lo apliquen. Debería tener algún significado. Es el camino central el que nos lleva a la meta, pasando por este dejan toda sus negatividades. Antes de criticar a otros, critíquense a sí mismos.

“Yo soy así, yo soy de esta manera”, se dicen ustedes mismos y cuando empiezan a hacer eso todos los bhoots (espíritus malignos) correrán, ya que mediante el proceso continuo de pensamiento, por nuestro Agnya, hemos acumulado todas estas negatividades. El uso excesivo del Agnya crea todos los problemas, todo se convierte en una proyección mental y tal persona se convierte en muy problemática.

El mismo siempre está en arreglos. Uno no puede ser feliz dándole problemas a otros. Tendrá efecto en ustedes aun si fueran de piedra. Tendrá impacto y así la persona se vuelve miserable. Madre piensa en el bienestar de ustedes. Ella desea que estén cómodos, contentos y en paz. Ella desea que sean amados para que se vuelvan cordiales. Este es el método de Madre. Pero el método de Lord Shiva es muy diferente. El tolera hasta cierto límite y luego trata tan severamente que me aterrorizo por esa persona: ¿qué le pasará a este hombre?, ¿hasta dónde llegará?, ¿qué está haciendo El? Pero Shiva no piensa estas cosas. No perdona a los que hacen maldades. Solo perdona a los que son dignos de Su perdón. Bendice a los que meditan en El continuamente. Pero la persona que básicamente no quiere mejorar, Lord Shiva la corrige. Es cierto. Por eso debemos tenerle miedo: “Bhayankara” (aterrorizante) es uno de sus nombres. Ya que en Su furia, El no perdona a nadie. Lo peor de Su furia (kopa) es en el tiempo de pralaya la noche de disolución. En ese tiempo El destruye todo con Su furia. Les he dicho que este es el juicio final: que camino toman, a donde van, todo lo que hagan está totalmente grabado en ustedes. De acuerdo a sus acciones se van al cielo o al infierno. Es Lord Shiva quien manda a la gente al infierno, Yo no lo hago. Yo no tengo nada que ver con el infierno (narka). Pero Shiva tomará a la persona por las piernas y lo tirará en el infierno. Ustedes pueden seguir diciendo que “soy el adorador de la Madre, soy Su seguidor, ¿por qué soy castigado?” Yo no soy instrumental en esto. Una vez que alguien Me llama Madre, no puedo pensar mal de esa persona. Si Yo soy los protocolos (maryadas) de Shiva, entonces también Él es Mis protocolos. Pero ambos tenemos naturalezas completamente diferentes. Así que deben ser muy cuidadosos.

Lord Shiva es las once Rudras (poderes de destrucción) de Jesús Cristo. Estas rudras son la forma de Lord Shiva así que deben ser muy cuidadosos. Tengo que advertirles ya que hasta en Sahaja Yoga la gente vienen a hacer dinero, a dañar a otros y a ser injustos. Esas personas son filtradas pero en cuanto salen, entran en la órbita de Lord Shiva. Entonces me platican que han ido a la bancarrota, que tienen varios problemas. Yo digo: no me lo cuenten ahora. Esa persona huyó de Su protección, ¿ahora quién puede salvarle? Deberían buscar la protección en Lord Shiva. Claro que están protegidos por la Madre pero aun así deberían buscar la protección en Lord Shiva. Y para ello les he dicho acerca de los cinco elementos, deben lograr la sutileza de estos elementos. Para lograr ese estado es necesario meditar regularmente. Los que meditan se distinguen de los que no, sin duda. Ahora bien, los que meditan pero su atención no está en la meditación, o los que no entienden, o no tienen pericia en la meditación, o que son flojos para meditar, quizás no tienen éxito con la meditación. No pueden beneficiarse de la meditación. La meditación debería ser tan profunda que cada una de sus células se llena de gozo y el gozo se derrama de ellas. 

La primer y más importante bendición de Lord Shiva es que les da gozo, llena el ser de gozo. Tan solo cantar su nombre da gozo pero la gente se comporta opuestamente, no se comportan de la manera esperada. Me sorprende mucho que las personas que pensamos que son los Shiva bhaktas (devotos) pueden ser tan secos. Ellos no podrían (ser secos). Podría haber otra razón para eso: los que se mantienen muy ocupados todo el tiempo se vuelven “del lado derecho”. Tales gentes se desconectan de Lord Shiva y entonces El demuestra Sus poderes. Ya saben que la diosa Saraswati es la hermana de Lord Shiva. Los adoradores de Saraswati, la gente que está ocupada en adquirir conocimiento, los que buscan el arte entusiásticamente deberían saber que es la hermana de Lord Shiva y que la relación con la hermana es muy importante. Si tratan de ir en contra de ella, crear literatura impura o malos libros y por lo tanto usar equivocadamente su conocimiento, entonces Lord Shiva los castiga con mano pesada. Su hermana es muy importante para El e ir en contra de Ella es un pecado terrible. Lord Shiva también tiene reglas y protocolos muy rígidos para Adishakti.

Ahora los Sahaja Yoguis deben prestarse atención a sí mismos, primero que nada. No quiero decir que deben sentarse juntos frente al espejo por horas. Para nada, sentarse frente al espejo es considerado como una enfermedad. Lo que quiero decir es que deberían tener su atención en su ser y ver: “¿cuál es el problema conmigo?”, “¿qué cosas erróneas hago?” El camino recto, como se dice en la cultura india, debería tomarse. Hoy en día la gente cree apropiado vivir como les da la gana, “¿qué tiene de malo”? Pero no es propio. En India uno tiene que vivir de acuerdo a la cultura india. Tu estilo de vida debería permanecer conectado a la cultura india, porque en ella se le da gran importancia al Principio de Shiva. El Principio de Shiva ha creado todos nuestros maryadas (límites de conducta correcta). El momento que dejamos de seguir estos maryadas estamos acabados. Todos estos maryadas vienen de la gracia de Lord Shiva. Shiva ha creado estos maryadas: todo lo que se nos ha dicho hasta ahora que no debemos hacer. Él se preocupa mucho de Sus maryadas. En cuanto los desobedecen, ustedes son afectados. 

La gente ha creado tantas ideas erróneas en el nombre de Shiva Tattva. Muchos piensan que tomando bhang (hierba intoxicante) se despierta el Principio de Shiva. ¡Otros tienen la opinión de que tomar alcohol los sumerge en el Principio de Shiva! Hemos creado ideas tan equivocadas. Lord Shiva bebió veneno, ¿lo beberían también? Él bebió veneno para liberar al mundo de esto, se comió la venenosa dhatura (planta venenosa) para que las gentes no tengan que comer estos venenos. Similarmente habrán escuchado que Sai Nath fumaba tabaco. Ya que en Maharashtra la mayoría son adictos al tabaco, Sai Nath pensó: “¿por qué no consumir todo el tabaco de Maharashtra?” Pero las gentes lo han tomado de la otra manera. Dicen si Sai Nath fumaba chilam (pipa), ¿porque nosotros no? Shri Sai Nath quería que se deshicieran de este mal hábito y por eso él quería acabar con todo el tabaco. Entonces si la Diosa se come todos los bhoots (espíritus malignos) del mundo, ¿ustedes también comerían bhoot? Devi (la Diosa) toma todas las enfermedades que hay en ustedes, ¿ustedes absorberían las enfermedades de otros? No es su deber. De lo contrario ¿qué están haciendo todos estos santos? Ustedes no tienen ni los poderes para hacerlo ni es su deber. Su deber es purificarse a sí mismos, corregirse a sí mismos. Primero alcancen ese estado y todo estará bien. Sin logar ese estado no tiene sentido.

No tiene sentido en absoluto hacer estos rituales. Muchas cosas pueden ser justificadas de la manera incorrecta pero si vamos en la dirección correcta, de la manera correcta, entonces primero que nada debemos limpiar y purificar nuestros corazones. Todos estos hábitos a los que somos adictos afectan nuestro corazón. En tiempos antiguos los discípulos tenían que vivir en junglas entre serpientes, escorpiones, otros animales e insectos, para que no fueran adictos a la vida lujosa. Como máximo podían vivir en chozas hechas de estiércol de vaca. Se les hacía dormir ahí y llevar una vida muy simple. Les daban ropas muy sencillas para que no pudieran estar locos con la ropa, zapatos y comida especial. Es innecesario decir todo esto a los Sahaja Yoguis. Ustedes saben que su Madre podría vivir donde sea, podría dormir en cualquier lugar; podría comer cualquier comida. Los Indios son muy aficionados a la comida sabrosa. Los Sahaja Yoguis se invitan mutuamente para cenar y almorzar. En especial las damas me piden que vaya a sus casas a comer. Digo que es difícil para mí ir a comer a cualquier lado. Hasta en mi casa como sin azúcar y sal. Desde mi niñez me hice insensible a los sabores de la lengua. Disfruto lo que haya disponible. Pero nuestras lenguas están acostumbradas a diferentes sabores. Todos los indios son expertos en esto, ya sean de U.P. (Uttar Pradesh), Punjab o del Sur. Con comida sabrosa engañan a la gente. A mi esposo le gusta esto, a mi esposo le gusta lo otro. ¿Qué hacer? Las mujeres serán esclavas de los esposos complaciéndoles día y noche. Aquel que habla de comida todo el tiempo no es un Sahaja Yogui.

En Milán, Yo tuve que cocinar para la Puja del Gurú. ¿Qué hacer? Por cuatro años tenía que cocinar porque nadie podía preparar comida sabrosa. Los Sahaja Yoguis, en especial los indios, decían “Madre, simplemente es como plástico”. Los indios que vienen para la puja Me quieren ver. Tienen derechos especiales sobre Mí. También son muy críticos de la comida que se les ofrece. Ahora algo más ha comenzado, ¡los Sahaja Yoguis indios necesitan baños adjuntos! ¿Cómo solían vivir sus padres? Ahora quieren baños adjuntos estilo británico. Lo menciono porque estoy cansada de esto. En Ganapatipule les proporcioné baños occidentales a los extranjeros y baños indios a los indios. Pensé que a los Sahaja Yoguis indios les gustaría el estilo indio, pero los Sahaja Yoguis indios exigieron baños occidentales. Les dije “tomen un vaso y vayan a la jungla, así es como ustedes mejorarán”. Por años han ido así, ¡pero ahora son grandes señores! Entonces los pobres Sahaja Yoguis extranjeros dijeron “Shri Mataji, a nosotros nos gustan los baños indios. Están muy limpios. Por favor danos esos baños”. Así que cambie las disposiciones y los indostanos estaban muy contentos de que tenían sus baños adjuntos. Deberían avergonzarse. Los Sahaja Yoguis hablando de tales cosas, deberían avergonzarse. Sus antepasados iban a la jungla con vasos, ¿y ahora qué es lo que exigen? ¿Tienen alguna enfermedad o problema? Innecesariamente me ponen en problemas. Pero de alguna manera me pegó y las cosas fueron resueltas. Les sorprenderá que a los indios que vienen a Cabella no les gusta vivir juntos. Los Sahaja Yoguis occidentales son muy ricos, tienen carros y otras comodidades, sin embargo se quedan a dormir en el hangar. Pero los indios necesitan un lugar especial, se quedan en hoteles. No pueden sacrificar sus comodidades. No han aprendido que este modernismo va más allá de mi entendimiento. Estos extranjeros no tienen sirvientes así que solo tienen un baño en su casa porque lo tienen que limpiar ellos mismos. Como ustedes pueden pagar sirvientes tienen muchos baños, pero todos estos hábitos los alejarán de su poder. Su atención se malgastará. Malgastar su atención en absurdidades hará de ustedes una persona ordinaria.

Es una moda que hoy en día las damas se van al salón de belleza, la cara queda igual pero van y tiran su dinero. Las damas brahmines de Pune usan ropa sin mangas, gafas oscuras y manejan motocicletas. ¡No lo podía entender! Pune es punaya patnam (tierra de virtudes) ¿pero que es punyai (buenas acciones)? Así hemos adoptado el estilo occidental sin siquiera pensar en el Principio de Shiva. Vean a Shiva: a Él no le importa la ropa. Hasta en su procesión nupcial se sentó en Nandi, el buey. ¿Porque en Nandi? Porque Nandi es su discípulo. El obedece sus órdenes por eso Nandi es el discípulo más amado de Lord Shiva. Shiva se sentó en Nandi y llegó a la casa de Parvati. Claro que Parvati no tuvo objeción pero su hermano Lord Vishnu se sorprendió de ver este novio tan extraño. No quiero decir que deberían vestirse andrajosamente para casarse. Aceptar todo, toda clase de alimentos es bueno. La sabiduría es su ornamento. Pero estas gentes continuarán criticando a sus anfitriones por la comida que ofrecen ¿Qué comida prepararon ellos? Si la comida era buena entonces le pedirán a sus esposas que cocinen asimismo. Este gusto de la lengua lo hay en abundancia en India. Debería ser reducido. Estos Sahaja Yoguis extranjeros se comen su comida, nunca he oído ninguna queja. Pero ninguno de ustedes pudo comer su comida occidental. Mientras estén atrapados en esta tentación no pueden tener este gozo profundo. En los tiempos antiguos, a los buscadores se les pedía que renunciaran a todo para lograr el gozo de Lord Shiva. Primero “renuncien, luego “vayan a los himalayas, párense en una pierna, no deberían usar ninguna ropa, sumérjanse en el rio y mediten con las ropas húmedas.” Acostumbraban torturar el cuerpo. Hasta hoy día los gurús le pegan a sus discípulos. No dan Realización tan fácilmente. Después de mucha tortura y arduo trabajo, unos cuantos buscadores la obtienen pero tales buscadores se establecen en esta (Realización del Ser).

La Realización se les da a los Sahaja Yoguis sin tener que pasar tanta penuria. Sus sanskaras (hábitos) todavía persisten en ellos. ¿Qué hacer con eso? Estos sanskaras hay que retirarlos, que terminarlos. No hay necesidad de ir a extremos. No hay necesidad de renunciar a su hogar y todo. No hay necesidad de hacer dravidi pranyamas (controlar la respiración). Pero una cosa es necesaria, tienen que reducir esta tentación del gusto. Hay que deshacerse de las tentaciones por el sabor. Es muy necesario. Liberarse del gusto es un gran logro. La gente se pone furiosa si no obtienen la comida de su preferencia. Tiran sus platos, les pegan a sus sirvientes y más. Si se hacen insensibles al gusto creo que muchas de las tiendas de dulces cerrarán. Lo que he querido decir es que no debería darse tanta importancia al cuerpo. Si duermen en la cama, entonces duerman en el suelo por diez días. No pueden lograr su ascenso sin esclavizar a su cuerpo. Muchas gentes no pueden caminar porque tienen el hábito de viajar en coche. Continuamente piden prestado coches, no se les ocurre que pudieran ir en autobús. En tiempos antiguos no había ni autobús. Caminábamos cinco millas todos los días para ir a la escuela aunque teníamos carro y todo, pero nos gustaba caminar descalzos. Caminar descalzo en la tierra es bueno para recibir vibraciones. También deberían desarrollar el hábito de caminar sin zapatos. Es muy importante. Se beneficiarán: la Madre Tierra absorberá sus vibraciones y ustedes se sentirán bien.  

Nos hemos convertido en esclavos de las comodidades como nawabs (virreyes), ¿qué logros tuvieron los nawabs? Asimismo nuestras vidas se malgastarán sino salimos de las garras de la esclavitud. Primero tenemos que reducir la esclavitud y establecer el Principio de Shiva en nuestros corazones. Ninguna cosa es muy importante - hermosos vestidos de moda, etc. Lo que hay disponible, pónganselo. No perderán nada, al contrario estarán felices de que son personas satisfechas. En estos días el precio de un cilindro de gas en India ha subido 16 rupias. Las damas se opusieron y tuvieron una procesión. Vi sus fotografías en el periódico. Todas tan bien decoradas que dije que cada una de ellas se puso el equivalente de 15 rupias en polvo, ¿para qué van a hacer huelga ahora? Nadie piensa en el incremento de salarios. Antes le pagábamos 20-25 rupias a nuestro sirviente. Ahora el obtiene dos mil quinientas rupias, ropa y otras facilidades, aun así se queja. Cuando los salarios se incrementan tanto ¿no subirían los precios? Los salarios y los precios suben a la misma velocidad. Hay una historia que en Sri Lanka los trabajadores eran remunerados un ladrillo de oro diario. En una ocasión, una persona recibió dos ladrillos por un día de trabajo. Él fue a la peluquería para una afeitada y le pregunto al peluquero “¿cuánto cobra?” “Dos ladrillos” fue la respuesta. Así como es el ingreso es el gasto. No es sabio seguirse quejando del incremento de precios. Cuando sus salarios son incrementados, ¿porque seguir quejándose de la alza de precios? Es muy simple. Si lo aprendemos entonces socialmente también podríamos alcanzar el Principio de Shiva.

Estuve con Gandhiji en su ashram por un tiempo. Los que se quedaban ahí acostumbraban huir porque tenían que limpiar los baños. No había ningún barrendero en el ashram. Uno tenía que lavar sus propias ropas, platos. Todos tenían que comer comida hervida cuando mucho con un poquito de aceite de mostaza. ¿Cuántos indostanos comen tal comida? La mayoría huyó del ashram en dos o tres días. Ustedes deben aprender a ir más allá de los gustos del paladar. Les beneficiaria comer comida hervida por unos días. Ninguna madre sugeriría tal cosa a sus hijos, ¿pero qué hago? está dañando el Principio de Shiva en ustedes. Si están absortos en la comida sabrosa el Principio de Shiva desaparecerá y toda la labor será perdida. No es bueno estar absorto en comer todo el tiempo. La gente en tiempos antiguos acostumbraban ayunar y sacrificar algo. Si están satisfechos no hay necesidad de pensar en comida todo el tiempo, ni de invitar a la gente a sus casas.

El sistema de castas es otro gran problema en la India: kayasth es diferente, brahmin es diferente. Cada uno forma un grupo por separado. Ahora son todos Sahaja Yoguis, ¿entonces por qué deberían preocuparse por estas castas? Si van a hacer todas estas cosas, ¿para qué han venido a Sahaja Yoga? No hay casta ni credo en Sahaja Yoga. ¿Cuál es la casta de Lord Shiva? Gente con un ojo ciego, descalzos y con extremidades rotas estaban en la procesión de matrimonio de Lord Shiva. Así que estar preocupado por castas y pensar que diferente comida debe preparase para castas diferentes, va en contra del Principio de Shiva. ¡Jamás entenderé como la gente se complace en esto! ¿Cuál es la razón que los bengalís quieren comida bengalí, los madrases quieren comida del sur de India? Una vez pregunte por qué no hay comida estándar en las aerolíneas.

Me contestaron: “¿Shri Mataji, cual es la comida estándar en nuestro país?”. Así es, a cada quien le gusta la comida de su propio estado. Uno deberia tener una lengua dulce. Uno siente como si Ravanas (Ravana, dios demonio) salieran de las sonrisas de ciertas personas y cuando las damas hablan, parece ser como Chandika (aterrorizante forma de Parvati). Tanto hombres como mujeres son muy extraños. ¿Dónde está el Principio de Shiva en estos hábitos extraños? Lord Shiva es el océano de amor. El otorga bendiciones hasta a los rakshasas (demonios). Si vamos a despertar el Principio de Shiva en nosotros entonces: ¿cómo podemos caer en tal estupidez? ¿cómo podemos hacer todo eso? Díganme. La manera en que criticamos y nombramos alto o bajo, no es como Lord Shiva.  

Las mareas de amor están fluyendo en Lord Shiva. Mientras nos bañamos en este océano de amor no deberían decir tantas cosas sin fundamento. No sirve para nada. Deberíamos disfrutar el amor y entendimiento entre nosotros. Por supuesto que los Sahaja Yoguis no pelean entre ellos. Se encuentran con gran amor. Sin embargo, sus pequeños gustos, comidas y movimientos deberían ser corregidos un poco. Si lo hacemos será maravilloso: su atención irá hacia el corazón, no permanecerá enredada en estas cosas. La moda y el diseño son más prevalentes en los países extranjeros. Crean diferentes vestidos a la moda y los que los usan piensan de sí mismos que son grandiosos. Los italianos están muy afectados por esto. Pero ustedes no tienen por qué enredarse en esto. Lleven una vida sencilla. En nuestro país la gente sencilla ha logrado elevarse. Durante los días antes de la independencia Gandhiji pidió que todos usaran khaddar (vestimenta de algodón) y así corrigió a la gente. Ahora ustedes deben controlarse porque son seres iluminados.

Ahora están a los pies sagrados de Lord Shiva. Corríjanse, no traten de corregir a otros. Corríjanse and siéntanse bendecidos de ser personas realizadas. ¿Cuántas almas realizadas había en tiempos antiguos? Hoy hay miles. Por lo tanto empiecen por hablar entre ustedes dulcemente desde la profundidad del corazón. Si hablan desde el corazón nadie los toma a mal.  Observen todos los protocolos (maryadas) con sus hijos y ancianos. De esta manera se harán felices a ustedes mismos y a otros. Aunque no pueden hacerlo sin las bendiciones de Lord Shiva. Miren dentro de sí mismos y vean que son personas iluminadas: “¿soy suficientemente paciente o no?, ¿peleo con otros por pequeñas cosas y los culpo? entonces definitivamente hay algo mal conmigo”. Pongan su atención en ello, solo así pueden ser purificados. A menos que conozcan sus propias fallas, ¿cómo podrían purificar a otros? Esta purificación es muy necesitada. Solo purificandose pueden visualizar al Divino Padre, el Dios Todopoderoso dentro de ustedes y otras gentes también podrían tener la bendición.

Que Dios los bendiga.

Esta ha sido una charla muy larga en Hindi, especialmente, porque hay muy pocos Sahaja Yoguis de otros países. Lo que les estaba diciendo a ellos, era que el Principio de Shiva está en vuestro Corazón y que, su reflejo, no está en un chakra sino sobre una especie de espejo. Ahora bien, todo lo que se ve de vosotros es este espejo. ¿Cuál es vuestro reflejo en el espejo? ¿Tenéis un reflejo claro, limpio? ¿Habéis limpiado vuestro Corazón? ¿Habéis limpiado el espejo que refleja? Esto es lo que uno tiene que ver.

Lo que les he dicho con bastante extensión es que tenemos seis enemigos, y que estos seis enemigos, uno tras otro, tratan de corrompernos. Les he hablado de cinco de ellos. El sexto no existe mucho en India, el que llamamos lujuria, allí se da mucho menos. Pero uno tiene que saber que en Occidente, es uno de los mayores problemas que tienen, porque piensan que una vida lujuriosa es la única vida que vale la pena vivir.

Shiva está más allá de esto. Y por eso tenemos que comprender que el reflejo completo de Shiva en nuestro Corazón solo es posible cuando hemos limpiado el Corazón. Albergar malicia hacia otros, tener lujuria hacia otros, cólera hacia otros, envidia por otros, todas estas reacciones internas actúan y nuestro Corazón se vuelve como una piedra. No puede reflejar.

Así que, reflejar la cualidad de Shiva, es muy importante hoy en este Kali Yuga. Hay muy pocas personas que realmente reflejen la imagen de Shiva en su propio carácter. Por eso es muy importante vigilarse uno a sí mismo y ver por uno mismo lo que no funciona ¿Adónde va mi atención? ¿Dónde estoy yendo? ¿Qué estoy haciendo? Juzgaos a vosotros mismos y no a otros.

También, una de las cosas típicas occidentales es que piensan que tienen derecho a criticar a otros, a todo el mundo. "Me gusta, no me gusta". ¿Quiénes sois vosotros? ¿Por qué decís algo así? Alguien, digamos, ha hecho un hermoso arreglo para vosotros. Entonces os sentáis en su casa y muy tranquilamente le decís, "no me gusta", para dañar a esa persona. Después de todo, ¿quiénes sois vosotros? ¿Qué pensáis de vosotros mismos? ¿Quiénes sois vosotros para juzgar? A los sahaja yoguis les está prohibido decir "me gusta" y "no me gusta". Está prohibido.

Mirad a Shiva. A Él le gusta todo. ¿Qué lleva puesto? Montones de serpientes. A Él le gustan toda clase de animales, todo tipo de cosas de las que pensamos que no son buenas, que son desagradables, pero para Él sí que son buenas. Por ejemplo, en su boda llevó con Él en su cortejo un montón de gente con malformaciones. Algunas personas tenían una sola pierna, otros tenían manos rotas, algunos solo tenían un ojo. Este tipo de personas iba con Él y, para Él, estas personas eran muy queridas y por eso las cuidaba.

Porque Él es la Fuente del gozo. Él es quien nos da gozo y quien nos hace disfrutar. El verdadero gozo solo es posible si en vuestro corazón está su reflejo. Pero, si vuestro corazón está lleno de cosas extrañas, como las que hemos descrito, se convierte en un espejo muy, muy sucio.

Es muy sorprendente. También les he dicho que, comparados con los indios, los occidentales no son tan susceptibles acerca de su confort. Aunque vienen de un entorno muy materialista, no están muy preocupados por su comodidad. Pueden vivir en cualquier parte, pueden ser felices en cualquier parte; este es un buen estado que ellos han alcanzado y que los indios deben tratar de imitar. Y no prestar atención a cosas absurdas. No es necesario gastar nuestra energía en cosas absurdas. Solo entonces podéis tener un bhakti real hacia vosotros mismos, hacia vuestro Atma, y esto es lo que se necesita hoy, que vuestro Espíritu brille en vuestro carácter, en vuestra conducta y en vuestra personalidad. Si eso ocurre, entonces, habéis alcanzado lo que Sahaja Yoga quería para vosotros.

Actualmente es muy importante, muy importante, incluso podéis leerlo en los periódicos, que lo que se necesita es un cambio, como lo llamamos en hindi "parivarta", una transformación de los seres humanos en el SER, en autoconciencia, en el Espíritu. Esto ha de hacerse y ha llegado el momento. Este proceso evolutivo ha empezado. Hay muchísimos que ya lo han alcanzado.

Los antiguos Santos y personas que eran verdaderos gurus, solían probar a sus discípulos haciendo que se pusieran de cabeza durante años, algunas veces metiéndolos dentro del agua, haciendo todo tipo de cosas. Solían golpearles y eran muy duros en las pruebas que les ponían. Y solo uno de ellos, a lo mejor, alcanzaba su Realización. Lo que yo pensé, es que llevaba mucho tiempo limpiar sus chakras, ponerles toda clase de trajes o atavíos, enviarlos a los Himalayas o al desierto de Gobi. Pensé que llevaría demasiado tiempo. Me dije, "¿por qué no iluminarlos primero, darles la luz? Y entonces, en esa luz, podrán ver sus problemas y se corregirán a sí mismos. Ellos serán su propio guru". Y fue un éxito. Salió bien.

Ahora podéis ver por vosotros mismos lo que estáis haciendo, cuál es vuestro problema, lo que os hace tan diferentes de otros y lo que os elevará porque el lugar de Sadashiva está sobre vuestra cabeza, sobre vuestros pensamientos, por encima de vuestra mente, por encima de vuestras emociones. Está aquí. Y tenéis que cruzar este límite. Solo cuando no reaccionáis a esas cosas y cuando nada es tan importante como Shiva, podéis cruzarlo. Solo entonces funcionará.

Así que, en algunas cosas los indios tienen que aprender y en algunas otras, vosotros, los occidentales, tenéis que aprender. Habéis realizado muchas cosas. Debo daros las gracias por ello. La gente solía pensar que no podían hacer nada, pero ahora han dejado la bebida, han dejado montones de malos hábitos. Ya no sois mujeriegos, vuestra atención es muy limpia. Habéis realizado muchas cosas, lo cual es admirable para mí. Pero debéis aprender que todavía hay ciertas cosas que se deben limpiar y que deben desaparecer completamente. Entre vosotros no hay muchos políticos, pero algunas veces también hacéis política. Se forman grupos. Todo esto tiene que acabarse. Porque, ¿qué es esto para Shiva? El universo está a sus pies. No es importante la formación de grupos. Todo esto no viene a su cabeza. Una persona que es como un gran océano, toca muchas orillas, pero en sí mismo es un gran océano. El Principio de Shiva es lo mismo. Todos vosotros deberíais desarrollar ese Principio de Shiva y entonces sentir el gozo, el gozo de este gran océano de amor.

Que Dios os bendiga

