Christmas Puja, Ganapatipule (India), 25  de Diciembre del 2000

[Shri Mataji habla en Hindi por 16 minutos, esta en inglés, falta la traducción al español]

Siento haber tenido que hablar en hindi, pero es la única lengua que entiende la mayoría de la gente que está aquí. Cuando estoy en el extranjero hablo siempre en inglés, así que, me agrada cambiar de vez en cuando.

Con relación al gran advenimiento que celebramos hoy, el de Shri Jesucristo, les he dicho que Él vino a la tierra con una misión muy importante. Yo diría que fue una de las misiones más grandes, porque quería abrir el Agnya chakra que estaba muy oprimido. Esto no hubiera podido hacerse antes. Para ello, tuvo que sacrificar su vida. Solo a través de este sacrificio era posible abrir este chakra tan importante.

Él era consciente de esto, sabía que tenía que ocurrir y que, en cierta forma, tenía que aceptar ese sacrificio. Era una personalidad divina, no tuvo ningún problema en hacerlo. Pero pensó que quizá hubiera otra forma de abrir el Agnya chakra. Sin embargo, Él tenía que sacrificar su vida. Y con este sacrificio, mostró que si se quiere ascender más allá de esta vida mundana superficial, en cierta forma, uno tiene que sacrificar algo. ¿Sacrificar qué? Vuestros seis enemigos. No obstante, con el despertar de la Kundalini, estos seis enemigos se apartan de vosotros completamente. Depende de cómo ha ascendido vuestra Kundalini. He visto personas que alcanzan una Realización completa al instante, porque su Kundalini asciende perfectamente. Por supuesto se han dado pocos casos así, pero los ha habido. Mientras que, según veo, la mayoría de vosotros habéis tenido algún pequeño problema, que casi siempre es un problema de Agnya.

Hacemos trabajar demasiado al Agnya así, como reacción a cualquier cosa externa, pensamos. Reaccionamos ante todo. Por ejemplo, veo aquí todas estas luces y puedo reaccionar diciendo: "De dónde habrán sacado todo esto, cuánto les habrá costado, dónde lo van a guardar el resto del año" y todo tipo de cosas. Puedo reaccionar. Esta reacción viene de nuestros condicionamientos o de nuestro ego. Las personas con mucho ego son muy susceptibles. Si les das algo que no consideran suficientemente digno, se sienten heridos. Se pueden ofender por cualquier cosa, porque tienen una conciencia de que son alguien especial o gente superior, y que en todas sus relaciones, los demás deben comportarse muy bien con ellos. Por eso se sienten completamente perturbados si se encuentran con alguien que de alguna forma los degrade. Esto viene del ego, que es una parte de este movimiento del Agnya.

El segundo aspecto viene dado por vuestros condicionamientos. Tenéis un condicionamiento determinado. Por ejemplo, si sois indio, vuestro condicionamiento es que cuando una persona viene a veros, debe tocar vuestros pies. Vuestras relaciones son así, y si la persona no toca vuestros pies, entonces os enfadáis. Cualquier condicionamiento de este tipo os da la idea de que os están insultando o de que de alguna forma no os han respetado. Y entonces os sentís mal. Las otras reacciones que vienen del ego son como las que os he comentado, por ejemplo, veo las lámparas y pienso: "¿Por qué no tener una?", o si ya la tengo, pienso: "¿Por qué he de dársela a otra persona?" Por tanto, unas reacciones vienen del ego y otras del superego. Había que terminar con ambas, y eso se llevó a cabo a través del sacrificio de la vida de Cristo.

Cristo era una persona divina. Las personas divinas son como el mar, permanecen a la altura cero, en el nivel más humilde, y desde allí hacen todo el trabajo. El mar produce las nubes, la lluvia, y cuando todos los ríos tienen caudal corren hacia el mar, porque éste está en el punto más bajo. Por tanto, la humildad es uno de los parámetros de Sahaja Yoga. A una persona que no tiene humildad, no se le puede llamar sahaja yogui. He visto que hasta los sahaja yoguis se enfadan mucho, a veces empiezan a gritar, a enfadarse y a comportarse mal. Esto es señal de que esa persona todavía no es un sahaja yogui, y que todavía tiene que madurar.

Esta humildad os llevará a un estado más constante o permanente gracias al cual no reaccionaréis tanto. Miráis cualquier cosa y reaccionáis. Pero en ese estado, no reaccionáis, simplemente observáis. Y así es cómo alcanzáis ese nuevo estado que es el de testigo. Cuando os volvéis el testigo, simplemente observáis, no reaccionáis, no pensáis sobre ello, sino que estáis en el presente. En el presente, simplemente lo observáis todo y realmente gozáis. Cuando estáis pensando, el gozo de toda la creación no está en vuestra mente. Y cuando no pensáis, todo el gozo de la belleza de la creación se refleja en vosotros y os proporciona un gozo y una paz tremendos. Así, hay que aprender que no se debe reaccionar. El problema de hoy es que todos los seres humanos reaccionan con mucha facilidad. La reacción es el principio básico de la vida de hoy.

Veis cualquier periódico, cualquier libro, os encontráis con cualquier persona, y lo que se percibe es que la gente es experta en reaccionar. Reaccionan, y con la reacción, lo que ocurre es que nunca llegan a la esencia de las cosas. Solo se puede llegar a la esencia de las cosas a través del estado de testigo. Esto es lo que hay que aprender de la crucifixión de Cristo, de su nacimiento.

Porque nació de una familia muy humilde, muy pobre, y en unas condiciones muy adversas. La razón de esto fue mostrar que todas estas cosas externas, todas estas glorias externas, no os hacen grandes personas. La grandeza viene del interior, y cuando esta grandeza está ahí, nada os preocupa, porque tenéis tanta riqueza interior que lo demás os es indiferente, no pensáis en lo externo, lleváis vuestra propia vida llena de grandeza.

Esto es lo que vemos también en su vida, Él era una persona majestuosa. Si os encontráis con un hombre pobre, que ha sufrido la pobreza, os hablará como un mendigo. Si alguien ha nacido en una familia rica, os hablará de forma presumida. Pero a una persona divina, todas estas cosas no le afectan. Para una persona así, la riqueza o la falta de riqueza, la posición o la falta de poder, es todo lo mismo. Cuando lleguéis a este punto, entonces podréis consideraros sahaja yoguis.

Ahora las cosas han cambiado mucho, pero al principio, cuando la gente venía a Ganapatipule, siempre se quejaba diciendo: "No tenemos agua, no tenemos tal servicio, hace mucho frío, o calor..." o lo que fuera. Siempre hablando de ello como si estuvieran de vacaciones. Pero este viaje trata de algo muy diferente. Estáis aquí para desarrollar vuestro estado de testigo. ¿Habéis visto qué bonito estaba el cielo? Los tonos naranjas, azules, todo tipo de colores... El cielo adopta un color automáticamente, y disfruta de él. No se preocupa de si ese color va a permanecer para siempre o no, o de si se irá cuando llegue la oscuridad, simplemente lo observa. El cielo lo observa. Todo lo que le sale al paso, lo acepta. Es algo tan hermoso y da tanto gozo...

Otro punto es que cuando estáis en ese estado de espiritualidad, os convertís en personas que dan gozo, que dan paz; sois compasivos y os amáis los unos a los otros. Todos estos problemas de ego simplemente desaparecen. El ego es vuestro mayor enemigo, creo yo, y es él quien realmente oculta toda la riqueza y la belleza de vuestra vida. Si tan solo pudierais ver este ego, cómo funciona, os divertiríais. Él representa una obra de teatro. "De acuerdo, veámosla". Podéis ver esta comedia y al hacerlo, de repente, os sorprende ver que no estáis dentro de ella, la estáis observando. Cuando estáis desapegados de vuestro ego, podéis ver cómo intenta incitaros. Estos son los problemas de hoy día y por eso necesitamos mucho a Jesucristo.

El problema más importante de ahora es que las personas no entienden cuánto daño se están haciendo a sí mismas, a los demás, y al mundo entero, al volverse tan egoístas. Si pudieran entenderlo, os digo que no lo harían. Pero el problema es que les gusta, disfrutan de ese tipo de maldad o, podría decirse, de ese tipo de vida tan mundano.

Mientras que vosotros sois todos sahaja yoguis, y lo que tenéis que hacer es entender por qué crece este ego en nuestra cabeza. Preguntaos: ¿Qué he hecho? ¿Quién soy yo? Si os hacéis estas preguntas, este ego desaparecerá. Para mí también es un gran problema tratar con gente que tiene ego, porque no puedo decirles que tienen ego, si se lo dijera, se irían. Si les digo que son muy buenos y muy agradables, se les hincha el ego. Dicen: "Madre me ha dicho que soy muy agradable". Esto es un problema. No sé cómo manejar el ego de los seres humanos. Sé que tienen ego, pero no sé cómo tratar con él. Creo que solo vosotros podéis hacerlo una vez que entendéis lo que no va bien en vosotros. Esta es una forma muy buena de resolver vuestro problema y el mío.

Creo que mi visión es demasiado grandiosa para una sola vida. Deseo una Realización Global. Quiero que el mundo entero tenga la Realización.

Es admirable que en la cultura sahaja tengamos un método adecuado para deshacernos del ego. Podéis hacer introspección y ver por vosotros mismos por qué os comportáis así. Otras personas no pueden hacer la introspección que hacen los sahaja yoguis, porque estos pueden entrar en su interior y ver las cosas por sí mismos, pueden observar a los demás, y con todo ello, pueden ver qué está haciendo este señor ego en sus cabezas.

Por supuesto, sabemos que el mantra de Jesucristo es lo mejor para eliminar todos los problemas de ego, y que ayuda mucho. Pero cuando utilicéis este mantra, hacedlo con mucha humildad: "¿Qué soy yo, después de todo? ¿Quién soy yo?" Mirad todas las estrellas, todas las cosas hermosas. Pensad: "¿Quién soy yo? ¿Qué he hecho? ¿Por qué tengo tanto ego? ¿Por qué me creo tan importante?"

A veces otras personas inflan vuestro ego porque quieren aprovecharse de vosotros. Os halagan diciendo: "Esto es muy importante, tú eres muy importante". A vosotros os encanta y así os echáis a perder. Es como si os metieran bajo una lluvia torrencial y vuestro ego se desbordara uniéndose a una gran corriente de gente egoísta.

Si miráis a vuestro alrededor hoy, en estos tiempos modernos, todo el mundo le da mucha importancia a su ego. Me sorprende la forma en la que aparecen en los periódicos o en las revistas, a mí me daría un poco de vergüenza, porque eso no es otra cosa que una gran expresión de vuestro ego. Hacen todo tipo de cosas y compiten en ego, y en mucho más. Por ejemplo, hacen concursos de belleza. Luego hacen concursos de Mister... India, por ejemplo, o Mister esto, Mister lo otro.

De hecho, todas estas cosas hacen crecer el ego de la persona, y los demás también desean participar en esos concursos. Piensan: "¿Y por qué yo no? Yo también quiero ser así". Es algo que os ofusca mucho, que ciega vuestra mente y os hace pensar que así es cómo se consigue mucho éxito. ¿Cuánto dura ese éxito? Perece rápidamente. Sin embargo, el éxito en Sahaja Yoga durará para siempre y todo el mundo lo recordará. Aquél que tenga esta humildad, será recordado durante generaciones.

Nunca he visto que le hayan hecho una estatua a una persona egoísta. Al contrario, cuando alguien ha sido egoísta, la gente lo ha criticado y ha comentado: "Era un hombre muy egoísta". Hoy día es imposible que le canten canciones a alguien egoísta o que erijan estatuas en su nombre. Por tanto, en lo más profundo de nuestro corazón, nos gusta la humildad, la gente humilde. Si queremos gustar a los demás, debemos ser realmente humildes. No artificialmente, sino sinceramente, comprendiendo, ¿qué somos nosotros? ¿De qué nos sentimos orgullosos? ¿Por qué intentamos dominar a los demás o causarles problemas? Si entendéis esto, habréis justificado plenamente la encarnación de Jesucristo "el Grande".

Él mostró muchas cualidades pero la mejor para nosotros fue la superación del ego, al sacrificar su vida. Este es el mensaje más importante. Por eso, debemos entender que aquellos que se hacen llamar cristianos son los más egoístas de todos. Me sorprendió ver que los ingleses son extremadamente egoístas. Y he visto que en otros países de Occidente la gente también tiene mucho ego, no son humildes en absoluto. En comparación con los hindúes, son gente con mucho ego. ¿Por qué? Porque siguen a Cristo. ¿Podéis creerlo? ¿Es esta la forma de seguir a Cristo? Los que se hacen llamar cristianos, los que se hacen llamar grandes admiradores de Cristo, deberían mostrar esta humildad en su vida, esta compasión, este amor. Pero no es así.
Especialmente la gente de los países occidentales debe intentar aprender la cultura sahaja. En la cultura sahaja, nuestra forma de hablar, nuestra forma de vivir, nuestro contacto con los demás, es muy diferente. Una vez comencéis a seguir la cultura sahaja en vuestra vida, os sorprenderéis y se sorprenderán los demás, por cómo os relacionáis unos con otros, cómo cuidáis tan bien de todo... Esta es la mejor forma de vivir en este mundo, como sahaja yoguis, sin ego, sin condicionamientos, nada, siendo absolutamente libres de todos estos horribles atributos. Entonces os asombraréis de cuánto confiará la gente en vosotros, de cuánto gustaréis a los demás.
Os deseo a todos unas "Muy Felices Navidades". Y también que recordéis la vida, y el mensaje, de Cristo.

Que Dios os bendiga.