Seminario: "Shri Kundalini Shakti y Shri Jesucristo". Auditorio Hinduja, 27 de septiembre de 1979.

Shri Kundalini Shakti y Shri Jesucristo es un tema muy atractivo e interesante. En conjunto es un tema nuevo para la gente común porque en ningún momento anterior nadie había intentado establecer alguna conexión entre Shri Jesucristo y Shri Kundalini Shakti. En el árbol del Virata de la religión, numerosos santos brotaron como flores en muchos países y lenguas. Solo el Virata puede conocer la relación entre estas hermosas flores. Allá donde fueron, estas flores extendieron la dulce fragancia de la religión. Pero ni siquiera las personas que rodearon a estos santos, pudieron comprender el significado de esa fragancia. Por tanto es inútil esperar que la gente corriente entienda la relación entre un santo y la Adi Shakti, la Madre Primordial.

Vosotros seríais capaces de experimentar o entender mi punto de vista si pudierais alcanzar el plano desde el cual os estoy hablando. Actualmente no tenéis los medios necesarios para comprender si lo que os estoy diciendo es la Verdad o no. En otras palabras, todavía no estáis equipados para entender cuál es la verdad. Hasta que no seáis capaces de entender el significado del Ser, el cuerpo físico permanecerá imperfecto y no será capaz de verificar la verdad. Pero una vez que el instrumento físico está conectado con la verdad, sois capaces de comprobarla. Por tanto, primero debéis aceptar Sahaja Yoga y recibir vuestra Realización. Después de la autorrealización, las vibraciones de Chaitanya empiezan a fluir de vuestras manos. Si algo en particular es verdad, entonces comenzarán a fluir de vuestras palmas olas de vibraciones frescas, pero si es falso, se sentirán vibraciones calientes. De esta manera sois capaces de saber si algún asunto en particular es verdad o no.

Todo lo que los cristianos saben de Jesucristo es lo que cuenta la Biblia. Este es un libro muy enigmático; es tan profundo que muchas personas no han sido capaces de entender el significado oculto de la verdad que en él se esconde. La Biblia dice: “Vendré a vosotros como lenguas de fuego”. La interpretación de los israelitas es que cuando el Señor encarnase emitiría llamas de fuego y por tanto ellos no podrían ser testigos de Él, no podrían verle. El verdadero significado es: “Vosotros me veréis en el Sahastrara”. Encontraréis muchas referencias a la Kundalini Shakti y al Sahastrara en la Biblia, pero aquí solo es posible una breve referencia. Jesucristo dijo: “Aquellos que no están conmigo están contra Mí”. Esto significa: “las personas que no están contra Mí, me pertenecen”. Si a los cristianos se les pide que identifiquen a estas personas, no saben quienes son.

Dos grandes poderes se combinan en Jesucristo. El primero es el Poder de Shri Ganesha, el cual se reconoce como su poder original; el segundo es el Poder de Shri Karttikeya. Debido a esto, la encarnación de Jesucristo es de completo “Brahman Tattwa” o “Aumkar”. Shri Krishna, el Padre de Jesucristo, le otorgó varios dones antes de que naciera. Uno de estos dones era: “Tú (Jesucristo) morarás en un plano más alto que el mío”. Podría explicarse del siguiente modo: El plano de Shri Krishna es el Vishuddhi, situado en la base de nuestro cuello, mientras que el plano de Jesús es el Agnya, situado en la unión del tálamo óptico (glándulas pineal y pituitaria).

El segundo don otorgado por Shri Krishna fue: “Tú serás el soporte de todo el Universo”, y el tercero: “Tú serás el primero en recibir una dieciseisava parte de las ofrendas que se me hagan en un Puja”. De esta manera, después de otorgarle varios dones, Shri Krishna permitió que Shri Jesucristo encarnara en la Tierra. Entenderíais mejor estas cosas si leyerais “Markandeya Purana”. Shri Markandeya, el autor del Purana, ha explicado de una forma muy bella algunos puntos muy sutiles. En el mismo Purana, hay una descripción gráfica de Shri Maha Vishnu . Si escucharais esta descripción estando en meditación, os daríais cuenta de que es la descripción de Jesucristo.

Si estudiarais la etimología de la palabra “Cristo”, veríais que procede de la palabra “Krishna”. De hecho, el Padre de Jesucristo es Shri Krishna. Esa es la razón del nombre de “Cristo”. El origen de su nombre, “Jesús”, es también muy interesante. A la Madre de Shri Krishna, Shri Yashoda Mata, se la llama “Yesu”. Incluso todavía hoy en el norte de la India, las personas que se llaman “Yeshu”, su nombre se pronuncia “Jesu”. Por tanto, se ve claramente que de “Yashoda” vino la palabra “Jesu” y finalmente el nombre de “Jesuristo”.

Siempre que Jesucristo contaba historias de su Padre, hablaba de Shri Krishna, hablaba del Virata. Aunque Shri Krishna no se reencarnó durante el período en el que Jesucristo estuvo en la Tierra, sus enseñanzas se centraron en cómo los buscadores conocerían el “Virata Purusha” o Dios Todopoderoso. La Madre de Jesucristo era la Diosa Mahalaksmi. La Madre María no es otra que la Diosa Mahalaksmi. Ella es la Adi Shakti, la Madre Primordial. Por tanto, Jesucristo solía dirigirse a su Madre como el “Espíritu Santo”.

Jesucristo posee todos los poderes de Ekadasha Rudra, esto es, once poderes de destrucción. Estos poderes tienen sus centros situados alrededor del cráneo. Cuando tenga lugar la encarnación de Shri Kalki, estos once poderes llevarán a cabo el trabajo de la destrucción. Uno de estos poderes es el de Shri Hanumana y otro el de Shri Bhairava. En la Biblia, estos dos poderes se mencionan como San Gabriel y San Miguel respectivamente. En Sahaja Yoga, después de la autorrealización, uno puede despertar estos poderes dirigiéndose a ellos en sánscrito, marathi e incluso inglés.

El Nadi de nuestro lado derecho, conocido como “Pingala Nadi”, es activado por el poder de Shri Hanumana. Siempre que se desarrolla algún tipo de presión o constricción en este Nadi, se alivia inmediatamente al decir el mantra de Shri Hanumana. De forma similar, incluso diciendo el nombre de San Miguel uno debería experimentar alivio en el “Ida Nadi”. El “Ida Nadi” está en nuestro lado izquierdo y manifiesta el Poder de San Miguel o Shri Bhairava. Obviamente, al decir los mantras de sus nombres, cualquier problema o constricción en el Ida-Nadi se alivia.

Todo lo anteriormente mencionado puede ser verificado por cualquier persona después de la autorrealización en Sahaja Yoga. El propósito con el que os digo todo esto es el de haceros ver que es absurdo que luchéis entre vosotros agrupándoos como los hindúes, musulmanes o cristianos. Si pudierais ver el principio que hay detrás de todo esto, os daríais cuenta de que todos estos santos son como muchas flores del mismo árbol de la religión, y que están conectados unos con otros por el único y mismo Poder.

Quizá os sorprenda saber que en Sahaja Yoga el despertar de la Kundalini depende mucho de cómo esté el Agnya chakra del buscador. En esta época, encontramos muchas personas con un ego muy inflado (Ahamkara). Esto es así porque la mayoría lleva una vida extremadamente egocéntrica. Es la actitud egoísta la que hace que el hombre se aparte de su verdadera religión. El hombre está perdido y por eso permanece continuamente ocupado trabajando, pensando, etc. Esto ocasiona un crecimiento del ego. Jesucristo es una gran ayuda para liberarse del ego.

De la misma manera que el Paigambar (profeta) Mahoma escribió acerca del despertar de la Kundalini y de las maneras de protegerse uno mismo contra los perversos poderes satánicos, también Jesucristo habló de una manera clara de los poderes que hay dentro de nosotros, así como de las armas. La primera de estas armas es el “perdón”, el cual actúa en la forma “Proksha” en el principio de Shri Ganesha, que se manifiesta en forma de perdón en el principio humano. De hecho, el perdón es un arma muy poderosa. Protege al hombre contra el ego. Si alguien os hiere, os mete en problemas u os insulta, vuestra mente se enoja al contemplar estas cosas, y os sentís molestos. No dejáis de pensar en ese hombre y al acordaros tantas veces de esos hechos, os metéis en problemas. Para superar esos problemas, os aconsejo que perdonéis a todo el mundo. De este modo, el perdón es un arma muy poderosa que hemos recibido de Jesucristo; nos da la posibilidad de liberarnos de los problemas que otros nos crean.

Os he dicho antes que Jesucristo poseyó varios poderes y que se le dotó con los poderes del Ekadasha Rudra. Entonces, ¿cómo es que fue crucificado y no pudo salvarse a Sí mismo de este horrible acontecimiento? Jesucristo, con sus distintos poderes, podría haber aniquilado a sus oponentes en un instante. Su Madre, María, era la mismísima Adi Shakti, la Madre Primordial. Ella tampoco podía soportar las atrocidades que hicieron sobre su Hijo. Y, sin embargo, ocurrió. Quizá Dios deseaba escenificar un drama. A decir verdad, Jesucristo estaba más allá de la felicidad y de la tristeza. Tenía que representar el drama de un modo perfecto y sin falta alguna. ¡Qué tontos fueron los que lo crucificaron! Jesucristo montó en burro con el fin de que la locura de las personas de aquellos tiempos pudiera ser erradicada.

Si tenéis dolores de cabeza y rezáis a Jesucristo para que perdone a todos aquellos que os han metido en problemas, vuestro dolor de cabeza se curará sin la ayuda de ninguna medicina. Sin embargo, antes de que tal cosa ocurra, tenéis que despertar vuestra Kundalini aceptando Sahaja Yoga y recibiendo la autorrealización. La razón es que el Agnya, que es el Principio de Jesús dentro de vosotros, se vuelve activo solo por el despertar de la Kundalini en Sahaja Yoga y no de otro modo. El Agnya es muy sutil. Los físicos tampoco son capaces de localizarlo o notarlo. Hay una puerta muy sutil en este chakra. Eso es por lo que Jesucristo dijo: “Yo soy la puerta”. Jesucristo encarnó en esta Tierra para facilitarnos la entrada a través de esta puerta, y Él mismo fue el primero en pasar por ella.

La gente crucificó a Jesucristo debido a sus egos. No podían concebir la idea de que algún ser humano pudiera aparecer en la Tierra como una encarnación de Dios. Su orgullo intelectual no podía aceptar esta idea y rechazaron la verdad debido a su ego. ¿Cuál fue la mala acción por la que se crucificó a Jesucristo? Por el contrario, había curado a muchos de sus enfermedades. Predicó la verdad y enseñó muchas cosas buenas a la gente. Les enseñó la forma de llevar una vida sólida con conocimiento. Siempre predicó el amor. A pesar de esto, la gente le torturó. Sin embargo, esa gente se inclinó ante aquellos que enseñaban cosas sucias y hacían de ellos unos locos majaderos. ¡Qué grado de estupidez! En nuestros días, cualquier fulanito o menganito se convierte en un guru, roba el dinero de la gente, y les quita sus bienes. A tales personas se las tiene en muy alta estima.

Sin embargo, si una buena persona que se mantiene en la verdad desea mostrar el verdadero camino, la gente no solo no le escuchará, sino que además se le echarán encima. Para educar a gente así de estúpida, Dios Todopoderoso envió a su amado Hijo Jesucristo a esta Tierra, pero la gente lo crucificó. Y desde entonces han estado haciendo lo mismo repetidamente. Si leéis, os daréis cuenta de que siempre que Dios encarnó, o algún sabio o santo nació en esta Tierra, la gente les causó daño y les torturó. En lugar de aprender de ellos, se comportaron estúpidamente con ellos. Esa misma historia ocurrió con Gyaneshwara, con Shri Tukarama, los grandes santos de Maharastra. Un trato similar se les impuso a Guru Nanaka y al profeta Mahoma. El hombre siempre huye de la verdad e intenta aferrarse a lo falso.

Si un sahaja yogui hace la pregunta de si cierta persona nacida en esta tierra es una encarnación o un santo, sentirá la brisa fresca si la respuesta es afirmativa. Los acontecimientos pasados de la vida de una persona derivan en un fortalecimiento del ego. Por ejemplo, uno alardea de ser discípulo de tal o cual persona; ese hombre no es consciente de la realidad que tiene frente a él. Obviamente, debido al fortalecimiento del ego, pierde de vista el significado real del Ser. Por tanto, es necesario entender el significado del Ser. Si suponemos que el río Ganges fluye de un cierto lugar, y luego vais a otro lugar diciendo que el río Ganges fluye desde allí, y de hecho estáis sentados sobre el río Ganges, resultaría ridículo.

Por tanto, aceptad solo aquello que se presente ante vosotros objetiva y materialmente. En el caso de Jesucristo las circunstancias fueran similares. Jesucristo intentó despertar la Kundalini, pero con gran dificultad solo consiguió dar la Realización a unas veintiuna personas. Sin embargo, en Sahaja Yoga la Realización la han recibido miles. Cristo podía haber dado la Realización a muchos más, pero sus discípulos creyeron que Él solo podía curar a personas enfermas y que la Realización no tenía otro significado para ellos. En muchas ocasiones, Jesucristo se mostró caminando sobre las aguas. Esto fue posible porque Él mismo era “Pranava”, “Aumkara”. A pesar de ello, la gente no supo entender que Cristo era el Hijo de Dios. En Sahaja Yoga un gran número de buscadores han recibido su Realización y se han librado de sus enfermedades.

El hombre debería entender que el ego es muy sutil. También os quiero decir que no está bien que luchéis con vuestro ego. Al ego no le produce ningún efecto el que luchéis contra él. El ego debería ser absorbido por vuestro propio Ser, cuando vuestra atención está enfocada hacia la Kundalini, atraviesa vuestro Brahmarandhra y se funde por tanto con el Virata; es en este estado en el que el ego es absorbido. El verdadero ego es el ego del Virata Shakti. De hecho, el Virata es el ego real. No podéis liberaros de vuestro ego. ¿Qué hacéis? Aquello que yo hago es ego (Aham Karoti, Sah Ahamkara). Simplemente preguntaos qué es lo que hacéis. No podéis hacer nada excepto cambiar la forma de la materia muerta. ¿Podéis transformar una flor en fruto? Se os ha dado la nariz, la cara, el hermoso cuerpo humano. ¿Cómo ocurrió esto? Hemos alcanzado esta forma humana desde el estado de ameba. ¿Cómo ha podido pasar? Es sin duda alguna la gracia de Dios Todopoderoso la que nos permitió tener esta hermosa forma humana. ¿Podemos pagarle a Él por esto? ¿Podéis hacer algo similar?

Después de que el hombre tuviera éxito al engendrar un niño probeta, su ego se hinchó considerablemente. A decir verdad, tampoco aquí el hombre creó ningún organismo viviente. Se hace igual que el injerto de dos plantas, en este caso uniendo dos células humanas vivientes pero, ¡cuánto se ha inflado su ego! Después de que el hombre alcanzara la Luna, su ego creció aún más. ¿Qué es vuestro ego en comparación con el de Él, que creó el Sol, la Luna, las estrellas y todo el Universo? En realidad, vuestro ego es falso, es una farsa.

El verdadero ego es el del Virata Purusha, porque es el Virata el que lo está haciendo todo. Deberíais saber que es el Virata Purusha el que lo está haciendo todo. Por tanto, dejemos que todo sea hecho por el Virata, vosotros sois simplemente un instrumento. Supongamos que yo estoy hablando con un micrófono y mi voz llega a vosotros a través de este medio; entonces el micrófono es solamente un “sakshi”, un testigo. Soy yo quien habla, y el Poder está fluyendo a través del micrófono. De la misma manera, vosotros sois solamente un instrumento de Dios Todopoderoso.

El Virata os ha creado, así que, dejad que el Poder del Virata fluya a través de vosotros y comprended el significado del Ser. Jesucristo encarnó en esta Tierra con el fin de explicar el significado del Ser, y tomó asiento en el Agnya. El Agnya es muy complejo, y es el asiento del Principio sutil de Aumkar o Pranava. De hecho, Jesucristo es el Aumkar, el Pranava. La conexión que existe entre la Kundalini y Jesucristo, es la misma que la que existe entre la luna y el rayo de luna, o el sol y el rayo de sol. La Kundalini, que es la Madre Gauri, creó a Shri Ganesha por su fuerza de voluntad, su tapasya y sus nobles actos. Cuando Shri Ganesha se preparó para encarnar, nació Jesucristo.

Hay muchas cosas en este mundo a las que el hombre no ha podido dar una explicación satisfactoria. ¿Os habéis planteado alguna vez cómo brota una semilla, cómo respiráis, cómo hacéis movimientos, de dónde viene el poder de vuestro cerebro o cómo vinisteis a este mundo? Hay muchísimas cosas. ¿Puede el hombre explicar estas cosas satisfactoriamente? Decimos que la Tierra tiene una fuerza gravitatoria pero, ¿de dónde vino esta fuerza? Hay un gran número de cosas por esclarecer. Esto es porque estáis bajo la influencia de una ilusión. Sin embargo, tenéis que salir de esa ilusión; tiene que ser destruida, de lo contrario seguirá fortaleciéndose. Para la evolución espiritual del hombre es necesaria la destrucción de la ilusión.

Las encarnaciones han aparecido en todas las etapas de la evolución. Todos sabéis que Shri Vishnu encarnó como Shri Rama y vagó por los bosques. Escenificó un bello drama para demostrar la vida de un rey ideal. La vida de Shri Krishna fue similar y también la de Jesucristo. Cuando estudiamos la vida de Jesucristo, observamos algo que resalta la estupidez de la gente de aquel tiempo. Debido a esa estupidez, esta magnífica figura fue crucificada. ¡Y qué grado de estupidez! Cuando se les pidió opinión respecto a quien querían liberar, si a un ladrón o a Jesucristo, los judíos pidieron que soltaran al ladrón y que crucificaran a Jesucristo.

Hoy en día conocemos el estado de esas personas. El pecado que cometieron no se limpiará en muchas vidas. E incluso ahora esas personas están envueltas en sus egos. Creen que han hecho algo virtuoso. Incluso si ahora buscaran el perdón de Dios diciendo: “Dios, perdónanos por crucificar tu Principio sagrado, perdónanos por destruir tu Principio sagrado”, Dios los perdonaría inmediatamente. Pero el hombre encuentra muy difícil pedir perdón, y comete bastantes actos perversos.

¿Cuántas personas puede haber en el mundo que hayan adorado a los santos? Tomad el ejemplo de Shri Kabir o Shri Nanaka. La gente los ha perseguido a cada paso. En este mundo la gente no ha dado a los santos otra cosa que daño y tortura. Pero ahora os digo que las circunstancias han cambiado. El Satya Yuga ha empezado. Puede que lo intenten, pero no conseguirán perseguir o torturar a ningún santo. Y esto es gracias a Jesucristo, ya que Él ha puesto en marcha en este mundo un poderoso Poder que hará sufrir a esas personas malvadas. Serán castigadas. Los Ekadasha Rudras de Jesucristo están listos para golpear. Aquellos que ahora torturen a algún santo, serán totalmente destruidos. Es un gran pecado torturar a cualquier santo. Intentad comprender esto desde el ejemplo de Jesucristo. A partir de ahora no cometáis una estupidez igual, si no, seréis totalmente destruidos.

Si hay una gran lección que aprender de la vida de Jesucristo, esta es que tenéis que permanecer contentos en el estado en el que el Todopoderoso os ha situado. Jesucristo no cambió su misión, Él no se apartó de la sociedad considerándose un “sanyasi”, sino que por el contrario asistió a algunas bodas e hizo los preparativos. La Biblia dice que en una de ellas transformó el agua en zumo de uvas. Y ahora el hombre utiliza este episodio para sugerir que -como Jesucristo transformó el agua en vino- Él solía beber vino. En hebreo la palabra “vino” quiere decir puro zumo de uvas frescas. No quiere decir alcohol.

Jesucristo encarnó para abrir el Agnya y disolver vuestro ego. Mi trabajo es despertar el Poder de vuestra Kundalini para que pueda atravesar vuestro Sahastrara. Este trabajo es de naturaleza colectiva, por tanto he de hacerlo en el caso de uno y de todos. Quiero hablaros sobre Jesucristo, Guru Nanak, el rey Janaka y otras encarnaciones, y del modo en que están relacionados con la colectividad. Igualmente me gustaría hablaros de Shri Rama, Shri Krishna, etc. y también sobre Shri Shiva, porque todos los poderes de estos dioses y deidades están dentro de nosotros. Ha llegado el momento de que se manifieste la consciencia colectiva.

En el Kaliyuga todos los que estén buscando a Dios le encontrarán, millones de personas serán capaces de hacerlo. Sahaja Yoga es el Juicio Final. Esto está escrito en la Biblia. Se os juzga solo después de que venís a Sahaja Yoga, por este motivo debéis entregaros completamente una vez que estáis en Sahaja Yoga. Después de recibir esto, lo cual quiere decir todo, hay que morar en ello, estar asentado y establecido en ello. Mucha gente me pregunta: “Mataji, ¿cuándo estaremos establecidos?”. La respuesta es muy sencilla: suponed que lleváis un barco, vosotros sabéis cuando está estable; lo mismo ocurre montando una bicicleta: cuando no os tambaleáis, sabéis que estáis en equilibrio y estables. Nuestra estabilidad en Sahaja Yoga se entiende de la misma manera. El juicio en esta materia lo ha de hacer uno mismo.

Solo cuando os establecéis en Sahaja Yoga el estado de conciencia sin pensamientos se estabiliza. Hasta que el Poder de Kundalini no atraviesa el Agnya, no se puede alcanzar el estado de conciencia sin pensamientos. Éste es el primer paso en el camino de la conciencia sin pensamientos del buscador. Tan pronto como la Kundalini cruza el Agnya, la conciencia sin pensamientos se establece. El Poder de Jesucristo es el instrumento para abrir la puerta sutil situada encima del Agnya. Para lograrlo, debéis recitar el “Padre Nuestro” que Jesucristo compuso. Después de cruzar esta puerta, el Poder de la Kundalini entra en el área límbica del cerebro; es después de que la Kundalini cruza esta área, llamada también “el Reino de Dios”, cuando el estado de conciencia sin pensamientos se establece. En el área límbica del cerebro hay chakras que activan los siete chakras principales y también los chakras secundarios que hay en el cuerpo.

Vamos a examinar las razones por las que el Agnya se echa a perder. Una de las principales razones de este deterioro son vuestros ojos. Deberíais cuidar mucho vuestros ojos, ya que son muy importantes. El Agnya también se estropea al inclinarse ante los pies de un Guru no autorizado. Por eso Cristo dijo que no se inclinara la cabeza ante ninguna persona o lugar, porque al hacerlo, sin daros cuenta perdéis todo lo que habíais ganado. Deberías inclinar vuestra cabeza solo ante una persona autorizada, es decir, ante una encarnación de Dios. No os inclinéis en ningún lugar equivocado, esto es muy importante. Si inclináis vuestra cabeza ante un lugar o persona errónea, vuestro Agnya se obstruirá. Actualmente en Sahaja Yoga he observado que muchas personas tienen muy obstruido el Agnya. La razón es que estas personas siguen a un falso guru o inclinan sus cabezas ante lugares equivocados. Muchas de las enfermedades de los ojos se deben a dichas prácticas erróneas.

Para mantener el Agnya en correcto funcionamiento, se debería leer siempre las escrituras y los textos sagrados. Nunca se debería leer literatura que no sea santa. Mucha gente puede decir: “¿Qué importa? Debido a nuestra profesión tenemos que hacer ciertas cosas que pueden no ser estrictamente adecuadas”. Pero entonces, al hacer esas actividades poco dignas, los ojos se echan a perder. Nunca pude entender por qué la gente tiende a cometer actos erróneos. Incluso solo con mirar a cualquier hombre sucio y obsceno, el Agnya puede obstruirse. Jesucristo dijo firmemente: “No cometeréis adulterio”. Pero yo os digo también: “No tendréis ojos adúlteros”. De nuevo se vuelve a los ojos. Si tenéis unos ojos impuros, estos se debilitan. Esto no quiere decir que si tenéis que llevar gafas seáis personas impuras o poco correctas. Es ley de vida tener que usar gafas a una edad avanzada. Vuestros ojos se echan a perder porque no los mantenéis firmes, y siempre se están moviendo de un lado a otro. Por eso también la atención de algunas personas va de un objeto a otro. Estas personas ni siquiera se dan cuenta de que esa acción echa a perder sus ojos.

La otra razón del deterioro del Agnya es la manera en la que trabajáis: si trabajáis más de la cuenta os volvéis demasiado conscientes del trabajo. Puede que el trabajo que estéis haciendo sea bueno, pero incluso entonces, si está mas allá del nivel normal, bien sea por leer mucho o por hacer punto o pensar más de lo normal, dañará el Agnya. La razón es que cuando trabajáis demasiado os olvidáis de Dios. Durante el curso de dicho trabajo la consciencia de Dios no se estabiliza en vosotros.

La Kundalini es la Verdad; es sagrada. No hay hipocresía en Ella. No es algo que pueda comprarse en una tienda. Es la Verdad Absoluta. Siguiendo el Vama Marg, o camino equivocado, no podréis reconocer la Verdad. Cuando os unáis a la Verdad, cuando seáis absobidos por ella, solo entonces comprenderéis que sois un instrumento de Dios Todopoderoso, del Padre Sant; que sois el instrumento a través del cual el Poder de Dios fluye, y que sois el instrumento del mismo Poder de Amor de Dios, el cual impregna todo el Universo y dirige todo movimiento dentro de él. Este poder ha sido posible en vosotros gracias a Jesucristo, a través de su crucifixión. ¡Qué gran sacrificio el de Cristo! Gracias a Él nuestro Agnya se ha abierto.

Si el Agnya de una persona no se abre, su Kundalini no ascenderá, ya que el Muladhara permanece obstruido mientras lo está el Agnya. Si el Agnya de una persona está muy obstruido, por muchos esfuerzos que haga el Poder de la Kundalini no ascenderá. Para eliminar las obstrucciones del Agnya, utilizamos “kumkum”, el cual tiene el efecto de reducir los problemas del ego, así como otros problemas. Cuando se aplica “kumkum” sobre la frente, sobre el Agnya, el chakra se abre y la Kundalini asciende. Tal es la íntima conexión entre Jesucristo y el Poder de Kundalini. Shri Ganesha, que está establecido en el Muladhara, protege la modestia de Shri Kundalini y también abre la puerta del Agnya para que la Kundalini lo traspase.

¿Qué debemos hacer para mantener el Agnya en buen estado? Hay muchas maneras. El extremismo en toda acción echa a perder la sociedad y, por lo tanto, el exceso en cualquier aspecto de la vida no es adecuado ni correcto y debería evitarse. Mantener un equilibrio permite que nuestros ojos descansen. En Sahaja Yoga hay varios remedios para esto, pero es absolutamente necesario recibir primero la autorrealización; después hay muchos ejercicios para los ojos que ayudan a mantener el Agnya en perfecto estado. Uno de estos ejercicios es observar vuestro propio ego y deciros: “Muy bien, señor, ¿cuál es el plan y a dónde te propones ir?”. Así es cómo podéis dirigiros a vosotros mismos, como si estuvierais observando vuestra imagen en un espejo. Si hacéis esto, la tensión en los ojos debida al ego disminuirá.

Otra área que es muy importante es la parte posterior de la cabeza, exactamente detrás de la frente. Es el área que está a una distancia de, más o menos, el grosor de ocho dedos (unos 12 cm.) desde la base del cuello, y es conocida como el área de Shri Maha Ganesha. Shri Ganesha encarnó como Maha Ganesha, y es la propia encarnación de Jesucristo. Cristo está en el centro de la frente y está rodeado por el Reino de los Ekadasha Rudras. Jesucristo es el Maestro de ese Reino. Los Ekadasha Rudras comprenden Shri Maha Ganesha y también Shri Shadanan (el Señor de las seis caras).

Si abrís vuestros ojos tras el despertar de vuestra Kundalini experimentaréis que vuestra visión está un poco nublada o borrosa; esto ocurre porque cuando la Kundalini se despierta, las pupilas de vuestros ojos se dilatan y se refrescan a consecuencia de la acción del sistema nervioso parasimpático. El mero hecho de pensar en Jesucristo o meditar en Él alivia el Agnya. Al mismo tiempo se debe recordar que seguir meramente los convencionalismos o tradiciones creadas después de Él no significa seguir a Jesucristo.

Ahora os diré algunas verdades que son eternas: la principal de todas ellas es que mirar a una mujer con intenciones perniciosas es un gran pecado. Podéis daros cuenta del enorme pecado que muchas personas están cometiendo en las calles al quedarse mirando a las mujeres con intenciones perversas. Jesucristo habló de esto hace dos mil años, pero no lo dijo tan claramente. Por eso tengo que recordaros este mal hábito. Jesucristo habló de esto y fue crucificado. Él solo dijo que esto no debía hacerse porque era sucio, pero no explicó las malas consecuencias de esta acción. Este hábito hace al hombre comportarse como una bestia, ya que su mente está atrapada día y noche por pensamientos malévolos. En nuestra Ciencia del Yoga se ha aconsejado que la mente debería estar controlada y mantenerse en el camino correcto. Deberíais aproximaros a Dios con toda la atención puesta en Él.

Nosotros hemos nacido del Yoga; nuestra es la tierra del Yoga. No somos egoístas ni queremos serlo; deseamos vivir en esta tierra como yoguis. Llegará el día en el que el mundo entero se inclinará ante este país (India) en reverencia. La gente sabrá quién fue Jesucristo y de dónde vino. Entonces será adorado con debido respeto en esta Tierra Sagrada. En India, incluso hoy, la modestia de las mujeres está protegida y son tratadas con mucho respeto. Cuando la gente de otros países venga a visitar esta tierra sabrán que es en este país donde se practica la verdadera Cristiandad, con gran devoción, y no en los países en los que se profesa la religión cristiana.

Jesucristo dijo: “Tenéis que nacer de nuevo”. En nuestro país nos referimos a este proceso como “Dwija” o nacido por segunda vez. El segundo nacimiento de cualquier ser humano solo es posible por el despertar del Poder de la Kundalini. Hasta que la Kundalini no sea despertada no se alcanzará el segundo nacimiento, y hasta que no recibamos el segundo nacimiento no seremos capaces de reconocer a Dios. Leed la Biblia después de la Realización; os sorprenderá saber que Jesucristo no habló de otra cosa que de la importancia de Sahaja Yoga. Todo ha sido explicado con los más mínimos detalles. Aquellos que no tienen discernimiento tergiversan la materia. En realidad, bautizar quiere decir despertar el Poder de la Kundalini para que, después de ascender, atraviese el Sahastrara, y allí se dé la unión del Poder Todopenetrante de Dios con el Poder de la Kundalini. De hecho, éste es el trabajo final del Poder de la Kundalini. Pero el clero no sabe nada de esto; en vano están tratando de hacer algo para lo cual no están autorizados.

Encontraréis a estos clérigos implicados en todo tipo de actos: de atención a los animales, de servicio a los pobres, a pacientes, etc. Vosotros me diríais: “Mataji, éstos son actos nobles”. Sí, ciertamente son actos nobles, pero este no es el trabajo de Dios. Servir a los pobres dándoles dinero no es el trabajo de Dios. El verdadero trabajo de Dios consiste en ayudar a la gente a entrar en el Reino de Dios, y a darles su unión con Dios. Llenar sus vidas de paz, prosperidad, felicidad, hermosura y gracia es realmente el trabajo de Dios. Dios no llegará a los pies de esas personas que roban, dicen mentiras o vagabundean debido a su pobreza. Ayudar a personas así es un acto de bondad y puede hacerlo cualquier persona. Os daréis cuenta de que algunos cristianos están implicados en trabajos proselitistas. Irán a cualquier rincón remoto en el que residan los adivasis (aborígenes); allí llevarán a cabo algún trabajo de servicio a los adivasis y después los convertirán al cristianismo. Pero una cosa debe quedar clara: éste no es el trabajo de Dios; el trabajo de Dios es Eterno.

En Sahaja Yoga los enfermos se curan cuando se despierta su Kundalini. En Sahaja Yoga no realizamos ningún trabajo de seudobondad. Si vamos a cualquier hospital podemos curar fácilmente a veinticinco o treinta pacientes. Con el despertar de la Kundalini se curan automáticamente, porque dentro de nosotros está el Poder del Amor. Gracias al despertar de la Kundalini, este Poder de Amor comienza a fluir por su cuerpo y el mismo Poder les cura. Jesucristo curó a muchas personas con el mismo Poder que fluía a través de Él. Jesucristo no ayudó a nadie en cosas materiales. Tenemos que entender estas cosas detenidamente. No repitáis los errores del pasado. Recibid vuestra Realización; éste es vuestro primer deber. Después de vuestra autorrealización vuestros poderes están despiertos.

Este Poder ha curado enfermedades como el cáncer, que se considera incurable. De hecho, podéis curar cualquier enfermedad. Enfermedades como el cáncer solo pueden curarse en Sahaja Yoga. Sin embargo, aquellos que se curan vuelven a sus antiguas andanzas y hábitos; ya no buscan más a Dios. Personas así solo se acuerdan de Dios cuando quieren ser curados de alguna enfermedad. De lo contrario no piensan que sea necesario buscar a Dios. ¿Por qué debería entonces Dios preocuparse por aquellos que no desean ser la Luz de Dios? Personas así, curadas o no, no extenderían la luz en este mundo. Dios solo encendería aquellas lámparas que extendieran la luz por todo el mundo. ¿Por qué habría Dios de curar a la gente estúpida? ¿Por qué ha de ayudar Dios a aquellos que no quieren hacer su trabajo o a aquellos que no quieren buscarle? El trabajo de ayudar a los pobres o el trabajo social no debería ser confundido con el trabajo de Dios.

Algunas personas degradan la relación con Dios al nivel más bajo. En cierto lugar vi en un tablón de anuncios: “Shri Sai Nath Bidi”. Utilizar el nombre de Dios de una manera tan sucia es un tremendo insulto a Dios. Al relacionar cualquier insignificante cosa mundana con Dios, cometéis grandes pecados. Esto deberíais saberlo. Sai Nath Bidi o Lakshmi Hing en un anuncio así es un insulto a Dios. ¿Qué ganan estas personas haciendo esto? Alguna gente dice: “Madre, esto nos hará bien”. ¿Qué es haceros bien? ¿Qué es bueno? Por su expresión quieren decir que hacen más dinero. Si un negocio se lleva de esta forma, un día u otro les va a traer problemas. Éste es un gran insulto a Dios.

Jesucristo vino a salvar y liberar a la humanidad entera. No era la posesión personal de ninguna secta en particular. Él mismo era la encarnación de “Aumkar”; Él era “Pranava” y la Verdad. Los cuerpos de las demás encarnaciones se crearon a partir del principio “tierra”, mientras que el cuerpo de Jesucristo lo fue a partir del principio del “Alma”. Por eso resucitó después de muerto. Y solo a través de su resurrección sus discípulos pudieron saber que Él era Dios mismo. Entonces empezaron a tocar las trompetas, a recitar su nombre, a predicar sobre Él. Lo más importante es que Dios encarnó. Si la gente le reconociera y asegurara la bienaventuranza y el desarrollo espiritual, esto iluminaría el alma y extendería la felicidad y la gloria por todas partes.

Que todos alcancéis el Yoga de Dios.

Muchas, muchas, bendiciones.