Seminario, Abrid vuestros corazones

Mill Farm Sherborne, Inglaterra 02-08-1981

En qué lugar tan hermoso estamos todos. Es una bendición de Sahaja Yoga para que todos vosotros os relajéis. Relajaos bien, porque solamente en relajación os daréis cuenta de que: ahora somos almas realizadas, que hemos entrado en el Reino de los Cielos, que podemos ver toda la belleza que Dios ha creado alrededor de nosotros, que nos hemos vuelto sensibles a su gracia, su bondad y su amor.

Habéis organizado un seminario y estoy muy contenta. Siempre he querido que organizarais seminarios, que os reunierais y vivierais juntos, y os comprendierais unos a otros.

Los seminarios trabajan muchas cosas en el nivel grosero, sin duda, pero los seminarios de sahaja yoguis significan mucho en niveles más sutiles.

Significa que sólidos núcleos se están consolidando en distintos lugares de un país y estas fortalezas o los núcleos poderosos que son creados así, pueden formar un mecanismo por el cual pueden fluir o ser proyectados por todo el lugar rayos de intensas vibraciones. Es una gran tarea construir estos mecanismos divinos en distintas partes de vuestro país.

Por ejemplo, la Madre Tierra ha hecho su trabajo. En cualquier lugar que le ha sido posible ha creado deidades vivientes para demostrar que Dios existe. Ahora podéis poner a prueba sus vibraciones. Ved lo duro que ha trabajado. Ha creado todo este hermoso Universo, también os ha creado a vosotros. Ha creado la Kundalini dentro de vosotros y representa la hermosa naturaleza.

Cuando estáis empapados de su compañía, de su generosidad y os encontráis unos con otros, veis por vosotros mismos cómo os bendice a todos de la misma manera. Para Ella no hay ninguna diferencia entre vosotros y alguna otra persona. Pero aquellos que son sensitivos y más sutiles la disfrutan más que vosotros.

He visto que el problema que existe en cada país tiene su propio estilo, y en este país tenemos un estilo que gradualmente está cambiando su forma. Al principio encontré que la gente era muy agresiva, escéptica e incluso, a veces, podía ser grosera. De acuerdo. No me importa.. Ahora han empezado a cambiar gradualmente. Están empezando a ser conscientes de lo que tienen, de qué papel están jugando y lo importante que es ser un inglés (cuando digo un inglés quiero decir toda la gente inglesa, no galesa o algo distinto) y cómo han venido a ser parte del Corazón del Universo. Me pregunto cuántos de vosotros os dais cuenta de lo importante que es ser inglés. Todo lo que ocurre en este país circula. Por ejemplo si esta boda, la del príncipe de Gales con Lady Diana, que es un alma realizada, hubiera tenido lugar en otra familia real, no se hubiera divulgado tanto. Todo circula desde este país. Puede que no os consideréis gran cosa. Puede que penséis que después de todo Inglaterra es como cualquier otro país. ¿Pero por qué la gente acepta tantas cosas de vosotros?

Incluso la monarquía. La mayoría de todos los países han desechado sus monarquías y en este país existe, tiene una posición muy respetable y el símbolo de la monarquía aún permanece aquí con orgullo. Después el matrimonio. Los matrimonios de las familias reales han sido puestos a prueba, han sido protestados y detestados, nadie se interesa en ellos. Y que una cosa tan auspiciosa tuviera lugar aquí, que todo el mundo lo viera, que tantos países lo vieran y apreciaran, y sobre todas las cosas que lo disfrutaran, es algo sorprendente. Trasciende toda racionalidad, todo entendimiento de la lógica. Podríamos decir: ¿Cuál es la lógica que hay en ello? Pero si estáis disfrutando, simplemente queréis disfrutar, no queréis pensar por qué estáis disfrutando.

Así, uno tiene que entender que sois parte del Corazón del Universo. Hay una cosa muy esencial y es que tenéis que ser gente muy flexible. Tenéis que tener la flexibilidad de las células del corazón. El corazón tiene que bombear. Tiene que ser fuerte, y sorprendentemente el león es vuestro emblema, por tanto tenéis que tener un corazón de león. Y corazón de león quiere decir que el león nunca está asustado. Es el rey y vive como un rey, como un león. Y Leo en Astrología es una persona extremadamente generosa. Con corazón de león, sin temor a nadie. No debería haber temor. Pero en la lengua inglesa, si leéis o escucháis a alguien, cada tres frases dice: "Me temo que..." "Me temo que esto es así". Estas palabras tienen que ser descartadas del vocabulario de los sahaja yoguis. ¿ De qué hay que tener miedo? Algunas personas opinan que esto se dice porque no queremos herir a otras personas. Pero hay muchas otras formas de decir las cosas sin herir a otros.

Entonces, ¿ qué hay que temer? Un hombre que es débil no puede amar. Solo una persona fuerte puede amar. Si habláis de amor, primero ved si tenéis la cualidad de amar o no. Amar no es una cosa fácil, incluso el amor carnal, incluso amar a vuestra persona amada en el sentido ordinario no es una cosa fácil. Tenéis que tener un concepto moral muy fuerte. De otra forma la gente cada tres minutos empieza a cambiar sus "amores". Esa clase de amor no tiene significado. Tenéis que tener ideas muy firmes. No solo ideas dentro de vuestro cerebro sino construidas dentro de vosotros. Muy poca gente puede tener un amor como el que tenía Romeo, os lo puedo asegurar. Es muy fácil pensar que sois un Romeo. Es distinto. Podéis pensar que sois el rey de Inglaterra, vale, pero así no os vais a convertir en eso. Para ser el verdadero Romeo, tenéis que tener un carácter tremendo, un tremendo sentido de sacrificio, amor y comprensión. Simplemente queréis amar, eso es todo, nada más allá. Quiero decir que cuando un hombre se enamora, se enamora para siempre. Si se enamora muchas veces, no puede ser amor. Por lo tanto esa experiencia es una especie de fruta prohibida para la mayoría de vosotros.

Así, amar a Dios es mucho más difícil, sin verle, sin conocerle, sin conocer su bondad. Sin obtener la Realización es muy difícil. Pero hoy, ese no es el caso. No obstante no tenéis que tener miedo en vuestra mente. Confiad. Confiad en vosotros mismos y en otros. Lo primero de todo, tratad de confiar en vosotros mismos. Si habéis cometido faltas tenéis que decir: Sí, he cometido faltas, ¿y qué?

Confiad en vosotros y en que podéis corregiros. Confiar no quiere decir un ciego viaje del ego. No quiere decir eso. Quiere decir que sí puedo corregirme, mejorar, hacerlo mejor. Algunas personas piensan que, si confiáis en vosotros, nunca deberíais confesar algo que habéis hecho mal. Que nunca deberíais decir que estaba mal y que puedo corregirlo. Éstas son ideas equivocadas. Tenéis que confiar en vosotros diciendo: "Sí, he cometido faltas. Lo he estado haciendo mal. He estado fallando, pero puedo corregirlo. Tengo esa fuerza dentro de mí. Puedo elevarme por encima de todas esas cosas. Tengo eso dentro de mí y puedo usarlo en mi provecho".

Confiad en vosotros. Confiad en que sois almas realizadas. Confiad en que Díos os ama. Os ha elegido para ser su instrumento. Amaos a vosotros mismos. Sois únicos, sin duda. Cada ser humano individual es una personalidad única. Pero después de la Realización sois definitivamente únicos. Uno tiene que usar discreción en la comprensión, que no quiere decir un viaje del ego. Si no podéis corregiros, no sois maestros de vosotros mismos. ¡Sí, no sois perfectos! Sois únicos, pero no sois perfectos. Tenéis que perfeccionaros.

Estas palabras pueden ser muy confusas. Cuando digo que sois únicos, inmediatamente pensáis que sois perfectos. Estas son dos palabras: único y perfecto. Alguien puede ser único, pero puede tener imperfecciones. Por tanto tenéis que perfeccionaros y confiar en vosotros, en que podéis perfeccionaros a través del despertar de vuestra Kundalini, limpiando vuestros chakras, comprendiéndoos a vosotros mismos podéis perfeccionaros.

Yo tengo muchos caminos. Os hablo directamente, a veces indirectamente a través de amigos; de alguna manera os señalo que este es el problema con vosotros. Deberías pensar que estoy dentro de vosotros. Yo soy, dentro de vosotros, esa parte que es discreción. Cuando no comprendéis vuestra propia discreción, yo intento daros la dirección de un modo u otro. Pero la gente se siente herida, se siente mal, o algunos lo aceptan. Si sois buscadores y estáis ascendiendo, definitivamente sois únicos; sois especialmente bendecidos y tenéis que prestar especial atención a vosotros mismos. No os podéis permitir el jugar con vosotros mismos. Por tanto tenéis que discriminar entre ego, o viajes de ego como ellos lo llaman, y ascenso. Los viajes de ego os van a llevar al dolor más agudo. Sería como lanzaros al aire y volver con un chichón y romperos una pierna o algo así. Eso es lo que es un viaje de ego. Pero ascenso es realmente cuando os eleváis más arriba. No solo que ascendéis vosotros sino que con vosotros hacéis ascender a otros. En vuestro ascenso desarrolláis poderes tremendos. Cuanto más alto ascendáis, mejor. Pero no por pensar que sois perfectos vais a ascender.

Hay una historia de un profesor y su estudiante. El profesor era muy amable con el estudiante, y éste venía y le mostraba sus creaciones. Era muy amable, y siempre decía: "He hecho esto bien y esto es lo que no he podido hacer, así que, ¿podría decirme cómo corregirlo?" Y el profesor decía: "Sí, muy bien. Mejor que corrijas esta parte. Haz esto". Un día el estudiante vino y dijo: "Ahora esto es perfecto". El profesor le dijo: "Ya no eres más un estudiante. Ya no tienes que venir más a mí". Había otro estudiante que venía todos los días y se corregía a sí mismo y le dijo a su profesor: "Creo que puedo enseñar a otros, aunque no perfectamente" y contesto: "De acuerdo, ve y enseña". El tercero era un estudiante que siempre venía y trataba de ver cuál era la falta y cómo tenía que corregirla, y trabajó muy duro, muy asiduamente; un día fue a su profesor y le dijo: "Señor, ya no le molestaré más. Él le dijo: "Es verdad, ahora tú toma mi lugar".

Esto es lo que uno tiene que entender. Si ascendéis, os volveréis más humildes. La gente lo entiende completamente al revés. Cuando han ascendido, piensan que han adquirido poderes especiales. De repente empieza la aprobación de uno mismo "soy muy bueno en espiritualidad, estoy muy alto... y todo eso." Esta autoaprobación comienza y puede llegar a un punto tal en el que de repente os deis cuenta de que no podéis estar en la Tierra otra vez. No es así cómo esto funciona. De hecho hay ciertas cualidades que se observan en gente que asciende.

La primera cosa es su colectividad. ¿Cuán colectivos sois? ¿Con cuánta gente podéis relacionaros? ¿De cuántas cosas os podéis reír? Esa es una de las más grandes cualidades.

La segunda cualidad es en qué gran medida aceptáis la dominación de otro que os acorta vuestra colectividad. Debéis tener vuestra personalidad separada de todos. Si permitís a otros cortar vuestra personalidad; por ejemplo, digamos que hay un jefe, tú eres un empleado y ambos sois almas realizadas y uno de los dos está ascendiendo y se vuelve más humilde y mejor. Tienen una relación agradable. Pero hasta un punto. Él nunca transigirá con su jefe en lo que se refiere a su ascenso, su colectividad, su entrega, su hacer cosas por otros. En ese punto, nunca tendrá ninguna dominación.

El segundo punto es lo responsables que os sentís de vosotros mismos. ¿Cómo sois de responsables de estar allí, de ser una célula en el corazón? Una célula que flaquea hace flaquear al corazón. Cada célula en el corazón tiene que ser extremadamente sensitiva, y extremadamente obediente al Ser, al Espíritu. Tiene que activarse, trabajar duro cuando hay necesidad o emergencia, y es la que más disfruta. No debería permitirse ninguna impureza.

Ahora el tercer punto. Como os he dicho, primero colectividad, segundo vuestra responsabilidad, y el tercer punto es pureza. Antes que nada la pureza de vuestro propio corazón. Con toda sinceridad, sin astucia. Según digo esto os daréis cuenta de que todos los ingleses creen en lo contrario. No en los viejos tiempos sino en los actuales.

Corazón limpio, transparente, abierto. Confiad en otros. ¿Por qué dudáis? Si no dudáis de vosotros no dudaréis de otros. ¿Qué os van a quitar? ¿Qué tenéis?, nadie puede llevarse vuestra nariz, ojos, nada. Todo está intacto. Todo está muy bien pegado, por tanto no va a desaparecer. ¿Cómo van a herir a una persona que es un alma realizada? Si vuestro corazón está limpio podéis ver claramente a través de otra persona. La inocencia es una cosa tan poderosa. Tan poderosa que incluso una rápida mirada podría matar a un diablo. Pureza del corazón.

De hecho cuando el corazón se vuelve impuro, la impureza fluye hacia otros lugares. No es al revés. Es desde el corazón. Mucha gente piensa que es el cuerpo el que se vuelve impuro. Yo creo que es el corazón el que se vuelve impuro. Empieza a gotear en él y se queda como un residuo. Se asienta allí.

Por tanto tened un corazón limpio, abierto, como el corazón de un niño. ¿Qué hay que temer de alguien? ¿Qué hay para no confiar en otros?¿Por qué estar enfadados con alguien? Hablad con todos, dad la mano a todos. Por el camino encontraréis alguien con dificultades. Echadle una mano. Si alguien no se siente bien o tiene un problema, intentad resolverlo. Si alguien no puede estar de píe, cededle el sitio. Intentad dar desde un corazón limpio. Si vuestro corazón no está limpio nunca puede dar.

El asunto ahora es cómo limpiar el corazón. No hay una escoba disponible para eso en el supermercado. No hay líquidos ni nada para lavarlo. Pero hay un modo.

Permitid a vuestro corazón empaparse en el Amor de vuestra Madre. Simplemente permitídselo. Ved cuánto os quiere Ella. Yo confío en vosotros. La gente se ríe de mí algunas veces. Alguno de esos santos que se supone que son gente muy grande. No pueden entender cómo confío en vosotros. Ellos dicen: "¡Oh!, esas son razas perdidas. Son personas horribles. ¿Cómo confiáis en ellos? No son sanyasins, no son sadhus, no son nada. Son gente ordinaria." Para ellos no valéis nada. Si vais a ellos harán que os pongáis sobre la cabeza durante tres meses. Puede que os cuelguen sobre un pozo durante tres años. No sé qué os harían para poneros a prueba.

Pero yo confié en vosotros el día que os vi. El día que vinisteis a mí, yo confié en vosotros. Trabajé en vosotros desde el primer día, sabiendo lo que sois, pero confié en vuestro Espíritu y en que brillaría. Confiad de la misma manera. Nos reímos de otros. He visto sahaja yoguis reírse de otros, se ríen de ellos cuando vienen a mí. Confiad en ellos. Cuando confiéis en ellos, también los respetaréis.

Así, tenéis que creer en vosotros mismos y disfrutar el suave modo en el que os estáis uniendo a la corriente del Amor de vuestra Madre. Disfrutadlo. Como una flor cae en la corriente y fluye y disfruta de toda la belleza de esa corriente. De la misma manera deberíais disfrutar vosotros. Cuando este gozo surja dentro de vosotros empezaréis a confiar. Y confiad en vuestra Madre.

Yo intento muchas cosas para corregiros, pero confiad en una cosa. Cualquier cosa que intente hacer o haga por vosotros, es solo para limpiaros. Ese es mi trabajo. Puede que sintáis que algunas veces os diga cosas en público. Puede que penséis cosas como que vuestra imagen se echa a perder. No es así. Es por vuestro "hita", por el bienestar de vuestro Espíritu y ese es el trabajo más difícil.

Con toda esta confianza en el corazón, confiad primero en vosotros, después en los sahaja yoguis. Ama a tu prójimo como a ti mismo. ¿Quién es tu prójimo? Un sahaja yogui. Permanece a su lado.

Confiad en vuestra Madre, como yo he confiado en vosotros. Tenéis que confiar en mí y todo funcionará. Abrid vuestro corazón a esta confianza. No deberíais preocuparos de si es absolutamente respetable o no, porque el corazón lo sabe. Cualquier cosa que vuestro corazón haga en su forma genuina será respetable, porque allí reside vuestro Espíritu que se manifiesta y se preocupará de ello. Cualquier cosa que intentéis con formas exteriores no va a funcionar. Es esa confianza en vuestro corazón amoroso lo que lo va a hacer.

No importa. Como veis ella trajo hoy algunas flores. Había algunas que, según ella, eran malas hierbas. Fue a la estación y cogió algunas flores; el jefe de estación y su mujer que estuvieron muy agradables, dijeron: "Adelante, solo son malas hierbas. Puedes cogerlas". Y son tan fragantes. Una de las flores más fragantes que nunca he visto. Son simplemente malas hierbas. No entonan con ningunas otras flores convencionales ni con nada, pero unas poquitas flores junto a otras es de lo más fragante.

El amor da toda la satisfacción, fragancia y educación que se requiere. No hablar de amor, sino realmente amar es el camino. Es de lo más agradable.

Sé que algunos de vosotros puede que no hagan mucho. Vale. Intentaré decíroslo muchas veces. Intentaré ayudaros, pero la mayoría de vosotros podéis hacerlo. Y deberíais intentarlo.

Así, desde hoy, comenzamos nuestro Sahaja Yoga en un nivel más profundo, donde alguno de vosotros puede que no lleguéis. Pero la mayoría de vosotros deberíais intentar profundizar. "Todos". Para eso no se necesita ser personas con mucha educación o estar bien situados. De ninguna manera.

La gente que medita, se dedica y profundiza, son como las primeras raíces que tienen que llegar para otros, más profundas, y así los otros podrán seguirles.

Para el Puja de hoy, tendremos un Ganesha Attharva Sheersha muy corto. No para lavar mis Pies.

Uno puede decir: "Madre cuando lavamos tus Pies, recibimos tus Vibraciones en el agua"....Pero es algo tan desapegado que no hay necesidad de lavar; es un estado en el que os laváis completamente, os limpiáis completamente.

Luego tendremos un Devi Puja, porque Gauri, que es la Virgen, ha de ser adorada, así que diremos los 108 nombres de la Virgen. Después haremos un Shiva Puja.

Siento no poderos decir todo sobre ésto en una pequeña charla. Pero el desapego debe empezar a expresarse a sí mismo en vuestra Realización. ¿Qué es rendirse? No es nada. Porque cuando sois desapegados, os entregáis automáticamente. Cuando os agarráis a otras cosas, no estáis entregados, eso es todo.

¿Qué hay para entregarme a mí? Soy una persona tan desapegada que no entiendo esas cosas. ¿Qué voy a obtener de vosotros? ¡Nada¡ Soy tan desapegada...

Así espero que todos recemos: "¡Oh Señor!, danos fuerza y esa fuente de atracción por la que dejemos todas las demás atracciones por todos los placeres, por todas las cosas sobre las que pensamos; pero deberíamos entrar, absolutamente, en la forma de Puro Gozo del Shiva-Tattwa."

Espero que haya podido explicaros por qué estoy aquí y por qué hoy es un gran día. Todos los que estáis aquí sois gente especialmente afortunada y deberíais pensar que Díos ha sido amable con vosotros, que Él os ha elegido para que hoy estéis aquí, para que escuchéis esto. Y entonces, una vez que os hacéis desapegados, empezáis a sentiros responsables. No ego, sino responsabilidad, que actúa por sí misma, se expresa y se manifiesta por sí misma.

Que Dios os bendiga