1 stycznia 1983
Zasada Mahalakszmi
Mahalakshmi Pudźa
Kolhapur (Indie)

Dzisiaj, znowu, jest Dzień Nowego Roku.

Każdy nowy rok nadchodzi, ponieważ musimy zwrócić się ku czemuś nowemu. Zostało tak ustalone, że słońce musi poruszać się przez 365 dni i ponownie musi nadejść Nowy Rok. W rzeczywistości cały Układ Słoneczny porusza się spiralnie. Tak więc, istnieje zdecydowanie wyższy, wyższy stan tego Układu Słonecznego. Każdego roku wznosi się coraz wyżej w sposób spiralny. Zatem nie chodzi tylko o to, że minęło 365 dni, ale dlatego, że przesunęło się o krok do przodu, wyżej niż było. Teraz widzimy, że w świadomości ludzie zdecydowanie wznieśli się znacznie wyżej niż byli, powiedzmy, około 2000 lat temu. Jednak pierwszy system, który zapoczątkował cały wszechświat, to pierwszy model, można powiedzieć, został stworzony. I ten model musiał być doskonały. I był to doskonały model, który potem zaczął doskonalić resztę.

Tak więc, to jest doskonały model, który stanowi zasadę tego wznoszenia. I to umożliwia to wznoszenie. Teraz doskonałość reszty wszechświata odbywa się w różnych kierunkach. Ale dzisiaj musimy rozważyć zasadę Mahalakszmi. Teraz Mahalakszmi, jak wam mówiłam, to doskonała zasada. To doskonała zasada. Jest udoskonalona. Narodziła się doskonała i pozostanie doskonała. Będzie zawsze, na wieki doskonała, tak że nie trzeba jej korygować. Teraz tę kwestię Mahalakszmi omawiam tutaj, ponieważ być może dzisiaj będziecie mogli udać się, aby zobaczyć świątynię Mahalakszmi.

Gdy idziecie do świątyni Mahalakszmi, musicie wiedzieć, że to bóstwo wyłoniło się z Matki Ziemi w tym konkretnym miejscu. To oznacza, że to miejsce ma zdolność dania wam siły, można powiedzieć, dodatkowej energii, lub intensywnego uczucia ewolucji. Jeśli jesteście wystarczająco wrażliwi, możecie to zobaczyć, poczuć i uczynić. Ale jeśli nie jesteście tak wrażliwi, nadal jesteście tak uwarunkowani i wciąż zewnętrzni, to może nie zadziałać. Mam na myśli, że można zrobić wszystko, ale jeśli ktoś chce pozostać jak kamień, nic z tym nie da się zrobić. Tak więc zasada Mahalakszmi działa w tym miejscu, Kolhapurze. Zazwyczaj to miejsce powinno być bardzo, bardzo ciepłe z powodu swojego położenia. Ale nawet latem to miejsce pozostaje bardzo chłodne ze względu na wibracje emitowane przez świątynię. Ludzie w tym miejscu mogą również nie być tak świadomi. Nie możemy powiedzieć, czy są świadomi, ponieważ gdy musi się ujawnić negatywność, działa tu wiele cukrowni i panuje tu duży problem alkoholowy.

Ale musimy jak najlepiej wykorzystać każde miejsce, które zostało stworzone specjalnie dla określonego celu. Tak więc, w pewnym sensie, jest to pielgrzymka, że jesteście tutaj. Że musicie dbać o naszą zasadę Mahalakszmi naszego wznoszenia. Jak wiecie, to wznoszenie zaczyna się od Nabhi i jest otoczone zasadą Guru. Zasada Guru w was, jeśli jest niedorzeczna, jeśli jest zestawiona, umieszczona w takim zestawieniu, gdzie, jeśli nie jest właściwie zakorzeniona w was, jeśli nie emanuje przez wasz charakter i zachowanie, tattva Mahalakszmi nie może być wzmocnione. Tattva Mahalakszmi jest wzmacniane poprzez zasadę Guru. Dzisiaj mamy szczęście, ponieważ były urodziny Datty, Dattatrei, zaledwie kilka dni temu, kiedy odbyła się pudźa, a dzisiaj odbywa się pudźa Mahalakszmi. Tak więc, dwa wydarzenia połączyły się. Najpierw była pudźa Datta, a dzisiaj ta pudźa Mahalakszmi. Aby zasada Guru była właściwa, musimy uczynić nasze dharmy poprawnymi.

Te dharmy, jak wam wielokrotnie mówiłam, jest ich dziesięć. I powinniście dbać o te 10 dharm w bardzo staranny sposób. Te przejawiają się na zewnątrz, ale to, co wewnątrz, wychodzi na jaw. Zauważam, gdy wy rozmawiacie i mówicie, wiem, że ta osoba jest negatywna, ta osoba jest zdecydowanie pozytywna. Istnieje tak wiele sposobów wyrażania pozytywności. Ale skąd mam to wiedzieć, nie mogę wam tego powiedzieć, bo po prostu nie wiem, jak to ująć. Ale wiem, że taka osoba jest zdecydowanie pozytywna, a taka osoba jest negatywna. Pozytywność polega na zrozumieniu, dlaczego tu jesteśmy. Przede wszystkim, dlaczego jesteśmy na tej ziemi? Dlaczego jesteśmy ludźmi zdolnymi do rozumienia?

Co z tym robicie? Dlaczego jesteśmy Sahadźa joginami? Co musicie czynić jako Sahadźa jogini? Jaka jest wasza odpowiedzialność jako Sahadźa jogini? Następnie przechodzicie do zrozumienia, "Dlaczego Matka jest tak dla mnie miła? Dlaczego mam wibracje? Dlaczego jestem wśród nielicznych, którzy otrzymali te szczególne błogosławieństwa, specjalną wiedzę o świadomości wibracyjnej?" A następnie zapytajcie siebie: "Co z tym robicie?" Czy nadal jesteście głęboko zanurzeni w waszej tandetności lub dziecinności, w waszej głupocie, w waszej surowości, w waszej agresywności?" Zawsze widzicie te cechy u innych, a nie u siebie - więc nie jesteście Sahadźa joginami.

Powinniście zrozumieć, że w momencie, gdy zaczynacie dostrzegać te cechy u innych, to nie jesteście Sahadźa joginami. Powinniście spojrzeć w siebie i emanować czystym współczuciem wobec innych. Ale ludzie zawsze widzą, że to istnieje u innej osoby. Cokolwiek próbuję powiedzieć, oni zawsze widzą to w innej osobie. Przypuśćmy, że wśród was jest ktoś negatywny, nie musicie okazywać temu człowiekowi współczucia. Wręcz przeciwnie, lepiej trzymajcie się z daleka. Pozbądźcie się tej osoby, o ile to możliwe, nie macie z nią nic wspólnego. To zdecydowany dowód wielkiego współczucia wobec siebie, jeśli nie też wobec innych. Lepiej nie mieć nic wspólnego z osobą negatywną, jeśli musicie się z nią stykć. Może być waszym bratem, siostrą, kimkolwiek.

Ale starajcie się trzymać z dala od osoby, która nie jest pozytywna. Powoduje to wiele problemów. Mówiłam wam to i prosiłam was, ale uwarunkowania są takie, że, mimo iż staliście się tattvą Guru, nie rozumiecie, że musicie być oderwani. Dla Guru nie ma brata, siostry ani żadnych innych relacji poza relacją z Matką. Nie ma żadnej innej relacji. Jedną z zasad, które należy zrozumieć, jest to, co uważam za bardzo ważne dla nas wszystkich, że nasze relacje dotyczą wyłącznie Matki i Sahadźa joginów, a nie jakichkolwiek innych związków, które zawarły się między wami, czy to poprzez Sahadźa Jogę, czy przez cokolwiek innego. Wyjaśniam to, ponieważ nasza tattva Mahalakszmi nie jest w porządku. Dlatego, w pewnym sensie, mówimy, że została rozproszona, zagubiona, w te sprawy. A tattva Mahalakszmi musi być jak siła wznosząca się, całościowo zjednoczona. Na przykład, mój ojciec podawał przykład: przypuśćcie, że zgromadziliście dużo pszenicy i rozsypaliście ją na ziemi, całość zaginie.

Rozsypie się tak, tu, tam, całkowicie zniknie. Ale jeśli wsadzicie ją do worka, naturalnie się podniesie. Będzie miała swoje maryady. Będzie się podnosić i wznosić coraz wyżej. Podobnie, zasada Mahalakszmi może się rozprzestrzeniać właśnie tak, i może po prostu zniszczyć wszystko, co Matka nam dała i wszystko, co mieliśmy przez te wszystkie lata, tylko przez rozprzestrzenianie na zewnątrz. Aby to zebrać wewnątrz, musicie zwrócić uwagę na siebie. Przede wszystkim spróbujcie wyjaśnić swoje myśli i zrozumienie w mózgu, to ważne. Ponieważ tattva Mahalakszmi ostatecznie działa w mózgu. To oświecenie umysłu, dokonane przez tattva Mahalakszmi. Daje wam "sattva", prawdę, widzicie.

Więc w mózgu musicie wyjaśnić, dojść logicznie. Logicznie musicie dojść do wniosku, że, "Nie musicie robić tych rzeczy, musicie robić te rzeczy. Musicie wznosić się. Dlatego tu jesteście. Dlaczego tu jesteście? Co powinniście zrobić?" Przede wszystkim logicznie przekonajcie swój mózg. To bardzo ważne po Samorealizacji. Ponieważ jeśli logicznie wasz mózg nie zrozumie, zawsze będzie tandetny, dziecinny, pozbawiony godności lub może być surowy, okropnie opresyjny. Może być taki.

Tak więc, w tattvie Guru jest 10 elementów. Pięć z nich dotyczy ciężaru. Ciężaru. Guru to ciężar, widzicie, ciężar osoby. Ile macie ciężaru? Grawitacja, jak to nazywamy. Osoba ma swoją grawitację. Kiedy mówi, jaką ma równowagę. W indyjskiej muzyce nazywamy to vazan, co oznacza ciężar. Ciężar osoby oznacza, że kiedy radzi sobie sama ze sobą lub z innymi, ile ciężaru niesie.

W języku angielskim używa się również tego słowa: ile ciężaru niesie przy innych. To znaczy, jak bardzo może naprawdę zaimponować innym? Jeśli zrobicie zbyt duże wrażenie, to osoba powie: "Och, to za dużo". To bardzo ważna cecha u ludzi z zachodu, "Och, to za dużo!" Tak to postrzegają, widzicie. Wszystko to jest napędzane przez ego, "To za dużo". Jeśli powiecie im za dużo, "Och! to za dużo. Za bardzo". Robię to powoli, powoli.

"To za dużo dla was" To bardzo powszechna, bardzo powszechna reakcja. Więc, ile macie ciężaru. A drugi to jakość magnetyzmu. Dwie rzeczy. Magnetyzm. Pierwsza to jakość ciężaru. To pokazuje, jak bardzo jesteście dostojni, jak mówicie. Jakim posługujecie się językiem. Jakie jest wasze zachowanie. Powinniście być dowcipni.

Ale czasami, nawet u mnie, zauważam, że ludzie mówią w bardzo zabawny sposób. Po prostu nie rozumiem, jak to się dzieje, że zawsze mówią niewłaściwe rzeczy? Mam na myśli, że nawet gdy mają powiedzieć jedno zdanie, wypowiadają coś błędnego. To zupełnie im się zdarza. Jest też Wiśuddhi, które pochodzi z Nabhi, ponieważ musicie wiedzieć, że Czakra Wiśuddhi to wznoszenie się Czakry Nabhi. Więc, co się dzieje, to że osoba, kimkolwiek jest, wyraża się poprzez swój język, poprzez swoje zachowanie, poprzez twarz, nos, oczy, wszystko, przez Czakrę Wiśuddhi. Tak więc, wzrost Nabhi jest ukazany przez Czakrę Wiśuddhi. Cokolwiek macie w Nabhi, jest tu widoczne. Przypuśćmy, że osoba, która właściwie rozwinęła tattvę Mahalakszmi, taka osoba będzie miała sposób radzenia sobie z inną osobą, w którym będzie miała ciężar oraz zrozumienie: jak daleko posunąć się z tą osobą. Jak długo kontynuować relację z tą osobą.

Jak długo z nią rozmawiać. Jak długo o niej myśleć. Jaką wagę przywiązać. To jeden z punktów, jest bardzo ważny. A drugi punkt to, ile macie magnetyzmu. Więc odwróćcie to z powrotem do siebie. Magnetyzm to magia, magia osoby. Osoba jest magnetyczna, ponieważ posiada pewną magię. Ta magia pochodzi z waszej własnej osobowości. Z waszej własnej osobowości.

Tak więc, podstawa magnetyzmu, z lewej strony, zaczyna się. I tą podstawą jest Śri Ganesza. Śri Ganesza jest podstawą tego magnetyzmu. Zatem wasza niewinność. Niewinność jest najlepszym sposobem, aby mieć ten magnetyzm. Magnetyzmu nie można wyrazić materialnie. To nie jest rzecz materialna. Ale to coś abstrakcyjnego, pochodzi z waszej cechy Śri Ganeszy. Taka osoba jest magnetyczna. Magnetyczna oznacza, że taka osoba przyciąga inną osobę ze względu na ciężar tej osoby, ze względu na jej jakość, taka osoba przyciąga.

Ale nie przyciąga z powodu pożądania, chciwości i bezsensownych rzeczy. Ale przyciąga inną osobę z powodu zapachu miłości tej osoby. Teraz to jest zawsze mylące. Mylące. Bo to taka abstrakcyjna rzecz. Dlatego trzeba to zrozumieć w bardzo subtelny sposób, czym jest ten magnetyzm, który powinniście mieć. Widzicie, są pewne gesty, których ludzie używają sztucznie, które normalnie używali tylko po to, by przyciągać innych, sposób, w jaki chodzą, sposób, w jaki się ubierają, sposób, w jaki żyją. Wszystko to jest bezużyteczne. To coś tak wewnętrznego, ten aromat jest tak głęboki, który trzeba rozwinąć. Ale w Sahadźa Joge widziałam, że ludzie po prostu się tym nie przejmują, po prostu nie dbają.

Myślą, że sposób, w jaki żyją, sposób, w jaki są, - powiedzmy, jeśli są Anglikami, to są Anglikami. Jeśli są Francuzami, to są Francuzami. Jeśli są Hindusami, to są Hindusami. Jeśli pochodzą z Kolhapuru, to są z Kolhapuru. Te idee najpierw trzeba powstrzymać, bo aromat rozprzestrzenia się wszędzie, niezależnie czy jesteście Anglikami czy kimkolwiek. Tak więc, aromat osoby rozwija się przede wszystkim poprzez zasadę Ganeszy w was. Zasadę Ganeszy należy przede wszystkim zauważyć. Osoba mająca Ganeszę nie jest kimś, kto jest absolutnie osobą pełną skruchy ani kimś, kto jest tak beznadziejny, że nawet gdybyście go pobili i rozdrobnili, on to wytrzyma. To nie tak. To nie tak.

Przeciwnie, jakość magnetyzmu polega na tym, że przyciąga was do punktu, gdzie nie jesteście w niepokoju. To bardzo ważna kwestia, którą powinniście znać. Widzicie, jeśli macie inny rodzaj miłości, jak miłość cielesna i wszelkie inne miłości, to ta miłość może przyciągnąć osobę. Ta osoba może was zniszczyć. I zawsze was niszczy. Ale to przyciąganie nie niszczy, nie niszczy niczego. Przyciąganie jest na tyle silne, że nie zostaniecie zniszczeni, ponieważ będąc o wiele wyżej, o wiele głębiej i o wiele bardziej znaczący, nie możecie zostać zniszczeni przez to, do czego jesteście przyciągani. Zawsze większy magnes przyciąga mniejszy magnes. I to właśnie powinniście zrozumieć: ta magia i to charyzmatyczne usposobienie osoby pochodzi przede wszystkim z tattvy Ganeszy, niewinności. A po drugie, poprzez całkowite oddanie i poświęcenie.

Ci, którzy są całkowicie oddani Matce, a nie czemukolwiek innemu - znowu tattva Ganeszy. Nie do waszej żony, nie do waszego męża, nie do waszej siostry, nie do waszego kraju, do nikogo poza Matką. Całkowite oddanie daje wam tę charyzmę, to przyciąganie. W Sahadźa Jodze taka osoba naprawdę przyciąga. Niektórzy myślą, że jeśli jesteście [Hindi] - Niektórzy uważają, że jeśli jesteście bardzo pasywni i jeśli ktokolwiek coś do was powie i nie zwracacie na to uwagi, taka osoba jest charyzmatyczna. To nieprawda. Ludzie lubią was, ponieważ mogą was dominować. Lubią was, bo mogą was kontrolować. Jeśli myślicie, że poprzez waszą agresję, wasze krzyki i wykrzykiwanie do tych ludzi, osiągniecie ten charyzmatyczny temperament, to nie zadziała. Nie możecie tego osiągnąć.

Więc, jak to osiągnąć? Stając się bardziej niewinnymi. Jak rozwija się niewinność u osoby? Poprzez nie myślenie o tym. Na przykład, ktoś mnie zapytał: "Jak poradzić sobie z podatkiem dochodowym?" Odpowiedziałam: "Nie mając w ogóle żadnych dochodów." Potem zapytali mnie: "Jak rozwiązać problem z samochodem?" "Nie mając w ogóle żadnego samochodu." Mówili: "A co z domem?" "Nie mając własnego domu."

"Nihi, Nihi." Wszystko "nihi" dla mnie. Mówią: "Jak rozwiązać ten problem?" "Nie mając go." Po prostu nie miejcie. "Nie, nie miejcie tego!" Nie obciążajcie się problemami. Gdy obciążacie się problemami, wtedy wasza niewinność maleje. Te kłopoty, takie, "To jest mój szal, to jest moja sari, to jest moja rzecz, to jest to, to jest to, to jest to". Ale tylko jedna rzecz jest taka: "To jest moja Matka i muszę Ją wysławiać", to wszystko.

Jeśli tak jest, wtedy niewinność zaczyna wzrastać jak Śri Ganesza. I poprzez brak innych kłopotów, "To jest moje, tamto jest moje." Ta kwestia "moje" powoduje problemy. Osobiście uważam, że to musi być powód. Że ta kwestia "moje". "To jest moje." Bo cokolwiek jest "moje". Ktoś mi powiedział, że to bardzo dobry argument, który mi przedstawił: "Cokolwiek jest moje, nie jest ja", co oznacza, że to nie jest Sahadźa. Moje ciało, moja głowa, wszystko moje, "moje". Ale "ja" – dał mi tę myśl: "ja".

Czym jest "ja"? Wtedy "ja" się oddziela. Cokolwiek nie jest moim, jest "ja". Więc to, co pozostaje, to wasz Duch". Ktoś przedstawił mi ten argument. Powiedziałam: "To bardzo dobry argument, by to rozważyć". Wtedy cokolwiek pozostaje, to "ja". I to "ja" jest tym, czego musicie szukać. Więc dalej redukujcie wszystkie te "moje", "moje", "moje". W ten sposób czysty duch niewinności wzrośnie.

Więc, jeśli chodzi o ducha, niektórzy myślą, że jeśli staniecie się duchowi -- Mam na myśli, nie wiem, co myślą ludzie o osobach duchowych. Ale idea o osobach duchowych polega na tym, że musicie być czymś niesamowitym, jak byk, czy nie wiem. Musicie być bystrzy jak lis, albo intelektualni jak Freud czy coś takiego. Ludzie mają wszelkiego rodzaju wyobrażenia. Nie, tak nie jest. Osoba duchowa jest po prostu niewinna, po prostu niewinna. Nie ma w niej inteligencji, nic. Tylko niewinność. Całość to niewinność. Cokolwiek mówi, wypływa z niewinności.

Nie ma w tym intelektu jako takiego, który wy posiadacie poprzez czytanie, rozumienie i analizę. Nic z tych rzeczy. Ma tylko czystą i prostą niewinność. I wszystko działa bardzo dobrze. Jest takie czyste. Po prostu mówi to, co wie, a to, co wie, jest najwyższe. Więc, to uwolnienie od uwarunkowań musi zostać wprowadzone w was. Ale nie powinniście tego również omawiać między sobą. Gdy zaczniecie to omawiać, widzicie, zacznie to przypominać teologiczną argumentację. Nie ma w tym teologii.

To jest bardzo proste. To najprostsza rzecz. Powinniście być niewinni. Ale niewinność została zatracona. Dlaczego? Bo wasza uwaga jest skierowana w różne strony. Zwracacie uwagę na inne rzeczy. Patrzycie na inne rzeczy. To takie proste. Dzisiaj myślałam, że mam kupić 3 sari o długości 9 jardów.

To proste sprawa. Bo były 3 panie, które noszą sari o długości 9 jardów, i musiałam im je dać. Po prostu pomyślałam: "W porządku". Przyszłam tutaj, zobaczyłam, jak pakowane są bardzo ładne sari. Zapytałam: "Skąd je macie?" Odpowiedziała: "Z tego sklepu". Powiedziałam: "W porządku. Więc idźcie i kupcie te 3 sari". Gotowe. Bez analizy.

Po prostu przyszło mi do głowy, że muszę kupić trzy sari. Gotowe. Odpowiedź jest tutaj. Tak więc, nawet atmosfera jest tak niewinna, cała sytuacja jest tak niewinna że rozwiązanie jest przedstawiane przez niewinność niewinności. Niewinność działa we wszystkim, widzicie, ponieważ każdy ma odrobinę niewinności w sobie, prawda? Więc możecie – to jak piąta kolumna, widzicie. Niewinność jest piątą kolumną w was. Więc jeśli któraś osoba jest niewinna, widzicie, to zadziała na waszą piątą kolumnę i wszystko będzie w porządku. Gdy dajecie innym bandhan, co się dzieje, to właściwie wiąże się wasza niewinność z tą osobą. A biedak nie wie.

On ma w sobie swoją niewinność, wy chwytacie tę niewinność, tak właśnie to działa. Tak to zarządzacie. To bardzo proste, aby wszystko działało. Cała zasada, tattva, wszystko opiera się na czym? Tattva to nic innego jak niewinność. Więc spróbujcie to rozwijać poprzez te wszystkie rzeczy, "Ya neti, neti wachane nigamor awachus". Mówiąc: "Nie to, nie to, nie to, nie to, nie to," do wszystkich waszych myśli. "Nie to, nie to, nie to, nie to". Docieracie tam. "Nie moje, nie moje, nie moje, nie moje".

Docieracie tam. I tak to jest. I widzicie, cały świat materialny teraz atakuje niewinność, ponieważ są przerażeni. Nie możecie atakować, niewinność nie może być zniszczona. Niewinność to coś, co przenika wszystko i nie może być zniszczona. Cokolwiek ludzie spróbują, nie może być zniszczona. Ale może być przykryta, może się wycofać, ale nie może być zniszczone. Będzie działać na swój sposób. Więc spróbujcie rozwijać tę niewinność, która jest podstawą tattvy Mahalakszmi, powinniśmy powiedzieć, że to jest istota tattvy Mahalakszmi. Zewnętrzną stroną jest waga, ciężar, godność, zachowanie – wszystko.

To jest to, co zewnętrzne. A to, co wewnętrzne, tattva, zasada, na której to opiera się, to niewinność. Jeśli tak jest, jeśli zrozumiecie tattvę Mahalakszmi w was, jak ma to działać, to nie jest kwestia intelektualna. Ponownie powiem, że nie chcę, abyście wtłaczali w to swój intelekt, aby to odkryć. Ale po prostu pozostawcie to tam, gdzie jesteście, a odpowiedzi przyjdą do was automatycznie. Nie wtłaczajcie w to swoich umysłów. Po prostu otrzymacie odpowiedzi na każde pytanie, tak po prostu. Ponieważ niewinność w każdym jest prostą odpowiedzią gdy wszystkie komplikacje znikają, niewinność pozostaje. I to właśnie jest miłość Boga, miłość Boga. Więc nie mylcie tego z miłością, z całą waszą bezsensowną miłością, pomysłami, jakie macie o ludziach i błędną identyfikacją.

To jest czysta miłość w was, czystość, niewinność, która jest miłością, i która jest samym życiem, powinniśmy powiedzieć. To jest część tego, to jest Pranaszakti Ale Pranaszakti nie jest Mahalakszmi. Tak więc, Mahalakszmi jest istotą i esencją wszystkiego. Ponieważ jeśli ma zachodzić stworzenie, również, jeśli istnieje pragnienie Boga, i jeśli nie ma tattvy Mahalakszmi, to jaki sens ma to pragnienie? Przypuśćmy, że nawet jeśli jest stworzenie, a nie macie tattwy Mahalakszmi, jak to zrealizujecie? Nie możecie tego zrealizować. Musicie mieć tattwę Mahalakszmi. Bo bez niej nic nie ma sensu. Zatem na zewnątrz to tattwa Mahalakszmi, ale wewnątrz, wewnątrz – można powiedzieć, że są 3 rdzenie. Pierwszy rdzeń to tattwa Mahalakszmi, zewnętrzny, na który patrzycie, widzicie wzrost, w porządku.

Następnie wewnątrz jest stworzenie, czyli wszystkie elementy, które się tworzą, i wszystko to. Ale wewnątrz tego jest pragnienie, a wewnątrz pragnienia znajduje się ta połówka (jajko), można powiedzieć, zasada Ganeszy. Tak więc tattwa Ganeszy ostatecznie wszystko przezwycięża i przenika wszystko. I to jest, powiedziałabym, nie myślcie o tym. Po prostu pozwólcie, aby wasza niewinność rosła, Prosta niewinność i wasza godność. To bardzo ważne, abyście mieli godność. Na przykład, niektórzy myślą, że jeśli noszą podarte ubrania, i chodzą po ulicy, i są wielkimi sanjasami. To jest złe. Dlaczego? Nie wykazujecie się godnością, a Bóg dał wam tak wiele, dlaczego mielibyście próbować pokazywać, że nie macie nic?

Tylko po to, aby pokazać, że nic nie macie, co Bóg wam dał. To jest po prostu rodzaj dziękczynienia Bogu, że: "Boże, dałeś mi tak wiele." Musicie nosić to, co najlepsze. Na przykład, podczas pudźy, jeśli widzicie, panie tutaj noszą wszystkie swoje kolczyki i wszystkie ozdoby i wszystko, w świątyni, gdy muszą iść, wszystko noszą. Podobnie mężczyźni noszą swoje bardzo czyste stroje, bardzo czyste rzeczy, cokolwiek mają. Noszą proste, czyste ubrania, cokolwiek mają. Ale bez ostentacji. To jest po prostu sposób, w jaki wyrażacie wdzięczność. Bóg dał wam to: "O Boże, dziękuję ci". To tak wspaniały dzień, aby być tutaj w Dniu Nowego Roku, w miejscu Mahalakszmi w Kolhapurze.

A to miejsce nazywa się również Kolhapur, ponieważ tutaj zabito Kolhasurę. Kolhasura był okropnym facetem jak lis i odrodził się. Teraz znowu nie żyje. Dzięki Bogu. Był tutaj, a teraz nie żyje. Kolhasura umarł. Nie myślcie o tym, znowu wasz umysł się rozprasza. Nie myślcie o tym, opowiem wam o tym. Celowo unikałam tej nazwy. Odrodził się i teraz został zakończony.

Więc to jest miejsce, gdzie zabito Kolhasurę, gdzie to zostało ustanowione, tak pojawiła się inkarnacja Mahalakszmi. I dlatego to miejsce ma szczególną wartość, że przyszliście tu na pielgrzymkę i pozwólcie, abyście w pokorze o tym pomyśleli. W rzeczywistości te rzeczy nie mogłyby się wydarzyć na Zachodzie, ponieważ nawet gdyby wyszły z Matki Ziemi, kto by je rozpoznał? Kto by o nich wiedział? Kto by je szanował? Kto by je czcił? Dlatego nie zdarzało się to na Zachodzie zbyt często. Ale tam jest, trochę tam jest, bez wątpienia. Ale teraz tutaj mamy te wszystkie świątynie a atak na niewinność pochodzi od tantryków. I tantrycy weszli do wszystkich tych świątyń, i próbowali się ustanowić.

Ale stopniowo są neutralizowani i oczyszczani. Ci tantrycy weszli do każdej świątyni wszystkich Bogiń. I stopniowo wszyscy znikną, zupełnie znikną. Tak więc, to jest atak, który się przedostał, i tak ci bramini, osiedlili się w tych miejscach – tak zwani bramini. I próbowali głosić wszystkie metody tantryczne i rzeczy tutaj, w świątyni, i naprawdę zepsuli tu atmosferę. Niech Bóg błogosławi was wszystkich. Chcę, abyście rozwijali koncentrację umysłu, abyście wznieśli się ponad wszelkie inne błędne identyfikacje i utożsamili się z Czystym Duchem, poprzez waszą zasadę Mahalakszmi. Niech Bóg was błogosławi.