8-my Dzień Navaratri (Ashtami) Ubóstwo, 29.09.1979, Shri Sunderbhai Hall, Bombaj, Indie

Shri Vijay Merchant, pan Rakure, wszyscy Sahaja yogini, którzy przybyli tutaj, aby wyrazić swoją miłość do Mnie i do wszystkich innych ludzi, którzy poszukują prawdy.

To było naprawdę bardzo uprzejme ze strony Shri Merchanta, że przyszedł i zainaugurował tę książkę. Od wczesnego dzieciństwa oglądałam jego grę w krykieta. Muszę przyznać, że jestem wielką fanką krykieta. Myślę, że krykiet jest grą, która jest naprawdę Sahaja, między jedną skrajnością piłki nożnej i kolejną nudną grą w golfa. I zawsze doceniałam to, w jaki sposób kierował naszymi zespołami i był takim dobrym kapitanem dla naszego kraju. I podziwiałam go za sposób, w jaki potrafił poradzić sobie ze sławą w dziedzinie krykieta. Nawet po tym, zamiast marnować swoje życie, jak wszyscy inni ludzie odnoszący sukcesy w życiu, na emeryturze wykonuje tak wspaniałą pracę, i ma takie uczucie dla wszystkich uciskanych i biednych ludzi z tego kraju, wskazuje na to, że jest bardzo wrażliwą osobowością.
Jestem mu bardzo wdzięczna, za jego dobroć dla nas wszystkich, że był tutaj i rozmawiał z nami o swojej pracy. Zgadzam się z nim całkowicie, że uciskanym lub tym, którzy nie są tak zamożni, jak my lub możemy powiedzieć, że ten, który nie jest dobrym pałkarzem, ten słabszy powinien być wspierany i podtrzymany przez mocniejszego. Dokładnie to robimy w Sahaja Yodze.

To, co robimy w Sahaja Yodze, to to, że docieramy do źródeł ubóstwa. Nie próbujemy tylko tworzyć mozaiki z właśnie poprawiających się warunków materialnych ludzi. Dlatego widzieliście na świecie ludzi, którzy byli bardzo zamożni, w krajach takich jak Szwajcaria i Szwecja, gdzie ludzie są bardzo zamożni i popełniają samobójstwo. Największa liczba samobójców pochodzi ze Szwecji. Informowałam was ostatnim razem, że mieliśmy kilka osób przybyłych ze Szwecji i ich wibracje przypominały martwe ciała.

Przede wszystkim musimy poznać korzenie naszych problemów. Nie zajdziemy daleko próbując jedynie leczyć objawy. I może się zdarzyć, że leczymy jeden objaw, ale możemy wyleczyć inny objaw.

Dam wam bardzo prosty przykład wrażliwości mojego męża wobec jego organizacji, którą jest Światowa Korporacja ds. Morskich.
On jest kolejnym dżentelmenem filantropem i chciał zrobić wiele dobrego dla kierowców, którzy byli w tej firmie. I on powiedział: "Ich wynagrodzenie jest bardzo małe, a kobiety i mężczyźni żyją naprawdę poniżej normy. Musimy coś dla nich zrobić". I zaczął podnosić im płace. Po trzech miesiącach nagle otrzymałam telefon od kobiety. Powiedziała: "Jesteśmy żonami kierowców i chcemy się z panią spotkać". Powiedziałam: "To dobry pomysł. Wszyscy musicie spotkać się ze Mną", ponieważ w Korporacji ds. Żeglugi zawsze miałam bardzo matczyny stosunek do wszystkich pracowników, a oni zawsze przychodzili i mówili Mi, jeśli uważali, że byłoby im trudno rozmawiać z Moim mężem. Teraz przyszli i powiedzieli Mi: "To miłe, że on dał nam sporą płacę, ale czy nasi kierowcy wiedzą, co robić z tymi dodatkowymi pieniędzmi?

Teraz zaczęli pić, poszli do złych kobiet, a nawet nie dają nam tych pieniędzy, które nam dawali.

Co jest podstawowym źródłem ubóstwa? To nie jest Bóg. To istoty ludzkie, istoty ludzkie, które mają za dużo ambicji, ludzie, którzy cały czas gonią za iluzją pieniędzy. Społeczeństwa Zachodu zorientowane na pieniądze, wykreowały taki rodzaj mentalności nawet na Wschodzie, ludzie chcą mieć wszystko na świecie. Dzisiaj chcą mieć dom, jutro samochód, pojutrze helikopter. Być może oni chcieliby mieć dla siebie nawet wielkiego jumbo jeta. Jak to ograniczyć?

Chyba że przyprowadzicie tych ludzi, którzy nagromadzili zbyt wiele pieniędzy i wyciągają pieniądze od biednych a z drugiej strony biednych, którzy nie czują się wystarczająco odpowiedzialni, aby kreować pracę dla samych siebie i nie pasożytować na nikim. Te dwa czynniki należy rozwiązać w tym samym czasie, a Sahaja Yoga jest jedyną drogą, żeby wygrać.

Teraz musieliście zauważyć, że w Sahaja Yodze są przeważnie ludzie [pochodzący] z klasy średniej. Są tam również ludzie bardzo biedni; mamy mnóstwo biednych ludzi z wiosek. W Sahaja Yodze, gdy Kundalini się unosi uzyskujecie swoją własną moc w sobie, poprzez którą czujecie się usatysfakcjonowani, a to zbyt wielkie pragnienie pieniędzy, pozycji i tego wszystkiego umiera i taka osoba sama myśli o innych, którzy są w pobliżu, ponieważ na swoich wibracjach, które ona może odczuwać, może czuć potrzeby innych.

Jak dotąd chorzy, którzy są biedni lub chorzy, którzy są bogaci, nawet choroby takie jak rak i trąd, mogą być wyleczeni tylko poprzez Sahaja Yogę. Leczymy ludzi nie biorąc za to ani grosza. Wyleczyliśmy tysiące ludzi na całym świecie nie biorąc ani grosza od nich, niezależnie czy są biedni, bogaci czy jacykolwiek. Jest wiele osób, które są psychicznie zaburzone. Na przykład większość pieniędzy biednych idzie na picie. Piją jak ryby. Marnują energię na picie.
Możecie myśleć, że mówię o zakazie, ale picie jest przeciwko ludzkiemu życiu. Teraz nie możecie prosić ludzi, aby przestali pić. To niemożliwe. Gdy powiecie komuś: "Przestań pić", on nie może przestać. Czasami mam wrażenie, że większość ubogich, tak zwanych biednych ma dużo pieniędzy do marnowania na picie.

Musimy również brać pod uwagę drugą stronę ubogich. Dając im więcej pieniędzy, czy naprawdę robimy ich odpowiedzialnymi, czy czynimy ich lepszymi ludźmi, czy sprawiamy, że stają się dobrymi obywatelami i czy czynimy ich jednością z Boską Mocą? Przypuśćmy, że biedny człowiek przychodzi do was i on jest pijakiem. Teraz nie możecie mu powiedzieć: "Nie pij". Jeśli mu powiecie: "Nie pij", mocno was zaatakuje. Jeśli jest ich dziesięciu, to jest bardziej niebezpieczne, a taki zakaz nigdy nie zadziałał.
Ale będziecie zdumieni wiedząc, że w dzielnicy Amart Nagar są tysiące ludzi, którzy właśnie przestali pić tak po prostu, poprzez otrzymanie tej ​​Realizacji.

Czym jest Realizacja? Jeśli zrozumiemy, natychmiast, będziecie wiedzieć, że powinniśmy ją dostać najpierw, a potem powinny nastąpić inne rzeczy. To poprzez Realizację poznajecie siebie. Poznajecie swoje własne moce, które są wewnątrz. Dowiadujecie się, czym jesteście i poznajecie Absolut. Jak powiedzieliście, prawdą jest, że bez uzyskania Samorealizacji, nie będziecie wiedzieli, co jest naprawdę dobre a co złe. Nie może istnieć żadna wartość bezwzględna, ponieważ jeszcze nie odkryliście swojego Absolutu. Wszystko jest względne.

Dlatego jest zamieszanie. Ale przypuśćmy, że odkryjecie, przypuśćmy, że [wam] powiem, zachowajcie to jako hipotezę, że odkryjecie swojego Ducha, Absolut. Jeśli to odkryjecie, to jakkolwiek względne są problemy, o których wiecie poprzez wibracje, przepływające przez was, możecie rozróżnić czy coś jest dobre czy złe. Jeśli jest złe, wibracje ustaną natychmiast.

Mówiłam, że raka nie można wyleczyć przez nic innego oprócz Sahaja Yogi i mamy tak wielu ludzi wyleczonych z raka.

Niedawno poszłam do Saskara i jak wiecie, było w okolicy wielu chorych. Jednym z nich był człowiek niewidomy od piątego roku życia, od około dwudziestu pięciu lat nie widział. Jego obie źrenice były odwrócone do góry nogami i on nic nie widział, mógł tylko widzieć białą siatkówkę. I on zaczął widzieć w ciągu dziesięciu minut. Jeśli chcecie napisać, możecie napisać do siostry prezydenta i zapytać sekretarza, Pana Madapa.

Wyleczyłam też naszego prezydenta, niewątpliwie, ale oprócz niego była mała dziewczynka, która była córką wartownika, który był muzułmańskim dżentelmenem. On zadzwonił i powiedział: "Ta dziewczynka w ogóle nie widzi, Matko, a ona jest mała ma siedem-osiem lat i straciła wzrok, bo wybuchł pożar". Ona również w ciągu pięciu czy dziesięciu minut zaczęła widzieć tak wyraźnie, że ujrzała garnitur mojego męża w białe prążki.

Sahaja Yoga to jedyny sposób, w jaki możecie rozwiązać kłopoty uciśnionych. Nie ma innego wyjścia, chyba że staliście się zrealizowani, ponieważ musieliście widzieć, jak reagują ci pracownicy socjalni. Zajmowałam się też pracą społeczną i widziałam ich reakcję, jak oni się zachowują. Ponieważ są niedoskonali. Dopóki ten instrument nie zostanie podłączony do sieci, to nie może działać poprawnie. To jest wciąż niedoskonały instrument. Musicie udoskonalić instrument. Wszystko jest gotowe. Ten instrument jest wewnątrz was; trzeba go tylko udoskonalić. Wszystkie wasze choroby można wyleczyć.

A co z ubóstwem? Ubóstwo, jak wiecie, jest zasadą Lakshmi. Rezyduje w waszym Nabhi. Zasada Lakshmi znajduje się w waszym Nabhi i jeśli wasza czakra Nabhi jest wyleczona, wasza zasada Lakshmi jest wyleczona. W naszym kraju z powodu czarnej magii, przez strasznych guru, z powodu wszelkiego rodzaju złych rzeczy, które myślimy o innych w związku z Nabhi, ze względu na post, bezsensowne poszczenie, z powodu chodzenia do świątyń i jedzenia złego prasadu... wszystkie te rzeczy spowodowały powiększenie czakry Nabhi. Teraz Sahaja yogini, którzy tutaj przybyli zdecydowanie zyskali materialnie. Wszyscy zyskali materialnie. Czy jest ktoś, kto może wstać i powiedzieć Mi: "Nie zyskaliśmy"?

Przybyli do nas bardzo biedni ludzie. Mieliśmy jednego dżentelmena, który przybył do nas z Kalwe. Powiedział Mi: "Matko, odkąd dołączyłem do Sahaja Yogi mam się świetnie. Byłam zaskoczona, ponieważ za każdym razem, gdy przybywał z Kalwe, przynosił Mi girlandę. Zapytałam: "Co się stało?" Odrzekł: "Nie wiem, ale przechodziłem po mojej ziemi każdego ranka i nagle pewnego dnia przyszedł do mnie dżentelmen i zapytał: ‘Czy możesz sprzedać mi tę glinę z twojego pola, po takiej i takiej cenie?’" Ponieważ to jest bardzo dobra glina, bardzo dobry materiał. I zaczął mi tak dużo płacić. "Być może nie zdaje pan sobie sprawy, że te wibracje są dynamiczne, są błogosławieństwem Boga, a kiedy już pan ich dotknie, zasada Lakshmi poprawia się właśnie tak."

Nie musicie się martwić o opiekę nad uciskanymi lub czymkolwiek. Każdy, czy jest bogaty czy biedny, kiedy przychodzi do Sahaja Yogi, zostaje połączony z całością.

Ta wrażliwość wszystkich ludzi, którzy wykonują pracę, dobrą pracę na rzecz pomocy biednym, staje się naprawdę oświecona. Tylko przez dotknięcie możecie wyleczyć ludzi. Tylko będąc gdzieś, możecie powstrzymać wypadki. Możecie kierować całym spektaklem, tylko myśląc o nim. Tak właśnie zagłębiając się w tą głębszą istotą, która jest całością, w Viraatę, dowiadujecie się, że jesteście częścią całości. Tylko musicie być podłączeni; siła sprawcza zaczyna płynąć.

Ale oczywiście w Sahaja Yodze nie możecie stać się bardzo bogaci, ani bardzo biedni, ponieważ w naturze nigdy nie ma nierównowagi. Niedawno powiedziałam wam, że człowiek rośnie do, pewnego wzrostu do pięciu, sześciu, siedmiu stóp i tyle, nie więcej. Nawet, powiedzmy, drzewo mango wyrasta do określonego punktu. Natura się o to troszczy.

Bóg się o was troszczy. On robi wszystko. Połączmy się tylko z Bogiem i On się o to zatroszczy. Zgadzam się, że praca filantropijna jest niezbędną częścią kraju takiego jak nasz. Ale musimy wiedzieć, że filantropia nie jest zadaniem Boga. Ludzie stworzyli ubóstwo. Ludzie stworzyli wszystkie te problemy. Dlatego powinni rozwiązywać własne problemy. To nie jest praca Boga.

Bożym dziełem jest błogosławienie was, obdarowanie was.

Kiedy idziecie do Niego, kiedy wchodzicie do Królestwa Bożego, On was błogosławi. Nie za dużo, nie za mało, ale [jest] satysfakcja i radość z posiadania tego. Właściwie nic nie posiadamy. Cokolwiek posiadamy, jest tylko mitem w naszych umysłach. Nawet w [umysłach] naszych biednych ludzi. Dawaliśmy im czasami bardzo złe pomysły, i oni utworzyli pewien rodzaj grupowego myślenia, że są bardzo biedni i mogą wywierać presję polityczną i temu podobne rzeczy. Musimy uważać chcąc zrobić coś dla biednych, żeby robić to od wewnątrz, a nie od zewnątrz. W rzeczywistości, to taki wspaniały kraj. Tutaj nie potrzebujecie wiele. Widzieliście Mnie, mogę spać na ulicy, mogę poruszać się dokądkolwiek chcę.

Nie ma potrzeby posiadania zbyt wiele. Właśnie dlatego Gandhiji zawsze mówił, że my powinniśmy nacisnąć na naszą sagara. Gandhi powiedział wszystkim gandhivad, ludziom Gandhiego, że powinniście mieć mniej. Ale zauważcie, że większość gandhivadich ma najwięcej czarnych pieniędzy, najwięcej diamentów i najwięcej pieniędzy. Mogą nosić zwykłe ubrania, ale Ja słyszałam, że nie robią tego.

To serce musi zostać zmienione. Dopóki nie zmienicie serca ludzi, kiedy oni naprawdę szczerze poczują tak jak wy czujecie, nie tylko to, ale po prostu poczują to jako konkretne uczucie w sobie. Na przykład, jeśli biedak stoi przede Mną, od razu czuję jego czakrę Nabhi. Mogę położyć Moją dłoń na czakrze Nabhi. Mogę rozwiązać jego problem, tak po prostu.

To jest fakt, wiecie to. Wszyscy Sahaja yogini, którzy są tutaj, większość z nich jest Sahaja yoginami powiedzą, że Mataji to zrobiła. Najbiedniejszy z najbiedniejszych może zostać dotknięty przez zasadę Lakshmi i może być wyleczony. Najważniejszą częścią jest to, że to jego zasada Lakshmi musi zostać wyleczona, a nie jego pieniądze lub materia. Więc musicie dowiedzieć się o różnicy między zasadą Lakshmi a materią. Zasada Lakshmi jest osobą.

On może być zwykłym kierowcą, ale on może być jak baccha [dziecko]. Widzicie, mieliśmy kierowcę przez wiele lat. Był jak baccha i wiedziałam, że był jak król, ponieważ był królem w poprzednim życiu. Był jak baccha, w ten sposób, że nic by mu nie przeszkadzało i wszystko by go satysfakcjonowało.

Jeśli powiecie mu, że musicie czekać trzy godziny, on będzie czekał. Jeśli powiecie mu, że teraz nie może tu zostać, może iść i spać gdziekolwiek, on też pójdzie. Cokolwiek mu powiecie, on się nie zawaha i był taką szczęśliwą osobowością. Powód jest taki, powiedziałabym, że on jest lepszy niż wielu bogatych ludzi, którzy nie mogą spać w nocy i którzy cały czas myślą o brudnych sztuczkach, które zamierzają próbować i wielu z tych polityków, którzy cały czas tylko planują wszystkie te brudne projekty.

Musimy oczyścić się od wewnątrz. Ubóstwo to tylko mit tego objawu. Teraz mówiąc, że ludzie są bardzo torturowani, wiem, że oni są, oczywiście, bardzo stłumieni. Ale jakie macie rozwiązanie? Jeśli rozwiązaniem jest danie im trochę pieniędzy lub po prostu zaaplikowanie im małą kurację, to nie pomoże. Musicie obudzić ich zasadę Lakshmi.

Zmierzam do istoty, do podstawy tego, skąd bierze się problem. Lakshmi stoi z jedną ręką w ten sposób, jedną ręką tak jak ta i ma dwa lotosy w swoich rękach i Ona jest kobietą w bardzo prostym sari, białym sari. Bądźcie pewni, że Lakshmi pati, osoba, która ma Lakshmi, satysfakcję Lakshmi, zawsze ma zwyczaj, aby dawać. Cały czas daje. Jeśli zasada Lakshmi tych wszystkich tak zwanych multi-milionerów się obudzi, oni będą się bali trzymać te wszystkie czarne pieniądze przy sobie i wyzyskiwać ubogich. Jeśli zasada Lakshmi ubogich zostanie oświecona, będą się wstydzić żebrania i bycia pasożytami. Nie ma sensu rozwijać w nich tendencji pasożytniczych. Pasożyta należy nienawidzić jak trądu. W tym kraju mamy dość tej żebraniny. Nasi liderzy również stali się największymi żebrakami na świecie.

Jeśli podróżujecie po całym świecie, czujecie się tak zawstydzeni. Nie ma znaczenia, czy połowa tego kraju jest przeklęta, ponieważ mogą narodzić się ponownie. Ale żyjcie z szacunkiem dla samego siebie. Ten rodzaj żebractwa, który ma miejsce i takie żebranie, które ​​robimy z innymi krajami jest dla nas bardzo haniebne, ponieważ Bóg dał nam takie błogosławieństwo yogi bhoomi. Cóż za chaos, który zrobiliśmy, przez niezrozumienie naszych własnych wartości, naszej własnej kultury i naszego własnego dziedzictwa, które mamy od Boga. To jedyny kraj na całym świecie, który jest zorientowany na yogę. Czy rozumiecie znaczenie tego kraju? Nie tylko jest to zorientowanie na yogę, ale również jest to punya bhoomi. Tutaj przybyli i żyli wszyscy wielcy święci. Nawet Zaratustra, którego czcili Parsyci jest inkarnacją Datattreyi i wy wiecie, jak czcimy go w naszej Sahaja Yodze, jak czcimy Mohameta w naszej Sahaja Yodze, jak rozumiemy, gdzie on się znajduje w nas.

Głębsza współzależność wszystkich tych problemów całego świata może być rozwiązana przez was, Hindusów. Macie to błogosławieństwo, że jesteście Hindusami w tym kraju i nie czujcie się tak źle, jeśli nie macie jednego helikoptera lub jednego tranzystora. Ubóstwo jest z umysłu, mogę wam powiedzieć. To nie jest więcej jedzenia czy nie-jedzenia. Jeśli dana osoba ma umysł, który jest odrażający, może być multi-milionerem, ale wciąż będzie płakać: "Nie mam tego. Nie mam tamtego". Nic nie może zadowolić ludzi i wiecie, że prawo ekonomii jest takie, że "żadne pragnienie generalnie nie może być zaspokojone". Zwłaszcza, gdy wszystko jest spełnione, ale nikt nie jest zadowolony. Dzięki Sahaja Yodze możecie dać im satysfakcję i szacunek do samych siebie. Rozwijajcie ich szacunek do samych siebie.
Nauczcie ich, jak się wznieść, nie zajmujcie się nimi jak po prostu uciskanymi.

Miałam tutaj bardzo dobrą okazję pracy w szkole dla niewidomych. A ludzie niewidomi w szkole chcieli zbierać pieniądze i to, i tamto, i wszystko to. Powiedziałam: "Nic z tego. Nie powinniście robić z nich żebraczek". Wszyscy mogą wypracować coś dla siebie. Zaczęli wypracowywać. Potem zrobili ładne rzeczy i narzuty na łóżka i to i tamto. Więc powiedzieli: "Kto to teraz sprzeda?" Powiedziałam: "Idźcie wszyscy, by zrobić dla nich marketing".

Ale potem powiedziałam im, że byłam zaskoczona, iż w Japonii nauczono niewidomych masażu. Powiedziałam: "Dajecie im Realizację i pozwólcie im robić masaż". Jeśli zrealizowana niewidoma osoba robiłaby masaż, wszyscy ci cudzoziemcy płaciliby im przynajmniej sto rupii za masaż, minimum. A jeśli ta osoba jest niewidoma, to jest o wiele łatwiej zrobić masaż. Ale ludzie nie mogli zaakceptować tego rodzaju rzeczy. Powiedzieli: "Nie, nie, Mataji, nie powinnaś dawać im Realizacji”. Tutaj brakuje nam zrozumienia głębi naszego problemu. Oni powiedzieli: "Mataji, jak możesz dać Realizację tym niewidomym?" A niewidomi by to dostali w jednej chwili. Tylko, że oni mogliby zostać wyleczeni i dostaliby tę Realizację.

Ale ponieważ ta organizacja należy do innych wielkich ludzi o wielkich umysłach i mądrości, oni nie zaakceptowaliby takiej sytuacji, w której powiedziałabym: "W porządku, przyprowadźcie wszystkich niewidomych a ja postaram się przywrócić im wzrok". Nie chcą tego zaakceptować.

Podam wam bardzo prosty przykład, że wyleczyłam białaczkę u małego dziesięcioletniego chłopca, który był pacjentem z rakiem krwi, w Delhi. Oczywiście nigdy nie pobieramy żadnej opłaty. Żaden Sahaja yogin nie bierze ani grosza zapłaty za to co robi, wiecie o tym. Ani grosza. I ten chłopiec został wyleczony. Został przywieziony przez doktora Mulhera i doktor Mulher wspomniał o Mnie w instytucie medycznym. Instytut medyczny zgłosił się do Mnie i tylko zobaczcie, jaka była ich propozycja: "Pani da nam listę ludzi, których wyleczyła, w jaki sposób wyleczyła, gdzie oni mieszkają i wszystko inne". Zapytałam: "Po co?" Nie proszę o żadne pieniądze. Niczego tu nie sprzedajemy. Wyglądacie, jakbyście brali [Mnie] w krzyżowy ogień pytań, tak jakbym była tutaj, by wziąć jakąkolwiek darowiznę od was. Po prostu przyjdźcie i przekonajcie się sami. Nie zapisuję imion ludzi, którym podawałam jedzenie lub ile kęsów oni zjedli. To jest moja miłość, która płynie. To działa moja miłość. Wy ludzie nie możecie zrozumieć miłości. Chcecie, żebym zapisała wszystkie osoby, które wyleczyłam. Odmawiam robienia tego.

W ten sposób oni na coś patrzą. Oni nie znają mocy miłości. Dla nas teraz konieczne jest wygenerowanie mocy miłości poprzez Sahaja Yogę. To bardzo łatwe. Sahaja Yoga nie jest błogosławieństwem jednego roku czy jednej yugi, ale wszystkich yug. Musicie to uzyskać. Musicie poznać swoją Atmę. Musicie znać swoją Jaźń a Sąd Ostateczny teraz ma tutaj miejsce. Nie trzeba myśleć o innym nadchodzącym Sądzie Ostatecznym. Tutaj, teraz, dzięki poznaniu swojej Atmy, otrzymacie moc Boga przepływającą przez was, kiedy podłączam to do sieci, moc zaczyna przez nas przepływać.

A potem ta moc może przekazać tę siłę sprawczą. Czym jest to ubóstwo? Jest u Stóp tego Pana. Możecie po prostu to odrzucić. Zgadzam się, że w chodzeniu do świątyń i kościołów nie ma Boga. Jednakże nawet pójście do biednego nie pomoże, tyle mogę wam dzisiaj powiedzieć, lecz sięgnięcie do korzeni ubóstwa, poprzez zrozumienie, dlaczego ubóstwo istnieje i dlaczego ludzie zachowują się w taki sposób. Musicie przekształcić całość. Nadal jesteście w stanie kwiatu. Wszyscy musicie stać się owocami. Wszyscy musimy dziś stać się owocami.

Jeśli nie jesteśmy owocami, nie możemy rozwiązać problemu naszego kraju i innego kraju. Jeśli tak się dzieje albo ta ogromna transformacja ma miejsce dzisiaj w naszym kraju, wtedy cały świat będzie prowadzony przez nas, i tak czy inaczej będzie prowadzony, czego jestem pewna, na sto procent pewna, że nadchodzi czas, kiedy cały świat będzie musiał nas wysłuchać w tej sprawie, aby rozwiązać swoje problemy. Są kraje, są tam komunistyczne kraje; ludzie mają wszystko. Byłam we wszystkich krajach. Byłam w Rosji. Ci, którzy mówią o komunizmie, powinni udać się do Rosji i przekonać się sami. Ci, którzy mówią o kapitalizmie, powinni udać się do Ameryki i przekonać się, jak głupimi, niemądrymi i bezużytecznymi ludźmi oni byli, jak ich społeczeństwo jest skończone. Pieniądze nie mogą przynieść wam szczęścia. Jeśli chcecie uszczęśliwić ludzi, przebudźcie ich czakrę Nabhi, jak ją nazywają, albo można ją nazwać zasadą Lakshmi. I ta zasada Lakshmi może zostać przebudzona, wyłącznie przebudzona przez Sahaja Yogę, poprzez którą cały kraj zostanie przekształcony.

Tak jak idziecie do nieurodzajnego ogrodu i widzicie ogród w absolutnie jałowym stanie. Nagle pojawia się woda i moc wody generuje całą tę zamożność i nagle całe miejsce tryska radością, i właśnie to wydarzy się w naszym kraju, o którym ludzie myślą, że jest biedny. Chcę jeszcze powiedzieć, że możemy być biedni na zewnątrz, ponieważ może nie mamy bardzo dobrych ubrań, według nich, i my nie używamy zbyt wiele tworzyw sztucznych. Co jest ich zamożnością? To nic innego jak tworzywa sztuczne i gumy. Jedzą plastik i śpią na gumach. Nie mają nawet tak wiele naturalnej bawełny.

Nasz dostatek to nasza yoga, która jest naszą mocą, naszym pożywieniem, naszym człowieczeństwem a nasze człowieczeństwo musi być podtrzymane. Musimy mieć o wiele więcej ludzi takich jak pan Vijay Merchant, który myśli o całości, o wszystkich ludziach, którzy cierpią, ale filantropia Sahaja Yogi jest inna, bo dla Mnie, kto jest tym drugim? Kiedy ktoś jest po prostu nieodłączną częścią Mojej Istoty, sam mój palec boli, tylko go pocieram i muszę to robić.
W tym celu nie muszę przebudzać ludzi, po prostu to dostają. Tylko stojąc blisko jakiejś osoby, dostajecie bólu głowy i pytacie ją: "Czy boli cię głowa?" "Tak". Masujecie swoją głowę i masujecie jego głowę, i po prostu ból ustaje.

Po prostu nie możecie nic na to poradzić, ponieważ makrokosmos, Viraat, informuje was, gdy jesteście jednością z nim to widzicie, że ten drugi człowiek cierpi. Stajecie się tym. Stajecie się kolektywnie świadomi. To nie jest wykład, ani nic takiego, ale to staje się wewnątrz was, i zaczynacie odczuwać na palcach, na koniuszkach palców, jakie centra są zablokowane, na czym polega problem, drugiej osoby, jak ją wyleczyć, co z tym zrobić.

Wszystko, cała ta wiedza jest podana w Sahaja Yodze, całkowicie za darmo. Spośród tak wielu, którzy tu siedzą, możecie zapytać, ile osób cierpiało na choroby, zostało całkowicie wyleczonych, i od kiedy są zrealizowani nie wydali ani grosza na lekarzy. Nie musicie troszczyć się o swoje zdrowie, nie potrzeba wiele w tej sprawie robić. Mieliśmy ludzi, którzy mieli trzy ataki serca, a teraz są mocni. Mieliśmy ludzi, którzy mieli białaczkę i wszystkie rodzaje chorób. Dzisiaj nie uwierzycie, że kiedykolwiek mieli te choroby, ponieważ teraz wewnątrz są całkowicie zrównoważeni, zintegrowani i błogosławieni przez Boską moc w was. To jest nasze dziedzictwo. Musimy na tym zyskać. I przez to tylko, my zlikwidujemy ubóstwo, pewnego dnia przekonacie się, a nie przez łatanie kilku rzeczy.

Poprosiłabym pana Vijaya Merchanta i mamy też z nami kolejnego świetnego pracownika socjalnego, Gidubai Kotaka, abyście poświęcili nieco więcej uwagi naszej Sahaja Yodze i zobaczyli dynamikę Sahaja Yogi. Zdziwicie się, że jedna osoba, ta osoba, która teraz do was mówi, była z Rahuri, te dwie osoby. Dali Realizację dziesięciu tysiącom ludzi.

Pójdźcie tylko i zobaczcie ich domy i ich dzieci. Tryskają radością, szczęściem, i nie widzicie w ich sercach żadnego ubóstwa w ogóle. Ich serca zostały wzbogacone i mają się tak dobrze. Ponieważ energia jest w was, zasada Saraswati jest również oświecona i zaczynacie myśleć, co należy zrobić i jak uczynić wasze życie szczęśliwym. Ale pieniądze to nie wszystko; jedzenie to nie wszystko. Dopóki nie poznacie swojej Atmy nigdy nie będziecie szczęśliwi. Więc idźcie do korzeni, a to jest takie proste. Nie musicie nic płacić. Nie musicie mieć wielu organizacji, ani nic. To po prostu działa, właśnie tak. Więc po co się martwić i po co myśleć tylko o czymś okropnym?

A teraz jeszcze więcej, porozmawiajcie z Gidubai o tym, jak oni byli oczarowani przez jednego guru, który pokazywał cuda. I spotkałam kogoś z Morvi, kto przyszedł, aby się ze Mną spotkać, a Ja powiedziałam mu, żeby nie miał nic wspólnego z tym okropnym facetem, ponieważ nadejdzie dzień, gdy Kalki będzie działać i nastąpi zniszczenie. On nie chciał Mnie słuchać. Pojechałam do Andhry. Dla waszej informacji powiem, że pojechałam do Andhry. Powiedziałam ludziom z Andhry, żeby nie uprawiali tego tytoniu. W Andhrze są dwa rodzaje ludzi: jedni, którzy zarabiają dużo pieniędzy; drudzy, tak zwani biedni, którzy dużo zajmują się czarną magią. Rozmawiałam z oboma. Powiedziałam im: "Nie róbcie czarnej magii, ponieważ jeśli robicie czarną magię, zasada Lakshmi zniknie.

Jeśli czarna magia przychodzi z tej strony, Lakshmi wychodzi drugą stroną. A oni po prostu Mnie nie słuchali. Rozmawiałam z tymi ludźmi, którzy uprawiają tytoń. Nie chcieli słuchać. Na trzech taśmach jest wykład, gdzie powiedziałam, że morze jest inkarnacją Datattreyi. Potrzebny jest wypoczynek, uwierzcie Mi. I tak się z tym stało. Musimy zrozumieć, że Bóg zna nas wszystkich. Zna szerokie rzesze z nas, i On wie dokąd zmierzamy i co robimy. Wasz Bombaj uniknął ostatnio bardzo dużej suszy.

Ale proszę uważajcie i zwróćcie się ku Bogu. To nie jest kwestia udania się w Himalaje, oczywiście, i nie ma mowy o ucieczce od tego. Ale weźcie to do siebie, spróbujcie tylu ilu możecie przyprowadzić tutaj, jeśli święci tam istnieją. Ci, którzy są Sahaja yoginami, są świętymi. Wtedy Bóg na pewno was pobłogosławi, zdecydowanie was pobłogosławi. I ci sami ludzie, którzy dzisiaj są zrealizowani, wykonali ogromną pracę na wsiach. Wyzwolili tak wiele wiosek, bez żadnych pieniędzy, bez niczego. Kiedy wchodzę do wiosek, jestem naprawdę zaskoczona jak ludzie zostają wyleczeni, w jaki sposób otrzymują pomoc, jak oni stają się energiczni, jak rozumieją temat. To jest najbardziej niesamowite.

Tak więc moc wszystkich mocy, to jest moc Bożej Miłości, weźmy się za to. Wykorzystajmy Go i zostawmy wszystko w rękach Boga. Doprowadźcie Go tylko do każdego, o kim myślicie, że cierpi. Zbierzecie Mi stu ludzi, którzy cierpią, a Ja spotkam się z nimi. Dzisiaj, gdyby cała sala była wypełniona, wyleczyłabym ich wszystkich. Wiecie, że to robiłam. To nie jest trudne. To nie są przechwałki. To jest fakt. To działa w pięć minut, tak wielu ludzi może to uzyskać. Ale ludzie nie chcą zmierzyć się z rzeczywistością i nie chcą się tym zająć.

Teraz mamy tak wielu Sahaja yoginów w Bombaju. Więc możecie sobie wyobrazić, że pracuję tu od dziewięciu lat. Mamy oczywiście więcej w odległych centrach, ale tutaj, w tym centrum, mamy tak wielu, czy nawet więcej. Więc możecie zobaczyć, jacy są ludzie. A praca, którą wykonujecie z zewnątrz, jest całkiem jakby niewidoma osoba wykonywała tę pracę, tę pracę, tę pracę, tę pracę. Politycy także myślą, że wykonują wspaniałą pracę. W porządku, wykonują. Pracownicy społeczni również wykonują świetną robotę. Wszyscy wykonują. Ale nie ma koordynacji, nie ma integracji i nie ma satysfakcji z tego, co się robi.

Powodem jest to, że wszyscy oni należą do całości a jeszcze nie są połączeni z całością, co trzeba zrobić. Odkrywamy całą naszą zdrowotność, na całym świecie, czy jesteśmy Hindusami czy Amerykanami lub kimkolwiek. Wszyscy próbujemy po prostu dowiedzieć się, co jest dobre dla zdrowia, a odpowiedzią jest Sahaja Yoga. To jest Sahaja Yoga. Nie ma innej odpowiedzi na każdy z tych problemów. Dzisiaj Ja wam mówię, potem ponownie wy możecie Mi powiedzieć. Przekażecie Mi swoje problemy. Powiecie Mi, kto jest uciskany. Niech to zobaczę. Pozwólcie Mi zobaczyć, kto jest uciskany.

Teraz wy, ktoś chciał, żebym poszła i zobaczyła rybaka. Powiedziałam: "Dobrze, pójdę go zobaczyć". Jestem pewna, że jeśli oni dostaną Realizację, ich połowy poprawią się, na pewno, na sto procent; jestem tego pewna. Wszystko się poprawia dzięki Bożym błogosławieństwom i Bóg ma sześć jakości, co czyni Go Bhagwan. Jednym z nich jest Shubha, pomyślność. Innym jest Kalyan [dobrobyt]. Kolejnym jest Ishwari [Wszechmocna Bogini]. Podobnie jak sześć cech Boga. Te sześć cech emitowane jest z istoty, i jak tylko się z tym zmierzycie, otrzymacie to. Chcecie osiągnąć Kalyana, w porządku, zatem stawcie czoło ludziom przed Bogiem, i to jest sposób, w jaki możecie się z tym zmierzyć. Nie musicie organizować kościołów i świątyń lub czegokolwiek.

To tylko energia, która musi płynąć, Shakti [Moc], która musi płynąć. Jak widzicie, leżące tam drewno nie ma niczego. Ale jeśli oświecicie je, to da wam światło, ogień, wszystko. W ten sam sposób oświecenie jest jedyną drogą, aby rozwiązać problem i wszyscy powinniśmy starać się oświecić tak wiele osób, jak tylko jest to możliwe. Nasza praca, oczywiście, jest bardziej dla klasy średniej, ponieważ ekstrema nas nie przyjmują. Ale kiedy środkowy bieg przybiera, to rzeka płynie po obu stronach. Może odżywiać obie strony. Stopniowo obie strony mogą również się przyłączyć, ale głębia jest w centrum, w madhya marga, i tam ona działa. Tylko klasa średnia może to wypracować, ponieważ mają oni niezbędne wartości, oni mają niezbędne uczucia i niezbędne błogosławieństwa, ponieważ oni wiodą bardzo normalne życie. Gdy już nauczą się pływać, muszą poznać samych siebie, zanim pomogą innym.

Musicie pomóc sami sobie. Musicie stać się sobą, zanim pomożecie innym. Gdy to osiągną, mogą łatwo pomóc, łatwo pomóc innym i to zostało zrobione. Jest to tak cicha praca Sahaja Yogi, że nie gromadzimy żadnych statystyk. Nie byliśmy jeszcze w stanie powiedzieć. Oto ludzie, którzy dali Realizację co najmniej dziesięciu tysiącom lub ośmiu tysiącom ludzi. Są ludzie, którzy wyleczyli tysiące osób, a którzy siedzą tutaj jak zwyczajni ludzie, ale o tym nie wiedzą i powiedzą: "Nie zrobiliśmy tego, Matko. Po prostu to zadziałało. To się po prostu wydarzyło". Wydarzyło się.

Więc to jest bardzo dynamiczna siła. Poprosiłabym wszystkich pracowników socjalnych, aby otworzyli oczy na to niezwykłe odkrycie, które przyszło do naszego kraju i zobaczyli dla samych siebie, jak to jest, co to znaczy. To przekształca osobowość w tak dynamiczną sieć, że zwykły chłopiec może stać się wielkim graczem krykieta. Zwykły muzyk może zostać świetnym muzykiem. Zwyczajny tępy chłopiec może stać się pierwszym uczniem w klasie. To się wydarzyło. Jest wielu, którzy powiedzą, że to się wydarzyło w ich przypadku. Tak wiele takich rzeczy się wydarzyło, więc musimy polegać na łasce Boga w tym. Musimy jedynie pragnąć tego i prosić o to.

Pewnego dnia rozmawiałam z jednym z przywódców politycznych. Powiedziałam: "Polityka bez adhyatmy [duchowości] jest bez życia". W ten sam sposób powiem: "Praca społeczna bez adhyatmy nie ma znaczenia". Bez adhyatmy, bez Atmy bez Ducha Boga w niej, robicie to, ponieważ w was coś umiera, w was coś czuje, że to, co jest uczuciem w was, jest częścią całości. Więc poznajcie całość i będziecie tacy dynamiczni. Będziecie tacy wspaniali i wszystko będzie płynąć od was i naprawdę możecie pomóc tysiącom ludzi.

Mam nadzieję, że dobrze jest, iż mamy dzisiaj tutaj dwóch wspaniałych pracowników socjalnych i Ja kieruję do nich tego rodzaju propozycję. Tak więc w imieniu wszystkich Sahaja yoginów oferujemy wszystkie nasze usługi. Każdą ilość uciskanych ludzi, których macie wyślijcie do naszych ośrodków my się nimi zajmiemy.

Niech Bóg was wszystkich błogosławi.