Shri Saraswati Puja. Vancouver (Kanada), 11 Sierpnia 1990. (wersja 2 – styczeń 2018, do korekt)

Kiedy zapytano Mnie, jaką powinniśmy mieć Puję w Vancouver, Ja słyszałam o tym ashramie, który jest położony w bardzo pięknym otoczeniu. A ponieważ natura jest stworzona przez moce Saraswati, pomyślałam, że najlepiej byłoby mieć tutaj Puję Saraswati. Co innego, kiedy ludzie żyją blisko natury, stają się bardzo twórczy, ich delikatne uczucia są zachowane. Oni nigdy się nie śpieszą, nigdy także nie są, jak to można nazwać, za bardzo nowocześni, ponieważ przyroda ich wycisza. 

Zatem twórczość Saraswati potęguje twórczość artysty, i wiedziałam, że w tym kraju musiało powstać wielu artystów od dawna. Kanada jako taka, czuję, że to jest Hamsa Czakra Vishuddhi, ale ta moc Saraswati staje się Mahasaraswati, kiedy jest wyrażona przez Mahabrahmadevę, nazywaną także Hiranya Garbhą. W tym celu Ona musi przejść przez Hamsę. Ona przechodzi przez Hamsę i staje się Shakti Vishnumayi. Mam na myśli, że ona jest Shakti Vishnumayi, siłą Vishnumayi. A więc Saraswati staje się Vishnumayą. Ona przechodzi przez dwa punkty: jeden - to jest Hamsa, a drugi - Vishuddhi. 

A więc ona jest siostrą Shri Krishny. Zatem Saraswati urodziła się jako siostra Shri Krishny i kiedy wujek Krishny, kiedy wujek Kamsa [brat mamy] przyszedł, żeby ją [Vishnumayę] zabić, ona wzniosła się do nieba i stała się błyskawicą. I zapowiedziała przyjście Shri Krishny - że On już tam jest, że już istnieje. A więc relacja pomiędzy Shri Krishną i Vshnumayą jest to relacja pomiędzy bratem i siostrą. I tak się złożyło, że dawniej obchodziliśmy Rakhi Bandhan, Raksha Bandhan, co jest tym samym, co relacja pomiędzy bratem i siostrą. Więc tu i teraz właśnie czcimy Bóstwo, które jest siostrą Shri Krishny. Później ona urodziła się jako Draupadi [w Mahabharacie żona pięciu braci Pandawów]. I dlatego Shri Krishna poszedł ocalić jej cześć, bo tylko brat troszczy się o cześć i dobre imię siostry. Wczoraj właśnie się to stało. Ponieważ jest to Puja Saraswati, a więc Vishnumaya osobiście wczoraj zagrzmiała 16 razy. 

Ja nic nikomu nie mówiłam, ale wiedziałam, że ona to zrobi i niezależnie od tego, ona także pogroziła Waszyngtonowi. I to jest bardzo dobra sprawa, ponieważ Waszyngton musi się przebudzić. Teraz to są bardzo, bardzo subtelne rzeczy i bardzo subtelne relacje. Tylko Ja mogę wam o tym powiedzieć, ponieważ wiem, że takie relacje istnieją. Więc Ja nie byłam zaskoczona, że ona tam była, i dokładnie 16 tysięcy razy zagrzmiała w tej części Vancouver, żeby pokazać, że nadszedł czas, abyście zrozumieli, że Sahaja Yoga jest bardzo ważna. I jeśli my nie utwierdzimy się całkowicie w Sahaja Yodze, Vishnumaya przyjmie inną formę, która może spalić wam wszystkie lasy, może spalić wszystko. 

Musicie wiedzieć, że błyskawica zawiera w sobie wszystkie 5 elementów: ma dźwięk, ma światło, jest i działa w eterze. Ma także w sobie to, co wy nazywacie wodą, a kiedy woda przechodzi w tarcie, co jest Matką Ziemią, wszystkie te rzeczy działają przez nią. A więc ta Vishnumaya wczoraj pokazała nam, że "Ja tu teraz jestem, proszę, czcijcie Mnie". Jak dotąd, nigdy nie czciliśmy Saraswati. 

A Brahmadeva nie jest nigdzie czczony, ponieważ On to wszystko stworzył; On stworzył te wszystkie lasy i wszystkie te rzeczy, wszystkie te oceany, wszystkie te lądy i wszystkie gwiazdy, wszechświaty po wszechświatach. Ale my nie powinniśmy czcić takich rzeczy jak to czy tamto drzewo. Nie czcimy niczego takiego, a tylko takie rzeczy, które są stworzone przez Matkę Ziemię, jak Swayambu. Tylko takie czcimy teraz w sposób, który jest abstrakcyjny, ponieważ gdziekolwiek one się pojawiły [wyszły z ziemi], ludzie praktykują komercjalną religię, a więc my nie chodzimy w te miejsca jako Sahaja yogini. Zatem możecie zrozumieć, dlaczego te rzeczy się zdarzają. Także wczoraj, po Moim przybyciu, niespodziewanie pojawił się taki deszcz błyskawic, jakiego tu nigdy przedtem nie było, i ludzie byli bardzo zdziwieni. Więc to jest siostra Krishny, która jest o wiele bardziej dynamiczna, z dużo bardziej ognistym temperamentem - dużo, dużo bardziej ognista osobowość. 

Esencją Shri Krishny jest słodycz, "Maduria" jest jego zdolnością a Radha jest "Allada Dayini Shakti"- czyli ta, która daje wam taką radość, od której, włosy stają wam dęba. W sanskrycie to słowo brzmi: "pulakrit". pulakita jest tym słowem. 
Więc to piękno Shri Krishny, które jest słodyczą, "leelą", stwarzanie tych pięknych uczuć jedności, komunikacji, to wszystko jest w Shri Krishnie. 

Ale Ona jest tą, która ostrzega i tak właśnie przyszło to ostrzeżenie. Ona jest bardzo ognistą osobowością, która ostrzega każdego. W ten jeden sposób Ona udowodniła Moje przybycie tutaj, że tutaj jestem. Może dla ludzi, którzy są tutaj aborygenami to będzie zrozumiałe, że to było przepowiedziane i to się zdarzyło. Wy ludzie, także musicie zrozumieć, że to jest ostrzeżenie, że nie możecie pozwolić Sahaja Yodze dryfować w ten sposób, że przyjmuje swój własny kurs i sama wszystko wypracowuje, a wy - tak przy okazji. A więc to jest ostrzeżenie od siostry Shri Krishny, Vishnumayi, którą jest Saraswati we własnej osobie, i dlatego dzisiaj będziemy Ją czcić. 

Tylko Sahaja yogini, którzy są oświeconymi ludźmi, mogą czcić Mahasaraswati. W innym wypadku ludzie mogą czcić tylko Saraswati, ponieważ czcząc Saraswati możecie czytać książki, a także tworzyć tańce i muzykę, aby zabawić ludzi. Ale właściwie puja do Saraswati jest przeznaczona dla ludzi o takiej zwyczajnej świadomości, tej takiej zwykłej, prostej ludzkiej świadomości. Ale dla Sahaja yoginów Mahasaraswati jest tą, która powinna być czczona. 

Tak jak wam powiedziałam, ta Mahasaraswati staje się Vishnumayą, Ona jest Vishnumayą, więc wy powinniście tak jak Vishnumaya, informować ludzi, czym jest Sahaja Yoga, poprzez żarliwe przemowy, poprzez ekscytowanie ich, mówiąc im: "Co wy robicie?" Ale tu Ja widzę, że przeważnie, kiedy ludzie mówią, oni starają się być bardzo delikatni i słodcy, jak Shri Krishna. My próbowaliśmy tego w Ameryce, że może to podziała na Amerykanów, ale nie podziałało. Oni lubią ludzi takich jak, powiedzmy, ten gość Graham albo ludzi takich jak on, którzy mówią w sposób żarliwy, musimy się nauczyć z wczorajszego doświadczenia, że potrzebujecie naprawdę bardzo żarliwych mówców i bardzo żarliwych ludzi, ponieważ oni nie są w ogóle wrażliwi na normalne doznania. Widzicie, wszystkie ich doznania już obumarły. Oni stali się odrętwiali. I musicie dostarczyć im jakichś wstrząsów. Oni lubią szoki, widzicie. Gazety muszą sprawiać im szoki. Każde wydarzenie, które jest szokujące - tylko to może przyciągnąć ich uwagę. 

Nawet muzyka musi być taka, żeby rozbijała skały. To musi być taka muzyka, która po prostu rozłupuje im głowy. Oni po prostu stali się takimi kamiennymi ludźmi i musicie zrozumieć, że ta ich skamieniałość może być rozbita tylko przez Vishnumayę. I dlatego właśnie ta puja dzisiaj, w Vancouver ma wielkie znaczenie nie tylko dla Kanady, ale także dla Ameryki. Amerykanie traktują z lekkością współczesne choroby, narkotyki, które biorą. Zniszczenie, które na siebie ściągają, ciągle nie dociera do ich świadomości. Oni nie rozumieją, co sobie robią, jak niszczą sami siebie. Jak to cenne ludzkie życie niszczą tylko dla swojego kaprysu i dla swojej tak zwanej wolności. A więc jest to bardzo, bardzo ważne, abyście powiedzieli im w bardzo żarliwy sposób: "Co wy robicie? Dlaczego oszukujecie siebie? Dlaczego nie chcecie zrozumieć, że to jest złe?" Przynajmniej dla potomków powiedzcie im: "My zrobiliśmy te złe rzeczy, ale przynajmniej wy tego nie róbcie". Wszystkie tego rodzaju [płomienne] mowy muszą istnieć i ludzie muszą się przygotować na tego typu mowy i sprawy. 

Ale żeby mówić, że ludziom to się nie będzie podobało, myślę, że to jest zupełnie odwrotnie. Dopóty, dopóki ich nie przestraszycie, oni nie będą z wami. Więc musicie ich ostrzec i właśnie to Vishnumaya zasugerowała wczoraj. Przyjmijcie nowy styl strategiczny i mówcie do ludzi w ten sposób, mówcie, że powiedzmy, robicie kurs a pod koniec kursu musicie im powiedzieć: "Teraz zobaczcie, że Sahaja Yoga nie jest tylko po to, żeby zaliczać kurs, ale jest także dla waszej pomyślności i dla waszej korzyści. I musicie z tym dalej pójść i musicie rosnąć. Nie porzućcie tego w pół drogi". Nie wystarczy, żeby ziarno tylko wykiełkowało, ale musi stać się drzewem, w przeciwnym razie, nikomu nie można pomóc. 

Więc powiedzcie im tylko o wszystkich niebezpieczeństwach, które płyną z tego, że się nie jest w pełni dojrzałym w Sahaja Yodze. To musi być powiedziane, ponieważ ten sposób bycia a la "dzieci - kwiaty" nie pomaga w Ameryce, widziałam to. Potrzeba wam naprawdę żarliwych ludzi, ponieważ niedawno słuchałam przemówienia tego Billa Grahama i powiedziałam: "To taki gość z pustą głową, ale mimo wszystko ludzie byli pod wrażeniem". I jest też taki drugi, który teraz jest chyba w więzieniu, nie wiem jak ma na imię, taki śmieszny człowiek. Też go zobaczyłam i byłam bardzo zdziwiona. Mówił coś bardzo pustego, tak jak pusta muszla, ale ludzie całkiem zwariowali na jego punkcie. Tysiące ludzi tam stały i śpiewały, i robiły to czy tamto. No więc trzeba nam zrozumieć, że ci ludzie potrzebują wstrząsów i oni muszą być szokowani, i trzeba im powiedzieć, że coś się stanie. Jest jeszcze jedna taka organizacja, która używa takiego szokującego systemu. Nazywa się Brahma Kumari. 

Więc ci ludzie z Brahma Kumari stali się jak błyskawice i mówią ludziom - teraz tego nie mówią: "Będziesz zniszczony", ale mówią: "Ten świat zostanie zniszczony, wszystko zostanie zniszczone i wiecie, wy nie jesteście na to przygotowani, co to będzie?" To samo robią Świadkowie Jehowy. Oni mówią: "Ten świat zostanie zniszczony, my wszyscy zostaniemy zniszczeni, a więc powinniśmy być przygotowani i powinniśmy zwrócić się ku Bogu". Ale to nie jest rzeczywistość. Mimo to ludzie ich popierają. Musicie powiedzieć im o rzeczywistości, że "nie tylko niszczycie samych siebie, ale niszczycie także przyszłość". Ludzie już mówią, że większość ludzi w Ameryce zostanie zniszczona. To się bierze z różnych powodów. Możemy powiedzieć, że nie ma tutaj tradycji, ale to nie jest powód, to nie jest główny powód. Jednym z głównych powodów jest to, że oni zniszczyli tak wielu ludzi, kiedy przyjechali i osiedlili się w tym kraju. 

To jedna kwestia. Teraz buce tych ludzi, którzy zostali zniszczeni ciągle jeszcze tutaj wiszą wokoło. I one chcą zobaczyć, jak one zniszczą Amerykanów, na ile to możliwe. Takiej ilości czarów i negatywnych technik działających w Ameryce - nie ma nigdzie. Wszyscy guru musieli uciekać ze wszystkich innych krajów, ale ciągle jeszcze są miło usadowieni w Ameryce. 
A powodem tego jest to, że te buce podsuwają im różne pomysły. Nie tylko dlatego, że oni [Amerykanie] potrzebują wstrząsów, ale te buce dają im także różne perwersyjne pomysły na samodestrukcję. Więc pomysły tych buców są takie, że powiedzmy, widzimy kogoś jak wychodzi z pubu i pada. A zamiarem tego buca jest: "Co w tym złego? Ty też spróbuj, ty nigdy się nie przewrócisz. Wejdź, nic ci się nie stanie. Ty jesteś w porządku, a i tak wszystko jedno". Albo powiedzmy, powie się im, że "to jest złe, nie powinniśmy tego robić". "No dobrze, więc jesteśmy źli. Co z tego?" To są wszystko pomysły buców, to nie są ludzkie pomysły, aby rozmawiać czy mówić w ten sposób. 

A więc dla tych wszystkich ludzi jedyną rzeczą jaka ich ocali jest moc Vishnumayi, nic innego. 
Ja teraz zrozumiałam, że tylko przez Vishnumayę ludzie mogą być uleczeni. A więc Vishnumaya we własnej osobie poszła teraz spać, z powodu religii chrześcijańskiej, katolickiej, ale też przez hinduizm - ponieważ także w hinduizmie jest ta idea grzechu, że zgrzeszyłeś tym, popełniłeś taki grzech. Zatem dajcie jakąś kwotę Braminowi, to będziecie zbawieni. 

Myślę, że w każdej religii jest taka niedorzeczność. Ale ta moc Vishnumayi, która jest całkowicie stłumiona i jest uśpiona w ludziach. Jeżeli możecie, to ją podnieście i powiedzcie ludziom, żeby obudzili się z tego snu, z tego lenistwa poprzez zaangażowanie ich w coś wielkiego, poprzez powiedzenie im, że "my działamy dla pokoju, dla pokoju światowego. My jesteśmy tutaj dla wyzwolenia ludzkości, my chcemy ocalić ludzi od błądzenia i destrukcji". Jeżeli wyjdziecie na szerszą platformę i opowiecie o tych rzeczach, to wtedy to w jakiś sposób pomoże. Np. to była bardzo dobra rzecz, że Ja byłam z Mahatmą Gandhim, a ludzie mają wielki szacunek dla Mahatmy Gandhiego. Oczywiście Mahatma Gandhi był pod dużym wrażeniem mojej osoby, bez wątpienia. Nawet kiedy byłam dzieckiem, on się ze mną konsultował. A dowodem tego jest, że on ułożył serię bajanów w inny sposób niż zwykle, zaczynając od serca, mówiąc o Atmie, czyli o Duchu, a potem zaczyna od Mooladhary w górę w ten sposób. 

To jest właśnie jeden z dowodów, że on musiał się ze Mną konsultować. Ale cokolwiek by to nie było, także możecie tego użyć i powiedzieć, że Shri Mataji robi tę samą pracę, jaką Mahatma Gandhi zalecał robić. On mówił o "sarva dharma dharma savanatma", co znaczy, że wszystkie religie powinny być traktowane z tym samym szacunkiem i zrozumieniem. Kiedy zaczniecie tak mówić, to ludzie zrozumieją, że to ma jakieś szlachetne pochodzenie, ponieważ każdy chce wiedzieć, z jakiej książki Ja się uczyłam. Nigdy przecież nie uczyłam się z żadnej książki, wiecie o tym bardzo dobrze. Ale możecie powiedzieć, że "Ona jest tą, która z nim była i zrobiła na nim duże wrażenie". I te same idee pokoju i niestosowania przemocy i to wszystko, "są tymi samymi technikami i metodami, których Ona chce używać". Jest to fakt, bez wątpienia, ale Mahatma Gandhi był bardzo żarliwym mówcą. Wszyscy jego stronnicy byli bardzo żarliwi. Oni nie byli tacy: "No dobrze, przyjdź i napij się herbaty", takie działanie nie przyniesie rezultatu. 

Zatem Amerykanie potrzebują wyzwania. Oni potrzebują naprawdę żarliwej osoby, żeby na nich nakrzyczała. No więc, jeżeli w ten sposób to zrobicie, tak jak pewnego dnia, kiedy mieliśmy program w Nowym Yorku i było wielu ludzi czarnych i chińczyków, a potem było też wielu z Indii, ale białych było niewielu. Więc biali przyszli i powiedzieli: "Jak to, mnie nic się nie zdarzyło na tym programie. Więc dlaczego mnie się nic nie zdarzyło?" "Tak, to co". "Musi być z tobą coś nie tak, na pewno popełniłeś jakieś grzechy czy coś". Wtedy oni będą zaszokowani. "Och, to jest coś zaskakującego. Nic nie czuliście? To bardzo źle, coś z wami niedobrze. Powinniście to poczuć. Spróbujcie to poczuć, coś z wami nie w porządku. Mamy nadzieję, że nie macie raka". 
Albo możecie spytać: "Macie AIDS?" "Nie, nie, nie". "Na co więc cierpicie? Jak to jest, że nic nie czuliście? Spójrzcie, ten czarny coś poczuł i ten Chińczyk coś poczuł. Czemu wy nic nie czujecie? Wy jesteście biali i powinniście poczuć to pierwsi". I wtedy rzeczy zaczną się wypracowywać.
Zastanawiałam się nad tym, czemu ci Amerykanie są tacy tępi? Ponieważ tak naprawdę, oni są bardzo tępi, skrajnie tępi. Bo ten rodzaj muzyki rockowej, jeśli komuś innemu zagrać, ludzie uciekliby. "Co to za muzyka?" Ale jak im się ta muzyka rockowa wczoraj podobała. Chcieli, abym słuchała, Serce zaczęło mi walić w całkiem inny sposób. Zapytałam: "Co się dzieje?" Wszystko zaczęło się trząść. Ja siedziałam na ławce, a cała ławka się trzęsła. Ktoś inny za Mną siedział, on tam był i także Karan tam był. W pewnym momencie zauważyliśmy, że wszyscy podskakiwali w ten sposób. To było tak jak trzęsienie ziemi. To jest to, co widzicie, ci ludzie są bardzo, bardzo tępi i odrętwiali, są odrętwiali, z powodu tej tak zwanej wolności. To coś takiego, jakby poprosić byka "przyjdź i uderz mnie". Oni wychodzą ze siebie, żeby całkowicie zatracić czucie; a to znieczulenie może pochodzić od alkoholu, od narkotyków, od kobiet, może od żenienia się tyle razy. Jeśli się ożenisz raz, to wystarczy. Jeśli ożenisz się 5 razy, stajesz się taki jak - no, nie wiem, czy jest takie zwierzę, do którego można to porównać. Ale stajesz się odrętwiały, niewrażliwy na różne rzeczy. 

Bo, po pierwsze, mając jedną żonę, masz do niej jakieś przywiązanie, masz z nią dzieci, tyle jest do zrobienia ze swoją żoną, i nagle się rozwodzisz i niczego nie czujesz, nie czujesz tego. Jest to wielkie odrętwienie i jeżeli takim coś powiesz, oni mówią: "Tak, ja wiem, ja wiem, ja wiem". 
Oni wiedzą, ale oni nic nie czują. Oni nie czują, że coś robią źle. Oni nie czują, że zrobili coś absurdalnego i wcale nie cierpią z tego powodu. Jakaś inna osoba by cierpiała. On rozwiódł się ze swoją żoną i stałby się osobą całkiem zagubioną, normalnie tak powinno być. Ale co my tutaj znajdujemy? Czym on się tak chełpi? - "Wiesz, rozwiodłem się z dwiema żonami, a tu trzecia na widoku, możesz się z nią spotkać, jeśli chcesz". 

Nie mają żadnego wstydu, żadnego wstydu ani żadnych uczuć - niczego. Ożeniłeś się z kobietą, żyłeś z nią, była twoją żoną i nie masz dla niej żadnych uczuć? I twoje własne dzieci nie mają w ogóle żadnych uczuć. Oczywiście, oni nie są tacy jak Anglicy, gdzie Anglicy nawet zabijają swoje dzieci, więc nie jest tak źle. Ale też słyszałam tutaj, że mąż i żona zabijają się nawzajem. I po co? - Z miłości. Jeżeli nie potrafią kochać jednego męża, w jaki sposób będą kochały innego męża, ja nie rozumiem. Miłość jest to właściwość serca. Jeśli spojrzycie na tę całą osobowość, to ta osobowość jest po prostu znieczulona. Bo oni nie zachowują się jak istoty ludzkie. Oni zachowują się - no, jak nie wiem kto, bo nie ma to porównania z niczym. 

Nie tylko w Ameryce ludzie są tacy. To jest wszędzie, ale w Ameryce jest to naprawdę przesada i wszystkie tego typu rzeczy wychodzą z Ameryki. Wszystkie tego typu dziwne poglądy wyrastają w Ameryce i wszyscy je przyjmują, ponieważ oni [Amerykanie] wiedzą, jak robić reklamę i jak spopularyzować te rzeczy. Kiedyś podróżowałam statkiem i pilot z tego statku podszedł do Mnie i powiedział, że jego brat jest strasznym diabłem. Ja zapytałam: "Co się stało?" On Mi powiedział, że złapał tych czterech chłopaków, tych Beatlesów i został ich menadżerem. On zapoczątkował tę muzykę, i przyprowadził jakieś kobiety, upił je, dał im narkotyki. A kiedy oni grali tę muzykę, te dziewczyny zaczęły drzeć się, krzyczeć i wariować, i to stało się bardzo popularne. 
Normalnie reakcja byłaby taka, że jeżeli tam grają jakąś muzykę i dziewczyny wariują, to oczywiście nikt by tam nie poszedł. Ale tutaj odwrotnie, wszyscy zaczęli się schodzić. Jak można wyjaśnić tego typu reakcję? Im bardziej krzyczą i wrzeszczą, to według nich coś w tym jest. Co znaczy, kryje się za tym jedna rzecz, która je wewnętrznie jakoś dotknęła, w przeciwnym wypadku dlaczego by krzyczały? To znaczy, że tacy znieczuleni ludzie nareszcie zostali czymś poruszeni, czymś wielkim i wszyscy powinniśmy tam pójść. Jesteśmy też głusi, więc powinniśmy w tym uczestniczyć. 

A teraz moglibyście zapytać: "Matko, jak doszło do tego otępienia ludzi?" Jak wam mówiłam, oni zażywali wolności w tak dużym stopniu, poświęcając swoją uwagę na marnotrawne zajęcia, aż stali się bardzo odrętwiali. Ich uwaga nic już nie czuje. 
Uwaga, jeśli ją skierujecie na zewnątrz, ona reaguje, i wraca do was jako informacja. Ale jeśli cały czas bombardujecie tę uwagę z zewnątrz, to trochę bombardowania z zewnątrz, po prostu niszczy waszą wrażliwość. Nie ma wtedy uczuć, nie ma przywiązania, nie ma wtedy żadnego rejestrowania tego, co się wydarzyło. 

No więc myślę, że po to potrzebna jest Vishnumaya. Dlatego Ona znajduje się po lewej stronie, ponieważ Vishnumaya bierze pod opiekę ludzi, którzy stali się całkowicie pozbawieni uczuć. Dlatego Ona tam jest, żeby dać wam uczucia. Zatem na lewej stronie, kiedy Ona błyska, Ona daje wam uczucia i ludzie zaczynają rozumieć. I w tym momencie wszystko, co im zostało, to jest ta mentalna idea - że są winni i tyle. To jest tylko mentalne, jeżeli to jest mentalna idea "och, jestem taki winny", to nie będziesz tego czuł. Mam na myśli, że jeżeli powiecie, że jesteście szaleni, chociaż nie jesteście, jeśli ktokolwiek nazwie was szaleńcem - to nie będziecie tego czuli. 

Tak to jest. Zatem oni tego w ogóle nie czują, ponieważ to jest zaakceptowane na poziomie mentalnym i oni stali się odrętwiali. To jest takie podejście: "Teraz nikt nie może mnie skrzywdzić, no i co mi zrobicie?" Chciałabym was ludzie prosić, abyście poszli "cała naprzód" i stali się bardzo żarliwi, piszcie w gazetach i mówcie co się dzieje i o co chodzi. Ja piszę teraz książkę pt. "Metamodern Era" i na tyle, na ile będę mogła być żarliwa, to będę, żeby im powiedzieć, co jest z nimi nie tak. I powinni to zobaczyć, co jest z nimi źle. Nie ma sensu próbować nazywać to czymś wielkim. 

Jak np. mamy teraz AIDS i myślałam, że przez AIDS się obudzą. Zatem teraz AIDS stało się sposobem męczeństwa. Teraz pojawili się "yuppies". Powiedziałam im: "Yuppie będą chorować". Oni na to: "Nie, nie, nie, nie. Bardzo przyjemnie jest być yuppies". Przede wszystkim, jak widać oni są następnymi bohaterami, którzy umrą na swój "yuppizm". Widzicie, każda głupota jest przerobiona na coś, co ma w sobie gloryfikację i ludzie to akceptują. To jest w tym najlepsze, że oni to akceptują. Zatem jest dla was ważne, żebyście byli żarliwi i pokazali im w świetle tego, czym oni są. Oni muszą być ujawnieni. 

To małe światełko Ducha już im nic nie powie, ale trzeba tego wielkiego, oślepiającego światła błyskawicy. Więc dzisiejsza puja będzie specjalnie po to, abyście wy wszyscy wyrobili w sobie tę kreatywność mówienia, zachowując się pod każdym względem w płomienny sposób. To ich wszystkich naprawi. Nic więcej. Również w pracy twórczej, kiedy coś tworzymy albo coś śpiewamy, i wszystko to, jeśli robimy to śpiewając w stylu hinduskim, część utworów jest "vilambit tala", bardzo powolnych "talas", to nie zadziała. Oni wolą kogoś takiego jak Ravi Shankar, który tylko miesza nuty i gra coś, co jest bardzo, bardzo nienaukowe wobec tradycyjnej muzyki hinduskiej, wcale nie jest rozrywkowe. To nie otworzy wam serca ani nic takiego. Ale to do nich przemawia, idące jakby w kierunku rock and rolla i nawet wręcz przerobić sitar, na rock and rolla lub nawet coś gorszego niż to. Nie znam ostatnich nowości, Nie wiem, co to jest. 

Drugą rzeczą jest zobaczyć, jak oni próbują ludzi zaszokować. Oni Również próbują ludzi zaszokować, ponieważ oni wiedzą, że oni są również tacy jak my. Jeśli np. pójdziecie na rynek i zobaczycie, że czyjeś spodnie - nawet nie całe spodnie, ale pół spodni - są podarte w dziwnych miejscach, to jest tylko po to, żeby zaszokować ludzi. Oni mają przynajmniej tutaj, oczekuje się od nich, w Ameryce oczekuje się, że mają ubierać się przyzwoicie. Nie powinniście być ubrani nieprzyzwoicie. To, czego chcą. Ale jeżeli dostaną jakąkolwiek szansę, żeby ubrać się w sposób, który będzie szokował, zrobią to. Np. oni będą mieli tylko jedną część włosów białą. Wszystko jest możliwe, żeby tylko zaszokować innych, zaszokować innych i przyciągnąć ich uwagę. 
Jaka jest dla nas korzyść? Żadna. Wydajecie tyle pieniędzy, żeby przyciągnąć uwagę innych, ale co z tego macie? Ta przyciągnięta uwaga nic wam nie daje ani nikt wam nie płaci, nie rekompensuje. Więc to jest taka pozbawiona radości pogoń... Wszystkie te rzeczy psują ich uwagę, co niszczy ją do tego stopnia, że stają się ludźmi bez uczuć. Są pozbawieni uczuć. 

A najgorsze co się stało jest to, że całkowicie rządzi nimi pieniądz. Pieniądze są kolejną stroną Saraswati. Saraswati różni się od Lakshmi. A więc Lakshmi i Saraswati nigdy nie idą ręka w rękę, i z tego właśnie powodu, jeśli oni zabiegają o łaskę Lakshmi i za bardzo gonią za pieniędzmi, to doznają szoku. Ponieważ nagle notowania na giełdach spadły albo przychodzi recesja, albo biznes plajtuje, i nagle człowiek, który był bardzo bogaty, staje się biedny. To wszystko jest dziełem Saraswati. 
A jeśli ktoś za bardzo interesuje się Saraswati, czyta za dużo książek, jest artystą, który jest bardzo ambitny i stara się zaćmić innych artystów itd. Taka osoba również dostaje "nagrodę" od Lakshmi, np. jego rzeczy w ogóle się nie sprzedają, nigdy nie otrzymuje pieniędzy, głoduje, wszelkie takie rzeczy. 

A więc te dwie rzeczy są w równowadze tylko w Hamsie albo możemy powiedzieć, że są one w równowadze, kiedy jesteś Sahaja yoginem. Więc trzeba to osiągnąć i zrównoważyć, aby mieć błogosławieństwa zarówno Saraswati jak też Lakshmi. Ale one się krzyżują tylko w punkcie Hamsy i w punkcie Vishudhi. A więc to co mamy zrobić, aby osiągnąć tę równowagę to to, że w jakikolwiek sposób zarabiamy, cokolwiek robimy - nie powinniśmy tego robić w sposób przeciętny. Powinniśmy starać się to robić w sposób dynamiczny i żarliwy. 
Te dwie rzeczy powinny być połączone na poziomie Vishuddhi. 

Powiedzmy, że masz wygłosić wykład na temat Sahaja Yogi w płomienny sposób, ale nosisz ubranie jak hippis albo jak ktoś, kto wyszedł z więzienia, nikt nie będzie traktował cię poważnie. Ale jeśli jesteś odpowiednio ubrany, i twój wygląd wzbudza szacunek, i masz dobrą prezencję i do tego wygłosisz żarliwą mowę, wszyscy będą słuchać. 

Zatem zasada Lakshmi musi być stosowana z dominacją zasady Saraswati. Następnym błogosławieństwem Saraswati jest, że możecie mieć wiedzę o Sahaja Yodze. Widziałam wiele kobiet, szczególnie w Sahaja Yodze, one są w Sahaja Yodze, ich wibracje i wszystko tam jest, ale nie wiedzą, co to jest Sahaja Yoga. One nie wiedzą, co to są czakry. One nie wiedzą, jak pojawiają się te wibracje. Powiedziałabym, że dzisiejszy wykład jest dość skomplikowany, jeśli się przyjrzycie. Musicie go wysłuchać przynajmniej 4-5 razy, żeby go zrozumieć, z papierem i ołówkiem w ręku. To nie jest taka prosta sprawa, bo teraz, jeśli wam mówię, to może być całkiem rozrywkowe, ale za rozrywką kryje się głęboka wiedza. Ja jakoś nie widzę Sahaja yoginek, żeby usiadły z kartką i ołówkiem, aby poznać co Matka mówi. Jaką wiedzę Ona nam daje o tych różnych rzeczach. Dla nich Sahaja Yoga oznacza bycie miłym, ugotowanie dobrego jedzenia, pomoc innym Sahaja yoginom, i oczywiście noszenie ładnego sari i ładnych ubrań, przychodzenie na puję, to wszystko i tyle. 

Więc dla nich jest bardzo ważne, żeby również wiedziały, czym jest Sahaja Yoga. One muszą słuchać moich wykładów, usiąść, dobrze je przestudiować i zrozumieć. A mężczyźni są inni. Dla nich [ważne] jest to, aby wykonać całą pracę na zewnątrz, obejdą naokoło, żeby przyjrzeć się wszystkiemu. Ale tam, gdzie wchodzą w grę relacje międzyludzkie czy uczucia, zaniedbują tę sferę. Dlatego Sahaja Yoga praktykowana przez mężczyzn jest inna, niż praktykowana przez kobiety. 

A szczególnie we Francji, jedni od drugich bardzo daleko odeszli. Kobiety są na jednej stronie, a mężczyźni - na drugiej. Wyobraźcie sobie, w Sahaja Yodze taka niedorzeczność. Ale w końcu odkryliśmy człowieka, który to wszystko powodował i poradziliśmy sobie z tym, i teraz sprawy stoją o wiele lepiej. Ale kobiety muszą znać Sahaja Yogę, co nie znaczy, że mają z nimi [mężczyznami] walczyć i myśleć, że one też wiedzą to, co wiedzą ci mężczyźni. Ale to jest bardzo powszechne. Widziałam to, że kobiety i mężczyźni mają inne podejście do Sahaja Yogi. Pierwszy jest ekstrawertyczny, drugi jest introwertyczny. Ale w Sahaja Yodze nie ma żadnej różnicy pomiędzy kobietą i mężczyzną, jeśli chodzi o wiedzę o Sahaja Yodze. Ja sama jestem kobietą i wiem tak wiele, dlaczego więc kobiety nie mają wiedzieć, czym jest Sahaja Yoga? 

Zatem wszystkie kobiety, które są tutaj i wszędzie, muszą wiedzieć o Sahaja Yodze. Przede wszystkim spójrzcie na Vishnumayę, Ona jest kobietą, jest tą Siłą, która działa. Brahmadeya nie pracuje, On stworzył te wszystkie rzeczy, ponieważ jego Siłą jest Saraswati. Bez niej On nic nie mógłby stworzyć. Więc wszystko jest stworzone poprzez Siłę, a tą Siłą jest kobieta, ale jeśli ta Siła nie wie, czym jest Sahaja Yoga, jak Ona to wypracuje? 

Zatem kobiety, chociaż mają dzieci, wiem, że muszą zajmować się domem, kuchnią, ale to jest taka przyjemność, taka radość, żeby czytać o Sahaja Yodze, żeby ją zrozumieć i żeby ją znać. Oczywiście, niektóre z nich czytają. Ja nie mówię, żeby tego nie robiły. Ale jest ich bardzo niewiele, one są bardzo rozsądne, bardzo rozsądne. A więc w moim rozumieniu dzisiejszych zdarzeń, kiedy jesteśmy w tym naturalnym otoczeniu, to naturalne otoczenie, gdzie jesteśmy pobłogosławieni poprzez pracę Brahmadevy i Saraswati, gdzie możemy poczuć możliwości tych Bóstw, do jakiego stopnia One mogą tworzyć. 

Przyroda jest absolutną jednością z Boskością. Teraz widzicie, jak tylko tu przybyłam, przyroda już wiedziała, że tu jestem. Po prostu zaczęła działać sama z siebie. Nie musiałam robić jej wykładu, nie musieli robić pujy, nic takiego. Oni wiedzieli, co ja robiłam. Kiedy pojechałam do Los Angeles stało się to samo. Gdziekolwiek pojadę, przyroda wie, co trzeba zrobić: "Teraz Matka jest w mieście, co powinniśmy zrobić?" I oni to robią. Ale to jest kłopot, że zmusiłam was do robienia wszelkiego rodzaju rozważań dla ludzi "w porządku, zrób to, zrób tamto, zrób to" itd. Powiedziałabym, że to powinno działać spontanicznie, bo teraz jesteśmy jednością, Tak jak przyroda jest jednością ze Mną, wy także jesteście jednością ze Mną. 

I to powinno się zdarzać, że staniecie się rzeczywiście wciągnięci w Sahaja Yogę, całkowicie jej oddani, tylko wtedy to zaistnieje. 

Niech was wszystkich Bóg błogosławi. 
