5 abril 1991
Talk to Sahaja Yogis
Brisbane (Australia)Charla a los sahaja yoguis. Brisbane, Australia. 4 de abril de 1991.

Yogui: “Siento mucho que solamente un medio de comunicación de Brisbane estuviese interesado”.

Shri Mataji: “¿Esperabais muchos?

Yogui: “Sí, pero no confirmados. Envié una invitación ayer a todas las televisiones, radios y periódicos y todos ellos me dijeron la misma historia, que quizá, que dependía de cómo fuese el día”.

Shri Mataji: “Todos estos periódicos están muy ocupados con las cosas, así llamadas, importantes. Para salir en los periódicos tienes que ser un político, es el único modo. Si no es así, no estarán interesados en vosotros.

Yogui: “Y ni siquiera te escuchan, porque de alguna manera les dije que Shri Mataji estaba en política. Les hablé acerca de Sir CP y de lo que él era, pero, a pesar de introducirlo de este modo, no lo aceptaron. Creo que si ven algo que tiene que ver con Dios o con el Espíritu se asustan. O quizá piensan que no existe, no lo sé. No sé qué podemos hacer, Madre.

Shri Mataji: “Creo que lo estamos extendiendo del mejor modo posible. Las personas que tienen que venir a Sahaja Yoga, vendrán, en cualquier caso. Pero los que no son de este tipo, nunca podrán venir. Así pues, no sé hasta qué punto nos hará tener éxito, tener demasiada publicidad y todo esto. Hay algunas personas a las que quizá nunca podremos dar la Realización. Pero, intentadlo. Ahora, en Francia, el gobierno francés ha tomado una buena actitud. Están enviando a algunos niños a un curso relámpago, para que aprendan la cultura india en siete días. Simplemente como el francés.

Yogui: “Lo siento Shri Mataji, deberíamos haber puesto el micrófono, hay gente fuera que no puede oír”.

Shri Mataji: “¿No pueden? ¡Lo siento! Creo que este curso relámpago ha empezado ya. Nadie quería hacerlo. Decían que era una tontería. Yo pensé que era algo bueno, porque sus niños podrían ser capaces de entender algunas cosas. Quizá puedan aprender algo bueno con ello. Imaginad, comenzar un curso de este tipo en Francia. Parece que algo está llegando a sus cabezas. Creo que estamos creciendo del mejor modo posible, porque los sahaja yoguis también deben convertirse en verdaderos yoguis, de otro modo la gente os verá y sacarán ciertas conclusiones. Además, hemos tenido algunos líderes horribles en Australia y en Inglaterra, y ahora también tenemos a alguien en Austria. Su principal debilidad era el dinero. Solo Dios sabe cómo pudieron caer en esta debilidad. Sus esposas también son responsables de esto.

Así pues, tuvieron una influencia de retraso, nos influyeron retrasando a Sahaja Yoga, y verdaderamente perdimos a muchos de ellos. Muchos estaban frustrados y preocupados por esta razón. Recientemente tuvimos a un caballero llamado Marcus que se aprovechó de los sahaja yoguis. Construyó su casa pidiendo dinero prestado a los sahaja yoguis, y después ha decidido abandonar Sahaja Yoga y vender la casa. Ahora los sahaja yoguis están preocupados, porque le dieron dinero, trabajaron para él, y ahora él lo está usando para ganar dinero con esta casa.

Así pues, mi única sugerencia fue que me deberían haber dicho que le estaban prestando dinero. Después de todo, esto es algo importante. Ellos pensaron: “¿Cómo podía él hacer algo así?” Yo les dije: “De cualquier modo, tengo que advertiros de que, si se os pide cualquier dinero extra, lo mejor es que me informéis a Mí”. También les voy a decir a todos los líderes que deben informarme si recogen cualquier dinero extra para cualquier cosa. En un grupo como el nuestro vivimos con confianza, sabemos que somos mejor gente que los demás, y que no tenemos todas esas cualidades horribles de lujuria y avaricia que ellos tienen. Al menos nosotros hemos intentado superarlas.

Es importante entender estos dos puntos. La gente es muy vulnerable. Si descubrís algo así debéis informarme. Respecto a mis viajes, normalmente yo solía viajar con mi propio dinero. Después poco a poco me dijeron: “¡No está bien, Madre! ¿Por qué deberías pagar Tú por nuestra salvación?” Para mis programas también hay que alquilar las salas. Ahora tenéis algunos músicos que han venido para ayudaros. Ellos os ayudan mucho, no hay duda. De modo que en todos los países tienen que recaudar algún dinero para nuestros programas. Pero me han dicho que hay muy pocas personas que contribuyen con esto. No se trata de que debéis pagar por vuestra Realización ni porque habéis sido beneficiados física, mental o emocionalmente, no es por nada de esto, sino porque esta es vuestra responsabilidad. Esta debe ser vuestra vida. Debéis involucraros en esto. Esto no es solamente para que os caséis en Sahaja Yoga y tengáis una buena vida familiar o para que consigáis un buen ashram en el que vivir cómodamente. Intentad comprender lo importante que es hoy día, salvar a la gente de ser ahogada completamente. Quiero decir que estaba muy sorprendida de que -a pesar de pedir una cantidad tan pequeña, aun así- la gente no quería pagar. Después de todo, ¿quién va a pagar por esto?

Como sabéis, en América la situación es muy, muy mala. Ahora tenemos una estadística que dice que el sesenta y cinco por ciento de la población de raza blanca sufrirá de enfermedades incurables y de esquizofrenia. Únicamente se librarán de ello personas procedentes de Asia y de otras culturas. Incluso entre la gente de raza negra no sé cuántos podrán sobrevivir, porque están intentando copiarles totalmente y caer en la misma trampa. Además de estas enfermedades, en todas partes la gente está tomando drogas y estas drogas también pueden produciros algunas enfermedades o desórdenes mentales. ¿Qué sucederá entonces?

Debemos pensar en el futuro de nuestros hijos. ¿Qué tipo de mundo vamos a dejarles? Por supuesto, en Sahaja Yoga no tenéis que pagar por vuestra Realización ni por ninguna otra cosa. Pero si observáis a cualquier gurú, por ejemplo, esta gurú Mai que ha venido, empieza cobrando trescientas libras. En Italia ha acabado cobrando tres mil libras. Hicieron una reclamación contra de ella. Ella dijo: “Yo soy una artista, no podéis cobrarme ningún impuesto”. Como ha ganado mucho dinero puede anunciarse mejor. Cobrando tanto dinero incluso puede producir su propio periódico en cualquier lugar. Cobra mucho y tiene a muchas personas ricas siguiéndola. Y lleva una vida tan inmoral, que si la vieseis os sorprenderíais. Tenemos un informe completo de su gurú. Si lo leéis os sorprenderéis de lo inmoral y estafador que es. Vedlo por vosotros mismos, os sorprenderá. Y la gente le ha dado miles y miles a esta mujer. Los funcionarios de hacienda de India me dijeron que tiene seiscientos croares, que significa, no sé...”

Yogui: “Un croare son 10 millones, Madre. Seis billones, seis billones americanos, se puede decir”

Shri Mataji: “Seis billones tan solo en diamantes, aparte del resto del dinero. Deben ser realmente estúpidos para darle el dinero, por eso están como están. Esto significa que a Sahaja Yoga solamente viene la gente sabia, sin duda. Pero la sabiduría también debería daros sentido de la responsabilidad, es muy importante. Como sabéis, a Mi edad estoy viajando, cada tres días tengo que viajar. Si fuese solamente a Australia estaría bien, pero viajo por todo el mundo. Yo gozo de ello, porque pienso que estoy haciendo mi trabajo. Por esta razón estoy en esta tierra. No me pagan nada por ello, pero a pesar de todo lo siento así. Pero, como sabéis muy bien, Yo no necesito Sahaja Yoga. Sahaja Yoga no es para Mí. Yo no lo necesito en absoluto. Vosotros si lo necesitáis, lo necesitáis para vuestros hijos, para vuestros nietos, y para todas las generaciones futuras. Esta es una gran revolución, y en cualquier revolución la gente ha sacrificado sus vidas. Hicieron muchos sacrificios. Dedicaron muchos años de sus vidas a este trabajo, para alcanzar la liberación.

Así pues, tenemos que entender que debemos asumir un poco la responsabilidad de Sahaja Yoga. He descubierto que la gente de Rusia lo hace sin que se les pida. Ellos no tienen mucho dinero, tienen rublos, pero donan todo lo necesario. Imaginad, siempre alquilan un estadio para Mí. Cada día tengo que hablar en un estadio, cada día. ¿Podéis imaginaros si tuviésemos que alquilar aquí un estadio cada día? ¿Podríamos pagar por él cada día? Esta podría ser la razón por la que Dios ve que aún no estamos preparados de hacer un programa en un lugar mayor. Así pues, vayamos poco a poco. Afortunadamente en India tenemos lugares abiertos, y podemos hacer programas al aire libre en los pueblos. Pero en las grandes ciudades la gente asume la responsabilidad de preparar todo de un modo adecuado.

Así pues, no debemos tomarnos Sahaja Yoga a la ligera. Es algo primordial en la vida. Pienso que estos son días muy, muy especiales. Estamos saltando desde el Kali Yuga hacia el Satya Yuga. Y el espacio entre ellos es llamado Krita Yuga, que es cuando el Poder Omnipresente intenta crear un movimiento de avance de nuestra evolución. Este es un tiempo muy, muy especial, porque el salto que hemos de dar es muy grande. Hemos de saltar desde el Kali Yuga hasta el Satya Yuga. Así pues, este Poder Omnipresente se ha vuelto hiperactivo. La actividad del Poder Omnipresente es tan grande, que yo misma me sorprendo. Intento ver de qué modo podemos ir tan rápido como Él, para obtener el mayor beneficio posible de este tiempo. Pero también descubro que, en Sahaja Yoga, hay gente que solo trabaja mentalmente en ello y, en cierto sentido, son un poco críticos con los demás o con cualquier trabajo como si este no fuese responsabilidad suya. Suponiendo que vayan al ashram dirán: “¡Oh, esto lo deberían haber pintado de otro color!”, o algo así. ¿Quién va a hacerlo? ¡Yo no voy a pintarlo! Por el contrario, todo lo que veáis que es erróneo debéis corregirlo vosotros mismos, es responsabilidad vuestra.

Esta es una visión tremenda. Estoy segura de que funcionará. Funcionará allí donde haya sahaja yoguis que estén dedicados de este modo. Así pues, la dedicación es muy importante. Si vosotros estáis dedicados, entonces el Divino estará dedicado a vosotros, y obtendréis bendiciones de todas las formas posibles. Desde todos los ángulos recibiréis bendiciones. Todo funciona de un modo tan bello que es sorprendente. La gente se sorprende, y yo misma también lo hago, de cómo cada persona individualmente es bendecida. Como sabéis, mi marido ha recibido un premio especial, y anteriormente había recibido treinta y un premios más. Premios importantes de treinta y un países. Él es la única persona en todo el mundo que ha recibido estos treinta y un premios. Y el premio que ha recibido ahora, es el más elevado que hay. Muy pocas personas lo han conseguido. Uno de ellos es Mr. Reagan. Quiero decir que para un indio es algo muy grande.

Hay cinco tipos de nombramiento de caballeros, y el que él ha recibido, es el más elevado de todos. Ahora ha empezado a reflexionar sobre ello, y en una de sus reuniones, creo que en Puna, dijo: “¡Solamente gracias a mi esposa recibo tantas bendiciones! Ella trabaja de un modo tan desinteresado por el bien de la gente, que quizá el Divino es amable conmigo, y por esta razón recibo todo esto”. Incluso el señor Parkinson dijo muy amablemente en su reunión, que no era fácil para los ingleses conceder estos premios. Este señor Parkinson fue muy dulce, y señalo todo esto como un gran acontecimiento. Fuimos invitados a la casa de Lancaster que, como sabéis, es un lugar al que muy raramente invitan los ingleses. Allí también estaban muchas otras personas del parlamento británico. El mismo parlamento británico nos invitó, y le dio a mi esposo regalos muy especiales. Mi esposo dijo que había muchas personas como él, que no era nadie tan especial. Incluso en esa reunión Mr. Parkinson dijo: “He oído hablar de leyendas, pero nunca esperaba poder ver una. Y ahora, aquí tengo a una sentada frente a Mí”. Luego, después de la cena empezaron a hablar.

Parkinson le preguntó a Mr. Shrivastava: “Por cierto, ¿cómo te verás con estas treinta y dos condecoraciones sobre tu cuerpo? Porque es algo que solamente un súper ser humano puede conseguir”. El bromeó diciendo que parecería un maestro de ceremonias en un circo.

Pero mi marido siempre sintió que había sido transformado, muy transformado. Se volvió muy humilde y de repente empezó a cuidarme mucho. Dijo: “¡Tú eres extremadamente valiosa para todo el mundo!” Está muy seguro de que solamente porque yo estoy muy bendecida por Dios, él es cuidado de este modo. En todos los aspectos de la vida ha sido ayudado, especialmente en lo que se refiere a asuntos económicos.

Por supuesto, al principio teníamos que gastar mi propio dinero para mis viajes. Las dos primeras veces vine a Australia con mi propio dinero. Incluso cuando vuestros primeros líderes fueron a India, yo pagué todos sus gastos. Pero él nunca puso ninguna objeción por ello. Siempre, incluso ahora, cada vez que necesito dinero para algo de Sahaja Yoga, es el primero en donar. Este año no sé cuánto dinero ha dado. Dijo que este sería el último año que podría donar, porque ahora se iba a jubilar. Pero como resultado, os sorprendería ver cómo ha sido ayudado él en asuntos económicos. Siempre que vendíamos nuestra casa en Londres, siempre obtenía un precio diez o doce veces mayor. Esto era algo fuera de lo común, quiero decir que nadie recibía tanto. Y la casa se vendía muy rápidamente y sin ningún problema, recibiendo siempre una cantidad extra de dinero. Él siempre guardaba dinero en el banco para mis viajes y para mis gastos. Pero me dijo que debíamos declarar algo a Hacienda, de otro modo el gobierno empezaría a preguntar cómo podemos mantenernos. Después de todo era dinero de mi marido y se suponía que él debía declarar todos sus ingresos. Aunque me lo donaba a Mí, aun así, debía declararlo a Hacienda. Yo le dije: “Muy bien, intentaré organizar algún tipo de pago de derechos por mis cintas o algo así”. Así pues, él está muy satisfecho con todo esto.

Él dijo: “Nada le puede suceder a nuestra familia, nadie puede tocar a nuestros niños”. A nuestros yernos les va muy bien, a nuestras hijas también les va muy bien y a nuestros nietos también les va muy bien. No tenemos ningún problema familiar. Todos ellos me apoyan, siempre están a mi lado, y son muy generosos y muy buena gente. No tienen ningún problema económico, pero piensan que todas estas bendiciones son solamente porque vosotros estáis haciendo todo esto por Sahaja Yoga. No tenemos ningún problema familiar como otras personas, no tenemos ninguna disputa ni nada parecido.

Esta vez le dije que los sahaja yoguis estaban allí. Él me dijo: “Debes invitarles a comer a nuestra casa”.

Yo le dije: “¡Yo no estaré allí!”

Y me contestó: “¡No te preocupes, yo me las arreglaré!”

Y verdaderamente hizo un gran trabajo. Aquellos que estuvieron en Pratishthan, recordarán la comida que él organizó. Todo lo organizó él. Hasta el menú. Todo lo hizo él, aunque debía marcharse inmediatamente después. Pero se quedó allí y os entretuvo a todos. Me han llegado noticias de que en mi cumpleaños hicieron un puja, quizá en Inglaterra, y él estuvo allí. Le invitaron y él dio una charla muy bonita acerca de Sahaja Yoga.

Así pues, una vez que sabéis que sois bendecidos, deberías desear hacer algo por ello. Una vez que tengáis este sentimiento en vuestro interior, seréis realmente ayudados. Como ya os he dicho, el Krita Yuga ya ha comenzado. Habéis visto muchas fotografías mías. Yo tengo algunas de ellas. ¿Las tenéis aquí? ¿Dónde está Steve? ¿Tienes las fotografías que has ampliado? Hay muchas, quiero decir, una cada vez mejor que la anterior. Hemos obtenido algunas recientemente, que aún no están aquí. Todo el Shri Chakra está sobre mi cabeza, como podéis ver aquí. Ha surgido con gran luminosidad. Esto es para que vosotros creáis que ahora estáis en una nueva era. No podéis pensar en ello ni cuestionarlo, simplemente debéis mirarlo y observar; ¿qué estamos haciendo nosotros? ¿Dónde estamos? Mientras que, si observáis a estos gurús, nunca les preguntan nada. Lo hacen simplemente para agradarles. Pero ¿cuál es su juego? Ellos tienen Rolls Royce, esto o aquello, pero no tienen ninguna reputación. Aunque definitivamente tienen discípulos muy dedicados, extremadamente, todos ellos y por millares. Además de esto les dan dinero y nunca les preguntan nada. Tienen discípulos muy dedicados, absolutamente. Vosotros lo habéis leído.

Ahora hemos recibido un informe de este gurú de gurú Mai, podéis leerlo y veréis cómo es. Os sorprenderá ver cómo la gente se ha dedicado a este hombre, que no les ha dado nada a cambio, y que es muy inmoral. Por el contrario, les ha maltratado. Esto desafía nuestra rectitud, y tenemos que ver qué vamos a hacer al respecto. Debemos salir todos fuera y hacer todo lo posible para lograr extender Sahaja Yoga. Ninguna otra cosa es importante. Cuando empecéis a alcanzar profundidad también mejorará, igual que un árbol que cuando empieza a crecer hacia afuera también lo hace interiormente. He estado diciendo todo esto desde que llegué aquí, porque ha habido muchos percances en Australia, y ahora esto debe parar. Si sois extremadamente dedicados, inmediatamente alcanzaréis la profundidad y la fuerza necesaria, para desbancar a cualquiera que intente estropear la imagen de Sahaja Yoga, y además comprenderéis todo. Porque vosotros no solamente vais a gozar y a sentir las bendiciones, sino que el resto del mundo os lo agradecerá. Os deseo que podáis ver esto, y también que podáis leerlo.

Otra cosa es que algunas personas que no son sahaja yoguis han hecho mi horóscopo, un tipo de horóscopo especial llamado R.V. Raman, que fue un astrólogo muy famoso. Este individuo es su discípulo, y ahora está completamente entregado a Mí. También deberíais leerlo, de modo que os convencieseis a vosotros mismos e intentaseis hacer introspección. Esto es lo que debemos aprender de los rusos, porque ellos son introspectivos. ¿Qué estamos haciendo nosotros? Si descubrimos que alguna persona hace algo erróneo, inmediatamente abandonamos. ¿Qué estamos haciendo nosotros? Nosotros tenemos ego o somos tacaños, o bien tenemos algunos condicionamientos. ¿Estamos salvando nuestras vidas? Esto es muy importante. En vez de ver faltas de los demás sahaja yoguis y de Sahaja Yoga, es mejor que descubráis las faltas que hay en vosotros. Intentad corregirlas, y también intentad comprender la grandeza de Sahaja Yoga. Debéis tener este tipo de mente para comprender la grandeza de Sahaja Yoga. No se trata solo de que Yo os amo ni de que vosotros debéis amarme, sino que debéis amar al mundo entero. Debéis preocuparos por el mundo entero. ¿Qué fue Cristo? ¿Qué fue Buda? ¿Qué fue Mahavira? Cualquiera de ellos. Ellos nacieron con este sentimiento. Ahora vosotros tenéis todos los poderes. Lo único que os falta es este sentimiento, y esto es lo que debéis desarrollar.

¡Que Dios os bendiga a todos! ¡Gracias!”