Ochtend seminari, Old Alresford (Engeland), 17 Mei 1980.

Nederlandse vertaling versie datum 2022-0816

We moeten weten dat Sahaja Yoga een levend proces is. Het is hetzelfde soort proces waardoor een zaadje uitgroeit tot een boom. Het is een levend proces. Dus het is Gods werk. Ik bedoel, hij moet het doen. Het is niet jouw taak. Het zaad laten ontkiemen is zijn werk. Maar het probleem ontstaat omdat, in dit stadium waar de mens het zaad is, hij over vrijheid beschikt, ze hebben vrijheid. Met die vrijheid kunnen ze zijn manifestatie, zijn werking bederven. Dus het eerste wat men moet onthouden is dat we wijsheid moeten hebben. Het eerste punt van wijsheid is dat het de Almachtige God is die dit werk gaat doen. Wij doen het niet. Jullie kunnen het zaad niet laten ontkiemen, hoe kunnen jullie dan dat zaad laten ontkiemen? En in die wijsheid moeten we, in onszelf, één ding leren en weten, dat je deel uitmaakt van het hele proces. Hoewel je je eigen vrijheid hebt, is vrijheid ook een onderdeel van hetzelfde proces. Je bent niet van God gescheiden.

Je bent geen afzonderlijke entiteit. Jullie maken deel uit van dat hele proces. Oké? Dus om te denken dat jullie er iets over moeten beslissen is ook fout. Jullie zitten in hetzelfde schuitje, gebracht tot het stadium waarin je de vrijheid krijgt voor je verdere evolutie. Dus in dit stadium, als je je vrijheid hebt, moet je weten dat vrijheid aan jou gegeven wil worden om er de waarde van te begrijpen. En in die vrijheid, moet je begrijpen wat eervol voor je is. Als je dat eenmaal begrijpt, zeg dan tegen jezelf: "Zie nu: Ik moet iets meer worden. Dat is waarom God dit heeft gedaan, het enige wat ik moet doen is alles coördineren, meewerken en me overgeven aan zijn wil, zodat ik word." Dit is de eerste voorbereiding die we moeten treffen. In die overgave, doe je het belangrijkste, omdat je daardoor zijn werk niet verstoort. Tenzij je je overgeeft, kun je de wijsheid niet bekomen. Dus allereerst begrijp je dit, door je beperkte wijsheid, en dan heb je de volle wijsheid. Allereerst, begrijp dit met het beetje wijsheid dat je hebt, dat, zonder overgave belemmer je de wegen van God. hij weet wat goed voor je is. Hij wil je het hoogste geven wat je zelf niet kunt bereiken. Hij gaat je het hoogste geven. Als je het wilt bereiken, kun je het niet bereiken. Het is zijn werk. Het is zijn werk, zoals jij het noemt, zijn geschenk aan jou. In dat geval moet je weten dat de beste manier om het te bereiken is, om zijn werk te laten uitwerken. Als je nu aan overgave denkt, begint allereerst de hersengolf te werken. "Wat moet ik opgeven?" Je denkt door opgeven aan, laten we zeggen, je materiële rijkdom.

Dat is niet wat hij wil. Het is allemaal rijkdom die hij aan jou heeft gegeven. Wat gaat hij daarmee doen? Het is zelfs niet gelijk aan een stofdeeltje van zijn voeten. Dus dit gaat niet helpen. Soms voel je dat, "Ik moet mijn intelligentie geven," of dat is wat er gevraagd wordt. Niemand wil jullie idiote en domme mensen hebben! Dus je geeft je intelligentie niet op. Dan denken sommige mensen: "Ik geef mijn hart op." Sommige mensen zeggen dat. We willen ook geen harteloze mensen. Dan zullen sommigen zeggen: "Moeder, we zullen onze relaties met anderen opgeven." Dat is ook niet nodig. Omdat je hart daar moet zijn waar het is en het licht moet in je hart komen. Aan wie kun je je hart geven? Wat heeft het voor zin om aan hem, die je je hart gaf, je hart terug te geven? Niet waar? Aan hem die je intelligentie heeft gegeven, wat voor zin heeft het om ze terug te geven? Iets dat je zelf bereikt hebt, moet gegeven worden. Wat je hebt bereikt is je ego en je superego. Wat je hebt bereikt is niets anders dan je ego. En dit ego moet je opgeven, wat een moeilijke taak is. Ego, als het voortkomt uit geld, materiële zaken, is het beter dat je wat materiële dingen opgeeft, niet aan God maar aan anderen. Het is beter zo. Als de materiële dingen dat ego creëren. Als je intelligentie ego creëert, bijvoorbeeld: je denkt dat je een zeer hoog IQ hebt, is het beter om het een beetje naar beneden te brengen. Het is aan jullie om te oordelen. Kijk naar jezelf. Wat maakt je ego zo opgeblazen? Als je naar je ego begint te kijken, zul je versteld staan, dat gelijk welk nutteloos ding het kan opblazen en het ook kan laten leeglopen.

Het kan gewond raken door helemaal niets. Het wordt zo belangrijk. Dan komt ook het superego opzetten. Dat moet je ook opgeven. En in het superego kun je je conditioneringen te danken hebben aan je guru's en verkeerde soorten daden en conditioneringen die je had vanaf je kindertijd. Zoals, bijvoorbeeld, iemand is katholiek: voor hem is de paus alles. Of iemand is een hindoe: voor hem is een bepaalde tempel alles. Dit zijn allemaal conditioneringen. Waarom het conditioneringen zijn is, dat zonder de waarheid over hen te zoeken, heb je ze gewoon geaccepteerd zoals ze zijn. Dit is het simpele ding. Dus als je de waarheid over al deze dingen te weten kunt komen, zul je ze opgeven. Je mag, je mag niet. Er zijn veel mensen die de waarheid kennen, toch geven ze niet op. Zie je, mensen zijn ingewikkelde dingen. Zelfs als ze de waarheid weten, zullen ze het niet opgeven. Maar stel dat je probeert de waarheid te vinden over al deze dingen: dan mag je geven, niet geven. Maar teruggaan in de hele zaak, om alles uit te zoeken, maak een schema van de hele zaak dat,     " 's Morgens vind ik iets over dit en 's avonds over dat:"

Je hele leven zul je één voor één zaken blijven vinden, en uiteindelijk zul je merken dat je nu in je graf bent beland. Dus die procedure zal je ook niet helpen. Door Gods genade zijn jullie gerealiseerde zielen en kunnen jullie in een seconde uitmaken of je nu aan de kant van de conditioneringen staat of niet. Als je links blokkeert, ben je geconditioneerd. Als je rechts blokkeert ben je op egotrip. Goed. Dus, je kent nu een heel eenvoudige methode om dat te weten, door vibraties, kun je erachter komen of Mr. Ego er is of het superego er is of je wankel bent. Dit is het grootste wat we hebben, want dit is mijn voorbereiding. Mijn voorbereiding is dat ik eerst jullie realisatie geef. Ik geef jullie eerst realisatie. Als je eenmaal gerealiseerd bent, hoef ik niet veel meer te zeggen. Als je aan de linkerkant geconditioneerd bent, krijg je pijnen, dit, dat. Als je rechts geconditioneerd bent, krijg je problemen met je gezondheid of zo. Dan zullen jullie tot mij komen en ik zal het jullie kunnen vertellen. Dit is mijn eigen voorbereiding: om jullie alert en bewust te maken zodat jullie licht hebben om dingen te zien. Nu jullie voorbereiding moet zijn om dit bewustzijn ten allen tijde te gebruiken. Verder zal ik zeggen dat: gebruik deze kennis steeds binnen in je. Dat vergeten mensen. Dus het eerste dat we moeten weten is dat deze voorbereiding voor ons is gedaan. We hebben de vibraties. Wij hebben de kennis om te controleren en wij moeten deze gebruiken. Wat je eerst moet aanvaarden is dat je in een nieuwe dimensie bent.

Als je dat aanvaard hebt, zal je oordeel beter zijn. Maar deze aanvaarding ontbreekt. Nu is er, in het Sanskriet, een woord, 'abhyas', als je elke dag hetzelfde doet op die manier, jij je zult herinneren dat je gerealiseerd bent en dat je bewustzijn niet het bewustzijn van gewone mensen is. Dus, de eerste voorbereiding om jezelf voor te bereiden, is om jezelf te vertellen dat je dit nieuwe bewustzijn in je hebt, is jezelf leren kennen. Zie je, op de universiteit wordt er een ceremonie gehouden als je afstudeert. Je moet met een jurk gaan en ze geven je een mooie rol en zo. Waarom is het nodig? Omdat je zou kunnen vergeten dat je een afgestudeerde bent. (gelach) Ja! En dat is precies wat er met jullie gebeurt, jullie vergeten dat jullie gerealiseerde zielen zijn. Ik bedoel, we hebben een ceremonie gehad in de zin dat we alles hebben gedaan om te bewijzen dat jullie gerealiseerde zielen zijn. Maar dit is wat er ontbreekt bij onze mensen, dat zij niet kunnen begrijpen dat zij gerealiseerde zielen zijn, dat het mensen zijn die op een niveau staan dat niemand anders heeft. Jullie zijn tweemaal geboren, wat zeer, zeer zeldzaam is.

Heel zelden vind je mensen die tweemaal geboren zijn. Ik bedoel, ik vond niemand, kun je je dat voorstellen? In mijn hele leven, behalve mijn vader en een paar hier en daar. Ik bedoel het is de moeite niet om ze te tellen omdat ik mijn vader koos en dat is het. Dus, allereerst als je aan je eigen intelligentie bekend maakt dat, "Ik ben een gerealiseerde ziel", zul je zien dat je prioriteiten heel snel zullen veranderen. Stel dat iemand je een enorm groot eigendom of een enorm grote rijkdom geeft. Onmiddellijk word je je ervan bewust. Je begint zo te lopen. Wanneer je een student bent loop je zo. Plotseling krijg je het diploma en loop je zo. (gelach) Hoe zit het met realisatie? Zo blij om je hier te zien, heel blij. Moge God jullie zegenen. Hoe zit het met je realisatie? Heb je je realisatie niet? Wat doe je er dan aan? Dit is de eerste voorbereiding: identificeren dat je een gerealiseerde ziel bent. We moeten op een andere manier praten - we zijn nu gerealiseerde zielen.

Wij zijn mensen van een andere kennis. Wij zijn mensen met een ander bewustzijn. Zoals ik je al zei. Bekijk dit prachtige gebouw. We zijn er allemaal door gecharmeerd en het ziet er heel mooi uit. Het is zo goed en mooi gedaan en het is heel belangrijk voor mensen. Oké? Maar voor het Goddelijke is zelfs dit groene blad belangrijker dan het hele gebouw bij elkaar en meer van die gebouwen bij elkaar. Voor het Goddelijke. Omdat dat blad leeft en een vogel die meer bewust is dan dat blad is veel belangrijker voor het Goddelijke. Dus jullie, de mensen die nu in deze mate bewust zijn hoe belangrijk moeten jullie wel zijn voor God? Hoezeer moet God zelf in jullie geïnteresseerd zijn? Denk daar maar eens over na! Als je dit punt eenmaal herkent, dan zul je relatief ook weten hoe erg belangrijk je bent in Gods plan. Ik heb het niet over zijn aards plan. (gelach) Het is Gods plan. Dus al de krachten van zijn zegeningen en al zijn verhevenheid, ze zijn er allemaal om je te helpen, je te steunen, je te geven wat je maar wilt. Je staat op het podium en zij zorgen voor je.

Ik bedoel, je bent nu op het toneel gekomen. Maar ik vind Sahaja yogi's, als ze eenmaal hun realisatie hebben, weet ik niet wat er met hen gebeurt. Als ze hun ego opgeven dan worden ze als, absoluut, ik weet niet hoe jullie ze noemen... bananen? (gelach) Ieder van jullie is de speciale, door God geschapen. Bekijk het nu voor jezelf, denk gewoon aan jezelf. Ik bedoel, jullie zijn degenen die zoveel van het leven weten. Zelfs als je een beetje bezeten raakt, maakt het niet uit. Maar je weet dat je bezeten bent. Denk er nu eens over na. Dit is de tweede voorbereiding die men moet hebben - het begrip dat het de Almachtige God zelf is, die bezorgd is om jullie. Hij heeft iedereen gestuurd om je te helpen, "Ga je gang!" Dus je hoeft je geen zorgen te maken over je geld, je hoeft je geen zorgen te maken over alle andere dingen. Het derde ding komt automatisch dat je je over al deze dingen helemaal geen zorgen hoeft te maken. Er zal voor gezorgd worden. Er is voor jullie allemaal gezorgd, dat weet je. Iedereen is geholpen. Maar als je weet dat hij de Almachtige is en dat hij medelijden heeft en dat je in zijn genade bent gevallen - denk daar eens aan! Vestig jezelf op dat punt. Dit is de voorbereiding die men moet hebben, dat hij degene is die dit alles heeft gegeven. Dan zijn de moderne Sahaja yogi's speciaal gezegend omdat ze een 'walkie-talkie' bij zich hebben. Alle problemen die ze hebben, worden persoonlijk afgehandeld! Zo'n zegen was er nog nooit.

Maar ego is het punt. Om te beginnen is er ego. Je hebt het gezien. Als je ego hebt zul je niet accepteren dat je een gerealiseerde ziel bent. Stel je voor, hoe dwaas is dat! Als je ook een superego hebt, zul je het niet herkennen. Je gaat terug naar dezelfde positie als voordien. Je zult nooit accepteren dat je een gerealiseerde ziel bent als je een superego hebt. Je zult nooit accepteren, "Oh, hoe kan het, Moeder? Ik ben tenslotte een gewoon mens." Zo ga je maar door, "Hoe kan ik anderen genezen? Hoe kan ik realisatie geven? Het is niet mogelijk." Zie je dit soort nederigheid, onzinnig. Ik bedoel, ‘t is in orde, ik bedoel, het is als een soldaat die zegt, "Oh, hoe kan ik doden?" Zo is het. Het is alsof het geen betekenis heeft. Dit soort nederigheid heeft geen betekenis voor jou. "Hoe kan ik het doen, Moeder? Wat kan ik doen? Oh, ik deug niet. Ik ben van geen nut." Deze taal moet worden opgegeven.

Als het ego is, is het nog erger. Je kunt jezelf schaden en uiteindelijk kun je Sahaja Yoga schaden. Egoïstische mensen zijn extreem moeilijk, het zijn zo'n lastposten, omdat ze alles proberen te doen met hun intelligentie en verstand en dit en dat, en zo gaat het maar door en door en door, en je probeert ze weer terug te halen maar ze gaan weer weg. Het is zo saai, weet je. Erg saai. Want weet je, ik zie het spul, veronderstel, Ik weet dat het dit is (een kopje thee) en ik wil ze aan je geven. En terwijl ik ze naar je lip breng, duw je ze telkens weg. Telkens duw je ze weg, hoe kan ik ze dan aan je lip brengen? Het is erg saai! En dit egoïstische temperament is zeer wijd verspreid in het Westen, verrassend. En ik begrijp het gewoon niet. Ze kunnen alle soorten vuiligheid aan, allerlei perversies zonder er ruzie over te maken! Ze nemen het gewoon aan! Elke vorm van perversie - "Wat is er mis mee?" Maar het is voor hen totaal onmogelijk om het feit te accepteren dat je een gerealiseerde ziel bent door middel van Sahaja Yoga.

Ze accepteren alles, maar niet de waarheid. Dit ego is als een paard dat op je hoofd zit. Jij moet op het paard zitten, en het paard zit op je hoofd. Jij draagt de last van het paard - stel je voor! Wat heeft dat voor zin? Als je jezelf gaat analyseren, ga je weer in een andere trip. Jullie zijn zulke 'trippers' als Jack in the box, zie je. Omdat je trip na trip hebt gemaakt, is er een soort veer. Je probeert je ego te zien, je gaat op een trip van superego. Je probeert je superego te zien en je gaat op een trip van ego. Ik bedoel, een persoon die de hele tijd naar deze trip of die trip heeft gestuiterd of die reis of die reis, is net als een persoon die de hele tijd reist, niet weet of hij moet afstappen of verder moet gaan. Zo is dat. De gewoonte van het verstand is zo egoïstisch dat je gewoon de rit op het ding neemt. Maar het is niet zo dat jij de rit maakt, maar het ego neemt je mee op een ritje.

En telkens er zoiets gebeurt, grijpt het je. En de vooruitgang is extreem traag. Het probleem met het Goddelijke is dat het zijn eigen protocol heeft en als de koning naar jouw huis moet komen, moet je de koning uitnodigen. De koning schrijft u toch niet: "Nodig me alstublieft uit bij je thuis?" Daarom is hij tenslotte koning! En hij smeekt de mensen niet: "Nodig me alstublieft uit." Deze meneer Ego verwacht dat je wordt uitgenodigd door het Goddelijke. Dat het Goddelijke uit de weg moet gaan om u eruit te kiezen. Ego, simpel gezegd, is niets anders dan absoluut verkeerde ideeën over iemands eigen waarde: waardoor je denkt dat, "Ik ben alles." Wat ben jij? Ga nu niet op een superego trip. Wat zijn wij? Niets! We kunnen niet eens het zaad laten ontkiemen. In het dagelijks leven zie je dit duidelijk: hoe ego opspringt. Veronderstel dat iemand zegt, "Britten hebben deze kwaliteiten," men voelt zich zeer gelukkig. "Oh, wat een lof is het! Wat een lof voor de Britten! Oh, we zijn Britten!" meteen. Iemand zegt dat, "Britten missen deze kwaliteiten," gedaan! Je bent absoluut... dan is die persoon de slechtste persoon in de hele wereld.

Allereerst moet je weten dat je noch Brits, noch Indisch, noch iets anders bent. Jullie zijn gewoon mensen. Onwetendheid is verantwoordelijk voor dit ego. Het is de volledige onwetendheid over jezelf die je dit ego geeft. Dus eenmaal we op weg zijn naar het licht, moeten we weten wat onze hindernissen zijn. Dit is de voorbereiding. Het is de onwetendheid die we over onszelf hebben waarom we onszelf gaan zien. En vanwege de onwetendheid, zijn ego en superego allebei op ons afgekomen, we hebben dus tenslotte niets met ze te maken. Stel dat je naar de Himalaya moet voor een expeditie. Je wordt verondersteld de lichtste dingen te dragen die je hebt. Je draagt geen drie koffers met voeding, vier koffers van dit, en vijf van die dingen, om daar een lekker bedje te hebben en te slapen. Dat laat je allemaal hier achter. Op dezelfde manier als je op de expeditie gaat om jezelf te leren kennen, moet je alles wat jezelf overbelast, achterlaten. Dus komen we weer uit bij ego en superego. Eigenlijk zijn deze twee verschrikkelijke olifanten die in toom gehouden moeten worden. Dus we maken onze eigen studie. Deze voorbereidingen zijn nodig omdat we al te veel deze kant op zijn gegaan of te veel die kant.

Dus de voorbereiding is om je naar beneden te brengen, "Kom hierlangs. Nu ga je in het midden staan!" Of we brengen je hier naar beneden en we staan in het midden. De voorbereiding is niets anders dan om je hier beneden te brengen, dat is alles. Dus we gaan verder met ego en we zien dat het subtielere en subtielere en subtielere vormen heeft. Zelfs in superego heb je subtielere en subtielere en subtielere vormen. Om ego te begrijpen moet je zien wat je van plan bent met je leven. Het is heel gemakkelijk. Wat zijn je plannen voor het verdere leven? Om je superego te begrijpen moet je weten waardoor je erg beïnvloed wordt, wat je erg ongelukkig maakt. Of je kunt zeggen, wat maakt je gelukkiger en wat maakt je ongelukkiger. Beide dingen, geluk en ongeluk, zijn de schaduwen van deze twee bomen. Het ene is ego, het andere is superego. Let maar eens op. Wat maakt je erg gelukkig? Goede kleren? Goed leven? Of als je naam voorkomt in "Who's who?" (boek) of al die onzinnige dingen die je aan het lachen maken, zie je! Dat allemaal. Zie je dat. Wat maakt je ongelukkig? Als er een soort van liefdesverdriet is en dit en dat. Al die onzin. Beide dingen zijn niet jezelf. Ze zijn gewoon de buitenkant. Dus wat er binnenin zit, als je dat wilt ontdekken, moet eerst de buitenkant weggenomen worden.

Als je het fruit wil proeven, haal je de buitenkant eraf, je schilt het. Op dezelfde manier, moet dit worden afgepeld. Dit moet je in jezelf zien en ook daarbuiten. Je kunt het heel duidelijk van buitenaf zien. Het is heel gemakkelijk. Hoe je met anderen omgaat is het punt - hoe is je relatie met anderen. Het is makkelijker om dit van buiten te weten dan van binnen, misschien. Als je met anderen praat, wat is dan de indruk die ze van je hebben? Word je door anderen gewaardeerd of niet? Onder Sahaja yogi's. Respecteer je een andere Sahaja yogi als een Sahaja yogi of niet? Verwacht je dat in welk stadium je ook bent, de andere Sahaja yogi ook zal groeien en dat hij het gepaste respect moet krijgen? Ook moet u zien dat wanneer een Sahaja yogi, die iets bereikt heeft of die op een hoger niveau staat, probeert je omhoog te trekken -vind je dat fijn, verzet je je ertegen of raak je erdoor van streek? Als iemand je zegt: "Dit moet je doen, dat moet je doen," neem je het dan op alsof hij je misbruikt heeft?

Als hij je vertelt over Sahaja Yoga moet je dankbaar zijn op alle mogelijke manieren. Ik ben je dankbaar als je me iets vertelt dat met Sahaja Yoga te maken heeft. Om het even wat! Zelfs als je tegen me zegt, "Moeder dit is misschien niet in orde als u zegt. Zie je, de mensen zijn zo:" Ik aanvaard het en ik doe het volgens jouw wensen. Of je het leuk vindt of niet? Dit is hoe je je ego zult beoordelen. Dit is alleen jouw Mr.Ego. Eigenlijk, is het beter om een ander te hebben om tegen je ego en jezelf te vechten; allebei samen. Als iemand je zegt, "Dit moet je doen," "Oh, ik zie het, ik heb dat gedaan. Ja, goed. Kom en help me. Je trekt me eruit. Werk het eruit. Probeer me te helpen. Ik ben verschrikkelijk!" Dat is de manier, als je het doet, dat je over dit ego heen kunt komen. Maar de andere persoon moet zeggen, "Je bent erg aardig. Oké, doe wat je wilt." en dan voel je je gelukkig. Deze persoon is niet zo in orde en jij bent ook niet zo in orde. Omdat je mensen eruit moet halen. Bijvoorbeeld, als je begrijpt dat je in een crisis zit, zit je in een noodsituatie, mensen verdronken en sommigen proberen hen eruit te trekken, zij zijn zelf halverwege naar beneden, halverwege naar boven, ze proberen je eruit te trekken, op dat moment, als zij zeggen: "Houd nu mijn hand vast!"

Als je je er boos over maakt, ben je niet wijs. Nu is er in Sahaja Yoga geen leider als zodanig. Ik bedoel, niemand is aangesteld als leider. Als iemand dat probeert, gaat hij eruit. Maar binnenin zit een aangeboren leiderschap, en zo'n persoon is uiterst nederig en sympathiek en aantrekkelijk en bevelhebbend ook, hij moet bevelhebbend zijn. En men zou zich op dat moment niet slecht moeten voelen, want als hij zegt, "Ga en steel iets," of "Ga en sluit je aan bij een van deze onzinnige dingen", dan heeft hij het natuurlijk mis! Maar als hij zegt, "In Sahaja Yoga moet je groeien!" Zelfs dominant als hij dat zo zegt, ik bedoel, het is een zeer goede zaak, zou ik zeggen. Stel dat er iemand in je buurt is die altijd kritiek heeft. Op een bepaalde manier is het een zegen, want als er iemand is die ons bekritiseert probeert hij ons te perfectioneren. Ik bedoel, we moeten dat aannemen. Er ons niet slecht bij te voelen. Stel dat iemand iets over je zegt, en het niet waar is, wat is er dan om je slecht bij te voelen? Als hij leugens over je vertelt, er is niets om bang voor te zijn.

Als hij de waarheid spreekt, dan moet je dankbaar zijn. Hoewel de waarheid soms zeer onsmakelijk kan zijn, zeer, zeer slecht. Maar het is een goede zaak. Er is een gezegde in Marathi, "Houd het huis van degene die een lasteraar is, degene die kwaadspreekt, houd het huis van zo'n man, die aan achterklap doet, naast je. Naast de deur." Dat je je gebreken kent, zie je, je corrigeert jezelf, is de wijze houding. Omdat je jezelf niet kunt corrigeren, dus gebruik een spiegel waarmee je jezelf kunt corrigeren. Ik bedoel, je zou zo'n man, die kritiek op je heeft, moeten bedanken. Als hij je volledig wil vernietigen door je te vertroetelen, wat is het nut? Dit is wat de guru's doen. Ze zijn je allemaal aan het verwennen en aan het vernietigen en uiteindelijk kom je erachter dat je bent bedrogen. Dus als je de situatie accepteert waarin je zegt: "Oké, als dit de waarheid wordt, is dat veel beter voor mijn ego en als het niet de waarheid is, wat is er dan zo belangrijk?" Deze houding helpt in Sahaja Yoga heel veel, het is een zeer wijze houding tegenover zichzelf.

En je zult verbaasd zijn hoe je groeit met deze houding, je zult niet snel gekwetst worden door wat mensen tegen je zeggen. Het kan je niet schelen. Je weet hoeveel mensen mij bekritiseren en van alles zeggen, redetwisten met mij, en het kan me niets schelen omdat ik weet dat ze dwaas zijn. Wat is er? Het zijn domme mensen. Dus... Zelfs als ze me prijzen, wat dan? Ten slotte, hoe ze me ook prijzen, het is mijn aard, niets zo groot. Zie je, het maakt geen verschil. Ik kijk gewoon hoe mijn chakra's werken. Ik heb er geen last van. Op dezelfde manier zal het ook bij jou gebeuren en het zal je niet storen. Maar dit zal je helpen bij het ontladen. Dit zal je helpen bij het ontladen. En, het ongelukkige deel ervan: dat wij ons moeten voorbereiden op een manier dat, "Niets kan mij ongelukkig maken. Wat kan mij ongelukkig maken als ik een gerealiseerde ziel ben?" Veronderstel dat je met iemand wil trouwen, neem een concreet voorbeeld. En je vindt dat de persoon zich misdragen heeft of je kan niet trouwen. En wat dan nog? "Ik ben er. Mijn waarde is mezelf, die ken ik."

Dus je waarde, je gevoel van eigenwaarde moet zo zijn dat niets je ongelukkig kan maken. Het is allemaal toneel. Het is allemaal toneel. Maar deze dingen moeten worden aanvaard door jullie grote intelligentie want wat ik hier vind is dat de moeilijkheid, de Westerse geest is, het heeft te veel van IQ, te veel overontwikkeld. Dus het is zo'n gepolijst oppervlak dat niets er op blijft, niets... Het eerste simpele ding is dat je een gerealiseerde ziel bent die zich daar op een of andere manier moet vestigen, op je intelligentie dat je nu een gerealiseerde ziel bent. Jullie geloven allemaal in het hart, niet in het verstand. Dat je een gerealiseerde ziel bent, is het eerste wat je je intelligentie moet vertellen. En dan moet je je intelligentie ook vertellen, "Niets kan mij ongelukkig maken en niets kan mij bedotten." Als deze drie punten op uw intelligentie inwerken, zal ik de rest zien. Je moet alleen deze drie punten aan je intelligentie opleggen, dan zul je versteld staan dat je een zeer liefdevol persoon zult worden, uiterst attent voor anderen. Het komt allemaal vanzelf goed. Want als jullie intelligentie zo is, gaat er niets naar binnen. Jullie zijn de hele tijd bezorgd om anderen. Of jullie zijn bang voor anderen of jullie zijn agressief tegen anderen.

Jullie kunnen niet rechtdoor gaan. Dit is wat er gebeurt. Als je deze drie punten duidelijk zou begrijpen... Yogini: Niemand doet dat.(lachend) Shri Mataji: Zij zegt: "Niemand doet dat. Dat is het probleem." Absoluut. Ze is zo praktisch.(lachend). Ze is zo praktisch, zie je. Zojuist in de auto zei ze, "Iedereen doet wel eens iets anders dan zou moeten. Zij doen niet wat eerst gedaan moet worden." Zoals zij zei, "Ze zullen trouwen, je moet trouwen en van je vrouw genieten en je man en je kinderen. Zij doen andere dingen, behalve dat." (lachend) Dat is het. Zie je, niemand doet dat. Het is zo praktisch als je het doet. Luisteren naar Mataji dat is niet wat ik wil dat jullie doen, maar zo handelen wel. Ga zitten en vertel je intelligentie, je IQ, dat, "Meneer IQ, luister nu alstublieft. Dit is wat er met mij gebeurd is, en dit is wat ik ben. Ik ben een gerealiseerde ziel en niets mag mij verwennen en niets mag me ongelukkig maken." Dat is alles. "Niemand kan me pijn doen." Anders ben je, "Aaahahhahaa, aahhaahah," of zoiets, het gaat in twee richtingen.

Nooit in een rechte lijn. Waar je alleen mededogen bent en je liefde bent. Absoluut op jezelf vertrouwen, absoluut. En dan ben ik bij je. En je denkt aan die wijzen die niemand hadden om hen te leiden, om hen iets te vertellen, niemand om mee te praten. Al je granthi’s (blokkades) en zo, ik ben er kapot van. Je hoeft niets te doen. Maar het enige wat je niet moet doen is je eigen granthi’s maken, je eigen blokkades. Als je ze niet creëert, komt het wel goed. Dit is een zeer eenvoudige voorbereiding. Dus ik hoef het jullie niet te vertellen, "Heb uw broeders en zusters lief," en dit en dat. Dat gaat de andere kant op. Maar je vertelt het gewoon aan je intelligentie. Dit is de verlichting van de intelligentie. Als die intelligentie in je komt, dan is het wijsheid. "Dat iemand me uitlacht of iedereen me uitlacht of iemand mij probeert te domineren," al deze angsten of al deze agressiviteit, dit zal allemaal zomaar verdwijnen. Dat je nu een bloem bent en dat je geurig bent en de geur zich verspreidt, en vele bijen zullen naar je toe komen, dat is wat je bent! Dit is het begin.

Blijf dat maar aan jezelf vertellen. Als je dat zou kunnen doen, als je je intelligentie op dit niveau kunt brengen, niet te hoog, niet te laag, maar in het centrum, kan alles in een mum van tijd opgelost worden. Wanneer ik nu met jullie leef, jullie Kundalini’s bekijk, dat allemaal, ben ik er op dit punt achter gekomen: dat jullie dit niet aan je intelligentie vertellen. Zodat je begint met het opgeven van alle soorten van fanatisme, alle angsten en zo, en bijgeloof en al die onzin. Omdat niets je kan schaden. Geen sterren kunnen je kwaad doen, je kennis kan je geen kwaad doen, hoe laat je geboren bent. Niets kan je nu nog schaden! Je staat er boven. Dus astrologie heeft afgedaan. Horoscopen hebben afgedaan. Alle andere... welke andere dingen had je zoals dit? Sahaja yogi: Karma. Shri Mataji: Karma’s zijn opgelost. Sahaja yogini: Handlezen. Shri Mataji: Handlezen heeft afgedaan. Sahaja yogi: Bioritme. (Groot gelach) Shri Mataji: Bioritme is voorbij! Bioritme is voorbij! Dat allemaal. Ik bedoel, je staat daar boven. Nu al deze dingen, al die dingen.

Dan de andere kant ervan. Alle liefdesaffaires beëindigd. Alle angst voor liefdesaffaires is voorbij. Alles is afgelopen, is onzin. Het is alleen maar liefde. Nu, wie je ook krijgt, je zult die persoon liefhebben, die persoon zal jou liefhebben. Als hij niet om je geeft of van je houdt, maakt niets uit. Als je maar liefhebt, klaar! Alle verwachtingen klaar, alle verwachtingen klaar. Alle verwachtingen voor geluk. Vreugde is enkel en absoluut. Wanneer je in vreugde bent, ben je in een toestand waarin er geen beweging is. Je bent er gewoon. Dus weg met die twee gevoelens van, "Nu ben ik heel gelukkig!" "Ik ben nu in vreugde. Ik ben gevestigd in vreugde en dat is wat ik in mij moet laten groeien, niet mijn oude spullen. Die zijn dood, opgelost." Als de bomen hun bladeren laten vallen, dan verwachten mensen niet dat ze opstaan en zich weer aan de bomen hechten? (Gelach) Op dezelfde manier is alles wat voorbij en af is, nu af. Laten we nu groeien wat nieuw in ons is, en dit moet nu gekoesterd worden - het is de vreugde, het is die waardige majestueuze schoonheid in onszelf. Dan raak je niet van streek. Het maakt je niet uit wat anderen over je zeggen. Het zal gebeuren. Het zal gebeuren als jullie het op jullie intelligentie zetten.

En mensen zullen dat in jullie zien omdat jullie geen onzinnige dingen doen, niets verkeerd doen. Mensen zoals jullie. Zelfs zij die niet gerealiseerd zijn zullen die waardigheid in jullie zien, dat jullie zo waardig zijn omdat jullie zelfkennis hebben. Het is iets heel simpel, maar zoals zij het heeft gezegd, doet niemand het. Vertel het aan je intelligentie. Zelfs nu merk ik dat bij sommige mensen die vreugde in hen doorsijpelt. Maar daar moet je in opbloeien. Je moet er in komen, alles wat onzinnig is weglaten. Anders ga je er zo aan. En het kost bijna geen tijd of nauwelijks iets. Wat verkeerd is gedaan, is verkeerd gedaan, afgelopen! Gewoon afgelopen, want het is nu dood, dus waarom je er zorgen over maken? Gewoon afronden. Omdat, als ik je iets op een harde toon vertel, zal het daar niet blijven hangen. Als ik het voorzichtig doe zal het ook niet lukken, want, wat ik je vertelde, er is een glanslaag. Haal de glanslaag weg, en wat is de glans?

Die glans is het alomvattende begrip van normen, het alomvattende begrip van levensnormen. Omdat je dacht dat als je in deze toestand zou zijn, je gelukkig zou zijn, dat is waarom je het doet. Omdat je dacht, als je dit doet, is er een angst, het is het probleem van de linkerkant. Maar dit volledig begrip van de geest, als je het opruimt met je licht, met je eigen wijsheid, dan zul je versteld staan dat het aan je blijft kleven, volledig. Deze wijsheid zal in je blijven hangen. Vergeet die oude onzin. Zoveel dingen heb je zelf al uitgezocht, weet je, zo veel dingen die voorheen onzinnig waren. Maar de identificatie van al deze ideeën moet worden bereikt, moet worden bereikt, dat is het punt. Je weet dat dit allemaal onzinnig is, maar het moet bereikt worden. Dat is de voorbereiding. Je hebt het licht, je hebt de beweging nu. Je beweegt je er in, maar het licht is niet hier. Het bengelt, soms valt het zo, valt het zo. Als je je licht goed kunt richten, juist door dit begrip dat wat voordien de normen waren, te wijten waren aan onwetendheid en we moeten nu onze eigen normen hebben betreffende wat een Sahaja yogi is. En deze normen, ik ga vertellen hoe deze normen tot jullie gaan komen als geloof, als volledige afhankelijkheid van spiritualiteit, volledige afhankelijkheid van je vibraties. Al deze normen van het nieuwe leven, moeten we accepteren.

Maar om ze te bereiken, ik wil zeggen, ze moeten bereikt worden, zie je. Niet alleen om te begrijpen in een lezing. Dus ik zal daar vanavond over vertellen, en morgen zal ik je vertellen over het echte ‘worden’, oké?  Dank u.

Moge God jullie zegenen.

Shri Mataji: Ga maar door, nu gaat u open? Sahaja yogi: (onhoorbaar) Shri Mataji: u wilt uw positie niet innemen, dat is het probleem. Beter? Dit is net wat ik zeg, zie je. Het komt naar buiten. Zeg dan gewoon, "Er kan niets gebeuren. Geen bhoot kan mij vangen. Ik kan de bhoots vangen." Dat is de waarheid. Douglas Fry: Lunch is geserveerd. Shri Mataji: Hah? Sahaja yogini: Wilt u uw lunch hier nemen?  Shri Mataji: Of anders? Sahaja yogini: In de eetkamer. Ze is erg mooi...

Shri Mataji: Mooi of niet, ik zal ze samen met jullie nemen.
