Shri Ganesha Puja, Utrzymuj Swoje Granice, 15.01.1984 Bombaj, Indie

To jest tak Sahaj dzisiaj, że dzień świętowania przypadł na urodziny Shri Ganeshy.

Każdego miesiąca, czwarty dzień księżyca obchodzony jest jako dzień urodzin Shri Ganeshy i dzisiaj jest ta data. Szczęśliwie, jesteśmy tutaj na Pujy do Shri Ganeshy w jego urodziny. Mówiłam wiele o Shri Ganeshy i Jego znaczeniu w naszym życiu. On jest dawcą mądrości, ale ta mądrość pochodzi od naszej niewinności. Niewinności, która jest wrodzona.

Jesteśmy niewinni tak jak dzieci, ale gdy dorastamy, zaczynamy eksploatować siebie w taki sposób, że zaczynamy tracić naszą niewinność. Tracimy ją na dwa sposoby: po pierwsze, gdy stracimy naszą niewinność, nie możemy uwierzyć, że inni mogliby być niewinni. Po drugie, myślimy, że niewinność nie jest ważna. Niewinność to wsparcie, to podstawa duchowości. Jeżeli osoba nie ma niewinności, nie może wzrastać w duchowości. Dlatego pierwszym zadaniem Sahaja Yogi jest ustanowienie Shri Ganeshy w was, przebudzenie Go.

Jak tylko Kundalini się budzi, musicie wiedzieć, że Shri Ganesha zaczyna działać. Bez jego przebudzenia w was, Kundalini nie może być uniesiona. Ale mogłaby być [uniesiona] chwilowo lub mogłaby być na stałe. Mogłaby [unosić się] na bardzo krótko u ludzi, którzy nie są jeszcze przystosowani do nowej metody lub do ścieżek Boskiej miłości. Tym, którzy nie zrozumieli lub tym, którzy nie przeszli poprzez te tradycje, jest im raczej trudno ustanowić Shri Ganeshę w sobie.

W tym punkcie odkrywam, że są ludzie, którzy walczą ze swoimi problemami i starają się przezwyciężyć powierzchowne problemy i ustanowić Shri Ganeshę. Ale są też inni ludzie, którzy wciąż jeszcze tego nie osiągnęli i zaczynają wątpić w niewinność innych. W Sahaja Yodze jest to bardzo częsty przypadek. Widuję ludzi narzekających na innych, mówiących, że ich niewinność nie jest ustabilizowana. To jest pierwsza oznaka, że wasza własna niewinność jest zagrożona.

Ponieważ wątpicie w siebie, wątpicie też w innych. Jeżeli wątpicie w innych, bądźcie pewni, że niczego nie osiągniecie. Waszym zadaniem jest zająć się sobą a nie innymi. I jeżeli zaczniecie tak postępować, stopniowo w waszej Mooladharze będzie mnóstwo tych buców, które tam wskoczą. I będą wam podsuwać więcej i więcej pomysłów na to jak wątpić w innych. Przez wątpienie w innych, nigdy nie możecie skorygować ani siebie ani innych. Więc ci ludzie, którzy się zagłębiają w tego rodzaju praktyki, oddalają się od swojej niewinności.

Oni próbują dociec, co inni robią, jakie są ich sposoby wykorzystywania innych ludzi w Sahaja Yodze, dla swoich własnych celów. Lub rozwijają zabawną postawę quasi-szpiegowską. W Sahaja Yodze macie tylko szpiegować samych siebie, a nie innych.

Ci, którzy zaczynają szpiegować siebie, krytykować innych, nigdy nie wzrosną powyżej tego czym jesteście.

Widziałam, że wielu Sahaja yoginów, którzy przyszli na początku, próbowało to robić, krytykować innych, co jest oznaką ich niedojrzałości, jak też słabego obudzenia ich Shri Ganeshy. Więc ci, którzy przychodzą po raz pierwszy, powinni być bardzo uważni na to, że wciąż jeszcze muszą wiele osiągnąć. I nie powinniśmy zaczynać powątpiewać w innych, robić uwag o innych. Ponieważ w niewinności, ludzie mogą być bardzo, bardzo prości, bardzo przyjacielscy, ale wewnątrz ich serca nie ma niechęci, nie ma brudu. Ale ci, którzy przychodzą po raz pierwszy, mają czasem w sobie brud. I oni widzą odzwierciedlenie swojego własnego brudu w innych ludziach.

Poszłam na program w Kolhapur – i wiecie jaka wasza Matka jest niewinna i czysta, i przyszedł jakiś pan, i powiedział Mi, że ma problem z Nabhi. Więc powiedziałam: “W porządku, połóż swoją rękę na Moim Nabhi”. On położył tam rękę i kobiety tam, które były bardzo dziwne, powiedziały: “Dlaczego Matka pozwala obcemu mężczyźnie dotykać swojego kolana?” One nie mogły tego zrozumieć.

“Jak ktokolwiek mógłby dotykać damskich kolan?” Ale jak tylko jesteś na takim poziomie, ty już naprawdę nie widzisz w tym niczego złego. I po prostu mówisz: “W porządku, wszystko w porządku, możesz dotknąć mojego kolana”. I mężczyźnie się poprawiło z jego kłopotem, z jego Nabhi. Więc widzicie, rzecz w tym, jeżeli wasze oczy są czyste, możecie zrozumieć co jest czyste a co jest nieczyste. Ale jeżeli wasze oczy nie są czyste, to wy zaczynacie widzieć coś, co chcecie zobaczyć. Albo czasem widzicie coś, co nigdy nie istniało. Więc wymagałabym od wszystkich nowych Sahaja yoginów, którzy tutaj są, żeby nie krytykowali starych Sahaja yoginów, gdyż to jest bardzo antyboskie działanie. Nigdy nie mów złego słowa o starych Sahaja yoginach. Ponieważ słyszałam skargi, ludzie przyszli i Mi się skarżyli. I byłam zdumiona.

Ci, którzy dopiero co przyszli tutaj, jak oni mogą zacząć krytykować innych Sahaja yoginów? To oznacza, że staracie się uderzyć w korzenie Sahaja Yogi. I to nie jest sposób w jaki pomożecie. Więc muszę was prosić, dbajcie proszę o swoje własne wibracje, dbajcie o swój własny wzrost, dbajcie o to co zrobiliście dla Sahaja Yogi, a potem mówcie. Nagle, jeżeli dopiero co weszliście do Sahaja Yogi i zaczynacie krytykować innych, na temat ich niewinności, to wy uderzacie w Ganeshę przy samych korzeniach. Więc bądźcie ostrożni; oczywiście, będziecie ukarani bez wątpienia. I tacy ludzie, którzy tak czynili, widziałam, jak kończyli z rakiem. Bo Ganesha jest tym, który gdy wpada w gniew, to pierwszą rzeczą którą dostajecie jest rak. Więc bądźcie ostrożni, ostrzegam was, nie próbujcie więcej tych sztuczek. Starajcie się poprawić waszą duchowość, tak byście mogli cieszyć się radością Shri Ganeshy.

To jest jedna strona, drugą stroną jest to, by utrzymać Shri Ganeshę nienaruszonym musimy mieć określone maryada, każdy musi mieć określone maryada. Jak to, powiedziałabym, że poprosiłabym Panią by położyła rękę nawet na wysokości mojego serca z przodu, ale nie poprosiłabym mężczyzny, żeby to zrobił, ponieważ jest maryada, jeżeli jesteś mężczyzną, nie powinieneś dotykać Mnie z przodu, lecz możesz dotykać Mnie z tyłu.

Tutaj są maryady na wszystko i jeżeli nie obserwujecie tych maryad czy tych granic, wtedy macie skłonność by je przekraczać, pomimo faktu, że jesteście czyści.

I możecie niepotrzebnie stworzyć problem. Dam bardzo dobry przykład Shri Mahaviry, który był inkarnacją Bhairavy. Bhairava sam wziął na siebie tę pracę, a dla Bhairavy: “Czym jest ubiór? Czym jest strój?” Mam na myśli, że On jest osobą; dla niego cały świat jest Jego strojem, wszystkie strony są jego jego ubiorem, On jest digambara. Dla Niego, nic to nie znaczy, On jest taki niewinny. On Sam w Sobie jest absolutną niewinnością. A niewinność, która jest destrukcyjna, która będzie niszczyć, tylko poprzez niego dostajecie raka, gdy zaczynacie się źle zachowywać.

Więc to jest taki prosty człowiek jak On, w tym sensie, że On nigdy nie wiedział co to jest nieczystość. On nie wiedział czym był grzech. Taka osobowość przybyła na tę ziemię, by nauczać ludzi by byli niewinni, by byli dharmiczni, by byli dobrzy.

A teraz ten osobnik pewnego razu musiał pójść do lasu, gdzie połowa jego odzienia została w strzępach w krzakach. Więc musiał ją odciąć i pozostał z połową ubrania.

A kiedy wyszedł na obrzeża wioski, spotkał osobę, którą w rzeczywistości był Shri Krishna, który próbował Go przetestować. Właśnie tam przybył i powiedział: “Dlaczego miałbyś mieć jakieś szaty? Nie ma potrzeby, a ja jestem istotą ludzką, nie mam na sobie ubrania. Więc Ty jesteś Bogiem, Ty Jesteś Inkarnacją, więc czemu nie miałbyś oddać Mi swojego ubrania?” On powiedział: ”W porządku, weź je” Oddał część, którą miał. I w ten sposób, przez krótki czas, On był bez ubrania – bardzo krótko.

Ale ludzie to wykorzystują i czynią Go nagim i wszystkie jego prywatne części obraźliwymi. To wszystko co oni robią jest nonsensem. Teraz wiele osób pyta Mnie: “Jak to jest, że ci dżiniści pozwalają sobie na nagość i wszystko to?“ To wszystko jest absurdalne, to nie ma nic wspólnego z Mahavirą. Nikt nie jest Mahavirą stając się nawet nagim, nawet na krótką chwilę. Więc czemu oni mieliby to robić? Ponieważ każdy próbuje znaleźć lukę tylko po to, by ukryć swoje własne słabości. I wszystkie takie słabości mówią o potomstwie. Teraz to zaszło tak daleko, że oni nie mogą zrozumieć, iż Shri Mahavira – On był digambara, był osobą, która nie potrzebowała żadnego odzienia. Wciąż, żeby tylko utrzymać [samayachar], On nosił swoje odzienie i potem też, ale na krótką chwilę, On oddał swoje ubranie. Ale to nie oznacza, że stał się nagi publicznie i zdjął swoje ubranie i wszystko to, tego to nie oznacza. On nie tylko szanował społeczność i wszystko to, ale również szanował swoich rodziców, by od tego zacząć, zanim stał się prawdziwym sanyasinem.

On szanował swoich rodziców i powiedział: „Teraz nadszedł dla mnie czas, aby porzucić to doczesne życie. Zagłębiałem się w sprawach świata i muszę pójść w sanyasę”. Nie znaczy, że nie był sannyasinem, był - ale znaczy to, że doczesne życie swoich rodziców i innych ludzi, musiał opuścić. Ponieważ, jeżeli masz się czasami zagłębiać w to życie – jak w tradycji hinduskiej, w pewnym wieku, mówią, że w 75 roku życia musisz przyjąć sannyasę. W tym sensie, że twoja rodzina, twoje dzieci są ustabilizowane, nie ma problemów, więc ty musisz przyjąć sannyasę. Ale po to, mądrość musi być gromadzona w młodym wieku; w przeciwnym wypadku, na starość wciąż nie ma mądrości, i wy zachowujecie się jak młody człowiek w wieku szesnastu lat – wtedy lepiej jest dla was nie przyjąć sannyasy.

Więc całe zrozumienie o życiu w Indiach, musi być bardzo subtelne. I by zrozumieć tych wielkich, wielkich ludzi, musicie być trochę więksi niż jesteście. Jeżeli jesteście tylko błotem, jak macie dojrzeć całość? Nie możecie. Więc musicie usunąć to błoto z waszych oczu.

To bardzo powszechna cecha na Zachodzie, albo oni są podejrzliwi, albo oni są ”zamieszani”, nie ma nic pomiędzy. Są albo ludzie podejrzliwi wobec innych albo są ludzie, którzy w to wchodzą, więc miejcie to [niesłyszalne]. Pierwsza rzecz, której muszę żądać, ponieważ teraz jesteście pierwszymi Sahaja yoginami, którzy przybyli po raz pierwszy do Indii, gdzie ziemia naszego kraju jest pełna rytmu Shri Ganeshy. Siedzicie na niej, musicie ślubować: “Ja ustanowię mojego Ganeshę”. Nie martwcie się o innych, o uwagę na innych. ”Ja ustanowię mojego Ganeshę i niech ta Matka Ziemia da mi pełną siłę, aby ustanowić mojego Ganeshę”. To jest bardzo ważne ponieważ, dopóki wasz Shri Ganesha nie jest ustabilizowany, nie możecie być połączeni z całością. Jak również nie możecie mieć radości, ze swojego Ducha. Będziecie na wpół upieczoną osobowością, którą nie powinniście być. Jak dotąd, możecie zobaczyć, że zachodni Sahaja yogini są ekstremalnie gorliwi i biorą rzeczy bardzo poważnie, dochodzą do tego. Ponieważ oni wiedzą, że jeżeli mają mieć radość, muszą to wypracować.

Więc jeśli chodzi o was, musicie dokonywać wglądu wewnątrz siebie, a jeśli chodzi o innych to macie tylko widzieć ich dobre strony. Zawsze dostrzegajcie dobre strony, nie złe strony. Inaczej stworzycie sobie problem, i nadejdzie dzień, że odejdziecie z Sahaja Yogi. Tak się stało z wieloma, którzy próbowali tych rzeczy. I oni są poza, całkowicie poza Sahaja Yogą. Jeżeli macie być w Sahaja Yodze, to musicie zrozumieć, żeby być jednym z całością, starajcie się o siebie troszczyć. Inna rzecz, którą wam powiedziałam, to to, że w każdym kraju muszę mieć kogoś na kim mogę polegać. Właśnie tak jak Shri Ganesha, polegam na Nim w wielu sprawach; On dba o wiele spraw, tak samo, w każdym kraju, muszę tam kogoś mieć. Nie lubię, jak cały czas narzekacie na osobę, z którą jestem w kontakcie. Nie macie ich korygować. Mówiłam wam ze sto razy: “Nie poprawiajcie tej osoby“.

Wiem, bo jestem w kontakcie, wiem o tej osobie; wy jej nie znacie. Wiem wszystko o tej osobie. Ja mogę korygować tę osobę. Ale byłam zaskoczona, w Londynie również, pewni ludzie przyszli i powiedzieli coś dziwnego o innych i byłam zdziwiona, że oni myślą, że ja nie wiem. Ja znam każdego i wszystko. Wy zostawcie to Mnie. To nie wasze zadanie robić takie rzeczy i to jest bardzo mierne podejście do Sahaja Yogi, skrajnie mierne. I jeżeli macie zamiar być mierni, to nic na to nie poradzę.

Ale nadejdzie dzień; być może będziecie musieli odejść z Sahaja Yogi. To jest pierwsze ostrzeżenie, które chcę wam dać, ponieważ teraz udajemy się do środkowego obszaru Maharashtry.

Zobaczycie, że kobiety i mężczyźni nigdy nie siadają razem w Maharastrze, oni siedzą osobno, oni trzymają się na dystans; musimy nauczyć się takich rzeczy. Na Zachodzie jesteśmy bardzo otwartymi ludźmi, to jest w porządku, możecie być otwarci, są metody i sposoby, jak jesteśmy otwarci, jak utrzymujemy dystans. Na przykład: będę znacznie bardziej otwarta z synem Sanghve, doktora Sanghave, ale z nim będę bardziej na dystans. To jest styl, że dama, ze starszymi, ona musi utrzymywać dystans. A mężczyzna, musi utrzymywać dystans z pokoleniem młodszym od niego. To jest system, poprzez który ten kraj wypracował swoją niewinność i my wszyscy powinniśmy starać się za tym podążać. Trzymajcie dystans z paniami, które są młodsze od was. I trzymajcie dystans z panami, którzy są starsi od was. Mam na myśli, że tam nawet osiemdziesięcioletni pan poślubia osiemnastoletnią dziewczynę. To taki pokręcony stan rzeczy, gdzie wy nie możecie rozmawiać o tych sprawach.

Ale tu, kiedy próbujemy uporać się z naszym chaosem, naszymi błędami, powinniśmy starać się przywrzeć do pewnych wzorców, które pomogły naszemu życiu społecznemu – to jest znacznie lepsze. I zrozumieć, dlaczego to życie społeczne jest lepsze, jest takie, ponieważ Shri Ganesha jest ważny. Tam, gdzie nie ma Shri Ganeshy, odkryjecie, że nawet Sahaja Yoga nie działa.

Mówi się, że na północy Indii, Shri Ganesha nie jest tak bardzo czczony. Więc muzułmanie przybyli, a gdyby tam był Shri Ganesha, to oni mogliby walczyć. Oni zaakceptowali islamską kulturę i kiedy ta kultura przyszła od Nawabów i wszystkich takich lubieżnych ludzi, wszystko to się rozprzestrzeniło. Nie do takich rozmiarów, wciąż mogę powiedzieć, że jest tam poczucie czystości w ludziach z Indii i my wszyscy powinniśmy mieć to poczucie czystości. Ale najważniejszą rzeczą jest, żebyście w waszym sercu, w waszym umyśle, nie pozwolili, by przychodziły dziwaczne pomysły. Po pierwsze, obserwujcie co jest w waszym umyśle. A on będzie wam podsuwał idee typu: ”Ten człowiek nie jest dobry, tamten człowiek nie jest dobry”. Po prostu nie słuchajcie tych rzeczy, słuchajcie tylko siebie: ”Gdzie ja jestem?

Co robię? Co zrobiłem dla Sahaja Yogi? Moje wibracje – czy są w porządku? Czy pomagam innym? Gdzie jest moja uwaga?” Uwaga powinna być: ”Co robię z tym, co Matka mi podarowała?”

Więc dzisiaj jest bardzo wielki dzień, wszyscy musimy się modlić do Shri Ganeshy by dał swoje błogosławieństwa, ponieważ On jest źródłem radości, On jest Chrystusem, On jest w waszym sercu, rezyduje jako Duch, więc On jest tą niewinnością, którą macie osiągnąć. I to jest początek istnienia Shri Ganeshy, który ewoluuje tutaj na głowie widzicie tu na [niesłyszalne], gdzie staje się Aum. Więc ten sam Shri Ganesha ostatecznie staje się Aum w nas. By mieć najczystszą formę radowania się waszym Duchem, musicie starać się zobaczyć, że ustanowiliście naszego Shri Ganeshę. I niech każdy podąża za odpowiednim wzorcem, nie próbujcie korygować się nawzajem. To bardzo zła postawa w Sahaja Yodze i jest bardzo szkodliwa dla wzrostu Sahaja Yogi.

Ktokolwiek tego spróbuje, jest wyrzucany z Sahaja Yogi niezwłocznie, w ten czy inny sposób. Widuję również ludzi dostających raka i oni Mnie pytają: “Matko jak to jest, że praktykujemy Sahaja Yogę i teraz dostajemy raka?” Z powodu tego nonsensu. Nie próbujcie iść przeciwko innym Sahaja yoginom; musicie ich szanować, oni wszyscy są święci. I szanujcie starszych Sahaja yoginów, ponieważ oni tam byli, wy musicie się wiele nauczyć. Oni pracowali bardzo ciężko, by ustanowić Sahaja Yogę.

Więc mam dziś bardzo prosty komunikat, że tego dnia Shri Ganeshy, wszystkie moje dzieci, które urodziły się jak Shri Ganesha, na jego podobieństwo, powinny stać się dynamiczne jak On, niewinne jak On, wielkie jak On, pracujące 24 godziny na dobę. To małe Dziecię pracuje cały dzień i noc by dać wam to źródło radości.

Niech was wszystkich Bóg błogosławi.