Mowa do joginów: "Ego i jego skutki" 27.10.1985 New Jersey, USA

... wam o kulturze Sahaj, dobrze? Kultura Sahaj, wyjaśnię wam, czym jest kultura Sahaj, w której musicie wzrastać. Gdzie jest Judy, ona jest tam, wejdź, wejdź, pozwól im usiąść.

Wtedy wczoraj wieczorem rozmawiałam z wami o ego. O tym, jak przejawia się ego i jak ciężko jest wydostać się z ego. To łatwe wydostać się z uwarunkowań superego, ale bardzo trudno wydostać się z ego, ponieważ ego atakuje innych, ale wam zupełnie nie sprawia kłopotów a wy lubicie tę agresję.

Dziś chcę wam opowiedzieć o tym, jak ego historycznie w tradycji torturuje ludzi wokół. Więc zobaczycie manifestację tego ego, a wtedy będziecie wiedzieć, że jeśli gracie jakąkolwiek rolę za pomocą waszego ego, to możecie być nieodłączną częścią tej niszczącej siły.

Zacznijmy od tego, zobaczcie teraz, kiedy to ego zaczęło się w ludziach powiększać. Przede wszystkim zobaczcie, że zaczęło się rozwijać jako ochrona, więc przysadka, która jest w nas, zaczęła rosnąć, gdy podnieśliśmy głowę, właśnie tak. Kiedy byliśmy zwierzętami, nasza głowa była tak, w tym czasie szyszynka, jak się ją nazywa, była bardzo silna.

Mówią, że w istotach ludzkich szyszynka nie działa. To nieprawda, ona działa, ale oni nie wiedzą, w jaki sposób ona działa. Więc ta szyszynka w nas była bardzo aktywna, kiedy byliśmy na poziomie zwierzęcia. Ale kiedy podnieśliśmy głowę, zaszła w nas przemiana chemiczna w tym sensie, że nasz mózg zaczął rosnąć w piramidę, o której wam mówiłam, jak z równoległobocznymi siłami i wszystkim tym, zaczął rozwijać się w piramidę i kiedy stał się taki, widzicie, ponieważ najpierw to było tylko ciałem szyszynki opiekującym się superego, aż do królestwa zwierząt, aż do królestwa, w którym pewien rodzaj zwierząt stał się bardziej zhumanizowany, wtedy ego zaczęło rosnąć...

...tylko ludzie mogą używać materii. Jedynie ludzie mogą użyć materii, nie zwierzęta. Zwierzęta nie mogą używać materii dla własnych celów. Kiedy zaczęli wykorzystywać materię, ego zaczęło się rozwijać i rozwinęliśmy to, co nazywacie "piramidą naszego mózgu", zaczynamy tym sposobem rosnąć, bardziej i bardziej i bardziej. Ale kiedy osiągnęło swój wzrost, zaczęliśmy bardziej używać naszego ego, nie zatrzymaliśmy się na tym punkcie. Zaczęliśmy przemieszczać się na drugą stronę, więc

[ego]

przemieściło się w dół i zakryło ją [szyszynkę], całkowicie ją zakryło w ten sposób. Dlatego mówi się, że szyszynka w ludziach nie działa, [ale ona] działa bez wątpienia, działa.

W wyniku tego, kiedy ego rosło ludzie czuli się niezwykle pewni siebie. Ta ideologia "No i co w tym złego?" zaczęła się dawno temu, od czasu Kolumba, jak już powiedziałam, gdyby Kolumb przybył do Indii, nie zobaczyłby Mnie tutaj [mówiącej do was], wykończyłby tam wszystkich Hindusów, nie on, on był bardzo miłym człowiekiem, ale ci, którzy za nim podążali. W ten sam sposób ego zaczęło niszczyć ludzi i oni [agresorzy] mieli koncepcję zwyciężania, i zabijania ludzi, okupowania ziem, okupowania terytoriów, gromadzenia bogactw. Kontynuowania wciąż i wciąż i wciąż, na tym poziomie. Od tego zaczęli.

Kiedy system małżeństwa rozpoczął się we właściwy sposób, ponownie agresja zaczęła się na kobietach, a teraz kobiety są agresorkami mężczyzn, tak jak to, wszystko stało się tak agresywne. Ale kiedy jesteś agresorem, nie widzisz, że atakujesz, to jest problem egoistycznej osoby. Chociaż może on być poszukiwaczem, choć może być bardzo szczerym poszukiwaczem, ale jeśli jest w obszarze ego, nigdy nie czuje swoich własnych bloków, ponieważ ego jest pomiędzy, stanowi rzeczywistość. Więc nie widzi własnych bloków, nie widzi jak atakuje innych, i nie widzi jak krzywdzi innych, sprawia innym kłopoty, torturując innych i taka osoba może być niezwykle arogancka, ekstremalnie jak to nazywacie "dusząca".

To samo dzieje się również, gdy dostajecie raka, kiedy zachorujecie na raka, co się dzieje, to zaczyna się od lewej strony bez wątpienia. Ale kiedy przychodzi do osoby, to ona staje się podatna na chorobę lub chorobę, w której osoba jest agresywna. Komórki ciała najpierw rozwijają agresję; nazywamy je "złośliwymi". Kiedy taka komórka wchodzi w kontakt z innymi, to one również stają się złośliwe. W ten sposób rozprzestrzenia się złośliwość, i kiedy to się rozprzestrzenia, to co się dzieje? Przypuśćmy, że w nosie są pewne komórki, które się stają złośliwe; więc zaczynają przeszkadzać we wzroście innym narządom. Nos będzie rosnąć w ten sposób, nie na zewnątrz, ale wewnątrz.

Więc oni atakują, zaczyna się agresja i oni kompletnie tracą kontrolę nad całością, ponieważ tam nie ma koordynacji z całością, nie widzą, że całość musi rosnąć razem i nie tylko nos, nie tylko oczy, czyż nie? A to zerwanie z kolektywnością jest pierwszym znakiem, gdy odkrywacie, że Sahaja yogin zachowuje się w dziwny sposób, że jeśli odchodzi od kolektywności, wtedy jest niczym innym jak egoistą, nie ma co do tego wątpliwości; przez jakąkolwiek sprzeczkę, przez cokolwiek.

Ale osoba, która ma superego, będzie się trzymać kolektywności; będzie próbowała być bardzo blisko ashramu, będzie bardzo blisko nas, wokół [ashramu], nawet jeśli powiemy "nie chcemy", ona tam będzie, dlaczego? Ponieważ zdaje sobie sprawę z agresji a także rozumie, że może być przebiegła. Tak więc, gdy lewostronna osoba wchodzi do ashramu, będzie bardzo miłą, cichą, słodką osobą. Ale [obce] byty, buce w niej, będą atakować ludzi w przebiegły sposób, będą torturować, lecz tych ludzi można bardzo łatwo wyleczyć, ponieważ sprawiają kłopoty i torturują samych siebie.

Ale tym, którzy są egoistyczni, będzie bardzo ciężko się z tego wydostać. Właśnie dlatego mówiłam o ego wczoraj i dziś. Oni mogą zobaczyć całą agresję, która manifestuje się przez ideę "co w tym złego?" Mówiłam na temat chemikaliów. Jak odkryliście te chemikalia? To przez wasze ego, przez waszą naukę. Teraz, jeśli nauka nie jest powiązana z Bogiem lub z całością, wtedy trwacie w takim postępowaniu, a potem możecie produkować bomby wodorowe, możecie produkować te okropne chemikalia, jak to, co nazywacie "niebezpieczna głupota". Wkraczacie w każdą sferę, każde miejsce i osiągacie nad tym władzę, ale wtedy nie wiecie do czego ten [wytwór] jest zdolny. Przypuśćmy, że teraz robicie komputery, przypuśćmy, to jutro te komputery was zjedzą.

Muszę wam teraz powiedzieć o nowej chorobie, którą odkryłam w ludziach, polegającą na tym, że ich świadomy umysł obezwładnia ich. Był taki człowiek, bardzo egoistyczny, nie wierzył również w Boga, on jest Hindusem i miał wypadek. Jego żona jest lekarzem, ona jest moją przyjaciółką i przyprowadziła go do Mnie. W mojej obecności wstał i odszedł [bez problemu]. Ale sam, kiedykolwiek chciał tego świadomie dokonać, nie mógł nawet podnieść nogi. Możecie sobie wyobrazić? Więc dla egoistycznych ludzi nadchodzi teraz nowa choroba, że świadomie nie są w stanie niczego zrobić. Nie mogą zrobić niczego. W ten sposób to nadejdzie, obiecuję wam teraz, czy też ostrzegam was teraz.

Tak, jak ostrzegałam ludzi, którzy schodzili na lewą stronę, że będą mieć straszną chorobę, a to jest nowa choroba dla wszystkich egoistów, że świadomie nie będą w stanie się poruszyć, będą niemi, będą jedynie siedzieć, ich ego przejmie władzę. Urodziliście się w bardzo niebezpiecznej erze, musicie o tym wiedzieć. Zostaliśmy umieszczeni w niepewnym czasie, albo osiągniecie Boga albo idziecie do piekła, nie ma nic pomiędzy. Tak więc nowa choroba nadejdzie bardzo szybko, nie ma w tym szaleństwa, niczego, będziecie całkiem czujni, ale nie możecie poruszyć rękami, cały wasz system nerwowy odmawia działania. To nadejdzie, wkrótce to się zamanifestuje.

Widzieliście, że egoistyczni ludzie zachowują się jak Hitler i jemu podobni, i oni zniszczyli świat i wyrządzili tak wiele szkód naszemu systemowi wartości. W subtelny sposób mówimy, że wszystkie te przejawy 25-ciu lat całego tego okropnego piekła, które stworzyli dla nas z powodu wojen, przez wojny. Ale te wojny i temu podobne rzeczy, nawet jeśli unikniecie, przez przypadek unikniecie, wciąż, jeśli jest tam ego, ono zamanifestuje się samo. Jeśli wy unikacie tego na zewnątrz, zamanifestuje się wewnątrz i wtedy przekonacie się, że po prostu nie możecie się ruszyć. Nie możecie mrugać, nie możecie spać, nie możecie poruszać rękami, nawet teraz ludzie nie mogą spać, wielu z nich.

A Ja nie chcę, aby Sahaja yogini cierpieli z powodu tej strasznej choroby, bo ludzie z Zachodu są bardziej podatni na tego typu rzeczy. Sahaja yogini, którzy próbują się wydostać z kolektywności, którzy domagają się uznania swojego ego w imię buców lub czegokolwiek, powinni zrozumieć, że jest w nas 99% ego i temu ego trzeba stawić czoła. "Och, mam ego, czuję się winny", wtedy z powrotem wkładacie je tutaj [w lewe Vishuddhi]. Nie tędy droga. To nie jest właściwy sposób postępowania.

Dzisiaj jesteście bardzo aktywni, bardzo ciężko pracujecie, robicie to, jutro odkryjecie, że będziecie po prostu unieruchomieni. Nie możecie się ruszyć a w tym kraju ludzie nie troszczą się nawet o osoby, które są w porządku, a wy staniecie się jak starcy, którzy nie mogą się ruszyć. Którzy wszystko widzą, wszystko wiedzą, którzy są świadomi. W bardzo młodym wieku to się stanie, najmniejszy wypadek, najmniejsze zakłócenia, po prostu sprowadzą was do tego obszaru, w którym będziecie zupełnie jak siedząca niema osoba. Nie możecie poruszyć palcem, nie możecie czegokolwiek trzymać.

Nie będziecie w śpiączce, śpiączka przytrafia się ludziom, którzy biorą pigułki i środki, aby przejść na lewo, jak narkotyki i takie rzeczy, które przesuną was na lewo. Ale ci, którzy są prawostronni, nie będą w śpiączce, to jedna rzecz, to klątwa, będziecie widzieć wszystko, będziecie czujni, będziecie wiedzieć wszystko, ale nie będziecie mogli nawet odwrócić głowy. Uwierzcie Mi. To pojawia się bardzo szybko. Możecie mówić albo nie mówić, to może przybrać taką formę, powoli, powoli, będziecie odkrywać, że wasze ciało będzie unieruchomione. Ludzie nie rozumieją, jakie niebezpieczeństwa może nieść ego. To nie jest tak bardzo agresją manifestującą się na zewnątrz, ponieważ przechodzi w lewe Vishuddhi i to lewe Vishuddhi stworzy tą okropną chorobę.

Teraz jest bardzo ważne, aby zrozumieć, w jaki sposób kontrolować nasze ego. Po pierwsze musicie pisać swoje imię i bić siebie butem 108 razy. Po drugie, dyscyplinujcie siebie, poprzez dyscyplinę wstawajcie rano, medytujcie z prawą ręką w kierunku zdjęcia, lewą ręka w tę stronę.

W ogóle nie używajcie światła, nie używajcie słońca, wcale nie wychodźcie na słońce. Słońca należy unikać, trzymajcie się księżyca, czytajcie książki, które opisują moce Mahakali, które są na lewej stronie, nie czytajcie takich książek jak te Avadhuty. Nigdy nie należy go czytać, ponieważ myślicie, że jesteście Avadhutą, i widzicie, powiedział: "Jestem wszechobecny, jestem tym", osoba zaczyna się czuć "Jestem tym". Czytałam księgę Avadhuty, powiedziałam, że ta książka pokazuje, co złego stało się z naszymi inkarnacjami. Co poszło nie tak z naszymi Inkarnacjami to to, że w ogóle nigdy nie znały ludzi, na jakim są poziomie. Przyjdźcie i powiedzcie im: "Jestem bez formy i formą, jestem tym i tamtym", co z tego? Jeśli tak, w porządku, jestem współczuciem, jestem miłością, jestem pokojem, jestem tym ... Więc co? Jak wypełniasz te naczynia, musisz zejść na poziom ludzki, czego oni nie próbowali, i dlatego to wszystko jest zmarnowane, myślę wręcz przeciwnie.

Wszyscy myślą, że jestem Bogiem, jestem Brahmą, Shivo Ham skończone, a potem kłócą się między sobą, ten wzrost, ta dojrzałość nie nadeszły. To jest bardzo płytkie, cała rzecz staje się bardzo płytka, stajecie się płytką osobą, i żyjecie z tym, więc pierwsza praktyczna rzecz, o której wam mówię, bijcie siebie butem i "nie jestem tym", od tego musicie zacząć w pierwszej kolejności, mówiąc sobie, że jeśli jesteście poszukiwaczami, prawdziwymi poszukiwaczami, uczciwymi poszukiwaczami, doradzam wam ten sposób, abyście obserwowali siebie w lustrze i mówili sobie: "Teraz panie Ego XYZ, wyniesiesz się stąd, wiem kim jestem, a ty się wynoś".

Przegońcie go, śmiejcie się z siebie, uśmiechajcie się do siebie, miejcie z siebie uciechę. To jest najlepsze, i nigdy nie poczujecie się zranieni, jeśli ktoś powie "jesteście egoistyczni", a następnie powiecie "wiem, wiem", jeśli wiecie, że jesteście egoistyczni, to dlaczego w tym trwacie?

Ego manifestuje się na tak wiele sposobów. Przez wasze oczy, uszy, usta, przez wasz nos, każdą drogą, ponieważ idziecie przeciwko Bogu, to znaczy działacie przeciwko kolektywności, ponieważ idziecie przeciwko Shri Krishnie, przeciwko waszej czakrze Vishuddhi.

To jest pierwsza rzecz, która się manifestuje, w dzisiejszych czasach nikt nie bije ludzi w ten sposób, staliśmy się subtelniejsi w przejawianiu naszego ego; używamy tej część, nie rąk.

Możliwe, że okazujecie temperament przez wasze oczy, albo możecie flirtować poprzez wasze oczy. Stajecie się cudzołożni. Dlatego Chrystus powiedział: "Nie bądźcie cudzołożni". Więc teraz to dobrze, że AIDS może się przenosić przez łzy. To jest dobre. Mieliście zwyczaj całować ludzi, w porządku, całujcie teraz. Nikt teraz nie będzie całować. Do tej pory używaliście całej swojej czakry Vishuddhi, by wyrazić cały brud. Teraz brud się uzewnętrznia.

Tak więc, w drugim etapie, kiedy rozumiemy, że dzieje się to za pośrednictwem Vishuddhi, którym jest ta Ameryka, wyrażamy siebie, nasze ego, więc co powinniśmy zrobić? Po pierwsze, przestańcie mówić w sposób, w jaki ludzie tutaj mówią, Widzicie, właśnie zaczęliście otwierać usta w ten sposób, i trwacie w tym, a drugi mówi, kiedy tylko im coś powiecie to oni wyskakują z całą wiedzą im dostępną, oni wszystko wiedzieli, od A do Z i nie wiecie, gdzie jesteście. Jak przestać mówić? Powiedziałam coś praktycznego, przyniosę wam orzechy betelu, które nawibruje, włóżcie je do ust i wyjmijcie, gdy będziecie musieli mówić, inaczej trzymajcie je tam, to Shri Ganesha, nie wyjmujcie tego. Przestańcie gadać. Jeśli przestaniecie mówić, wasza obłuda odejdzie.

Jesteśmy hipokrytami poprzez naszą twarz, wszystko działa przez Vishuddhi. Teraz zobaczcie, osoba, która jest niezwykle agresywna, może grać kogoś bardzo, bardzo słodkiego, jeśli mają was wykorzystać lub zarobić na was. Oni mogą grać, działać; całe aktorstwo przychodzi poprzez Vishuddhi. Wtedy gracie, "ty jesteś bardzo łagodną osobą, jesteś bardzo dobra", ale nie jesteście, jesteście agresywni. Więc w tym celu musicie wiedzieć, że mówienie mniej zmniejszy o 50% waszą hipokryzję i aktorstwo o 50%. Teraz wciąż pozostało 50%, co teraz zrobić z tymi 50%? 50% to punkt, w którym musimy wiedzieć, jakie inne czakry są odpowiedzialne za przejawianie się ego. Jedną z nich jest Hamsa, Hamsa jest bardzo ważna. Używamy jej, gdy chcemy pokazać nasz temperament, obojętność. Wtedy człowiek myśli: "O Boże, co ja zrobiłem tej osobie?"

Oto jak pokazujemy nasz temperament, przez cały czas robimy to w ten sposób. To jest Hamsa i właśnie dlatego mamy używać prostej rzeczy nazywanej ghee lub coś oleistego do uszu, do nosa, do oczu ‘kajal’ i dla tej części również. Musimy umieścić trochę ghee w gorącej wodzie lub mleku i spożywać, aby uspokoić nerwy i zmiękczyć wasze Vishuddhi, a także zmiękczyć to, co nazywacie otrzewną, bo ona jest wyściółką. Wyściela, tak jak my zmiękczamy nasze palce i dłonie, kiedy są wysuszone, musimy je zmiękczyć. Nacierajcie ghee tutaj, i tutaj, olej tutaj, olej tam, na głowie. We współczesnym stylu jest, aby nie nacierać głowy olejem, staniecie się łysi. Wyłysiały gentleman, oczywiście możecie wciąż zachowywać się jak Yull Brinner, ale on zmarł na raka. Jego siostra jest naszym uczniem, a wy będziecie rozwijać zabawny styl fryzur, wszystko to i z tej nowoczesnej mody zaczęło się to, aby nie używać żadnego oleju, nie wiem skąd to przyszło. Oni również mówią dzieciom "nie zakraplajcie żadnego oleju do uszu", to lekarze, oni chcą tworzyć pacjentów, nie słuchajcie ich. Przed wyruszeniem w podróż lub gdziekolwiek, zakraplajcie olej do uszu, a do nosa nie olej, ale ghee, i kontrolujcie swoją otrzewną poprzez waszą czakrę Hamsa, to jest bardzo istotne.

Ta czakra naprawdę bardzo wam pomaga, aby się uspokoić. Teraz w Sanskrycie, a także w wielu językach potocznych, ghee nazywane jest "mir" a "sneha" to miłość. Neha to także miłość. Musicie więc nałożyć tam olej tak, żeby tarcia były mniejsze. Wiemy, że w naturze, aby zmniejszyć tarcie, aplikujemy olej. Powiedzmy, że mamy wodować statek, Ja wodowałam, więc wiem jak to jest, musieli natłuścić element, i jak tylko to dotknęło statku, statek spłynął tak gładko do morza. Pięknie się rusza. W Indiach podkładają banany, ponieważ banany są bardzo łatwo dostępne, więc podkładają banany. Tutaj oni używają smaru, na przykład w Anglii używają smaru. W ten sam sposób musimy smarować samych siebie.

Nasz język, nasz ton, nasza mowa musi być nasmarowana, nasmarowana miłością a miłość jest czymś tak potężnym, że może przyciągnąć każdego, nawet Hitlera. Kiedy rozmawiacie z kimś lub coś mówicie, to powinno być powleczone czekoladą Miłości, wtedy możecie zaaplikować nawet olej rycynowy, Ja tak robię. Tak więc wszystkie te rzeczy należy rozumieć [Vedy] mówią, że nie powinniśmy stać się głupcami, tak jak inni ludzie. Jesteśmy yoginami i musimy mieć idealne życie, które samo manifestuje się we wszelkiego rodzaju dynamice i nie marnujemy tego wielkiego błogosławieństwa, które otrzymaliśmy.

Teraz kolejną czakrą, która zawsze się blokuje jest Agnya, czakra Agnya. W czakrze Agnya musimy stać się świadomi bez myśli, ale nie możemy. Jeśli obserwujecie swoje myśli, będziecie wiedzieć, że myślimy głównie o ludziach, którzy nas skrzywdzili, którzy sprawiali nam kłopoty, czasami mamy również przebłysk czegoś dobrego. Czasami myślimy także o dobrych ludziach, czasami, ale zwykle myślimy o ludziach, którzy nas skrzywdzili, krzywdzą nas, to, tamto. Chrystus, który jest Shri Ganeshą i który ma wszystkie moce by nas zabić i aby z nami skończyć, i całkowicie nas zniszczyć, dał nam najpotężniejszą broń, którą jest wybaczenie. Więc tutaj mantrą jest "wybaczam" i musicie dopilnować tego, żeby wybaczać innym.

Ktoś coś mówi, wybacz. Kiedy przebaczacie, Bóg przejmuje [ten problem]. I On wie, jak sobie z tym poradzić lub zaprzepaścić, aby robić z tą osobą cokolwiek zechce. To nie wasza praca, wy po prostu wybaczcie, więc musicie dać mu bilet; idź do Boga, wybaczam ci i musicie wybaczyć, i to jest coś, czym możecie bardzo uradować waszą czakrę Agnya i podnieście swoją Kundalini ponad nią mówiąc: "Wybaczam, wybaczam, wybaczam", trzy razy i musicie powiedzieć mantrę Nirvichara, brak myśli. Agnya to ta, która przynosi wam myśli, to dlatego Chrystus był taki wrażliwy szczególnie w kwestii oczu: "Nie będziesz miał cudzołożnych oczu", spróbujcie koncentrować swoje oczy na Matce Ziemi przez jakiś czas, Ona będzie wchłaniać, więc wasza uwaga nie stanie się tak chwiejna, stanie się skoncentrowana, wyrównana i zrównoważona. Kiedy to się stanie wasze oczy stają się tak potężne, nawet jeśli patrzycie na kogoś, możecie wyleczyć tę osobę, a niewinność będzie pojawiać się w waszych oczach, nie będziecie mieć pożądania i chciwości. To bardzo niebezpieczne, jak ludzie się tutaj bawią, nie znałam tego wszystkiego co ludzie robią, ale widziałam to na Zachodzie, to znaczy, każdy patrzy na każdą dziewczyną, czym jest ta niekończąca się pogoń za radością? Po co kierować wzrok na coś, co nie przynosi wam radości. Każda dziewczyna szuka mężczyzny, dziewczyna patrzy na każdego mężczyznę, co to za nonsens? Po co marnować swoją energię.

Zawsze patrzę do wysokości ok 3 stóp, widzicie tam wszystkie kwiaty, wszystkie dzieci. Któregoś dnia ktoś zapytał Mnie: "Nie masz ochoty patrzeć na przystojnego mężczyznę?" Odrzekłam: "Nie jestem głupia, patrzę na najprzystojniejsze rzeczy, na wysokości 3 stóp". Powiedział: "Musisz być głupia, aby na to patrzeć". Nie jestem, to właśnie to. Więc to wam da ogromną ilość energii, ponieważ zachowujecie całą swoją energię poprzez swoje oczy. Oczy są oknami tej Mocy. Jeśli spróbujecie to zachować, wszystko będzie w porządku, w przeciwnym razie, jak teraz mówią "oszczędzaj wodę, bo zmarnowałeś swoją wodę, więc teraz oszczędzaj wodę". Ale kiedy wasze oczy są niewinne w tej obfitości błogości, radujecie się tą błogością, nie musicie patrzeć na każdego, nie musicie nic mówić, po prostu się radujecie, po prostu czujecie radość hojnie na was spływającą. Ponieważ ego zniknęło, widzicie, że agresją jest patrzeć na wszystkich w tamten sposób, to agresja.

Znałam ludzi, którzy hipnotyzują kobiety, hipnotyzują mężczyzn. Znałam takie kobiety, widziałam na imprezach, widziałem buce wychodzące z tych kobiet i one patrzą na mężczyzn, i on zostaje całkowicie oczarowany, zakochuje się w tej kobiecie, dopóki nie stanie się jak żebrak, ona go po prostu linczuje. To jest prostytucja, mężczyzn lub kobiet, to okropna rzecz, to brud w waszych oczach, więc utrzymujcie swoje oczy stabilne, próbujcie je uspokoić, jeśli próbują iść tu i tam powiedzcie im: "Patrzcie tam, tam jest Matka Ziemia, Ona jest tą, która daje nam wszystkie piękne rzeczy, patrzcie na nią", a wtedy piękno tej Matki Ziemi pojawi się w waszych oczach. A czystość i niewinność oczyści innych, oto jak powinno być. Aby więc walczyć z tym ego, trzeba być przygotowanym i trzeba mieć odpowiednią siłę woli, ponieważ ego całkowicie zabija moc woli człowieka. A człowiek, który jest egoistą, pozostaje bez mocy woli. Robi to, co podpowiada mu ego. Może mordować ludzi, może być bardzo gwałtowny, cała przemoc w Ameryce pochodzi z manifestacji ego. Ponieważ nie ma szacunku dla prawa, dla praw człowieka, również prawa Boskiego, tak zachowują się ludzie narażając się na nieuleczalne choroby, coś strasznego.

Osoba, która nie jest egoistyczna, nie zachoruje na raka. Musicie być egoistyczni, aby zachorować na raka, chociaż jest to choroba lewostronna, ale musicie mieć ego, podatność przychodzi przez ego i wtedy działa. Jeśli jesteście egoistyczni, jesteście podatni na raka, więc w pierwszej kolejności, jeśli przeżyjecie raka, będzie na was czyhało coś innego, zostaniecie sparaliżowani przez buce. Staniecie się jak niektórzy z tych, których widuję w telewizji, gdzie ludziom dano pewien rodzaj protezy i są po prostu niczym innym jak maszynami i poruszają rękami jak maszyny, chodzą tak, wyglądają jak istota ludzka i idą prosto w ten sposób, nic nie czują, staniecie się tacy, ponieważ ego odciąga was od emocji, i od lewej strony, a wy się stajecie naprawdę osobą taką jak maszyna, stajecie się jak maszyna.

Spotkałam pewnego dentystę, przyszedł do Mnie i powiedział Mi: "Matko, teraz nie mogę płakać, nie mogę czuć i nie czuję się źle, kiedy ktoś umiera". Zapytałam: "Więc co robisz?" "Biegam", to znaczy bieganie oznacza uciekanie przed samym sobą. Przez ile godzin biegasz? "5 godzin" z 10-ciu godzin, kiedy nie śpi traci 5 godzin, on biega, co jeszcze się stanie? A więc wszystkie te sztuczne rzeczy przyszły do ​​nas, ponieważ to jest przejaw czyjegoś ego, nawet narkotyki przyszły do ​​nas, ponieważ ktoś chciał zarabiać na nas. Wszyscy ci guru chcieli zrobić na nas pieniądze, widzicie, że są bardziej zainteresowani zarabianiem pieniędzy.

Wszyscy egoistyczni ludzie są bardzo zorientowani na pieniądze, nie mogą się z tego wydostać, każdą kwotą jaką im dacie, cokolwiek. Mam na myśli, że pobłogosławiłam ludzi tysiącami i tysiącami rupii, miliardem i miliardami rzeczy, ale nadal ich orientacja na pieniądze nie odchodzi, a potem tracą to w mgnieniu oka, tracą tak po prostu, właśnie tak, naturalnie. Ponieważ nie rozpoznają, że to jest błogosławieństwo, które otrzymali, teraz macie się tym podzielić.

Był pewien pan, który gdy przyszedł do Sahaja yogi, był naprawdę absolutnie na skraju załamania, bez pieniędzy. Z dnia na dzień stał się takim bogatym człowiekiem, i z dnia na dzień stał się taki sam. To jest przykład, przyszedł do Mnie, przyszedł do Sahaja Yogi, stał się bardzo bogaty, stał się tym wszystkim, i potem nagle stracił wszystko, a nawet Sahaja yogini zaczęli mówić: "Matko, my przyszliśmy do Ciebie na krótko", a potem oni odchodzą i stają się bardzo bogaci. Powiedziałam: "W porządku". Zobaczymy po roku, przed i po, gdzie oni teraz są? Ten człowiek stał się tak biedny, że nawet nie ma pieniędzy na autobus, więc nieszczęścia przychodzą w ten sposób i wtedy oni nie rozumieją, ale mówię wam, dopóki nie mówicie o klęskach, ludzie się nie uczą. Oni potrzebują szoku, w przeciwnym razie nie chcą wydostać się ze swojego ego, nie mogą, oni żyją z tym, nie chcą zrozumieć, że to się wydarzy, więc lepiej żeby to zrobili, kiedy widzą, że to się dzieje.

W tym wypadku, przypadek pewnego pana dał wszystkim indyjskim Sahaja yoginom wielką lekcję. Mówili: "Powinieneś przyjść do Sahaja Yogi na krótki czas i wyjść z niej, wtedy staniesz się bardzo bogaty", oto do jakiego wniosku doszli. A teraz tak nie mówią, ponieważ medium, przez które otrzymaliście Bożą łaskę, jeśli to straciliście, to straciliście. Więc nie żyjcie z pełną pewnością siebie z tym waszym straszliwym ego, bo to będzie was obezwładniać.

I tak jak widzieliście, że buce się łączą, także egoistyczni ludzie zawsze będą się łączyć. Jeśli są dwoma egoistami, zawsze będą zaprzyjaźnieni, ponieważ połączyli się, bo są dokładnie tacy sami, ale kiedy są unieruchomieni, to co się stanie? Siedzieli jak posągi, możecie zrobić z nich posągi, jaki będzie z nich potem pożytek. Nie wiem, ponieważ nie są martwi, żyją, ale nie mogą jeść, mogą patrzeć na jedzenie, ale nie mogą go jeść, ale jeśli wstrzykniecie w..., ponieważ parasympatyczny układ może działać albo sympatyczny może działać lub autonomiczny może działać, ale reszta jest skończona. Centralny układ nerwowy jest skończony. Może się to nagle komuś przydarzyć.

Zapiszcie to, dzisiaj opowiadałam wam o tej chorobie. Starajcie się trzymać w grupie, starajcie się dzielić wszystkim i nie próbujcie swoich przebiegłych, sprytnych metod. Przebiegłość to oszukiwanie samego siebie, Gregoire powiedział Mi: "Matko ta inteligencja, ludzka inteligencja jest tak inteligentna, że ​​może oszukiwać siebie". To właśnie widzę. Dlaczego chcecie oszukiwać siebie, czy jesteście szaleni? To jest to, co trzeba zrozumieć, kiedy już to zrozumiecie, to zobaczycie, że większość problemów tego świat ustąpi. W jaki sposób stworzyliście bombę atomową, w jaki sposób stworzyliście te wszystkie rzeczy?

Nauka nigdy nie powiedziała "zrób bombę atomową", nauka została wam dana dla konstruktywnej pracy, dla zaoszczędzenia czasu na medytację, a nie po to, aby stworzyć bomby atomowe, żeby was zabiły, nie, ale w pewien sposób to działa, ponieważ Ameryka robi jakieś bomby, Rosja robi jakieś bomby, jak dwa diabły będą siedzieć im na głowach, teraz nie mogą położyć rąk na przyciskach. To dobry pomysł, oni boją się diabłów, które sami stworzyli, ponieważ to jest tak przytłaczające, więc jeśli chcecie uniknąć własnego zniszczenia, wtedy uważajcie, bądźcie świadomi siebie, nie chwalcie się "ja wiem, ja wiem", nie. Jak się zachowujecie?

Niektórzy ludzie są tacy, że mówią: "Nie możemy żyć w pospolitym miejscu, nie możemy spać w zwykłym miejscu i temu podobne", to oznacza, że ​​są żebrakami, to właśnie czuję w stosunku do takich ludzi, bo jeśli jesteście królem, tak jak Ja jestem Królową, nie chcę niczego, jeśli każecie Mi spać pod tym drzewem, mogę spać, mogę spać gdziekolwiek, mogę żyć tak, jak lubię i wiecie, że żyję w pałacu, rzeczywiście w pałacu, co z tego, pałac nie jest dla Mnie ważny, gdziekolwiek idę, zrobię z tego pałac dla siebie, ponieważ nie dbam i wygody, brak wygód nie może na Mnie wpływać, nic nie może Mnie zdominować, nic nie może Mnie dotknąć, nic nie jest dla Mnie ważne, ponieważ jestem Królową, jeśli jestem żebrakiem, wtedy chcę wygody, chcę tego, chcę tamtego.

Nie zostało już żadne pragnienie. Niczego nie chcę. Kiedy wejdziecie w ten stan, wtedy będziecie się radować Sahaja Yogą, waszym Duchem, i to jest to, co się dzieje, gdy ludzie przyjeżdżają do Indii. Byłam zdumiona widząc tych ludzi, którzy przybyli, za pierwszym razem, gdy przyjechali wydaliśmy 40 tys. dolarów i 5 Amerykanów tutaj przybyło, 4 lub 5, 4 i 1 Kanadyjczyk, więc 5, a 4 z nich uciekło, wyobraźcie sobie, jak drogie to było, 4 uciekło, próbowaliśmy. Oni przyszli spotkać się ze Mną i tak dalej: "Nie, Matko nie możemy znieść tej niewygody, nie możemy znieść tego dyskomfortu", jaki komfort chcecie tutaj mieć? Nie dostrzegam żadnego komfortu, było okropnie gdy tu przyjechałam, spójrzcie na moją głowę, chorowałam w tym okropnym miejscu, a jaki komfort wy chcecie mieć? A tam oni tak się chełpili, że się nie udało. Więc wszyscy zrozumcie, że ci ludzie, którzy przez cały czas proszą o rzeczy, żebrząc o rzeczy, nie osiągnęli w życiu niczego.

Teraz, kiedy przyjeżdżacie w tym czasie do Indii, będziemy mieli znacznie bardziej spartańskie życie, ponieważ nie zamierzamy zostać w żadnym budynku, w miarę możliwości, z wyjątkiem Rahuri, może tam również, zamierzamy umieścić was na zewnątrz pendalu [świątyni], całkowicie w lesie, gdzie będą tygrysy, węże będą pełzać po was i będziecie musieli kąpać się w rzekach, które płyną z dużą prędkością. A potem także będziecie mieć piękną muzykę porannych ptaków i piękny zapach, co jest tak piękne i kojące. Tam, gdzie rośnie esencja życia i tak zadecydowaliśmy. Uważam, że jeśli Ja mogę tam żyć, dlaczego wy nie możecie? Nie mogę zrozumieć, co jest w tym tak nadzwyczajnego? Jestem starą kobietą teraz mam 63 lata i całe moje życie, mój ojciec lub mój mąż wyjątkowo lubią nadmierny komfort. Uważam, że żyją w luksusie. Nigdy, przez całe moje życie nie wiedziałam jak wezwać taksówkę lub jechać autobusem, nigdy nie wiedziałam jak kupić bilet, żeby pojechać pociągiem, nigdy nie podróżowałam sama samolotem, nie wiem jak podróżować samotnie samolotem, zawsze taka byłam, bo niczego nie potrzebuję, mogę podróżować sama, mogę iść gdziekolwiek, mogę robić wszystko bez odczuwania strachu, bez odczuwania problemu, ponieważ tak długo, jak jestem ze sobą, o co się martwić? I właśnie to musimy osiągnąć, to jest to, co musimy zrobić. Kiedy osiągniemy ten rodzaj temperamentu, to jest takie piękne, będziecie siebie szanować, pokochacie siebie i tak jak kochamy innych i szanujemy innych, ci, którzy nie szanują samych siebie nie mogą szanować [innych].

Egotyczni ludzie nie szanują samych siebie, jeśli by szanowali samych siebie, nie byliby egoistyczni, bo to takie haniebne być egoistycznym. Jeśli powiecie "jesteś bardzo egoistyczny" ta osoba was uderzy, nawet jeśli powiecie coś inneg... Ale jeśli mówicie: "Jesteś egoistą", oni was uderzą, to znaczy, że czują się zranieni. Jeśli tego nie lubią, to dlaczego to mają? Bardzo ciężko jest ruszyć to ego z waszych głów, a wy łapiecie od jednych od drugich tak szybko, że czasami nie rozumiem. Ale klimat indyjski i indyjskie wychowanie jest takie, że ludzie nie stają się egoistyczni, nie znałam nikogo, kto jest dzisiaj dobry a jutro czeka, by was uderzyć, nie spotkałam nikogo takiego w Indiach, to bardzo stabilni ludzie, zobaczcie, tutaj siedzi pewien doktor i on pragnął nagrody Nobla, człowiek tego typu. Czy możecie uwierzyć, że taki człowiek tu siedzi? On jest kolejnym. Nie znajdziecie tego zachowania u nikogo z Indii, oni mają ego, bardzo subtelne ego, muszę powiedzieć, że biurokraci mają i inni politycy mają, ale jak wyjadą za granicę, to oni stają się nawet jeszcze gorsi. Ale zwykle status osoby w Indiach jest znany dzięki temu, że jest ona skromna, w przeciwnym razie nie uwierzą, że pochodzicie z królewskiej rodziny, jeśli pochodzicie z rodziny królewskiej, jesteście wyjątkowo pokorni, to jest znak, jak....

Zamieniłam z nią pięć zdań i ona powiedziała: "Ta pani jest bardzo czcigodna, musi być z rodziny królewskiej" jestem, jestem, ale myślę, że nigdy jej tego nie powiedziałam, niewielu ludzi o tym wie, ale ona powiedziała: "Ona musi być z królewskiej rodziny". Jaka jest potrzeba, aby obrażać innych, jaka jest potrzeba, aby krzyczeć na innych i mówić w taki sposób? Nie ma potrzeby, musicie mówić w sposób słodki i miły, to wygląda dobrze i prezentuje się lepiej. Wasza osobowość jest lepiej odbierana przez innych, choćby ze względu na stosowną zgodę z innymi ludźmi, proszę postarajcie się pozbyć waszego bezsensownego ego. Ono utrzymuje was poza zasięgiem radości, poza oceanem radości, który powinniście mieć.

Jesteście nieszczęśliwymi istotami zupełnie bez powodu, czyniąc wszystkich nieszczęśliwymi. Ale stawcie temu czoła, nie wkładajcie tego w lewe Vishuddhi "Och, jestem egoistyczny, jestem bardzo nieszczęśliwy", jesteście skończeni, nie mogę tego wyleczyć. Ja już cierpię, widzicie, przez cały czas czuję tutaj ból, ból tu, nie wiem co mam robić, odkąd przyjechałam na Zachód, rozwinął się u Mnie tutaj ten problem, ponieważ wy wszyscy macie to lewe Vishuddhi i ja umieściłam was wewnątrz Mojego ciała. Nie wiecie jak wielki ból Mi sprawiacie, chociaż to nie jest dla Mnie istotne, mogę to widzieć. Muszę od was teraz żądać, abyście zaopiekowali się sobą i zachowywali w taki sposób, żeby to amerykańskie ego znikło, ponieważ tu jest inny sposób, którym jest czas Shri Krishny, którego nie chcę teraz używać. Destrukcja najpierw zacznie się w Ameryce, potem zacznie się budowa. Destrukcja jest niemożliwa, chmury destrukcji znikną, znikną zupełnie, rozwieje je chłodny wiatr, ale wy musicie być szczerzy i rozumiejący, bez żadnego ego, to jest wasza odpowiedzialność, dla waszych dzieci, dla waszego potomstwa, dla waszego kraju, to jest wasza odpowiedzialność. Dobrze?

Niech was Bóg błogosławi!

Więc teraz będę szła gdzie indziej i wieczorem mogę was już ponownie nie spotkać. Ale mam nadzieję, że wy ludzie dacie teraz pełną listę osób, które chcą się pobrać. Ci, którzy jeszcze nie zadecydowali, powinni zdecydować, nawet jeśli jeszcze nie zdecydowaliście się co do ludzi, dajcie Mi listę osób, które chcą wziąć ślub w Indiach, jeśli nie w tym, to w przyszłym roku, coś w tym stylu, wszyscy powinniście dać swoje imiona, ci którzy chcą się pobrać, to jest bardzo ważne, ponieważ nie da się tego zrobić bez spisania wszystkich tutaj, o to chodzi.

Po drugie musimy zdecydować, jak wielu się wybiera, w jaki sposób i wszystko to musi zostać zrobione we właściwy, systematyczny sposób i Babet musi zostać o tym poinformowana, każdy powinien powiedzieć, że tylu jedzie z Los Angeles w ten sposób, oni jadą w ten sposób i Babet musi być w stanie zorganizować to, nie powinno być współzawodnictwa, niczego. A wy powinniście widzieć, że uzyskujecie najniższą cenę, ale nie kosztem martwienia się o to, cokolwiek chcecie łatwo uzyskać, po prostu to miejcie, to nie jest takie istotne.

Trzecią sprawą, o której powiedziałam jest to, że nie potrzebujecie zabierać ze sobą zbyt wielu bagaży, szczególnie panie, nie ma potrzeby zabierać do Indii kosmetyków do makijażu czy czegokolwiek, zupełnie nie ma potrzeby, to jest kraj, w którym wasza skóra poprawi się sama, nie musicie zbyt wiele się malować. To jest bardzo łagodny kraj, w którym wasza skóra odżywi się sama i będziecie się czuć bardzo dobrze, i nawet jeśli musicie kupować, możecie kupić w Indiach takie, które nie są zrobione z chemikaliów czy czegokolwiek, ale są naturalne. Nawet pasta do zębów i wszystko to, lepiej jest używać indyjskiej pasty do zębów, więc myślę, że teraz doszłam do konkluzji, że wszystkie te okropne pasty do zębów tutaj, które zawierają środki chemiczne, nie wiem co stanie się z zębami, jak dotąd moje zęby są nienaruszone, nigdy nie byłam u dentysty, ale czuję, czuję, że one są pełne okropnych chemikaliów.

Więc nie psujcie sobie skóry tymi okropnymi makijażami i tym podobnymi rzeczami, myślę, że znalezienie tutaj właściwego szamponu jest niemożliwe, ponieważ czasami niektóre szampony mogą po prostu pozbawić was włosów, więc postarajcie się nabrać nawyków, które są proste, naturalnych nawyków, w żywy, nie prymitywny, znów mówię nie prymitywny, ale nie bardzo skomplikowany [sposób] i nie przywiązujcie tak wiele uwagi do swojego ciała, tak jak to teraz robicie, nie ma potrzeby, to jest dobre cokolwiek Bóg dał ciału, to jest w porządku, nie musicie się zbytnio tym martwić. Róbcie trochę ćwiczeń rano albo coś takiego, medytujcie właściwie, bądźcie normalnymi ludźmi nie musicie przesadzać z robieniem czegokolwiek, ‘trochę’ jest wystarczające, ale utrzymujcie się w centrum, nie idźcie w niczym w ekstrema.

Teraz musicie przywieźć sweter i rzeczy w tym stylu, i tak jak wam powiedziałam, odpowiednie rzeczy do spania. W Indiach oni dostarczą wam pościel i wszystko, z ładnymi bawełnianymi prześcieradłami, ponieważ musicie używać wszędzie gdzie to możliwe - bawełny i jedwabiu albo bawełny, naturalnych rzeczy, nie sztucznych, bo będziecie mieli kłopoty, jeśli będziecie używać plastików i takich rzeczy. Więc postarajcie się w możliwie największym stopniu nie przywozić wielu ubrań, ponieważ my wam wszystko damy.

Teraz przejdźmy do części praktycznej. Chciałabym mieć wszystkie potrzebne - jak wy to nazywacie - rozmiary, spisane odpowiednio, ale pogrupujcie je w 4 rozmiary. Posortujcie je, możecie to zrobić, utwórzcie 4 rozmiary, dla kurtas i dla pań również bluzki w 4 rozmiarach, więc utwórzcie 4 rozmiary A, B, C, D dla panów i pań, i to będzie gotowe dla was, gdy przyjedziecie.

Wyobraźcie sobie jak wiele Hindusi pracują w tym celu i jak wiele Ja ofiarowuję. To wszystko co daję jest darowizną, pozostaje tak niewiele pieniędzy i oni zamierzają ofiarować tak wiele pieniędzy na waszą szkołę, dla waszych dzieci, wyobraźcie sobie, że Hindusi to robią, to nie jest zbyt dobre. Mamy tak niewiele pieniędzy, które zostały dane, szczerze mówiąc, więc naprawdę wstydzę się brać te pieniądze do Indii, więc zatrzymam je teraz u Arneau, wszystkie pieniądze są tutaj przechowywane, trzymacie je tutaj, ale jeśli macie mieć szkołę, musicie mieć dobrą szkołę i w tym celu potrzebujemy pieniędzy, ale na razie nie myślicie o darowiznach, ponieważ myślicie, że jesteście bogatymi ludźmi, jesteście teraz niezdolni do darowizn. Widzę to jasno, ponieważ musicie podróżować musicie wydawać pieniądze na swoje podróże, Hindusi nie muszą tego robić, więc to jest w porządku, cokolwiek powiedzieli o darowiznach. A wy przybywacie tutaj z miłością, ale ludzie wracają jak handlowcy, naprawdę jak handlowcy, ponieważ Indie są miejscem, gdzie można kupić wiele rzeczy, chcecie kupić to chcecie kupić tamto, to niedobrze.

Ale troszkę rzeczy o symbolicznej wartości, cokolwiek potrzebujecie powinniście kupić, nie możecie przywieźć z Indii wszystkich rzeczy, które potrzebujecie, ale ludzie, kiedy podróżują w ten sposób, to jest bardzo haniebne, myślę, że ludzie czasem nie rozumieją, w jaki sposób yogini muszą dźwigać tak wiele rzeczy, teraz powinniście nosić rzeczy, które są dla was użyteczne, które są dla was dobre, ale nie za wiele. [koniec transkrypcji]
