Charla Pre-Ganesha Puja, se un sabio pescador de hombres y programa musical

San Diego, EEUU, 6-9-1986

Es muy hermoso estar con todos vosotros en un entorno tan natural. En medio de la ciudad no se puede encontrar esta paz; siendo la paz algo muy beneficioso para los que intentan ascender. Me pedisteis que viniera para que pudierais hacer el Puja a Ganesha; y la razón por la que he venido es porque me parece esencial el que Shri Ganesha se establezca. Estoy muy contenta de ver tantos americanos que son ahora sahaja yoguis; aunque, desde luego, comparados con la población americana son muy pocos; tenemos que tener muchos más sahaja yoguis. Sus problemas básicos, o por lo menos uno de ellos, pienso que es el referente a Shri Ganesha. Por eso es necesario celebrar el puja a Shri Ganesha en América; ya sea en Los Ángeles o en algún otro lugar como San Diego; otra opción es hacerlo en esta montaña. Espero que este Puja contribuya a que podamos establecer la esencia de la inocencia; ya que hoy en día se encuentra en un estado de sueño profundo.

Hoy os quiero decir algunas cosas, referentes al trato que hay que dispensar a las personas que vienen a Sahaja Yoga por primera vez. La idea que tenemos respecto al trato que debemos dar a los buscadores que vienen a vernos, es la de tratarles con una actitud que parece un poco como que les pedimos disculpas. También parece que debéis hablarles de todos los chakras y darles una retroalimentación (así lo llaman) de todo el conocimiento de Sahaja Yoga, pero a nivel mental. Sin embargo, no creo que sea una forma eficaz de hacerlo; lo primero que hay que hacer es darles la experiencia de la Realización. También decirles que Sahaja Yoga no consiste en las enseñanzas de un guru falso o de una secta (como lo llaman aquí). En Sahaja Yoga no hay cabida para estas cosas. Muy por el contrario se fundamenta en el proceso evolutivo; en la manifestación natural y gradual del poder que se encuentra dentro de nosotros.

También tenéis que hablarles de mí. Hasta ahora se ha intentado no mencionarme, el no seguir el tópico. Quizá porque pensamos que ha habido gurus, y esto y lo otro...Y que los gurus han traído mal nombre al hecho de ser guru; pero no es así. Incluso hoy en día, multitud de personas siguen yendo a estos gurus. Estos gurus comienzan a decir que son encarnaciones de los dioses, semidioses, de algún dios específico o cosas por el estilo. Esta especie de actitud de pedir perdón no les va a convencer; debéis darles la experiencia y decirles que es de esta persona (Madre) de quién emanan todas las bendiciones. Y que es por su Gracia por lo que Sahaja Yoga funciona en las personas.

A nivel psicológico os quedaréis sorprendidos, ya que siempre funciona todo al revés de cómo pensáis. Supongamos que mañana preparáis mi programa en San Diego; allí podemos lograr que vengan fácilmente unas trescientas personas sin ningún problema. Sin embargo, cuando vosotros hacéis el seguimiento no quieren venir. O como cuando os trabajáis unos a otros; si yo estoy allí hay mucha gente, pero con el tiempo pierden el interés en verme. La razón fundamental de su comportamiento es tan solo una; y es que no quieren pasar por la actividad mental ni por las pertinentes acrobacias mentales, que se requiere hacer al escuchar las cosas que les contáis. La gente quiere sentir mi presencia a través de vosotros, del mismo modo que la sienten cuando estoy presente en un programa público. Creo que debéis cambiar vuestras tácticas; decidles de una forma sencilla y natural: "Fuimos buscadores y conocimos a muchos gurus, pero nunca encontramos la verdad. Y además nos engañaron. Sin embargo, aquí hay alguien que no acepta ningún dinero y que no quiere nada de nosotros. Además, no nos convierte en personas raras y podemos llevar una vida muy normal; es alguien que nos concede todo tipo de bendiciones. ¡Probadlo!. Pero si no queréis experimentarlo, pues no lo experimentéis".

Suponed el caso de una persona que no está realizada y que se propone a sí misma: "debo luchar con mi ego". Pero con lo que se propone luchar es con su propio ego; así que, como resultado de ello actúa sobre su ego. De la misma manera cuando halagáis a estas personas, actuáis sobre su ego. De hecho se vuelven como cáscaras endurecidas de huevos pasados por agua; las cuales son imposibles de atravesar.

Los resultados serán evidentes cuando tengáis dedicación y devoción hacia mí; además no hay otra forma de conseguirlo. Si les habláis directamente, no os escucharan; porque esa es la naturaleza humana y no lo podéis evitar. ¿Cómo se lo vais a explicar?; cuando doy una conferencia, en cualquier lugar al que vaya, vienen muchas personas y es porque piensan que soy auténtica. Ven que hablo con autoridad pero no con agresividad; Me ven hablar con carácter y con convencimiento. Se ha de expresar esta convicción; pero si por el contrario comenzáis a explicarles lo referente a un chakra y que si esto y que si lo otro. En ese caso se dicen a sí mismos: "De acuerdo, pero para conocer este tema podemos leer un libro sobre ello; ¿qué necesidad hay de venir y escucharlo aquí?. Además, el hecho de tener que escucharlo nos produce dolor de cabeza". Deberíais ser personas con convicción; una convicción basada en la realidad y no en la falsedad.

Ya que estáis todos aquí, os debo decir que tenéis en este país, a vuestra disposición, sahaja yoguis de la India que son extraordinarios. Pero no sé hasta qué punto les escucháis; como el señor Karde. Es la persona que comenzó Sangamya, las personas que estuvieron en Sangamya pudieron ver un inmenso gimnasio; el cual incluye una amplia área para jugar al fútbol. La cubierta fue construida por la gente que pasó por Sangamya. Y fue él quién estableció realmente esta ciudad de Sangamya y quién la transformó en un hermoso centro. Pero tenéis que escucharle; de otro modo estas personas son inútiles. En segundo lugar Shara,Varkari es muy buena sahaja yoguini, además de otras cosas es muy auspiciosa y una persona entendida.

La comprensión del conocimiento de Sahaja Yoga no es cómo lo entendéis vosotros. El fundamento de Sahaja Yoga no es el conocimiento de los chakras, sino de las actitudes. No consiste en tener el conocimiento de un sistema, porque nosotros no queremos sistema alguno. Los sistemas crean barreras y generan una especie de esclavitud. Tenemos que desarrollar actitudes dentro de nosotros, basadas en las experiencias que hemos comprobado y testado. Lo importante no es lo que habláis de los diferentes niveles de los chakras. Creéis que lo importante es hablar de ellos. Lo verdaderamente importante es la personalidad que expresáis en vuestra actitud hacia las cosas. Ya hay muchos sistemas creados; especialmente en Occidente existe el hábito de crear normas y sistemas. Por ejemplo, crearán el sistema de comer la comida de una determinada manera; y entonces todo el mundo comienza a sentarse para comer de la misma manera. También crearon un sistema, hace ya tiempo; el de ir a cenar con traje de cola. Tenéis que cambiaros de traje para cenar; y por la mañana tenéis que volver a poneros otro traje diferente. Posteriormente, como consecuencia de todo ello, la gente se hartó y llegaron a una conclusión: " este sistema no es bueno". Y de este modo comenzaron la anticultura.

Así, comenzó la anticultura y con ella los hippies; sin embargo estos hippies tenían su propio sistema; para ser hippie tienes que llevar tu vestido de una forma determinada, tienes que ser una persona sucia. El pelo también debe de llevarse en su forma correspondiente. Tenéis que seguir los patrones de una moda preconcebida; por lo tanto se ha vuelto a construir un sistema. Al traer este sistema, surgió al mismo tiempo el sistema punki; en este asunto del sistema punki hay que llevar la ropa de un modo determinado. Con el pelo sucede lo mismo, hay que llevar un tipo de peinado particular (para el cual gastáis mucho dinero); y si no hacéis esto no sois un punki. De modo que cuando intentan romper con un sistema, al mismo tiempo caen en otro sistema. Van cayendo en diferentes sistemas, uno detrás de otro; pasan de algo muerto a otra cosa también muerta. Pero la actitud es la misma, la actitud no cambia; pude observar como los hippies, al ir en contra de la cultura, se comenzaron a comportar de una forma muy extraña; con ese comportamiento lo que demostraban es que no había habido ningún cambio. Se volvieron muy arrogantes y sin auto respeto; después vinieron los punkis, quienes se comportaron de la misma manera.

La transformación más grande que tiene lugar es la de vuestra actitud; con ello vuestras prioridades cambian completamente. No deberíamos formar un sistema. Como os dije ayer por la noche, no deberíais decir: "Ahora hay que hacer una meditación de ocho horas". Nada de eso, con ocho minutos es suficiente; lo que va a contribuir a vuestro crecimiento es vuestra actitud y no el hecho de sostenerse durante ocho horas sobre una pierna o algo parecido. Hay algunos saddhus que se quedan de pie, poniendo su pierna de un modo o de otro y sosteniéndose sobre una sola pierna. Pero eso no va a ayudar, porque se trata de un proceso viviente; y el modo de hacer funcionar un proceso viviente es de una forma viva. Dejad que funcione, permitid que se desarrolle. Así que, toda esta actitud debe cambiar.

Cuando comenzáis a descubrir cómo ha cambiado vuestra actitud hacia la vida; entonces debéis daros cuenta que os habéis convertido en un yogui. Si vuestra actitud no ha cambiado... Si hay alguien que es muy arrogante y se toma demasiado tiempo para pensarse las cosas; entonces es mejor no preocuparse de esta persona. Pero si se trata de la actitud de un buscador; si se trata de alguien que quiere recibir su Realización, entonces dádsela. Creo que todavía no hemos llegado a lugares en los que hayamos encontrado sistemas y buscadores reales; y esta es la razón por la que habéis conseguido que venga muy poca gente a Sahaja Yoga. Es como cuando los pescadores dirigen sus dispositivos de pesca hacia donde se encuentra el oleaje en los mares; además conocen las zonas costeras donde hay peces. Dirigen sus dispositivos de pesca hacia esas zonas y pescan los peces. De la misma manera que hacen los pescadores con los peces, debemos descubrir, antes que nada, en dónde están los buscadores.

Ver a dónde podemos dirigir nuestra atención y nuestros esfuerzos. En ocasiones se comportan como los burros; si hay alguien que está por delante de ellos, entonces ponen sus cabezas a disposición de esas personas que están por delante y dejan que les tiren de las orejas; si se trata de alguien que se encuentra detrás, dejan que les den puntapiés. Creo que hemos fallado en Occidente, a este respecto, en todas nuestras actitudes. No necesitamos hacer estas cosas, si quieren venir pues dejadles que vengan; ya que si quieren conseguir paz mental tienen que venir a nosotros. Y si no quieren tener paz mental, muy bien, pues tenemos compasión a su disposición. Albergamos amor por ellos; pero si tampoco lo quieren; Cristo dijo: "No echéis perlas...". Y después, una vez que comencéis a comportaros de esta manera, podréis ver cómo conseguís que lo prueben tantos buscadores como caben en una carpa abarrotada de gente.

Cuando fui a Calcuta, había un hombre llamado señor Yala; es un empresario muy sabio y vino a Sahaja Yoga. Este hombre envió cartas a todas las personas eminentes, a las que consideró que serían buscadores. Les dijo que le gustaría ir a conocerles o que podían venir a verle. De todas estas cartas, desde luego que hubo pocas personas que contestaran y que quisieran conocerle; y esta fue la forma en la que conoció a gente relevante. Después les contó lo que era Sahaja Yoga, les habló de ello; y cuando llegué me presentó a estas personas. Uno de ellos era el editor de un importante periódico; vino a verme y observó cómo cuidaba de la gente. Escribió un bello artículo a este respecto y me dijo: "Madre, mañana iré a tu programa"; asistió al programa, como dijo, e hizo una hermosa introducción. A raíz de ello todo comenzó a funcionar de una forma muy distinta en India.

Os puedo hablar de Italia, donde hay una mujer llamada Alganesh. Fue a ver a alguien pensando que podía ser un buscador; era el director de los medios de comunicación del gobierno italiano y trabajaba en la televisión. Alganesh le dijo que podía recibir su Realización. Cuando fui y le vi por primera vez, le dije: " Primero recibe tu Realización y después tendremos la entrevista". Me dije: " Esta es la clase de persona que busco"; puse toda mi atención en él y le di la Realización. Él ya había tenido algunas experiencias, pero después de recibir la Realización afloró un carácter que era todo corazón, como el de un gran sahaja yogui. Y actualmente Sahaja Yoga se está extendiendo muy rápidamente en Italia. Por lo tanto no deberíais ir por las calles recogiendo a los mendigos; ni tampoco ir pidiéndoles: "Por favor ven a Sahaja Yoga, te ruego que vengas a Sahaja Yoga". ¿De qué nos van a servir?, ¿en qué nos van a ayudar? No estoy diciendo que tengamos que ir a la gente rica o a personas eminentes; sino a personas que son reconocidas públicamente como sabias y sensatas. Personas que consideréis que tienen buenas vibraciones y que son capaces de hacer algo en Sahaja Yoga. Aproximaos a la gente y decidles que habéis descubierto esto y lo otro. Si os acercáis a diez personas veréis que unas tres se sienten felices de practicar Sahaja Yoga; este es un método mucho mejor que ir cogiendo personas de aquí o de allá y así continuamente.

Vendrán a vosotros estos buscadores... Me sorprendió que me dijeran que hubo un montón de personas que vinieron a Sahaja Yoga, pero que luego una a una todas fueron desapareciendo. Vino un señor, quien dijo que le habían enseñado todo el conocimiento de Kundalini Yoga durante ocho meses, pero también desapareció; porque nunca tuvo la experiencia. Una vez que os establezcáis a un nivel en el que podéis sentir las vibraciones y el gozo; entonces la gente nunca dejará Sahaja Yoga. También debéis ver cuán profundas son las personas. Toda la actitud hacia extender Sahaja Yoga debe de ser: " Sahaja Yoga no es algo que se deba desperdiciar con gente que no lo comprende". Sé que tenéis un gran afecto por los americanos, y es ésta la razón por la que yo también tengo este afecto por ellos. Sin duda, todos deseamos que cada vez vengan más y más americanos a Sahaja Yoga. Pero está tan solo en vuestras manos la posibilidad de trabajar duro; podemos decidir lo que vamos a lograr. Debemos entender también cuáles son los problemas de los americanos; conocer las cosas que les obstaculizan para venir a Sahaja Yoga. Quizá mañana pueda hablaros de lo que he podido entender respecto a su situación; así que mantenedlo presente en vuestra mente. Y de este modo, si os acercáis a ellos con una actitud adecuada, con confianza en vosotros, entonces estoy segura que lo haréis muy bien; pero para que funcione debéis tener confianza en vosotros mismos. Eso no significa que seáis agresivos, sino gente con confianza; para hacer algo bien debéis tener plena confianza en vuestro Ser. Si no, nadie os va a creer.

Queremos que vengan más sahaja yoguis de India para ayudarnos; pero creo que antes que nada, todos los que ya estáis aquí debéis intentar escucharles. Me dicen los indios que sois vosotros los que les enseñáis a ellos; con ello no quiero decir que todos los indios sean excepcionales o gente muy cualificada. Sin embargo lo que sí es verdad, es que han pasado conmigo días enteros. Aparte de esto, eso no significa que todos los indios sean mejores que todos los americanos; sin embargo algunos de ellos son muy buenos, y es a estos a quiénes tenéis que respetar.

Intento comprender la actitud de estas personas y lo que debo decirles. La manera en la que entendéis la vida no es correcta; si fuera correcta habría una América distinta. Se han cometido muchos errores y para conseguir un estilo nuevo de vida, es necesario tener una comprensión novedosa de la nueva era; tenemos que entender que se trata de un conocimiento nuevo para nosotros y que debemos aprenderlo y entenderlo. Hasta ahora no teníamos el conocimiento de los procesos vivientes. Cualquier conocimiento que teníamos, era un conocimiento muerto. Como por ejemplo, podéis hacer una casa a partir de un árbol muerto, partimos de algo muerto y terminamos haciendo algo muerto. Pero nunca habéis comprendido los procesos vivientes. De modo que todo el proceso de santificación, no es más que el resultado de vuestra actitud hacia el conocimiento de cómo funciona el proceso viviente de nuestra evolución. También incluye la plena confianza en ese conocimiento. Estoy segura que prestaréis plena atención a lo que he dicho; mañana podéis hacerme preguntas acerca de este tema. En tan poco tiempo no os puedo contar todo minuciosamente. Pero espero que hayáis comprendido el hecho de tener que adoptar una nueva actitud, si es que realmente queréis lograr esta visión.

Que Dios os bendiga.