Diwali Puja, “Potęga Niewinności”, 25.10.1987, Lecco (Italy)

Najpierw kłaniamy się Shri Ganeshy, ponieważ Shri Ganesha jest źródłem niewinności w nas. Zatem kłaniamy się niewinności w nas. I ta niewinność daje wam oświecenie. Jak wam wczoraj mówiłam, światło ma niewinność, ale to jest niewinność bez wiedzy. A wasze światło jest niewinnością z wiedzą. Myślimy zawsze, że ludzie mający wiedzę nie mogą nigdy być niewinni, prości. A ta idea jaką mamy o niewinności, że niewinna osoba jest zawsze oszukiwana, zawsze daje się nabierać - może być uznawana za oczywistą. Lecz niewinność jest siłą, siłą chroniącą was, dającą wam światło wiedzy.

Wiedza jaką posiadamy w sensie doczesnym, polega na wykorzystywaniu innych, oszukiwaniu ich, robieniu na nich pieniędzy, wyśmiewaniu i braku szacunku dla innych. Ale światło mądrości jest światłem, dzięki któremu wiecie, że miłość jest najwyższą rzeczą. I ono uczy was jak kochać innych, jak się o nich troszczyć, jak być delikatnym wobec innych. Daje wam również światło wewnątrz.

To jest po prostu odwrotna droga do tej avidya jaką mamy na tym świecie. Po prostu odwrotna droga. Avidya na zewnątrz uczy nas rywalizacji, jak kogoś poniżyć. Ponieważ jest pełna strachu, niepokoju. Ta wiedza nie posiada spokoju - wcale. Gdyby miała poczucie bezpieczeństwa nie zachowywałaby się w ten sposób. Lecz światło niewinności wie wszystko. Nie ma lęku. Kiedy mówimy: “Dzieci są niewinne”, mamy na myśli, że one mają moc niewinności. Wiele razy ludzie zauważali, że jeśli dziecko spada z wysokości, nie umiera, podczas gdy młody mężczyzna może umrzeć spadając z mniejszej wysokości. I dziecko się nie boi, gdy spada. Cieszy się tym, jak gdyby było spadochronem spadającym, wiecie, tak przyjemnie. A kiedy spadnie, wstaje, śmieje się do wszystkich. I nie rozumie, dlaczego wszyscy się martwią. Ponieważ w tej niewinności wie, że jest otoczony opieką, chroniony. Wie, że istnieje siła, będąca wysoko ponad nim i ono nie musi się martwić.

A kiedy zaczynamy wkładać do głowy dziecka te idee, to ono zaczyna tracić moc tej niewinności i staje się tchórzem, przebiegłym osobnikiem, nie prawą osobowością. Ale nadal możemy mówić, że niewinność dzieci jest niewinnością ignorancji, ponieważ one nie znają niebezpieczeństw życia. Ale światło niewinności zna wszelkie niebezpieczeństwa i wie również jak się ich pozbyć, a także wie, jak być z dala od takiej osoby.

Był sobie mądry człowiek, wchodzący po schodach oraz człowiek schodzący drugą stroną – głupiec. Głupcy są zawsze agresywni, to jest jedna z oznak, ponieważ mają kompleks niższości. Tak więc głupi człowiek mówi do tego wchodzącego człowieka, mówi [ponieważ] po schodach idzie się jedną stroną – tak więc on mówi: ”Ja nie ustępuję głupcom!” Tak mówi głupiec. Na to odpowiada mądry człowiek: “A ja tak” i ustępuje. Tak oto światło niewinności mówi wam, jak daleko posunąć się w relacjach z kimś, Jak rozmawiać z osobą, jak długo znosić problemy innej osobowości; w innym wypadku on się wycofuje. Rozumie, że ten gentleman jest głupcem, tak więc ”wycofuję się przed takimi”. Nie przywiązuje uwagi do takiej osoby, nie przejmuje się taką osobą.

To jest światło niewinności, które daje wam rozróżnienie. Jak daleko posunąć się w relacjach z innymi. Kocham tę osobę, jest wiele “kocham go”. W porządku! Inna osoba może kopnąć was, może was uderzyć, narobić wam kłopotów, może być strasznie opętana, ale wy wciąż kochacie tę osobę, bez szacunku do siebie samego. A to przychodzi, ponieważ nie ma.... wy możecie być niewinni, w doczesnym tego słowa znaczeniu, ale nie jesteście oświeceni i niewinni. Kiedy jesteście oświeceni i niewinni, wtedy wasza niewinność jest siłą, która daje wam przede wszystkim rozróżnienie.

Przypuśćmy, że bierzecie światło do ręki - teraz wiecie czy to jest wąż czy lina, ale jeśli nie macie światła w dłoni, nie możecie zobaczyć. Ale nawet, jeśli to nie jest wąż możecie uciec lub jeśli jesteście głupi, powiecie: “Chodź i ugryź mnie chciałbym zobaczyć jak to działa”. Lecz jeżeli jesteś oświeconą osobą, wtedy powiesz do węża: “Teraz, zostaw mnie samego. W porządku? Papa”. I wąż będzie wiedział i pójdzie sobie. Lub jeśli wąż będzie złowrogi, możecie po prostu na niego spojrzeć i on ucieknie.

Tak więc ta siła niewinności jest bardzo, bardzo ważną rzeczą i przychodzi do nas poprzez nasze oświecenie. Tak więc my jesteśmy, powiedzmy, w stanie, który jest ignorancją i niewinnością - niewinnością i ignorancją. Wtedy ludzie ani nie mają niewinności, ani nie są ignorantami, ale też nie są oświeceni - stają się przebiegli! Jeśli nie posiadają obu tych cech – nie są ani tak zwanymi ignorantami, posiadają wiedzę, są dobrzy we wszystkim, są dobrze znanymi ludźmi, za swoją inteligencję, błyskotliwość, za wszystko - nazywa się ich mądrymi. Takich ludzi moglibyśmy określić jako posiadających wiedzę, w doczesnym tego słowa znaczeniu, lecz oni nie mają niewinności i oni zaczynają wymyślać metody, a niewinność, która jest tutaj, która kontroluje trochę umysł, jest stracona. Ponieważ oni myślą, że niewinność jest głupia, wiecie? Oni nie szanują swojej niewinności.

Zaczynają więc manipulować ludźmi, stosować przemoc, krzywdzić, mówić okropne, sarkastyczne rzeczy. Mózg zaczyna robić te wszystkie rzeczy, ponieważ nie może wrócić do niewinności. Później nie lubimy tych ludzi, nie chcemy ich. A wtedy oni wymyślają idee, że “my jesteśmy wyższymi ludźmi, wybranymi ludźmi, jesteśmy lepsi” - następnie, rozwijają te wszystkie idee. A potem jednoczą się.

Tak więc ignorancja jest zaliczona do tak zwanej wiedzy, widzicie. Wewnątrz jest kompletną ignorancją, zewnątrz wiedzą. I sumując to – oni nie chcą poszukać w swoim wnętrzu i są usatysfakcjonowani tym, co na zewnątrz, tą tak zwaną wiedzą. Podążają z tym do przodu i gdy kiedyś potłuką sobie głowę, wtedy zdadzą sobie sprawę “Boże, co to jest? To wszystko jest ciemnością”.

Nie możemy żyć za zamkniętymi hermetycznie oknami oraz słońcem świecącym na zewnątrz. Musimy mieć światło wewnątrz, żeby ujrzeć siebie, czym jesteśmy, jakie są nasze moce, jak daleko możemy zajść, jak przepracowujemy siebie, nasze życie, cele?

W tej chwili, oświecenie, podobnie jak zapalenie się tych świateł manifestuje się w was jako wibracje, jako chaitanya, jako światło. Sama chaitanya jest więc światłem. Ale różnica pomiędzy tym światłem a tamtym światłem jest taka, że to powie wam tylko to, co powiązane jest z oczami. Powie wam, że to jest kamień, albo że to jest drewno lub dom, lub że to jest twarz człowieka – cokolwiek, to światło, lecz to nie będzie w stanie wam powiedzieć, czy ta osoba jest dobra czy zła, czy ten dom ma wibracje czy nie, czy jest pomyślny czy nie. Tak więc nie da wam pomyślności, idei pomyślności. Mówimy o niewinności Ganeshy, która daje nam sens pomyślności, a także czyni nas pomyślnymi.

Tak to chaytanya jest oświeceniem, sama jest oświeceniem. Przekazuje wam całą wiedzę jaką ma. Wyobraźcie sobie teraz, jaki to jest mikro-porządek, te chaitanye, które są małe, tak małe jak małe okrągłe valayas, małe, małe. Mają w sobie inteligencję oraz wbudowane rozróżnienie, aby powiedzieć wam, czy osoba jest dobra czy zła.

Macie to, Sahaja Yogę, w prosty sposób. Tak więc bez przeszkód możemy się dowiedzieć, co wasz komputer zawiera. On ma wiedzę nie tylko odnośnie tego, czy osoba jest dobra czy zła, ale również jakie ma problemy. To światło może wejść w obszar osoby, jak ona wygląda, jak chodzi, wszystko. I wy, gdy zaczynacie sobie coś wyobrażać, jeśli zaczynacie wyobrażanie – oraz mówienie, że: “czuję w ten sposób, myślę że w ten sposób”.

[ktoś przerywa mowę Matki]
Shri Mataji: nie dobrze? Yogini: [niedosłyszalne] Shri Mataji: Ha? Yogini: [niedosłyszalne] Shri Mataji: nie słyszycie Mnie? Wielu yoginów: Tak. Na górze tylko w przedszkolu Shri Mataji: Co to jest? Akbar: tam jest video dla matek z dziećmi i one Cię nie mogą usłyszeć. To jest na górze. Shri Mataji: Nie usłyszałam, co to jest? Antonio Scialo: Tam na górze jest pokój dla dzieci, dla dzieci, z video dla dzieci i Matek. Ale Cię nie słyszą. Shri Mataji: A, rozumiem, ale są tutaj dzieci? Yogini: małe dzieci, małe dzieci; matki i małe dzieci Shri Mataji: O Boże. Ktoś musi wejść na górę i to naprawić, prawda? Myślę, że powinniście to przedtem przetestować, prawda? W porządku.

Tak więc, chaitanya, która jest wewnątrz nas, która wypływa, którą otrzymujemy zewsząd, jest wszechprzenikająca, pulsuje w każdej molekule, która daje nam wiedzę o każdej materii bez wyjątku, o każdym bez wyjątku zwierzęciu, o każdym bez wyjątku człowieku i każdym bez wyjątku Bóstwie. Bez tego światła nie moglibyście Mnie rozpoznać. Nie moglibyście rozpoznać żadnego z Bóstw. Nie moglibyście znać waszej pozycji w życiu ani waszych życiowych celów. Nie znalibyście waszego celu w życiu, dlaczego tutaj jesteście.

Jesteście tutaj, żeby zarobić trochę pieniędzy, odłożyć trochę na ubezpieczenie i trochę do rozdzielenia? Oczywiście, teraz to nikt tego nie zrobi! [rynek papierów wartościowych upadł w poniedziałek, 19.10.1987 roku w tygodniu pujy], aby otrzymać dom, tańczyć jak wam zagra wasza żona lub żona musi tańczyć pod dyktando męża, jakoś wychować dzieci - czy po to jesteście tutaj? Ta chaitanya mówi wam, bardzo wyraźnie: “Nie”. Ponieważ, jeśli się bardziej wciągniecie w te rzeczy i staniecie się całkowicie odcięci od kolektywnych wydarzeń, wówczas to światło odejdzie. A gdy tylko światło zostanie odłączone, nie będziecie mieć żadnego światła.

Tak więc jakiekolwiek macie połączenie, z wibracjami, musi być bardzo silne i musi być absolutnie nienaruszone i pewne. Na przykład, jeśli mamy światło, które nie jest stabilne, porusza się, to nie możecie zrozumieć rzeczy właściwie. Poprzez wibracje wiecie wszystko, ale jak można przesyłać informacje, jeśli instrument nie jest doskonały, który nie szanuje wibracji i nie porozumiewa się przy pomocy wibracji?

Proszę wyprowadźcie dziecko. Nie próbujcie pchać – nie, nie, nie, nie róbcie tak. Nie, nie, nie róbcie. Nie powinniście stracić panowania przy dzieciach, wiecie? One płaczą, muszą czegoś chcieć.

No więc, ten mądry instrument jaki posiadacie, ma cały czas płynąć przez was, a wy musicie być bardzo czystym aparatem. Załóżmy, że macie to światło, ale szkło nie jest czyste – nie otrzymacie odpowiedniego światła. Tak więc czystość musi być ustabilizowana, i to jest część, gdzie Ganesha jest tak ważny, ponieważ On was oczyszcza, myje a wy stajecie się niewinni: ponieważ nie planujecie ani nie myślicie o zranieniu kogokolwiek, kto jest dobrą, miłą osobą. To staje się niewinnością, ponieważ to jest pomyślne. Zaczynacie być pomyślni. Gdziekolwiek idziecie i spotkacie kogoś, to ta osoba to poczuje”, o Boże, coś dobrego wydarzyło się dzisiaj w naszej rodzinie. Coś dobrego się pojawiło.

Ostatnio spotkałam kogoś w Niemczech, gdzie był Sahaja yogin, który zaczął mówić coś przeciwko Mnie i Sahaja Yodze. Wyszedł z ashramu i poszedł do kogoś, kto przypuszczalnie był Sahaja yoginem i do jego żony, i tam zaczął wylewać swoje żale przeciwko Sahaja Yodze i tego typu rzeczy. Chociaż on był zawsze opętanym człowiekiem, lecz ci ludzie nie powinni byli słuchać niczego przeciwko Mnie. W shastrach jest napisane, że słuchanie Guru-ninda, czegokolwiek co jest przeciw waszemu Guru, jest bardzo niebezpieczne. Tak więc, gdy ktokolwiek mówi coś przeciwko waszemu Guru, musicie położyć swoje ręce w ten sposób: “Nie chcę słuchać niczego przeciw mojemu Guru!” Ale oni zamiast tego, aprobowali to. Tak więc ta kobieta dostała raka poważnego typu i mąż również jest bardzo chory.

Teraz, należy zrozumieć, że jeśli zamierzacie przekroczyć ocean w łodzi - wszyscy jesteśmy w niej - i jeden chce włożyć swoją stopę w paszczę krokodyla, to jak my możemy ocalić takich ludzi? Lepiej jest więc, gdy pójdą do krokodyla niż na łódź. A ci, którzy to akceptują i wkładają druga stopę w paszczę krokodyla, muszą mieć kłopoty.

Te wszystkie rzeczy nie tylko utrudniają lecz są też niepomyślne i niebezpieczne tak, że wy wszyscy musicie być z tym nadzwyczaj ostrożni. Nie potrzebujecie mówić tym ludziom: ”Jesteś diabłem! Jesteś zły!” lub coś takiego - ale po prostu: “Wyjdź z Sahaja Yogi!” Nie musicie nic z nimi robić. Powinniście powiedzieć: ”Przykro nam. Nic nie możemy z tym zrobić. Róbcie co chcecie. To nie nasza odpowiedzialność”. I nie powinniście być łagodni, nie powinniście czuć się zakłopotani ani delikatni. Zbesztajcie ich: “Dość tego. Nie możemy wam tu pomóc, przykro nam, sami to wypracujcie”.

Ponieważ to światło jest światłem, które was odżywia i wzmacnia. Światło Ducha musi dać wam tę siłę wewnątrz was. Stajecie się silną osobowością. Stajecie się osobowością, która może znieść wiele rzeczy, nawet ukrzyżowanie, ale mogącą również walczyć. Posiadają wszystkie cechy wbudowane wewnątrz siebie. Jak osoba mająca gniew. Nie! To nie jest dobrze mieć gniew. To nie jest dobre dla Sahaja yogina mieć gniew. Ale jeśli ktoś mówi wam coś przeciwko waszej Matce, wtedy musicie mieć gniew. Wtedy możemy użyć gniewu. Możecie boksować tę osobę, nie ma to znaczenia. Ganesha będzie stał za wami. A Hanumana będzie z przodu. Jeśli raz go uderzycie, Hanumana zrobi to dziesięć razy. Wtedy gniew ma uzasadnienie.

Teraz ludzie mówią, że nie powinno się być chciwym w życiu. Tak, nie powinno się mieć chciwości, ale jeśli jesteście żądni wibracji, to jest to bardzo dobre. W kwestii wibracji powinniście być bardzo chciwi Gdziekolwiek otrzymujecie wibracje, musicie się pośpieszyć i starać się dostać więcej wibracji. Chciwość jest w porządku, musicie mieć tę chciwość wewnątrz was. Jeśli nie macie takiej żądzy, jak będziecie w stanie pokonać inne przeciwności?

To jest wielce zastanawiające, zawsze Mnie zaskakują ludzie, których nigdy nie jestem w stanie zrozumieć. Gdy przychodzi do nienawiści, oni są najlepsi! Jeśli chcą kogoś nienawidzić, można sprawić, że poświęcą wszystko co mają. W imię Boga, w imię narodu, w imię wszystkiego czegokolwiek chcą. Wystarczy tylko powiedzieć: “Musimy kogoś nienawidzić”. Natychmiast zgromadzą się, przejdą wszystkie próby, poświęcą wszystko, pójdą do więzień, pozabijają siebie, popełnią samobójstwo - po prostu, gdy powiecie im: “Nienawidzimy kogoś”. Lub możecie powiedzieć: ”Jesteśmy wspaniałym narodem, czymś bardzo wielkim, a to są złe narody - musimy więc walczyć”. Zrobią to.

To jest bardzo zaskakujące, że nawet w przypadku politycznej rewolucji lub ich wolności politycznej, ich poświęcenie nie zna granic. Jednego dnia oglądałam walkę Lenina. Byłam zdumiona! Ten jeden mężczyzna Lenin, będący zawsze na zesłaniu, pisał tylko: “Musimy walczyć, musimy to dostać, musimy zrobić to”. Choć był Zrealizowaną Duszą, nie pisał o duchowości, pisał o politycznej walce, trzy razy nastąpił gwałtowny przyrost i tysiące, tysiące ludzi znajdywaliście zabitych w każdym miejscu - tak po prostu. To jest bardzo zaskakujące.

Nie wachlujcie Mnie, w chwili gdy Ja mówię, nie powinniście wachlować, wiecie, to przeszkadza. Skupcie się całkowicie, to jest ważne. Bo jeśli nie koncentrujecie się, inni będą na was spoglądać i ich uwaga się pogorszy.

Ten był tak gorliwy, że nawet małe dzieci, żony, ciężarne kobiety i tak wielu mężczyzn zostało zabitych w ten sposób. I znowu powstawali, trzy razy ponownie powstawali, a czwarty raz zakończył się ich sukcesem. Po co? Dla politycznego wzrostu.

Zrobiliśmy to także w Indiach. Ludzie rezygnowali z wszystkiego co mieli, z domów, z rodzin - rezygnowali ze wszystkiego. Nawet na fałszywych guru ludzie wydali tak dużo pieniędzy, tyle robili, rezygnowali ze wszystkiego, sprzedali domy, wpakowali swoje dzieci w kłopoty, wpędzili siebie w kłopoty – robili wszystko. Ale dla właściwej rzeczy, najmądrzejszej rzeczy, jedynej wspanialej rzeczy jaka musi się wydarzyć - Sahaja Yoga, gdzie komfort wlewa się na nas przez cały czas, gdzie wszystkie rodzaje radości leją się na nas, gdzie wszystko zostaje wygładzone dla was - ludzie zaczynają tak lubić komfort i to, i tamto, że najmniejszego poświęcenia nie są w stanie zrozumieć.

Przyjdą ze swoimi problemami z żonami, dziećmi, mężami - wszystko rozwiązane. To dzieje się dalej i dalej i dalej. Rozwiążcie je! Skończcie z tym! Odetnijcie się od tego! Musicie rozprzestrzeniać Sahaja Yogę! Musicie poświęcić trochę czasu, a także trochę pieniędzy. Kto będzie to wypracowywał? Nikt nie chce was zabić, tak jak ludzie byli zabijani w Rosji, Niemczech czy w Polsce. Nikt nie chce zabrać wam dzieci, pieniędzy czy czegokolwiek - nikt tego nie chce.

Ale światło w waszej ręce musi zostać zapalone przez prawdziwe pragnienie, czyste pragnienie w was, Kundalini. To jest knot, który musi być zawsze całkowicie odżywiony. I tu Sahaja yogini zawodzą.

Ludzie nie chcą opuścić Sahaja Yogi. Nawet, gdy im powiecie: “Proszę, odejdźcie, nie możemy pomóc!” - “Nie, nie, nie, nie mogę opuścić Sahaja Yogi”. “Dlaczego? Ponieważ to jest miejsce radości. Ale byłoby coś odmiennego od istot ludzkich, ponieważ ludzkie istoty, jeśli dostaną butelkę wina, to poproszą o dziesięć więcej, aby się tym cieszyć. Jeśli pies otrzyma coś do jedzenia, to zawoła inne psy, żeby też jadły. Jeśli wrona dostanie coś do zjedzenia, zawoła inne wrony, aby jadły. To jest naturalnie w nie wbudowane. Podobnie jest z ludzkimi istotami. Ale gdy chodzi o Sahaja Yogę, to nie jesteśmy w tym doskonali. Musimy powiedzieć wszystkim naszym krewnym: “Jesteśmy Sahaja yoginami i to jest religia wnętrza, i to jest to, co jest - jeśli nie chcecie za tym podążać, nie mam z wami nic do czynienia. Dlaczego nie podążacie za tym? Każdy ma krewnych.

Tak więc w dniu Diwali, kiedy mówimy o naszym świetle, co zamierzamy zrobić z tym światłem? Czy chcemy je używać tylko dla własnego celu? Chrystus powiedział, nie stawiajcie światła pod - jak wy to nazywacie? - przykryciem. Nie kładźcie pod przykryciem. Postawcie na stole. My wszyscy musimy wyjść do społeczeństwa, musimy znaleźć sposoby i metody. Nie tylko liderzy, każdy musi wypracować to, co można zrobić, aby rozprzestrzeniać Sahaja Yogę. Gdziekolwiek idziecie: jak możemy dać Sahaja Yogę? Oczywiście nie chcę, abyście zmieniali swoje stroje - ale możecie nosić duże plakietki. Ludzie zapytają was. A wy powinniście powiedzieć: ”Tak, to jest osoba, która dała nam spokój, radość i szczęście”. W ten sposób zaczynajcie, idźcie do sklepów, w publiczne miejsca.

Ja chodzę do sklepów, aby po prostu rozprzestrzeniać wibracje - wy wszyscy musicie to robić, w innym wypadku będziecie mieć radość Sahaja Yogi tylko dla siebie, ale dopóki nie dzielicie tego, to nie będziecie mogli cieszyć się tym w pełni. Spójrzcie na Mnie. Mam wszystkie wibracje świata. Mam wszystko, powinnam być zadowoloną z siebie osobą, siedzącą w domu - w medytacji. W tym wieku, dlaczego mam podróżować wszędzie? Ja jestem Adi Shakti - dlaczego mam się troszczyć o zrobienie z każdego, tak pełnego mocy shakti człowieka? Nie ma potrzeby. Powinnam cieszyć się swoimi mocami, mogę, ale nie potrafię.

Muszę ciężko pracować. Daję Sahaja Yodze maksimum czasu, jaki ktokolwiek z was mógłby dać. Mam rodzinę, mam męża. On ma bardzo, bardzo intensywne życie. Mam wnuki. A daję maksimum czasu. Teraz widzicie, stąd do Rzymu, następnie do Francji, potem do Hiszpanii. A wy wszyscy macie po prostu sztafetę. W porządku, jestem tutaj - Włosi są trochę napięci. Potem będą mieli relaks! ”Teraz w porządku......”. Potem, co Ja robię? Przez cały okrągły rok jeżdżę z miejsca na miejsce......podróżując. Kiedy mam wszystko. Możecie pomyśleć o bogatym człowieku, który jest bardzo zajęty rozdawaniem całego bogactwa jakie ma? To jest właśnie tak.

Zatem muszę wam powiedzieć, że musicie wejść w inny wymiar waszego entuzjazmu. Sahaja Yoga nie służy naszej osobistej radości. ”Jesteśmy świętymi”. Po co? Dlaczego? Po co zostaliście uczynieni świętymi? To nie tak, że mężczyzna powinien robić tylko to lub kobieta powinna to robić lub powinno się robić to lub tamto. Nie angażujcie się w takie pokusy. Jest trzynaście pokus, które przyszły z “ubijania”. Czternasta była wielkim myśliwym mającym zneutralizować te wszystkie trzynaście.

Nie dlatego, że Sahaja Yoga chce kusić kogoś, ale one stają się pokusami, ponieważ są błogosławieństwami dla was, i błogosławieństwa zaczynacie używać jako pokusy. Teraz, dla każdego taka pokusa jest bardziej jak koń, który musi pobiec na południe lub na północ stoi i je trawę. Musicie się poruszać, ruch jest sednem, musicie poruszać się z miejsca na miejsce, chodzić od wsi do wsi, musicie chodzić od domu do domu. Wiadomość musi być rozprzestrzeniana.

Chrystus miał tylko dwunastu uczniów - a ile religii oni stworzyli? Oczywiście, to bez znaczenia, ale zawsze! Macie dać coś tak znaczącego i wspaniałego. Ale kiedy im to mówicie, to sposób w jaki powiecie jest ważny. Sposób w jaki zapewniacie jest ważny. Nie robi Mi różnicy czy od dzisiaj - ale możecie im powiedzieć kim jestem. Bez znaczenia. Jak długo mamy zamiar to ukrywać? Lepiej powiedzcie im: “Ona jest taka i taka, to jest napisane w Biblii, jest taka i taka - znaleźliśmy to. Jeśli nie chcecie tego zobaczyć nie musicie - ale tak to jest”.

Miejmy tę determinację oraz tę szczerość w wyrażaniu opinii. Spójrzcie na tych okropnych polityków. Oni mówią: “Wierzę, że część ludzi powinna być bogata, a reszta powinna być biedna. Wierzę. Wierzę w to i wierzę w tamto”. A co z wami? Wy nie tylko wierzycie, ale wiecie to definitywnie! I to jest to, co powinno być zadecydowane na Diwali, iż na następne Diwali musimy mieć więcej ludzi, dużo ludzi dla Sahaja Yogi.

Ale kiedy Ja mówię, wielu ludzi mówi Mi, że myślą, iż nie mówię do nich, lecz do kogoś innego. Powinniście patrzeć na ludzi, którzy pracują ciężej niż wy dla Sahaja Yogi, którzy są bardziej zaangażowani w Sahaja Yogę, którzy osiągają więcej w Sahaja Yodze - a nie na ludzi, którzy nie robią nic. Możecie patrzeć na Mnie.

Co robimy? Powinniście patrzeć na to. Gdzie jesteśmy? To jest najważniejszy okres. Będę w Europie co najwyżej pięć lat. Czy myślicie, że będę podróżować w wieku powyżej siedemdziesięciu lat?! Nie wiem. To jest tak ważny czas, kiedy jestem tutaj, mogę spotkać ludzi, porozmawiać z nimi, mogę wam bardzo pomóc. W ciągu tych pięciu lat musicie coś osiągnąć. Musicie zrobić skok i nadać sobie prędkości. W innym przypadku ten bardzo ważny czas zostanie utracony przez wszystkich waszych bliźnich.

Tak jak pewnego dnia mieliśmy program. Powiem wam o praktycznej stronie. To, co teraz Ja bym zrobiła, to wzięłabym adresy wszystkich ludzi, którzy dostali Realizację, zanotowałabym, napisała do nich, zobaczyła się z nimi, spotkała, dowiedziała się co się wydarzyło, dlaczego nie przychodzą.

Następnie zrobiłabym sprawozdanie, dlaczego ludzie nie przychodzą, co się dzieje, dlaczego nie przychodzą. Zawsze piszcie do nich. Zobaczycie, będziecie zaskoczeni, jeśli weźmiecie jeden numer magazynu “Reader's Digest”, tylko raz - popełnicie błąd. A oni będą wysyłać tak wiele rzeczy, znacie to? Otrzymacie taki prezent, otrzymacie - to jest dla was samochód za darmo, ta rzecz jest dla was. Kto tego chce? Ale oni będą wysyłać. Napisałam do nich: “Nic Mi już nie przysyłajcie. Nie chcę żadnego samochodu – niczego. Przyślijcie Mi tylko Reader's Digest, bardzo dziękuję. Nie jestem tą szczęściarą. Proszę nie przysyłajcie już”. Ale oni wciąż przysyłają!

W ten sam sposób, wy musicie do nich pisać, cały czas: “Dlaczego nie przychodzicie do Matki? Dlaczego nie przychodzicie do Sahaja Yogi? Sahaja Yoga jest tak ważna, tyle mi dała. Dlaczego nie chcecie tego mieć?” Musi pokazać tą żarliwość w was. A jeśli nie pokażecie tej żarliwości - pokażecie to w nieciekawy sposób: “W porządku, jest dobrze, to, tamto, jest dobrze, w porządku, to się polepsza, to jest”. To nie jest sposób w jaki macie to wypracowywać!

Kiedy jadę do Indii to wiem, że w Indiach to nie zabierze dużo czasu. Indie wypracowują to szybko. Musicie zarezerwować swoje miejsca w niebie, to jest bardzo ważne. Mam na myśli, że nawet w samolocie musicie rezerwować miejsce; a co dopiero w niebie? A tylu musi rezerwować miejsca. Jeśli wszyscy Hindusi siedzą tutaj, to co wy zrobicie?

Tak więc z tą radością, z tym szczęściem, z tym światłem na waszych twarzach, z tym pięknem oświecenia, wszyscy jesteście guru. Wyobraźcie sobie tych bezużytecznych, fałszywych guru, którzy nic nie wiedzą, ich Kundalini nie jest obudzona, nic z tych rzeczy - a ile wybudowali imperiów, nie mówię, żebyście budowali imperia, nie, nie w ten sposób, ale dlaczego nie wybudować przynajmniej chaty, aby pokazać, że coś osiągnęliście i to musi być zrobione.

Rozmawiajcie z każdym w waszym biurze, nie czujcie się nieśmiali. Widziałam ludzi stawiających wszędzie fotografie strasznych ludzi. Pójdziecie do ich biura, znajdziecie je, w autobusach je znajdziecie, wiszą wszędzie. Dlaczego nie Moja fotografia? Co tam jest ciekawego, ludzie będą was pytać, powiedźcie im - to się wypracuje.

Zaskakująco, najlepsza rzecz wypracowuje się we Włoszech. I to idzie do przodu, ponieważ znaleźliśmy paru dobrych ludzi i wy powinniście spróbować znaleźć ich i to się wypracuje. Ale nie idźcie do złych ludzi, musicie używać swojego rozróżnienia. Wiecie jak ci fałszywi guru pracują - to bardzo ważne. Mój brat powiedział Mi, że kobieta z Muktanandy - nie ma ma już Muktanandy, jest inna Amerykańska dziewczyna, hinduska dziewczyna wystylizowana na Amerykankę. Zatem kobieta z Muktanandy [uczennica], Angielka, przyszła do jego domu, domu Mojego brata - była bardzo słodka: “Chcę się z panem zobaczyć, sir”, to i tamto. I ujrzała Moją fotografię. Powiedziała na to: ”Co ta Mataji tutaj robi?” On odpowiedział: “Dlaczego? Ona jest moją siostrą”. A ta się po prostu ubrała i uciekła. Na to mój brat ją zawołał: ”Proszę, przyjdź, usiądź, usiądź. Co ty robisz?” Ona powiedziała: “Nie sir, zawsze chodzimy, spotykamy się z wszystkimi ważnymi ludźmi z miasta i rozmawiamy o tym”. On powiedział: ”Tak”. Wszystkie nazwiska sędziów były na liście. Natychmiast Mój brat wziął telefon i powiedział im: ”Nie miejcie nic wspólnego z tą kobietą!”

Ale tak to jest. Powinniście dowiedzieć się, jak podejść do ludzi. Kiedy Ja jestem tutaj to jest - powiedzmy - 200 ludzi. Kiedy odjeżdżam, jest tylko 2 ludzi. Dlaczego? Co się dzieje? Dlaczego odchodzą? Musi być jakiś powód. Nie znają Mnie. Weźcie przynajmniej ich adresy. Dowiedzcie się kim są ci ludzie. Nie ma nic złego we wzięciu ich adresów i dowiedzeniu się kim oni są. Potem umieśćcie ich na liście i wysyłajcie im listy, jeśli nie tak dużo jak Reader's Digest, to cokolwiek. Kiedy zaczniecie wysyłać im listy, to przekroczycie ich ignorancję. Światło wejdzie. Poprzez wasz ruch, waszą uwagę, światło wejdzie. Nie znacie swojej uwagi, jaką ona ma moc. Jak raz położycie na nich swoją uwagę, to światło przejdzie. Jeśli nie dzisiaj, to jutro oni wrócą. Możecie również wysłać Moją fotografię. “Spróbujcie ze zdjęciem, to jest zdjęcie, przyszedłeś na program, jesteśmy bardzo szczęśliwi”. Jeśli kontynuowanie tego nie wyjdzie, spróbujcie tego.

To jest najlepszy sposób na osiągnięcie czegoś, ale musicie myśleć i zrozumieć - ponieważ jesteście ludzkimi istotami i znacie ludzkie istoty. Po prostu postawcie się na miejscu innej osoby - co by do was przemówiło? Inna sprawa, to czuję, że ludzie powinni pisać o Mnie książki. Nie ma w tym nic złego. Ale o Mnie, piszcie książki o Mnie. Ale pewni ludzie, którzy mają już wyrobione nazwiska, którzy są uznani w społeczeństwie, którzy zostaną wzięci poważnie - oni mogą pisać książki o Mnie. Piszą książki o każdym, dlaczego nie mogą napisać o Mnie? Nie o Sahaja Yodze, możecie też o tym napisać, ale napiszcie o Mnie. Powiedzcie ludziom, że jest taka osoba, która jest rozwiązaniem, nadzieją. Dlaczego nie? Pisali o tych wszystkich okropnych guru, dlaczego nie mogą napisać o Mnie? Ale to musi być dobrze znana osoba. Przypuśćmy, że piszecie książkę, ktoś inny może ją opublikować w swoim imieniu - jeśli jesteście dobrym pisarzem. Ktoś inny może wydać i opublikować. Możemy to zrobić w ten sposób. Jest tyle metod i sposobów, poprzez które możecie zwrócić uwagę ludzi na Sahaja Yogę. Ilu ludzi wie o Sahaja Yodze?

Osoba wychodzi z więzienia, z Indii, wychodzi i jest tutaj. Bardzo znany “guru” siedzi gdzieś w Ameryce, w rogu jakiegoś brudnego zaułka i jest bardzo znaną osobą. Wszyscy są bardzo znani - jak?

I to nie dzieje się zawsze dzięki pieniądzom, to zostaje zrobione przez ludzi, stosujących własne pertraktacje. Ale one mogą być hipnotyzujące, zabucowane. Zgadzam się. Rozumiem, że jesteście wolnymi ludźmi robiącymi co chcecie, ale w swojej wolności musicie to wykonać. I dziś musicie wszyscy zadecydować, że to światło jakie mamy, ma stać się latarnią morską, a nie tylko światłem, światłem przyciemnionym. Jaki z tego pożytek?

Musimy być jak piękna wieża ze światła. Jak dom ze świateł. I każdy powinien wypracować to wewnątrz i na zewnątrz. Jeśli wypracowaliście to wewnątrz, to teraz musicie działać na zewnątrz.

Następnie, jest teraz deepawali, to nie jest tylko jedno światło. Dlatego musimy wszyscy być kolektywni, spróbujcie wejść w kolektywne życie. Kiedykolwiek to jest możliwe, spróbujcie uczestniczyć w tym wszystkim, co jest kolektywne, spróbujcie być tam, gdzie są kolektywne wydarzenia. Tam, gdzie jest kolektywnie, źródło energii płynie lepiej.

Niech Bóg was wszystkich błogosławi!

(Podczas Pudży Sahadża jogini zaczęli śpiewać pieśń zawierającą mantry z dziesięcioma imionami Shri Lakshmi. Wtem Shri Mataji przerywa śpiew.)

Fałszują. Oni trochę fałszują. Niech zaśpiewają w tonacji. Nie powinno się…, mówcie z serca i z uczuciem. Oni bardzo fałszują. Zróbcie to poprawnie. Teraz.
(Shri Mataji mówi coś w hindi albo w marathi).
Podejdźcie tutaj. Jeszcze raz. Musicie trzymać się tej samej tonacji. Zacznijcie grać w jakiejś tonacji, a wtedy oni dołączą i będą śpiewać.

Gdzie oni są? Ci, którzy śpiewają? Oni powinni być tam, widzicie to dlatego oni nie są z wami zgrani. Podejdźcie tutaj, ci którzy śpiewają. Tak jest lepiej, to była przyczyna. Musicie usiąść z muzykami i śpiewać w tonacji, dobrze?

Nie fałszować. A wtedy wibracje przyjdą. Wibracje nie płyną. Lepiej śpiewać… nie w tonacji, ale po prostu. Oni tego nie umieją. Blokuje się Sahasrara. Zaśpiewajcie to w tonacji indyjskiej.

Zaśpiewaliście całkiem nie tak. Niech ona śpiewa, ona wie jak. Widzicie, wibracje nie mogły…. Moja Sahasrara zablokowała się. Usiądź, wszyscy usiądźcie.

To są mantry, to nie jest piosenka, to mantry, widzicie? Powinno się je wypowiadać z namaszczeniem i zrozumieniem.

(Jedna z Indusek śpiewa Mahalakshmi Stotram.)

Zobaczcie, jak to trzeba zaśpiewać, nie tak, jakby was gonił tygrys. To trzeba śpiewać z namaszczeniem, to jest mantra, widzicie? Nie każdy też ma prawo śpiewać mantry. To jest coś, co wymaga namysłu i zrozumienia.

Teraz posłuchajmy jak one śpiewają, bo nie chcę znów czuć blokady na Swojej Sahasrarze. Co oni śpiewają? Co to za utwór, co śpiewają?
(Odpowiedź: 10 imion Shri Lakshmi.)

Teraz. Zaśpiewajcie to powoli, spokojnie i bez pośpiechu. Ze zrozumieniem tego, co mówicie. Jej pojazdem jest słoń, nie samolot.

(Sahadża jogini pyta czy ta pieśń powinna być zaśpiewana w jednej czy w dwóch częściach.)

Nie, w jednej. Dwie części nie są dobre. To również jest złe. Jedna część. Jedna część, ale z namaszczeniem. Każde słowo powinno być wyraźne. W końcu to są mantry, nieprawdaż? To są słowa oświecone i tylko niewielu ludzi posiada to Adhikara [prawo] – wy je macie, ponieważ jesteście Sahadża joginami – żeby śpiewać mantry. Więc zaczynajmy. Niepodzielone na części, lecz jako całość.

(Sahadża jogini mówią mantry dla 10 imion Shri Lakshmi).

Dobrze, wspaniale, widzicie, wibracje zaczęły płynąć. Teraz znacie znaczenie.

Dzisiaj, kiedy spełniamy Pudżę do Shri Lakshmi wszystko to są błogosławieństwa w waszych czakrach, które na was zesłano. Zatem trzeba to zrobić w taki sposób, by bóstwa były szczęśliwe i by spłynęły na was wszystkie błogosławieństwa.

To są mantry. Istnieje różnica między muzyką a mantrą. Te mantry oddziaływują na wasze czakry, otwierają tę część w was i zsyłają błogosławieństwa danej mantry. To jest właśnie ta różnica. Dobrze? Tak więc mantr nigdy nie powinno się śpiewać słodko ani tylko powierzchownie. To musi być bardzo głębokie, z uczuciem i zrozumieniem. A czy znacie znaczenie wszystkich 10 Lakshmi? Czy potraficie je podać, czy raczej Ja powinnam to zrobić?

Pierwszą jest Shri Adya Lakshmi. Adya jest tą, która jest Pierwotna, Pra-Lakshmi. Jak już wam mówiłam, Ona wyszła z Morza. Dlatego Matkę Chrystusa nazywamy Mary, Maria, ponieważ Ona wyszła z Morza. Ludzie nie wiedzą, dlaczego Ona została nazwana Mary. Moim imieniem, jak wiecie, jest również Nira, co oznacza wychodząca z wody.

Drugą jest Shri Vidya Lakshmi. Ona jest tą, która uczy was technik obchodzenia się z Boską Mocą. Musicie to dobrze zrozumieć. Kim jest Lakshmi? Lakshmi to jest łaskawość. Ona uczy was jak używać tej Mocy z łaskawością. Na tym polega błogosławieństwo, że otrzymujecie tę moc Adya Lakshmi, dzięki której stajecie się jak woda. Jakie woda ma właściwości? Woda posiada siłę oczyszczania, a także błyszczy. Bez wody nie możemy istnieć. Jest życiem. Zatem pierwsze błogosławieństwo polega na tym, że twarz świeci, z Adya Lakshmi, stajecie się oczyszczający i potraficie zatopić wszystko to, co materialne – wszystko, co jest lekkie, może się na was unosić.

Zatem Vidya Lakshmi jest tą, która jak już mówiłam, daje wam wiedzę – wiedzę jak obchodzić się z Boską Mocą z łaskawością. Dam wam przykład. Widziałam wielu ludzi, którzy robili bandhan, w tak toporny sposób, to …Nie, tak nie wolno robić. To jest błogosławieństwo Shri Lakshmi. Zatem jak powinniście to robić, powinniście to robić z uwagą. Widzieliście jak zawsze to robię. Nigdy nie robię tego w ten sposób! Nie mogę! Z szacunkiem. Z gracją. Ona [Lakshmi] reprezentuje w tym szacunek.

I to, że otrzymujecie tę wiedzę. Jak robić to z wdziękiem. Wszystko ma być robione z gracją – w sposób, który wygląda wdzięcznie. Zauważcie, część osób która się wypowiada, nie ma gracji.

Niektóre z osób przekazujących wiedzę o Sahadża Jodze nie ma tej gracji i mówią w sposób pozbawiony wdzięku. Całą tę grację – w jaki sposób wykorzystać Boską wiedzę – przekazuje Vidya Lakshmi

Saubhagya Lakshmi. Ona jest tą, która daje wam powodzenie. Powodzenie nie oznacza pieniędzy, ale oznacza łaskę pieniędzy. Wielu ludzi ma pieniądze, ale jest to tak jak pieniądze na ośle. Nie znajdziecie żadnej gracji w tych osobach. Czyli, że Saubhagya to nie tylko pieniądze – to oznacza również szczęśliwy los. Całe to szczęście we wszystkim, a przy tym z wielką łaskawością. To błogosławieństwo oznacza, że jesteście błogosławieni, i również ludzie, którzy was spotkają będą błogosławieni dzięki Saubhagyi.

Amruta Lakshmi. Amrut oznacza „ten, który jest nektarem [bogów]”. Jeżeli będziecie go pić, to nigdy nie umrzecie. Oznacza wieczność. Ona jest zatem tą, która daje wam życie wieczne.

Gruha Lakshmi. Gruha Lakshmi jest boginią rodziny – to ta, która jest boginią rodziny. Obecnie żadna gospodyni domowa nie musi być Gruha Lakshmi. Ona może być butem. Ona może być czymś okropnym. Bogini gospodarstwa domowego – jeżeli rezyduje w tobie, wtedy jesteś Gruha Lakshmi, w przeciwnym wypadku nie jesteś.

Następna jest Raja Lakshmi. Ona jest tą, która obdarza łaską królów. Jeżeli królowie zachowują się jak służący, to nie nazywa się ich królami. Muszą zachowywać się z godnością. Dostojeństwo i majestat króla pochodzą od Raja Lakshmi w nim. Ale Sahadża jogin nie wymaga treningu. Chodzi z głową uniesioną, jest wyprostowany i dostojny. Jest dostojny we wszystkim, co robi. Jest bardzo dostojny w obchodzeniu się z ludźmi. Wykonuje wszystko z gracją i w taki sposób, że ludzie myślą: „O, oto idzie król”.

Satya Lakshmi. To jest tak, że otrzymujecie świadomość prawdy, ale oprócz tego – świadomość prawdy istnieje, ale trzeba tę prawdę przedstawiać z wdziękiem. Nie tak: „A więc to jest prawda – miej ją!” – Nie w ten sposób! Nie musicie uderzać ludzi prawdą. Musicie umieścić ją w kwiecie i dać ją ludziom. To jest Satya Lakshmi. Oczywiście wszystkie Tattwy [zasady] Lakshmi są parasympatycznymi mocami w nas, ale tak naprawdę przejawiają się w naszym mózgu. Mózg jest Viratą. Jest Vishnu, kiedy On staje się Viratą, Akbarem. Zatem wszystkie Jego moce – zwłaszcza te moce, znajdują się w mózgu. A więc sam mózg, spontanicznie zachowuje się w taki sposób, iż ludzie myślą, że ta osoba jest wyjątkowa.

Następnie mamy Bhogya Lakshmi, dzięki której wiemy jak się cieszyć. Sahadża jogin zawsze wie jak cieszyć się wszystkim. Sahadża jogin nigdy nie jest kimś, kto się zamartwia. Może radować się czymkolwiek. Pewnego razu wspięliśmy się bardzo stromą drogą do miejsca zwanego Palithana. To było jakieś 6 mil pod górę – sześciomilowy spacer, cały czas pod górę. Dotarłam na szczyt i ujrzałam piękne rzeźby. Gdy ujrzałam te rzeźby, w ogóle nie odczuwałam już zmęczenia. Mówiłam zięciowi: „Popatrz, każdy słoń jest zrobiony inaczej”. On odpowiedział: „Matko, ja tu dyszę ze zmęczenia. Jak Ty możesz jeszcze dostrzegać te ogony słoni?” To dlatego, że potrafię się cieszyć. Powinniście umieć się cieszyć wszystkim. Przypuśćmy, że widzicie coś absurdalnego, niedorzecznego. Wtedy powinniście się śmiać i radować, to jest śmieszna rzecz, absurdalna. Nie trzeba się złościć na osobę, która zachowuje się śmiesznie, ale powinniście zrobić z tego okazję do radości. Myślę, że jest to największe błogosławieństwo, chyba jedno z najwspanialszych, że Ona daje wam moc cieszenia się wszystkim. W przeciwnym wypadku, czegokolwiek byście spróbowali, ludzie niczym nie będą się cieszyć, ponieważ stali się już tacy egocentryczni, że nic do nich nie dociera. I tu trzeba ich połaskotać (…)

Joga Lakshmi – to Ta, która daje wam Jogę. Ta moc jest w was. To jest moc Shri Lakshmi w was … co oznacza, że wy dajecie Jogę innym. Kiedy dajecie moc jogi innym, mam na myśli, że kiedy używacie mocy jogi, wtedy nie zachowujecie się jak małpy, osły czy konie, ale robicie to z wdziękiem. Zróbcie to w sposób pełen gracji.
To jest to, co nazywacie (Shri Mataji szuka odpowiednika w języku angielskim dla słowa w sanskrycie) … w delikatny, dostojny, majestatyczny sposób. Delikatny, dostojny, majestatyczny sposób – trzy słowa (po angielsku) dla jednego wyrazu (w sanskrycie). To jest właśnie to. Kiedy zaśpiewaliście w ten majestatyczny sposób, ta moc została na was zesłana. Teraz, nawet jeśli chcecie, nie możecie zachowywać się nieprzyzwoicie. Jesteście naprawieni. (Shri Mataji śmieje się).

Dobrze. Dziękuję wam bardzo.

Zatem mantry należy śpiewać z namaszczeniem i zrozumieniem. Jak to, co ułożyliście jak wiersz – pieśń. To zaśpiewaliście tak, jak trzeba. Nigdy tak: Shri – to, Shri – tamto, Shri… nie, nie, nie. To tak, jakbyście wyczytywali listę Shri Lakshmi: Obecna, obecna, obecna”? … w ten sposób.

Róbcie to z namaszczeniem, z szacunkiem i wdziękiem, ponieważ we wszystkim, co dotyczy Shri Lakshmi, musicie zachowywać się z niesamowitą gracją. Musicie używać bardzo delikatnych słów, tonów i dźwięków.

W porządku.