Programa público: "Necesidad de la Realización". Brisbane, Australia. 5 de mayo de 1987.

Me inclino ante todos los buscadores de la verdad. Hace un momento Albert os ha explicado con mucha claridad el mecanismo que hay en nuestro interior, que permite que se produzca nuestra Realización. Sin duda hay un mecanismo. Estamos en esta sala, vemos muchas luces a nuestro alrededor y hay un mecanismo detrás de ello. Pero lo que hacemos es simplemente dar al interruptor y la luz aparece. Así, todo el mecanismo ha sido construido en nuestro interior a lo largo del proceso de la evolución y ahora hemos llegado a un punto en el que tenemos que lograr el resultado de este proceso evolutivo.

En Occidente la gente lleva la búsqueda fuera de este cuerpo. Diría que tratan de descubrir el conocimiento sobre el Árbol de la Vida, pero cuando se busca la vida desde fuera, solo se puede llegar hasta un punto. El árbol solo puede crecer hasta una cierta altura. Se tiene que ir a la raíz. Este es el conocimiento de las raíces.

Ahora bien, decir que viene de la India o que viene de una región particular no es cierto. Por supuesto, al ser India un país milenario han sido capaces de profundizar más en ello pero, incluso en la Biblia hay frases como: "Apareceré ante vosotros como lenguas de fuego" y, estos centros, verdaderamente parecen lenguas de fuego. En el Corán se llama "Ases" a la Kundalini y se describe que debéis estar conectados con Dios, de lo contrario cualquier cosa que hagáis en nombre de Dios, os volverácrueles y seréis desintegrados. Esto se dice claramente. Lo mismo en cualquier religión sobre la que leáis se dice que debéis tener vuestra Realización.

Todas las religiones han hablado del Espíritu; todas ellas han dicho que debéis encontrar vuestro Espíritu. Cuando somos ignorantes respecto al Espíritu (y hay mucha gente en el "mercado"- al que llamo "mercado de gurus"- que estáinteresada), la gente no sabe qué esperar y qué encontrar. ¿Qué es el Sí mismo? ¿Qué es el Espíritu? ¿Y por qué deberíamos obtenerlo? Como dije, la cúspide de vuestra evolución es que os convirtáis en el Espíritu. Esa es la verdad: Que sois el Espíritu. Si sois el Espíritu, entonces, tenéis que alcanzar ese estado de una forma u otra; pero ese es vuestro derecho de nacimiento, ha nacido con vosotros, por eso lo llamamos Sahaja Yoga.

El significado de Sahaja es: "Saha" significa "con", "ja" es "nacido con uno". Ese es el Yoga, la unión con el Divino. El Divino es el Poder Omnipresente del Amor de Dios, que es lo más sutil de lo más sutil. ¡Omnipresente! Estáen todo y vosotros tenéis que sentirlo. Es lo que llamamos la brisa fresca del Espíritu Santo. En la Biblia no existe ninguna descripción del Espíritu Santo. La Kundalini es el reflejo del Espíritu Santo. El Espíritu Santo es el Deseo de Dios, es el Poder de Dios reflejado en nuestro interior como Espíritu Santo, como Kundalini enrollada en tres vueltas y media. Es nuestro deseo puro; el resto de nuestros deseos son impuros. Deseamos esto y lo otro y, como sabéis, según las leyes de la economía los deseos no pueden ser saciados. ¿Por qué? Porque esos deseos no son puros. Por tanto, este es el Poder de la Kundalini que reside en el interior de vuestro hueso triangular.

Mientras os estoy contando todo esto no deberíais tener una fe ciega en ello, sino que es una hipótesis. Si sois una persona científica o tenéis una mente muy lógica, entonces tenéis que entender que no deberíais cerrar vuestra mente; deberíais mantener vuestra mente abierta, verlo por vosotros mismos y, si se prueba como cierto, entonces estábien. Pero no deberíais ser personas cínicas que estén ya desafiándome; porque lo que estoy haciendo es daros lo que ya tenéis, deciros lo que tenéis, lo que os pertenece. Es vuestro por derecho, yo no tengo nada que ver con ello como tal. Pero tampoco puedo evitar contároslo.

Esta Kundalini tiene que elevarse desde su asiento, que él nos acaba de mostrar. Reside en el hueso triangular llamado hueso sacro. "Sacro" significa sagrado, eso quiere decir que los griegos ya conocían esta palabra, sabían acerca de la Kundalini y por eso le dieron el nombre de sagrado.

Cuando esta Kundalini se eleva atravesando los diferentes centros, pasa por seis centros. El séptimo estádebajo de Ella. Este séptimo centro (Muladhara) cuida de la gloria o de la castidad, o digamos que protege a la Madre Kundalini que estádentro de nosotros. El primer centro (Muladhara) es el más importante. Es el centro de nuestra inocencia. Cuando intentamos jugar con nuestra inocencia este centro se deteriora y es el centro que protege a la Kundalini. Cuando este centro es dañado podemos tener muchos problemas. Hoy en día se ha alzado un gran grito sobre esta enfermedad mortal llamada SIDA: hay que luchar contra ella. Hemos hecho algo mal, eso debemos aceptarlo y, después, tenemos que combatirla. No es difícil luchar contra esta enfermedad si aceptáis que habéis perdido vuestra inocencia.

El problema es que cuando la gente comenzó a tener el conocimiento del árbol, realmente se volvieron locos, no sabían qué hacer consigo mismos. Una vez que terminaron con esto y aquello se empezaron a comer la nariz, los ojos, los dientes y cosas por el estilo. Se elevó una ola de locura entre la gente. No sabían qué hacer, así que, también comenzaron a practicar el sexo. También le echaría la culpa a Freud por ello. En India no aceptarían en absoluto a Freud, no tiene ningún sentido. Nadie puede aceptar esa teoría en la que se dice que constantemente tenéis deseos carnales por vuestra madre. Por supuesto, esto es ridículo para nosotros. Pero todo lo nuevo ha de ser aceptado; esa es la idea actual. Cualquier cosa nueva que llega a vosotros hay que aceptarla. Pero algo nuevo puede que no sea correcto. El otro día estábamos en un banquete y mi vecino de mesa era el embajador de Méjico. Me dijo: "Sé que no le gusta Freud y le gusta Jung, pero Jung hablaba de las viejas cosas de siempre. Dije: "Las mismas cosas viejas pero con algo nuevo en ellas".

La evolución tiene lugar de tal manera que primero aparece el árbol, luego las ramas, después las hojas, después las flores y de las flores sale el fruto. Pero si alguien hace una flor y os la da, sabréis que es de plástico. Debe existir una base, detrás debe haber una tradición; debe estar en nuestros libros antiguos, debe haber sido descrito por la gente que vivió antes. De repente alguien como Freud aparece y lanza una nueva teoría. La gente sale como setas contando historias y nosotros nos las creemos. Así que, le dije al caballero: "De acuerdo, hemos comido todo tipo de alimentos antes, pero no nos hemos comido la mesa. ¿Por qué no nos la comemos? ¡Si es algo nuevo!" De la misma manera comenzamos a aceptar cualquier cosa que sea nueva, porque "esto es nuevo, esta es una nueva idea, deberíamos aceptarla".

Es una carrera de locos, de verdad, una auténtica carrera de locos. Toda nuestra atención se va a estas tonterías. Por ejemplo, las modas que han surgido. Se trata de empresarios que son materialistas, que quieren volvernos locos, constantemente cambiando de una moda a otra. Ahora en Inglaterra no encontráis a nadie con pelo, porque los pobres intentaron esto y aquello y al final se convirtieron en punkis. Yo les dije: "Ahora punkis, ¿y después?" Dijeron: "Madre, ya no estás al día, ahora son cabezas rapadas".

Esta es la situación: hemos rendido todo nuestro Ser, nuestra forma de pensar, a alguien que nos hace jugar de esta manera. El materialismo es para nosotros, no nosotros para el materialismo. La materia es para nosotros; tenemos que dominar esta materia. En todo momento el Espíritu domina a la materia y cuando el Espíritu emerge utiliza la materia para sus propios propósitos; no estádominado por la materia. Nadie puede dominar a una persona que es el Espíritu. Pero estamos tan perdidos en ello - probando cosas nuevas, saltando como locos de una cosa a otra - que no vemos el sentido de la cosas, como el comerse la mesa. No tenemos ideas propias; o reaccionamos en contra o aceptamos las ideas de otros.

Si alguien nos cuenta sus ideas diremos: "¡Oh, es grandioso! Pero, ¿por qué? ¿Por qué es grandioso? Debe estar respaldado por ciertas premisas. En primer lugar debemos averiguar si tiene relación con alguna tradición, con algún libro antiguo, con algún profeta, con alguna encarnación que viniera a la Tierra. Estos no fueron personas inútiles ni falsas; no nos contaron mentiras. Pero somos reaccionarios. Como ahora que vemos que el cristianismo ha fallado, las iglesias están fallando, así que, reaccionamos. ¡No, puede que el cristianismo haya fallado pero, Cristo no!

Ayer tuvimos una pareja muy interesante. Uno vino para entrevistarme y el otro era un fotógrafo. El fotógrafo era un cristiano fervoroso que me dijo: "Madre, ¿quiere decir que todo lo hicimos mal?" Le contesté: "No, amas a Cristo, ¿no es así?" "¡Sí, amo muchísimo a Cristo!" Le dije: "Entonces lo obtendrás; si amas a Cristo lo conseguirás. Pero si estás ocupado organizando a Cristo, entonces, resultarábastante difícil. No puedes organizar a Cristo, no puedes ordenarle y no puedes utilizarlo para tus propios intereses, para hacer dinero, para construirte enormes palacios". Podéis ver lo que estáocurriendo ahora en el Vaticano. Tienen grandes problemas con la mafia y no quieren oír hablar de ello. ¡No, nada!, hacen oídos sordos a ello. ¿Cómo puede ser que estas personas que hablan de rectitud, de virtud, de valores, hayan llegado a este extremo?

Lo mismo ocurre en India; la religión hindú se ha ido a pique, se ha hundido totalmente. Están utilizando la misma magia negra y las mismas cosas viejas que se hacían en los pueblos. Ahora han venido a las ciudades. En los templos están vendiendo drogas horribles a la gente que acude. ¿Es eso el hinduismo? ¿Qué ocurre con el Islam? Veis cómo la gente del Islam estápeleando entre sí, cuando el Islam es entrega. Todos luchan entre ellos. ¿Es esa la religión que Mahoma predicó? ¿Y qué pasa con los budistas? Es otra gente absurda, extremadamente materialista.

Todas las religiones se han ido a pique. ¿Por qué? Porque no entendieron el punto más importante. Y ese punto es que debéis estar conectados a Dios. Tenéis que nacer de nuevo. No consiste en daros un certificado de "he nacido de nuevo" y que vayáis diciendo: "¡He nacido de nuevo!" Una vez una mujer así vino dispuesta a pegarme. Me empecé a reír de ella. Esta mujer que había nacido de nuevo venía a pegarme. ¿Para qué? No podéis certificaros a vosotros mismos. Este autocertificado o el certificado que alguien os diera son absurdos. Debéis tener los poderes del nacido de nuevo. Los nacidos de nuevo tienen poderes propios que se manifiestan y no van por ahí diciéndolo.

Ahora bien, ¿cuáles son los poderes de una persona que ha nacido de nuevo? En primer lugar una persona así es tranquila, pacífica; automáticamente se vuelve una persona íntegra, automáticamente. No tengo que deciros: "¡No hagáis esto, no hagáis lo otro!" Eso se acabó con Moisés. Nada más de eso. En cuanto os convertís en el Espíritu, sencillamente abandonáis todas las cosas que son destructivas para vosotros, automáticamente. No se necesita hacer ninguna presión, ninguna advertencia, nada de eso. Automáticamente sucede, porque el Espíritu es la Luz y obtenéis vuestra Iluminación.

Suponed que estoy sujetando una serpiente en mi mano y que todo estáoscuro, si alguien me dice: "¡Es una serpiente!" Yo digo: "No, es una cuerda, estoy sujetando una cuerda". Pero si hubiera luz, inmediatamente la soltaría. De una forma sencilla, nadie tiene que decirme nada, viene la luz y la suelto. De esta misma manera vosotros sois personas iluminadas. Podéis saber lo que es verdadero y lo que es falso. Por ejemplo, alguien sale de la cárcel -incluso de las prisiones indias- algunas personas que acaban de salir de la cárcel no saben qué hacer consigo mismas. Y entonces se visten con ropas de color azafrán y se van a Alemania o quizáa Australia y allí se convierten en grandes "babajis". Estos grandes "babajis" se sientan en lugares importantes de las ciudades y todo el mundo les rodea, les dan dinero, les dan su propia vida. Y solo por dar charlas sobre el amor y cosas así.

¿Son almas realizadas o no? ¿Cómo lo descubriréis? No sabéis si son almas realizadas porque no estáis en un punto absoluto, todavía estáis en un entendimiento relativo. Como este hombre viste así y se sienta de una forma muy tranquila ya debe ser un "babaji". No sabéis reconocer si una persona es verdadera o no. Tampoco me podéis reconocer a mí si estoy diciendo la verdad o no. Hasta que no os convirtáis en un Ser Absoluto, no lo podréis saber.

Entonces lo que sucede es que, cuando la Kundalini se eleva y atraviesa vuestra área de la fontanela, también empezáis a sentir en la punta de vuestros dedos. Los dedos no son otra cosa que centros del sistema nervioso simpático, que os están indicando la Verdad. Si se siente la brisa fresca fluyendo de esa persona, entonces es verdadero; si no la tiene, entonces no lo es. Hay muchas personas que proclaman ser grandes pero no lo son. Al final lo descubrimos y nos quedamos sorprendidos de cómo son. No sabemos, ¿cómo ha podido fallar nuestro cerebro? ¿Por qué nuestra inteligencia no ha podido mostramos con claridad lo que le pasaba a este señor? Porque aún no somos eso. Tenemos que admitir humildemente que todavía estamos a nivel de la consciencia humana y que debemos estar en la consciencia del Espíritu. Esa es la dimensión que debemos alcanzar, de lo contrario no podremos juzgar las cosas correctamente.

En este país hay ciertos problemas, en todo el mundo hay problemas, problemas con la bomba atómica... Todos los días oímos hablar de este y aquel problema y todos son creados por los seres humanos. Imaginaos, gente muy inteligente y buena que se han creado problemas a sí mismos matándose unos a otros, fabricando bombas y cosas así, protegiéndose unos de otros. Ningún animal hace eso. Solo los seres humanos se intentan proteger unos de otros; todo el tiempo están preocupados de que alguien les ataque, no se sienten seguros de sí mismos. La razón es que no han alcanzado ese estado absoluto.

Ahora ha llegado el momento de que decidáis entre solucionar constructivamente los problemas o destructivamente. Mediante discusiones, disputas y cosas así no vais a alcanzar nada hasta que no haya una transformación completa en la mente humana. Y la transformación solo es posible cuando os convertís en el Espíritu, porque el Espíritu es el Ser Universal en vuestro interior. Y os hacéis colectivamente conscientes, es decir, os iniciáis en un sentimiento universal; empezáis a sentir a la otra persona en la punta de vuestros dedos. Y si sabéis cómo corregirla, habréis corregido a esa persona.

Este es el juego del Amor de Dios; es tan sencillo que incluso los niños pueden hacerlo. Muchos niños, cuando se meten los dedos o los pulgares en la boca, según Freud no tiene sentido, pero según nosotros están sugiriendo qué centros tenéis obstruidos. Para entender a vuestros hijos tenéis que ser almas realizadas, porque su entendimiento todavía no ha madurado. Hasta que no os convirtáis en almas realizadas no sois personalidades maduras para juzgar nada. A ese nivel, cualquier cosa que juzguéis tendráun punto de vista distinto.

Podéis coger a diez niños pequeños que sean almas realizadas (tenemos muchos de esos) y tapar sus ojos. Entonces preguntadles: "¿Qué le pasa a esta persona en particular?" Todos levantarán un dedo u otro. Si es este dedo (índice izquierdo), significa que esa persona se siente culpable por cualquier cosa (es el Vishuddhi en el lado izquierdo); o si es el (índice) derecho, significa que habla demasiado y que tiene problemas aquí.

Este conocimiento se convierte en algo propio. Este es uno de los poderes que os he descrito. Que sentís la consciencia colectiva en vuestro interior. Todo lo que conseguís en vuestra evolución es un proceso viviente. No es un proceso muerto, es un proceso vivo por el que vuestro sistema nervioso central puede sentir lo que hay a vuestro alrededor, lo que hay dentro de vosotros. Lo que llamáis sistema nervioso parasimpático se activa y podéis entender el parasimpático, mientras que cualquier médico os diráque no se sabe mucho acerca de él. Todo esto es lo que os sucede e incluso si sois niños sabéis cómo mejorar la situación.

El segundo poder que conseguís es que podéis subir la Kundalini de otra persona, como una vela encendida puede encender otra. Pero no podemos tratar con gente que sea desagradable, superficial o estúpida. No estápensado para ellos, sino para personas que sean buscadoras, intensas; ellos son los elegidos y a los que hoy en día se llaman buscadores. Puede que sean drogadictos o cualquier cosa, no importa; han estado buscando de verdad. Puede que hayan tomado como bueno algo malo o hayan cometido algunos errores, no pasa nada. Todo es perdonado. Conseguirán lo que quieren porque han estado buscando intensamente, queriendo de verdad ser el Espíritu. Es el deseo puro de la persona el que hace que funcione, no la persona que solo lo quiere por algún motivo egoísta o por ciertas ideas de poder.

El tercer poder que se consigue es que la persona se vuelve totalmente dinámica. Trabaja muy duro en horas de oficina, puede hacer muchas cosas que nunca antes había hecho. Conozco a alguien que nunca había hecho nada artístico y que de repente empezó a pintar. También sé de otro que nunca había sabido qué era la poesía, porque es un jurado de cuentas y había estado tratando con dinero todo el tiempo, y que de golpe comenzó a escribir poesía. Y además lo hizo en Urdu, que es un idioma muy difícil. Ese es el dinamismo que se desarrolla.

Aparte de eso, desarrolláis un sentimiento especial de unidad con otras almas realizadas. La amistad y la fraternidad son cualidades tan excepcionales que nunca habíais visto gente así, ni siquiera las personas que van a luchar a la guerra. No tienen ese amor ni esa comprensión pura ni esa relación pura que encontráis entre los que son almas realizadas. Había una chica que tuvo su Realización y que viajó a Sicilia; otra era diplomática, tuvo su Realización en Roma y fue a Sicilia. Estaban sentadas en dos esquinas del mismo restaurante, se miraron y sintieron las vibraciones. Una se levantó y le preguntó a la otra: "¿Sientes brisa fresca en las manos?" Le dijo: "¿Tienes la Realización de Shri Mataji?" Le contestó: "¡Sí, la tengo!", y se abrazaron. Estaban tan contentas. Me decían: "¡Madre, tal felicidad y gozo no lo habíamos sentido nunca con nadie!" Esa seguridad, esa ayuda...

A cualquier lugar del mundo que vayáis están con vosotros vuestros hermanos y hermanas en pureza. No quieren nada, sin lujuria, sin avaricia, simplemente sintiendo la unidad. Una raza así ha surgido ahora en Australia, gracias a Dios. Tenemos muchos ashrams y mucha gente y Australia estácreciendo muy deprisa. Básicamente los australianos están en la tierra misma de la inocencia. La deidad de la inocencia es vuestro Uluru y la gente de Australia con la que me he encontrado tiene una bendición especial de Dios; consiguen la Realización muy deprisa, la mantienen y crecen muy rápidamente. Debo decir que otra gente así son los italianos y los austriacos. Lo están haciendo muy bien. Diría que los ingleses son muy buenos, pero tenéis que trabajar duro con ellos. Si os esforzáis con ellos, pueden crecer bien. Así que, en todo el mundo, ahora hay catorce países en los que tenemos gente viniendo a Sahaja Yoga.

No tenéis que pagar nada, ¿cómo podríais pagar? Es decir, pensáis en una cosa. Pero es ridículo que la gente piense que hay que pagar por todo. Si le tuvierais que decir a una semilla que germinara, ¿cuánto le pagaríais a la Madre Tierra? ¿Cuánto dinero cobraría por una cosa así? Esto es algo que la gente no entiende. Cualquiera que pida dinero o que viva del dinero ganado en nombre de Dios no puede estar conectado a Él. No podéis ganaros la vida en nombre de Dios, no podéis hacerlo. Es algo muy sencillo; eso es pecado. Por supuesto, me han dicho que cuando viajo la gente tiene que gastar dinero. Yo gasto el mío; gracias a Dios tengo suficiente. Pero suponed que estuviera en la condición de Cristo. Entonces la gente hubiera pagado por este billete de avión. Estábien, no importa. Él no necesita pagar por vuestra salvación. Podéis pagar un billete de avión, muy bien, pero Él no necesita nada, ¿no? De la misma manera, yo no necesito nada. Lo que necesito es ver que mucha gente obtiene su Realización y así se convierten en el Espíritu. Por la gracia de Dios estáfuncionando muy bien en Australia, sorprendentemente lo estáhaciendo. Y estoy segura de que todas estas cosas también funcionarán hoy aquí, en Brisbane.

La otra cosa buena de Sahaja Yoga es que os asentáis con buenos matrimonios. Celebramos setenta y un un matrimonios el año pasado y el cien por cien de ellos ha sido un éxito. Tienen hijos preciosos, muy hermosos, y están llevando una vida muy dulce juntos. Es sorprendente cómo, de la inmundicia de ese sinsentido que había, de esas ideas de destruir la humanidad entera, han surgido estos lotos tan bellos. Cuando veo eso, olvido que hay muchos más que tienen que salir de ahí. Tiene que funcionar. Hay muchos que pueden recibirla y convertirse en lotos que llenen de fragancia el Universo entero. Creo que es un trabajo de algunos años más. Estoy segura de que mucha gente conseguirásu Realización, pero aquellos que no la quieran, que sean inflexibles, que no quieran tener las bendiciones de Dios, serán juzgados porque este es el día del Juicio Final. Espero que hoy la mayoría de vosotros obtenga su Realización.

Me gustaría que alguno de vosotros me hiciera preguntas. Pero haced preguntas relevantes y no solo para atacarme porque, no he venido aquí para ser elegida ni nada por el estilo. Haced preguntas sencillas. ¿Podéis darme agua? Tantas charlas, de la mañana a la noche. ¡Sí, por favor!

Pregunta: ¿Es posible que aquellos que enseñan sobre el Espíritu difieran en ciertos aspectos?

SM: Al principio así es, un poco, porque todavía no están asentados. Tienen que madurar en Sahaja Yoga, sin duda, por eso al comienzo difieren un poco, pero no mucho. He visto que al empezar hay algunas diferencias, porque uno ha de madurar en primer lugar. Una vez que han crecido, no difieren. Van al unísono entre ellos. No hay ninguna diferencia.

Pregunta: ¿Hay que sentarse en una postura especial cuando se practica esto o puede hacerse en cualquier momento de cualquier (manera) (inaudible)?

SM: ¡No! En Sahaja Yoga os convertís en el Espíritu. Entonces no tenéis que meditar mucho (unos diez minutos o así es suficiente), y no hay ninguna restricción en particular respecto a ello. Os podéis sentar de la manera que os guste, no hay ninguna limitación porque os convertís en el Espíritu. Lo único es que tenéis que entrar en consciencia sin pensamientos. Ese es el primer estado, al que llamamos Nirvichara, y para conseguirlo tenéis que sentaros y rechazar cualquier pensamiento que entre en vuestra mente. Simplemente decid: "esto no, esto no" y de repente, como vuestra Kundalini ya estáahí arriba, os quedáis en consciencia sin pensamientos. Una vez que estáis en consciencia sin pensamientos, podéis seguir así unos cinco minutos más o menos y ya está. No se necesita mucho tiempo porque estáis en meditación.

Pregunta: Ese señor dice que por experiencias anteriores ha visto que no es posible tener un momento en el que no haya pensamientos.

SM: Es verdad, no se puede hasta que la Kundalini despierta. Un pensamiento surge y se desvanece, entonces otro aparece y se va, pero hay un pequeño espacio en medio, al que llamamos en sánscrito "Vilambha". Son espacios muy pequeños. Lo que sucede es que con el despertar de la Kundalini, estos dos pensamientos se alargan y este Vilambha aumenta. Conseguiréis esto automáticamente, no tenéis que preocuparos por ello.

Pregunta: ¿El despertar de la Kundalini es bueno para los niños?

SM: ¡Es excelente! Los niños son los mejores, es decir, no tienen complicaciones. Los adultos somos complicados, estamos en el lado izquierdo o en el derecho, tenemos dificultades. Los niños son muy equilibrados, son los mejores. Cuantos más, mejor. Les dije que trajeran a todos los niños aquí y habría estado muy feliz en su compañía. Muchos de ellos puede que hayan nacido ya realizados.

Pregunta: ¿Cuál es esa sensibilidad de los niños? Si son sensibles, ¿cómo se les puede proteger de ser dañados por otros?

SM: Se conocen a sí mismos; son muy inteligentes. Y se les dice cómo hacerse una protección alrededor de su cuerpo y lo hacen. Son muy dulces; hacen pequeñas cosas con sus manos, como subirse la Kundalini. Y si ven a un hombre horrible, inmediatamente empezarán a hacer así (a subirse la Kundalini) Son muy activos. Debo decir que son muy buenos.

Pregunta: ¿Qué se les enseña para eso?

SM: Sí, es lo que llamamos bandhan, es decir, una especie de protección para vuestras auras. Lo ponéis con vuestras propias manos porque las vibraciones empiezan a fluir de las manos. Entonces simplemente hacéis un bandhan. Y los niños lo hacen inmediatamente. Son muy rápidos; son tremendos. Son los que protegen. Un padre quiso tener su Realización pero no lo lograba. Así que, se sintió tan frustrado que se postró a mis Pies. Pero su hijo saltó a su espalda y empezó a usarla como un tobogán para que su Kundalini subiera primero. Resultó muy interesante el modo en que el niño reaccionó.

Pregunta: ¿Cómo comenzó Usted esto? ¿Cómo se inició en ello?

SM: No fui iniciada. Lo tengo desde mi niñez. Sé que querríais saber sobre mí, pero es mejor que primero os conozcáis a vosotros mismos y entonces me conoceréis mejor, ¿de acuerdo?

Pregunta: Esa mujer pregunta si se abandonaría el plano presente de consciencia simplemente teniendo la Realización. Dice que ha venido aquí para aprender pero que no debería ocurrir que se perdiera el actual plano de consciencia. ¿Es esa la pregunta?

SM: ¡No, no se pierde! ¡No, no, nada de eso! ¡No sucede así! De hecho, lo que ocurre es que conseguís una consciencia nueva adicional, en vuestro interior. Verdaderamente estáis ahí, mucho más alertas, conscientes absolutamente; pero además sumáis una consciencia que es la del Espíritu. No se pierde nada de lo que hay. Digamos, por ejemplo, que tenéis un hermano y tenéis sentimientos muy buenos hacia él; por ejemplo, cuando obtenéis la Realización, veis que es un buen chico y le perdonáis con todo vuestro corazón; le amáis y perdonáis lo que estámal en él. Veis sus buenas cualidades porque os volvéis completos. Vuestros juicios difieren. Os reís de vosotros mismos. Lo que estaba mal en él ya no estáahí. "Yo estaba equivocado en ese momento". No os importa aceptar ese punto: "Estaba equivocado, no ahora, entonces".

Otra cosa es la siguiente: Suponed que tenéis un hábito en particular y no podéis superarlo, os resulta imposible. Aunque queráis no lo lográis. Ahora sois tan poderosos que ni lo miráis. No queréis tenerlo nunca más. Simplemente no os gusta. Lo diría de la siguiente manera: Un animal puede pasar por un camino sucio; no siente la suciedad ni la inmundicia, no huele a nada. Pero en el ser humano no es así. De la misma manera, al alma realizada no le gusta nada que sea incorrecto. Se vuelve recto y virtuoso automáticamente y no impone nada a los demás. Son gente virtuosa, recta, viven en su propia gloria. Así es cómo la consciencia adquiere una bella forma. ¿Algo más, por favor?

Pregunta: ¿Cree en la reencarnación?

SM: ¡Sí, por supuesto!, existe la reencarnación, sin duda alguna. Y cuando Cristo dijo: "Volveré de nuevo", eso significa que hay reencarnación. Pero la cosa más importante es lo que sois ahora, y qué es lo que conseguís; ¡eso es lo más importante! No deberíamos preocuparnos de lo que fuimos en vidas pasadas. ¿Qué importa eso? ¿Sí, por favor?

Pregunta: ¿Es su Espíritu uno con su ser mental y físico o estáseparado de él?

SM: ¡Lo ilumina todo! Veamos, ¿podéis decir que esta luz que nos estáiluminando es una con nosotros o sin nosotros? Veis que la luz es algo distinto. El Espíritu estáseparado de nosotros, sin duda, pero lo integra todo. La razón es que vemos. Por ejemplo, ahora estáis sentados en un lugar iluminado, pero suponed que estuvierais sentados en la oscuridad. Os abalanzaríais unos sobre otros, no sabríais cómo estar de pie con los otros, no habría integración. Por tanto, la luz en el campo físico, mental y emocional de nuestra vida es completa y estátotalmente integrada. Esa era una buena pregunta.

Pregunta: Cuando una persona estáiluminada, ¿puede darlo a alguien más?

SM: ¡Por supuesto, por supuesto! Cuando estáis iluminados, podéis iluminar a otra persona. Ese es el poder que conseguís.

Pregunta: ¿Cómo ocurre?

SM: Sucede porque os convertís en eso. Suponed que hay una vela. Esta vela no estáencendida, ¿de acuerdo? Ahora la enciendo y entonces, con esta vela, puedo encender cualquier otra vela. Es tan sencillo como eso (Madre ríe). ¡Es tan simple! Todo lo que es divino es sencillo; todo lo que es humano es complicado. Tomadlo así. Es extremadamente simple.

Pregunta: En su discurso, se ha referido a la Kundalini como "Ella". ¿Es porque Usted es una mujer?

SM: ¡No, no, no! Ella representa el aspecto femenino. Es la Shakti (el Poder), el lado femenino. Por eso la disputa sobre mujeres y hombres es una verdadera falacia. No hay nada de eso; coexisten juntos. Es como la Luna y la luz de la Luna, como el Sol y los rayos del Sol, como Dios y la Kundalini, como la palabra y su significado.

Pregunta: ¿Es exacto decir que la energía Kundalini asciende y se encuentra con otra energía que viene de fuera?

SM: ¡Sí, es el Poder Omnipresente! Cuando la Kundalini asciende, lo que hace es que ilumina un aspecto más sutil de nuestros nervios, nuestro cerebro; lo ilumina todo. Y al hacerlo, comenzamos a sentirlo. La iluminación que conseguimos es por nuestra conexión con el Poder Omnipresente. Estáahí, existe desde antes, pero no lo podéis sentir normalmente. Cuando la Kundalini asciende, vuestros nervios se iluminan tanto que podéis sentirlo. ¿De acuerdo? Puede que ya lo estéis notando; creo que sí. Bien, ¿lo hacemos ya? ¡Vale!, una pregunta más.

Pregunta: He oído ciertas historias sobre que es peligroso despertar la Kundalini. ¿Por qué existen esas historias?

SM: Las historias son porque la gente que no estaba autorizada ha intentado elevar la Kundalini. La persona que ha de subir la Kundalini debe estar autorizada por el Divino. Una persona así debe tener un carácter puro. Estos otros, sencillamente, intentan elevar la Kundalini y la Deidad del último chakra, al que llaman chakra de la inocencia, es el que se enfada, y así es cómo se meten en problemas. Como os he dicho, este es el chakra que cuida de... En el caso de las personas que no están autorizadas a hacerlo, digamos que de una manera superficial se puede explicar así: es como la persona, que no sabe nada de electricidad, mete el dedo en el enchufe. Recibe una descarga. Pero es mucho peor que eso. La persona que no tiene un carácter apropiado o una vida adecuada e intenta estos trucos se mete en problemas; no por la Kundalini, sino por la Deidad que cuida de su castidad.

Estas historias están ahí y naturalmente hay personas que cuentan estas historias sensacionales. A la gente le gusta y muchas personas las siguen. Lo que quiero decir es que es muy peligroso seguir todas estas cosas equivocadas. Debo haber dado el despertar de la Kundalini a miles y miles de personas y nadie ha tenido ningún problema. Ella es vuestra Madre y, como tal, os ha dado vuestro nacimiento llevándose consigo todo vuestro dolor. Ella absorbe todo el sufrimiento; no os da ningún problema en absoluto. Como mucho, puede que sintáis un pequeño hormigueo o algo así. Quizási alguien estáposeído, puede que empiece a saltar un poco; si hay un hombre poseído, le puede pasar, pero hasta ahora no hemos tenido ninguna experiencia rara de ese tipo. La gente que ha hecho meditación trascendental se pone a saltar. Eso lo he visto, también en personas que han hecho magia negra; empiezan a saltar frente a mí. También los "rastafaris" lo hacen. Hay algunas personas que reaccionan así porque están todos poseídos, no son gente normal. Saltan un poco, pero podéis traerlos aquí; no es tan difícil.

Pregunta: ¿Qué le sucede al Espíritu después de la muerte en la tierra?

SM: Hablaremos de ello más adelante; es un tema muy largo. El Espíritu, cuando morís, tiene diferentes tipos de existencia después de la muerte. Depende: Si sois un alma realizada sois un pájaro libre, hacéis lo que queréis. Pero si no lo sois, entonces pertenecéis a categorías diferentes y de acuerdo a vuestra categoría vivís y existís. Pero creo que es un tema muy largo y en otra ocasión os hablaré de ello, ¿de acuerdo? ¿Sí?

Pregunta: No sé por qué, pero me resisto a ser iluminado.

SM: En primer lugar, usted tiene un problema de hígado, señor, y mucho calor en el cuerpo. Si coloca su mano izquierda sobre él el calor se reducirá. No, no, la mano izquierda en el lado derecho. Hay mucho calor y la resistencia viene de ahí. El hígado (caliente) es algo horrible porque genera todos los problemas. Ponga la mano derecha así. El hígado os hace pensar y pensar constantemente. ¿Algo más?

Pregunta: ¿Qué es lo que provoca sufrimiento y miseria en este mundo y por qué la gente se engaña unos a otros? (él también siente esa angustia).

SM: Esta pregunta es buena. Pero te refieres a por qué los seres humanos se tratan entre sí de esa forma, ¿no? ¿Qué hacer? Esa es la pregunta que os hago. Toda esta estupidez, ¿por qué estáahí? Estáahí porque los seres humanos todavía no son el Espíritu. Necesitan transformación; todos ellos necesitan transformarse. Pero imaginad que mañana viene Hitler y me pide la transformación. Yo le contestaré: "Lo siento, ya veremos en la próxima vida". ¿Sí?

Pregunta: Al eliminar el estrés de otra gente, ¿lo absorbe su cuerpo o entra como dolor en Usted?

SM: ¡No, nada de eso! ¡Yo no quito nada! Es solo un estado de mente que se vuelve iluminado por el Espíritu. Simplemente os relajáis, eso es todo. Estáen vuestra propia voluntad. Imaginaos (señalando los micrófonos) que este estáencendido y este otro apagado. Funciona de la misma manera, pero yo no actúo sobre ello. Estádentro de vosotros, sencillamente funciona en vuestro interior. La Kundalini misma, cuando se eleva, os relaja automáticamente. Así que, ¿por qué me ha de doler?

Pregunta: Ella pregunta si le doleráen caso de que se cargue con el estrés de otra gente.

SM: ¡No, no! Al principio recomendaría que no se hiciera porque cuando se comienza uno no sabe cómo hacerlo adecuadamente, pero una vez que se ha madurado, nada puede ocurrir. Es como cuando a algo que aún no ha madurado se le puede dejar huella, pero una vez maduro, estáperfectamente bien. Primero tenéis que madurar. Eso cuesta un mes más o menos; después estábien.

Pregunta: ¿Por qué una persona se estresa? ¿Es porque sus chakras están bloqueados?

SM: ¡Sí, y mucho! Bloqueados o desequilibrados, especialmente desequilibrados. El desequilibrio es muy grande porque los chakras son así (lo demuestra con sus manos, juntando las yemas de los dedos) Imagináoslo, ¿de acuerdo? Si lo empujáis demasiado hacia este lado, se produce un desequilibrio y el chakra se bloquea aquí. Esto puede suceder en el lado izquierdo o en el derecho; puede ser en cualquiera de los lados. Esto es debido a desequilibrios.

Pregunta: Siento la búsqueda de lo material y también la búsqueda de lo espiritual. Pero mientras sea joven, ¿debería entregarme a la búsqueda material o a la espiritual?

SM: Si llegas al Espíritu, consigues lo material automáticamente. Toda la materia estácontrolada por el Espíritu. Es muy sorprendente cómo lo conseguís. Entráis en el Reino de Dios. Os asombraráver que en Inglaterra hay mucho desempleo; la gente no consigue trabajo en absoluto. Hay mucho paro, pero ningún sahaja yogui estádesempleado, ni siquiera uno estáen paro. El otro día un señor pretendía venir de París a Australia para asistir a uno de nuestros seminarios. Quería venir. Era al otro lado del mundo y estaba bastante ilusionado, pero no tenía dinero. De repente consiguió el dinero que hubiera ganado durante ocho años. De golpe logró ese dinero y aquí está.

Suceden muchos milagros como ese. Os contaré un milagro de Australia; es muy interesante. Una niña pequeña me escribió una carta en la que decía: "Madre, quiero ir y verte en India, pero no tengo suficiente dinero". Ella y su madre, las dos querían ir. Se celebró una fiesta en el colegio y la niña llevó una baratija para vender. Cuando la profesora la vio, le dijo: "esto es oro, sí, oro, mejor que se lo lleves a tu madre". Y cuando fueron a la joyería, la cantidad que les dieron era la misma que necesitaban para ir a India. Así pues, se os ayuda de muchas maneras. No conocéis el reino de Dios. Es muy diferente; es tan eficiente. Trabaja muy deprisa. Aún no habéis entrado en ese reino.

Pregunta: Usted ha hablado de los desequilibrios o bloqueos en los chakras. ¿Cómo nos hacemos conscientes de ellos y cómo los corregimos?

SM: Eso es lo que tenéis que aprender. Es muy sencillo. Una vez que tenéis la Realización, debéis venir a nuestros centros y os diremos cómo hacerlo. Es muy simple. Hay unos cuantos métodos por los que podréis limpiar los chakras. Pero tenéis que venir a nuestros centros. Debéis respetar vuestra Realización y prestarle un poco de atención. Porque para la gente es como comprar Coca Cola en un bar, pero la Realización no es así. Es la cúspide de vuestra evolución; es lo más grande y ha de ser respetado como tal. La gente viene a mis charlas y estábien, pero no intentan establecer su Realización. Tenéis que trabajar por ello y convertiros en maestros. Debéis llegar a ser vuestros propios maestros. Todos podéis. ¿Algo más?

Pregunta: Cuando habla de Realización, ¿es que cuando se obtiene se mantiene o se puede perder o tener solo destellos de ella?

SM: ¡No!, veréis, funciona así: Si tenéis la Realización, debéis cuidar de ella, nutrirla y desarrollarla. Es como una pequeña planta. Cuando tenéis una planta pequeña, debéis hacerla crecer. Una vez que se convierte en árbol, entonces muchos vendrán a refugiarse bajo él, ¿no es verdad? De la misma manera tenéis que cuidar de vuestra Realización. Puede que no disminuya, pero no tendrámucho efecto y siempre estaráen una posición peligrosa. Lo importante es hacer que madure completamente. Apenas lleva tiempo, esfuerzo o dinero. Uno ha de saber cómo hacerlo.

Pregunta: ¿Por qué las distintas iglesias no nos han hablado de esto?

SM: Porque no era el momento, señor. Imagínese: Cristo habló solo durante tres años y medio, en lo que se refiere a sus enseñanzas espirituales. Solo se le permitió vivir así tres años y medio. Las iglesias no lo saben, pero incluso Cristo... Imaginad: Durante cuatro años estuve peleando con siete chicos y chicas ingleses para darles la Realización. Cristo hizo muy buen trabajo, debo admitirlo, pero aquel no fue el momento. En realidad, Él vino a este chacka que es el Agnya. Ese fue su trabajo: Mostrar el camino de la Resurrección. Esa fue su vida y eso es lo que hizo, pero las iglesias no lo han entendido y seguirán sin entenderlo. Su principal interés consiste en cómo hacer dinero; eso no es bueno. O en cómo convertir a la gente y eso tampoco es bueno.

Pregunta: ¿Hay mucha gente santa en la iglesia?

SM: Puede que haya muchas personas que son muy sencillas, que creen en Cristo, que van a la iglesia porque creen que serán salvadas. Todos esos serán salvados, sin duda. Son gente muy simple. Dan mucho dinero a la iglesia y tienen mucha dedicación, aunque están en el lugar equivocado. Pero se salvarán, no hay duda sobre ello. Todos ellos han de ser salvados. Sin embargo, hay gente que solo se dedica a ganar dinero a costa de las iglesias intentando convertirlas en una organización. Tratan de convertir a la gente para sacar un provecho político de ello. Eso es lo que no funcionaráporque no es lo correcto. Las iglesias solo deberían cumplir la promesa de dar la Realización a la gente. Esa es la misión de la iglesia. Aprenderán, estoy segura de ello; tendrán que convertirse. Alguna de ellas deberáhacerlo, pero si están orientadas al dinero, no sé lo que pasará. Estas están más interesadas en los reyes y los primeros ministros, en las princesas y en todo eso. No lo entiendo. No tienen nada que ver con Dios.

Pregunta: ¿Por qué hace falta el juicio? Algunas personas progresan y otras no. ¿Y por qué otros les juzgan? ¿Por qué ha de llegar el momento del juicio?

SM: Ha de haber un momento para el juicio, hijo mío, y este es un tiempo muy particular porque lo consideramos el peor momento, ya que el hombre estáen una gran confusión. La época más difícil en la que pueden vivir los seres humanos es este momento actual, al que nosotros llamamos "Kali Yuga". Ahora tenía que ocurrir, de lo contrario el hombre no se habría acercado a Dios seriamente. Quizánuestros antepasados no vivieron este estrés ni esta tensión y por tanto no quisieron relajarse o pensar en Dios. Fueron bastante felices haciendo sus tareas en el campo, pero ahora realmente hemos llegado a un extremo. Todo ha de llegar a su punto de ebullición, y este es el momento de que el mundo obtenga sus resultados, sean buenos o malos.

Pregunta: ¿Por qué es ahora el momento del juicio final? Porque si existe la reencarnación, la gente iráyendo y viniendo hasta que se produzca un cambio.

SM: Ya os he dicho que este es el momento en el que la gente estámás confundida y tienen que tomar una decisión. Por eso este es el tiempo del juicio final. O bien irán al infierno o al cielo. ¿Te deja eso satisfecho? Bien. El cielo estáen nuestro interior.

¿Qué tal si tenemos nuestra Realización? Algo muy simple que tenéis que hacer. Como dije, tenéis que colaborar un poco conmigo. Si sois inflexibles o cínicos respecto a esto, resultarádifícil. Así que, si queréis recibir vuestra Realización, tenéis que cooperar un poco conmigo; eso es todo. Bien, para ello tenéis que quitaros los zapatos, para así tocar la Madre Tierra, eso es todo: estar en contacto con la Madre Tierra. ¡Quitáoslos! Es algo que ya tenéis y simplemente ha de salir, así de sencillo. Ahora poned los pies sobre el suelo, en paralelo y sentaos cómodamente en una postura recta.