Charla a yoguis, India Tour. Ganapatipule (India), 3 Enero 1988.

Espero que estéis muy cómodos y que estéis disfrutando también de la comida. Además estamos llegando al final de nuestro tour. Este tour se ha organizado, como sabéis, como un viaje a través de vuestro Shushumna Nadi. En distintos puntos, tenemos distintos chakras, de igual manera hemos pasado a través de varios lugares y ahora hemos llegado a Ganapatipule, donde tenemos que conseguir que nuestro Sahasrara se empape completamente de las bendiciones de Shri Ganesha.

Como sabéis, Sahaja Yoga es un suceso muy sutil en nuestro interior. Es un suceso muy sutil y este suceso os da sensibilidad al gozo Divino. Cuando empezáis a sentir el gozo Divino no os importan las comodidades, no os importan los tipos de placeres mundanos que os dan cosas. Para vosotros se vuelve lo más importante y lo único.

Aparte de eso, empezáis a ver la verdad tal como es. Cuando digo que empezáis a ver la verdad, muchos pueden malinterpretar estas palabras. He visto que muchos dicen que pueden decidir cosas con las vibraciones y que han decidido ciertas cosas basándose en las vibraciones. Pero cometen errores. Eso significa que no han crecido a ese estado en el que pueden decidir con vibraciones. Así que nadie debería decidir arbitrariamente, sino que debe consultar al colectivo, especialmente vuestros líderes deben averiguar si las decisiones que han tomado, todo lo que han pensado, está bien o no. Uno puede cometer muchos errores si empezáis a comportaros arbitrariamente.

La mayor ley de Sahaja Yoga es que es un suceso colectivo. Ahora como habéis visto aquí, hay gente de fuera, de Delhi, de Calcuta, de Bombay, de los pueblos, de varios sitios. La idea de que todos vengáis aquí, es crear el entendimiento del colectivo. Al volveros más y más colectivos, no molestáis a otros, no les creáis problemas, sino que dais gozo. No os importa ir y venir, la comida y todo, simplemente no os comportáis como gente mundana normal, sino que sois muy pacientes, se llama Saburi. Tenéis paciencia.

Esta paciencia es lo que da más gozo. La paciencia os da el mayor gozo. Cuando sois pacientes, desarrolláis todas vuestras cualidades. Creo que con paciencia es como mejor florecéis. Pero paciencia no es sólo ser paciente, ser paciente. Es también un tipo de estado interior que tiene esta paciencia, Saburi. Sólo observad y ved vosotros mismos. Dondequiera que estéis, ahí estáis. Algunas personas están preocupados porque deben coger el autobús. Algunos están preocupados por volver a casa. Algunos por tener su comida a tiempo. De acuerdo con ellos, esto es disciplina. Pero no lo es. Es condicionamiento. ¿Cuál es la disciplina en Sahaja Yoga? Es la paciencia, con la que observáis todo y sois pacientes. Si estáis en el autobús, estáis ahí. Si estáis en la carretera, estáis ahí. Si estáis caminando, estáis ahí.

Por el contrario, es buena idea caminar. Me gustaría pero no puedo, porque en cuanto empiezo a caminar todos vienen a Mis pies. Nadie Me dará tiempo libre. Así que estoy encarcelada dentro de casa, en la habitación todo el día porque no puedo salir, en cuanto salgo veo que hay mucha gente esperando fuera. Pero ese no es vuestro caso. Vosotros sois libres. No estáis atados como Yo. Así que es bueno caminar un poco por la tarde, es una buena idea, muy buena idea. Podéis caminar sin prisa, así haréis la digestión de la comida. La comida es bastante pesada a veces. Os hace sentir mejor. Sólo sabed que estáis caminando y eso es todo. Sentir que tengo que caminar, tengo que ir allí, en cuanto empezáis a pensar os agotáis ahí sentados, incluso si no habéis caminado. Así que es importante que esa paciencia sea la disciplina de nuestra vida.

¿Cuánta paciencia tenemos para todo, para cualquier cosa? Ahora como podéis ver, tengo que sentarme aquí, no podéis empezar hasta que no venga, tengo que estar sentada hasta que terminéis. Vosotros sois todos libres de levantaros, pasear, ir a donde os apetezca, no como Yo. ¿Y cómo hago todo esto? Es con Mi paciencia. Pero la paciencia es Mi cualidad. Es Mi naturaleza, de la que más disfruto. Si estoy aquí sentada y no hay nadie, lo estoy disfrutando. Si Me pierdo en algún lugar, lo disfruto. Si Me pierdo lo disfruto porque estoy ahí para disfrutar de Mi misma.

Así que creo que debemos practicar ahora que ha salido la Luna, tenemos hermosas noches con luz de la Luna, intentad caminar, especialmente la gente de Delhi deberían caminar. Ellos no caminan. En Delhi está bien, porque no podéis pasear, hay peligro y todo eso, pero aquí es mejor. Mejor caminad. Vuestra salud mejorará. Sahaja Yoga mejorará. La Kundalini mejorará. Os sentiréis mucho mejor.

Esto es lo bueno de este remoto lugar, que nadie os ve. No le molestáis a nadie. Podéis vivir como queráis, pasear como queráis. No molestáis a nadie. No hay necesidad de hacer una competición o correr, sino que es buena idea caminar sin prisas. No lo digo para ahorrar dinero en autobuses, sino para haceros sentir más saludables, sólo estando sentados aquí todo el día os sentis raros, sentados aquí, sentados allí, yendo en taxi, en autobús, en coches, no movéis las piernas. Además no hacéis ejercicio en Sahaja Yoga. Caminar es el mejor ejercicio para todos los sahaja yoguis, como os he dicho. Por eso es importante que todos intentéis caminar un poco, si es posible. Por supuesto hay mujeres que tienen niños, está bien, mujeres mayores, hombres mayores, pero incluso para ellos es buena idea caminar la mitad del camino y después podéis ir en autobuses. Intentad algo así durante estos tres, cuatro días. Os sentiréis mucho mejor. Os prometo que os sentiréis mucho mejor cuando caminéis.

Y otra cosa que debemos aprender, aparte de Saburi, de la paciencia, es empaparse en nuestro interior de dulzura. Si sois dulces, os llenáis de buen humor, no herís a los demás, tampoco sois heridos, veis todo muy hermoso y agradable, Esa es la cualidad de Shri Krishna, Madhurya. Todo puede hacerse con dulzura. Es muy importante. Ahora algunos podrían decir: "Madre, a veces tienes que enfadarte y todo eso". Para vosotros no hay necesidad. Yo puedo hacer ese trabajo sucio. Vosotros no tenéis que hacerlo. Vosotros no tenéis que enfadaros con nadie. Sólo mostrad vuestra paciencia, vuestro amor, vuestra amabilidad, vuestra dulzura. Así es como la personalidad de Sahaja Yoga, que es algo colectivo, ha de ser construida por personas que tengan paciencia, que sean dulces exteriormente, e interiormente.

Y lo tercero es ser genuino. Si no somos genuinos no podemos entrar en nuestro interior porque nuestro ser interior sabe lo que somos. Si hay hipocresía, si sólo queremos presumir, o si hay alguna clase de reserva dentro de nosotros, no podemos profundizar en nuestro interior. Además la gente que entra en contacto con esas personas tampoco pueden progresar. Así que tenemos que ser muy genuinos en eso y esto es una cualidad individual, no es una cualidad Samuhik [colectiva]. No es una cualidad colectiva. Todos nosotros tenemos que ser genuinos en nuestro interior, porque es para nuestra mejora, para nuestra Hitha.

Así que tenemos que ser colectivos porque es bueno para nosotros, tenemos que ser pacientes porque es bueno para nosotros, y tenemos que ser genuinos porque es bueno para nosotros. Esto es Swartha. El significado de Swa, Swartha. Swa significa nosotros mismos, Artha significa el significado. Swartha significa nosotros mismos, pero el ser, el ser y el ser.

Ahora sois personas que habéis cambiado, vuestra personalidad es diferente, brilla a través de nuestro Espíritu. En ese Espíritu tenéis que ver todo. Todos vuestros condicionamientos se irán en cuanto empecéis a identificaros completamente con el Espíritu. De nuevo digo completamente, porque no lo somos, todavía somos cristianos, hindúes, musulmanes. Todavía somos indios, ingleses, todo eso. Todavía somos pequeños charcos de mente estrecha. Tenemos que ser el océano. Una vez os identificáis con el océano tenemos que deshacernos de todo, y volvernos absolutamente limpios y desapegados, Nisanga. Así que cuando estamos cantando todas estas canciones estamos diciendo eso. No debería ser palabrería. Debería haber un flujo en nuestro corazón. Deberíamos sentirlo.

Pero estoy contenta de que vuestros Espíritus están brillando y el Espíritu está disfrutando de que estéis ascendiendo suavemente. Un pequeño empuje os ayudará más, y también entendiendo todo esto. Esta vez he visto que ha sido un seminario mucho mejor. Debemos tener un seminario adecuado, quizá mañana por la mañana podríamos intentar tener un seminario apropiado o algo pero la mayoría de la gente que va a venir, lo harán realmente mañana, así que no sé, quizá mañana por la tarde. Vendrán mañana en algún momento. Apenas tenemos tiempo para un seminario como Me gustaría, que nos sentáramos y tuvieramos algo apropiado. O podéis tenerlo mañana por la mañana o también pasado mañana en algún momento. Así que algo puede ser organizado por los líderes, todos los líderes del mundo deberían reunirse y hacerlo.

Tal como sale el programa, así es, porque en Sahaja Yoga los programas nunca son iguales. El cambio es una señal de la vida. Como os he dicho, una pequeña raíz tiene una pequeña célula al final que tiene mucha discriminación y cambia su curso según el camino, para penetrar en la Madre Tierra. Si hay una gran roca la rodea y rodea para crear un lazo sobre el que después el árbol se puede apoyar. Después va a todas las partes de una forma correcta, que sea la mejor y Sahaj. De la misma manera es un proceso viviente y todo lo que funcione ha de ser trabajado de esa manera. A veces podéis ir a dormir a las diez, a veces a la una. A veces podéis dormiros en cualquier momento. Depende cómo se mueven las cosas.

Tenemos que estar preparados para todo de una manera muy dulce, muy agradable. Así que de una vez, decidamos que vamos a ser grandes sahaja yoguis, que estamos aquí para ser Nirmalitas, para luchar contra todo lo que está equivocado, para defender lo correcto y emancipar a toda la humanidad. Si entendéis este tremendo trabajo que tenemos que hacer, entonces crearéis vuestras propias personalidades de tal manera que seréis capaces de llevar esta gran responsabilidad.

Así que vamos a ver, hoy es el comienzo de este entendimiento entre nosotros, de que no vamos a crecer exigiendo, pidiendo, preocupándonos por nosotros mismos, sino que vamos a disfrutar, simplemente disfrutar, y esto es lo que falta en algunas personas y por eso no pueden disfrutar. Se preocupan todo el tiempo de cómo llegarán allí, cómo vendrán aquí, cómo está organizado, qué es esto, qué es aquello. Relajáos y las cosas funcionarán para vosotros. Así es como vais a disfrutar de la vida.

¡Que Dios os bendiga!

H.H. Shri Mataji Nirmala Devi