16 lipca 2001
Program Publiczny
Holland Park School, Londyn (Anglia)
Program Publiczny, Londyn, Anglia, 16 lipca 2001.

Bardzo się cieszę, że mogę was tu wszystkich widzieć.

Jeszcze nie mogę powiedzieć, że jesteście poszukiwaczami, ale jesteście tymi, którzy to znaleźli. To jest coś tak satysfakcjonującego. Wyobraźcie sobie, że w dawnych czasach był taki zwyczaj, zgodnie z którym jeden guru mógł dać realizację jednej osobie, z wielką niechęcią! Najpierw musieli oni przejść przez różnego rodzaju testy, wszelkiego rodzaju tapasya, jak to nazywają, bardzo, bardzo surową pokutę. I spośród nich wybierali jedną osobę, która mogła otrzymać Samorealizację. Wyobraźcie sobie, co uzyskaliście w tak krótkim czasie! Ale po tym długim okresie męk rozwinęli wielkie poczucie szacunku dla swojej Samorealizacji, rozumienia, co to jest. Chodzi o zrozumienie własnych mocy, zrozumienie własnych obowiązków. A nie było ich tak wielu. Jedna osoba walcząca z całym społeczeństwem swoimi wzniosłymi ideami.

Chociaż dzisiaj jest was tak wielu, wszystkich was łączy braterstwo, wzajemna miłość. Nikt nie będzie was torturował, nikt nie będzie was ścigał, ale wy sami będziecie chcieli propagować Sahaja Yogę, dawać ludziom miłość i życie. To przyjdzie spontanicznie do was. Podobnie jak kwiat, rozprzestrzeniający zapach, będziecie mieć zapach duchowości i ludzie nagle was rozpoznają, ponieważ tak bardzo różnicie się od innych. Wasz temperament jest tak inny, jesteście tak zrównoważeni, jesteście tacy słodcy, a oni przyjdą, pójdą za wami. W niektórych krajach stało się to bardzo szybko. Na przykład w Indiach, oni to wiedzą, wiedzą czym jest Samorealizacja i wiedzą, że to jest cel życia, więc było dużo łatwiej, jest tam tak wielu Sahaja yoginów. Jednak teraz mamy sahaja yoginów na całym świecie, nawet na Grenlandii, możecie sobie wyobrazić, w Finlandii, Szwecji, Norwegii. Mamy Izraelczyków, a także Palestyńczyków. Oni są w Sahaja Yodze.

Powinni walczyć ze sobą, a oboje są w Sahaja Yodze. Pewien Izraelczyk zadzwonił do mnie i powiedział: "Matko, w wiosce jest kilku palestyńskich sahaja yoginów i dowiedzieliśmy się, że zostanie zbombardowana. Czy możesz zwrócić na to uwagę? Byłam tak wzruszona. Zauważcie, ile troski i miłości okazują tak zwanym wrogom! Jeśli pewnego dnia taka miłość umocni się, wszystkie te wojny i starcia skończą się, nie będzie żadnych walk, jeśli zrozumiecie, że wszyscy jesteśmy częścią całości, po prostu wszyscy, absolutnie, częścią jednej Boskości, częścią jednej Boskiej Mocy. Jeśli to zostanie wbudowane w nas, wszystkie te problemy, o których mówiłam w moim wykładzie, zostaną rozwiązane. (Spotkanie w Royal Albert Hall kilka dni wcześniej). Właściwie Kundalini uniosła się w wielu z was, w większości z was. Bez wątpienia przebiła również okolicę ciemiączka, ale wciąż czasami schodzi, schodzi, by was wyleczyć.

Przypuśćmy, że jesteś pacjentem z chorą wątrobą, wtedy Kundalini zstąpi i skupi pełną uwagę na twoją wątrobę i spróbuje poprawić stan twojej wątroby. Ona się wami opiekuje. Ona jest waszą indywidualną Matką. Każdy ma w sobie tę Matkę. I ta Matka jest tą, która was prowadzi, opiekuje się wami i prowadzi na właściwą drogę. I tak zaczniecie swój nowy wzrost w Sahaja Yodze. Stajesz się wtedy inną osobowością. Wtedy twoja uwaga zaczyna przenosić się z ciebie na innych. To znak, że jesteś w pełni dorosły. Jeśli tak się stanie, że twoja uwaga nie jest skupiona na sobie, kieruje się ku innym i martwisz się o innych.

To bardzo zdumiewające, jak ta Boska miłość tworzy cuda. Gdy po raz pojechałam do Rosji byłam zaskoczona, dwadzieścia pięć osób z Niemiec i Austrii przyjechało tam na własną rękę, nigdy do nich nie dzwoniłam, nie organizowałam ich pobytu itp. I powiedziałam im: "Dlaczego tu jesteście? Jak się czujecie? Jak przyjechaliście? Co jest takiego szczególnego w Rosji? A oni na to: "Matko, nasi przodkowie wyrządzili im tyle krzywd, że nie mogliśmy nic na to poradzić". To rodzaj ogromnej miłości i zrozumienia problemów Rosjan które odczuli podczas wojny. I opowiadali mi, co się stało z Rosjanami. Byłam zaskoczona.

Zapytałam ich: "Kto wam o tym powiedział?". "Nasz ojciec, nasz dziadek, którzy żałowali tego, co zrobili. Ale już ich nie ma, więc pomyśleliśmy, że lepiej będzie, jeśli przyjedziemy i trochę pomożemy". Bardzo mnie to wzrusza. Widziałam tak piękną stronę istot ludzkich po otrzymaniu przez nich realizacji. Żadnego okrucieństwa , żadnej nieuprzejmości, zawsze przebaczenie, tak wielu ludzi stało się teraz takimi słodkimi. W Rosji mamy, jak wiecie, maksymalną liczbę sahaja yoginów, nie więcej niż w Indiach, ale tak jest. Tak wielu z nich jest w Rosji i są tak głębocy, tak bardzo rozumieją. Nigdy nie narzekają na problemy z pieniędzmi, nic podobnego. Powiedzieli: "Matko, mamy tylko jeden problem".

Zapytałam:"Jaki macie problem?" "Przywództwa. Daj nam dobrego przywódcę. A teraz powiedzieli — mamy fajnego przywódcę. Przyjął Sahaja Yogę, jest ona religią w Rosji. Oczywiście jest ona również religią w Indiach. Ale w rzeczywistości jest akceptowana jako oficjalna religia w Ameryce. Wyobraźcie sobie! Myślimy, że Amerykanie są tacy materialistyczni itd. Oni są dopiero 200- letnim narodem, a tak głęboko dojrzeli do duchowości, jak oni zdali sobie sprawę z tego, że duchowość jest sednem życia.

Teraz jestem z wami, ludźmi, którzy rzekomo pochodzą z Anglii, a Anglicy mieli tych wielkich ludzi takich jak Szekspir, William Blake, wszyscy oni byli zrealizowanymi duszami. Ale to, co widzę w ich wysiłkach, to to, że próbują pokazać wam tak wiele rzeczy, abyście zrozumieli Sahaja Yogę. Ale co mogli oni zrobić, jeśli nie wiedzieli, jak podnieść Kundalini prawdopodobnie ludzie byli całkowicie głuchoniemi, gdyż nie rozumieli, co ci ludzie próbowali przekazać. Większość poetów była duszami zrealizowanymi. Większość pisarzy była duszami zrealizowanymi. Jak to możliwe, że tak wspaniali ludzie tak po prostu giną? Ale teraz, kiedy was tu wszystkich widzę, myślę o nich. Muszą być bardzo szczęśliwi widząc was wszystkich cieszących się błogością, błogością Boskości. Opisom tych rzeczy nie ma końca. Nie da się tego w pełni opisać.

Należy się z tego cieszyć. Tylko wszystko polega na tym, że pierwszym etapem jest świadomość bez myśli, którą musicie osiągnąć. Jeśli osiągnęliście świadomość bez myśli, to wykonaliście jeden krok. To jest najważniejsze. Musicie stać się świadomymi bez myśli. To nie jest trudne. Jest takie powiedzenie w Sanskrycie, że zaczynacie mówić “nie" każdej myśli. Jakakolwiek myśl przychodzi – "Ya neti neti wachane nigamor awachus". Po prostu mówcie dalej: "Nie. Nie ta myśl.

Nie ta myśl. Nie ta myśl. I możecie to osiągnąć. Również podnosząc Kundalini, wybaczając ludziom, możecie to osiągnąć. Również jeśli jesteście w stanie dowiedzieć się, dlaczego te myśli przychodzą do ciebie, jakie jest źródło tej myśli. Gdybyście tylko mogli zobaczyć, co jest źródłem, moglibyście to zrobić. Nagle zauważycie, że jesteście w ciszy, nie myślicie, ale jesteś świadomi, w pełni świadomi tak wielu rzeczy, których nigdy nie byliście świadomi. Jest to coś, co musicie praktykować, to stawanie się świadomym bez myśli. Ta świadomość nadaje nowy wymiar waszej uwadze. Rozwijacie uwagę, która działa, która działa.

Siedząc tutaj, jeśli chcecie o czymś pomyśleć, ta uwaga dotrze tam i rozwiąże problem. To działa. wy też możecie to zrobić. Ale jeśli wasza uwaga skupiona jest na małych, małych rzeczach, takich jak "Mój ojciec jest taki... moja szwagierka jest taka", itp., to zapominasz o tym. I nie osądzajcie siebie. Jeśli potępiacie siebie samego, to na nic się to zda, ponieważ teraz jesteście Duszą Zrealizowaną. Nie ma potrzeby osądzania, wystarczy obserwować bez myślenia. To właśnie nazywa się sakshi, stan świadka. Ten stan świadka musicie osiągnąć, a kiedy go osiągniecie, zaczniecie cieszyć się wszystkim. Przypuśćmy, że ktoś jest niemiły, ale wy możecie zobaczyć humor, który się za tym kryje.

Przypuśćmy, że ktoś jest agresywny, lecz wy możecie po prostu się z tego śmiać. Możecie spojrzeć na to biedactwo, jak on robi coś złego, bo nie może nic na to poradzić, albo jest złośliwy, nieważne, wszystko będzie w porządku. To jest zachowanie niewinnej osoby. Jesteście niewinni, nie widzicie w nikim nic złego. Jeśli jesteście przebiegli, widzicie wszystkich jako przebiegłych. Jednak niewinność jest tysiąc razy błogosławiona przez Boga. Bóg błogosławi niewinność. Teraz możesz powiedzieć: "Jak to jest, Matko, że ginie tak wielu ludzi, którzy byli niewinni? Jak to się stało? W porządku, oni nie byli duszami zrealizowanymi, a niektórzy z nich, np.

Chrystus, przeszli przez mękę. To ma znaczenie. Jego ukrzyżowanie ma bardzo duże znaczenie. Dla nas jest to bardzo pomocne, ponieważ On sam się ukrzyżował. Teraz możemy przejść przez czakrę Agnya. Każdy z nich ma duże znaczenie, oni wszyscy pomogli tak bardzo w budowaniu waszej Kundalini, pomagając wam i pracując nad tym. Wszystkie ich tak zwane męki i ofiary dały tak wiele, co zrozumiecie będąc w stanie świadka. To wszystko jest jak w ogrodzie, wszyscy muszą pracować, ogrodnik musi pracować, potem wrzuca się ziarno i musi pracować Matka Ziemia, i woda musi pracować, a potem ma miejsce kiełkowanie. Wciąż to wymaga czasu, a następnie podczas kwitnienia, wszystkie kwiaty są tam, ale za tymi kwiatami jest tak wielki wysiłek ludzi. W ten sam sposób wszyscy ci ludzie, którzy włożyli swój trud, są w nas i pomogą nam.

Z Sahaja Yogą, po otrzymaniu realizacji, jeśli nie rozprzestrzeniacie Sahaja Yogi, to nie oddajecie sprawiedliwości Sahaja Yodze. Nic na to nie poradzicie, to jest coś takiego, po prostu na odwrót, podobnie do człowieka samolubnego. Samolub nigdy nie będzie chciał się dzielić, natomiast zrealizowana dusza chciałaby dzielić się wszystkim z innymi i cieszyć się, cieszyć się dzieleniem. Pojawia się tak wielu pięknych ludzi. Stają się oni tak piękni i mili, tak zrelaksowani, tak zrównoważeni, że jesteście zdumieni, zaskoczeni samym sobą pytając "Miałem w sobie cały ten skarb? Całe to piękno we mnie, co bardzo mi się podoba." Cieszycie się sobą, cieszycie się innymi, cieszycie się każdą cząstką tego. Więc błogosławię was wszystkich z głębi serca. Tak wielu z was osiągnęło Realizację. Jak już wam powiedziałam, musimy zmienić przeznaczenie istot ludzkich.

Nie przybyliśmy tutaj, aby niszczyć, ale przybyliśmy tutaj, aby rozwijać się, a przeznaczenie musi zostać zmienione i to jest to, co musimy wykonać. Niech Bóg Was błogosławi. Derek Lee: "Shri Mataji, jest tu jedna lub dwie nowe osoby" Shri Mataji: "Więc czego oni chcą?" (śmiech) Derek Lee: "Nie wiem, czy chcesz Matko odpowiadać na pytania, czy prosić ich, aby poczuli..." Shri Mataji: (śmiech) "W porządku! Derek stara się zaopiekować wami wszystkimi i mówi, że jest tu wielu nowych ludzi, którzy chcieliby zadać ci pytania. (śmiech) Tak oto, czasami jestem zaskoczona, gdyż stajecie się kimś na podobieństwo przestępcy, który wymusza przyznać się do czegoś. Na przykład wczoraj pytali mnie: "Czy jesteś boginią?" Powiedziałam: "Bapare, co mam powiedzieć?" Powiedziałam: "Chcecie, żebym się do czegoś przyznała?" I wtedy oni zamilkli.

Więc teraz jakie są pytania. Pytania powinny być związane z waszym rozwojem, a nie bezsensownymi rzeczami, po co marnować energię? To nie jest partia polityczna ani nic z tych rzeczy, to coś duchowego. Więc jeśli chcecie zapytać, poproście o swój duchowy rozwój". Hinduska zadaje pytanie w języku hindi Derek Lee: "Mówi, że pochodzi z Ameryki i nie może spać, bo wszystko kręci jej się w głowie, więc nie może spać" (hindi) Shri Mataji: "Znam około siedmiu języków, ale próbuję nauczyć się włoskiego, który jest dla mnie bardzo trudny". Poszukiwacz: "Buonasera, pranaam" Shri Mataji: "Tyle wiem!" Poszukiwacz: "Czy powiedziałbyś, że Sahaja Yoga zawiera i obejmuje inne religie, czy też jest odrębną religią?" Shri Mataji: "Ona zawiera. Oczywiście zawiera wszystkie religie, całą esencję wszystkich religii. Religia jest ponownie, krok po kroku, ostrzeżeniem dla istot ludzkich.

Jak możecie ją wykluczyć? ​​Chodzi tutaj o esencję, esencję religii, a nie wszystkie bzdury, które ludzie utworzyli". Poszukiwacz: "Z głębi serca chciałbym Ci podziękować nie tylko za to, co zrobiłaś dla mnie, ale za to, co zrobiłaś dla tysięcy ludzi na całym świecie". (brawa) Shri Mataji: "Mam nadzieję, że mówi w imieniu was wszystkich? (więcej braw) To daje tyle radości. Taka dająca radość odpowiedź. Mam na myśli to, że to jest jak fale, które dotykają brzegu, następnie zaczyna się kolejna seria fal. I to nie ma końca, to jest takie piękne. Dziękuję, bardzo dziękuję. Macie jeszcze jakieś pytania?

Poszukiwacz: "Czy istnieje dobry lub zły sposób medytacji?" Shri Mataji: "Nie rozumiem, nie ma złej drogi. To znaczy, z całym szacunkiem, jeśli praktykujecie jakąś medytację, to doskonale, lecz przede wszystkim wasze serce i wasz umysł muszą mieć szacunek. W każdym razie, kiedy medytujecie, powinniście to robić z miłością, to wszystko. Miłość wszystko oczyści. To znaczy, jeśli staniecie na głowie i będziecie medytować, to jest w porządku, lecz nie ma takiej potrzeby! (śmiech) Po prostu usiądźcie i medytujcie. Co to jest?" Poszukiwacz: "Co Pani sądzi o podnoszeniu Kundalini metodą Sahaja Maithuna?" Shri Mataji: "Jeśli chcesz, możesz spróbować.

Ale to niebezpieczne" Poszukiwacz: "Czy my po prostu odgrywamy jakieś role w imię wyższej istoty?" Derek Lee: "On zastanawia się, dlaczego mamy wolną wolę" Shri Mataji: "Widzicie, duchowo ludzie nie są bardzo dojrzali i kiedy już osiągną Realizację, nie rozumieją jej wartości, gdyż jest to takie proste i łatwe. Ale ci, którzy są dojrzali, ci, którzy są prawdziwymi poszukiwaczami, traktują to bardzo poważnie. To nie jest kwestia wolnej woli, to zależy od waszego wzrostu, waszej dojrzałości. To zależy od tego. Niektórzy są naprawdę świetnymi poszukiwaczami, niektórzy dobrze się starają, a niektórzy robią to tylko ze względu na jakąś modę. Poszukiwanie Prawdy powinno wypływać z waszego serca. To bardzo ważne. Ci, którzy chcą unikać Prawdy, oczywiście nie są dobrzy, a ci, którzy również są bez przekonania, wymagają czasu, lecz stopniowo, wraz z doświadczeniem, wskakują w to". Ten sam poszukiwacz: "Shri Mataji z pewnością ci, którzy są mniej rozwinięci i mniej otwarci, są najbardziej w potrzebie, z pewnością powinno im to przychodzić łatwiej?"

Shri Mataji: "Tak jest. Wszystkim wam jest łatwiej. Mam na myśli sposób, w jaki osiągnęliście Realizację, nikt nie mógł w to uwierzyć. Na początku też nie mogłam uwierzyć, że to działa tak szybko. Ale to działa. Można powiedzieć, że niektóre kwiaty kwitną szybciej niż inne. Nie przejmuję się tym, ponieważ jeśli mają najmniejsze pragnienie bycia Duchem, to stają się Nim. Również Boskość pragnie wam dać." (brawa) Poszukiwacz : "Powiedziała Pani o medytowaniu z miłością, ale ja po prostu próbowałem myśleć o tym, czym jest miłość, ponieważ tak naprawdę nie rozumiem miłości" Shri Mataji: "ah! (śmiech) To znaczy, miłość jest cechą ludzką.

Co tu jest do zrozumienia? Ludzie kochają nawet psy i zwierzęta. Masz psa? (śmiech) Miłość oznacza bez złośliwości, bez jakiejkolwiek złości, to jest to czego się pragnie. To tak abstrakcyjna rzecz, że nie da się tego wyrazić słowami, lecz to uczucie jest w was, a kiedy medytujecie z miłością, oznacza to, że, przypuśćmy, że jesteście bardzo źli i sfrustrowani i wtedy przystępujecie do medytacji i zaczynacie mówić: "Matko, zrób to! Zabij go! Zrób tamto!' To tak nie działa. Jednak bycie w miłości oznacza właściwie brak myśli. Miłość to nie myśl, to po prostu uczucie, uczucie emancypacji.

Po prostu uczucie" Poszukiwacz: "Jak opisałaby Pani korzyści płynące z medytacji Sahaja Yogi w porównaniu z innymi rodzajami medytacji?" Shri Mataji: "Pierwszą i najważniejszą rzeczą jest to, że musicie czuć wibracje na swoich dłoniach. Chłodne wibracje, które są Boską Miłością Wszech-przenikającej Mocy. Powinniście poczuć, jak to wychodzi z obszaru kości ciemiączka. W przypadku jakiejkolwiek innej medytacji tak się nie dzieje, a to nie jest właściwe. Jest to minimum tego, co powinno się wydarzyć, abyście poczuli swoje wibracje, jak chłodny powiew na dłoni i wychodzący poza obszar kości ciemiączka. To minimum na początek. Bez medytacji to się dzieje. Proszę tego Pana w oknie." Poszukiwacz: "Co miłość ma wspólnego z religią?"

Shri Mataji: "Istotą religii jest miłość. Istotą. Co on mówi? Nie słyszysz mnie?" Poszukiwacz: "Ludzie zaangażowani w religię często się boją" Shri Mataji: "Tak jest, zgadzam się, ponieważ oni nie są religijni." Poszukiwacz: "Miłość nie potrzebuje religii" Shri Mataji: " Oczywiście, że tak. Oczywiście. Nie potrzebuje żadnej nazwy. Miłość jest miłością. Jednak jest w nas wrodzona religia.

Religia wrodzona jest oświeceniem Ducha. To jest wrodzone. Możecie to nazwać religią, możecie to nazwać boską miłością, możecie nazwać to jakkolwiek, ale w nas jest to źródło, które tworzy nową osobowość przesiąkniętą miłością i które możemy nazwać wewnętrzną religią." Poszukiwacz:"Czy Samorealizacja jest tym samym co oświecenie?" Shri Mataji:"Oczywiście. Istnieje wiele określeń." Poszukiwacz: "Czy Sahaja Yoga jest jedyną drogą do Samorealizacji?" Shri Mataji: "Powinnam powiedzieć, że tak. Nie zauważyłam żadnej innej" Poszukiwacz: "Dlaczego trzeba podnosić Kundalini, aby medytować lub osiągnąć oświecenie?" Shri Mataji: "Już tak to jest utworzone.

Dlaczego podłączacie ten (mikrofon) do sieci? W ten sam sposób macie być połączeni. Aby połączyć się z Wszech-przenikającą Mocą, wasza Kundalini musi zostać podniesiona. Wszystko jasne?" Poszukiwacz: "Jak Duch Święty przenika to wszystko?" Shri Mataji: "To jedynie Duch Święty robi wszystko! Gdy przyjdziecie do Sahaja Yogi i wejdziecie w nią głęboko, będziecie o tym wiedzieć. To wszystko jest dziełem Ducha Świętego. Nie wiem, dlaczego nazywają to duchem! (śmiech)" Poszukiwacz: "Czy otwieranie siedmiu poziomów świadomości bez odpowiedniego przewodnictwa jest niebezpieczne?"

Shri Mataji: "Widzicie, to może robić tylko ten, kto jest w stanie to zrobić i nie sądzę, aby ktokolwiek wiedział, jak to wykonać, więc należy to powinno być zrobione w odpowiedni sposób. Ale Kundalini wie, wie o was wszystko i zna wasze problemy, a gdy się unosi, robi to tak słodko, nie wyrządzając wam krzywdy, nie niepokojąc was, więc najlepszą rzeczą jest umocnienie waszej Samorealizacji." Poszukiwacz: “Jak Pani podnosi Kundalini?" Shri Mataji: " Jeżeli chodzi o Mnie, to, wiedzcie, że nie ma sensu wam mówić, co mogę zrobić, gdyż wy nie możecie tego zrobić, prawda? Możecie podnieść Kundalini, gdy już jesteście Duszą Zrealizowaną, możecie też podnosić, ale może nie tak jak Ja. Gdy osiągniecie Mój poziom, będziecie tak robić! (brawa i śmiech)" Poszukiwacz:"Czy może Pani nam opowiedzieć o swoim wczesnym życiu, kiedy po raz pierwszy uświadomiła Pani sobie znaczenie Samorealizacji" Shri Mataji:"Widzicie, myślę, że jest o tym książka. W porządku? Lepiej to przeczytajcie." Poszukiwacz:"Czy może mi Pani powiedzieć, w jaki sposób stymulujemy wzrost Kundalini, medytując w domu?"

Shri Mataji:"Myślę, że oni wiedzą, że jest zdjęcie, którego używają na początku i które pomaga. Musicie jednak przyjść do ośrodków, gdzie dokładnie powiedzą wam, co należy zrobić. Trzeba poświęcić trochę czasu, żeby to zrozumieć. Wszyscy musicie przychodzić do centrum, ilu z was przychodzi do centrum, podnieście rękę. Widzicie, nawet nie ma 10%. Proszę opuścić dłonie. Dlatego ważne jest, abyście uczęszczali do centrum, opanowali to, stali się pełnowartościowymi powinnam powiedzieć - sahaja yoginami, i dawali realizację innym, to jest wasz obowiązek, musicie to robić. W przeciwnym razie jest tak, jak powiedział Chrystus, że niektóre ziarna padły na skałę, inne na bagnisty teren, a jeszcze inne na urodzajną ziemię. Jeśli jesteś osobą o urodzajnym temperamencie to się uda. W porządku?"

Poszukiwacz: "Czy samorealizacja następuje wtedy, gdy zdajemy sobie sprawę, że jesteśmy wszystkim?" Shri Mataji: "Gdy jesteście duszą zrealizowaną, jeśli nią jesteście, ale czy czujecie wibracje? Czy odczuwacie wibracje innych? Jeśli nie, to jest tylko mitem" Poszukiwacz: "Mi się to przydarzyło, ale to był taki szok, że wróciłem do ciała" Shri Mataji: "Lepiej zacznij poważnie zajmować się Sahaja Yogą. Dobrze?" Poszukiwacz: "Kiedy opisuje Pani stan świadomości bez myśli, czyni go Pani tak pięknym, że wydaje się to takie łatwe, więc dlaczego dla niektórych jest to tak trudne do osiągnięcia?" Shri Mataji: "Wiem, wiem, wiem, lecz trzeba to wykonać w ten sposób, że patrzysz na coś bez myślenia. Spróbujcie! Spróbujcie to zrobić. Wiem, że dla niektórych jest to trudne, ponieważ cały czas w głowie jest zbyt wiele myśli.

Teraz myśl przychodzi z lewej lub z prawej strony, to znaczy pochodzi z przeszłości, z naszych uwarunkowań i pochodzi z prawej strony z naszym ego i futurystycznymi ideami. Cały czas. Więc jedna myśl będzie się pojawiać, opadać, następna będzie opadać i podnosić się, a my skaczemy na krawędzi myśli. Jednak gdy Kundalini się podnosi, dzieje się tak, że te myśli wydłużają się i powstaje przestrzeń pomiędzy nimi, a to jest świadomość bez myśli. Ludzie mają z tym problem i nie wiedzą jak to zrobić. [Poprzez] podniesienie swojej Kundalini. Podnosicie swoją Kundalini, podnosicie Kundalini innych, nagle odkrywacie, że stajecie się świadomym bez myśli. To nie trudne. Co to jest?" Poszukiwacz: "To właściwie nie jest pytanie, przyjaciel przyprowadził mnie dziś wieczorem i przyszedłem tutaj z dużym sceptycyzmem, ale doceniłem bezpośredniość i prostotę tego, co Pani powiedziała i sposób, w jaki wyjaśniła Pani kwestie."

Shri Mataji: "Dziękuję." Poszukiwacz: "Czy jest jakiś powód, dla którego Boska miłość manifestuje się jako chłodny powiew?" Shri Mataji: "Powinniśmy zapytać o to Boską Miłość" Poszukiwacz: "Czy według Pani w przyszłości nadejdzie czas gdy będziemy mieli globalną Samorealizację wśród światowych przywódców, co sprawi że ludzie nie będą głodować tak jak teraz? Czy według Pani nastąpi to w Erze Wodnika?" Shri Mataji: "To jest ta Era Wodnika. To jest ta Era, ale nie możemy powiedzieć, ilu W niej będzie zbawionych osób. Nie możemy powiedzieć. Jeśli wy to osiągniecie, możecie uratować tak wielu. Ale to jest Era Wodnika, bez wątpienia. Poszukiwacz: "Jak wybacza Pani całkowicie?"

Shri Mataji: "Niezależnie od tego, czy przebaczasz, czy nie, i tak nic nie robisz. Co robicie? W porządku? Ale kiedy mentalnie nie przebaczasz, to wtedy cierpisz, a nie druga osoba." Poszukiwacz: "Jak można zmienić swoje serce, aby móc przebaczyć?" Shri Mataji: "Serce nie jest w tym potrzebne. Trzeba tylko zrozumieć, że nic nie robisz wybaczając, czy też nie wybaczając. Po prostu mówisz "wybaczam" Poszukiwacz: "Mogę to powiedzieć, ale nie mam tego na myśli" Shri Mataji: "Możesz nie mieć na myśli, ale to jest mantra, po prostu mów" Wybaczam wszystkim " W porządku? To działa. To działa" Poszukiwacz: "Czy Sahaja Yoga jest odpowiedzią na wiele problemów psychiatrycznych?"

Shri Mataji: "Kto? Ty?" Poszukiwacz: "Czy to może rozwiązać problemy schizofrenii?" Shri Mataji: "Oczywiście" Poszukiwacz: "Ludzie inwestują dużo pieniędzy w badania psychiatryczne" Shri Mataji: "Co można zrobić, jeśli Mnie nie słuchają!" (brawa) Poszukiwacz: "Czy Pani uważa, że jest w nas wszystkich światło i wszyscy jesteśmy częścią Boga i czy dla przyszłych pokoleń przyniesie to korzyść całemu światu?" Shri Mataji: "Oczywiście, że tak" Poszukiwacz: "Czy przyniesie korzyści przyszłym pokoleniom? Czy to właśnie Pani próbuje zrobić?" Shri Mataji: "Tak. Lecz to co mówię oznacza – najpierw umacniajcie waszą Samorealizację, doprowadźcie się do porządku, doskonalcie się, a następnie będziecie mogli to robić sami." (ten sam poszukiwacz ponownie próbuje zadać to samo pytanie!)

Shri Mataji: "Pracuj nad tym aż przyjadę następnym razem i nie będziesz wtedy zadawać żadnych pytań!" (brawa) Poszukiwacz:"Czy Matka chroni nas w Sahaja Yodze, gdziekolwiek jesteśmy?" Shri Mataji:"Oczywiście, ale nie chcę tego mówić . Możecie tego doświadczyć." Poszukiwacz: "Jak mam wiedzieć, że osiągnąłem Samorealizację?" Shri Mataji: "Poczujesz chłodny powiew na twoich dłoniach twoje i wychodzący z obszaru kości ciemiączka. To jest pierwszy krok, pierwszy krok." Poszukiwacz: "Czy podczas praktykowania Sahaja Yogi nadal można używać innych technik duchowych, takich jak Reiki i Kryształy" Shri Mataji: "Nie, nie! Doświadczenie Reiki było bardzo złe. Nie nie nie nie!

Jeśli mnie o to pytasz, powiedziałabym, nie rób tego, gdyż wiem, jak ludzie cierpieli z tego powodu. To nie jest zgodne z nauką. A teraz wszyscy proszę, wyciągnijcie ręce w moją stronę i zamknijcie oczy. Zapomnijcie o wszystkich pytaniach..." Jedyne, co musicie zrobić, to przebaczyć. Przebaczyć wszystkim, to wszystko. Po prostu powiedzcie, tylko powiedzcie: "Przebaczam". Po prostu powiedzcie: "Przebaczam, przebaczam wszystkim". Zobaczcie jak to będzie działać. A teraz wyciągnijcie prawą rękę w Moją stronę, a lewą rękę połóżcie na szczycie kości ciemiączka. I sprawdźcie nie dotykając jej wierzchołka, czy z głowy wydostaje się chłodny lub gorący powiew.

Jeśli jest gorąco to znaczy, że macie jakieś problemy z wątrobą lub coś podobnego. A to warto skorygować, a może nie wybaczyliście. Czasami wieje za bardzo na boki lub do góry. Proszę sprawdźcie sami. Teraz wyciągnijcie proszę lewą dłoń do Mnie, a prawą dłoń połóżcie na szczycie głowy. Pochylcie głowę, lepiej ją pochylić. A teraz sami sprawdźcie, czy z okolicy ciemiączka wydobywa się chłodny, czy też gorący powiew, ta kość była miękka gdy byliście dziećmi. Po prostu sprawdźcie. To jest chrzest, prawdziwy chrzest, urzeczywistnienie chrztu. Teraz wyciągnijcie obie dłonie w ten sposób do Mnie, otwórzcie oczy.

I przekonajcie się sami, czy w waszą stronę płynie chłodny powiew, czy też gorący, podobny do wibracji płynących do was. Niektórzy mogą odczuwać to pod dłońmi, więc je przełóżcie w ten sposób. Niektórzy mają takie odczucia. Bardzo dobrze. Proszę podnieść ręce w ten sposób. W ten sposób. Stajecie się bez myśli. Patrzcie tylko na Mnie. Niech Bóg was błogosławi.