Šrí Krišna Pudža, Los Angeles (Spojené štáty), 18. septembra 1983

Keď som prvýkrát prišla do Spojených štátov, ako prvé som prišla do Los Angeles. Lebo je to miesto anjelov. Myslela som si, že na toto veľmi sväté miesto treba prísť najskôr, ak cestujete do tejto veľkej krajiny Spojených štátov.

Ako viete, celé Spojené štáty, alebo Amerika, je Višudhi čakra. Máme tri strany Višudhi čakry. Takže stredná časť Višudhi čakry sú Spojené štáty.

Strednej časti Višudhi čakry vládne Šrí Krišna. A jeho silou je Radha - „RA - DHA‟. „RA‟ znamená energia, „DHA‟ znamená ten, kto podporuje energiu. „RA - DHA‟.  „Dha-re-ti-saa‟. Takže ona je tá, ktorá vyživuje energiu, a tak je nazývaná Radha. Je silou Šrí Krišnu.

Slovo Krišna je odvodené od slova - kriši, čo znamená - orať. Alebo môžeme povedať, poľnohospodárstvo sa volá „kriši‟. Ten, kto orie a sadí semená do pôdy, robí kriši. Preto sa volá Krišna.

Semeno, ktoré zasial, je semeno duchovnosti. Bol to Šrí Krišna, ktorý povedal v sanskrite - „nainam chindanti shastrani nainam dahati pavakah na chainam kledayanty apo na sosayati marutah‟. Čo znamená: Nie je možné - mysliac tým na duchovný život alebo môžeme povedať večný život, alebo Ducha - nemožno ničím zabiť, žiadnou zbraňou, nemôže byť odviaty vetrom ani vysatý, ani nič ho nemôže zničiť.

Takže Kristus prišiel na tento svet aby dokázal svojím vzkriesením to, čo povedal Šrí Krišna. A väčšina sahadža jogínov pozná vzťah medzi Kristom a Šrí Krišnom - prečo sa volá Kristus. Slovo Kristus pochádza z toho istého - Kriši. A jeho prvé meno pochádza zo slova Jašoda. Jašoda sa nazýva aj Dže-su alebo Je-su. Preto sa (Kriš) Kristus volá Dže-su alebo Je-su. Niektorí ho volajú Jesu a niektorí ho volajú Džesu, kvôli Jašode, nevlastnej matke Šrí Krišnu.

Tiež viete, že Radha bola tá istá Mahalakšmi, bola to tá istá matka Krista, Mária. Všetky tieto veci vieme v Sahadža joge dokázať. Lebo ak Kundalini stúpa hore k Višudhi čakre a ak sa tu zastaví, môžete sa opýtať - Bol Ježiš synom matky Márie? Bol synom Ra, čo je to isté ako Radha? A Kundalini sa začne pohybovať.

Dnes teda Sahadža joga dokáže, čo bolo doteraz povedané. Dokazuje to. Nie je to len vymyslený príbeh. Lebo ľudia tomu neveria. Myslia si, že je to všetko vymyslené. Kto bol Kristus? Kto bol Krišna? Kto bola Radha? Nakoniec, nebol žiaden Boh.

Ale dnes len v Sahadža joge môžeme dokázať, že čo hovoríme, je pravda. Lebo vďaka Realizácii ste pripojení k hlavnému zdroju. Vaše vibrácie začnú prúdiť. Začnete pracovať ako počítač. A keď položíte akúkoľvek otázku, odpoveď k vám príde ako ohromné vibrácie, alebo sa zastavia, alebo pocítite teplo, alebo môžete dostať pľuzgiere. Takže celý odkaz je vám odovzdaný cez vaše končeky prstov.

Mohammed Sahib veľmi jasne povedal, že „v čase vzkriesenia budú hovoriť vaše ruky‟. Ale moslimovia vôbec nechcú hovoriť o vzkriesení. Lebo chcú ľudí strašiť súdnym dňom. Nechcú hovoriť o čase vzkriesenia, ktorý prichádza, ktorý je prechodným obdobím. Lebo chcú čas využiť na strašenie ľudí tým, že hovoria: „Teraz prichádza váš súdny deň‟. Teraz prichádza váš súdny deň, a tak sú všetci z Boha vystrašení a myslia si, že teraz by mali čakať svoj súd, nič medzi tým.

V tomto je Višudhi čakra špeciálna. Višudhi čakra bola vytvorená v sobotu. Saturn je dôležitá hviezda pre Višudhi čakru. Keď bude Saturn najvyššie, Amerika bude lepším miestom na konanie. Ale nemyslím si, že o sebe vedia veľa. Nevedia, kto sú, prečo sú na tomto svete, aká je ich práca, čo by mali robiť alebo aký dôvod mal Boh na stvorenie Ameriky.

Prvou prácou Višudhi čakry v nás bolo to, keď sme sa stali ľudskými bytosťami, keď sme takto vzpriamili hlavu. Keď ste takto vzpriamili hlavu, stali ste sa ľudskými bytosťami v takom význame, že teraz je vo vašom vedomí nový pohyb. Nový pohyb vo vašom vedomí začal pred 6000 rokmi, keď prišiel na túto Zem Šrí Krišna. Ten nový pohyb bol, že je to Otec. Bol oslavovaný advent Otca, a tak si ľudia v sebe vyvinuli nový nástroj nazvaný ego.

Keď bol mozog takto zdvihnutý, tak sa pyramídovo rozšíril - je to pyramída - stal sa pyramídou. U zvierat je mozog plochý. A postupne sa dvihol. Keď bola hlava vzpriamená, keď bola prevzatá zodpovednosť dvihnutím hlavy, mozog začal rásť takým spôsobom, že sa zmenil na pyramídu. A keď sa zmenil na pyramídu, tak sa zmenila pozornosť a bola to iná pozornosť, ako majú zvieratá. Lebo keď vlny vášho vedomia padnú na strany pyramídy, dostanú sa do silového rovnobežníka, vďaka čomu výslednica - výsledná sila - takto klesne, ide takto, výsledná sila je takáto - má dve strany - jedna je tu, druhá je tu. (Šrí Matadži pohybom ukazuje y a x os grafu). Takže vedomie, alebo môžeme povedať pozornosť, namiesto toho, aby išla dovnútra, začala prúdiť von!

Takže jedna časť výslednej sily išla von a preto, keď ste sa stali ľudskou bytosťou, vaša pozornosť išla von. Sú to jedine ľudia, ktorí majú svoju pozornosť vonku. Niežeby ju zvieratá nemali, ale pozornosť ľudí je taká, že vytvárajú reakcie.

Povedzme, že niečo vidíte. Teraz napríklad vidím dom lekára, tak v mojej mysli začnú reakcie - čo to je, čo to znamená, koľko to muselo stáť, kde to kúpil! Ak vidíte čokoľvek, tak vám vedomie začne dávať reakcie. Nie je to tak u zvierat. Zvieratá najviac povedia - toto musím zjesť, tamto musím zjesť, toto musím získať! Ale nepremýšľajú o tom.

Sú to jedine ľudia, ktorí zvažujú. A toto uvažovanie je kvôli pyramídovej štruktúre mozgu. A toto má zvláštnu reakciu v samotnom mozgu, že si začneme budovať svoje vlastné ego, svoje vlastné mýty, svoje vlastné mentálne predstavy. A keď si vytvoríme svoje vlastné mentálne predstavy, tak toto ego si začne vytvárať: „Ja viem!”, “Čo je na tom zlé?“ prichádzajú všetky tieto nezmyselné veci. A keď to raz začne fungovať, začne stúpať balón ega. Začne zatláčať druhý balón, ktorý v nás bol, je to superego - ako u zvierat. A potom príde do stredu. Tak sme sa teraz stali normálnymi ľudskými bytosťami. Ale potom začneme svoje ego zväčšovať. Začne prekrývať superego a nastáva kalcifikácia, ktorou si vyvinieme svoje Ja-stvo.

Toto všetko nastáva potom, ako sme vzpriamili hlavu, zodvihli hlavu a už viac nie sme ako zvieratá. Takže Višudhi čakra hrá veľmi dôležitú úlohu v ľudskej evolúcii. Rozvinutím vašej Višudhi čakry ste sa v prvom rade stali ľuďmi. Po druhé, pretože je to čakra Otca, ktorý sa opäť stal prvotný - ako to nazývate (v marathi) … makrokozmos.

Stali sa makrokozmom. Ste mikrokozmom a Otec je makrokozmos. Stali ste sa tým vďaka Višudhi čakre, ktorej vládne Šrí Krišna, ktorý sa stal tým makrokozmom nazývaným Viráta. V mozgu je vyjadrený v tejto časti (Šrí Matadži ukazuje na čelo). V tejto časti hlavy. Tu ste začali prejavovať svoje kvality makrokozmu - v tomto mieste.

Táto Višudhi čakra má svoje zvláštnosti - vždy hovorievame, že zodpovednosť je na mojich ramenách. Vždy hovorievame - zodpovednosť je na mojich ramenách. Dôvodom je, že Višudhi čakra vám dáva zmysel pre zodpovednosť. A viete, preto sa Američania cítia zodpovední za celý svet. Prirodzene! Je to úplne jasné, že sa cítia zodpovední za celý svet. Ale ako si uvedomujú svoju úlohu ako zodpovední ľudia, to je už niečo iné. Cítia, že sú zodpovední, ale ako zodpovední ľudia, musia pochopiť, že majú byť ideálom. Ideálom.

Lebo človek, ktorý je v rodine zodpovedným, musí byť pre ostatných ideálom. Povedala by som, že to veľmi dobre začalo za čias Abrahama Lincolna. Začalo to veľmi dobre. Keď ste začali hovoriť o demokracii, demokracia nie je nič iné, len kolektivita. Začal hovoriť o kolektivite ľudí pre ľudí. To všetko ukazuje, že zmysel pre kolektivitu začal práve v tejto Višudhi čakre. Ale potom, len ľudia, ktorí sú v strede, môžu zostať normálnymi. Ale tí, ktorí sa príliš sklonia, alebo ktorí sa príliš zaklonia, trpia problémami.

Tí, ktorí sa klaňajú druhým, sú tí, ktorí dostanú superego. Stali sa prehnane pokornými, ako sú rozvojové krajiny. A tí, ktorí sa zakláňajú, sú ľudia, ktorí sa snažia druhých ovládať. Majú ego. Vďaka náhlym Božím požehnaniam odhalili mnohé veci. Ego sa začalo v Amerike príliš rozvíjať.

Ale ego je ako balón, ako som vám povedala. A drží vás, lietate vo vzduchu. A keď ste vo vzduchu, stanete sa povrchnými ľuďmi. Nemáte žiadne ukotvenie. Ale má to jednu výhodu. Ak viete, že lietate vo vzduchu, môžete mať úplný komplexný nadhľad. Úplnú víziu celku, ak sú vaše oči čisté a vaše zámery sú jasné.

Ďalšou vecou, ktorá sa stala ich príchodom sem, bol problém, že cítili, že sme veľmi nový národ. Má to výhodu a rovnako aj nevýhodu. Výhodou je, že ak ste nový, je to veľmi dobré, lebo sa veľmi ľahko môžete zmeniť na niečo lepšie, lebo vo vašej mysli niet žiadnych podmieneností.

Ste veľmi čistý, úplne pripravený niečím sa stať. Alebo je možné, že ste tak nový, že ste užasnutý všetkým, čo je staré. Čo je veľká pravda o Američanoch, keď kupujú všetky staré mosty z Anglicka a vozia ich sem. A túžba po starých veciach je príliš veľká.

A tak všetko, čo je nové, je pre nich absurdné! Takže možno aj Sahadža joga je pre nich absurdná vec. Lebo podľa nich je to niečo nové. Lebo sú novým národom, tak začali odhadzovať všetko, čo je nové. Je to absurdné.

Musíme povedať, že Sahadža joga je dnes najstarodávnejšou vecou. Začala s vesmírom a teraz prišiel bod vyvrcholenia, lebo je to živý proces. Keď vidíte na strome kvet, je to prvý nový kvet. Ale kvet musel vyrásť zo semienka, ktoré má najskôr korene, potom kmeň, potom listy a až potom sa stane kvetom. Takže aj keď vyzerá ako nový kvet, má za sebou veľké dedičstvo. Rovnako Sahadža joga je starodávna, tak ako vesmír.

Ale pre ľudí, ktorí tak prahnú po tradicionalizme, je zložité rozpoznať, čo je skutočná tradícia. Jedine tradiční ľudia môžu poznať, čo je skutočná tradícia. Keď som poslednýkrát prišla do Ameriky bola som šokovaná z človeka, ktorý prišiel so mnou robiť rozhovor. A keď hovoril, opýtal sa ma na pána, ktorý je podľa indického uhla pohľadu najnetradičnejším. Jeho meno bolo Ramakrišna Paramhamsa. Oženil sa so ženou, ktorú urobil matkou. Myslím, že to nikto neurobil. Rama to neurobil. Krišna to neurobil. Je to úplne absurdné. Ale pre nich to bol najtradičnejší človek. A povedal mi: „Matka, vaša Sahadža joga nie je tradičná, ak neveríš v Ramakrišnu.“

Za posledných päťdesiat - šesťdesiat rokov prišlo veľa takýchto neo-tradičných ľudí. Ďalším je tento Pondicherry. Ďalšia absurdná situácia. Túto ženu nazýval matkou a jeho vzťah s ňou je dvojzmyselný. Neviete, aký je medzi nimi vzťah. Toto je niečo, čo je v indickej tradícii nemožné.

S každým musíte mať úplne jasné vzťahy. Nemôžete mať dvojzmyselné vzťahy. Ani priateľ ani manželka či matka alebo sestra. Takáto situácia je najnetradičnejšia. To by nikomu ani nenapadlo. Myslím, že vy, Indovia viete, že toto nie je možné. Je to absurdné. Ale pre niektorých je (Ramakrišna) tradičný.

Čo sa stalo asi pred šesťdesiatimi rokmi, myslím v čase môjho narodenia. Negativity začali dostávať nové formy, lebo chápali západnú pomätenosť. Ak si ich všimnete, všetci sú v tomto západní. Prevzali západný zmätok pre svoj vlastný prospech. Používajú ho pre svoj úžitok. A v tomto západní ľudia zlyhávajú, aby ich odhalili.

Raz som bola u jungovcov a mala som k tým ľuďom hovoriť o Sahadža joge a Jungovi. O Jungovi som sa dozvedela, len keď zomrel, lebo bol o ňom krátky článok. Nikdy som neštudovala psychológiu. Samozrejme som sa snažila naučiť nejakú slovnú zásobu, aby som k nim hovorila. Myslela som, že možno budem niekedy aj k nim hovoriť. A títo jungovci, všetko veľkí intelektuáli a veľkí ľudia, sedeli predo mnou.

… prezident americkej spoločnosti Junga. Len som si predtým prelistovala knihu a videla som nejaké diagramy, ktoré ma skutočne zmiatli. Prvú predstavu, ktorú majú, samozrejme, to sú všetko Jungove mentálne predstavy. Neobviňujem ho, lebo on dostal Realizáciu, ale nevedel, ako bol tento stav vytvorený, aká bola štruktúra tohoto stavu a jeho pohyb bol stále ako u hľadača, ktorý hľadá to, ako získal Sebarealizáciu.

A všetky pohyby boli lineárne. Nerozširovali sa z jedného bodu všade. Nebolo to dosť integrované. Myslia si, ukazovali, že naspodku je nevedomie, ktoré sa nikdy nestane vedomím. Na tom je nevedomie, ktoré sa môže stať vedomím. Potom je podvedomie a na vrchu je ego. Poviem vám, bol to úplný zmätok.
Povedala som im, pozrite, aj samotné slovo nevedomie je zmätočné. Čo myslíte tým nevedomím? Všetko, čo necítite vo svojom centrálnom nervovom systéme, je nevedomie - tak? Ale čo to znamená? Podvedomie necítime. Tak aj podvedomie je nevedomie. Všetko to, čo necítime - napríklad existujú určité zvuky, isté frekvencie, ktoré vôbec nepočujeme. Počujeme to, čo je pre nás ako ľudí tolerovateľné. Vy vedci to všetko viete. Nepočujeme všetko.

Takže všetko nevedomie znamená, že je pomiešané vrece. Všetky typy spolu zamiešané. Ale viete, Boh nie je zmätená osoba. On je jasný džentlmen. Vie, čo robí. Je najlepší organizátor. Ako by to mohol takto dať do vreca, že na spodok nevedomie, na to nevedomie, ktoré sa stane vedomím, na to podvedomie, na to vedomie a na to všetko ego! Tak zostupujete dole a nesiete si v sebe toto všetko a kam sa dostanete? Ako pôjdete?

Takže prvou chybou bolo tvrdenie, že existujú vrstvy jedna na druhej - tak to nie je. Sú umiestnené vertikálne. Ego je na pravej strane a superego je na ľavej strane. Budúcnosť je na pravej strane a minulosť na ľavej strane. Takže podvedomie je na ľavej strane a nadvedomie na pravej strane. A stredná cesta sa udržiava čistá. Myslím, že v každej organizácii, povedzme, že idete na letisko, tak to nie je tak, že  by ste museli prejsť cez steny, aby ste sa dostali do lietadla.

Ak my ľudia nerobíme také hrozné chyby, akoby Boh mohol robiť také chyby? Bolo teda úplne nesprávne takto rozmýšľať. Takže stredná cesta je v strede, zatiaľ čo pravá strana je vpravo a ľavá strana je na ľavej strane. A do podvedomia nemusíte vôbec chodiť. Lebo sa snažili ospravedlňovať tých ľudí, ktorí ich učili hypnotizovať alebo sa ich pokúšali hypnotizovať, alebo im dať novú skúsenosť - to všetko bolo nevedomie, to by sme mali akceptovať. Dokonca ak niekto začal odrazu skákať, povedali: „Ó, to je úžasné.“

Takže vnemy, ktoré získate z podvedomia alebo z nadvedomia, boli prijímané ako niečo veľké. Povedala by som, že to bol zmätok vašich intelektuálov. Úplný. Ale nie je to tak. Vaša cesta je priama. Pre Kundalini je úplne priama. Jediná vec pre toho, kto má stúpať, je len to, že sa to musí stať - to je všetko. Inak je to všetko veľmi dobré, nemusíte chodiť do toho hrozného podvedomia.

Keď som im to povedala, boli udivení. Povedali - Matka je to tak jednoduché. Povedala som - je to veľmi jednoduché. Vaše nevedomie je rozdelené na štyri. Jedno je kolektívne podvedomie, jedno je kolektívne nadvedomie, jedno je, môžeme povedať, kolektívne peklo a na vrchole je superkolektívne vedomie.

Takže kam máme ísť? Mali by sme poznať cieľ. Potom ho musíme dosiahnuť.

A takto sa ľudia s týmto problémom zaplietli s Muktanandom. Áno, opýtali sa ma - Čo je na Muktanandovi zlé? Prečo je tak nebezpečný? Jedna pani, chúďatko, prišla a povedala - išla som tam, zlomila som si chrbát a nadobro som skončila. On je tak nebezpečný človek. Lichotil mi. Išla som tam a neviem, čo sa stalo s mojím chrbtom. Nemohla som sedieť viac ako desať minút na jednom mieste, musela som vstať. A mala som vibrátor a vždy som si to musela takto dávať. Ako som povedala, vidíte to nebezpečenstvo.

Potom začali ďalšiu teóriu, že ak máme prísť k Bohu, musíme trpieť. Prečo? Myslím, že to v žiadnom prípade nie je nápadom Boha. Prečo by sme mali trpieť? Nechal trpieť Krista pre vás - teraz je to hotové. Radšej netrpte. Vôbec nie je potrebné, aby ste trpeli.

Takže všetky tieto nápady prenikli do západných ľudí. A tieto mentálne predstavy  prijali bez porozumenia toho, čo sa píše v iných knihách. Mali by sme vidieť. A mohli by ísť maximálne do šesťdesiatych rokov, kde všetci títo hrozní ľudia, ktorí prišli do Indie, veľmi plytkí ľudia, videli nejaké tantrické knihy, lebo chceli ospravedlniť Freuda pomocou indickej kultúry. Tak vzali tantrické, erotické veci a to všetko a priniesli tieto knihy a niektoré prečítali – nepoznám, aké knihy - aby povedali, že Kundalini je v žalúdku, niektorí hovoria v mozgu. Myslím, že nevedia, kde je Kundalini. Píšu veľké knihy. Viete si to predstaviť? Napísali také veľké knihy.

Ak sú knihy napísané, tak nie každá kniha je Písmo. Ale pre nich, ak je to napísané v knihe, tak je to Písmo. A tak začal celý ten zmätok. Títo ľudia prišli, využili to a teraz sa stali veľkými guruami s množstvom peňazí. Bohatí ľudia. Ale teraz, keďže Božia ruka je veľká, tak jeden po druhom vychádzajú z hláv ľudí. A teraz dúfam, že príde deň, keď ľudia uvidia svetlo.

Takže úlohou Sahaža jogy je upevniť vo vás pravdu. Nemôžeme mať členstvo. Nemôžeme do toho nikoho zapísať. Nemôžeme ich nazvať značkovými sahadža jogínmi. Je to rast človeka, ktorý musí byť vidieť.

Urobila som veľa prednášok o ritambara pragya a o tom všetkom a myslím, že pre každého sahadža jogína je nevyhnutné počúvať tieto prednášky, prechádzať cez ne, porozumieť im a meditovať, aby ste rástli. Lebo to nie je umelá vec, ktorú môžeme vytvoriť. Je to živý proces, živej energie, živého Boha. Takže to musí rásť. Nevyrastie to premýšľaním, ale nepremýšľaním tomu dovolíte rásť viac a viac.

Ak to začne vo vás rásť, len potom si uvedomíte, kým ste. Je to jediný spôsob, ako dosiahnuť tento stav supervedomia a upevniť sa v ňom. Až potom budete vedieť, o čom hovorím.

Dnešná pudža je niečo iné. Čo je Pudža? Môžete (vy ľudia) povedať, čo je pudža? V skutočnosti som mala včera pudžu a pre mňa to nie je jednoduché znášať pudže, úprimne povedané. Lebo vibrácií je tak veľa, že neviem. A potom som išla na letisko - dve hodiny sme vyberali vibrácie a dávali ich všade na New Yorskom letisku. Bolo to potrebné. Fungovalo to.

Lebo vibrácie začali prúdiť s ohromnou silou a ak ich vy neabsorbujete, trvá to nejaký čas, kým sa vytratia z môjho tela. Dosť ma to zaťažuje. Ale ak vyprchajú, tak sa cítim lepšie a hovorením mantier sa stane jedna vec, prebudíte v sebe božstvá a začnete prijímať vibrácie. A keď sú vaše božstvá prebudené, tak sú prebudené cez silu božstiev, ktoré sú vo mne - musia veľmi ťažko pracovať, aby to urobili, a preto vyžarujú príliš veľa vibrácii, ktoré musíte absorbovať, keď sú prebudené vaše božstvá. Takto to funguje. Nemôžete to opísať slovami. Nemôžete to povedať slovami. Je to udalosť, ktorá sa musí stať.

Veľa ľudí, ktorí prišli po prvýkrát do Sahadža jogy, môže na začiatku ísť trochu takto  (Šrí Matadži zamávala rukami). Postupne sa usadia, prídu k sebe, vyrastú v tom, potom sú v poriadku. Niektorí sú za jeden deň vystrelení a sú tam. Niet v tom žiaden rozdiel. Lebo je to vec rastu, tak to musí rásť. U niektorých ľudí je pôda tak úrodná alebo tak nejako, že to rýchlo funguje. Nikto by nemal nikoho obviňovať. A obzvlášť nikto by sa nemal cítiť vinným, lebo to je Višudhi na ľavej strane.

Zvlášť pre Ameriku nosím tento kameň, ktorý sa nazýva čierny zafír. Lebo je to kameň Šrí Krišnu. Je to kameň Višudhi čakry. Každá čakra má svoj kameň. A toto je kameň Višudhi čakry, tak ho nosím, ako som prišla do Ameriky. A dúfam, že dnešné uctievanie prinesie tejto krajine potenciál prebudením božstiev, samotného Šrí Krišnu, ktorý je zodpovedný. Tým, že ho potešíte. Tým, že začne byť aktívnym. Má ohromné kvality a jednou z jeho najväčších kvalít je, že má sanwahra šakti, pomocou ktorej môže zabiť démonov. A všetci títo démoni, ktorí sa tu usadili, sa skutočne pomýlili. Lebo ak je toto miesto Šrí Krišnu, tak sú na veľmi nebezpečnom mieste. Lebo ak sa tu raz prebudí, tak všetci títo skončia jeho sudaršana čakrou, ktorú má v ruke, a môže ich zabiť jedného po druhom.

Ale najskôr ho treba potešiť a musí sa prebudiť a musí byť „prasanna‟. To je to správne slovo. Prasanna znamená byť potešený. A potom to funguje.

Takže dnes budeme mať najskôr Ganeša pudžu, krátko, lebo Ganeša pudža je pre upevnenie nevinnosti. Nevinnosti miesta. Ak je raz nevinnosť upevnená, to je to najdôležitejšie. Je to podstata všetkého. Ganéša je podstata. A potom budeme mať Šrí Krišna pudžu a potom pudžu Devi, Sily. Takto budeme mať tri pudže - jednu po druhej, ale každú len krátko. Dobre?