Wartość Małżeństwa, 08.03.1980, Dollis Hill Ashram, Londyn

…w Sahaja Yodze najpierw następuje wasze kiełkowanie, następnie jest wzrost.

W tym wzroście, musicie stawać się coraz szerszą osobowością. W małżeństwie stajecie się jeszcze lepszą osobą i rozwijacie lepszą osobowość. Zatem, dlaczego małżeństwo jest konieczne dla Sahaja yoginów? Przede wszystkim, wzięcie ślubu jest czymś najnormalniejszym. Bóg dał wam pragnienie wzięcia ślubu w pewnym celu. Jednak, to samo pragnienie, jeśli nie użyjecie go w przeznaczonym do tego celu, może stać się perwersją, może stać się okropną rzeczą. Może być bardzo szkodliwe dla waszego wzrostu. Zatem, by wziąć ślub należy zrozumieć to pragnienie wewnątrz nas.

Małżeństwo oznacza żonę, która stanowi nieodłączną część ciebie. Żonę, na której możesz polegać. Ona jest twoją matką, ona jest twoją siostrą, ona jest twoim dzieckiem, ona jest wszystkim. Możesz dzielić wszystkie swoje uczucia ze swoją żoną. Zatem to jest ważne, że żona powinna być taka i rozumieć, że jest to niezbędne w małżeństwie.

Jak zauważyliście, w Sahaja Yodze wszyscy macie problemy, są one po lewej lub po prawej stronie. Kiedy dojdzie do małżeństwa, przeważnie spontanicznie to się stanie poprzez sam plan natury, że poślubicie osobę, która jest uzupełniającą osobowością do was. Ponieważ, przypuśćmy, że jesteś lewostronną osobą, jeżeli będziesz miał osobę, której lewa strona jest bardzo silna, to się wyrówna i w ten oto sposób tworzycie dobre małżeństwo.

Ale w tym celu, jedna rzecz jest bardzo ważna, musicie się dzielić. Musicie dzielić wspólne życie, każdą jego cząstkę, każdy jego moment. Jeżeli nie wiecie jak dzielić wspólne życie, to będzie to bardzo, bardzo trudne. Jeżeli chodzi o miłość, jak okazujemy naszą miłość?

Poprzez dzielenie się całą naszą radością, naszymi bólami, wszystkimi naszymi problemami.

A w Sahaja Yodze to jest trochę więcej, myślę, że o wiele więcej, dużo więcej. Tu musicie dzielić się ze społecznością. Małżeństwo w Sahaja Yodze w żadnym wypadku nie jest dla indywidualistów. Jeśli ktokolwiek ma takie odczucie, że małżeństwo w Sahaja Yodze jest pomiędzy dwiema osobami, to się myli. To są dwie społeczności, to mogą być dwa narody, to mogą być dwa zupełnie inne światy.

Zatem, to nie jest po to, abyście dzielili się radością jedynie ze sobą. W Sahaja Yodze to nie wystarcza jeżeli jesteście dla siebie nawzajem dobrym mężem-żoną. Tą miłością powinni się cieszyć wszyscy inni w społeczeństwie, w społeczności. Jeżeli nie potraficie tego dokonać, to nie osiągnęliście małżeństwa w Sahaja Yodze.

 To jest po prostu zwyczajne małżeństwo jakie ludzie mają, nie ma w nim nic wyjątkowego. Małżeństwo powinno dawać szansę na przyjście wspaniałych dusz na tę ziemię. Osobom, które są poślubione w Sahaja Yodze, które są Sahaja yoginami, które dzielą się swoją miłością jednakowo z Sahaja yoginami i ze społecznością Sahaja Yogi, tylko wtedy urodzą się im wspaniali ludzie. Powiedziałabym, że Bogdan to osiągnął. Bogdan i Mandy, oni to osiągnęli. To coś zaskakującego. Oni byli zaręczeni przed ślubem, zostali małżeństwem przed Sahaja Yogą, pobrali się po Samorealizacji i nie wiem jak to zaskoczyło w ich życiu, że naprawdę dzielą towarzystwo z innymi Sahaja yoginami. Ilekroć on pisze do Mnie, to zawsze pisze o innych Sahaja yoginach, pyta o każdego z nich, jak się miewają, jakie mają problemy. Dopóki to się nie wydarzy, to małżeństwo w Sahaja Yodze nie ma w ogóle znaczenia.

Zatem, pierwszym małżeńskim testem dla Sahaja yogina jest to, jak bardzo dzielił to małżeństwo z innymi ludźmi.

Na przykład, w zwykłym małżeństwie mówi się, że mężczyzna jest głową rodziny. On musi być głową, mężczyzna musi być głową z pewnych powodów. Nie ma nic w tym złego, że mężczyzna staje się głową, w porządku, a wy stajecie się sercem. Serce jest dużo ważniejsze od głowy. Być może nie zdajemy sobie sprawy, jak ważne jest serce. Zobaczcie, nawet gdy zawiedzie głowa to serce wciąż bije. Zawsze możemy funkcjonować, jeżeli serce bije. Ale jeśli serce się uszkodzi, to głowa również się uszkodzi.

Zatem, jako kobiety, jesteście sercem, a on jest głową rodziny. Niech ma to odczucie, że jest głową, to jest odczucie, tylko odczucie.

To tak jak głowa, wciąż czuje, że to ona decyduje. Ale to mózg, który również wie, że to serce jest tym, z którym trzeba się liczyć. Serce jest tym, które wszystko przenika, które jest prawdziwym źródłem wszystkiego. Zatem pozycja kobiety, jeśli ona zrozumie jak jest to ważne, wtedy ona nigdy nie poczuje się zawiedziona lub zdominowana, jeśli ona wie, że ona jest sercem.

Uważam, że to jest punkt, który ludzie, kobiety, głównie na Zachodzie, straciły, zapomniały i nie uświadomiły go sobie. Jeśliby uświadomiły by sobie ten punkt, to byłby dużo mniejszy problem. To nie tak jak ludzie myślą, że kontrolują i dominują innych lub próbują ich stłumić, to nie tak.

To serce jest tym, które naprawdę wszystkim zarządza. To serce panuje nad wszystkim. To serce otrzymało moc, aby otoczyć mózg i go ukoić.

Wiecie, że mózg to tylko ból głowy, pracuje, pracuje jak szalony. Tylko serce jest tym, które naprawdę pokrywa całe ciało swoją miłością i potrafi ukoić je, potrafi dać mu radość i szczęście. To w sercu rezyduje Duch. Zatem to serce jest bardzo ważne, bo jest mocą ciała. Ostatecznie musicie stać się Duchem, który rezyduje w sercu.

Za pomocą mózgu wiecie o rzeczach i to dlatego mężczyzna musi być głową. On musi wyjść, musi pracować, musi współpracować z ludźmi. On jest ekstrawertykiem - jak wy to nazywacie. Czasami również kobieta musi pracować, gdy występują trudności i kłopoty. Jeżeli mężczyzna powie: "W porządku, nie będziesz pracować", to kobieta nie powinna czuć się zdominowana.

Jeśli on to powie tylko z miłości.

Zatem, jeżeli mózg zaczyna za bardzo dominować serce, to co się wydarzy? Wtedy będzie oschłość. Tak jak wielu mężczyzn jest bardzo pedantycznych, bardzo dokładnych. Przyprawiają o ból głowy, sprawiają ból głowy sobie, innym i całemu społeczeństwu. Tacy ludzie potrafią stać się niezwykle oschłymi i mogą być tacy cały czas. Oni nigdy nie będą mogli cieszyć się swoimi żonami, dziećmi, absolutnie niczym, ponieważ są bardzo drobiazgowi. Na przykład mogą powiedzieć: "Przyjdź o 5:10". Gdy przyjdziesz o 5:09 lub 5:11, to ci się dostanie. Oni kontrolują czas, tylko po to by wytknąć błędy, jak tylko żona przyjdzie, będą krzyczeć: "Co? Bardzo się spóźniłaś!" Jak bardzo? 45 sekund! Stracona! Zobaczcie, żona nadchodzi, oczekiwanie na spotkanie, radość z niego. Wkrótce spotkasz się ze swoim własnym sercem. Tego brakuje. Ten mózg może przekroczyć wszelkie granice. On może być bardzo męczący. On stwarza ogromne problemy wewnątrz.

Zatem, w tym rzecz, że serce musi być szanowane, trzeba słuchać serca. Serca trzeba słuchać.

Ale to nie oznacza, że kobiety powinny dominować mężczyzn. To tego nie oznacza. Podporządkowanie oznacza, że musicie rozumieć, co wasza miłość mówi. Zróbcie to z miłości. Jeżeli zrobicie to z miłości to bardzo dobrze. Na przykład, daję wam wykłady od rana do wieczora. Nie jesteście zmęczeni moimi wykładami. Zwykle ludzie powiedzieliby: "Co to za kazanie? Ta pani wciąż nam coś mówi". Ale z jednego powodu wam to nie przeszkadza. Jakiego? Ponieważ wy wiecie, że Ja bardzo was kocham. W ten sam sposób, kobieta musi ustanowić swoją rolę, że ona kocha. Mężczyzna może stać się trochę dziwny, ale on się zmieni. Może trochę zejść na manowce, ale on się poprawi. Lecz nie osądzaj go w zewnętrznych dominacjach. Na przykład, jeżeli on powie: "Ten kolor nie jest dobry", "Dobrze, założę cokolwiek ci się podoba". Wtedy on powie: "Och, myślę, że ten który miałaś był w porządku.

Wiesz, byłem naprawdę głupi". On tak powie. Po prostu się zgadzajcie. Eksperymentowałam

z tym w swoim własnym życiu. Zrobiłam to. Na przykład, mój mąż nie wie za dużo o drogach i przypuśćmy, że gdzieś się wybieramy i on powiedział: "Myślę, że powinniśmy pójść tą drogą". Powiedziałam: "W porządku, prowadź, a ja pójdę z tobą". Powiedziałam też: "Nie, myślę, że to nie jest dobra droga i na pewno będę musiała zawrócić. Ale nie szkodzi, jeżeli chcesz mogę z tobą pójść". W porządku, idę.

Po prostu cieszę się. Być może właśnie tą drogą mam iść. Wtedy on zaczyna się zastanawiać: "Czy to prawda? Czy ma rację?" Wtedy on zaczyna myśleć: "Czy faktycznie tak jest?" lub "Być może?" Ponieważ ona ma instynkt. Ona ma intuicję. Ona ma tak wiele rzeczy. Ona ma to przeczucie.

One mają przeczucie. One kierują się przeczuciem. Tak właśnie jest. Kiedy oni zrozumieją, że przeczucia żony są trafne, wtedy w pewnym sensie będą za nią podążać. Ale, co w tym wspaniałego, że zmusisz swojego męża, aby za tobą podążał? To nie jest właściwe. Uważam, że nie ma potrzeby, aby on podążał. "Masz iść tędy!" Po co to wszystko robić?

Idziemy tą samą drogą. Ale musimy wiedzieć, że jedno jest po lewej a drugie jest po prawej. Lewa musi być po lewej. Załóżmy, że lewe koło zaczyna poruszać się w prawo - zostaniemy wtedy tylko z jednym kołem. Co z tym zamierzamy zrobić? My wszyscy zmierzamy w jednym kierunku. Nie ma dwóch dróg. Potrzebne są dwa koła, aby była równowaga. Ale my idziemy tą samą drogą. Tego ludzie sobie nie uświadamiają, myślą, że jedno powinno kierować się w prawą stronę a drugie w lewą. Wyobraźcie sobie, w jakim stanie byłaby taka rodzina?

Idziemy tą samą drogą. Potrzebne jest tylko zrozumienie. Jedno ma żyć z mocami serca, zaś drugie ma żyć z mocami rozsądku, zrozumienia. Jeśli chodzi o rozsądek to on ostatecznie skieruje się do serca, ponieważ osiągnie punkt, w którym on nie wie. Wtedy skieruje się do serca, jak tylko kobiety uświadomią sobie, że mają to wewnątrz siebie. Ale musicie pielęgnować swoją moc serca.

Zamiast tego rywalizujecie z nimi we wszystkim: "Jeśli on idzie pojeździć konno, dlaczego ja nie mogę?" "On to robi, dlaczego nie ja?" "On prowadzi samochód, ja też mogę". Mądrość polega na wykonywaniu rzeczy, wielu rzeczy poprzez ich unikanie. Na przykład, nie prowadzę samochodu, więc każdy mnie wozi. Nie piszę na maszynie, więc wszyscy piszą za Mnie. Ale robię rzeczy, których nikt nie potrafi zrobić tak dobrze jak Ja. Na przykład potrafię świetnie gotować. Więc, gdy trzeba coś ugotować, to oni przychodzą do Mnie. Tak to działa. Ale nie róbcie wszystkiego, co mężczyźni chcą robić. Lub nie róbcie wszystkiego, co kobiety chcą robić. Dla mężczyzn byłoby błędem gotowanie a dla kobiet prowadzenie samochodu. Mężczyźni powinni znać się na wszystkich męskich rzeczach a kobiety na kobiecych. Muszą się nauczyć.

Muszą wkładać w to serce. Kobiety mogą być równie inteligentne, mężczyźni mogą być równie inteligentni. Kobiety mogą pójść na prawo a mężczyźni mogą pójść na lewo. Co do tego nie ma wątpliwości. Ale rzecz w tym, że w ten sposób zakłócacie równowagę w całym wszechświecie. To nie jest tak, że poprzez robienie tego jesteście gorsi lub lepsi. Ta idea powinna całkowicie zniknąć z waszych umysłów. Mężczyźni myślą: "Och, jestem mężczyzną, który nosi spodnie!" W porządku, nosicie spodnie, ale my nosimy piękne spódnice. To jest sposób, w jaki powinno się to widzieć.

Gdy tylko to odejdzie, to Sahaja Yoga będzie lepiej działać. Dominacja jest tylko wtedy odczuwana, gdy nie ma miłości. Czasami lubicie, gdy ludzie was dominują, nieprawdaż? Na przykład powiemy: "Podejdź, jedz. Musisz jeść, musisz to zjeść". To się wam podoba, ponieważ ktoś się wami opiekuje, jest troska, ktoś was kocha, chce, abyście to mieli i chce, abyście to zrobili. Lubicie taką osobę. Chcecie, aby ktoś tak zrobił. Nie chcecie być pozostawieni sami sobie: "Rób co chcesz!" To nie jest dobre.

Gdy tylko rozwiniesz to odczucie w sobie: "Och, ta osoba opiekuje się mną. Ta osoba mnie kocha". Wtedy i ty zaczniesz dbać o uczucia tej osoby. Również zaczniesz rozumieć. Znów poczucie winy zaczyna działać. Proszę przestańcie mieć poczucie winy o cokolwiek! Nie mówię tych rzeczy, abyście poczuli się winni, lecz tylko po to, abyście zrozumieli, że musicie być w bardzo dobrym nastroju, w bardzo dobrym nastroju. Ta równowaga została stworzona dawno temu, bardzo dawno temu. Wtedy gdy byli Radha i Krishna: Radha była mocą a Krishna był tym, który ją wyrażał. Jak wy to mówicie, [siły] potencjalna i kinetyczna.

Ludzie wiedzieli tylko o Krishnie, ale to Radha była mocą. Kiedy miał zabić Kamsę, musiał poprosić Radhę, aby to zrobiła. To ona była tą, która wszystkiego dokonała, musiała tańczyć i on przycisnął jej stopy. Powiedział: "Musisz być zmęczona". Dlaczego musiała tańczyć? Ponieważ, bez niej rzeczy by się nie wypracowały. Zatem to jest takie współzależne. To jest takie współzależne. Tak jak nie możecie mieć knota i nie możecie mieć światła. Nie możecie mieć tych rzeczy osobno.

Jeżeli to zrozumiecie, to wtedy ta równowaga będzie całkowicie harmonijna. Tak jak pomiędzy Bogiem i Jego mocą: absolutna jedność. Nie wyobrażacie sobie, jak Bóg i Jego moc są jednym. Jego moc, Jego pragnienie jest tym samym co Bóg. Nie ma żadnej różnicy. Ale jako istoty ludzkie jesteście zdezintegrowani. Wasze pragnienie jest inne, wasze myślenie jest inne, wasze prośby są inne. Wszystko jest rozdzielone, to dlatego nie potraficie zrozumieć. To dlatego również małżeństwa są zdezintegrowane. Pełne scalenie jest wymieszaniem.

Jeżeli żona musi pracować, to nie ma się o co martwić. Jeżeli mężczyzna ma pracować, to nie ma o co się niepokoić tak długo, jak jest całkowite zrozumienie integracji, równowagi wewnątrz was. Oczywiście, kobiety są odpowiedzialne za grację w rodzinie. Ona musi być elegancka. To nie wygląda ładnie gdy kobieta zachowuje się jak mężczyzna, ponieważ mężczyzna nie musi być aż taki dostojny jak kobieta. Ostatecznie on jest mężczyzną. Więc to jest w porządku. Mam na myśli, to, że jego zachowanie nie musi być okropne, ale czasami jeżeli on przeklnie, to nie ma znaczenia dla mężczyzny, czasami, w pewnym sensie. Ale dla kobiety, to ma znaczenie, ona jest gracją. Ale są rzeczy, których mężczyzna nie może robić, jak np. interesować się kobietami.

Niektórzy mężczyźni są tak obrzydliwe rozgrzani, że w ogóle, nie można zrozumieć sposobu w jaki interesują się kobietami. Jaki ubiór noszą kobiety, tego typu rzeczy. To wszystko jest jak zachowanie szczura, obrzydliwe. To nie może być męskie. To oznacza, że są niewolnikami kobiet. Mogą siebie nazywać tym czy tamtym. Słyszałam, że ubrania, bielizna pani Kennedy była na sprzedaż. I ludzie z Australii lecieli, aby ją kupić. Tylko pomyślcie o tych mężczyznach. Jak byście ich nazwali? Nie wiem jak ich nazywacie po Angielsku. Ale oni są po prostu gorsi od robaków. Nie wiem skąd oni się biorą.

Zatem mężczyzna ma być mężczyzną! Mężczyzna jest taką osobą jaką jest Rama. Słyszeliście o jego życiu, jaki był. Jak bardzo kochał swoją żonę, szanował swoją czystość. Mężczyzna, który nie może uszanować swojej czystości nie jest mężczyzną. Jest zupełnym robakiem. Tak właśnie jest.

Mężczyzna musi mieć charakter, musi mieć tą rycerskość w sobie, musi mieć tą odwagę w sobie, musi mieć tą opiekuńczość. Jeżeli złodziej przyjdzie do domu a mężczyzna powie do żony: "Och idź i otwórz drzwi a ja się schowam". A kiedy złodziej odejdzie to mężczyzna powie: "Ja będę dominował!" - to nie tędy droga. Mężczyzna musi ochraniać. Mężczyzna musi się opiekować. To dlatego nie ma to znaczenia, jeżeli czasami jest trochę nieokrzesany. To nie ma znaczenia. Ponieważ on musi stawiać czoła. On jest jak kolec a kobiety są jak kwiaty.

Więc, jeżeli chodzi o kolec i kwiat, chcecie być kwiatem, nieprawdaż? Ale jeżeli chodzi o kobietę i mężczyznę, to wy chcecie być kolcem. Więc to jest złe. On musi ochraniać, on musi strzec życia rodzinnego przed atakami i innymi rzeczami. Lecz jest wprost przeciwnie, to oni są tymi, którzy dopuszczają przenikanie złych ludzi do rodziny. To są mężczyźni. Poprzez swoją dominację sprowadzają potworne kobiety, sprowadzają potwornych ludzi. "Och, ona jest moim przyjacielem. Jak możesz być przeciwna?" Ale jakim ona jest typem przyjaciela?

On musi powiedzieć: "Nie, ja nie chcę, aby ci ludzie przychodzili do domu, oni nie są w porządku. Oni muszą wyjść". To on ma to powiedzieć. A kobieta ma to zrozumieć. Ale jeżeli on to powie tylko z dominacji, to jest głupie.

Zatem jak wyraźnie widzicie, wszystko ma dwie strony. Jeżeli jest to zrobione z miłości, wtedy jest perfekcyjne. Ale jeżeli jest to zrobione aby zdominować, wtedy to jest głupie. Po co dominować? Nie rozumiem słowa "dominacja".

Czy dwa koła dominują się nawzajem? Czy mogą? Jeżeli jedno dominuje, powiedzmy jedno staje się większe, to będą się kręcić w kółko, nieprawdaż? Bez wątpienia, nie ma tutaj dominacji. Ale jest to kwestia integracji, zrozumienia i pełnego współdziałania wewnątrz siebie, co musi przeniknąć do społeczeństwa, do rodziny. Małżeństwa, które nie są pomocne społeczeństwu są bezużyteczne, są po prostu bezwartościowe.

Mamy wiele tego typu małżeństw. Ludzie się pobierają, żyją razem w dobrobycie, w szczęściu i umierają. To małżeństwa mają zmienić społeczeństwo, poprzez ich radość, szczęście, stworzenie domu, w którym wszyscy są oczekiwani, w którym troszczą się i robią coś dla innych. Wiele ludzi myśli, że nikt dla nich nic nie robi, ale co wy zrobiliście dla innych? Co takiego zrobiliście? Czy cokolwiek dla nich zrobiliście? Jak tylko o tym zadecydujecie i zaczniecie to rozumieć, wtedy będzie bardzo dobrze. Kobieta, jeżeli nie została należycie wychowana, może być bardzo, bardzo zarozumiała i może być bardzo samolubna i egocentryczna. Mężczyzna również taki może być, kobieta też. Jeżeli one nie zostały należycie wychowane, to mogą nie lubić wydawania pieniędzy na innych. Mogą nie lubić, gdy inni przychodzą do domu i dzielenia się tym i tamtym. Ale ponownie powinniśmy osądzić, czy jest to zrobione z miłości czy też nie.

Na przykład mąż przyprowadza swoich przyjaciół i one mogą nie chcieć, aby przyjaciele przychodzili, ponieważ to oznacza wydatki. One chciałyby mieć dla siebie więcej biżuterii, niż mieć przyjaciół. To możliwe, one mogą być takie. Niektórzy mężczyźni też tacy są. Obie rzeczy są złe. To musi być wspólne, aby to zrozumieć. Wszystko na tym polega, że musicie być hojni

w swojej miłości dla innych. Nie trzeba na to wydawać pieniędzy. Nie trzeba. Możecie być po prostu życzliwi dla nich, dobrzy dla nich z niewielką ilością pieniędzy. Nie ma w tym nic złego, jeżeli wydacie trochę pieniędzy na innych okazując im swoją miłość.

W naszej Sahaja Yodze wciąż jesteśmy bardzo skrupulatni jeżeli chodzi o pieniądze, jeżeli chodzi o miłość. Jesteśmy bardzo, bardzo ostrożni. Mamy tak wiele strachu wewnątrz nas.

Dominacja nigdy, w żadnym wypadku, nie powinna przyjść do Sahaja Yogi. Na przykład, kiedy wam coś mówię, osoba postronna może pomyśleć, że was dominuję, ponieważ dotykam bardzo bolesnych punktów w was, jeżeli to zobaczycie, to tam jest. Kładąc zbytnio na lewą stronę: wszyscy czujecie się winni, to nie jest dobre, podejdźcie. To także jest ucieczka, że zaczynacie mieć poczucie winy i wtedy właśnie nie leczycie siebie. Po prostu o nic nie czujcie się winni. Mówię wam to, ponieważ muszę wam to powiedzieć. Ktoś może poczuć, że jest to dominacja, jeżeli za tym nie dostrzeże miłości, piękna i współczucia.

Zatem, najlepszym sposobem jest nie czuć się przez nikogo zdominowanym.

Jak można was zdominować? Jesteście Duchem. Wasze ego można urazić. Jesteście Duchem, jego nie można zdominować. Ale czy jesteście Duchem? Czy czujecie swojego Ducha? Jeżeli czujecie swojego Ducha, to nigdy nie możecie zostać zdominowani, nikt nie może was zdominować. Ale jeżeli czujecie przez cały czas, że jesteście zdominowani, to staniecie się bardzo, bardzo nerwową osobą. Możecie być okropną osobą. Nie potraficie rozmawiać z ludźmi.

Zatem to jest czas, abyście uświadomili sobie, że jesteście Duchem i wasz mąż jest również Duchem. Lub jeżeli jesteś mężem to musisz wiedzieć, że żona także jest Duchem. I wzajemny szacunek musi rozwijać się na tym poziomie, ponieważ oboje jesteście świętymi, jesteście Sahaja yoginami. Musicie się nawzajem szanować, ponieważ jesteście Sahaja yoginami. Wszyscy was szanują, ponieważ jesteście Sahaja yoginami - ci, którzy nie osiągnęli Samorealizacji: "Och, oni są Zrealizowanymi Duszami". Po prostu pomyślcie, gdy nie byliście zrealizowani, gdyby ktoś wam powiedział: "On jest Zrealizowaną Duszą". Co byście poczuli do tej osoby? Nie jesteście tego świadomi, ale powinniście być świadomi. Nie powinniście stać się zarozumiali poprzez to, lecz musicie szanować innych, oni są Zrealizowanymi Duszami, oni są dziećmi waszej Matki. Rozmawiając ze sobą musicie zrozumieć, że jesteście mężem i żoną.

Całe pojmowanie o mężu i żonie jakie dotychczas mieliście musicie odrzucić. Myślę, że małżeństwo jest jak kontrakt. W małżeństwie jest: "Jak bardzo on dominuje? Jaką on ma kontrolę? Jaką ja mam siłę? Ile zarabiam? Ile on zarabia, gdzie są trzymane pieniądze? Po co to wszystko?" To się wydarzy tylko wtedy, gdy nie będziecie sobie ufać. Zatem, ufajcie sobie coraz bardziej .

Powinno być rywalizowanie w miłości. Powinna być rywalizacja w zaufaniu, w byciu szczerym, w byciu życzliwym, w byciu pomocnym. Niech będzie tego typu współzawodnictwo i wtedy osiągniecie wyniki. Współzawodnictwo powinno być po drugiej stronie, zamiast dominacji, zamiast być przestraszonym, zamiast dzielić głupie zachowania.

Muszę wskazać jeszcze jeden punkt, który przydarza się parom małżeńskim, i który jest bardzo, bardzo zły, taki, że oboje przyjmują rolę bardzo nieszczęśliwych ludzi, Les Miserables. Siadają, płaczą, szlochają: "Och ho ho" beż żadnego powodu. Tak, jakby cały świat się im zawalił. Są tak zwani wspaniali poeci, jak lord Byron lub inni potworni ludzie, którzy napisali straszne wiersze tego typu. I oni będą recytować te wiersze: "Najsłodsze piosenki są te, które są najsmutniejsze" i innego typu bzdury: to nie jest dla Sahaja yoginów. Macie nie robić tego typu bzdur i siedzieć, i ulegać tego typu niedorzecznościom, i radować się wspólną niedolą.

Teraz nie macie żadnych cierpień. Cokolwiek się wydarzyło, to przeszłość, to koniec. Teraz jesteście nowymi ludźmi, z nową świadomością, z nowymi rzeczami. Nie macie cierpień. Zatem zapomnijcie o tych wszystkich rzeczach i starajcie się radować sobą nawzajem. Gdy zaczniecie to robić, siedzieć i radować się niedolą, musicie uciec z tego natychmiast i powiedzieć: "Och wpadamy w tą samą grę lorda Byrona". Nie chcę już tworzyć lordów Byronów z Sahaja yoginów. Zatem, proszę pamiętajcie, nie siadajcie, nie rozmawiajcie i nie analizujcie swoich nieszczęść. Nie macie żadnych nieszczęść. Jesteście Duchem.

Jesteście źródłem radości dla siebie i dla innych i nie macie żadnego interesu w tym, aby usiąść, płakać i szlochać i nie wiedzieć co się dzieje. Nie wiem dlaczego, nie znacie swojego Ducha. Czy nie znacie swojego Ducha? Znacie! Zatem dlaczego nie znacie? Macie swoją świadomość wibracyjną, więc dlaczego wciąż mówicie, że nie znacie? Musicie wszystko wiedzieć. I musi to być bardzo pozytywne działanie, aby być szczęśliwym, pachnącym radością i dającym radość innym. To musi być z wami. Inaczej to wszystko nie ma znaczenia.

Staram się najbardziej jak mogę, aby każde małżeństwo było uroczyste i przepiękne a finalnie odkrywam dwoje siedzących i dąsających się ludzi. I wyobraźcie sobie dzieci, które mają się narodzić. One pomyślą: "Co to za obrażeni rodzice, o Boże, uchroń nas od tych płaczących dzieciaków". Nie zaprzepaśćcie wszystkich moich nadziei poprzez takie podejście. Jeżeli macie jakieś pytania to pytajcie, ponieważ nie wiem, czy mówić dalej. Wyłącz. [mikrofon]