Jezni ste na življenjeKot majhni otrociČigar mati je izgubljena v temi

S tiho jezo izražate obupNa brezplodnem koncu vaše poti

Nosite grdoto, da bi odkrili lepoto

Vse poimenujete napačno v imenu resniceIzčrpate čustva, da bi napolnili skodelico ljubezni

Moji sladki otroci, moji dragiKako lahko dobite mir z bojevanjemS samim seboj, s svojim bitjem, z radostjo samo?

Dovolj so vaši napori odpovediumetna maska tolažbe

Sedaj počivajte v cvetnih listih lotosovega cveta v naročju svoje milostljive MatereOkrasila bom tvoje življenje s čudovitimi cvetoviIn napolnila tvoje trenutke z radostnim vonjemNamazala bom tvojo glavo z božansko ljubeznijo

Ker ne morem več prenašati vašega mučenja

Naj vas potopim v ocean radostiDa izgubiš svoje bitje v Večjemki se smehlja v cvetni čaši SebeSkrivno skrit, da te ves čas draži

Zavedajte se in ga boste našlivibrirajoč vsako vaše vlakno z blaženo radostjopokrivajoč celotno vesolje s svetlobo.

Mati Nirmala
