2º programa público en Madrid. España. 6 de noviembre de 1987.

Saludo a todos los buscadores de la Verdad. Como os dije ayer, este es el conocimiento de las raíces; tenemos el conocimiento del árbol, pero si el árbol crece y crece sin prestar atención a sus raíces, entonces siempre llegará un momento definitivo en el que se destruirá. Así, la destrucción no viene desde fuera, sino desde dentro de nosotros mismos, a través de enfermedades y cosas malas en nuestra vida. Es importante que os convirtáis en el Espíritu para que entendáis los misterios de la vida, incluso en la medicina o en  cualquie otra ciencia hay muchas cosas que ellos no pueden explicar, cualquier teoría que se propone nunca es absoluta, siempre es desafiada. Por tanto hay algo que falta en la conciencia de los seres humanos, que hace que no estemos en lo absoluto.

Este hermoso sistema sutil que tenemos aquí representado , fue creado en nosotros a lo largo del proceso de evolución. Pero cuando vamos hacia el lado izquierdo o hacia el derecho, a los extremos, nuestros centros se quiebran y perdemos la conexión con el Todo; como resultado de esto, desarrollamos trastornos que pueden ser psicosomáticos, físicos o emocionales. Cuando la Kundalini, que es la fuerza vital, se eleva y pasa por estos centros quebrados los vuelve a unir y trae la atención al centro.

Cuando nuestra atención se va al lado izquierdo o al derecho tenemos experiencias raras. Si nos vamos al lado derecho podemos sentir que nuestro cuerpo está en algún otro lugar y que estamos volando, estas se llaman experiencias del supraconsciente; la gente comienza a ver el futuro, a vivir en el futuro, pero no saben cómo sucede, no tienen control sobre ello, no tienen un conocimiento científico de ello, es como si fueran arrastrados por una fuerza incontrolable. Si os vais demasiado al lado izquierdo, desarrolláis enfermedades horribles que son psicosomáticas, también sois poseídos por ideas muy extrañas y comenzáis a saltar, a gesticular, a cantar, de una manera muy miserable. Los problemas residen, dentro de nosotros, en los extremos de nuestro Ser.

Les voy a decir cómo aparece el cáncer; si una persona está en el centro, de ninguna manera puede desarrollar un cáncer. Suponed que esta persona se va demasiado al lado derecho: excesivo planear, muy futurista, entonces sus chakras se mueven hacia el extremo derecho y así se vuelve vulnerable ante el cáncer porque pierde su conexión con la fuente; ahora suponed que en un momento dado se va al lado izquierdo: porque tenga un accidente, conozca a un falso guru..., y él se va al lado izquierdo o es hipnotizado, entonces se dispara el cáncer. Los doctores dicen que el cáncer es causado por la proteína 52, la 54 y la 58, solo son nombres dados por ellos, pero dicen que estas proteínas vienen a nosotros de un área que existe en nosotros desde nuestra creación; eso significa que hay un área -que en Sahaja Yoga denominamos el subconsciente colectivo- donde se almacena todo lo que está muerto, desde el comienzo de la creación. Y cuando algo de esa zona viene a nuestra atención comenzamos a desarrollar el cáncer. Porque se ha perdido la conexión con el Todo, y la células comienzan a ir a su aire, comienzan a actuar por sí mismas y se vuelven malignas. Si tenéis la oportunidad de volver a unir estos chakras y de traerlos al centro, entonces se puede curar el cáncer. Sahaja Yoga ha curado muchos tipos de cáncer, incluso la leucemia; es vuestro propio poder, no es el poder de nadie más, es vuestro propio poder el que funciona. Y esto ha sido probado por doctores, como os contaba ayer que dos doctores han hecho su tesis sobre Sahaja Yoga en la Universidad de Nueva Delhi.

También podemos hablar de los trastornos causados por la sobreactividad de la mente. Aquí, en el esquema, podéis ver dibujado un círculo al que llamamos el Vacío, ahí residen las diez valencias de los seres humanos, y si estas diez valencias se iluminan, nunca podréis ir a los extremos. Pero cuando sois sobreactivos y excesivamente futuristas, entonces el segundo chakra, el Swadisthan, tiene que trabajar muy duro, este centro cuida de nuestras vísceras y tiene una función muy importante: la transformación de materia grasa que hay en nuestro estómago en células grises para el consumo de nuestro cerebro. Pero si pensáis mucho, mucho, necesitáis un continuo suministro, y es el Swadistana chakra el que realiza este suministro. Este chakra también tiene que cuidar del hígado, del bazo, del páncreas, de los intestinos, tiene que cuidar de los riñones y del intestino grueso. Si está ocupado transformando la grasa en células grises, entonces no tiene tiempo para otras funciones. Como resultado de esto tenéis un hígado muy malo, vuestra atención se distorsiona, y todo el tiempo os sentís incómodos, no os apetece comer, y si coméis sentís ganas de vomitar, esto puede ir más allá y tener cirrosis en el hígado y problemas de piel. Especialmente si tenéis un mal hígado y os ponéis a tomar al sol, seguro que desarrollaréis cáncer de piel. Si coméis muchas grasas y tomáis mucho aceite también tendréis un problema de hígado, os volvéis personas muy delgadas, porque el hígado no puede consumir ninguna grasa de vuestro cuerpo. Luego está el páncreas, que es el responsable de absorber vuestra azúcar; cuando este órgano sufre trastornos, como resultado desarrolláis diabetes. En los pueblos de la India, la gente toma tanta azúcar que cuando ponen una cuchara en la taza, el azúcar sostiene la cuchara; pero no desarrollan diabetes porque no se sientan a pensar demasiado, viven la vida tal como llega, y están por encima de los pensamientos.

La tercera cosa que les ocurre es incluso más seria: el bazo, que es responsable de las emergencias, produce más glóbulos rojos. Suponed que habéis terminado de comer y seguidamente después comenzáis a correr, entonces sentís un dolor en ese área, y ese área se vuelve muy sensible. Pero en los tiempos modernos estamos dando sobresaltos al bazo a cada momento porque nuestra vida es muy movida; por la mañana temprano leemos los periódicos, noticias horribles, después nos tomamos el desayuno con prisas, cogemos el coche y nos encontramos con un atasco, aquí viene el segundo choque, y así continuamos dando sobresaltos a nuestro organismo todo el tiempo.

Cualquiera que sea la arrogancia de los seres humanos, sea lo que sea lo que piensen de ellos mismos, deben saber que han sido hechos delicada y cuidadosamente, no deberían tratarse a sí mismos como hipopótamos, son seres humanos, y si se tratan mal terminarán desarrollando enfermedades horribles como la leucemia. Con el riñón desarrolláis hipertensión arterial, entonces el riñón no funciona y tienen que extirpar los riñones. Tenéis estreñimiento, todo esto viene a vosotros a causa de la sobreactividad de la mente. De hecho no hay necesidad de planear demasiado, porque cuando planeáis mucho las cosas no funcionan. Debéis mantener la mente abierta para ver cómo funciona. Antes estaba en otro sitio y tuve que ir otro lugar muy alejado; si hubiera vuelto al primer lugar, tal y como estaba planeado, nunca hubiera llegado aquí; así que, decidí venir directamente y ha funcionado, sin disturbar mi organismo.

Tenemos relojes y todo el tiempo estamos mirando la hora y asustándonos de ella, tenemos que ahorrar tiempo, pero para qué. Una persona en la India estaba muy ansiosa por coger un avión, y no conseguía el billete así que estaba muy agitado. Le pregunté: "¿A qué es debida la urgencia?". Él respondió: "He de asistir a una fiesta". Una pérdida de tiempo. Y por esta causa estaba dañando tanto su organismo. Y cualquier día oís decir que una de estas persona ha muerto de un ataque al corazón. Si os volvéis demasiado del lado derecho, el Espíritu para, muere, el Espíritu no muere, digamos que se diluye o desaparece, el corazón se vuelve como una piedra, con vuestra arrogancia es incluso peor. Y así desaparece el reflejo de Dios. Estas personas no tienen ninguna compasión ni amor ni gozo, son destructoras del gozo. Corren de un lugar a otro para obtener gozo, pero son personas sin gozo.

Después están las personas del lado izquierdo, que indulgen en romances sin sentido e indulgen en todo tipo de sufrimientos sin causa. Como la primera vez que fui a París, me dijeron: "Madre, pareces una persona tan feliz que no les vas a gustar, piensan que la gente feliz es ignorante, que no saben lo que pasa en este mundo". Así que, comencé mi conferencia con "Los miserables". Si en París tenéis un bar cada cinco farolas, y una mujer mala cada tres farolas, entonces estáis invitando a los problemas. Veis a un hombre salir de un bar y caer en la calle, y entráis en el mismo bar. Veis a gente que se mete en problemas por hábitos sexuales raros, y todavía vosotros mismos también queréis hacerlo. No sois personas libres en absoluto ni tampoco poderosas, sois tentados continuamente por las fuerzas de vuestra destrucción; y así tampoco tenéis discriminación ni entendéis vuestra gloria, ni la belleza que Dios os ha otorgado creandoos especialmente para que entréis en su Reino. Vivimos en nuestro propio paraíso de destrucción, destruyéndonos a nosotros gradualmente, nada nos da felicidad. Corremos de un lugar a otro buscando felicidad y gozo. Últimamente creo que la gente tiene que ponerse electrodos en el área límbica para sentir gozo, como los monos. No nos respetamos a nosotros mismos ni tampoco tratamos de entendernos. ¿Para qué hemos sido creados? ¿Cuál es el propósito de nuestra vida? ¿Qué tenemos que obtener de la vida?

Hay un océano de gozo tan enorme delante de vosotros y no queremos entrar. Este tipo de cosas están ocurriendo, y es por eso que ayer os dije que la gente de España tiene ahora que crecer, y conseguir el gozo de sus vidas; un pequeño viaje de algunos centímetros de la Kundalini os trae este gozo. He de haceros un petición, que debido a que no hay mucho tiempo hoy no responderé a preguntas, ayer pasamos una hora y media con preguntas inútiles. Es mejor que tengáis vuestra Realización, no necesitáis saber todas estas cosas, de la misma forma que no necesitáis conocer el funcionamiento de la electricidad, vosotros simplemente dais al interruptor.

Que Dios os bendiga.