1.veřejný program: Dosáhli jste úplné skutečnosti? 06/11/1991, Madras, Indie

Klaním se všem hledačům pravdy.

Jsme-li opravdovými hledači pravdy, musíme být poctiví a upřímní tak, že jsme upřímní sami k sobě a zdůvodnili jsme svoji vlastní existenci na tomto světě. Existuje mnoho sádhaků, kteří od rána do večera dělají nějaké rituály, nějaké meditace, nějaké bhakti, něco čtou. Člověk ale musí pochopit - čeho jsme dosáhli? Kde se nacházíme? Jako Matka bych řekla: "Mé dítě, tolik jsi toho udělal ve svém hledání, ale co jsi našel? Dosáhl jsi úplné skutečnosti? Získal jsi to, co je popsáno v Písmech?" Ta píseň, kterou dnes zpívali, je v maráthi - přála bych si, aby zpívali něco v sanskrtu, jsou v sanskrtu velmi dobří, zpívají také o Ádi Šankaračárjovi a podobně. Budou zpívat zítra. Tu píseň napsal Námadéva ve dvanáctém století; byl to básník, který šel později do Pandžábu, kde si ho velmi vážil Nának Sáhib a požádal ho, aby psal v jazyce pandžábí.

Studoval jazyk pandžábí a napsal velmi tlustou knihu, a v "Granth Sáhib" je tam z ní mnoho veršů. Byl obyčejným krejčím, velmi obyčejným krejčím, a šel se setkat s jiným světcem do další vesnice, který se jmenoval Gora Kumbhar. "Kumbar" znamená člověk, který je hrnčířem, který vyrábí hrnce, a Gora Kumbhar byl zaneprázdněný přípravou hlíny. Námadéva se jen před něj postavil a řekl: "Přišel jsem sem, abych uviděl nirgun, beztvaré, abych spatřil čaitanju, ale tady je v ságun, ve formě." Pouze realizovaná duše, pouze svatý toto může říct o svatém, protože zná úplnou skutečnost. Ale lidé, kteří nejsou realizovaní, nechápou, co je za tímto životem. Dokonce v křesťanství máme Tomáše, který přišel do Indie a napsal mnoho pojednání, která se zachovala v jeskyni v Egyptě a byla objevena. Existuje o něm kniha - po čtyřiceti osmi letech výzkumů. Je úžasné, jak dopodrobna popisuje Sahadža jógu, že musíte zažít skutečnost. Samozřejmě, každá kniha, každé Písmo říká: "Poznej sám sebe" - kdo jsem, musím zjistit, kdo jsem.

Když je to takto řečeno, naše úsilí by mělo směřovat k tomu, abychom nalezli ono "já", které je uvnitř nás. Říkáme: "Mé tělo, můj hlas, můj nos, moje země, moje, moje" - kdo je ono "já", kterému všechny tyto věci patří? Odkud tato inspirace přichází? Toto "já" je uvnitř nás, odraženo v našem srdci. Musím vás požádat, abyste se mnou nesouhlasili slepě. Zaslepenost ničemu nepomůže. Ale nabízím vám hypotézu jako ve vědě o tom, jak se to děje a podobně. Bude-li dokázána a zjistíte-li, že jste zažili to, o čem hovořím, pak to jako upřímní lidé musíte přijmout. Na západě máme jiné problémy než tady, obrovské problémy. Nejdřív jsem jela do Anglie a znáte Angličany, jsou tvrdý oříšek - je obtížné jejich skořápku prolomit.

Ale jakmile se prolomí, jsou plní vědecké práce a spěchají na univerzity a do různých knihoven zjistit všechno o Kundaliní. Tolik toho již bylo napsáno Náthem Panthisem, který tu byl, který tolik pracoval na probouzení Kundaliní, ale ztratilo se to. A když sem přišli Němci a další lidé, tantrikové jim řekli nějaké špatné věci, které si odtud odnesli. A takové nedorozumění a takové chybné informace do takové míry, že jsem četla v jedné německé knížce, že Kundaliní leží ve vašem břiše a všechno to tam vysvětlil. Byl to bezpochyby velice vzdělaný člověk, ale nevím jestli to, co se naučil, je důležité, a takto popisoval Kundaliní. Toto vědění nám bylo známo už dávno. Měli jsme tři typy činností směřujících k Božskému. Jedním byly Védy. Dokonce "vida" znamená "vědět" - tak Tomáš nazýval lidi, kteří věděli - "gnostikové", jako "gn". Nevím, co se říká na jihu - jestli "gňána" nebo "gjána", ale v maráthi říkáme "gn".

Slovo gnostik má stejný význam jako člověk, který má poznání, ale ne vnější poznání, ne díky vašemu rozumovému úsilí nebo emocionálnímu vnímání, ale díky něčemu naprosto jinému. A zkoušeli to stejným způsobem, ale ve védách se říká, v prvním, v prvním verši se říká, že když to neznáte, nemá smysl tuto knihu číst. Ale co znamená "vědění"? Vědět to ve vašem centrálním nervovém systému, ne na duševní nebo fyzické úrovni, ale na mnohem vyšší. Když jsme se stali lidskými bytostmi, musíme pokorně říct, že nejsme dokonalí. Něco nám chybí; protože proč jinak bojujeme, proč se hádáme? Chci říct, všechny tyto problémy jsou převážně lidskými problémy: ekologický problém, ekonomický problém, politický problém. Přicházíte k příčině, že je to lidská bytost, která způsobuje všechny tyto věci. Takže co je v nepořádku s lidskými bytostmi? Zvířata jsou v pořádku, jsou "pašu"; jsou pod "paša", pod kontrolou Boha.

Ale lidské bytosti dostaly svobodu, jsou zmatení a všechny tyto problémy existují proto, že nemají opravdové vědění. Takže co je to skutečné vědění, které musíme hledat a ke kterému musíme směřovat? Takže tito lidé ve védách zkoušeli porozumět, ale víc se snažili porozumět přírodě a pěti elementům. Během uctívání pěti elementů se podle nás posunuli na pravou stranu a pravostranný pohyb je velmi dobře ukázán v řecké mytologii; a potom z Řecka se to obrátilo do vědy a začaly všechny tyto věci. Levá strana byla bhakti. Lidé začali uctívat Boha se slepou vírou a přicházet k Bohu, uctívat Ho v chrámech a kostelech, věřit ve svaté. Zejména Indie je obzvlášť požehnaná, protože cokoliv máme, je od svatých, třebaže je to velmi odchýlené a také dost strnulé. Ale vědění přišlo od svatých, od mahárišů a od velkých proroků. Další dobrou věcí ohledně Indů je, že jejich náboženství není organizované, neexistuje žádná organizace, která by ho řídila. To je velmi velké požehnání.

Navzdory tomu všechny tyto ideologie přešly také ve védách do jistého druhu mentální máje (iluze), a proto máme Arja Samadž a všechny tyto věci, které jsou velmi obtížné. Chci říct, pokud potkáte jakéhokoliv Arja Samadž, nevíte, jak s takovýmto člověkem jednat; neustále mluví, mluví - Bůh ví, takové vědění. Ale on toho bodu nedosáhl a je spokojený s tím, co četl, neustále příliš čte. To je, co řekl Kabír: "Padi padi pandita murkh bhajo" - "Přílišným čtením, se dokonce i panditové stávají hloupými." Dřív jsem se divila - Jak je to možné? Ale nyní jsem mnoho takových potkala. Takže jde o to, že čtením nemůžete poznat to konečné. Řekněme, že je tu doktor a dá vám lék proti bolesti hlavy, a řekne: "Vezměte si Anacin." Takže si čtete recept, "Anacin, vezměte si Anacin, vezměte si Anacin" - bolest hlavy se zvýší nebo sníží? Musíte si lék vzít.

A toto je napsáno ve védách, že musíte najít sami sebe. Stejně tak, částí véd jsou Upanišády; ve všech částech Upanišád není nic jiného, než "najděte sami sebe". Dokonce když se podíváte na "Pátandžálí šástru", úplně na začátku, nepatrný kousek toho je vjájama, chci říct, jsou tam aštanga. Velice malinký kousek je tak zvaný fyzický problém, se kterým si museli poradit. V Sahadža józe to také používáme, ale na základě porozumění, kde je problém; ne tak, že všichni se dávají na cvičení a dostanou infarkt a všechny druhy problémů, teplotu, vysoký krevní tlak. Někdy je to nízký krevní tlak, někdy vysoký krevní tlak, a přijdou a říkají mi: "Matko, cvičíme jógu a podívej..." Nejsme pouze fyzickou bytostí, nejsme pouze psychickou bytostí, ani emocionální bytostí, ale jsme duchovní bytostí. A druhý typ pohybu, který v této zemi máme, je bhakti. Bhakti je v pořádku, chození do chrámu, ale to také začíná upadat tím, že nerozumějí, co je to bhakti. Krišna v Gítě řekl - musíte vědět, že Šrí Krišna byl diplomat, nebyl matkou, a věděl, jaké jsou lidské bytosti. Chtěl, aby se motali, dokud nenajdou pravdu, protože nikdo nechce přímočaré prohlášení.

Obzvlášť v té době to řekl pouze Ardžunovi. Řekl jim tři věci, ve kterých můžete vidět Jeho diplomacii, pokud dokážete vidět mezi řádky. Zaprvé řekl, že musíte získat gjána. Nebyl dobrým obchodníkem, protože obchodník vám nikdy neřekne nejlepší věc jako první, ale On řekl, že byste se měli dát na gjánu. Tak to je. "Gjána" znamená vědění ve vašem centrálním nervovém systému. Ale jako druhou věc řekl, že byste měli dělat bhakti, "Jakýkoliv plod nebo květ nebo vodu mi dáte, vezmu ji, ale musíte dělat bhakti, které je ananja." Pokud znáte sanskrt, "ananja" znamená, když nejste ten druhý, když jste realizovanou duší. Jestliže nejste spojení, jak můžete mít bhakti? Mnoho lidí si stěžuje: "Matko, postil jsem se, dělal jsem toto, dělal jsem tamto, a podívej se na můj stav.

Je ze mne troska." Není to chyba Boha, ještě nejste připojení. Je to jednoduché jako telefon. Pokud telefon není připojený, k čemu je telefonování? Zničíte telefon. Takže bhakti bez spojení je špatné, proto Krišna řekl: "Jóga kšéma vam aham" - "Nejprve jóga, pak kšéma." Nejprve musíte dosáhnout svého spojení (jógy) a pak přijde blahobyt; jinak se to nevypracuje. Velmi jemně dal jógu na první místo. Proč neřekl: "Kšéma - jóga" ? Takže o bhakti řekl toto.

O karmě řekl: "Dělejte všechnu práci a položte ji k lotosovým chodidlům Boha Všemohoucího." To je nemožné. Mnoho lidí říká: "Matko, všechnu svoji práci pokládám k lotosovým chodidlům Boha," dokonce, myslím, i vraždy. Je to jenom mentální myšlenka, že: "Pokládám to k lotosovým chodidlům Boha." Nemůžete, protože nejste na té úrovni. Ale řekněme, sahadža jogín mi neřekne: "Zvedám Kundaliní," řekne: "Matko, nestoupá, nepřichází," mluví ve třetí osobě. Řekne: "Tudy to nepůjde" - ve třetí osobě, protože tam už více není. Takže toto je karma, automaticky je u lotosových chodidel Boha Všemohoucího. On všechno dělá. My jsme pouhými nástroji.

Řekněme, že tento nástroj řekne: "Já mluvím," nepřijmete to. Stejným způsobem, když říkáme, že "Pokládám svoji..." jako kdyby si brali nějaký náklad a pokládali ho k lotosovým chodidlům Boha - ne. Je to automatické, je to spontánní. Neboli sahadž. Je to vrozené. Všichni jste získali tuto sílu uvnitř vás. Existují knihy, které popisují Kundaliní jako velice nebezpečnou věc. Je to naprostý nesmysl, to vám povím. Byla jsem mezi tolika národy, tolik lidí dostalo realizaci a nemají ani náznak nějakých problémů. Naopak, ve všech směrech se zlepšili.

Lidé se ze dne na den vzdali drog, svých špatných zvyků. Lidé byli ze dne na den vyléčeni. Nic nedělám. Chci říct, můžete si myslet, že něco dělám - nedělám, vaše vlastní Kundaliní to vypracovává. Je velmi překvapující, jak pracuje, a jak vám pomáhá; protože je vaší matkou, vaší vlastní matkou a všechno o vás ví. Je to všechno v ní nahráno, můžete říct. Je umístěna v tři a půl závitech, je to tak kvůli jistému matematickému vzorci - a když stoupá, může po sobě zanechat trochu tepla, kvůli drobnému, můžeme říct, zápasu, který musí podstoupit. Někdy je v některých lidech vytvořeno trochu tepla. Řekněme, že jste pacientem trpícím na játra, pak můžete ve svých rukách cítit trochu tepla, to je vše. Ale všichni máte tuto Kundaliní a ona je čistým přáním uvnitř vás.

Víte, že je v ekonomii zákon, že obecně nejsou potřeby uspokojitelné. Dnes chceme dům, zítra auto, a pozítří pak vrtulník a takto to pořád pokračuje. Když to nemáme, tak o to usilujeme, a když to máme, tak se tím netěšíme. Je to ale čisté přání, které musí být zajedno s touto všepronikající silou Božské lásky. Dokonce ani nepomyslíme, že taková síla existuje, bereme ji jako samozřejmost. Vidíme všechny výtvory, vidíme nádherné květiny, vidíme, jak se z malého semínka stává velký strom. Podívejte se na oči, jsou takovými nádhernými kamerami - kdo je vytvořil? Kdo nás vyvinul do tohoto stavu? Co je to za sílu, která z nás vytvořila lidské bytosti? Nikdy na to nechceme přijít, protože věda nedokáže vysvětlit, jak klíčí semeno, jak jsme se stali lidskými bytostmi.

Takže do tohoto bodu je to v pořádku, za ním to nechceme zjistit. Takže Bůh Všemohoucí rozprostřel tuto nádhernou čaitanju, tuto Brahmačaitanju, všude kolem. Když to říkám, musíte to zkusit a pak mi říct, jestli to tak je nebo ne. Ale říct pouze "ne", znamená, že se zříkáte šance získat spojení s touto životodárnou silou. Tato životodárná síla nás bezpochyby rozvinula, všechno zařídila, všechno vytvořila, vše navibrovala. Sjednocuje, omezuje a kromě toho vás především miluje. Takže přemýšlí, jak dalece s vámi zajít. Je to tak nádherná síla, prostupující vším, každým atomem a každou živou květinou, každou živou bytostí. Pracuje tak nádherně, že dokonce ani necítíme její jemnost. Dokonce ani nevidíme vykvétat květinu, rozkvétání, otevírání, nevidíme to.

Prostě rozkvete a řekneme: "Ó, dnes je tu květ." Je to tak jemné, tak krásné, že dokonce ani žádným způsobem necítíme její existenci, ale ona existuje. A dokud s touto silou nejsme spojeni, nemůžeme poznat úplnou skutečnost, protože Duch uvnitř nás není v naší pozornosti. Je svědkem naší pozornosti. Ale jakmile tato Kundaliní vzestoupí, prochází šesti centry, proniká touto fontanelní oblastí, což je uskutečněním křestu, a pak Duch přichází do naší pozornosti jako světlo. A naše nervy získávají nový rozměr, díky kterému se stáváme, stáváme se - opět říkám, že se stáváme, není to jen přednáška, není to jen chvástání se, není to nějaký druh osvědčení - vy se skutečně stáváte kolektivně vědomí: sámuhik četana. Můžete vnímat ostatní. Na konečcích prstů můžete vnímat - je tu pět, šest a sedm center nalevo a sedm center napravo. Těchto sedm center představuje vaši emocionální stránku a tyto vaši fyzickou a mentální stránku. Můžete vnímat centra všech lidí.

Když léčíme lidi, léčíme strom z vnějšku, můžeme říct, že léčíme listy. Ale pokud máte opravdu strom vyléčit, musíte jít ke kořenům, a já hovořím o kořenech uvnitř nás, o Stromu života, který je uvnitř nás. Budete překvapeni, že dokonce Mohammed Sáhib popisoval kjámu - "kjáma" znamená čas vzkříšení. "Když přijde čas vzkříšení, vaše ruce promluví a budou proti vám svědčit." Všichni o tomto čase mluvili, o Posledním soudu, a že tato Kali juga dá vzniknout Satja juze. Ale jde o to, kolik lidí je ochotno to přijmout. Tisíce a tisíce půjdou na nějaký druh bláznivého, šíleného místa, ale ne za skutečností. Potřebujete jistý druh božské inteligence, myslím, abyste tomu rozuměli. Budete překvapeni, zjistila jsem, že Rusko je pro to nanejvýš vnímavou zemí, protože nejsou tolik materialističtí. Neměli tento druh svobody a podobně, ale měli svobodu jít dovnitř.

Jsou to velice introspektivní lidé, dokonce i jejich spisovatelé, vždy jsem je četla, Tolstého a ostatní. Všichni jsou velice introspektivní a jsou - budete překvapeni, že vždy zajistíme velký stadion, a přesto je mnoho lidí, kteří sedí venku. Přinejmenším na jednom místě, které se nazývá Togliatti, je 22 tisíc sahadža jogínů. A když jsem tam byla, tak došlo ke státnímu převratu, tak jsem řekla: "Nejste znepokojení?" Řekl: "Matko, k čemu se znepokojovat? Jsme v království Boha, nepatříme tomuto království." Po celém světě se dějí tak krásné věci. My, Indové, máme jiné problémy, jsme velice podmínění. Máme před sebou takové vzory, ale nikdy o ně neusilujeme. Budeme uctívat Rámu, budeme uctívat gurua, ale co jste získali uvnitř sebe?

K něčemu se upínáte, ale co takhle něco mít? To je Sahadža jóga. Dokud nepoznáte sami sebe, nepoznáte Šrí Rámu, nepoznáte nikoho. Onehdy jsem viděla jednu knihu o Sahadža józe, kterou napsal nějaký bláznivý člověk. Popírá existenci Krišny, popírá existenci Rámy, popírá existenci Ježíše, všech. Řekla jsem, takový bláznivý člověk, je to velice nevědecké, bez toho, abyste to vypátrali, jak to můžete říct? Říkáte to jen tak, bez toho, abyste to vypátrali. Řekněme, že nikdy nepřijdu do Madrásu a začnu Madrás popisovat. Jak mě nazvete? Stejným způsobem mnoho lidí psalo o Bohu, protože neexistuje zákon, který by jim to zakazoval, můžou napsat jakýkoliv nesmysl.

Ale dokud nepochopíme pravdu, nepoznáme, kdo je falešný guru a kdo ne. Například se mě můžete zeptat: "Matko, je to falešný guru, je to falešný guru?" Měla bych říct - proč mi věříte? Předpokládejme, že řeknu, že není, tak se se mnou začnete přít. Když řeknu, že je, pak mi uvěříte. To není nutné. Sami budete vědět a prostřednictvím toho poznáte absolutní pravdu, protože váš Duch je absolutní. Dává absolutní pravdu. Zítra vám povím víc o Duchu, myslím, že pro dnešek to stačí. Měli bychom mít... Pokud budete chtít, můžeme si udělat seberealizační cvičení.

Nezabere to žádný čas. Hlavní je, abyste byli připravení a jen o to požádali, a všichni to získáte. Samozřejmě máte v hlavách otázky. Posledně, když jsem přijela do Madrásu, strávili jsme celý čas odpovídáním na otázky, otázky, otázky, otázky. Ale nyní bych vás požádala, pokud máte nějaké otázky, abyste je odložili stranou a můžete je napsat. Zítra všechny vaše otázky zodpovím, ale prosím, právě teď, jestli je to možné, se pokuste získat svoji realizaci. Mnohokrát vám děkuji. Řekla bych, že pokud chcete jít na pět minut ven, můžete jít a pak se vrátit, to je v pořádku - ale nemluvte, to je vše. Neřekla jsem vám o třetím druhu pohybu, který v naší zemi máme, což je Náth Panthis. Džinisté mají Ádi Nátha a od toho začaly odchylky.

Jeden guru měl předat vědění pouze jednomu člověku - jako Džanaka měl pouze Načikétu, až do dob Gjánéšvary, což bylo ve dvanáctém století. Gjánéšvara byl učedníkem svého vlastního bratra Nivritinátha, a mnoho trpěli. A požádal Nivritinátha o jedno svolení: "Dovol mi veřejnosti odkrýt pravdu. Jen jim o tom řeknu, nic nebudu dělat, jen jim o tom řeknu." Protože před třinácti, čtrnácti tisíci lety Márkandéja popsal Kundaliní. Pak přišel Ádi Šankaračárja a popsal Kundaliní, ale všechno v sanskrtu. A sanskrtské vědění nebylo přístupné běžné veřejnosti a ti, kteří znali sanskrt, nechtěli sebepoznání. A tak bylo toto vědění po celý čas udržováno v tajnosti. Ale on o to požádal a pak napsal "Gjanéšvarí". "Gjanéšvarí" není nic jiného než druh "Gíty" v maráthi, kterou rozšířil a ozdobil množstvím poezie.

V šesté kapitole "Gjanéšvarí" popisuje Kundaliní velice jasně. A tato šestá kapitola také byla znehodnocena, ale byla nazývána jako "nišidha", "která nemá být čtena", lidmi zodpovědnými za náboženství, zodpovědnými za náš takzvaný vzestup. A řekli: "Toto nesmíte číst, jinak budete mít potíže." Takže tato kapitola byla uzavřena a nikdo se o ni nic nesnažil zjistit. Ale pak se rozšířili Náth Panthis. Od nich máme Kabíra, máme Nanaka. Mluvil o "khalis", Nának mluvil o "khalis". "Khalis" znamená čistý, nirmal. Sahadža jogíni jsou nirmal. Pokud někdo něco zneužije, je to jasně vidět; a světci takoví být nemůžou.

"Khalis" lidé takoví být nemůžou, nemůžou mít násilí. Je to láska. Je to láska, která je naprosto nirvadž, bez jakékoliv náhrady. Je to láska, která je neohraničená. Je to láska, která nečiní žádné rozdíly. Jako energie, která stoupá v rostlině, nebo můžeme říct, že stoupá míza, jde do různých oblastí: do listů stejně jako do větví, do květů, do plodů a vrací se zpátky. Není připoutaná. Když se k něčemu připoutáte, je to pro danou oblast smrt, stejně jako je to smrt pro ten strom. Takže musíme pochopit, že všechny tyto velké inkarnace, proroci a zvěstovatelé, všichni přišli na tuto zemi na stejném Stromu života. Musíte věřit ve všechny.

Pokud v ně začnete věřit, v ně všechny, kde pak budou spory? Ale ti, kteří věří pouze v jednoho, se musí přít. A proto nás nemají rádi, protože my věříme ve všechny - není to jen víra, ale je to pravda. Tady vám musím říct, že je to živoucí proces evoluce, poslední průlom. Nemuseli jste nic dělat, abyste se stali lidskými bytostmi; stejným způsobem je toto bez úsilí, je to sahadž. Pouze vám řeknu, jak vyživit svá centra tak, aby mohla Kundaliní snadněji stoupat. Je to velmi jednoduché, všichni byste to měli udělat. Nemusíte se dívat na ostatní, ale dívejte se sami na sebe. Bylo by dobré, kdybyste si sundali boty, abyste cítili Matku Zemi, protože ona je tou, která neustále nasává naše problémy. Zejména tato naše země jógy.

Nevíme, jak jsme významní, že jsme se narodili v této zemi. Udělali v ní chaos, to nevadí. Pokud měl přijít král Ráma, přišel sem, ne politický styl, ale duchovní styl. Myslím, že to stále padá. Můžete to trošku upevnit - padá to. Teď je to v pořádku, myslím, že to vydrží. Teď je to lepší. Děkuji. Jak jsem vám řekla, nemusíte nic dělat. Nemusíte zastavovat svoje myšlenky, nemusíte vynakládat žádné úsilí, říkat nějaké mantry, nic.

Kundaliní tu práci udělá; velice dobře vás zná a zvládne to. Jen v sebe mějte víru, plnou jistotu, že získáte realizaci. Cítit se vinen je něco nepřirozeného, myslím, že to přichází od lidí, kteří nám říkají: "Jsi hříšník, jsi toto, jsi tamto." V mých očích není nikdo hříšník. Jste ztracení, jste nevědomí, ale nikdo není hříšník. Takže musíte pochopit, že si musíme sami sebe vážit, protože jsme nádherní, jsme báječní. Protože nejsme spojení, tak tak vypadáme, opovrhujeme sami sebou, druzí mohou opovrhovat vámi. Ale jste lidskými bytostmi, jste zosobněním evoluce. A nyní je potřeba drobný posun, jednoduše jako spojení, a jsem si jistá, že poznáte sami sebe. Po probuzení Kundaliní a proniknutí skrze fontanelní oblast, začnete ve svých rukách cítit chladný vánek.

To je čaitanja. V Bibli je popisována jako chladný vánek Ducha Svatého, v Koránu jako Ruh. Potom také začnete cítit chladný vánek vycházející z vaší hlavy. Jakmile začne z vaší hlavy vycházet chladný vánek, budete se cítit velice uvolnění, pokojní a radostní. Tolik lidí se potom prostě začne smát. Měli byste se smát. Tento svět je vytvořen pro vaše potěšení a nyní musíte vstoupit do království Boha, jež není pouze radostí, není pouze mírem, ale je to požehnaný stav. Jestli na sobě máte cokoliv obtaženého nebo těsného kolem krku, bude lepší, když to trochu uvolníte, pokud se cítíte nepříjemně. Také pokud si chcete sundat brýle... později, až vám řeknu, teď ne; protože si zavřete oči, a pak je nebudete otevírat. Takže nejprve vám ukážeme, jak si pomůžete.

Díky tomuto také poznáte svoje centra. Budeme pracovat na levé straně. Nejprve musíte položit levou ruku takto směrem ke mně, na klín, pohodlně. Představte si, nemusíte chodit do Himalájí, dělat nic podobného, jen pohodlně na své židli získáte svoji realizaci - to je vaše právo. Takto položte levou ruku. Teď musíme pravou rukou vyživovat naše centra na levé straně. Nejprve položíme ruku na srdce, protože zde se odráží Duch. Duch je odrazem Boha Všemohoucího. Pak půjdeme dolů na vrchní část břicha na levé straně. Toto je centrum našeho mistrovství.

Pokud jste Duchem, stáváte se svým vlastním mistrem, nepotřebujete žádného mistra, vede vás váš Duch. Pak půjdeme dolů na spodní část břicha na levé straně. Zde získáváte vědění prostřednictvím svého centrálního nervového systému. Toto centrum je tím, které vám dává čisté vědění - Šuddha vidja, které pracuje prostřednictvím vašeho centrálního nervového systému. Pak zvedněte svoji ruku opět nahoru na levou stranu břicha a zatlačte. Tady je centrum Guru principu. Řekněme, že jste byli u nějakého falešného gurua apod., může se to napravit. Pak musíte položit pravou ruku na srdce. Nyní položte ruku na přechod mezi krkem a ramenem, a měli byste otočit hlavu doprava. Toto je centrum, které je napadáno, když se cítíte vinni, a když se cítíte vinni, toto centrum je napadeno.

Dává vám mnoho nemocí - jednou z nich je angína a také zánět obratlů; a tolik věcí se stane orgánům, protože se stávají letargickými. Takže nejlepší věcí je, dát si sem pořádně ruku a posunout hlavu takto na pravou stranu. Pak, prosím, dejte pravou ruku na vrch čela a skloňte hlavu, co nejvíc je to možné. Toto je centrum, kde musíte odpustit, odpustit každému bez přemýšlení, komu máte odpustit. Jestli odpustíte nebo neodpustíte, nic neděláte, je to vaše myšlenka. Ale když neodpustíte, pak nahráváte do špatných rukou. Takže, prosím, položte takto ruku, toto je centrum odpuštění; bez přemýšlení o lidech, kterým máte odpustit nebo kteří vám ublížili. Toto je velice důležitá ádžňa čakra, protože je velmi úzká, a jestliže neodpustíte, nebude stoupat, Kundaliní nemůže projít. Jen odpusťte. Nyní posuňte pravou ruku na zadní část hlavy.

Budeme to dělat později, jen vám ukazuji čakry. Teď tato zadní strana... protože se po celý čas cítíte vinni, myslíte, že jste něco udělali špatně nebo podobně, takže nejlepší věcí je prostě poprosit o odpuštění Božskou sílu, to centrum je tady. Nyní plně propněte ruku a střed dlaně položte na vrchol fontanelní kosti, která byla ve vašem dětství měkká, "talú", tady - zrovna tam. Propněte prsty pěkně dozadu, propněte je dozadu, abyste vyvinuli správný tlak na kůži na temeni, správný tlak na kůži na temeni. Nyní prosím sehněte hlavu, jak je to jen možné. A teď pomalu kůží na hlavě pohybujte, sedmkrát ve směru hodinových ručiček - ve směru hodinových ručiček. S tlakem: propněte své ruce dozadu, jinak - chci říct své prsty - jinak tam nebude tlak. To je všechno! Takže, nejprve musíme mít důvěru sami v sebe, musíme mít úctu a lásku sami k sobě. Takže nyní takto položíme levou ruku, obě nohy dejte vedle sebe a zavřete nyní oči.

Položte, prosím, pravou ruku na srdce položte pravou ruku na srdce. Tady je centrum Ducha, zde sídlí Duch. Můžete se mě třikrát zeptat, jako byste se ptali počítače, ve svém srdci. Můžete mě nazývat "Šrí Mátadží" nebo "Matko", jak budete chtít. "Matko, jsem Duch?" Zeptejte se třikrát: "Matko, jsem Duch? Šrí Mátadží, jsem Duch?" Pokud jste Duchem, stanete se svým pánem. Takže nyní prosím dejte svoji ruku vlevo na vrchní část břicha a silně zatlačte. Nyní se zde opět zeptejte: "Matko, jsem svým vlastním mistrem?"

Zeptejte se třikrát, prosím, ve svém srdci, s plnou důvěrou: "Matko, jsem svým vlastním mistrem?" Jste, ale jen se mě ptáte, respektuji vaši svobodu a nemohu vám vnutit čisté vědění, musíte o něj požádat. Takže nyní musíte položit pravou ruku na spodní část břicha, silně zatlačit, na levé straně. Tady teď musíte říct: "Matko, prosím, dej mi čisté vědění - Šuddha Vidja." "Šrí Mátadží, dej mi Šuddha Vidja." Řekněte to, prosím, šestkrát, protože toto centrum má šest okvětních lístků - centrum svádhištány. "Prosím, dej mi Šuddha Vidja - čisté vědění." Jakmile požádáte o čisté vědění, Kundaliní začne stoupat. Ale musíte jejímu pohybu napomoct tím, že se sebedůvěrou otevřete vyšší čakry. Takže teď prosím zvedněte pravou ruku na vrchní část břicha a silně zatlačte, na levé straně.

Nechte nohy vedle sebe. Tady musíte desetkrát s plnou sebedůvěrou říct: "Matko, já jsem svým vlastním mistrem." Řekněte to, prosím: "Matko, já jsem svým vlastním mistrem." "Matko, já jsem svým vlastním guruem." Protože všichni velcí guruové, satguruové, vytvořili toto centrum pro váš vzestup. A matka vždy chce, aby její děti nejen měly to, co má ona, ale aby měly mnohem víc, než ona. Tady, na úplném začátku vám musím říct, že nejste tímto tělem, touto myslí, emocemi, ani podmíněnostmi nebo egem, ale jste čistým Duchem. Takže zvedněte pravou ruku na srdce a s plnou důvěrou dvanáctkrát řekněte: "Matko, jsem čistý Duch. Matko, jsem čistý Duch" - dvanáctkrát - "Šrí Mátadží, jsem Šuddha átma." Musíte to říct s plnou důvěrou.

Musím vám říct, že tato všepronikající Božská síla je oceánem vědění, je oceánem milosrdenství a blaženosti. Musíte s plnou sebedůvěrou říct: "Matko, nejsem vůbec ničím vinen" - řekněte to, prosím, šestnáctkrát. Musíte říct: "Šrí Mátadží, jsem nirdóša, jsem nirdóša." Řekněte to, prosím, šestnáctkrát. Řekněte to pro moje uspokojení. Nyní zvedněte svoji pravou ruku na vrchol čela. Jak jsem vám již řekla, ať už odpustíte nebo neodpustíte, nic neděláte. Takže nyní skloňte hlavu, co nejvíc je to možné, a zde, s plnou pokorou, každému odpusťte! Jednoduše odpusťte! Nepřemýšlejte o lidech, kteří vás trápili, ale jen jim odpusťte.

To je nejlepší způsob, jak se můžete zbavit tohoto břemena, protože nahráváte do špatných rukou, jestliže neodpustíte. Řekněte to ze svého srdce, nezáleží na tom, kolikrát, ale řekněte to ze svého srdce, prosím. Mnoho lidí říká, že je velice obtížné, někomu odpustit. Co je na tom obtížného? Jde jen o to, to říct. Dejte svoji pravou ruku dozadu na zadní stranu hlavy a zakloňte hlavu, jak je to jen možné, zakloňte, jak je to jen možné. Zde musíte opět ze svého srdce říct: "Božská sílo, pokud jsem učinil cokoliv špatně, prosím, odpusť mi. Pokud jsem učinil nevědomě cokoliv špatně, prosím, odpusť mi." Také toto řekněte ze svého srdce. Nyní plně propněte svou dlaň a položte střed své dlaně na vrchol fontanelní kosti, která byla ve vašem dětství měkká.

Nazývá se "talú", "talavjam" v sanskrtu. Nyní, skloňte hlavu, jak je to jen možné, skloňte ji. A nyní se, prosím, pokuste pohybovat kůží na temeni pod tlakem tím, že tlačíte své prsty ven. Tlačte své prsty, prosím, ven, pěkně zatlačte a sedmkrát otočte ve směru hodinových ručiček. Zde opět - nemohu vám vnutit seberealizaci, musíte o ni požádat. Takže zatímco pohybujete rukou, řekněte sedmkrát: "Matko, prosím, dej mi moji seberealizaci. "Matko, prosím, dej mi moji seberealizaci." Nikomu ji nemohu vnutit. Dejte, prosím, ruce dolů. Velice pomalu otevřete oči.

Tady, dejte svoji pravou ruku takto směrem ke mně a skloňte hlavu a vnímejte sami pro sebe, jestli z vaší hlavy vystupuje chladný vánek. Vnímejte fontanelní kost. Někteří lidé jej vnímají velmi blízko, ale ne na vrcholu, trochu mimo, nebo někteří lidé ho vnímají jako silný proud, docela daleko. Možná může být také horký, může být také horký. Pokud jste neodpustili, určitě bude horký. Nyní, prosím položte svoji levou ruku směrem ke mně. Nyní opět skloňte hlavu a sami vnímejte, jestli z vaší hlavy vychází chladný nebo horký vánek. Sami musíte dosvědčit, že Sahadža jóga je stanutí se něčím; jak jsem vám řekla, žádné osvědčení neexistuje. Někteří lidé možná cítí horký vánek, to nevadí. Nyní prosím, dejte svoji pravou ruku směrem ke mně a skloňte hlavu a opět sami vnímejte.

Nedávejte ji na vrchol hlavy, trochu nad, pak to budete cítit, trochu nad. Nyní prosím dejte ruce takto směrem ke mně, dívejte se na mě a nepřemýšlejte. Dokážete to. Všichni, kteří cítili chladný vánek na konečcích prstů, nebo i horký, a ti, kteří ho cítili buď na rukách nebo z fontanelní oblasti, nebo z obou míst, prosím, zvedněte obě ruce. Prosím, zvedněte obě ruce. Nechť vám Bůh žehná. Většina z vás to získala. Většina z vás to získala. Nediskutujte o tom, protože když přejdete na mentální úroveň, ztratíte to. Jen se tím těšte.

Přála bych si, abyste dnes pokojně spali. Zítra opět zavolejte svým přátelům a lidem; protože za to nemůžete platit a nic nemusíte dělat, je to vaše vlastní - jako Matka Země neví, jak vyúčtovat semenům, že je nechala vzklíčit. Takže toto je také vaše purva punja. Ti, kteří to nezískali, to získají zítra. Takže prosím všechny z vás, abyste přišli, a prosím zavolejte svým přátelům. Je to ta nejlepší věc, kterou někomu můžete dát. Na to jsme čekali. Nechť vám Bůh žehná. Přijďte, prosím, zítra. Vysvětlím vám podstatu Ducha, co je to Duch.

Podívejte, co jsem zrovna teď udělala. Chce, abyste všichni přišli a získali daršan. Nyní sedím před vámi, to je daršan. Není potřeba se dotýkat mých Chodidel, není třeba. Zítra uvidíme. Tolik si přejete to udělat, není potřeba to dělat. Na to máme politiky. Zítra, prosím, doneste své dotazy. Prosím, vzneste své dotazy, ráda je zodpovím.